"""Content for 🎓 Thi chứng chỉ (game/certificates.py): certificate groups, the
lesson notes read while studying, a small practice quiz (checked in the browser,
separate from the exam bank) and the exam bank (the answer key stays on the server).

Each group covers related hired jobs; holding it raises the hire chance there
(employment._evaluate). Facts come from the game's own rules (career plugins,
employment_content, tax_payroll.RULES…). Everything is a simplified GAME rule
written in xu, not professional, medical, tax or legal advice.

Shapes:
* GROUPS: {id, emoji, name, short, issuer, careers, fee, intro, notes[str],
  practice[{text, options[{id, label}], answer, why}], bank[same, plus id]},
  optional hire=False + perk (a craft certificate for a job without an interview: the perk replaces the hire bonus).
"""
from __future__ import annotations


def _q(qid, text, options, answer, why):
    return dict(id=qid, text=text, options=[dict(id=k, label=v) for k, v in options], answer=answer, why=why)


def _p(text, options, answer, why):
    return dict(text=text, options=[dict(id=k, label=v) for k, v in options], answer=answer, why=why)


GROUPS = [
    dict(
        id='work_safety', emoji='🦺', name='Chứng chỉ An toàn lao động', short='An toàn lao động',
        issuer='Trung tâm dạy nghề phường (lớp giả lập)', careers=('delivery', 'repair'), fee=15,
        intro='An toàn điện khi sửa đồ, an toàn đường sá khi giao hàng, giữ đồ và tiền của khách cho đúng.',
        notes=[
            'Máy điện: rút điện trước khi mở. Quạt còn tụ giữ điện, phải xả tụ bằng điện trở. Nồi cơm chờ mâm nhiệt nguội. Điện thoại, laptop tắt nguồn và ngắt cáp pin.',
            'Dây nguồn chảy nhựa, có mùi khét: báo khách ngưng dùng, thay dây đúng loại, đo cách điện trước khi giao. Băng keo không cứu được dây đã chảy.',
            'Đo trước, thay sau. Báo giá rõ trước khi sửa; sửa tốn gần bằng mua mới thì nói thật để khách chọn.',
            'Đồ của khách là của khách: không mở ảnh, tin nhắn. Phiếu nhận ghi tình trạng máy (vết nứt, trầy) và phụ kiện đi kèm.',
            'Xe giao hàng chở tối đa 20 kg. Hàng dễ vỡ lót xốp hơi, đồ lạnh có túi giữ lạnh, trời mưa bọc túi chống nước.',
            'Đường ngập, mưa to: tấp vào chỗ an toàn, báo điều phối và khách giờ giao mới. Không đơn nào đáng để liều.',
            'Tiền thu hộ (COD): đếm trước mặt khách, thối đủ tới từng xu, ghi phiếu. Túi tiền quá 250 xu thì về bưu cục nộp trước.',
            'Thư bảo đảm giao tận tay người nhận, không gửi bảo vệ. Địa chỉ thiếu: gọi, nhắn khách, hỏi quy định giữ hàng, báo điều phối.',
        ],
        practice=[
            _p('Sửa xe đạp: bước an toàn trước khi tháo bánh?',
               [('a', 'Dựng xe lên giá, khóa bánh'), ('b', 'Dựng nghiêng vào tường'), ('c', 'Đặt nằm dưới sàn')], 'a',
               'Xe không dựng giá dễ đổ, xước thêm một vệt mới.'),
            _p('Đơn thu hộ 327 xu, khách đưa tờ 500 xu. Bạn thối bao nhiêu?',
               [('a', '170 xu cho chẵn'), ('b', '173 xu'), ('c', '183 xu')], 'b', '500 − 327 = 173 xu, đếm trước mặt khách.'),
            _p('Đơn có hũ sữa chua. Bạn mang theo gì?',
               [('a', 'Không cần gì thêm'), ('b', 'Xốp hơi'), ('c', 'Túi giữ lạnh')], 'c', 'Đồ lạnh cần túi giữ lạnh cho tới tay khách.'),
            _p('Máy nào phải xả tụ trước khi mở?',
               [('a', 'Quạt đứng'), ('b', 'Tai nghe'), ('c', 'Xe đạp')], 'a', 'Tụ khởi động của quạt vẫn giữ điện sau khi rút phích.'),
        ],
        bank=[
            _q('ws_fan', 'Khách mang tới cái quạt đứng không quay. Trước khi mở hộp tụ, bạn làm gì?',
               [('a', 'Rút điện rồi xả tụ bằng điện trở'), ('b', 'Cắm điện nghe thử mô-tơ rồi mở luôn'),
                ('c', 'Mở nhanh vì quạt nhỏ, điện yếu')], 'a', 'Tụ quạt còn giữ điện sau khi rút phích; phải xả tụ trước khi chạm vào.'),
            _q('ws_cooker', 'Nồi cơm điện khách vừa mang tới còn ấm tay. Bạn mở thế nào?',
               [('a', 'Lật đáy ngay cho kịp'), ('b', 'Rút điện, chờ mâm nhiệt nguội rồi mới lật đáy'),
                ('c', 'Đeo găng vải, mở khi còn cắm điện')], 'b', 'Mâm nhiệt còn nóng gây bỏng; nồi phải rút điện và nguội hẳn.'),
            _q('ws_phone', 'Thay pin điện thoại: bước an toàn đầu tiên?',
               [('a', 'Cắm sạc cho máy khỏi sập nguồn'), ('b', 'Tách màn khi máy còn mở để xem cảm ứng'),
                ('c', 'Tắt nguồn và ngắt cáp pin trước khi tách màn')], 'c', 'Còn nguồn mà tách màn dễ tóe lửa ở cáp pin.'),
            _q('ws_cord', 'Dây nguồn nồi cơm chảy nhựa, có mùi khét.',
               [('a', 'Báo khách ngưng dùng, thay dây đúng loại, đo cách điện trước khi giao'), ('b', 'Quấn băng keo thật kín'),
                ('c', 'Trả máy, dặn khách dùng tạm')], 'a', 'Dây đã chảy nhựa quấn băng keo vẫn có thể chập cháy.'),
            _q('ws_quote', 'Thay mô-tơ quạt tốn gần bằng mua quạt mới. Bạn làm gì?',
               [('a', 'Cứ sửa rồi báo giá sau'), ('b', 'Báo giá rõ, nói thật mua mới có thể hợp hơn, để khách chọn'),
                ('c', 'Nói là không sửa được')], 'b', 'Khách có quyền chọn khi biết đủ thông tin.'),
            _q('ws_data', 'Điện thoại khách gửi thay màn hình không cài khóa.',
               [('a', 'Mở thư viện ảnh để thử cảm ứng'), ('b', 'Cài lại máy cho sạch lỗi'),
                ('c', 'Chỉ làm phần màn hình, không mở ảnh, tin nhắn; ghi tình trạng máy vào phiếu')], 'c',
               'Dữ liệu của khách là riêng tư; cài lại máy làm khách mất hết ảnh.'),
            _q('ws_intake', 'Nhận máy sửa, bạn ghi gì vào phiếu nhận?',
               [('a', 'Tình trạng máy (vết nứt, trầy) và phụ kiện đi kèm'), ('b', 'Chỉ tên và số điện thoại khách'),
                ('c', 'Không cần phiếu, nhớ trong đầu là được')], 'a',
               'Ghi rõ lúc nhận để khi trả máy không ai phải cãi nhau về vết trầy hay cục sạc.'),
            _q('ws_load', 'Xe giao hàng của bưu cục chở tối đa bao nhiêu?',
               [('a', '20 kg'), ('b', '35 kg nếu buộc chặt'), ('c', 'Không giới hạn nếu chạy chậm')], 'a',
               'Quá tải làm xe khó phanh, dễ đổ.'),
            _q('ws_fragile', 'Đơn là một bình thủy tinh. Bạn đóng gói thế nào?',
               [('a', 'Để chung thùng cho gọn'), ('b', 'Lót xốp hơi, chằng riêng'), ('c', 'Cầm tay trong lúc chạy xe')], 'b',
               'Hàng dễ vỡ không lót sẽ vỡ trên đường, khách từ chối nhận.'),
            _q('ws_flood', 'Đường phía trước ngập nửa bánh xe, đơn sắp trễ hẹn.',
               [('a', 'Chạy băng qua cho kịp giờ'), ('b', 'Tắt máy chờ, không báo ai'),
                ('c', 'Tấp vào chỗ an toàn, bọc hàng, báo điều phối và khách giờ giao mới')], 'c',
               'Người về an toàn là đơn quan trọng nhất; báo sớm để khách biết mà chờ.'),
            _q('ws_cod', 'Đơn thu hộ 186 xu, khách đưa tờ 200 xu. Bạn thối bao nhiêu?',
               [('a', '14 xu, đếm trước mặt khách'), ('b', '10 xu cho chẵn'), ('c', '24 xu')], 'a',
               '200 − 186 = 14. Thối thiếu là mất uy tín của cả bưu cục.'),
            _q('ws_codcap', 'Túi tiền thu hộ đã hơn 250 xu, còn một đơn COD nữa.',
               [('a', 'Nhận tiếp, tối nộp một lần'), ('b', 'Về bưu cục nộp tiền trước rồi mới nhận thêm'),
                ('c', 'Gửi tiền nhờ quán quen giữ giùm')], 'b', 'Cầm nhiều tiền mặt trên đường là rủi ro; bưu cục có mức giới hạn.'),
            _q('ws_registered', 'Thư bảo đảm, người nhận đi vắng, bảo vệ chung cư đề nghị nhận giùm.',
               [('a', 'Gửi bảo vệ, chụp ảnh làm bằng'), ('b', 'Bỏ vào hộp thư'), ('c', 'Không gửi bảo vệ; hẹn giao lại, báo điều phối')], 'c',
               'Thư bảo đảm phải giao tận tay người nhận.'),
            _q('ws_address', 'Tới chung cư, đơn thiếu số phòng, khách không nghe máy.',
               [('a', 'Nhắn tin, gọi lại, hỏi bảo vệ quy định giữ hàng, báo điều phối'), ('b', 'Để hàng ở sảnh, chụp ảnh là xong'),
                ('c', 'Báo hủy đơn luôn')], 'a', 'Để hàng ở sảnh dễ mất, người giao phải đền.'),
            _q('ws_rain', 'Trời mưa dầm, đường trơn, còn ba đơn.',
               [('a', 'Chạy nhanh cho xong trước khi mưa to'), ('b', 'Chạy chậm, giữ khoảng cách, bọc hàng bằng túi chống nước'),
                ('c', 'Bỏ túi chống nước cho nhẹ xe')], 'b', 'Mưa làm đường trơn; hàng ướt là khách phàn nàn.'),
        ]),
    dict(
        id='grooming', emoji='✂️', name='Chứng chỉ Chăm sóc tóc & thú cưng', short='Chăm sóc tóc & thú cưng',
        issuer='Hội nghề chăm sóc khu phố (lớp giả lập)', careers=('salon', 'pet_care'), fee=15,
        intro='Hỏi trước làm sau, hóa chất an toàn ở salon, tắm sấy và đọc tín hiệu của chó mèo.',
        notes=[
            'Hỏi trước, làm sau: lịch sử tóc (nhuộm, uốn, duỗi gần đây); với thú cưng là sổ tiêm, dị ứng, da lông.',
            'Chưa có kết quả thử dị ứng thì thử thuốc sau tai trước, hẹn nhuộm từ ngày sau. Da đầu trầy, viêm: hôm đó không thoa hóa chất.',
            'Oxy: cùng tông hoặc tối hơn 10 vol; nâng 1–2 tông 20 vol; nâng 3 tông 30 vol; 40 vol không bao giờ thoa sát da đầu.',
            'Thuốc nhuộm không nâng được màu nhuộm cũ, muốn sáng hơn phải tẩy. Tóc nhuộm hộp: thử một lọn trước khi tẩy. Canh giờ thuốc, quá giờ là tóc khô cháy.',
            'Giữa hai khách: thay khăn, khử khuẩn lược kéo, quét tóc rồi mới mời ngồi.',
            'Tắm chó mèo: nước 36–39 °C. Giống mặt ngắn (Pug, Ba Tư mặt tịt) chỉ sấy nấc mát. Bé sợ thì dừng, quấn khăn, cho nghỉ; không ép.',
            'Móng đen: cắt từng chút ở đầu móng, để sẵn bột cầm máu. Thấy cục u hay bé bỏ ăn: báo chủ, khuyên đi thú y; không tự chẩn đoán, không tự cho thuốc.',
            'Nhận lưu trú: sổ tiêm phải còn hạn tới ngày chủ đón; trên 39,2 °C là sốt, chưa nhận.',
        ],
        practice=[
            _p('Tóc bạc từ một nửa trở lên: bát màu cần gì?',
               [('a', 'Toàn tuýp ánh tro'), ('b', 'Ít nhất một nửa là tuýp nền tự nhiên (x.0)'), ('c', 'Chỉ dùng toner')], 'b',
               'Tóc bạc nhiều cần nền tự nhiên để phủ đều.'),
            _p('Nhuộm, tẩy làm trên tóc thế nào?',
               [('a', 'Tóc khô chưa gội; xả thuốc xong mới gội'), ('b', 'Gội sạch rồi nhuộm khi tóc còn ướt'),
                ('c', 'Xả nước trước khi thoa')], 'a', 'Thuốc thoa trên tóc khô; gội sau khi xả thuốc.'),
            _p('Bé chó liếm mép, ngáp, đuôi kẹp trên bàn tắm nghĩa là gì?',
               [('a', 'Bé đang vui'), ('b', 'Bé buồn ngủ'), ('c', 'Bé đang lo: dỗ hoặc cho nghỉ rồi mới làm tiếp')], 'c',
               'Đó là tín hiệu căng thẳng; đọc tín hiệu trước mỗi bước.'),
            _p('Bé nhảy khỏi bàn, chạy quanh tiệm.',
               [('a', 'Đóng cửa, ngồi thấp, gọi nhỏ hoặc dụ bằng bánh nếu chủ cho'), ('b', 'Đuổi theo chụp lại'),
                ('c', 'Hét lớn cho bé đứng lại')], 'a', 'Đuổi hay chụp làm bé hoảng thêm.'),
        ],
        bank=[
            _q('gr_patch', 'Khách muốn nhuộm, salon chưa có kết quả thử dị ứng của khách.',
               [('a', 'Nhuộm luôn vì khách nói chưa từng bị dị ứng'), ('b', 'Thử thuốc sau tai trước, hẹn nhuộm từ ngày sau'),
                ('c', 'Nhuộm một nửa đầu để thử')], 'b', 'Chưa có kết quả thử dị ứng thì chưa thoa thuốc nhuộm.'),
            _q('gr_scalp', 'Da đầu khách có vết trầy, hơi đỏ. Khách vẫn muốn tẩy hôm nay.',
               [('a', 'Không thoa hóa chất hôm đó, hẹn lại khi da lành'), ('b', 'Tẩy nhanh cho đỡ rát'),
                ('c', 'Bôi kem dưỡng rồi tẩy')], 'a', 'Hóa chất trên da đầu trầy, viêm gây bỏng rát.'),
            _q('gr_vol_same', 'Nhuộm cùng tông hoặc tối hơn màu tóc tự nhiên: dùng oxy nào?',
               [('a', '30 vol (9%)'), ('b', '40 vol (12%)'), ('c', '10 vol (3%)')], 'c', 'Không cần nâng tông thì dùng oxy nhẹ nhất.'),
            _q('gr_vol_40', 'Oxy 40 vol (12%) được dùng thế nào?',
               [('a', 'Không bao giờ thoa sát da đầu'), ('b', 'Dùng cho mọi ca nhuộm cho nhanh'), ('c', 'Thoa sát chân tóc cho lên màu đều')], 'a',
               'Oxy mạnh sát da đầu gây bỏng.'),
            _q('gr_lift', 'Tóc đang nhuộm nâu, khách muốn sáng hơn hai tông. Cách đúng?',
               [('a', 'Nhuộm đè màu sáng hơn'), ('b', 'Phải tẩy, vì thuốc nhuộm không nâng được màu nhuộm cũ'),
                ('c', 'Trộn thuốc nhuộm với oxy 40 vol')], 'b', 'Màu nhuộm cũ chỉ đi ra khi tẩy.'),
            _q('gr_boxdye', 'Tóc khách từng nhuộm hộp ở nhà. Trước khi tẩy?',
               [('a', 'Pha bột tẩy đặc hơn'), ('b', 'Tẩy cả đầu luôn'), ('c', 'Thử một lọn trước')], 'c',
               'Thuốc nhuộm hộp có thể phản ứng với bột tẩy; thử lọn cho biết trước.'),
            _q('gr_timer', 'Thuốc màu đã đủ giờ nhà sản xuất ghi, thợ màu đang bận.',
               [('a', 'Thử một lọn, báo thợ màu, xả đúng giờ'), ('b', 'Để thêm hai mươi phút cho màu đậm'),
                ('c', 'Chờ thợ màu rảnh rồi tính')], 'a', 'Quá giờ thuốc làm tóc khô cháy.'),
            _q('gr_clean', 'Khách vừa đứng dậy, khách mới đã tới cửa.',
               [('a', 'Mời ngồi luôn, lau ghế sơ'), ('b', 'Thay khăn, khử khuẩn lược kéo, quét tóc rồi mới mời ngồi'),
                ('c', 'Dùng lại khăn nếu còn khô')], 'b', 'Sạch sẽ là lời chào đầu tiên của tiệm.'),
            _q('gr_water', 'Nước tắm cho chó mèo nên ở khoảng nào?',
               [('a', 'Nước lạnh cho bé tỉnh'), ('b', 'Càng nóng càng sạch'), ('c', '36–39 °C')], 'c', 'Nước ấm vừa thân nhiệt, không làm bé giật mình.'),
            _q('gr_flatface', 'Sấy cho một bé Pug mặt ngắn.',
               [('a', 'Chỉ sấy nấc mát, để xa mặt'), ('b', 'Sấy nấc nóng cho mau khô'), ('c', 'Chĩa máy thẳng vào mặt cho nhanh')], 'a',
               'Hơi ấm phả vào mặt làm giống mặt ngắn khó thở.'),
            _q('gr_scared', 'Con mèo sợ máy sấy, gồng người và rít lên.',
               [('a', 'Giữ chặt để sấy cho xong'), ('b', 'Tắt máy, cho bé nghỉ, quấn khăn, sấy nhẹ để xa'), ('c', 'Đeo rọ mõm cho bé')], 'b',
               'Không ép một bé đang hoảng; rọ mõm không bao giờ dùng cho mèo.'),
            _q('gr_nails', 'Cắt móng cho chó móng đen, không thấy lòng móng.',
               [('a', 'Cắt một nhát cho gọn'), ('b', 'Cắt sát cho lâu mọc'), ('c', 'Cắt từng chút đầu móng, soi mặt cắt, để sẵn bột cầm máu')], 'c',
               'Cắt sâu chạm lòng móng làm bé đau, chảy máu.'),
            _q('gr_lump', 'Đang tắm, bạn thấy một cục u nhỏ dưới da bé.',
               [('a', 'Báo chủ khi trả bé, khuyên đi bác sĩ thú y; không tự chẩn đoán'), ('b', 'Nói với chủ là u lành, không sao'),
                ('c', 'Im lặng cho chủ khỏi lo')], 'a', 'Người chăm sóc không phải bác sĩ thú y; báo sớm để chủ đưa bé đi khám.'),
            _q('gr_fever', 'Nhận bé lưu trú, nhiệt kế đo 39,6 °C.',
               [('a', 'Nhận, cho bé nằm chỗ mát'), ('b', 'Chưa nhận, mời chủ đưa bé đi khám vì bé đang sốt'),
                ('c', 'Nhận và cho uống thuốc hạ sốt')], 'b', 'Trên 39,2 °C là sốt; không nhận lưu trú, không tự cho thuốc.'),
            _q('gr_vaccine', 'Sổ tiêm của bé còn hạn tới hôm nay, chủ gửi bé ba ngày.',
               [('a', 'Nhận vì hôm nay còn hạn'), ('b', 'Nhận rồi nhắc chủ đi tiêm sau'),
                ('c', 'Chưa nhận: sổ tiêm phải còn hạn tới ngày chủ đón bé')], 'c', 'Bé ở cùng các bé khác suốt thời gian lưu trú.'),
        ]),
    dict(
        id='customer_service', emoji='🎧', name='Chứng chỉ Chăm sóc khách hàng', short='Chăm sóc khách hàng',
        issuer='Trạm Lắng Nghe phối hợp phường (lớp giả lập)', careers=('customer_care', 'pharmacy', 'tour_guide'), fee=20,
        intro='Lắng nghe, hẹn điều mình giữ được, biết mình được làm tới đâu và giữ kín thông tin của khách.',
        notes=[
            'Đọc lịch sử trước khi nghe máy; tóm tắt điều đã biết để khách không phải kể lại từ đầu.',
            'Xác minh mã yêu cầu của chủ đơn trước khi nói chi tiết. Đọc đủ nguồn (đơn, kho, vận chuyển) rồi mới đề nghị phương án.',
            'Hẹn một mốc mình giữ được và gọi lại đúng hẹn. Vụ đang chờ thì gọi cập nhật trong ngày, trước buổi trưa.',
            'Chỉ hứa điều nơi mình làm được (hoàn phí ship, mã bù). Khách đòi ngoài quyền: nói rõ, chuyển người có quyền kèm bản tóm tắt.',
            'Khách giận: xin lỗi vì khách phải chờ, đừng bảo “bình tĩnh lại”. Bị xúc phạm: nhắc nhẹ ranh giới, không cãi lại.',
            'Biết mình được làm tới đâu: ở quầy thuốc không tự đưa liều, không tự chọn thuốc cho trẻ. Không biết thì nói thật và hỏi người biết.',
            'Thông tin của khách là riêng tư: không kể ai mua gì, ở đâu, gọi về chuyện gì.',
            'Dẫn đoàn: đếm người trước khi đi và sau mỗi điểm dừng; mưa to thì vào chỗ có mái che, đừng đứng dưới gốc cây.',
        ],
        practice=[
            _p('Khi nào nên chuyển khách cho quản lý?',
               [('a', 'Ngay khi khách hơi to tiếng'), ('b', 'Khi khách cần điều ngoài quyền của mình, kèm bản tóm tắt'), ('c', 'Không bao giờ')], 'b',
               'Chuyển kèm tóm tắt để khách không phải kể lại.'),
            _p('Khách nói giọng địa phương khó nghe.',
               [('a', 'Xin phép nhắc lại ý chính để chắc mình hiểu đúng'), ('b', 'Đoán ý rồi làm'), ('c', 'Bảo khách nói giọng khác')], 'a',
               'Nhắc lại ý chính giúp cả hai hiểu đúng mà không làm khách ngại.'),
            _p('Một bác lớn tuổi trong đoàn chóng mặt dưới nắng.',
               [('a', 'Động viên bác đi tiếp cho kịp lịch'), ('b', 'Đưa bác thuốc của mình'),
                ('c', 'Đưa vào chỗ mát, cho nghỉ, uống nước; không đỡ thì gọi 115')], 'c', 'Sức khỏe trước lịch trình; không tự cho thuốc.'),
            _p('Hộp thuốc hết hạn từ hôm qua, khách nói “không sao đâu”.',
               [('a', 'Không giao; đổi hộp còn hạn'), ('b', 'Giao vì khách đồng ý'), ('c', 'Giao và ghi vào sổ')], 'a',
               'Hạn dùng không phụ thuộc vào việc khách đồng ý.'),
        ],
        bank=[
            _q('cs_history', 'Khách gọi lần thứ ba về cùng một đơn. Câu đầu tiên của bạn?',
               [('a', 'Xin khách kể lại từ đầu cho chắc'), ('b', 'Đọc lịch sử trước, tóm tắt điều đã biết để khách khỏi kể lại'),
                ('c', 'Chuyển ngay sang bộ phận khác')], 'b', 'Khách gọi lần thứ ba cần nghe là mình đã nắm chuyện.'),
            _q('cs_identity', 'Một người gọi hỏi tình trạng đơn “của chị tôi”. Bạn làm gì trước?',
               [('a', 'Xác minh mã yêu cầu của chủ đơn rồi mới nói chi tiết'), ('b', 'Đọc hết thông tin đơn cho nhanh'),
                ('c', 'Cúp máy vì không phải chủ đơn')], 'a', 'Chỉ nói chi tiết đơn khi đã xác minh đúng người.'),
            _q('cs_sources', 'Khách nói đơn báo “đã giao” nhưng chưa nhận được. Trước khi đề nghị phương án?',
               [('a', 'Hoàn tiền ngay cho khách vui'), ('b', 'Bảo khách tự hỏi bên vận chuyển'),
                ('c', 'Đọc đủ nguồn: lịch sử đơn, xác nhận của kho, đối soát vận chuyển')], 'c', 'Phương án đúng cần dữ kiện từ đủ các bên.'),
            _q('cs_promise', 'Bạn chưa chắc kho xử lý kịp trong hôm nay. Bạn hẹn khách thế nào?',
               [('a', 'Hẹn một mốc mình giữ được và gọi lại đúng hẹn'), ('b', '“Trong hôm nay chắc chắn xong ạ.”'),
                ('c', 'Không hẹn gì, xong thì báo')], 'a', 'Hứa điều ngoài tầm tay là nợ khách thêm một lần giận.'),
            _q('cs_update', 'Một vụ đang chờ kho trả lời từ hôm qua. Hôm nay bạn nên?',
               [('a', 'Chờ có kết quả rồi mới gọi'), ('b', 'Gọi khách cập nhật trước buổi trưa, kể cả khi chưa có tin mới'),
                ('c', 'Nhắn “đang xử lý” rồi thôi')], 'b', 'Khách đang chờ cần biết vụ của mình vẫn có người theo.'),
            _q('cs_calm', 'Khách quát: “Năm ngày rồi hàng chưa tới!” Câu mở đầu nào tốt nhất?',
               [('a', '“Anh bình tĩnh lại đã.”'), ('b', 'Giải thích dài về quy trình kho'),
                ('c', 'Xin lỗi vì khách phải chờ, xác nhận mã đơn, nói mình kiểm ngay')], 'c',
               'Bảo người đang giận “bình tĩnh” thường làm họ giận hơn.'),
            _q('cs_demand', 'Khách đòi bồi thường gấp đôi tiền hàng.',
               [('a', 'Nói rõ điều nơi mình làm được, không hứa ngoài quyền, hẹn mốc cập nhật'), ('b', 'Đồng ý cho xong chuyện'),
                ('c', '“Không có chuyện đó.” rồi thôi')], 'a', 'Hứa ngoài quyền thì nơi làm phải gánh, lần sau khách lại đòi.'),
            _q('cs_abuse', 'Khách bắt đầu xúc phạm bạn qua điện thoại.',
               [('a', 'Cãi lại cho khách biết'), ('b', 'Giữ giọng bình tĩnh, nhắc nhẹ ranh giới, đề nghị nói tiếp khi khách sẵn sàng'),
                ('c', 'Im lặng chịu đựng tới hết cuộc gọi')], 'b', 'Không đáp trả xúc phạm, nhưng cũng không phải chịu đựng mãi.'),
            _q('cs_manager', 'Khách đòi gặp quản lý ngay.',
               [('a', '“Quản lý bận, không gặp được đâu.”'), ('b', 'Chuyển máy luôn, không ghi chú'),
                ('c', 'Nói rõ việc mình làm được ngay; khách vẫn muốn thì chuyển kèm bản tóm tắt')], 'c',
               'Quản lý có tóm tắt thì khách khỏi kể lại từ đầu.'),
            _q('cs_dose', 'Ở quầy thuốc, khách hỏi “uống mấy viên cho mau khỏi?”, phiếu không ghi liều.',
               [('a', 'Không tự đưa liều; mời người phụ trách hoặc hỏi lại nơi kê phiếu'), ('b', 'Nói theo kinh nghiệm nhà mình'),
                ('c', 'Khuyên uống gấp đôi cho mau khỏi')], 'a', 'Liều dùng là việc của người có chuyên môn.'),
            _q('cs_address', 'Một người gọi tới hỏi địa chỉ giao hàng của một khách quen để “gửi quà bất ngờ”.',
               [('a', 'Đọc địa chỉ vì người đó biết tên khách'), ('b', 'Không cung cấp; địa chỉ của khách là thông tin riêng'),
                ('c', 'Cho số điện thoại khách để họ tự hỏi')], 'b', 'Địa chỉ, số điện thoại của khách là thông tin riêng tư.'),
            _q('cs_unknown', 'Khách hỏi một chuyện bạn không biết chắc.',
               [('a', 'Nói thật là chưa rõ, hỏi người biết hoặc hẹn tìm hiểu rồi báo lại'), ('b', 'Bịa một câu cho xong'),
                ('c', 'Lảng sang chuyện khác')], 'a', 'Người đáng tin là người không bịa.'),
            _q('cs_count', 'Khi dẫn đoàn, lúc nào phải đếm đủ người?',
               [('a', 'Chỉ lúc xuất phát'), ('b', 'Khi có ai hỏi'), ('c', 'Trước khi khởi hành và sau mỗi điểm dừng')], 'c',
               'Lạc đoàn thường xảy ra lúc rời một điểm dừng.'),
            _q('cs_rain', 'Đang dẫn đoàn thì mưa to.',
               [('a', 'Đưa đoàn tới chỗ có mái che gần nhất, đổi lộ trình, báo điều phối'), ('b', 'Đứng dưới gốc cây chờ tạnh'),
                ('c', 'Đi tiếp theo lịch, ướt chút không sao')], 'a', 'Đứng dưới cây khi mưa giông không an toàn.'),
            _q('cs_handover', 'Hết ca, một vụ của bạn vẫn chưa xong.',
               [('a', 'Để mai tính, không ghi gì'), ('b', 'Đóng vụ cho gọn danh sách'),
                ('c', 'Ghi bàn giao: đã làm gì, đang chờ ai, đã hẹn khách mốc nào')], 'c',
               'Ca sau đọc bàn giao là tiếp được, khách không phải kể lại.'),
        ]),
    dict(
        id='teaching', emoji='🍎', name='Chứng chỉ Nghiệp vụ sư phạm', short='Nghiệp vụ sư phạm',
        issuer='Trường Tiểu học Mầm Nắng (lớp giả lập)', careers=('teacher',), fee=25,
        intro='Dạy một lớp có nhiều nhịp học, nhận xét cho đúng, làm việc với phụ huynh và giữ lớp an toàn.',
        notes=[
            'Cùng một mục tiêu, nhiều cách: hình ảnh, làm thử, kể chuyện; chia nhóm để bạn nhanh giúp bạn chậm.',
            'Tiết học vừa thời gian: khởi động ngắn, phần chính, luyện tập, rồi phiếu ra lớp để biết ai đã hiểu.',
            'Nhận xét cụ thể vào việc làm được và bước tiếp theo; không so sánh bạn này với bạn kia trước lớp.',
            'Phụ huynh nhắn khuya: trả lời ngắn, hẹn trao đổi trong giờ hành chính, chuẩn bị sổ lớp. Không bỏ mặc, không tranh cãi.',
            'Sự kiện lớp: hỏi mong muốn của lớp, kiểm tra dị ứng thức ăn, công khai quỹ lớp; không ép phụ huynh đóng thêm.',
            'Trẻ buồn kéo dài hay bị trêu chọc: quan sát, nói chuyện riêng, báo phụ huynh và nhà trường khi cần.',
            'Ra khỏi lớp: điểm danh trước khi đi và sau khi về. Làm sai thì nhận, sửa và nói rõ.',
        ],
        practice=[
            _p('Mục tiêu tiết học nên viết thế nào?',
               [('a', '“Con hiểu bài.”'), ('b', 'Cụ thể, đo được: “Con đọc đúng giờ trên đồng hồ.”'), ('c', 'Không cần mục tiêu')], 'b',
               'Mục tiêu đo được thì cuối tiết mới biết lớp đạt chưa.'),
            _p('Học sinh hỏi một câu bạn chưa biết.',
               [('a', 'Nói thật, cùng tìm hiểu và trả lời vào buổi sau'), ('b', 'Bịa một câu cho xong'), ('c', 'Bảo con đừng hỏi linh tinh')], 'a',
               'Thầy cô không bịa; cùng tìm hiểu cũng là một bài học.'),
            _p('Một bạn làm xong bài sớm.',
               [('a', 'Cho ngồi chơi'), ('b', 'Bắt làm lại bài cũ'), ('c', 'Có sẵn nhiệm vụ mở rộng hoặc nhờ bạn giúp bạn khác')], 'c',
               'Bạn nhanh cũng cần được học tiếp.'),
            _p('Phụ huynh muốn xem điểm của cả lớp.',
               [('a', 'Chỉ trao đổi kết quả của con mình; điểm bạn khác là riêng tư'), ('b', 'Gửi bảng điểm cả lớp'),
                ('c', 'Đọc điểm to trong buổi họp')], 'a', 'Kết quả học tập của mỗi em là thông tin riêng.'),
        ],
        bank=[
            _q('te_diff', 'Lớp có bạn học nhanh, có bạn học chậm. Bạn tổ chức tiết học thế nào?',
               [('a', 'Dạy theo nhóm giỏi cho kịp chương trình'), ('b', 'Cùng mục tiêu, nhiều cách làm; nhóm hỗ trợ lẫn nhau'),
                ('c', 'Dạy thật chậm cho mọi người')], 'b', 'Dạy học phân hóa: không ai bị bỏ lại, không ai phải chán.'),
            _q('te_exit', 'Cuối tiết, cách nhanh nhất để biết ai đã hiểu bài?',
               [('a', 'Phiếu ra lớp: mỗi bạn trả lời một câu ngắn'), ('b', 'Hỏi cả lớp “hiểu chưa?”'), ('c', 'Chờ tới bài kiểm tra cuối kỳ')], 'a',
               'Cả lớp đồng thanh “hiểu rồi” không cho biết ai còn vướng.'),
            _q('te_feedback', 'Bạn Vy làm sai bài toán nhưng đã cố gắng nhiều.',
               [('a', 'Đọc to lỗi sai trước lớp để cả lớp rút kinh nghiệm'), ('b', 'Chỉ ghi “Sai” rồi trả bài'),
                ('c', 'Khen cụ thể phần làm đúng, chỉ bước tiếp theo để sửa')], 'c', 'Nhận xét cụ thể giúp con biết sửa gì tiếp theo.'),
            _q('te_compare', 'Để động viên cả lớp, bạn nói gì?',
               [('a', 'Nêu điều cả lớp đã tiến bộ và mục tiêu tiếp theo'), ('b', '“Sao các con không được như bạn An?”'),
                ('c', 'Dán bảng xếp hạng điểm lên bảng')], 'a', 'So sánh trước lớp làm các con ngại, không làm các con giỏi hơn.'),
            _q('te_parent', 'Phụ huynh nhắn tin gay gắt lúc 22 giờ.',
               [('a', 'Trả lời ngay, giải thích tới khuya'), ('b', 'Nhắn ngắn hẹn trao đổi trong giờ hành chính, chuẩn bị sổ lớp'),
                ('c', 'Không trả lời')], 'b', 'Ranh giới rõ nhưng không bỏ mặc.'),
            _q('te_event', 'Lớp tổ chức Trung thu. Việc đầu tiên?',
               [('a', 'Đặt bánh và đèn cho nhanh'), ('b', 'Thu thêm tiền phụ huynh cho hoành tráng'),
                ('c', 'Hỏi mong muốn của lớp, kiểm tra dị ứng và quỹ lớp')], 'c', 'Chuẩn bị từ người tham gia, không tạo áp lực cho gia đình.'),
            _q('te_allergy', 'Một bạn dị ứng đậu phộng. Buổi liên hoan có bánh đậu phộng.',
               [('a', 'Chuẩn bị món khác cho bạn, ghi vào sổ lớp, dặn người phụ trách bữa ăn'), ('b', 'Dặn bạn tự tránh món đó'),
                ('c', 'Cho ăn ít thôi chắc không sao')], 'a', 'Dị ứng thức ăn có thể nguy hiểm; người lớn phải chủ động.'),
            _q('te_bully', 'Bạn Bảo mấy hôm nay ngồi một mình, có bạn trêu chọc.',
               [('a', 'Để các con tự giải quyết'), ('b', 'Phạt cả lớp đứng dậy'),
                ('c', 'Quan sát, nói chuyện riêng với các bạn, báo phụ huynh và nhà trường khi cần')], 'c',
               'Chuyện trêu chọc cần người lớn để ý sớm và xử lý riêng.'),
            _q('te_roll', 'Dẫn lớp ra sân tập thể dục. Bạn làm gì trước và sau?',
               [('a', 'Điểm danh trước khi ra và sau khi về lớp'), ('b', 'Chỉ điểm danh buổi sáng'), ('c', 'Nhờ lớp trưởng nhớ giùm')], 'a',
               'Ra khỏi lớp là lúc dễ thiếu một bạn mà không ai hay.'),
            _q('te_plan', 'Kế hoạch cho một tiết 35 phút nào hợp lý?',
               [('a', '35 phút giảng liên tục'), ('b', 'Khởi động ngắn, phần chính, luyện tập, phiếu ra lớp'),
                ('c', 'Cho làm bài tập suốt tiết')], 'b', 'Có nhịp và có kiểm tra cuối tiết.'),
            _q('te_fund', 'Quỹ lớp còn dư sau buổi liên hoan.',
               [('a', 'Giữ lại dùng cho lớp, khỏi báo'), ('b', 'Công khai thu chi với phụ huynh, bàn cách dùng tiếp'),
                ('c', 'Chia lại tiền mặt cho vài bạn')], 'b', 'Tiền của phụ huynh thì phải minh bạch.'),
            _q('te_noise', 'Lớp ồn khi làm việc nhóm.',
               [('a', 'Dùng tín hiệu im lặng đã thống nhất, nhắc lại mục tiêu và thời gian'), ('b', 'Quát lớn cho cả lớp im'),
                ('c', 'Hủy hoạt động nhóm')], 'a', 'Tín hiệu quen thuộc giữ lớp mà không phá không khí.'),
            _q('te_sub', 'Bạn được nhờ dạy thay một lớp lạ.',
               [('a', 'Dạy theo giáo án của mình, không cần biết lớp'), ('b', 'Cho lớp tự học cả buổi'),
                ('c', 'Đọc sổ lớp, hỏi giáo viên chủ nhiệm về các bạn cần lưu ý')], 'c', 'Biết lớp trước thì tiết dạy thay mới trọn.'),
            _q('te_mistake', 'Bạn lỡ chấm sai điểm một bài.',
               [('a', 'Nhận lỗi, sửa điểm, nói rõ với học sinh và phụ huynh'), ('b', 'Giữ nguyên cho đỡ rắc rối'),
                ('c', 'Sửa lặng lẽ, không nói ai')], 'a', 'Nhận và sửa lỗi cũng là dạy các con.'),
        ]),
    dict(
        id='accounting', emoji='🧮', name='Chứng chỉ Kế toán cơ bản', short='Kế toán cơ bản',
        issuer='Hội Kế toán khu phố (lớp giả lập)', careers=('corp_accounting', 'tax_payroll', 'group_accounting'), fee=30,
        intro='Chứng từ, khấu hao, khóa sổ, lương và bảo hiểm, thuế GTGT, hợp nhất. Mọi số tính bằng xu, theo luật chơi đơn giản của game.',
        notes=[
            'Hóa đơn mua vào: đối chiếu ba chiều — hóa đơn, phiếu nhập kho, sổ nhà cung cấp — khớp mới chấp nhận.',
            'Khấu hao đường thẳng: mức tháng = nguyên giá ÷ (số năm × 12). Tài sản đưa vào dùng trong tháng thì trích từ tháng sau; khấu hao hết thì thôi trích.',
            'Khóa sổ theo thứ tự: ghi đủ (trích trước, khấu hao) → thuế → kết chuyển doanh thu, chi phí → lãi/lỗ.',
            'Bảo hiểm phần người lao động tính trên lương đóng bảo hiểm trong hợp đồng: BHXH 8%, BHYT 1,5%, BHTN 1%.',
            'Tăng ca: ngày thường 150%, Chủ nhật 200%, ngày lễ 300%. Thực lĩnh = tổng thu nhập − bảo hiểm − thuế.',
            'Thuế GTGT phải nộp = đầu ra − đầu vào hợp lệ. Hóa đơn từ 200 xu trở lên trả tiền mặt thì không được khấu trừ.',
            'Phiếu lương gửi riêng từng người. Sổ lệch sao kê: đối chiếu từng dòng, có chứng từ mới điều chỉnh.',
            'Hợp nhất: loại trừ doanh thu và công nợ nội bộ giữa các công ty trong tập đoàn; sở hữu 70% thì cổ đông không kiểm soát là 30%.',
        ],
        practice=[
            _p('Chứng từ nào cho biết hàng đã thực sự vào kho?',
               [('a', 'Báo giá'), ('b', 'Phiếu nhập kho'), ('c', 'Email chào hàng')], 'b', 'Phiếu nhập kho ghi số thực nhận.'),
            _p('Thực lĩnh bằng gì?',
               [('a', 'Tổng thu nhập − bảo hiểm − thuế'), ('b', 'Lương cơ bản + tăng ca'), ('c', 'Tổng thu nhập − thuế')], 'a',
               'Bảo hiểm và thuế đều trừ vào tổng thu nhập.'),
            _p('Hạn nộp thuế rơi vào ngày nghỉ lễ.',
               [('a', 'Nộp trước kỳ nghỉ, trễ thì phạt'), ('b', 'Bỏ qua kỳ đó'), ('c', 'Lùi sang ngày làm việc đầu tiên sau kỳ nghỉ')], 'c',
               'Luật chơi của game theo đúng quy định lùi hạn.'),
            _p('Kiểm quỹ tiền mặt thấy thiếu 20 xu.',
               [('a', 'Ghi biên bản, tìm nguyên nhân, báo kế toán trưởng'), ('b', 'Bù tiền túi cho khớp, không nói'), ('c', 'Sửa sổ cho khớp')], 'a',
               'Chênh lệch phải có biên bản và nguyên nhân.'),
        ],
        bank=[
            _q('ac_3way', 'Hóa đơn mua vào ghi 100 cái, phiếu nhập kho ghi 90 cái.',
               [('a', 'Ghi sổ 100 cho khớp hóa đơn'), ('b', 'Chưa chấp nhận: gửi lại nhà cung cấp điều chỉnh theo số thực nhận'),
                ('c', 'Ghi 95 cho công bằng')], 'b', 'Đối chiếu ba chiều: chỉ trả tiền cho hàng đã thực nhận.'),
            _q('ac_dep', 'Máy nguyên giá 1.200 xu, dùng 5 năm, khấu hao đường thẳng. Mức khấu hao tháng?',
               [('a', '20 xu'), ('b', '240 xu'), ('c', '100 xu')], 'a', '1.200 ÷ (5 × 12) = 20 xu mỗi tháng.'),
            _q('ac_dep_start', 'Tài sản đưa vào dùng ngày 15 tháng 3. Bắt đầu trích khấu hao từ khi nào?',
               [('a', 'Ngày 15 tháng 3'), ('b', 'Đầu năm sau'), ('c', 'Tháng 4')], 'c', 'Đưa vào dùng trong tháng thì trích từ tháng sau.'),
            _q('ac_dep_full', 'Tài sản đã khấu hao hết (hao mòn lũy kế bằng nguyên giá) nhưng vẫn còn dùng.',
               [('a', 'Thôi trích khấu hao'), ('b', 'Trích tiếp như cũ'), ('c', 'Trích gấp đôi cho chắc')], 'a',
               'Giá trị còn lại đã bằng 0 thì không trích nữa.'),
            _q('ac_close', 'Thứ tự khóa sổ cuối tháng nào đúng?',
               [('a', 'Kết chuyển trước, bổ sung chi phí sau'), ('b', 'Trích trước, khấu hao → thuế → kết chuyển → lãi/lỗ'),
                ('c', 'Tính lãi/lỗ trước cho biết kết quả')], 'b', 'Ghi nhận đủ chi phí rồi mới kết chuyển, nếu không lãi/lỗ sẽ sai.'),
            _q('ac_ins', 'Lương đóng bảo hiểm 5.000 xu. Phần BHXH người lao động đóng?',
               [('a', '500 xu'), ('b', '75 xu'), ('c', '400 xu')], 'c', 'BHXH phần người lao động 8%: 5.000 × 8% = 400 xu.'),
            _q('ac_ins_base', 'Bảo hiểm của người lao động tính trên khoản nào?',
               [('a', 'Lương đóng bảo hiểm ghi trong hợp đồng'), ('b', 'Tổng thu nhập tháng, kể cả tăng ca'), ('c', 'Lương thực lĩnh')], 'a',
               'Không tính trên tổng thu nhập.'),
            _q('ac_ot', 'Lương giờ 30 xu, tăng ca 2 giờ vào Chủ nhật. Tiền tăng ca?',
               [('a', '90 xu'), ('b', '120 xu'), ('c', '180 xu')], 'b', 'Chủ nhật 200%: 30 × 2 × 200% = 120 xu.'),
            _q('ac_holiday', 'Tăng ca vào ngày lễ tính hệ số bao nhiêu?',
               [('a', '150%'), ('b', '200%'), ('c', '300%')], 'c', 'Ngày thường 150%, Chủ nhật 200%, ngày lễ 300%.'),
            _q('ac_vat', 'Thuế GTGT đầu ra 900 xu, đầu vào hợp lệ 600 xu. Phải nộp bao nhiêu?',
               [('a', '300 xu'), ('b', '1.500 xu'), ('c', '900 xu')], 'a', 'Phải nộp = đầu ra − đầu vào hợp lệ = 300 xu.'),
            _q('ac_cash', 'Hóa đơn mua vào 250 xu trả bằng tiền mặt. Thuế GTGT đầu vào của hóa đơn này?',
               [('a', 'Khấu trừ bình thường'), ('b', 'Không được khấu trừ vì từ 200 xu trở lên mà trả tiền mặt'), ('c', 'Khấu trừ một nửa')], 'b',
               'Luật chơi: hóa đơn từ 200 xu trả tiền mặt không được khấu trừ.'),
            _q('ac_payslip', 'Gửi phiếu lương cho nhân viên thế nào?',
               [('a', 'Dán bảng lương chung lên nhóm chat'), ('b', 'Đọc to trong buổi họp'), ('c', 'Gửi riêng từng người')], 'c',
               'Lương của mỗi người là thông tin riêng.'),
            _q('ac_bank', 'Số dư sổ tiền gửi khác sao kê ngân hàng 50 xu.',
               [('a', 'Đối chiếu từng dòng tìm khoản chênh, có chứng từ mới điều chỉnh'), ('b', 'Sửa sổ cho khớp sao kê luôn'),
                ('c', 'Bỏ qua vì số nhỏ')], 'a', 'Mỗi dòng điều chỉnh phải có chứng từ.'),
            _q('ac_trial', 'Bảng cân đối thử không cân: tổng Nợ lệch tổng Có 90 xu.',
               [('a', 'Thêm một dòng 90 xu cho cân'), ('b', 'Gửi luôn, tháng sau tính'),
                ('c', 'Soát lại từng bút toán, để ý số bị đảo chữ số (khoản lệch chia hết cho 9)')], 'c',
               'Đảo chữ số (54 thành 45) luôn tạo khoản lệch chia hết cho 9.'),
            _q('ac_nci', 'Công ty mẹ sở hữu 70% một công ty con. Khi hợp nhất, phần của cổ đông không kiểm soát là?',
               [('a', '70%'), ('b', '30%'), ('c', '0% vì công ty mẹ kiểm soát')], 'b', '100% − 70% = 30%.'),
            _q('ac_interco', 'Công ty con này bán hàng cho công ty con khác trong cùng tập đoàn.',
               [('a', 'Loại trừ doanh thu và công nợ nội bộ khi lập báo cáo hợp nhất'), ('b', 'Cộng dồn như doanh thu bình thường'),
                ('c', 'Chỉ ghi ở công ty mua')], 'a', 'Trong tập đoàn, bán cho nhau không tạo ra doanh thu với bên ngoài.'),
        ]),
    # ✈️ Hãng bay Cánh Cò (pilot, flight_attendant)
    dict(
        id='air_safety', emoji='✈️', name='Chứng chỉ An toàn bay cơ bản', short='An toàn bay',
        issuer='Trung tâm huấn luyện Cánh Cò (lớp giả lập)', careers=('pilot', 'flight_attendant'), fee=25,
        intro='Dầu đủ, tàu kiểm kỹ, checklist đúng thứ tự, khoang khách an toàn và nói thật với khách khi chậm chuyến.',
        notes=[
            'Dầu cho một chặng = dầu chặng + dầu bay đi sân bay dự bị + 30 phút dự phòng. Dự báo giông lúc tới: mang thêm 20 phút dầu chờ.',
            'Tàu kín khách thì không đổ đầy bình: quá trọng lượng cất cánh. Dầu dự phòng không bao giờ được bớt.',
            'Đi một vòng quanh tàu trước mỗi chặng. Vỏ che ống pitot, chốt cửa khoang hàng: tự xử lý. Lốp mòn, rò dầu: gọi thợ máy.',
            'Checklist đọc theo thẻ, từng dòng một, không nhảy cóc. Thấy đồng đội quên dòng nào thì nói ngay.',
            'Tiếp cận chưa ổn định, hoặc tới độ cao quyết định chưa thấy đường băng: bay lại. Bay lại không bao giờ là thất bại.',
            'Chậm chuyến: nói rõ vì sao, chậm bao lâu, xin lỗi và hẹn báo lại. Không nói “sắp bay rồi” khi chưa chắc.',
            'Hàng ghế cạnh cửa thoát hiểm chỉ dành cho người lớn đi lại được, mở được cửa. Pin sạc dự phòng mang theo người, không gửi khoang hàng.',
            'Khách ốm: hỏi han, dùng đúng đồ trong túi sơ cứu, không đưa thuốc của mình; khách nặng thì tìm bác sĩ trên chuyến và báo cơ trưởng.',
        ],
        practice=[
            _p('Dầu chặng 600 kg, đi sân bay dự bị 300 kg, dự phòng 30 phút 350 kg, trời đẹp. Nạp bao nhiêu?',
               [('a', '950 kg'), ('b', '1.250 kg'), ('c', 'Đầy bình cho chắc')], 'b', '600 + 300 + 350 = 1.250 kg.'),
            _p('Cổng 1.000 ft: tốc độ 132 kt, chuẩn 110–120 kt.',
               [('a', 'Bay lại'), ('b', 'Tiếp tục, xuống thấp sẽ giảm'), ('c', 'Hạ cánh rồi phanh gấp')], 'a', 'Chưa ổn định thì bay lại.'),
            _p('Đèn thắt dây bật giữa lúc đang đẩy xe phục vụ.',
               [('a', 'Phục vụ nốt hàng này'), ('b', 'Khóa phanh xe, cất bình nóng, về ghế thắt dây'), ('c', 'Đẩy xe về bếp thật nhanh')], 'b',
               'Xe khóa phanh không trôi, bình nóng cất đi không làm bỏng ai.'),
            _p('Em bé ba tuổi xin uống trà nóng giống bố.',
               [('a', 'Rót ít thôi'), ('b', 'Mời bé nước cam hoặc nước lọc'), ('c', 'Đưa cho bố cầm hộ')], 'b', 'Trẻ nhỏ không uống đồ nóng trên tàu.'),
        ],
        bank=[
            _q('air_fuel', 'Dự báo giông ở sân bay đến đúng giờ tới. Dầu cần thêm gì?',
               [('a', 'Không cần thêm'), ('b', 'Thêm 20 phút dầu chờ'), ('c', 'Bớt dầu dự bị cho nhẹ')], 'b', 'Có dầu chờ thì tới nơi mới bay chờ được.'),
            _q('air_full', 'Tàu kín 68 khách, chặng ngắn. Đổ đầy bình được không?',
               [('a', 'Được, dư còn hơn thiếu'), ('b', 'Không, quá trọng lượng cất cánh'), ('c', 'Được nếu bay chậm')], 'b',
               'Đầy bình với tàu kín khách là quá tải.'),
            _q('air_pitot', 'Đi quanh tàu thấy vỏ che ống pitot còn cắm.',
               [('a', 'Tháo ra, cất vào túi đồ nghề'), ('b', 'Để nguyên, gió sẽ thổi bay'), ('c', 'Báo hủy chuyến')], 'a',
               'Còn vỏ che thì đồng hồ tốc độ bị mù.'),
            _q('air_tyre', 'Lốp bánh trái mòn tới vạch đỏ.',
               [('a', 'Bay nốt chặng này'), ('b', 'Gọi thợ máy thay lốp, báo khách chậm chuyến'), ('c', 'Tự bơm thêm hơi')], 'b',
               'Lốp mòn tới vạch đỏ dễ nổ khi hạ cánh.'),
            _q('air_order', 'Đang làm checklist, bạn lỡ bật đèn chống va trước khi đóng cửa khoang.',
               [('a', 'Kệ, miễn cuối cùng đủ'), ('b', 'Dừng lại, làm lại đúng dòng đang đọc'), ('c', 'Bỏ qua dòng cửa khoang')], 'b',
               'Checklist đi từng dòng theo thẻ.'),
            _q('air_minima', 'Tới độ cao quyết định 200 ft vẫn chưa thấy đường băng.',
               [('a', 'Xuống thêm chút nữa xem'), ('b', 'Bay lại'), ('c', 'Hạ cánh theo đồng hồ')], 'b', 'Chưa thấy đường băng ở độ cao quyết định: bay lại.'),
            _q('air_storm', 'Giông đang ở trên sân bay đến, tàu không mang dầu chờ.',
               [('a', 'Bay đi sân bay dự bị'), ('b', 'Bay vòng chờ 20 phút'), ('c', 'Cố hạ cánh')], 'a', 'Không có dầu chờ thì đi sân bay dự bị.'),
            _q('air_pa', 'Chuyến bay chậm 30 phút vì thợ máy kiểm tra lại tàu. Thông báo thế nào?',
               [('a', '“Vì lý do khách quan…”'), ('b', 'Nói rõ lý do, chậm bao lâu, xin lỗi và hẹn báo lại'), ('c', '“Sắp cất cánh rồi ạ.”')], 'b',
               'Nói thật, nói rõ thì khách mới yên tâm chờ.'),
            _q('air_exit', 'Cụ ông chống gậy có vé hàng 17 cạnh cửa thoát hiểm.',
               [('a', 'Để cụ ngồi vì đã mua vé'), ('b', 'Giải thích, mời cụ sang ghế khác rộng chân'), ('c', 'Hỏi cụ có muốn đổi không')], 'b',
               'Người ngồi cạnh cửa thoát hiểm phải mở được cửa.'),
            _q('air_power', 'Khách muốn gửi vali có pin sạc dự phòng xuống khoang hàng.',
               [('a', 'Gửi luôn'), ('b', 'Lấy pin ra cho khách mang theo người rồi mới gửi'), ('c', 'Bỏ pin vào thùng rác')], 'b',
               'Pin sạc dự phòng dễ cháy, phải ở trong khoang khách.'),
            _q('air_nut', 'Hàng 9 có khách dị ứng đậu phộng. Khách bên cạnh xin một gói đậu phộng.',
               [('a', 'Đưa, vì người khác xin'), ('b', 'Mời bánh bông lan thay, không phát đậu phộng cả hàng'), ('c', 'Đưa nhưng dặn ăn nhỏ nhẹ')], 'b',
               'Bụi đậu phộng cũng đủ làm người dị ứng khó thở.'),
            _q('air_med', 'Khách đau ngực, vã mồ hôi giữa chuyến bay.',
               [('a', 'Đưa thuốc của mình cho khách uống'), ('b', 'Cho thở dưỡng khí, tìm bác sĩ trên chuyến, báo cơ trưởng'), ('c', 'Chờ xem có đỡ không')], 'b',
               'Không đưa thuốc của mình; báo cơ trưởng để quyết định chuyển hướng.'),
        ]),
    # 🛢️ Dầu khí Sóng Bạc (oil)
    dict(
        id='offshore_safety', emoji='🛢️', name='Chứng chỉ An toàn cơ bản ngoài khơi', short='An toàn ngoài khơi',
        issuer='Trung tâm huấn luyện Sóng Bạc (lớp giả lập)', careers=('oil',), fee=25,
        intro='Thoát hiểm trực thăng, giấy phép làm việc, khóa và treo thẻ, đo khí, quyền dừng việc, tập trung khi báo động. Luật chơi đơn giản của game.',
        notes=[
            'Trực thăng chạm nước và lật: giữ tư thế, một tay nắm mốc cửa, chờ khoang ngừng lật rồi mới tháo dây. Áo phao chỉ bơm khi đã ra khỏi khoang.',
            'Túi lên trực thăng: không bật lửa, bình xịt, dao, đồ có cồn, thuốc lá điện tử. Mặc đủ đồ bơi giữ nhiệt, áo phao, bình thở khẩn cấp, chụp tai.',
            'Mọi việc bảo dưỡng cần đúng loại giấy phép: làm nguội, làm nóng (hàn, cắt, mài), vào không gian hạn chế, làm việc điện.',
            'Khóa và treo thẻ: mỗi người làm một ổ khóa của mình trên mọi điểm cô lập, chìa ai nấy giữ. Không ai khóa giùm, không ai ký giùm.',
            'Trước khi mở thiết bị: xả áp, rồi kiểm về không. Đồng hồ không về 0 là van lọt: dừng, cô lập thêm một lớp.',
            'Đo khí tại chỗ làm: khí dễ cháy dưới giới hạn (làm nóng phải 0% LEL), ôxy 19,5–23,5%, H₂S dưới giới hạn. Máy đo phải thử khí mẫu đầu ca.',
            'Ai cũng có quyền dừng việc khi thấy không an toàn, không bị trách. Báo cả suýt sự cố, kể cả của mình: người báo không bị phạt.',
            'Có báo động: dừng việc, để thiết bị an toàn, không quay lại lấy đồ, đi ngược gió, không đi thang máy, về đúng điểm tập trung, quẹt thẻ.',
        ],
        practice=[
            _p('Trực thăng chạm nước và lật úp. Việc đầu tiên?',
               [('a', 'Tháo dây ngay'), ('b', 'Giữ tư thế, nắm mốc cửa, chờ ngừng lật'), ('c', 'Bơm áo phao')], 'b', 'Tháo dây khi còn lật là mất phương hướng.'),
            _p('Đồng hồ vẫn 4 bar sau khi xả áp.',
               [('a', 'Nới bích từ từ'), ('b', 'Dừng, báo trưởng ca, cô lập thêm một lớp'), ('c', 'Làm luôn, áp nhỏ')], 'b', 'Chưa về không thì chưa được mở.'),
            _p('Còi báo rò khí, gió thổi từ hướng Đông Bắc, rò ở khu bình tách.',
               [('a', 'Đi lối tắt qua khu bình tách'), ('b', 'Đi cầu thang phía đón gió, tránh khu rò'), ('c', 'Đi thang máy cho nhanh')], 'b',
               'Đi ngược gió, tránh khu rò, không đi thang máy.'),
            _p('Hai người cùng sửa một bơm. Khóa cầu dao thế nào?',
               [('a', 'Mỗi người một ổ khóa'), ('b', 'Một người khóa là đủ'), ('c', 'Treo thẻ, khỏi khóa')], 'a', 'Cầu dao chỉ mở khi cả hai cùng tháo khóa.'),
        ],
        bank=[
            _q('os_huet', 'Khi nào bơm hơi áo phao trực thăng?',
               [('a', 'Ngay khi có báo động'), ('b', 'Khi đã ra khỏi khoang'), ('c', 'Lúc ngồi xuống ghế')], 'b', 'Bơm trong khoang thì bị ép lên trần, không ra được cửa.'),
            _q('os_bag', 'Món nào không được mang lên trực thăng ra giàn?',
               [('a', 'Thuốc riêng có đơn'), ('b', 'Bật lửa'), ('c', 'Quần áo cho 14 ngày')], 'b', 'Bật lửa là nguồn lửa, giàn cấm.'),
            _q('os_permit', 'Hàn lại chân lan can trên boong cần giấy phép gì?',
               [('a', 'Làm nguội'), ('b', 'Làm nóng'), ('c', 'Không cần giấy phép')], 'b', 'Hàn, cắt, mài sinh tia lửa: giấy phép làm nóng.'),
            _q('os_lock', 'Đồng nghiệp bảo “xài chung ổ khóa của tao cho nhanh”.',
               [('a', 'Đồng ý cho nhanh'), ('b', 'Treo ổ khóa của mình bằng kẹp nhiều khóa'), ('c', 'Chỉ treo thẻ tên')], 'b', 'Ai làm người đó khóa, chìa ai nấy giữ.'),
            _q('os_zero', 'Thứ tự đúng trước khi mở bình lọc?',
               [('a', 'Khóa van, xả áp, kiểm về không, đo khí'), ('b', 'Mở nắp rồi xả'), ('c', 'Đo khí rồi mở, khỏi khóa')], 'a', 'Cô lập, xả, chứng minh về không, đo khí rồi mới mở.'),
            _q('os_hotlel', 'Làm nóng mà máy đo báo 3% LEL.',
               [('a', 'Dưới 10% thì làm được'), ('b', 'Dừng: làm nóng phải 0% LEL'), ('c', 'Làm nhanh cho xong')], 'b', 'Có khí dễ cháy thì không được có tia lửa.'),
            _q('os_o2', 'Đo trong bồn: ôxy 18%.',
               [('a', 'Vào nhanh rồi ra'), ('b', 'Không vào, thông gió rồi đo lại'), ('c', 'Đeo khẩu trang rồi vào')], 'b', 'Dưới 19,5% là thiếu ôxy, vào là ngất.'),
            _q('os_bump', 'Thử khí mẫu đầu ca, kênh H₂S của máy đo không phản ứng.',
               [('a', 'Vẫn dùng, ba kênh kia tốt'), ('b', 'Đổi máy dự phòng, thử lại'), ('c', 'Tắt kênh H₂S')], 'b', 'Máy đo hỏng thì có khí cũng không báo.'),
            _q('os_stop', 'Giám sát giục bỏ bước đo khí cho kịp tàu dịch vụ.',
               [('a', 'Làm theo vì sếp chịu'), ('b', 'Dùng quyền dừng việc, đo khí rồi mới làm'), ('c', 'Đo cho có')], 'b', 'Không tiến độ nào đáng một bước an toàn.'),
            _q('os_nearmiss', 'Bạn suýt làm rơi cờ lê từ sàn trên xuống, không ai thấy.',
               [('a', 'Im lặng'), ('b', 'Tự báo suýt sự cố'), ('c', 'Chỉ xin lỗi người bên dưới')], 'b', 'Báo suýt sự cố giúp cả giàn sửa cách làm; người báo không bị phạt.'),
            _q('os_muster', 'Còi báo động lúc bạn đang ở phòng. Điện thoại để trên giường.',
               [('a', 'Quay lại lấy điện thoại'), ('b', 'Đi luôn về điểm tập trung, quẹt thẻ'), ('c', 'Gọi điện hỏi xem thật không')], 'b', 'Có báo động là đi ngay, không quay lại lấy đồ.'),
            _q('os_leak', 'Đi tuần nghe tiếng xì và mùi khí ở mặt bích.',
               [('a', 'Tự siết bu lông cho hết xì'), ('b', 'Báo phòng điều khiển, rào khu vực, đứng ngược gió'), ('c', 'Ghi sổ, mai báo')], 'b', 'Không siết bích khi còn áp: báo và cô lập.'),
        ]),
    # 🚦 Xí nghiệp Đường sắt Sông Mây (railway)
    dict(
        id='rail_safety', emoji='🚦', name='Chứng chỉ An toàn đường ngang', short='An toàn đường ngang',
        issuer='Trung tâm huấn luyện Xí nghiệp Đường sắt Sông Mây (lớp giả lập)', careers=('railway',), fee=20,
        intro='Nhận lệnh và nhắc lại, đóng chắn đúng lúc, không mở chắn cho ai, nhìn hết đoàn tàu, tuần đường và báo đúng kênh. Luật chơi đơn giản của game.',
        notes=[
            'Ga báo tàu: nhắc lại đủ số hiệu tàu, giờ rời ga trước, giờ qua đường ngang. Không rõ thì hỏi lại ngay, không “rõ” cho qua.',
            'Nhìn hai phía đường ngang trước khi đóng. Người, xe, gia súc trên ray: dẹp trước. Không dẹp kịp thì báo ga dừng tàu, cờ đỏ về phía tàu tới.',
            'Chuông đèn bật trước, cần chắn hạ sau. Hạ khi tàu còn khoảng ba phút: sớm quá dân sốt ruột chui chắn, muộn quá là nguy hiểm.',
            'Chắn đã hạ thì không nâng cho bất kỳ ai, kể cả xe cứu thương, đám tang, người dúi tiền. Nói rõ còn mấy phút, mời chờ sau vạch.',
            'Đứng cờ xanh (đêm: đèn trắng) báo đường thông chỉ khi trên ray không còn ai. Có vật cản: cờ đỏ, đèn đỏ.',
            'Nhìn hết đoàn tàu: khói ở bầu trục, cửa toa mở, xích quệt lửa, không có đèn đuôi toa cuối: báo ga ngay.',
            'Trước khi nâng chắn, hỏi ga còn tàu nào không. Tàu chậm mà ga xác nhận tàu còn đứng ở ga trước thì được mở tạm.',
            'Tuần đường: bu lông lỏng tự siết, ghi sổ; tà vẹt nứt ghi phiếu báo hỏng; ray nứt, đá trôi, ray cong: cắm cờ phòng vệ hai đầu và điện khẩn cho ga.',
        ],
        practice=[
            _p('Ga báo tàu còn tám phút. Bạn làm gì trước?',
               [('a', 'Hạ chắn ngay'), ('b', 'Nhắc lại lệnh, nhìn đường ngang, dẹp người trên ray'), ('c', 'Chờ thấy tàu rồi tính')], 'b',
               'Nhắc lại lệnh, nhìn và dẹp đường ngang trước; còn khoảng ba phút thì đóng.'),
            _p('Chắn đã hạ, xe cứu thương xin qua, tàu còn hai phút.',
               [('a', 'Nâng chắn cho xe ưu tiên'), ('b', 'Giữ chắn, nói rõ còn hai phút'), ('c', 'Bảo xe đi đường khác rồi bỏ đi')], 'b',
               'Tàu không phanh kịp; hai phút chờ là an toàn cho cả xe cứu thương.'),
            _p('Tàu qua, bạn không thấy đèn đuôi toa cuối.',
               [('a', 'Báo ngay trực ban ga'), ('b', 'Ghi sổ cuối ca'), ('c', 'Bỏ qua')], 'a', 'Không có đèn đuôi có thể là đứt toa.'),
            _p('Đi tuần thấy bu lông mối nối lỏng.',
               [('a', 'Điện khẩn cho ga'), ('b', 'Tự siết lại, ghi sổ tuần đường'), ('c', 'Để tổ thợ tự thấy')], 'b',
               'Việc nhỏ trong tầm tay thì tự xử lý và ghi sổ.'),
        ],
        bank=[
            _q('rs_readback', 'Bộ đàm rè, bạn chỉ nghe được nửa lệnh báo tàu.',
               [('a', 'Trả lời “rõ” rồi đoán theo bảng giờ'), ('b', 'Xin ga nhắc lại, rồi đọc lại đủ số hiệu và giờ'), ('c', 'Chờ thấy tàu')], 'b',
               'Không rõ thì hỏi lại ngay.'),
            _q('rs_bell', 'Thứ tự đúng khi đóng đường ngang?',
               [('a', 'Hạ chắn rồi bật chuông'), ('b', 'Bật chuông đèn rồi mới hạ chắn'), ('c', 'Bật cùng lúc')], 'b',
               'Chuông đèn báo trước để người đi đường dừng lại.'),
            _q('rs_when', 'Khi nào hạ chắn?',
               [('a', 'Ngay khi ga báo, dù tàu còn hai mươi phút'), ('b', 'Khi tàu còn khoảng ba phút'), ('c', 'Khi thấy đèn tàu')], 'b',
               'Sớm quá người ta chui chắn, muộn quá thì nguy hiểm.'),
            _q('rs_open', 'Chắn đã hạ, người dúi tiền xin nâng cho xe qua.',
               [('a', 'Nâng nhanh hai giây'), ('b', 'Từ chối, giữ chắn, ghi biển số báo công an'), ('c', 'Nhận tiền rồi không nâng')], 'b',
               'Chắn đã hạ thì không nâng cho ai.'),
            _q('rs_cow', 'Ga báo tàu còn hai phút, con bò đứng lì giữa ray.',
               [('a', 'Báo ga dừng tàu, cờ đỏ về phía tàu tới'), ('b', 'Hạ chắn kệ con bò'), ('c', 'Cầm cờ xanh cho tàu chạy chậm')], 'a',
               'Không dẹp kịp thì dừng tàu.'),
            _q('rs_green', 'Khi nào giơ cờ xanh báo đường thông?',
               [('a', 'Khi chắn đã hạ và trên ray không còn ai'), ('b', 'Khi tàu tới gần'), ('c', 'Bất cứ lúc nào chắn đã hạ')], 'a',
               'Cờ xanh là lời bảo đảm đường ngang thông.'),
            _q('rs_tail', 'Tàu hàng vừa qua không có đèn đuôi.',
               [('a', 'Báo ngay trực ban ga'), ('b', 'Nâng chắn, ghi sổ'), ('c', 'Gọi lái tàu bằng điện thoại riêng')], 'a',
               'Đèn đuôi cho biết đoàn tàu còn nguyên.'),
            _q('rs_second', 'Tàu vừa qua hết. Trước khi nâng chắn bạn làm gì?',
               [('a', 'Nâng ngay cho xe đỡ dồn'), ('b', 'Hỏi ga còn tàu nào không'), ('c', 'Nhìn một bên rồi nâng')], 'b',
               'Có thể còn tàu chạy ngược chiều trên đường bên kia.'),
            _q('rs_delay', 'Chắn đã hạ, ga báo tàu chậm thêm hai mươi phút.',
               [('a', 'Tự nâng chắn cho xe qua'), ('b', 'Hỏi ga: tàu còn đứng ở ga trước không, ga xác nhận thì mở tạm'), ('c', 'Bỏ chòi đi uống nước')], 'b',
               'Chỉ mở tạm khi ga xác nhận tàu còn đứng.'),
            _q('rs_ballast', 'Đi tuần thấy đá ba-lát trôi, ray treo hẫng.',
               [('a', 'Ghi phiếu báo hỏng'), ('b', 'Cắm cờ đỏ phòng vệ hai đầu, điện khẩn cho ga'), ('c', 'Tự xúc đá chèn rồi đi tiếp')], 'b',
               'Chỗ nguy hiểm: phòng vệ và báo khẩn.'),
            _q('rs_sleeper', 'Đi tuần thấy một thanh tà vẹt nứt chân.',
               [('a', 'Phiếu báo hỏng gửi cung'), ('b', 'Điện khẩn, dừng hết tàu'), ('c', 'Bỏ qua')], 'a',
               'Không gấp thì báo bằng phiếu cho tổ thợ.'),
            _q('rs_handover', 'Đồng nghiệp nhờ ký sổ giao ca “thiết bị bình thường” khi chưa thử.',
               [('a', 'Ký giúp'), ('b', 'Từ chối, thử từng thiết bị rồi mới ký'), ('c', 'Ký nhưng ghi “chưa thử”')], 'b',
               'Ký là nhận trách nhiệm.'),
        ]),
    dict(
        id='office_admin', emoji='🗂️', name='Chứng chỉ Hành chính văn phòng', short='Hành chính văn phòng',
        issuer='Trung tâm dạy nghề phường (lớp giả lập)', careers=('hr_admin', 'secretary', 'it_helpdesk'), fee=20,
        intro='Lọc hồ sơ công bằng, chấm công, hợp đồng lao động, lời nhắn và lịch họp, thư lừa đảo, an toàn máy tính. Luật chơi đơn giản của game.',
        notes=[
            'Lọc hồ sơ chỉ theo yêu cầu công việc: kinh nghiệm, kỹ năng, bằng cấp. Không loại vì giới tính, hôn nhân, tuổi hay quê quán.',
            'CV và tra cứu BHXH lệch nhau, hoặc thiếu bản sao bằng bắt buộc: xếp “Cần xác minh”, chưa mời ngay. Người quen giới thiệu vẫn xét như mọi người.',
            'Chấm công: vào 08:00, trễ tới 08:05 vẫn đủ công. Nghỉ chỉ tính có phép khi đơn đã duyệt; đi công tác có lịch vẫn tính công.',
            'Hợp đồng lao động: thử việc tối đa 60 ngày, lương thử việc ít nhất 85%; hợp đồng từ 1 tháng phải đóng bảo hiểm; không ký thay người lao động.',
            'Lời nhắn điện thoại: ghi đủ họ tên, lấy số sau cùng người gọi đọc lại, giờ ghi theo 24 giờ (2 giờ rưỡi chiều là 14:30).',
            'Thư lạ đòi chuyển tiền gấp hay báo đổi số tài khoản: gọi lại bằng số đã biết để xác minh, không làm theo thư.',
            'Xếp lịch họp: không trùng người, phòng đủ chỗ và đủ thiết bị, tránh giờ người ta bận, vòng sau xếp sau vòng trước.',
            'Máy tính: sao lưu trước khi sửa; không ai được hỏi mã OTP hay mật khẩu; nghỉ việc thì khóa quyền ngay hôm đó; nghi nhiễm mã độc thì rút mạng trước.',
        ],
        practice=[
            _p('Ứng viên đủ mọi yêu cầu nhưng email là “heocon.2k1@gmail.com”.',
               [('a', 'Loại vì email trẻ con'), ('b', 'Mời phỏng vấn'), ('c', 'Cần xác minh')], 'b', 'Email ngộ nghĩnh không phải lý do để loại người đủ điều kiện.'),
            _p('Bảng công ghi 08:04 – 17:10.',
               [('a', 'Đủ công'), ('b', 'Đi muộn'), ('c', 'Thiếu giờ ra')], 'a', 'Trễ tới 08:05 vẫn đủ công.'),
            _p('Khách đọc số: “0903 412… à nhầm, 0903 421 785.” Ghi số nào?',
               [('a', 'Số đọc đầu tiên'), ('b', '0903 421 785'), ('c', 'Ghi cả hai cho chắc')], 'b', 'Lấy số sau cùng người gọi đọc lại.'),
            _p('Người tự xưng giám đốc gọi xin mã OTP để “kiểm tra tài khoản”.',
               [('a', 'Đọc mã cho nhanh'), ('b', 'Không đọc, báo trưởng nhóm IT'), ('c', 'Gửi qua tin nhắn')], 'b', 'Không ai được hỏi mã OTP, kể cả sếp.'),
        ],
        bank=[
            _q('oa_bias', 'Anh Quân dặn: “Mới cưới, chắc sắp sinh con. Loại đi em.” Hồ sơ đủ mọi yêu cầu.',
               [('a', 'Loại theo lời giám đốc'), ('b', 'Mời phỏng vấn như mọi người'), ('c', 'Cần xác minh')], 'b',
               'Không loại vì hôn nhân hay giới tính; chỉ xét yêu cầu công việc.'),
            _q('oa_bhxh', 'CV ghi 3 năm kinh nghiệm, tra cứu BHXH chỉ có 7 tháng.',
               [('a', 'Mời phỏng vấn'), ('b', 'Cần xác minh chỗ làm cũ'), ('c', 'Báo công an')], 'b', 'Lệch giữa CV và BHXH thì xác minh trước.'),
            _q('oa_nephew', 'Cháu giám đốc nộp hồ sơ, thiếu bằng bắt buộc.',
               [('a', 'Nhận thẳng vì người nhà'), ('b', 'Xét như mọi người: chưa đủ điều kiện'), ('c', 'Làm bằng giả cho kịp')], 'b',
               'Người quen giới thiệu vẫn xét như mọi người.'),
            _q('oa_leave', 'Bảng công trống ngày thứ Ba; đơn nghỉ phép của người đó còn “chưa duyệt”.',
               [('a', 'Nghỉ có phép'), ('b', 'Nghỉ không phép'), ('c', 'Đủ công')], 'b', 'Đơn chưa duyệt thì chưa tính là nghỉ có phép.'),
            _q('oa_trip', 'Bảng công trống, nhưng lịch công tác ghi người đó đi giao hàng mẫu hôm đó.',
               [('a', 'Đi công tác: vẫn tính công'), ('b', 'Nghỉ không phép'), ('c', 'Thiếu giờ ra/vào')], 'a', 'Đi công tác có lịch thì vẫn tính công.'),
            _q('oa_probation', 'Hợp đồng nháp ghi thử việc 90 ngày, hưởng 70% lương.',
               [('a', 'Để nguyên, người lao động đồng ý rồi'), ('b', 'Sửa: tối đa 60 ngày, ít nhất 85% lương'), ('c', 'Bỏ hẳn điều thử việc')], 'b',
               'Thử việc không quá 60 ngày, lương thử việc ít nhất 85%.'),
            _q('oa_sign', 'Bên B chưa ký mà sếp giục lưu hợp đồng.',
               [('a', 'Ký thay Bên B cho kịp'), ('b', 'Mời Bên B ký trước khi lưu'), ('c', 'Lưu bản chưa ký')], 'b', 'Không ký thay người lao động.'),
            _q('oa_time', 'Khách hẹn “gọi lại sau ba giờ chiều”. Ghi giờ nào?',
               [('a', '03:00'), ('b', '15:00'), ('c', '13:00')], 'b', 'Giờ ghi theo 24 giờ: ba giờ chiều là 15:00.'),
            _q('oa_bank', 'Email “nhà cung cấp” báo đổi số tài khoản, nhờ chuyển gấp tiền hàng hôm nay.',
               [('a', 'Chuyển vào số mới'), ('b', 'Gọi lại số điện thoại đã biết của nhà cung cấp để xác minh'), ('c', 'Trả lời email hỏi lại')], 'b',
               'Đổi tài khoản qua email là chiêu lừa quen thuộc; xác minh bằng số đã biết.'),
            _q('oa_room', 'Buổi phỏng vấn nhóm 7 người. Phòng họp nhỏ có 3 chỗ, phòng lớn 8 chỗ.',
               [('a', 'Phòng họp nhỏ, kê thêm ghế'), ('b', 'Phòng họp lớn'), ('c', 'Chia hai phòng')], 'b', 'Phòng phải đủ chỗ cho cả nhóm.'),
            _q('oa_backup', 'Máy Cô Hằng chậm, cần cài lại. Việc đầu tiên?',
               [('a', 'Cài lại ngay cho nhanh'), ('b', 'Sao lưu dữ liệu trước'), ('c', 'Xóa bớt file cho nhẹ')], 'b', 'Sao lưu trước, sửa sau.'),
            _q('oa_quit', 'Một nhân viên nghỉ việc hôm nay. Tài khoản email và phần mềm của người đó?',
               [('a', 'Để nguyên một tháng'), ('b', 'Khóa quyền ngay hôm nay, chuyển dữ liệu cho người nhận việc'), ('c', 'Đưa mật khẩu cho đồng nghiệp')], 'b',
               'Nghỉ việc thì khóa quyền ngay hôm đó.'),
            _q('oa_ransom', 'Màn hình hiện thông báo đòi tiền chuộc, file đổi đuôi lạ.',
               [('a', 'Trả tiền cho xong'), ('b', 'Rút mạng máy đó, báo trưởng nhóm IT'), ('c', 'Tắt cảnh báo rồi làm tiếp')], 'b',
               'Rút mạng trước để mã độc không lây sang máy khác.'),
        ]),
    # 🏥 Bệnh viện phường Lá Sen (nurse): procedures only, never a dose (the doctor decides treatment)
    dict(
        id='patient_safety', emoji='🏥', name='Chứng chỉ An toàn người bệnh', short='An toàn người bệnh',
        issuer='Phòng Điều dưỡng, Bệnh viện phường Lá Sen (lớp giả lập)', careers=('nurse',), fee=20,
        intro='Nhận diện người bệnh, sát khuẩn tay, đối chiếu y lệnh, báo bất thường, quyền từ chối của người bệnh. Không có câu nào hỏi liều thuốc: việc đó của bác sĩ.',
        notes=[
            'Nhận diện người bệnh bằng hai thông tin: mời người bệnh tự nói họ tên và ngày sinh, đối chiếu vòng tay và phiếu. Không dùng số giường, không hỏi kiểu “có phải bác … không”.',
            'Sát khuẩn tay trước và sau khi chạm người bệnh. Đeo găng không thay được việc sát khuẩn tay.',
            'Trước khi cho thuốc: đúng người, đúng thuốc trên phiếu y lệnh, nhãn khay khớp y lệnh, xem vòng dị ứng so với nhóm thuốc. Có gì không khớp: giữ lại, báo bác sĩ.',
            'Y lệnh có dòng dặn (đo đường huyết trước, nhịn ăn chờ thủ thuật) thì làm đúng dòng dặn. Không tự thêm, bớt, đổi thuốc; thuốc trong túi mình không bao giờ đưa người bệnh.',
            'Đo dấu hiệu sinh tồn rồi ghi đúng số đo thật. Chỉ số ngoài thẻ báo động thì báo bác sĩ ngay, nói rõ chỉ số nào. Số đo lạ so với người bệnh (kẹp ngón lỏng, tay lạnh) thì đo lại.',
            'Người bệnh có quyền từ chối: hỏi vì sao, giải thích, vẫn không đồng ý thì giữ lại, báo bác sĩ, ghi hồ sơ. Không ép, không dọa.',
            'Trước thủ thuật: giấy cam đoan có bác sĩ giải thích và người bệnh ký, nhịn ăn đúng giờ, ghi dị ứng, tháo trang sức. Ăn rồi hoặc đổi ý thì không chuyển đi.',
            'Không nhận phong bì, quà của người bệnh. Không kể bệnh của người này cho người khác. Không quay, đăng hình người bệnh. Ghi sổ giao ca đúng điều đã xảy ra.',
        ],
        practice=[
            _p('Bạn sắp cho thuốc ở giường 3. Cách xác định người bệnh nào đúng?',
               [('a', 'Hỏi “Bà là bà Tư phải không ạ?”'), ('b', 'Mời bà tự nói họ tên, ngày sinh, đối chiếu vòng tay'), ('c', 'Nhìn số giường')], 'b',
               'Hai thông tin do người bệnh tự nói, đối chiếu vòng tay.'),
            _p('Vòng dị ứng ghi “nhóm P”, phiếu y lệnh ghi kháng sinh nhóm P.',
               [('a', 'Cho theo y lệnh'), ('b', 'Giữ lại, báo bác sĩ'), ('c', 'Cho một nửa')], 'b', 'Trùng nhóm dị ứng: giữ lại và báo bác sĩ.'),
            _p('Máy kẹp ngón báo SpO2 84%, người bệnh nói chuyện bình thường, tay lạnh, kẹp lỏng.',
               [('a', 'Chỉnh kẹp, xoa ấm tay, đo lại ngón khác'), ('b', 'Ghi 84% rồi đi'), ('c', 'Tắt máy cho đỡ kêu')], 'a', 'Số đo lạ so với người bệnh thì đo lại cho chắc.'),
            _p('Người nhà dúi phong bì “cảm ơn”.',
               [('a', 'Nhận cho người nhà vui'), ('b', 'Cảm ơn, không nhận, mời viết vào sổ góp ý'), ('c', 'Nhận rồi bỏ quỹ khoa')], 'b', 'Không nhận phong bì.'),
        ],
        bank=[
            _q('ps_id', 'Hai người bệnh trùng tên trong khoa. Trước khi cho thuốc, bạn làm gì?',
               [('a', 'Gọi tên to, ai dạ thì đưa'), ('b', 'Mời người bệnh tự nói họ tên và ngày sinh, đối chiếu vòng tay và phiếu'), ('c', 'Xem số giường')], 'b',
               'Hai thông tin: họ tên và ngày sinh, đối chiếu vòng tay.'),
            _q('ps_hands', 'Đồng nghiệp bảo: “Đeo găng rồi khỏi sát khuẩn tay.”',
               [('a', 'Làm theo cho nhanh'), ('b', 'Vẫn sát khuẩn tay trước khi chạm người bệnh'), ('c', 'Rửa tay cuối ca là đủ')], 'b',
               'Đeo găng không thay được sát khuẩn tay.'),
            _q('ps_label', 'Nhãn khay của khoa dược ghi một thuốc, phiếu y lệnh ghi thuốc khác.',
               [('a', 'Cho theo nhãn khay'), ('b', 'Cho theo phiếu'), ('c', 'Giữ lại, báo khoa dược và bác sĩ')], 'c', 'Nhãn khay không khớp y lệnh thì giữ lại, hỏi lại.'),
            _q('ps_sugar', 'Y lệnh ghi: “Đo đường huyết trước; máy báo THẤP thì giữ thuốc, báo bác sĩ.” Máy báo THẤP.',
               [('a', 'Giữ thuốc, báo bác sĩ ngay'), ('b', 'Tiêm theo giờ'), ('c', 'Đo lại ngày mai')], 'a', 'Làm đúng dòng dặn của y lệnh.'),
            _q('ps_npo', 'Người bệnh nhịn ăn chờ nội soi, phiếu có thuốc uống lúc 8 giờ.',
               [('a', 'Cho uống như thường'), ('b', 'Giữ lại, hỏi bác sĩ'), ('c', 'Cho uống với ít nước')], 'b', 'Đang nhịn ăn uống chờ thủ thuật thì hỏi lại bác sĩ.'),
            _q('ps_own', 'Người bệnh xin viên giảm đau, trong túi bạn có sẵn một vỉ.',
               [('a', 'Đưa luôn cho đỡ đau'), ('b', 'Không đưa thuốc của mình; hỏi đau, báo bác sĩ'), ('c', 'Đưa nửa viên')], 'b', 'Thuốc của mình không bao giờ đưa người bệnh.'),
            _q('ps_alarm', 'Nhiệt độ 38,9 °C, ngoài thẻ báo động. Bạn làm gì?',
               [('a', 'Ghi phiếu rồi đi tiếp'), ('b', 'Báo bác sĩ ngay, nói rõ chỉ số'), ('c', 'Chờ tới lượt đo sau')], 'b', 'Ngoài thẻ báo động thì báo bác sĩ ngay.'),
            _q('ps_chart', 'Gần giao ca, đồng nghiệp bảo chép số đo hôm qua vào phiếu cho kịp.',
               [('a', 'Chép cho kịp'), ('b', 'Đi đo thật, ghi đúng số'), ('c', 'Bỏ trống phiếu')], 'b', 'Chỉ ghi điều mình thật sự đo.'),
            _q('ps_refuse', 'Người bệnh không chịu uống thuốc, đã giải thích mà vẫn không đồng ý.',
               [('a', 'Nhờ người nhà giữ tay cho uống'), ('b', 'Giữ lại, báo bác sĩ, ghi hồ sơ'), ('c', 'Bỏ qua, không cần báo')], 'b', 'Tôn trọng quyền từ chối, báo bác sĩ.'),
            _q('ps_consent', 'Giấy cam đoan nội soi còn trống, người bệnh đang sợ.',
               [('a', 'Ký giùm cho kịp giờ'), ('b', 'Mời bác sĩ giải thích, người bệnh tự quyết và ký'), ('c', 'Chuyển đi, ký sau')], 'b',
               'Giấy cam đoan phải có bác sĩ giải thích và người bệnh tự ký.'),
            _q('ps_ate', 'Người bệnh chờ nội soi nói sáng nay lỡ uống ly sữa.',
               [('a', 'Vẫn chuyển đi'), ('b', 'Giữ lại, báo bác sĩ'), ('c', 'Bảo người bệnh đừng nói ai')], 'b', 'Ăn uống rồi thì chưa chuyển đi thủ thuật.'),
            _q('ps_envelope', 'Người nhà dúi phong bì xin xếp giường gần cửa sổ.',
               [('a', 'Nhận, xếp giường đẹp'), ('b', 'Không nhận; giường xếp theo bệnh'), ('c', 'Nhận rồi bỏ quỹ khoa')], 'b', 'Không nhận phong bì; giường xếp theo bệnh.'),
            _q('ps_privacy', 'Hàng xóm của người bệnh xin xem bệnh án.',
               [('a', 'Cho xem chút'), ('b', 'Không cho; chỉ người bệnh và người được ủy quyền'), ('c', 'Kể sơ cho vui')], 'b', 'Giữ bí mật bệnh tình của người bệnh.'),
        ]),
    # A craft certificate (hire=False): the ice-cream shop does not hire through an interview, so this one
    # carries a perk instead of the hire bonus (game/careers/ice_cream.py reads it: the khoai môn recipe).
    dict(
        id='ice_cream_craft', emoji='🍨', name='Chứng chỉ làm kem', short='Làm kem',
        issuer='Bếp nghề phường cùng tiệm kem Góc Phượng (lớp giả lập)', careers=('ice_cream',), fee=15, hire=False,
        perk='Cô Hiền dạy công thức kem khoai môn nhà làm ở Tiệm kem Góc Phượng.',
        intro='Giữ tủ kem đúng nhiệt, múc viên đủ gam, nấu một mẻ kem nhà làm cho mịn, bán sạch sẽ và an toàn.',
        notes=[
            'Tủ kem để ở −18 °C (nút số 4). Từ −12 °C kem mềm, viên to, mau chảy; từ −9 °C là nhão. Múc xong ly nào đậy nắp ly đó.',
            'Hộp kem đã chảy rồi đông lại (mặt lổn nhổn tinh thể đá) thì bỏ, không bán. Chiều nào tủ lên tới −8 °C, sáng mai soi kỹ từng hộp.',
            'Viên kem chuẩn 60–70 gam trên cân. Kem cứng múc sâu tay, kem mềm múc nhẹ tay. Hộp mang về: trừ bì hộp rỗng trước khi múc.',
            'Nước ngâm muỗng thay mỗi sáng, đục là thay. Khách dặn dị ứng đậu phộng thì không rắc đậu phộng, kể cả một hạt.',
            'Kem dừa nhà làm: đong đúng công thức, nấu lửa nhỏ, khuấy đều tới 76–88 °C thì hỗn hợp sánh, tắt bếp. Để sôi là nước cốt tách dầu, kem lợn cợn; khét đáy nồi thì đổ bỏ.',
            'Nấu xong ngâm nồi vào thau nước đá cho nguội dưới 10 °C rồi mới cho vào máy đánh kem. Còn ấm mà đánh là kem mềm, mau chảy.',
            'Máy đánh kem chạy đúng giờ trong sổ (kem dừa 25–30 phút). Ít quá kem còn lỏng; lâu quá béo kết hạt. Đổ hộp, dán nhãn ngày, đông qua đêm mới bán.',
            'Đong thiếu đường hay thiếu bột năng là kem dăm đá; dư đường là kem mềm. Mẻ không đạt thì nói thật: đổ bỏ, ghi hao hụt, không trộn vào hộp tốt.',
        ],
        practice=[
            _p('Nhiệt kế tủ kem chỉ −13 °C. Bạn làm gì?',
               [('a', 'Vặn nút về số 4 (−18 °C), đậy nắp'), ('b', 'Múc đầy tay cho kịp'), ('c', 'Mở nắp cho thoáng')], 'a', 'Tủ ấm thì kem mềm, viên to và mau chảy.'),
            _p('Sổ ghi “5 muỗng canh đường, muỗng 20 g”. Đong bao nhiêu?',
               [('a', '60 g'), ('b', '100 g'), ('c', '160 g')], 'b', '5 × 20 = 100 g.'),
            _p('Hỗn hợp kem dừa đang 91 °C, sủi lăn tăn.',
               [('a', 'Tắt bếp ngay'), ('b', 'Vặn lửa lớn cho mau sánh'), ('c', 'Đun thêm mười phút')], 'a', 'Để sôi là nước cốt dừa tách dầu, kem lợn cợn.'),
            _p('Khách dặn: “Bé nhà chị dị ứng đậu phộng.” Ly kem gọi kèm topping giòn.',
               [('a', 'Rắc đậu phộng, ít thôi'), ('b', 'Rắc bánh quế vụn'), ('c', 'Rắc đậu phộng rồi nhặt ra')], 'b', 'Dị ứng là không một hạt nào.'),
        ],
        bank=[
            _q('ic_knob', 'Sáng ra nút tủ kem đang ở số 2 (−13 °C). Bạn làm gì trước khi bán?',
               [('a', 'Vặn về số 4 (−18 °C) rồi mới bán'), ('b', 'Để vậy, kem mềm dễ múc'), ('c', 'Vặn số 6 cho thật lạnh')], 'a',
               'Số 4 là −18 °C: kem đủ cứng, viên đủ gam, không mau chảy.'),
            _q('ic_refrozen', 'Một hộp kem mặt lổn nhổn tinh thể đá sau buổi chiều cúp điện.',
               [('a', 'Múc bán trước cho hết'), ('b', 'Bỏ hộp đó, ghi hao hụt'), ('c', 'Trộn với hộp mới')], 'b',
               'Kem chảy rồi đông lại thì không bán.'),
            _q('ic_scoop', 'Viên kem trên cân 47 gam. Chuẩn là bao nhiêu?',
               [('a', '40–50 gam là đủ'), ('b', '60–70 gam'), ('c', 'Bao nhiêu cũng được')], 'b', 'Viên chuẩn 60–70 gam; thiếu thì múc thêm.'),
            _q('ic_lid', 'Đang làm ly hai viên, giữa hai lần múc nắp tủ nên thế nào?',
               [('a', 'Mở luôn cho nhanh'), ('b', 'Đậy lại'), ('c', 'Tháo nắp ra')], 'b', 'Để nắp mở là tủ ấm nhanh, kem mềm nhão.'),
            _q('ic_tare', 'Khách lấy hộp 500 gam mang về. Bước đầu tiên trên cân?',
               [('a', 'Đặt hộp rỗng, trừ bì'), ('b', 'Múc kem vào rồi trừ bì'), ('c', 'Cân luôn cả hộp')], 'a', 'Trừ bì khi hộp còn rỗng.'),
            _q('ic_allergy', 'Khách dặn dị ứng đậu phộng mà lỡ rắc đậu phộng rồi.',
               [('a', 'Gạt bớt rồi đưa'), ('b', 'Bỏ ly đó, làm ly mới, rắc topping khác'), ('c', 'Đưa luôn, ít thôi')], 'b',
               'Dị ứng là lỗi an toàn: làm lại ly mới.'),
            _q('ic_well', 'Thau nước ngâm muỗng từ hôm qua đã đục.',
               [('a', 'Thay nước sạch'), ('b', 'Lau muỗng bằng khăn'), ('c', 'Để chiều thay')], 'a', 'Nước ngâm muỗng thay mỗi sáng, đục là thay.'),
            _q('ic_cook', 'Nấu hỗn hợp kem dừa tới khi nào thì tắt bếp?',
               [('a', 'Khoảng 76–88 °C, hỗn hợp sánh lại'), ('b', 'Khi sôi bùng lên'), ('c', 'Vừa ấm tay là được')], 'a',
               'Chưa tới thì bột chưa chín (kem dăm đá); sôi là tách dầu.'),
            _q('ic_cool', 'Hỗn hợp vừa nấu xong còn 60 °C. Cho vào máy đánh kem luôn được không?',
               [('a', 'Được, máy tự làm lạnh'), ('b', 'Ngâm thau nước đá cho dưới 10 °C rồi mới đánh'), ('c', 'Để qua đêm ngoài bếp')], 'b',
               'Đánh khi còn ấm thì kem mềm, mau chảy.'),
            _q('ic_churn', 'Sổ ghi kem dừa đánh 25–30 phút. Hẹn máy bao lâu?',
               [('a', '15 phút cho nhanh'), ('b', '30 phút'), ('c', '45 phút cho thật bông')], 'b', 'Ít quá kem lỏng; lâu quá béo kết hạt.'),
            _q('ic_sugar', 'Đong thiếu đường so với công thức thì kem ra sao?',
               [('a', 'Nhiều dăm đá'), ('b', 'Mềm, mau chảy'), ('c', 'Không sao')], 'a', 'Đường giữ kem mịn; thiếu đường kem đông thành dăm đá.'),
            _q('ic_burnt', 'Nồi kem bị khét đáy. Bạn làm gì?',
               [('a', 'Múc phần trên đánh kem'), ('b', 'Đổ bỏ cả mẻ, ghi hao hụt'), ('c', 'Thêm đường cho át mùi')], 'b',
               'Mùi khét ngấm cả mẻ; đổ bỏ, không bán.'),
        ]),
    # The ward library and archive (hire=False: the library does not hire through an interview). Archive work is a
    # regulated trade; holding this pays the archive allowance on every records request (game/careers/library.py).
    dict(
        id='archive_craft', emoji='🗂️', name='Chứng chỉ nghiệp vụ lưu trữ', short='Lưu trữ',
        issuer='Trung tâm bồi dưỡng nghiệp vụ quận cùng Thư viện phường Mây (lớp giả lập)', careers=('library',), fee=15, hire=False,
        perk='Phường trả thêm phụ cấp lưu trữ cho mỗi lượt hồ sơ ở Thư viện – Lưu trữ phường Mây.',
        intro='Giữ kho khô ráo, tiếp cận hồ sơ đúng quy định, giữ kín thông tin cá nhân, cấp bản sao chứ không đưa bản gốc, ghi sổ đủ.',
        notes=[
            'Kho giấy giữ độ ẩm 45–60%. Cao hơn thì bật máy hút ẩm, kéo kệ cách tường; thấy mốc thì cách ly, không lau bằng khăn ướt.',
            'Thấy mọt sách: cho sách bị mọt vào túi kín, báo khử trùng. Không xịt thuốc diệt côn trùng thẳng lên sách.',
            'Ba mức tiếp cận: tài liệu mở ai cũng đọc được; hồ sơ cá nhân chỉ chính chủ, người thân có giấy tờ hoặc người được ủy quyền; tài liệu hạn chế cần lãnh đạo ký duyệt.',
            'Người xin hồ sơ: xem căn cước, giấy tờ chứng minh quyền (ủy quyền có chứng thực, giấy chứng tử và giấy tờ quan hệ khi làm thừa kế), điền phiếu yêu cầu.',
            'Thiếu giấy tờ thì hướng dẫn rõ còn thiếu gì; việc không được phép (xem hồ sơ người khác, sửa hồ sơ, rút trang) thì từ chối và chỉ nơi làm đúng.',
            'Bản gốc không rời kho: cấp bản sao có dấu “sao y bản lưu trữ”. Cho mượn bản gốc trong cơ quan chỉ khi có phiếu đã duyệt và người nhận ký.',
            'Mở hộp hồ sơ cũ: găng tay vải sạch, khẩu trang; cầm nhẹ tay giấy giòn. Mọi lượt khai thác ghi vào sổ, người nhận ký.',
            'Mục lục ghi mà không thấy hồ sơ: tìm các hộp kế bên, xem sổ giao nhận trước. Chỉ lập biên bản thất lạc khi đã tìm kỹ.',
        ],
        practice=[
            _p('Ẩm kế kho chỉ 68%. Bạn làm gì?', [('a', 'Bật máy hút ẩm, kiểm giấy trong hộp'), ('b', 'Mở toang cửa sổ cho thoáng'), ('c', 'Để đó, chiều xem')], 'a',
               'Kho giấy giữ 45–60%.'),
            _p('Người hàng xóm xin xem hồ sơ đất nhà bên cạnh.', [('a', 'Cho xem nhanh'), ('b', 'Từ chối, hướng dẫn đề nghị qua bộ phận địa chính'), ('c', 'Cho chụp một trang')], 'b',
               'Hồ sơ cá nhân của người khác không cấp khi không có quyền.'),
            _p('Bản gốc giấy phép xây dựng năm 1996, người dân muốn mang đi công chứng.', [('a', 'Cho mượn một buổi'), ('b', 'Cấp bản sao có dấu sao y'), ('c', 'Cho mang đi, ghi nợ')], 'b',
               'Bản gốc không rời kho.'),
            _p('Mở hộp hồ sơ bụi năm 1980.', [('a', 'Găng tay vải, khẩu trang'), ('b', 'Tay không cho nhanh'), ('c', 'Lau bụi bằng khăn ướt')], 'a',
               'Mồ hôi tay làm ố giấy; bụi cũ không tốt cho phổi.'),
        ],
        bank=[
            _q('lt_hum', 'Độ ẩm kho giấy nên giữ trong khoảng nào?', [('a', '30–40%'), ('b', '45–60%'), ('c', '70–80%')], 'b',
               'Quá ẩm giấy mốc, quá khô giấy giòn.'),
            _q('lt_mould', 'Ba cuốn sách mốc trắng mép trên kệ sát tường.', [('a', 'Lau bằng khăn ướt'), ('b', 'Cách ly vào túi, kéo kệ cách tường, báo phụ trách'), ('c', 'Xếp lại chỗ cũ')], 'b',
               'Khăn ướt làm mốc ăn sâu hơn.'),
            _q('lt_mot', 'Dưới kệ có bụi gỗ vàng li ti, trang sách thủng lỗ nhỏ.', [('a', 'Xịt thuốc lên kệ'), ('b', 'Cho sách bị mọt vào túi kín, báo khử trùng'), ('c', 'Để đó')], 'b',
               'Thuốc xịt dính lên sách, độc cho người đọc.'),
            _q('lt_self', 'Bà cụ xin bản sao giấy phép xây nhà của chính mình, có căn cước.', [('a', 'Cấp bản sao, điền phiếu yêu cầu'), ('b', 'Bắt xin lãnh đạo duyệt'), ('c', 'Từ chối')], 'a',
               'Chính chủ có giấy tờ thì được cấp.'),
            _q('lt_heir', 'Con gái xin hồ sơ hộ khẩu cũ của bố đã mất để làm thừa kế, quên giấy chứng tử.', [('a', 'Cấp luôn cho nhanh'), ('b', 'Hướng dẫn mang thêm giấy chứng tử, giấy tờ quan hệ'), ('c', 'Từ chối hẳn')], 'b',
               'Thiếu giấy tờ thì hướng dẫn bổ sung.'),
            _q('lt_neighbor', 'Ai đó xin xem hồ sơ đất nhà hàng xóm “để kiện”.', [('a', 'Từ chối, chỉ nơi làm đúng thủ tục'), ('b', 'Cho xem, không chụp'), ('c', 'Cho chụp một trang')], 'a',
               'Hồ sơ cá nhân không cấp cho người không có quyền.'),
            _q('lt_restricted', 'Hồ sơ lý lịch cán bộ (tài liệu hạn chế) cho người viết sách.', [('a', 'Cấp luôn'), ('b', 'Trình lãnh đạo ký duyệt'), ('c', 'Cho đọc tại chỗ không cần ai biết')], 'b',
               'Tài liệu hạn chế phải có lãnh đạo duyệt.'),
            _q('lt_original', 'Người xin muốn mang bản gốc ra tiệm photo đầu ngõ cho rẻ.', [('a', 'Cho mang đi, dặn giữ kỹ'), ('b', 'Sao tại thư viện, bản gốc ở lại'), ('c', 'Cho mang, giữ căn cước làm tin')], 'b',
               'Bản gốc không rời kho.'),
            _q('lt_vip', 'Phó Chủ tịch phường cần hồ sơ gấp, bảo “sổ với phiếu để sau”.', [('a', 'Mang lên ngay kèm phiếu, xin ký'), ('b', 'Mang lên, khỏi ghi sổ'), ('c', 'Bắt chờ đủ thủ tục ở kho')], 'a',
               'Gấp vẫn ghi sổ, mang phiếu tới tận nơi.'),
            _q('lt_missing', 'Mục lục ghi hồ sơ ở hộp 12 mà mở ra không thấy.', [('a', 'Lập biên bản mất ngay'), ('b', 'Tìm các hộp kế bên, xem sổ giao nhận'), ('c', 'Bảo người xin về')], 'b',
               'Hồ sơ hay kẹp nhầm hộp bên, hoặc đang có phòng ban mượn.'),
            _q('lt_edit', 'Bà cụ nhờ sửa năm sinh trong sổ cũ cho khớp căn cước.', [('a', 'Sửa một nét bút'), ('b', 'Từ chối, hướng dẫn thủ tục đính chính'), ('c', 'Dán giấy ghi chú đè lên')], 'b',
               'Hồ sơ lưu trữ không được sửa tay.'),
            _q('lt_log', 'Cấp bản sao xong. Việc cuối trước khi trả hộp về kệ?', [('a', 'Ghi sổ khai thác, người nhận ký'), ('b', 'Không cần ghi'), ('c', 'Ghi vào giấy nháp')], 'a',
               'Mọi lượt khai thác đều ghi sổ.'),
        ]),
]
