"""Content for 🎓 Thi chứng chỉ (game/certificates.py): certificate groups, the
lesson notes read while studying, a small practice quiz (checked in the browser,
separate from the exam bank) and the exam bank (the answer key stays on the server).

Each group covers related hired jobs; holding it raises the hire chance there
(employment._evaluate). Facts come from the game's own rules (career plugins,
employment_content, tax_payroll.RULES…). Everything is a simplified GAME rule
written in xu, not professional, medical, tax or legal advice.

Shapes:
* GROUPS: {id, emoji, name, short, issuer, careers, fee, intro, notes[str],
  practice[{text, options[{id, label}], answer, why}], bank[same, plus id]}.
"""
from __future__ import annotations


def _q(qid, text, options, answer, why):
    return dict(id=qid, text=text, options=[dict(id=k, label=v) for k, v in options], answer=answer, why=why)


def _p(text, options, answer, why):
    return dict(text=text, options=[dict(id=k, label=v) for k, v in options], answer=answer, why=why)


GROUPS = [
    dict(
        id='work_safety', emoji='🦺', name='Chứng chỉ An toàn lao động', short='An toàn lao động',
        issuer='Trung tâm dạy nghề phường (lớp giả lập)', careers=('delivery', 'repair'), fee=15,
        intro='An toàn điện khi sửa đồ, an toàn đường sá khi giao hàng, giữ đồ và tiền của khách cho đúng.',
        notes=[
            'Máy điện: rút điện trước khi mở. Quạt còn tụ giữ điện, phải xả tụ bằng điện trở. Nồi cơm chờ mâm nhiệt nguội. Điện thoại, laptop tắt nguồn và ngắt cáp pin.',
            'Dây nguồn chảy nhựa, có mùi khét: báo khách ngưng dùng, thay dây đúng loại, đo cách điện trước khi giao. Băng keo không cứu được dây đã chảy.',
            'Đo trước, thay sau. Báo giá rõ trước khi sửa; sửa tốn gần bằng mua mới thì nói thật để khách chọn.',
            'Đồ của khách là của khách: không mở ảnh, tin nhắn. Phiếu nhận ghi tình trạng máy (vết nứt, trầy) và phụ kiện đi kèm.',
            'Xe giao hàng chở tối đa 20 kg. Hàng dễ vỡ lót xốp hơi, đồ lạnh có túi giữ lạnh, trời mưa bọc túi chống nước.',
            'Đường ngập, mưa to: tấp vào chỗ an toàn, báo điều phối và khách giờ giao mới. Không đơn nào đáng để liều.',
            'Tiền thu hộ (COD): đếm trước mặt khách, thối đủ tới từng xu, ghi phiếu. Túi tiền quá 250 xu thì về bưu cục nộp trước.',
            'Thư bảo đảm giao tận tay người nhận, không gửi bảo vệ. Địa chỉ thiếu: gọi, nhắn khách, hỏi quy định giữ hàng, báo điều phối.',
        ],
        practice=[
            _p('Sửa xe đạp: bước an toàn trước khi tháo bánh?',
               [('a', 'Dựng xe lên giá, khóa bánh'), ('b', 'Dựng nghiêng vào tường'), ('c', 'Đặt nằm dưới sàn')], 'a',
               'Xe không dựng giá dễ đổ, xước thêm một vệt mới.'),
            _p('Đơn thu hộ 327 xu, khách đưa tờ 500 xu. Bạn thối bao nhiêu?',
               [('a', '170 xu cho chẵn'), ('b', '173 xu'), ('c', '183 xu')], 'b', '500 − 327 = 173 xu, đếm trước mặt khách.'),
            _p('Đơn có hũ sữa chua. Bạn mang theo gì?',
               [('a', 'Không cần gì thêm'), ('b', 'Xốp hơi'), ('c', 'Túi giữ lạnh')], 'c', 'Đồ lạnh cần túi giữ lạnh cho tới tay khách.'),
            _p('Máy nào phải xả tụ trước khi mở?',
               [('a', 'Quạt đứng'), ('b', 'Tai nghe'), ('c', 'Xe đạp')], 'a', 'Tụ khởi động của quạt vẫn giữ điện sau khi rút phích.'),
        ],
        bank=[
            _q('ws_fan', 'Khách mang tới cái quạt đứng không quay. Trước khi mở hộp tụ, bạn làm gì?',
               [('a', 'Rút điện rồi xả tụ bằng điện trở'), ('b', 'Cắm điện nghe thử mô-tơ rồi mở luôn'),
                ('c', 'Mở nhanh vì quạt nhỏ, điện yếu')], 'a', 'Tụ quạt còn giữ điện sau khi rút phích; phải xả tụ trước khi chạm vào.'),
            _q('ws_cooker', 'Nồi cơm điện khách vừa mang tới còn ấm tay. Bạn mở thế nào?',
               [('a', 'Lật đáy ngay cho kịp'), ('b', 'Rút điện, chờ mâm nhiệt nguội rồi mới lật đáy'),
                ('c', 'Đeo găng vải, mở khi còn cắm điện')], 'b', 'Mâm nhiệt còn nóng gây bỏng; nồi phải rút điện và nguội hẳn.'),
            _q('ws_phone', 'Thay pin điện thoại: bước an toàn đầu tiên?',
               [('a', 'Cắm sạc cho máy khỏi sập nguồn'), ('b', 'Tách màn khi máy còn mở để xem cảm ứng'),
                ('c', 'Tắt nguồn và ngắt cáp pin trước khi tách màn')], 'c', 'Còn nguồn mà tách màn dễ tóe lửa ở cáp pin.'),
            _q('ws_cord', 'Dây nguồn nồi cơm chảy nhựa, có mùi khét.',
               [('a', 'Báo khách ngưng dùng, thay dây đúng loại, đo cách điện trước khi giao'), ('b', 'Quấn băng keo thật kín'),
                ('c', 'Trả máy, dặn khách dùng tạm')], 'a', 'Dây đã chảy nhựa quấn băng keo vẫn có thể chập cháy.'),
            _q('ws_quote', 'Thay mô-tơ quạt tốn gần bằng mua quạt mới. Bạn làm gì?',
               [('a', 'Cứ sửa rồi báo giá sau'), ('b', 'Báo giá rõ, nói thật mua mới có thể hợp hơn, để khách chọn'),
                ('c', 'Nói là không sửa được')], 'b', 'Khách có quyền chọn khi biết đủ thông tin.'),
            _q('ws_data', 'Điện thoại khách gửi thay màn hình không cài khóa.',
               [('a', 'Mở thư viện ảnh để thử cảm ứng'), ('b', 'Cài lại máy cho sạch lỗi'),
                ('c', 'Chỉ làm phần màn hình, không mở ảnh, tin nhắn; ghi tình trạng máy vào phiếu')], 'c',
               'Dữ liệu của khách là riêng tư; cài lại máy làm khách mất hết ảnh.'),
            _q('ws_intake', 'Nhận máy sửa, bạn ghi gì vào phiếu nhận?',
               [('a', 'Tình trạng máy (vết nứt, trầy) và phụ kiện đi kèm'), ('b', 'Chỉ tên và số điện thoại khách'),
                ('c', 'Không cần phiếu, nhớ trong đầu là được')], 'a',
               'Ghi rõ lúc nhận để khi trả máy không ai phải cãi nhau về vết trầy hay cục sạc.'),
            _q('ws_load', 'Xe giao hàng của bưu cục chở tối đa bao nhiêu?',
               [('a', '20 kg'), ('b', '35 kg nếu buộc chặt'), ('c', 'Không giới hạn nếu chạy chậm')], 'a',
               'Quá tải làm xe khó phanh, dễ đổ.'),
            _q('ws_fragile', 'Đơn là một bình thủy tinh. Bạn đóng gói thế nào?',
               [('a', 'Để chung thùng cho gọn'), ('b', 'Lót xốp hơi, chằng riêng'), ('c', 'Cầm tay trong lúc chạy xe')], 'b',
               'Hàng dễ vỡ không lót sẽ vỡ trên đường, khách từ chối nhận.'),
            _q('ws_flood', 'Đường phía trước ngập nửa bánh xe, đơn sắp trễ hẹn.',
               [('a', 'Chạy băng qua cho kịp giờ'), ('b', 'Tắt máy chờ, không báo ai'),
                ('c', 'Tấp vào chỗ an toàn, bọc hàng, báo điều phối và khách giờ giao mới')], 'c',
               'Người về an toàn là đơn quan trọng nhất; báo sớm để khách biết mà chờ.'),
            _q('ws_cod', 'Đơn thu hộ 186 xu, khách đưa tờ 200 xu. Bạn thối bao nhiêu?',
               [('a', '14 xu, đếm trước mặt khách'), ('b', '10 xu cho chẵn'), ('c', '24 xu')], 'a',
               '200 − 186 = 14. Thối thiếu là mất uy tín của cả bưu cục.'),
            _q('ws_codcap', 'Túi tiền thu hộ đã hơn 250 xu, còn một đơn COD nữa.',
               [('a', 'Nhận tiếp, tối nộp một lần'), ('b', 'Về bưu cục nộp tiền trước rồi mới nhận thêm'),
                ('c', 'Gửi tiền nhờ quán quen giữ giùm')], 'b', 'Cầm nhiều tiền mặt trên đường là rủi ro; bưu cục có mức giới hạn.'),
            _q('ws_registered', 'Thư bảo đảm, người nhận đi vắng, bảo vệ chung cư đề nghị nhận giùm.',
               [('a', 'Gửi bảo vệ, chụp ảnh làm bằng'), ('b', 'Bỏ vào hộp thư'), ('c', 'Không gửi bảo vệ; hẹn giao lại, báo điều phối')], 'c',
               'Thư bảo đảm phải giao tận tay người nhận.'),
            _q('ws_address', 'Tới chung cư, đơn thiếu số phòng, khách không nghe máy.',
               [('a', 'Nhắn tin, gọi lại, hỏi bảo vệ quy định giữ hàng, báo điều phối'), ('b', 'Để hàng ở sảnh, chụp ảnh là xong'),
                ('c', 'Báo hủy đơn luôn')], 'a', 'Để hàng ở sảnh dễ mất, người giao phải đền.'),
            _q('ws_rain', 'Trời mưa dầm, đường trơn, còn ba đơn.',
               [('a', 'Chạy nhanh cho xong trước khi mưa to'), ('b', 'Chạy chậm, giữ khoảng cách, bọc hàng bằng túi chống nước'),
                ('c', 'Bỏ túi chống nước cho nhẹ xe')], 'b', 'Mưa làm đường trơn; hàng ướt là khách phàn nàn.'),
        ]),
    dict(
        id='grooming', emoji='✂️', name='Chứng chỉ Chăm sóc tóc & thú cưng', short='Chăm sóc tóc & thú cưng',
        issuer='Hội nghề chăm sóc khu phố (lớp giả lập)', careers=('salon', 'pet_care'), fee=15,
        intro='Hỏi trước làm sau, hóa chất an toàn ở salon, tắm sấy và đọc tín hiệu của chó mèo.',
        notes=[
            'Hỏi trước, làm sau: lịch sử tóc (nhuộm, uốn, duỗi gần đây); với thú cưng là sổ tiêm, dị ứng, da lông.',
            'Chưa có kết quả thử dị ứng thì thử thuốc sau tai trước, hẹn nhuộm từ ngày sau. Da đầu trầy, viêm: hôm đó không thoa hóa chất.',
            'Oxy: cùng tông hoặc tối hơn 10 vol; nâng 1–2 tông 20 vol; nâng 3 tông 30 vol; 40 vol không bao giờ thoa sát da đầu.',
            'Thuốc nhuộm không nâng được màu nhuộm cũ, muốn sáng hơn phải tẩy. Tóc nhuộm hộp: thử một lọn trước khi tẩy. Canh giờ thuốc, quá giờ là tóc khô cháy.',
            'Giữa hai khách: thay khăn, khử khuẩn lược kéo, quét tóc rồi mới mời ngồi.',
            'Tắm chó mèo: nước 36–39 °C. Giống mặt ngắn (Pug, Ba Tư mặt tịt) chỉ sấy nấc mát. Bé sợ thì dừng, quấn khăn, cho nghỉ; không ép.',
            'Móng đen: cắt từng chút ở đầu móng, để sẵn bột cầm máu. Thấy cục u hay bé bỏ ăn: báo chủ, khuyên đi thú y; không tự chẩn đoán, không tự cho thuốc.',
            'Nhận lưu trú: sổ tiêm phải còn hạn tới ngày chủ đón; trên 39,2 °C là sốt, chưa nhận.',
        ],
        practice=[
            _p('Tóc bạc từ một nửa trở lên: bát màu cần gì?',
               [('a', 'Toàn tuýp ánh tro'), ('b', 'Ít nhất một nửa là tuýp nền tự nhiên (x.0)'), ('c', 'Chỉ dùng toner')], 'b',
               'Tóc bạc nhiều cần nền tự nhiên để phủ đều.'),
            _p('Nhuộm, tẩy làm trên tóc thế nào?',
               [('a', 'Tóc khô chưa gội; xả thuốc xong mới gội'), ('b', 'Gội sạch rồi nhuộm khi tóc còn ướt'),
                ('c', 'Xả nước trước khi thoa')], 'a', 'Thuốc thoa trên tóc khô; gội sau khi xả thuốc.'),
            _p('Bé chó liếm mép, ngáp, đuôi kẹp trên bàn tắm nghĩa là gì?',
               [('a', 'Bé đang vui'), ('b', 'Bé buồn ngủ'), ('c', 'Bé đang lo: dỗ hoặc cho nghỉ rồi mới làm tiếp')], 'c',
               'Đó là tín hiệu căng thẳng; đọc tín hiệu trước mỗi bước.'),
            _p('Bé nhảy khỏi bàn, chạy quanh tiệm.',
               [('a', 'Đóng cửa, ngồi thấp, gọi nhỏ hoặc dụ bằng bánh nếu chủ cho'), ('b', 'Đuổi theo chụp lại'),
                ('c', 'Hét lớn cho bé đứng lại')], 'a', 'Đuổi hay chụp làm bé hoảng thêm.'),
        ],
        bank=[
            _q('gr_patch', 'Khách muốn nhuộm, salon chưa có kết quả thử dị ứng của khách.',
               [('a', 'Nhuộm luôn vì khách nói chưa từng bị dị ứng'), ('b', 'Thử thuốc sau tai trước, hẹn nhuộm từ ngày sau'),
                ('c', 'Nhuộm một nửa đầu để thử')], 'b', 'Chưa có kết quả thử dị ứng thì chưa thoa thuốc nhuộm.'),
            _q('gr_scalp', 'Da đầu khách có vết trầy, hơi đỏ. Khách vẫn muốn tẩy hôm nay.',
               [('a', 'Không thoa hóa chất hôm đó, hẹn lại khi da lành'), ('b', 'Tẩy nhanh cho đỡ rát'),
                ('c', 'Bôi kem dưỡng rồi tẩy')], 'a', 'Hóa chất trên da đầu trầy, viêm gây bỏng rát.'),
            _q('gr_vol_same', 'Nhuộm cùng tông hoặc tối hơn màu tóc tự nhiên: dùng oxy nào?',
               [('a', '30 vol (9%)'), ('b', '40 vol (12%)'), ('c', '10 vol (3%)')], 'c', 'Không cần nâng tông thì dùng oxy nhẹ nhất.'),
            _q('gr_vol_40', 'Oxy 40 vol (12%) được dùng thế nào?',
               [('a', 'Không bao giờ thoa sát da đầu'), ('b', 'Dùng cho mọi ca nhuộm cho nhanh'), ('c', 'Thoa sát chân tóc cho lên màu đều')], 'a',
               'Oxy mạnh sát da đầu gây bỏng.'),
            _q('gr_lift', 'Tóc đang nhuộm nâu, khách muốn sáng hơn hai tông. Cách đúng?',
               [('a', 'Nhuộm đè màu sáng hơn'), ('b', 'Phải tẩy, vì thuốc nhuộm không nâng được màu nhuộm cũ'),
                ('c', 'Trộn thuốc nhuộm với oxy 40 vol')], 'b', 'Màu nhuộm cũ chỉ đi ra khi tẩy.'),
            _q('gr_boxdye', 'Tóc khách từng nhuộm hộp ở nhà. Trước khi tẩy?',
               [('a', 'Pha bột tẩy đặc hơn'), ('b', 'Tẩy cả đầu luôn'), ('c', 'Thử một lọn trước')], 'c',
               'Thuốc nhuộm hộp có thể phản ứng với bột tẩy; thử lọn cho biết trước.'),
            _q('gr_timer', 'Thuốc màu đã đủ giờ nhà sản xuất ghi, thợ màu đang bận.',
               [('a', 'Thử một lọn, báo thợ màu, xả đúng giờ'), ('b', 'Để thêm hai mươi phút cho màu đậm'),
                ('c', 'Chờ thợ màu rảnh rồi tính')], 'a', 'Quá giờ thuốc làm tóc khô cháy.'),
            _q('gr_clean', 'Khách vừa đứng dậy, khách mới đã tới cửa.',
               [('a', 'Mời ngồi luôn, lau ghế sơ'), ('b', 'Thay khăn, khử khuẩn lược kéo, quét tóc rồi mới mời ngồi'),
                ('c', 'Dùng lại khăn nếu còn khô')], 'b', 'Sạch sẽ là lời chào đầu tiên của tiệm.'),
            _q('gr_water', 'Nước tắm cho chó mèo nên ở khoảng nào?',
               [('a', 'Nước lạnh cho bé tỉnh'), ('b', 'Càng nóng càng sạch'), ('c', '36–39 °C')], 'c', 'Nước ấm vừa thân nhiệt, không làm bé giật mình.'),
            _q('gr_flatface', 'Sấy cho một bé Pug mặt ngắn.',
               [('a', 'Chỉ sấy nấc mát, để xa mặt'), ('b', 'Sấy nấc nóng cho mau khô'), ('c', 'Chĩa máy thẳng vào mặt cho nhanh')], 'a',
               'Hơi ấm phả vào mặt làm giống mặt ngắn khó thở.'),
            _q('gr_scared', 'Con mèo sợ máy sấy, gồng người và rít lên.',
               [('a', 'Giữ chặt để sấy cho xong'), ('b', 'Tắt máy, cho bé nghỉ, quấn khăn, sấy nhẹ để xa'), ('c', 'Đeo rọ mõm cho bé')], 'b',
               'Không ép một bé đang hoảng; rọ mõm không bao giờ dùng cho mèo.'),
            _q('gr_nails', 'Cắt móng cho chó móng đen, không thấy lòng móng.',
               [('a', 'Cắt một nhát cho gọn'), ('b', 'Cắt sát cho lâu mọc'), ('c', 'Cắt từng chút đầu móng, soi mặt cắt, để sẵn bột cầm máu')], 'c',
               'Cắt sâu chạm lòng móng làm bé đau, chảy máu.'),
            _q('gr_lump', 'Đang tắm, bạn thấy một cục u nhỏ dưới da bé.',
               [('a', 'Báo chủ khi trả bé, khuyên đi bác sĩ thú y; không tự chẩn đoán'), ('b', 'Nói với chủ là u lành, không sao'),
                ('c', 'Im lặng cho chủ khỏi lo')], 'a', 'Người chăm sóc không phải bác sĩ thú y; báo sớm để chủ đưa bé đi khám.'),
            _q('gr_fever', 'Nhận bé lưu trú, nhiệt kế đo 39,6 °C.',
               [('a', 'Nhận, cho bé nằm chỗ mát'), ('b', 'Chưa nhận, mời chủ đưa bé đi khám vì bé đang sốt'),
                ('c', 'Nhận và cho uống thuốc hạ sốt')], 'b', 'Trên 39,2 °C là sốt; không nhận lưu trú, không tự cho thuốc.'),
            _q('gr_vaccine', 'Sổ tiêm của bé còn hạn tới hôm nay, chủ gửi bé ba ngày.',
               [('a', 'Nhận vì hôm nay còn hạn'), ('b', 'Nhận rồi nhắc chủ đi tiêm sau'),
                ('c', 'Chưa nhận: sổ tiêm phải còn hạn tới ngày chủ đón bé')], 'c', 'Bé ở cùng các bé khác suốt thời gian lưu trú.'),
        ]),
    dict(
        id='customer_service', emoji='🎧', name='Chứng chỉ Chăm sóc khách hàng', short='Chăm sóc khách hàng',
        issuer='Trạm Lắng Nghe phối hợp phường (lớp giả lập)', careers=('customer_care', 'pharmacy', 'tour_guide'), fee=20,
        intro='Lắng nghe, hẹn điều mình giữ được, biết mình được làm tới đâu và giữ kín thông tin của khách.',
        notes=[
            'Đọc lịch sử trước khi nghe máy; tóm tắt điều đã biết để khách không phải kể lại từ đầu.',
            'Xác minh mã yêu cầu của chủ đơn trước khi nói chi tiết. Đọc đủ nguồn (đơn, kho, vận chuyển) rồi mới đề nghị phương án.',
            'Hẹn một mốc mình giữ được và gọi lại đúng hẹn. Vụ đang chờ thì gọi cập nhật trong ngày, trước buổi trưa.',
            'Chỉ hứa điều nơi mình làm được (hoàn phí ship, mã bù). Khách đòi ngoài quyền: nói rõ, chuyển người có quyền kèm bản tóm tắt.',
            'Khách giận: xin lỗi vì khách phải chờ, đừng bảo “bình tĩnh lại”. Bị xúc phạm: nhắc nhẹ ranh giới, không cãi lại.',
            'Biết mình được làm tới đâu: ở quầy thuốc không tự đưa liều, không tự chọn thuốc cho trẻ. Không biết thì nói thật và hỏi người biết.',
            'Thông tin của khách là riêng tư: không kể ai mua gì, ở đâu, gọi về chuyện gì.',
            'Dẫn đoàn: đếm người trước khi đi và sau mỗi điểm dừng; mưa to thì vào chỗ có mái che, đừng đứng dưới gốc cây.',
        ],
        practice=[
            _p('Khi nào nên chuyển khách cho quản lý?',
               [('a', 'Ngay khi khách hơi to tiếng'), ('b', 'Khi khách cần điều ngoài quyền của mình, kèm bản tóm tắt'), ('c', 'Không bao giờ')], 'b',
               'Chuyển kèm tóm tắt để khách không phải kể lại.'),
            _p('Khách nói giọng địa phương khó nghe.',
               [('a', 'Xin phép nhắc lại ý chính để chắc mình hiểu đúng'), ('b', 'Đoán ý rồi làm'), ('c', 'Bảo khách nói giọng khác')], 'a',
               'Nhắc lại ý chính giúp cả hai hiểu đúng mà không làm khách ngại.'),
            _p('Một bác lớn tuổi trong đoàn chóng mặt dưới nắng.',
               [('a', 'Động viên bác đi tiếp cho kịp lịch'), ('b', 'Đưa bác thuốc của mình'),
                ('c', 'Đưa vào chỗ mát, cho nghỉ, uống nước; không đỡ thì gọi 115')], 'c', 'Sức khỏe trước lịch trình; không tự cho thuốc.'),
            _p('Hộp thuốc hết hạn từ hôm qua, khách nói “không sao đâu”.',
               [('a', 'Không giao; đổi hộp còn hạn'), ('b', 'Giao vì khách đồng ý'), ('c', 'Giao và ghi vào sổ')], 'a',
               'Hạn dùng không phụ thuộc vào việc khách đồng ý.'),
        ],
        bank=[
            _q('cs_history', 'Khách gọi lần thứ ba về cùng một đơn. Câu đầu tiên của bạn?',
               [('a', 'Xin khách kể lại từ đầu cho chắc'), ('b', 'Đọc lịch sử trước, tóm tắt điều đã biết để khách khỏi kể lại'),
                ('c', 'Chuyển ngay sang bộ phận khác')], 'b', 'Khách gọi lần thứ ba cần nghe là mình đã nắm chuyện.'),
            _q('cs_identity', 'Một người gọi hỏi tình trạng đơn “của chị tôi”. Bạn làm gì trước?',
               [('a', 'Xác minh mã yêu cầu của chủ đơn rồi mới nói chi tiết'), ('b', 'Đọc hết thông tin đơn cho nhanh'),
                ('c', 'Cúp máy vì không phải chủ đơn')], 'a', 'Chỉ nói chi tiết đơn khi đã xác minh đúng người.'),
            _q('cs_sources', 'Khách nói đơn báo “đã giao” nhưng chưa nhận được. Trước khi đề nghị phương án?',
               [('a', 'Hoàn tiền ngay cho khách vui'), ('b', 'Bảo khách tự hỏi bên vận chuyển'),
                ('c', 'Đọc đủ nguồn: lịch sử đơn, xác nhận của kho, đối soát vận chuyển')], 'c', 'Phương án đúng cần dữ kiện từ đủ các bên.'),
            _q('cs_promise', 'Bạn chưa chắc kho xử lý kịp trong hôm nay. Bạn hẹn khách thế nào?',
               [('a', 'Hẹn một mốc mình giữ được và gọi lại đúng hẹn'), ('b', '“Trong hôm nay chắc chắn xong ạ.”'),
                ('c', 'Không hẹn gì, xong thì báo')], 'a', 'Hứa điều ngoài tầm tay là nợ khách thêm một lần giận.'),
            _q('cs_update', 'Một vụ đang chờ kho trả lời từ hôm qua. Hôm nay bạn nên?',
               [('a', 'Chờ có kết quả rồi mới gọi'), ('b', 'Gọi khách cập nhật trước buổi trưa, kể cả khi chưa có tin mới'),
                ('c', 'Nhắn “đang xử lý” rồi thôi')], 'b', 'Khách đang chờ cần biết vụ của mình vẫn có người theo.'),
            _q('cs_calm', 'Khách quát: “Năm ngày rồi hàng chưa tới!” Câu mở đầu nào tốt nhất?',
               [('a', '“Anh bình tĩnh lại đã.”'), ('b', 'Giải thích dài về quy trình kho'),
                ('c', 'Xin lỗi vì khách phải chờ, xác nhận mã đơn, nói mình kiểm ngay')], 'c',
               'Bảo người đang giận “bình tĩnh” thường làm họ giận hơn.'),
            _q('cs_demand', 'Khách đòi bồi thường gấp đôi tiền hàng.',
               [('a', 'Nói rõ điều nơi mình làm được, không hứa ngoài quyền, hẹn mốc cập nhật'), ('b', 'Đồng ý cho xong chuyện'),
                ('c', '“Không có chuyện đó.” rồi thôi')], 'a', 'Hứa ngoài quyền thì nơi làm phải gánh, lần sau khách lại đòi.'),
            _q('cs_abuse', 'Khách bắt đầu xúc phạm bạn qua điện thoại.',
               [('a', 'Cãi lại cho khách biết'), ('b', 'Giữ giọng bình tĩnh, nhắc nhẹ ranh giới, đề nghị nói tiếp khi khách sẵn sàng'),
                ('c', 'Im lặng chịu đựng tới hết cuộc gọi')], 'b', 'Không đáp trả xúc phạm, nhưng cũng không phải chịu đựng mãi.'),
            _q('cs_manager', 'Khách đòi gặp quản lý ngay.',
               [('a', '“Quản lý bận, không gặp được đâu.”'), ('b', 'Chuyển máy luôn, không ghi chú'),
                ('c', 'Nói rõ việc mình làm được ngay; khách vẫn muốn thì chuyển kèm bản tóm tắt')], 'c',
               'Quản lý có tóm tắt thì khách khỏi kể lại từ đầu.'),
            _q('cs_dose', 'Ở quầy thuốc, khách hỏi “uống mấy viên cho mau khỏi?”, phiếu không ghi liều.',
               [('a', 'Không tự đưa liều; mời người phụ trách hoặc hỏi lại nơi kê phiếu'), ('b', 'Nói theo kinh nghiệm nhà mình'),
                ('c', 'Khuyên uống gấp đôi cho mau khỏi')], 'a', 'Liều dùng là việc của người có chuyên môn.'),
            _q('cs_address', 'Một người gọi tới hỏi địa chỉ giao hàng của một khách quen để “gửi quà bất ngờ”.',
               [('a', 'Đọc địa chỉ vì người đó biết tên khách'), ('b', 'Không cung cấp; địa chỉ của khách là thông tin riêng'),
                ('c', 'Cho số điện thoại khách để họ tự hỏi')], 'b', 'Địa chỉ, số điện thoại của khách là thông tin riêng tư.'),
            _q('cs_unknown', 'Khách hỏi một chuyện bạn không biết chắc.',
               [('a', 'Nói thật là chưa rõ, hỏi người biết hoặc hẹn tìm hiểu rồi báo lại'), ('b', 'Bịa một câu cho xong'),
                ('c', 'Lảng sang chuyện khác')], 'a', 'Người đáng tin là người không bịa.'),
            _q('cs_count', 'Khi dẫn đoàn, lúc nào phải đếm đủ người?',
               [('a', 'Chỉ lúc xuất phát'), ('b', 'Khi có ai hỏi'), ('c', 'Trước khi khởi hành và sau mỗi điểm dừng')], 'c',
               'Lạc đoàn thường xảy ra lúc rời một điểm dừng.'),
            _q('cs_rain', 'Đang dẫn đoàn thì mưa to.',
               [('a', 'Đưa đoàn tới chỗ có mái che gần nhất, đổi lộ trình, báo điều phối'), ('b', 'Đứng dưới gốc cây chờ tạnh'),
                ('c', 'Đi tiếp theo lịch, ướt chút không sao')], 'a', 'Đứng dưới cây khi mưa giông không an toàn.'),
            _q('cs_handover', 'Hết ca, một vụ của bạn vẫn chưa xong.',
               [('a', 'Để mai tính, không ghi gì'), ('b', 'Đóng vụ cho gọn danh sách'),
                ('c', 'Ghi bàn giao: đã làm gì, đang chờ ai, đã hẹn khách mốc nào')], 'c',
               'Ca sau đọc bàn giao là tiếp được, khách không phải kể lại.'),
        ]),
    dict(
        id='teaching', emoji='🍎', name='Chứng chỉ Nghiệp vụ sư phạm', short='Nghiệp vụ sư phạm',
        issuer='Trường Tiểu học Mầm Nắng (lớp giả lập)', careers=('teacher',), fee=25,
        intro='Dạy một lớp có nhiều nhịp học, nhận xét cho đúng, làm việc với phụ huynh và giữ lớp an toàn.',
        notes=[
            'Cùng một mục tiêu, nhiều cách: hình ảnh, làm thử, kể chuyện; chia nhóm để bạn nhanh giúp bạn chậm.',
            'Tiết học vừa thời gian: khởi động ngắn, phần chính, luyện tập, rồi phiếu ra lớp để biết ai đã hiểu.',
            'Nhận xét cụ thể vào việc làm được và bước tiếp theo; không so sánh bạn này với bạn kia trước lớp.',
            'Phụ huynh nhắn khuya: trả lời ngắn, hẹn trao đổi trong giờ hành chính, chuẩn bị sổ lớp. Không bỏ mặc, không tranh cãi.',
            'Sự kiện lớp: hỏi mong muốn của lớp, kiểm tra dị ứng thức ăn, công khai quỹ lớp; không ép phụ huynh đóng thêm.',
            'Trẻ buồn kéo dài hay bị trêu chọc: quan sát, nói chuyện riêng, báo phụ huynh và nhà trường khi cần.',
            'Ra khỏi lớp: điểm danh trước khi đi và sau khi về. Làm sai thì nhận, sửa và nói rõ.',
        ],
        practice=[
            _p('Mục tiêu tiết học nên viết thế nào?',
               [('a', '“Con hiểu bài.”'), ('b', 'Cụ thể, đo được: “Con đọc đúng giờ trên đồng hồ.”'), ('c', 'Không cần mục tiêu')], 'b',
               'Mục tiêu đo được thì cuối tiết mới biết lớp đạt chưa.'),
            _p('Học sinh hỏi một câu bạn chưa biết.',
               [('a', 'Nói thật, cùng tìm hiểu và trả lời vào buổi sau'), ('b', 'Bịa một câu cho xong'), ('c', 'Bảo con đừng hỏi linh tinh')], 'a',
               'Thầy cô không bịa; cùng tìm hiểu cũng là một bài học.'),
            _p('Một bạn làm xong bài sớm.',
               [('a', 'Cho ngồi chơi'), ('b', 'Bắt làm lại bài cũ'), ('c', 'Có sẵn nhiệm vụ mở rộng hoặc nhờ bạn giúp bạn khác')], 'c',
               'Bạn nhanh cũng cần được học tiếp.'),
            _p('Phụ huynh muốn xem điểm của cả lớp.',
               [('a', 'Chỉ trao đổi kết quả của con mình; điểm bạn khác là riêng tư'), ('b', 'Gửi bảng điểm cả lớp'),
                ('c', 'Đọc điểm to trong buổi họp')], 'a', 'Kết quả học tập của mỗi em là thông tin riêng.'),
        ],
        bank=[
            _q('te_diff', 'Lớp có bạn học nhanh, có bạn học chậm. Bạn tổ chức tiết học thế nào?',
               [('a', 'Dạy theo nhóm giỏi cho kịp chương trình'), ('b', 'Cùng mục tiêu, nhiều cách làm; nhóm hỗ trợ lẫn nhau'),
                ('c', 'Dạy thật chậm cho mọi người')], 'b', 'Dạy học phân hóa: không ai bị bỏ lại, không ai phải chán.'),
            _q('te_exit', 'Cuối tiết, cách nhanh nhất để biết ai đã hiểu bài?',
               [('a', 'Phiếu ra lớp: mỗi bạn trả lời một câu ngắn'), ('b', 'Hỏi cả lớp “hiểu chưa?”'), ('c', 'Chờ tới bài kiểm tra cuối kỳ')], 'a',
               'Cả lớp đồng thanh “hiểu rồi” không cho biết ai còn vướng.'),
            _q('te_feedback', 'Bạn Vy làm sai bài toán nhưng đã cố gắng nhiều.',
               [('a', 'Đọc to lỗi sai trước lớp để cả lớp rút kinh nghiệm'), ('b', 'Chỉ ghi “Sai” rồi trả bài'),
                ('c', 'Khen cụ thể phần làm đúng, chỉ bước tiếp theo để sửa')], 'c', 'Nhận xét cụ thể giúp con biết sửa gì tiếp theo.'),
            _q('te_compare', 'Để động viên cả lớp, bạn nói gì?',
               [('a', 'Nêu điều cả lớp đã tiến bộ và mục tiêu tiếp theo'), ('b', '“Sao các con không được như bạn An?”'),
                ('c', 'Dán bảng xếp hạng điểm lên bảng')], 'a', 'So sánh trước lớp làm các con ngại, không làm các con giỏi hơn.'),
            _q('te_parent', 'Phụ huynh nhắn tin gay gắt lúc 22 giờ.',
               [('a', 'Trả lời ngay, giải thích tới khuya'), ('b', 'Nhắn ngắn hẹn trao đổi trong giờ hành chính, chuẩn bị sổ lớp'),
                ('c', 'Không trả lời')], 'b', 'Ranh giới rõ nhưng không bỏ mặc.'),
            _q('te_event', 'Lớp tổ chức Trung thu. Việc đầu tiên?',
               [('a', 'Đặt bánh và đèn cho nhanh'), ('b', 'Thu thêm tiền phụ huynh cho hoành tráng'),
                ('c', 'Hỏi mong muốn của lớp, kiểm tra dị ứng và quỹ lớp')], 'c', 'Chuẩn bị từ người tham gia, không tạo áp lực cho gia đình.'),
            _q('te_allergy', 'Một bạn dị ứng đậu phộng. Buổi liên hoan có bánh đậu phộng.',
               [('a', 'Chuẩn bị món khác cho bạn, ghi vào sổ lớp, dặn người phụ trách bữa ăn'), ('b', 'Dặn bạn tự tránh món đó'),
                ('c', 'Cho ăn ít thôi chắc không sao')], 'a', 'Dị ứng thức ăn có thể nguy hiểm; người lớn phải chủ động.'),
            _q('te_bully', 'Bạn Bảo mấy hôm nay ngồi một mình, có bạn trêu chọc.',
               [('a', 'Để các con tự giải quyết'), ('b', 'Phạt cả lớp đứng dậy'),
                ('c', 'Quan sát, nói chuyện riêng với các bạn, báo phụ huynh và nhà trường khi cần')], 'c',
               'Chuyện trêu chọc cần người lớn để ý sớm và xử lý riêng.'),
            _q('te_roll', 'Dẫn lớp ra sân tập thể dục. Bạn làm gì trước và sau?',
               [('a', 'Điểm danh trước khi ra và sau khi về lớp'), ('b', 'Chỉ điểm danh buổi sáng'), ('c', 'Nhờ lớp trưởng nhớ giùm')], 'a',
               'Ra khỏi lớp là lúc dễ thiếu một bạn mà không ai hay.'),
            _q('te_plan', 'Kế hoạch cho một tiết 35 phút nào hợp lý?',
               [('a', '35 phút giảng liên tục'), ('b', 'Khởi động ngắn, phần chính, luyện tập, phiếu ra lớp'),
                ('c', 'Cho làm bài tập suốt tiết')], 'b', 'Có nhịp và có kiểm tra cuối tiết.'),
            _q('te_fund', 'Quỹ lớp còn dư sau buổi liên hoan.',
               [('a', 'Giữ lại dùng cho lớp, khỏi báo'), ('b', 'Công khai thu chi với phụ huynh, bàn cách dùng tiếp'),
                ('c', 'Chia lại tiền mặt cho vài bạn')], 'b', 'Tiền của phụ huynh thì phải minh bạch.'),
            _q('te_noise', 'Lớp ồn khi làm việc nhóm.',
               [('a', 'Dùng tín hiệu im lặng đã thống nhất, nhắc lại mục tiêu và thời gian'), ('b', 'Quát lớn cho cả lớp im'),
                ('c', 'Hủy hoạt động nhóm')], 'a', 'Tín hiệu quen thuộc giữ lớp mà không phá không khí.'),
            _q('te_sub', 'Bạn được nhờ dạy thay một lớp lạ.',
               [('a', 'Dạy theo giáo án của mình, không cần biết lớp'), ('b', 'Cho lớp tự học cả buổi'),
                ('c', 'Đọc sổ lớp, hỏi giáo viên chủ nhiệm về các bạn cần lưu ý')], 'c', 'Biết lớp trước thì tiết dạy thay mới trọn.'),
            _q('te_mistake', 'Bạn lỡ chấm sai điểm một bài.',
               [('a', 'Nhận lỗi, sửa điểm, nói rõ với học sinh và phụ huynh'), ('b', 'Giữ nguyên cho đỡ rắc rối'),
                ('c', 'Sửa lặng lẽ, không nói ai')], 'a', 'Nhận và sửa lỗi cũng là dạy các con.'),
        ]),
    dict(
        id='accounting', emoji='🧮', name='Chứng chỉ Kế toán cơ bản', short='Kế toán cơ bản',
        issuer='Hội Kế toán khu phố (lớp giả lập)', careers=('corp_accounting', 'tax_payroll', 'group_accounting'), fee=30,
        intro='Chứng từ, khấu hao, khóa sổ, lương và bảo hiểm, thuế GTGT, hợp nhất. Mọi số tính bằng xu, theo luật chơi đơn giản của game.',
        notes=[
            'Hóa đơn mua vào: đối chiếu ba chiều — hóa đơn, phiếu nhập kho, sổ nhà cung cấp — khớp mới chấp nhận.',
            'Khấu hao đường thẳng: mức tháng = nguyên giá ÷ (số năm × 12). Tài sản đưa vào dùng trong tháng thì trích từ tháng sau; khấu hao hết thì thôi trích.',
            'Khóa sổ theo thứ tự: ghi đủ (trích trước, khấu hao) → thuế → kết chuyển doanh thu, chi phí → lãi/lỗ.',
            'Bảo hiểm phần người lao động tính trên lương đóng bảo hiểm trong hợp đồng: BHXH 8%, BHYT 1,5%, BHTN 1%.',
            'Tăng ca: ngày thường 150%, Chủ nhật 200%, ngày lễ 300%. Thực lĩnh = tổng thu nhập − bảo hiểm − thuế.',
            'Thuế GTGT phải nộp = đầu ra − đầu vào hợp lệ. Hóa đơn từ 200 xu trở lên trả tiền mặt thì không được khấu trừ.',
            'Phiếu lương gửi riêng từng người. Sổ lệch sao kê: đối chiếu từng dòng, có chứng từ mới điều chỉnh.',
            'Hợp nhất: loại trừ doanh thu và công nợ nội bộ giữa các công ty trong tập đoàn; sở hữu 70% thì cổ đông không kiểm soát là 30%.',
        ],
        practice=[
            _p('Chứng từ nào cho biết hàng đã thực sự vào kho?',
               [('a', 'Báo giá'), ('b', 'Phiếu nhập kho'), ('c', 'Email chào hàng')], 'b', 'Phiếu nhập kho ghi số thực nhận.'),
            _p('Thực lĩnh bằng gì?',
               [('a', 'Tổng thu nhập − bảo hiểm − thuế'), ('b', 'Lương cơ bản + tăng ca'), ('c', 'Tổng thu nhập − thuế')], 'a',
               'Bảo hiểm và thuế đều trừ vào tổng thu nhập.'),
            _p('Hạn nộp thuế rơi vào ngày nghỉ lễ.',
               [('a', 'Nộp trước kỳ nghỉ, trễ thì phạt'), ('b', 'Bỏ qua kỳ đó'), ('c', 'Lùi sang ngày làm việc đầu tiên sau kỳ nghỉ')], 'c',
               'Luật chơi của game theo đúng quy định lùi hạn.'),
            _p('Kiểm quỹ tiền mặt thấy thiếu 20 xu.',
               [('a', 'Ghi biên bản, tìm nguyên nhân, báo kế toán trưởng'), ('b', 'Bù tiền túi cho khớp, không nói'), ('c', 'Sửa sổ cho khớp')], 'a',
               'Chênh lệch phải có biên bản và nguyên nhân.'),
        ],
        bank=[
            _q('ac_3way', 'Hóa đơn mua vào ghi 100 cái, phiếu nhập kho ghi 90 cái.',
               [('a', 'Ghi sổ 100 cho khớp hóa đơn'), ('b', 'Chưa chấp nhận: gửi lại nhà cung cấp điều chỉnh theo số thực nhận'),
                ('c', 'Ghi 95 cho công bằng')], 'b', 'Đối chiếu ba chiều: chỉ trả tiền cho hàng đã thực nhận.'),
            _q('ac_dep', 'Máy nguyên giá 1.200 xu, dùng 5 năm, khấu hao đường thẳng. Mức khấu hao tháng?',
               [('a', '20 xu'), ('b', '240 xu'), ('c', '100 xu')], 'a', '1.200 ÷ (5 × 12) = 20 xu mỗi tháng.'),
            _q('ac_dep_start', 'Tài sản đưa vào dùng ngày 15 tháng 3. Bắt đầu trích khấu hao từ khi nào?',
               [('a', 'Ngày 15 tháng 3'), ('b', 'Đầu năm sau'), ('c', 'Tháng 4')], 'c', 'Đưa vào dùng trong tháng thì trích từ tháng sau.'),
            _q('ac_dep_full', 'Tài sản đã khấu hao hết (hao mòn lũy kế bằng nguyên giá) nhưng vẫn còn dùng.',
               [('a', 'Thôi trích khấu hao'), ('b', 'Trích tiếp như cũ'), ('c', 'Trích gấp đôi cho chắc')], 'a',
               'Giá trị còn lại đã bằng 0 thì không trích nữa.'),
            _q('ac_close', 'Thứ tự khóa sổ cuối tháng nào đúng?',
               [('a', 'Kết chuyển trước, bổ sung chi phí sau'), ('b', 'Trích trước, khấu hao → thuế → kết chuyển → lãi/lỗ'),
                ('c', 'Tính lãi/lỗ trước cho biết kết quả')], 'b', 'Ghi nhận đủ chi phí rồi mới kết chuyển, nếu không lãi/lỗ sẽ sai.'),
            _q('ac_ins', 'Lương đóng bảo hiểm 5.000 xu. Phần BHXH người lao động đóng?',
               [('a', '500 xu'), ('b', '75 xu'), ('c', '400 xu')], 'c', 'BHXH phần người lao động 8%: 5.000 × 8% = 400 xu.'),
            _q('ac_ins_base', 'Bảo hiểm của người lao động tính trên khoản nào?',
               [('a', 'Lương đóng bảo hiểm ghi trong hợp đồng'), ('b', 'Tổng thu nhập tháng, kể cả tăng ca'), ('c', 'Lương thực lĩnh')], 'a',
               'Không tính trên tổng thu nhập.'),
            _q('ac_ot', 'Lương giờ 30 xu, tăng ca 2 giờ vào Chủ nhật. Tiền tăng ca?',
               [('a', '90 xu'), ('b', '120 xu'), ('c', '180 xu')], 'b', 'Chủ nhật 200%: 30 × 2 × 200% = 120 xu.'),
            _q('ac_holiday', 'Tăng ca vào ngày lễ tính hệ số bao nhiêu?',
               [('a', '150%'), ('b', '200%'), ('c', '300%')], 'c', 'Ngày thường 150%, Chủ nhật 200%, ngày lễ 300%.'),
            _q('ac_vat', 'Thuế GTGT đầu ra 900 xu, đầu vào hợp lệ 600 xu. Phải nộp bao nhiêu?',
               [('a', '300 xu'), ('b', '1.500 xu'), ('c', '900 xu')], 'a', 'Phải nộp = đầu ra − đầu vào hợp lệ = 300 xu.'),
            _q('ac_cash', 'Hóa đơn mua vào 250 xu trả bằng tiền mặt. Thuế GTGT đầu vào của hóa đơn này?',
               [('a', 'Khấu trừ bình thường'), ('b', 'Không được khấu trừ vì từ 200 xu trở lên mà trả tiền mặt'), ('c', 'Khấu trừ một nửa')], 'b',
               'Luật chơi: hóa đơn từ 200 xu trả tiền mặt không được khấu trừ.'),
            _q('ac_payslip', 'Gửi phiếu lương cho nhân viên thế nào?',
               [('a', 'Dán bảng lương chung lên nhóm chat'), ('b', 'Đọc to trong buổi họp'), ('c', 'Gửi riêng từng người')], 'c',
               'Lương của mỗi người là thông tin riêng.'),
            _q('ac_bank', 'Số dư sổ tiền gửi khác sao kê ngân hàng 50 xu.',
               [('a', 'Đối chiếu từng dòng tìm khoản chênh, có chứng từ mới điều chỉnh'), ('b', 'Sửa sổ cho khớp sao kê luôn'),
                ('c', 'Bỏ qua vì số nhỏ')], 'a', 'Mỗi dòng điều chỉnh phải có chứng từ.'),
            _q('ac_trial', 'Bảng cân đối thử không cân: tổng Nợ lệch tổng Có 90 xu.',
               [('a', 'Thêm một dòng 90 xu cho cân'), ('b', 'Gửi luôn, tháng sau tính'),
                ('c', 'Soát lại từng bút toán, để ý số bị đảo chữ số (khoản lệch chia hết cho 9)')], 'c',
               'Đảo chữ số (54 thành 45) luôn tạo khoản lệch chia hết cho 9.'),
            _q('ac_nci', 'Công ty mẹ sở hữu 70% một công ty con. Khi hợp nhất, phần của cổ đông không kiểm soát là?',
               [('a', '70%'), ('b', '30%'), ('c', '0% vì công ty mẹ kiểm soát')], 'b', '100% − 70% = 30%.'),
            _q('ac_interco', 'Công ty con này bán hàng cho công ty con khác trong cùng tập đoàn.',
               [('a', 'Loại trừ doanh thu và công nợ nội bộ khi lập báo cáo hợp nhất'), ('b', 'Cộng dồn như doanh thu bình thường'),
                ('c', 'Chỉ ghi ở công ty mua')], 'a', 'Trong tập đoàn, bán cho nhau không tạo ra doanh thu với bên ngoài.'),
        ]),
]
