"""Canonical PostgreSQL schema for game saves, accounts, live chat and shared limits.

Text columns use COLLATE "C" for stable byte ordering. Timestamps are UTC text in
'YYYY-MM-DD HH:MM:SS' format; `sessions.state` preserves the serialized JSON bytes.
Generated bigint identities allow explicit ids on restore. reset_sequences() can
advance them past restored rows and supplied sequence floors.

DDL stages create tables, indexes, statistics triggers and storage tuning.
ensure(conn) runs them idempotently at startup and records SCHEMA_VERSION in
`mnl_meta` so subsequent starts skip DDL and its locks. TABLES contains only the
runtime catalog needed to check table presence and maintain identity sequences.
"""
from __future__ import annotations

SCHEMA_VERSION = 33  # 33: 🚔 Trại tạm giữ marks (jail_marks: game/jail.py); 32: 💌 Thiệp mời cưới cả phố (wed_invites, wed_invite_seen: game/wed_invite.py); 31: 🎨 Cho trang trí (home_deco_grants, home_deco_log: game/home_coop.py); 30: 🎙️ Phòng hát mic trực tiếp (account_birth: game/karaoke_mic.py); 29: 🔨 Nhà đấu giá (auction_lots, auction_bids: game/auction.py); 28: 🎆 Mạnh Thường Quân (lux_gifts: game/lux.py); 27: 🐾 Bé cưng của tuần (pet_board: game/pets.py; ensure() also creates any table missing); 26: 🎤 Phòng hát (kara_songs, kara_tickets, kara_reviews: game/karaoke.py, live/karaoke.py), on top of 25 (spend-1: donations, chat_style); 24: 🐢 chat slow mode (chat_slow: game/live_chat.py, live/chat.py); 22: synchronize character/account names; 21: chat replies; 20: friend home invitations.
                     # 2: leaderboard, marriage/friends/couple tables, stat_fb_created, stat_accounts_created; 3: stat_play;
                     # 4: system_gifts; 5: Giữ chân (game/retention.py: stat_milestones, stat_actions(_daily), stat_rollups,
                     # stat_leaves, stat_leave_last, stat_client_errors, stat_loads, stat_acquisition) and stat_play_daily;
                     # 6: live chat (chat_*, live_effects: game/live_chat.py, live/), 1.0.0;
                     # 7: dates (live_dates, date_bonds: game/live_dating.py, live/dating.py), 1.0.1
                     # 8: live weddings (wedding_dates, wedding_parties, wedding_guests, wedding_photos, wedding_race,
                     #    player_closeness: game/wedding_live.py, live/wedding.py), 1.1.0
                     # 9: weekly leaderboard titles (lb_weekly: game/lb_titles.py)
                     # 10: 📌 admin messages and the pinned message of Cả phố (chat_messages.adm, chat_pins:
                     #     game/live_chat.py, live/chat.py, scripts/chat_pin.py)
                     # 11: 😍 reactions (chat_reacts) and the admin-only original text (chat_messages.raw), 1.2.2
                     # 12: 🙂 chat faces (chat_faces: live/faces.py, live/chat.py)
                     # 13: 🗑️ "xóa ở phía tôi" (chat_hides: one message, chat_clears: a whole chat up to an id; live/chat.py)

# UTC timestamp text, independent of the connection's TimeZone.
NOW_TEXT = "to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"       # CURRENT_TIMESTAMP
UNIXEPOCH = "floor(extract(epoch FROM statement_timestamp()))"                                # unixepoch()
VN_DAY = "to_char((statement_timestamp() AT TIME ZONE 'UTC') + interval '7 hours', 'YYYY-MM-DD')"  # date('now','+7 hours')

# Play time (stat_play, the same rule as game/admin_stats.py SCHEMA): a command within PLAY_GAP seconds
# of the save's previous one that day continues the session (the gap counts as played); a longer gap
# starts a new session. Each session also counts PLAY_IDLE_TAIL seconds after its last command.
PLAY_GAP = 600
PLAY_IDLE_TAIL = 60

T = 'text COLLATE "C"'
ID = 'bigint GENERATED BY DEFAULT AS IDENTITY'

TABLES_DDL = f"""
CREATE TABLE IF NOT EXISTS mnl_meta (key {T} PRIMARY KEY, value {T} NOT NULL);

CREATE TABLE IF NOT EXISTS sessions (
  sid {T} PRIMARY KEY, csrf {T} NOT NULL, revision bigint NOT NULL DEFAULT 0,
  state {T} NOT NULL, updated_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS receipts (
  sid {T} NOT NULL, request_id {T} NOT NULL, request_hash {T} NOT NULL,
  result {T} NOT NULL, created_at {T} NOT NULL DEFAULT {NOW_TEXT},
  PRIMARY KEY (sid, request_id)
);
CREATE TABLE IF NOT EXISTS accounts (
  uid {ID} PRIMARY KEY, username {T} UNIQUE NOT NULL, display {T} NOT NULL,
  pw {T} NOT NULL, sid {T} UNIQUE NOT NULL,
  created_at {T} NOT NULL DEFAULT {NOW_TEXT}, updated_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS logins (
  token {T} PRIMARY KEY, sid {T} NOT NULL, csrf {T} NOT NULL,
  created_at {T} NOT NULL DEFAULT {NOW_TEXT}, seen_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS tiktok_identities (
  client_key {T} NOT NULL, open_id {T} NOT NULL, uid bigint NOT NULL, sid {T} NOT NULL,
  display {T} NOT NULL, created_at {T} NOT NULL DEFAULT {NOW_TEXT},
  PRIMARY KEY(client_key,open_id), UNIQUE(client_key,uid)
);
CREATE TABLE IF NOT EXISTS tiktok_flows (
  state_hash {T} PRIMARY KEY, binding_hash {T} UNIQUE NOT NULL,
  source_token {T} NOT NULL, source_sid {T} NOT NULL, source_login bigint NOT NULL,
  mode {T} NOT NULL, client_key {T} NOT NULL, expires_at double precision NOT NULL,
  phase {T} NOT NULL, target_uid bigint, nonce_hash {T}
);
CREATE TABLE IF NOT EXISTS player_feedback (
  id {ID} PRIMARY KEY, sid {T} NOT NULL, account {T},
  kind {T} NOT NULL, text {T} NOT NULL, context {T} NOT NULL DEFAULT '{{}}',
  status {T} NOT NULL DEFAULT 'new', reply {T},
  created_at double precision NOT NULL, updated_at double precision NOT NULL, replied_at double precision
);
CREATE TABLE IF NOT EXISTS archive (
  sid {T} NOT NULL, career {T} NOT NULL, kind {T} NOT NULL, seq bigint NOT NULL,
  day bigint, row {T} NOT NULL, created_at double precision NOT NULL DEFAULT {UNIXEPOCH},
  CONSTRAINT archive_rows UNIQUE (sid, career, kind, seq)
);

CREATE TABLE IF NOT EXISTS profiles (
  pid {T} PRIMARY KEY, sid {T} UNIQUE NOT NULL, name {T}, name_key {T} UNIQUE, bio {T} NOT NULL DEFAULT '',
  avatar {T} NOT NULL DEFAULT '🌸', visible bigint NOT NULL DEFAULT 0, shop {T} NOT NULL DEFAULT '{{}}',
  served bigint NOT NULL DEFAULT 0, week_key {T} NOT NULL DEFAULT '', week_base bigint NOT NULL DEFAULT 0,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0,
  created double precision NOT NULL, updated double precision NOT NULL, seen double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS work_visit_places (
  id {T} PRIMARY KEY, owner {T} NOT NULL, kind {T} NOT NULL, target {T} NOT NULL,
  visibility {T} NOT NULL DEFAULT 'friends', data {T} NOT NULL, updated_at double precision NOT NULL,
  UNIQUE(owner,kind,target)
);
CREATE TABLE IF NOT EXISTS work_service_orders (
  id {T} PRIMARY KEY, place {T} NOT NULL, customer {T} NOT NULL, provider {T} NOT NULL,
  status {T} NOT NULL, price bigint NOT NULL CHECK(price >= 0), request_id {T} NOT NULL,
  fingerprint {T} NOT NULL, data {T} NOT NULL, created_at double precision NOT NULL,
  updated_at double precision NOT NULL, UNIQUE(customer,request_id)
);
CREATE TABLE IF NOT EXISTS work_service_reviews (
  order_id {T} PRIMARY KEY, place {T} NOT NULL, customer {T} NOT NULL, provider {T} NOT NULL,
  stars bigint NOT NULL CHECK(stars BETWEEN 1 AND 5), tags {T} NOT NULL, comment {T} NOT NULL,
  reply {T} NOT NULL DEFAULT '', created_at double precision NOT NULL, updated_at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS visits (
  from_pid {T}, to_pid {T}, day {T}, at double precision, PRIMARY KEY (from_pid, to_pid, day)
);
CREATE TABLE IF NOT EXISTS previews (
  id {ID} PRIMARY KEY, from_pid {T} NOT NULL, to_pid {T} NOT NULL, career {T} NOT NULL, day {T} NOT NULL,
  stars bigint NOT NULL, text {T} NOT NULL, reply {T}, reply_at double precision, at double precision NOT NULL,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0, UNIQUE (from_pid, to_pid, day)
);
CREATE TABLE IF NOT EXISTS gifts (
  id {ID} PRIMARY KEY, from_pid {T} NOT NULL, to_pid {T} NOT NULL, sticker {T} NOT NULL, coins bigint NOT NULL,
  note {T} NOT NULL DEFAULT '', day {T} NOT NULL, at double precision NOT NULL, claimed bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS market (
  id {ID} PRIMARY KEY, seller {T} NOT NULL, career {T} NOT NULL, item {T} NOT NULL, qty bigint NOT NULL,
  price bigint NOT NULL, life_left bigint NOT NULL, unit_cost bigint NOT NULL, listed_day bigint NOT NULL,
  status {T} NOT NULL, buyer {T}, at double precision NOT NULL, sold_at double precision, settled bigint NOT NULL DEFAULT 0,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS board (
  id {ID} PRIMARY KEY, pid {T} NOT NULL, career {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL,
  at double precision NOT NULL, reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS comments (
  id {ID} PRIMARY KEY, post bigint NOT NULL, pid {T} NOT NULL, text {T} NOT NULL, at double precision NOT NULL,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS reactions (post bigint NOT NULL, pid {T} NOT NULL, emoji {T} NOT NULL, PRIMARY KEY (post, pid, emoji));
CREATE TABLE IF NOT EXISTS follows (pid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (pid, target));
CREATE TABLE IF NOT EXISTS blocks (pid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (pid, target));
CREATE TABLE IF NOT EXISTS reports (
  reporter {T} NOT NULL, kind {T} NOT NULL, target {T} NOT NULL, reason {T} NOT NULL, at double precision NOT NULL,
  PRIMARY KEY (reporter, kind, target)
);
CREATE TABLE IF NOT EXISTS inbox (
  id {ID} PRIMARY KEY, pid {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL, ref {T}, at double precision NOT NULL,
  read bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS push_subs (
  endpoint {T} PRIMARY KEY, sid {T} NOT NULL, created double precision NOT NULL, last_ok double precision,
  fails bigint NOT NULL DEFAULT 0, prefs {T} NOT NULL DEFAULT '{{}}'
);
CREATE TABLE IF NOT EXISTS push_queue (
  id {ID} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, body {T} NOT NULL, url {T} NOT NULL,
  at double precision NOT NULL, sent bigint NOT NULL DEFAULT 0, shown bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS push_daily (sid {T} PRIMARY KEY, day {T} NOT NULL);

CREATE TABLE IF NOT EXISTS stat_births (sid {T} PRIMARY KEY, day {T} NOT NULL);
CREATE TABLE IF NOT EXISTS stat_active (day {T} NOT NULL, sid {T} NOT NULL, PRIMARY KEY (day, sid));
CREATE TABLE IF NOT EXISTS stat_fb_ack (id bigint PRIMARY KEY, at double precision NOT NULL);
-- Play time per save per Vietnam day (game/admin_stats.py "Thời gian chơi"), kept by the trigger
-- stat_play_cmd on receipts (one receipt = one game command). Today's rows are updated on every
-- command: room on each page for HOT updates (no index write) and an early vacuum.
CREATE TABLE IF NOT EXISTS stat_play (
  day {T} NOT NULL, sid {T} NOT NULL, secs bigint NOT NULL, sessions bigint NOT NULL, cmds bigint NOT NULL,
  first_at double precision NOT NULL, last_at double precision NOT NULL, hours bigint NOT NULL DEFAULT 0,
  sess_at double precision NOT NULL, lens {T} NOT NULL DEFAULT '',
  PRIMARY KEY (day, sid)
) WITH (fillfactor = 90, autovacuum_vacuum_scale_factor = 0.01, autovacuum_analyze_scale_factor = 0.02);
CREATE TABLE IF NOT EXISTS stat_play_est (day {T} PRIMARY KEY, saves bigint NOT NULL, capped bigint NOT NULL, at double precision NOT NULL);
-- One row per finished day of stat_play, written before its per-player rows are purged (kept forever).
CREATE TABLE IF NOT EXISTS stat_play_daily (day {T} PRIMARY KEY, players bigint NOT NULL, secs bigint NOT NULL, sessions bigint NOT NULL,
  cmds bigint NOT NULL, data {T} NOT NULL, at double precision NOT NULL);

-- Giữ chân (game/retention.py): funnel steps per save (kept), commands per player per day (fillfactor:
-- today's rows are updated by each worker's flush, HOT), leave beacons, client errors, load times,
-- where new players came from. None of them is ever read to serve a player.
CREATE TABLE IF NOT EXISTS stat_milestones (
  sid {T} NOT NULL, key {T} NOT NULL, at double precision, day bigint, career {T}, detail {T}, PRIMARY KEY (sid, key)
);
CREATE TABLE IF NOT EXISTS stat_actions (
  day {T} NOT NULL, sid {T} NOT NULL, career {T} NOT NULL, action {T} NOT NULL, n integer NOT NULL, errors integer NOT NULL DEFAULT 0,
  err {T}, PRIMARY KEY (day, sid, career, action)
) WITH (fillfactor = 90, autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.05);
CREATE TABLE IF NOT EXISTS stat_actions_daily (
  day {T} NOT NULL, career {T} NOT NULL, action {T} NOT NULL, players bigint NOT NULL, n bigint NOT NULL, errors bigint NOT NULL,
  err {T}, PRIMARY KEY (day, career, action)
);
CREATE TABLE IF NOT EXISTS stat_rollups (kind {T} NOT NULL, day {T} NOT NULL, rows bigint NOT NULL, at double precision NOT NULL, PRIMARY KEY (kind, day));
CREATE TABLE IF NOT EXISTS stat_leaves (
  id {ID} PRIMARY KEY, sid {T} NOT NULL, at double precision NOT NULL, day {T} NOT NULL, payload {T} NOT NULL
);
CREATE TABLE IF NOT EXISTS stat_leave_last (sid {T} PRIMARY KEY, at double precision NOT NULL, payload {T} NOT NULL) WITH (fillfactor = 80);
CREATE TABLE IF NOT EXISTS stat_client_errors (
  day {T} NOT NULL, kind {T} NOT NULL, message_key {T} NOT NULL, screen {T} NOT NULL, count bigint NOT NULL,
  last_at double precision NOT NULL, sample {T}, PRIMARY KEY (day, kind, message_key, screen)
);
CREATE TABLE IF NOT EXISTS stat_loads (
  day {T} NOT NULL, metric {T} NOT NULL, net {T} NOT NULL, who {T} NOT NULL, cache {T} NOT NULL, tier {T} NOT NULL,
  bucket integer NOT NULL, n bigint NOT NULL, PRIMARY KEY (day, metric, net, who, cache, tier, bucket)
);
CREATE TABLE IF NOT EXISTS stat_acquisition (
  sid {T} PRIMARY KEY, at double precision NOT NULL, day {T} NOT NULL, source {T}, medium {T}, campaign {T}, ref_domain {T}
);

CREATE TABLE IF NOT EXISTS hits (k {T} NOT NULL, at double precision NOT NULL);

-- Bảng xếp hạng (game/leaderboard.py)
CREATE TABLE IF NOT EXISTS leaderboard (
  sid {T} NOT NULL, board {T} NOT NULL,
  score bigint NOT NULL, k1 bigint NOT NULL, k2 bigint NOT NULL,
  level bigint NOT NULL, days bigint NOT NULL, served bigint NOT NULL,
  stars bigint NOT NULL, mastered bigint NOT NULL,
  since double precision NOT NULL, updated double precision NOT NULL,
  PRIMARY KEY (sid, board)
);
CREATE TABLE IF NOT EXISTS leaderboard_players (
  sid {T} PRIMARY KEY, name {T}, show bigint, updated double precision NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS leaderboard_meta (k {T} PRIMARY KEY, v {T} NOT NULL);
-- 🏅 Danh hiệu tuần (game/lb_titles.py): the holders per (week, board, rank); final=0 now, final=1 past weeks (kept)
CREATE TABLE IF NOT EXISTS lb_weekly (
  week {T} NOT NULL, board {T} NOT NULL, rank bigint NOT NULL, sid {T} NOT NULL, score bigint NOT NULL,
  title {T} NOT NULL, final bigint NOT NULL DEFAULT 0, day {T} NOT NULL, at double precision NOT NULL,
  PRIMARY KEY (week, board, rank)
);

-- Hôn nhân (game/marriage.py), bạn bè (game/friends.py), vợ chồng (game/couple.py)
CREATE TABLE IF NOT EXISTS marriage_people (
  sid {T} PRIMARY KEY, code {T} UNIQUE NOT NULL, accept bigint NOT NULL DEFAULT 1,
  life_day bigint, pool {T}, remarry_after double precision NOT NULL DEFAULT 0,
  notice {T}, notice_at double precision, created double precision NOT NULL, updated double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS marriage_rings (
  id {T} PRIMARY KEY, sid {T} NOT NULL, tier {T} NOT NULL, price bigint NOT NULL,
  status {T} NOT NULL, at double precision NOT NULL, metal {T}, stone {T}
);
CREATE TABLE IF NOT EXISTS proposals (
  id {ID} PRIMARY KEY, from_sid {T} NOT NULL, to_sid {T} NOT NULL, ring {T} NOT NULL,
  message {T} NOT NULL, announce bigint NOT NULL DEFAULT 1, status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS couples (
  id {ID} PRIMARY KEY, a {T} NOT NULL, b {T} NOT NULL, ring {T},
  status {T} NOT NULL, since double precision NOT NULL, married_at double precision, ended double precision, ended_by {T}
);
CREATE TABLE IF NOT EXISTS marriage_bonds (sid {T} PRIMARY KEY, couple bigint NOT NULL);
CREATE TABLE IF NOT EXISTS weddings (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, status {T} NOT NULL,
  version bigint NOT NULL DEFAULT 1, planner {T}, plan {T} NOT NULL, quote {T} NOT NULL,
  split_a bigint NOT NULL DEFAULT 50, announce_a bigint NOT NULL DEFAULT 1, announce_b bigint NOT NULL DEFAULT 1,
  days bigint NOT NULL, target_a bigint, target_b bigint, due_at double precision,
  deposit_a bigint NOT NULL DEFAULT 0, deposit_b bigint NOT NULL DEFAULT 0, result {T},
  seen_a bigint NOT NULL DEFAULT 0, seen_b bigint NOT NULL DEFAULT 0,
  created double precision NOT NULL, confirmed_at double precision, done_at double precision
);
CREATE TABLE IF NOT EXISTS marriage_effects (
  id {T} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, amount bigint NOT NULL DEFAULT 0,
  label {T} NOT NULL DEFAULT '', data {T} NOT NULL DEFAULT '{{}}', status {T} NOT NULL,
  due double precision NOT NULL DEFAULT 0, at double precision NOT NULL, applied_at double precision
);
CREATE TABLE IF NOT EXISTS marriage_blocks (sid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (sid, target));
CREATE TABLE IF NOT EXISTS news (
  id {ID} PRIMARY KEY, kind {T} NOT NULL, ref {T} UNIQUE NOT NULL, text {T} NOT NULL,
  a {T}, b {T}, at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS friend_prefs (sid {T} PRIMARY KEY, findable bigint NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS friend_requests (
  id {ID} PRIMARY KEY, from_sid {T} NOT NULL, to_sid {T} NOT NULL, status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS friends (sid {T} NOT NULL, friend {T} NOT NULL, since double precision NOT NULL, PRIMARY KEY (sid, friend));
CREATE TABLE IF NOT EXISTS home_guest_invites (
  id {T} PRIMARY KEY, owner {T} NOT NULL, guest {T} NOT NULL,
  home_id {T} NOT NULL, home_kind {T} NOT NULL,
  kind {T} NOT NULL CHECK (kind IN ('visit','stay')),
  status {T} NOT NULL CHECK (status IN ('pending','accepted','declined','revoked','left','expired')),
  created_at double precision NOT NULL, expires_at double precision,
  CHECK (owner <> guest)
);
CREATE TABLE IF NOT EXISTS friend_searches (sid {T} NOT NULL, at double precision NOT NULL);
CREATE TABLE IF NOT EXISTS joint_funds (couple bigint PRIMARY KEY, balance bigint NOT NULL DEFAULT 0, updated double precision NOT NULL);
CREATE TABLE IF NOT EXISTS joint_ledger (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, sid {T}, kind {T} NOT NULL, amount bigint NOT NULL,
  balance bigint NOT NULL, label {T} NOT NULL DEFAULT '', ref {T} UNIQUE NOT NULL, status {T} NOT NULL DEFAULT 'done', at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS couple_requests (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, from_sid {T} NOT NULL, to_sid {T} NOT NULL, kind {T} NOT NULL,
  amount bigint NOT NULL DEFAULT 0, note {T} NOT NULL DEFAULT '', loan bigint NOT NULL DEFAULT 0, debt bigint,
  status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS couple_debts (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, lender {T} NOT NULL, borrower {T} NOT NULL,
  amount bigint NOT NULL, repaid bigint NOT NULL DEFAULT 0, status {T} NOT NULL, note {T} NOT NULL DEFAULT '',
  ref {T} UNIQUE NOT NULL, at double precision NOT NULL, updated double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS couple_moments (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, sid {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL,
  key {T} UNIQUE NOT NULL, at double precision NOT NULL, seen bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS couple_stats (
  couple bigint PRIMARY KEY, happy bigint NOT NULL DEFAULT 0, streak bigint NOT NULL DEFAULT 0, best bigint NOT NULL DEFAULT 0,
  last_day bigint NOT NULL DEFAULT 0, today bigint NOT NULL DEFAULT 0
);

-- 👶 Shared family, mutual invitations and surviving parents' private custody copies.
CREATE TABLE IF NOT EXISTS family_children (
  couple bigint PRIMARY KEY, state {T} NOT NULL, revision bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS family_custody (
  child bigint NOT NULL, sid {T} NOT NULL, state {T} NOT NULL, revision bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (child,sid)
);
CREATE TABLE IF NOT EXISTS family_requests (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, from_sid {T} NOT NULL, to_sid {T} NOT NULL,
  kind {T} NOT NULL, data {T} NOT NULL, status {T} NOT NULL DEFAULT 'pending', at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS family_receipts (
  sid {T} NOT NULL, rid {T} NOT NULL, op {T} NOT NULL, fingerprint {T} NOT NULL,
  result {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (sid,rid)
);

-- 🎁 Quà từ Phố Có Chuyện (game/system_gift.py): a gift from the operator to one save, pending -> applied -> seen
CREATE TABLE IF NOT EXISTS system_gifts (
  id {T} PRIMARY KEY, sid {T} NOT NULL, coins bigint NOT NULL, title {T} NOT NULL, text {T} NOT NULL,
  status {T} NOT NULL, created double precision NOT NULL, applied_at double precision, seen_at double precision,
  granted_by {T}
);
-- granted_by: the admin account that gave it from /admin ("🎁 Tặng xu"); NULL for scripts/grant_gift.py and older rows.
-- Added in 16 (nullable, no default: no table rewrite); earlier releases name their columns and never read it.
ALTER TABLE system_gifts ADD COLUMN IF NOT EXISTS granted_by {T};

-- 💬 Chat (the live service, live/; admin side in game/live_chat.py). Messages are kept: a player's own
-- delete empties the text (deleted=1); reports and the admin hide (hidden 1 = auto-hidden after 3 reports,
-- 2 = hidden by an admin) never remove a row.
CREATE TABLE IF NOT EXISTS chat_channels (
  id {T} PRIMARY KEY, kind {T} NOT NULL, title {T} NOT NULL DEFAULT '', owner_pid {T}, created double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_members (
  channel {T} NOT NULL, pid {T} NOT NULL, sid {T} NOT NULL, role {T} NOT NULL DEFAULT 'member', joined double precision NOT NULL,
  last_read bigint NOT NULL DEFAULT 0, muted_until double precision NOT NULL DEFAULT 0, pushed_at double precision NOT NULL DEFAULT 0,
  PRIMARY KEY (channel, pid)
);
CREATE TABLE IF NOT EXISTS chat_messages (
  id {ID} PRIMARY KEY, channel {T} NOT NULL, pid {T} NOT NULL, name {T} NOT NULL DEFAULT '', av {T} NOT NULL DEFAULT '',
  text {T} NOT NULL, at double precision NOT NULL, hidden bigint NOT NULL DEFAULT 0, deleted bigint NOT NULL DEFAULT 0,
  reports bigint NOT NULL DEFAULT 0, reviewed_at double precision, adm bigint NOT NULL DEFAULT 0, raw {T}
);
-- adm = 1: written by an admin (ADMIN_USERS) on Cả phố. Added in 10 (a constant default: no table rewrite).
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS adm bigint NOT NULL DEFAULT 0;
-- raw: what the player typed when the filter masked part of it (NULL when the text is as typed). Admins only,
-- never sent to players. Added in 11 (nullable, no default: no table rewrite); older rows stay NULL.
-- Since 13 a message its author takes back (Thu hồi) after somebody reported it keeps its text here for the admin.
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS raw {T};
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS reply_to bigint;
CREATE TABLE IF NOT EXISTS chat_mutes (
  pid {T} PRIMARY KEY, until double precision NOT NULL, by_admin {T} NOT NULL DEFAULT '', reason {T} NOT NULL DEFAULT '',
  at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_prefs (pid {T} PRIMARY KEY, online bigint NOT NULL DEFAULT 1, updated double precision NOT NULL);
-- 😍 Reactions (live/chat.py): one per player per message, replaced or removed by the player.
CREATE TABLE IF NOT EXISTS chat_reacts (
  msg bigint NOT NULL, pid {T} NOT NULL, emoji {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (msg, pid)
);
-- 📌 The pinned message of a channel (Cả phố only for now): one row, read by the live service by primary key.
CREATE TABLE IF NOT EXISTS chat_pins (
  channel {T} PRIMARY KEY, msg bigint NOT NULL, by_pid {T} NOT NULL, at double precision NOT NULL
);
-- 🙂 The face of a player's chat avatar (live/faces.py code of whitelisted ids), written by the live service only.
CREATE TABLE IF NOT EXISTS chat_faces (pid {T} PRIMARY KEY, code {T} NOT NULL, at double precision NOT NULL);
-- 🗑️ Deleted on one side only (live/chat.py): a message a player removed from their own screen, and a whole chat
-- emptied for one player (every message up to `upto`, the chat's newest id then). Nobody else's view changes; the
-- messages themselves stay (admins still see them). Written by the live service only.
CREATE TABLE IF NOT EXISTS chat_hides (pid {T} NOT NULL, msg bigint NOT NULL, at double precision NOT NULL, PRIMARY KEY (pid, msg));
CREATE TABLE IF NOT EXISTS chat_clears (
  channel {T} NOT NULL, pid {T} NOT NULL, upto bigint NOT NULL, at double precision NOT NULL, PRIMARY KEY (channel, pid)
);
-- 🐢 Slow mode set by an admin (game/live_chat.py, read by live/chat.py; SCHEMA_VERSION 24): one player may post on
-- Cả phố once per `every` seconds until `until`; the row with pid 'town' slows Cả phố for everyone. Never a ban.
CREATE TABLE IF NOT EXISTS chat_slow (
  pid {T} PRIMARY KEY, every double precision NOT NULL, until double precision NOT NULL, by_admin {T} NOT NULL DEFAULT '',
  at double precision NOT NULL
);
-- 🙏 Công đức Chùa Gió Lành (game/spend.py; SCHEMA_VERSION 25): one row per donation, written in the save's own
-- transaction (id '<pid>:<n>', idempotent). The weekly board reads it by week. A player who erases their data stays
-- on the board as anonymous (sid '').
CREATE TABLE IF NOT EXISTS donations (
  id {T} PRIMARY KEY, sid {T} NOT NULL, week {T} NOT NULL, amount bigint NOT NULL CHECK(amount > 0),
  wish {T} NOT NULL DEFAULT '', anon bigint NOT NULL DEFAULT 1, at double precision NOT NULL
);
CREATE INDEX IF NOT EXISTS donations_week ON donations(week, sid);
-- 🎨 Màu tên, khung hồ sơ, danh hiệu tuần worn now (game/spend.py writes it with the save; live/styles.py reads it by
-- pid and shows it as `st` beside the name). An expired item is ignored by its `_until` (unix seconds).
CREATE TABLE IF NOT EXISTS chat_style (
  pid {T} PRIMARY KEY, sid {T} NOT NULL, color {T} NOT NULL DEFAULT '', color_until double precision NOT NULL DEFAULT 0,
  frame {T} NOT NULL DEFAULT '', frame_until double precision NOT NULL DEFAULT 0, title {T} NOT NULL DEFAULT '',
  title_until double precision NOT NULL DEFAULT 0, at double precision NOT NULL
);
CREATE INDEX IF NOT EXISTS chat_style_sid ON chat_style(sid);
-- Rewards the live service grants (phase 3 dates, phase 2 lucky envelopes); the game server applies them on load.
CREATE TABLE IF NOT EXISTS live_effects (
  id {T} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, amount bigint NOT NULL DEFAULT 0, data {T} NOT NULL DEFAULT '{{}}',
  status {T} NOT NULL DEFAULT 'pending', at double precision NOT NULL, applied_at double precision
);
-- 💼 Hired players' shifts at someone's counter (game/quay_hire.py): one row per offer, guarded status changes.
CREATE TABLE IF NOT EXISTS quay_jobs (
  id {T} PRIMARY KEY, owner {T} NOT NULL, owner_name {T} NOT NULL, stall {T} NOT NULL, stall_name {T} NOT NULL,
  trade {T} NOT NULL, place {T} NOT NULL, wage bigint NOT NULL, value bigint NOT NULL, friend {T}, worker {T},
  status {T} NOT NULL, day {T} NOT NULL, taken_day {T}, at double precision NOT NULL, taken_at double precision,
  ended double precision, until double precision NOT NULL,
  tasks bigint NOT NULL DEFAULT 0, stars bigint NOT NULL DEFAULT 0, earned bigint NOT NULL DEFAULT 0
);
-- 💸 Transfers between friends (game/bank_xfer.py): one row per transfer (the audit log), guarded status changes;
CREATE TABLE IF NOT EXISTS quay_funding (
  job {T} PRIMARY KEY, owner {T} NOT NULL, rid {T}, fingerprint {T} NOT NULL,
  source {T} NOT NULL, couple bigint, UNIQUE(owner,rid)
);
-- the day counters move with conditional upserts (the caps hold under concurrency).
CREATE TABLE IF NOT EXISTS bank_xfers (
  id {T} PRIMARY KEY, code {T} NOT NULL, sender {T} NOT NULL, receiver {T} NOT NULL, from_name {T} NOT NULL,
  to_name {T} NOT NULL, amount bigint NOT NULL, note {T} NOT NULL DEFAULT '', src {T} NOT NULL, status {T} NOT NULL,
  day {T} NOT NULL, at double precision NOT NULL, done_at double precision
);
-- Prepaid player leases. Session rows are always locked before rental rows.
CREATE TABLE IF NOT EXISTS rentals (
  id {T} PRIMARY KEY, owner {T} NOT NULL, property {T} NOT NULL, kind {T} NOT NULL,
  owner_name {T} NOT NULL, tenant {T}, tenant_name {T} NOT NULL DEFAULT '',
  rent bigint NOT NULL, status {T} NOT NULL, start_day bigint, end_day bigint,
  at double precision NOT NULL, updated double precision NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS rentals_property_active ON rentals(owner,property) WHERE status IN ('listing','leased');
CREATE UNIQUE INDEX IF NOT EXISTS rentals_tenant_active ON rentals(tenant) WHERE status='leased';
CREATE INDEX IF NOT EXISTS rentals_market ON rentals(status,at);
CREATE INDEX IF NOT EXISTS rentals_owner ON rentals(owner,at);
CREATE INDEX IF NOT EXISTS rentals_tenant ON rentals(tenant,status);
CREATE TABLE IF NOT EXISTS rental_closed_accounts (sid {T} PRIMARY KEY);
CREATE TABLE IF NOT EXISTS rental_receipts (
  sid {T} NOT NULL, rid {T} NOT NULL, fingerprint {T} NOT NULL, result {T} NOT NULL,
  PRIMARY KEY(sid,rid)
);
CREATE TABLE IF NOT EXISTS bank_xfer_days (
  sid {T} NOT NULL, day {T} NOT NULL, sent bigint NOT NULL DEFAULT 0, n bigint NOT NULL DEFAULT 0,
  got bigint NOT NULL DEFAULT 0, PRIMARY KEY (sid, day)
);
-- 💕 Dates of the live service (live/dating.py; game/live_dating.py): one row per café date (pids a < b), and the
-- bond "đang tìm hiểu" of two saves (sids a < b) that both tapped ❤️.
CREATE TABLE IF NOT EXISTS live_dates (
  id {T} PRIMARY KEY, a {T} NOT NULL, b {T} NOT NULL, a_sid {T} NOT NULL, b_sid {T} NOT NULL, at double precision NOT NULL,
  ended double precision, how {T} NOT NULL DEFAULT '', same bigint NOT NULL DEFAULT 0, hits bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS date_bonds (a {T} NOT NULL, b {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (a, b));
-- 💍 Live weddings (game/wedding_live.py, live/wedding.py): the couple's date for good (insert-only), the parties,
-- the guests who stayed 5 minutes, the group photos, the settled weekly race, closeness between players.
CREATE TABLE IF NOT EXISTS wedding_dates (
  couple bigint PRIMARY KEY, at double precision NOT NULL, source {T} NOT NULL, wedding bigint, created double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS wedding_parties (
  wedding bigint PRIMARY KEY, couple bigint NOT NULL, a {T} NOT NULL, b {T} NOT NULL, at double precision NOT NULL,
  status {T} NOT NULL DEFAULT 'booked', reminded double precision, guests bigint NOT NULL DEFAULT 0, done_at double precision,
  created double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS wedding_guests (
  wedding bigint NOT NULL, sid {T} NOT NULL, pid {T} NOT NULL, ok bigint NOT NULL DEFAULT 0, paid bigint NOT NULL DEFAULT 0,
  steps bigint NOT NULL DEFAULT 0, counted_at double precision NOT NULL, day {T} NOT NULL, week {T} NOT NULL,
  PRIMARY KEY (wedding, sid)
);
CREATE TABLE IF NOT EXISTS wedding_photos (
  wedding bigint NOT NULL, n bigint NOT NULL, sid {T} NOT NULL, at double precision NOT NULL, image {T}, PRIMARY KEY (wedding, n)
);
CREATE TABLE IF NOT EXISTS wedding_race (week {T} PRIMARY KEY, settled double precision NOT NULL, top {T} NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS player_closeness (
  sid {T} NOT NULL, other {T} NOT NULL, points bigint NOT NULL DEFAULT 0, updated double precision NOT NULL, PRIMARY KEY (sid, other)
);
-- 🎤 Phòng hát (game/karaoke.py, live/karaoke.py; SCHEMA_VERSION 26): the oEmbed cache of each YouTube id (only the id,
-- never a link; banned by an admin), the "lượt hát" tickets and tips (one row each, idempotent by id; a queue ticket is
-- redeemed by the live service (used) and stamped when its song starts (played)), and the admin's reviews of reports.
CREATE TABLE IF NOT EXISTS kara_songs (
  vid {T} PRIMARY KEY, title {T} NOT NULL DEFAULT '', channel {T} NOT NULL DEFAULT '', ok bigint NOT NULL DEFAULT 0,
  why {T} NOT NULL DEFAULT '', checked_at double precision NOT NULL DEFAULT 0, plays bigint NOT NULL DEFAULT 0,
  banned bigint NOT NULL DEFAULT 0, banned_by {T}, banned_at double precision
);
CREATE TABLE IF NOT EXISTS kara_tickets (
  id {T} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, amount bigint NOT NULL DEFAULT 0, got bigint NOT NULL DEFAULT 0,
  ref {T}, to_sid {T}, vid {T}, room {T}, used bigint NOT NULL DEFAULT 0, played double precision,
  day {T} NOT NULL, at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS kara_reviews (
  target {T} PRIMARY KEY, verdict {T} NOT NULL, by_admin {T} NOT NULL DEFAULT '', at double precision NOT NULL
);
-- 🐾 Bé cưng của tuần (game/pets.py; SCHEMA_VERSION 27): each player's best-cared pet of a Vietnam ISO week, written in
-- the save's own transaction on jr_pet_* commands. Cosmetic only. A player who erases their data leaves the board.
CREATE TABLE IF NOT EXISTS pet_board (
  sid {T} NOT NULL, week {T} NOT NULL, name {T} NOT NULL, breed {T} NOT NULL, coat bigint NOT NULL DEFAULT 0,
  acc {T} NOT NULL DEFAULT '[]', pts bigint NOT NULL DEFAULT 0, at double precision NOT NULL, PRIMARY KEY (sid, week)
);
CREATE INDEX IF NOT EXISTS pet_board_week ON pet_board(week, pts);
-- 🎆 Mạnh Thường Quân (game/lux.py; SCHEMA_VERSION 28): one row per public sponsorship (fireworks, a numbered bench or
-- lamp, the fair's or a ZPOP night's sponsor of the week, the school library fund), written in the save's own
-- transaction (id '<pid>:<n>', idempotent). `slot` ('ghe_da:7') is unique among plaques: a slot taken refuses the whole
-- command. The weekly board reads it by week. A player who erases their data stays as anonymous (sid '').
CREATE TABLE IF NOT EXISTS lux_gifts (
  id {T} PRIMARY KEY, sid {T} NOT NULL, week {T} NOT NULL, kind {T} NOT NULL, slot {T} NOT NULL DEFAULT '',
  size {T} NOT NULL DEFAULT '', amount bigint NOT NULL CHECK(amount > 0), msg {T} NOT NULL DEFAULT '',
  anon bigint NOT NULL DEFAULT 0, at double precision NOT NULL
);
CREATE INDEX IF NOT EXISTS lux_gifts_week ON lux_gifts(week, sid);
CREATE INDEX IF NOT EXISTS lux_gifts_kind ON lux_gifts(kind, at);
CREATE UNIQUE INDEX IF NOT EXISTS lux_gifts_slot ON lux_gifts(slot) WHERE slot <> '';
-- 🔨 Nhà đấu giá đồ độc bản (game/auction.py; SCHEMA_VERSION 29). One row per lot (system lots: the day's plan
-- '<yyyymmdd>-<slot>' or an operator's 'a<hex>'), locked FOR UPDATE by every bid and by the settlement; `seq` moves on
-- every change (compare-and-set). An item is in at most one open or sold lot (an unsold one goes back to the pool).
CREATE TABLE IF NOT EXISTS auction_lots (
  id {T} PRIMARY KEY, item {T} NOT NULL, kind {T} NOT NULL, tier bigint NOT NULL, name {T} NOT NULL, emoji {T} NOT NULL DEFAULT '',
  data {T} NOT NULL DEFAULT '{{}}', start bigint NOT NULL CHECK(start > 0), step bigint NOT NULL CHECK(step > 0),
  starts_at double precision NOT NULL, ends_at double precision NOT NULL, planned_end double precision NOT NULL,
  status {T} NOT NULL DEFAULT 'open', high bigint NOT NULL DEFAULT 0, high_sid {T} NOT NULL DEFAULT '',
  high_anon bigint NOT NULL DEFAULT 0, bids bigint NOT NULL DEFAULT 0, seq bigint NOT NULL DEFAULT 0,
  winner_sid {T} NOT NULL DEFAULT '', winner_name {T} NOT NULL DEFAULT '', price bigint NOT NULL DEFAULT 0,
  settled_at double precision, src {T} NOT NULL DEFAULT 'plan', created double precision NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS auction_lots_item ON auction_lots(item) WHERE status IN ('open', 'sold');
CREATE INDEX IF NOT EXISTS auction_lots_due ON auction_lots(status, ends_at);
CREATE INDEX IF NOT EXISTS auction_lots_settled ON auction_lots(settled_at);
-- One row per player per lot: the latest bid and the escrow the database knows (`held`, 0 once refunded or burned;
-- refunds travel through live_effects rows 'auc:<lot>:<pid>:b<n>', `refunds` = n).
CREATE TABLE IF NOT EXISTS auction_bids (
  lot {T} NOT NULL, sid {T} NOT NULL, amount bigint NOT NULL CHECK(amount > 0), held bigint NOT NULL DEFAULT 0 CHECK(held >= 0),
  anon bigint NOT NULL DEFAULT 0, n bigint NOT NULL DEFAULT 0, refunds bigint NOT NULL DEFAULT 0, at double precision NOT NULL,
  pushed_at double precision NOT NULL DEFAULT 0, PRIMARY KEY(lot, sid)
);
CREATE INDEX IF NOT EXISTS auction_bids_sid ON auction_bids(sid, lot);
-- 🎙️ Phòng hát mic trực tiếp (game/karaoke_mic.py, live/karaoke.py; SCHEMA_VERSION 30): an account's optional birth year,
-- asked the first time it turns the live mic on (under 16: listening only). Set once; deleted with the player's data.
-- Its own table (not a column of accounts, not a save key): a rollback never sees it.
CREATE TABLE IF NOT EXISTS account_birth (
  sid {T} PRIMARY KEY, year bigint NOT NULL, at double precision NOT NULL
);
-- 🎨 Cho trang trí (game/home_coop.py; SCHEMA_VERSION 31): a friend may move the owner's furniture in one home they own
-- (expires_at NULL: until revoked), and every change they make, with the spots before (`undo`) and after, for Hoàn tác.
-- Tables only, no save key: an older build or a rollback never sees them.
CREATE TABLE IF NOT EXISTS home_deco_grants (
  id {T} PRIMARY KEY, owner {T} NOT NULL, guest {T} NOT NULL,
  home_id {T} NOT NULL, home_kind {T} NOT NULL,
  status {T} NOT NULL CHECK (status IN ('active','revoked','left','expired','ended')),
  created_at double precision NOT NULL, expires_at double precision, ended_at double precision,
  CHECK (owner <> guest)
);
CREATE TABLE IF NOT EXISTS home_deco_log (
  id {ID} PRIMARY KEY, owner {T} NOT NULL, actor {T} NOT NULL,
  home_id {T} NOT NULL, home_kind {T} NOT NULL, text {T} NOT NULL,
  undo {T} NOT NULL, after {T} NOT NULL, at double precision NOT NULL, undone double precision
);
-- 💌 Thiệp mời cưới cả phố (game/wed_invite.py, live/wedinvite.py; SCHEMA_VERSION 32): one row per paid card (`rid` =
-- its marriage_effects debit, idempotent), and per viewer the last card shown (`upto`), today's count and the last card
-- cheered: written only when a card is shown, never in bulk. Tables only, no save key: an older build never sees them.
CREATE TABLE IF NOT EXISTS wed_invites (
  id {ID} PRIMARY KEY, rid {T} NOT NULL UNIQUE, sid {T} NOT NULL, partner {T} NOT NULL, pid {T} NOT NULL, ppid {T} NOT NULL,
  couple bigint NOT NULL, wedding bigint, name_a {T} NOT NULL, name_b {T} NOT NULL, text {T} NOT NULL, raw {T},
  at double precision NOT NULL, until double precision NOT NULL, status {T} NOT NULL DEFAULT 'live',
  cheers bigint NOT NULL DEFAULT 0, by_admin {T}, deleted_at double precision
);
CREATE TABLE IF NOT EXISTS wed_invite_seen (
  sid {T} PRIMARY KEY, upto bigint NOT NULL DEFAULT 0, day {T} NOT NULL, n bigint NOT NULL DEFAULT 0,
  cheer_upto bigint NOT NULL DEFAULT 0
);
-- 🚔 Trại tạm giữ (game/jail.py mark_commit; SCHEMA_VERSION 33): one row per jailed save, `until` its safety release,
-- written in the save's own transaction, so the live server knows "free" from a primary-key lookup (no save read).
-- Not in the save: an older build ignores it (a stale row is checked against the save and deleted).
CREATE TABLE IF NOT EXISTS jail_marks (sid {T} PRIMARY KEY, until double precision NOT NULL);
"""

INDEX_DDL = """
CREATE UNIQUE INDEX IF NOT EXISTS home_guest_active_pair ON home_guest_invites(owner,guest)
  WHERE status IN ('pending','accepted');
CREATE INDEX IF NOT EXISTS home_guest_recipient ON home_guest_invites(guest,status);
CREATE UNIQUE INDEX IF NOT EXISTS home_deco_active_pair ON home_deco_grants(owner,guest) WHERE status='active';
CREATE INDEX IF NOT EXISTS home_deco_guest ON home_deco_grants(guest,status);
CREATE INDEX IF NOT EXISTS home_deco_log_owner ON home_deco_log(owner,id);
CREATE INDEX IF NOT EXISTS home_deco_log_actor ON home_deco_log(actor);
CREATE INDEX IF NOT EXISTS wed_invites_live ON wed_invites(status, id);
CREATE INDEX IF NOT EXISTS wed_invites_sid ON wed_invites(sid, id);
CREATE UNIQUE INDEX IF NOT EXISTS wed_invites_party ON wed_invites(sid, wedding) WHERE wedding IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS family_pending_kind ON family_requests(couple,kind) WHERE status='pending';
CREATE INDEX IF NOT EXISTS family_request_recipient ON family_requests(to_sid,status);
CREATE INDEX IF NOT EXISTS family_custody_owner ON family_custody(sid);
CREATE INDEX IF NOT EXISTS logins_sid ON logins (sid);
CREATE INDEX IF NOT EXISTS tiktok_identity_sid ON tiktok_identities (sid);
CREATE INDEX IF NOT EXISTS tiktok_flow_source ON tiktok_flows (source_sid);
CREATE INDEX IF NOT EXISTS player_feedback_sid ON player_feedback (sid, id);
CREATE INDEX IF NOT EXISTS player_feedback_status ON player_feedback (status, id);
CREATE INDEX IF NOT EXISTS inbox_pid ON inbox (pid, id);
CREATE INDEX IF NOT EXISTS board_career ON board (career, id);
CREATE INDEX IF NOT EXISTS market_status ON market (status, career);
CREATE INDEX IF NOT EXISTS preview_to ON previews (to_pid, id);
CREATE INDEX IF NOT EXISTS gifts_to ON gifts (to_pid, claimed);
CREATE INDEX IF NOT EXISTS push_subs_sid ON push_subs (sid);
CREATE INDEX IF NOT EXISTS push_queue_sid ON push_queue (sid, id);
CREATE INDEX IF NOT EXISTS stat_sessions_seen ON sessions (updated_at, revision, sid);
CREATE INDEX IF NOT EXISTS stat_births_day ON stat_births (day);
CREATE INDEX IF NOT EXISTS stat_active_sid ON stat_active (sid);
CREATE INDEX IF NOT EXISTS stat_play_sid ON stat_play (sid);
CREATE INDEX IF NOT EXISTS stat_leaves_sid ON stat_leaves USING hash (sid);   -- equality only (delete with the save): ~4x smaller than a btree
CREATE INDEX IF NOT EXISTS stat_acquisition_day ON stat_acquisition (day);
CREATE INDEX IF NOT EXISTS stat_milestones_key ON stat_milestones (key, at);   -- "started a workplace" (start:<career>) in a period
CREATE INDEX IF NOT EXISTS hits_k ON hits (k, at);
CREATE INDEX IF NOT EXISTS stat_fb_created ON player_feedback (created_at);
CREATE INDEX IF NOT EXISTS stat_accounts_created ON accounts (created_at);
CREATE INDEX IF NOT EXISTS leaderboard_rank ON leaderboard (board, score DESC, k1 DESC, k2 DESC, since, sid);
CREATE INDEX IF NOT EXISTS lb_weekly_sid ON lb_weekly (sid, final);
CREATE INDEX IF NOT EXISTS lb_weekly_board ON lb_weekly (board, final, week);
CREATE INDEX IF NOT EXISTS marriage_rings_sid ON marriage_rings (sid, status);
CREATE INDEX IF NOT EXISTS proposals_to ON proposals (to_sid, status);
CREATE INDEX IF NOT EXISTS work_places_owner ON work_visit_places(owner,visibility);
CREATE INDEX IF NOT EXISTS work_places_public ON work_visit_places(visibility,updated_at);
CREATE INDEX IF NOT EXISTS work_orders_provider ON work_service_orders(provider,status,created_at);
CREATE INDEX IF NOT EXISTS work_orders_customer ON work_service_orders(customer,created_at);
CREATE INDEX IF NOT EXISTS work_reviews_place ON work_service_reviews(place,created_at);
CREATE INDEX IF NOT EXISTS proposals_from ON proposals (from_sid, at);
CREATE INDEX IF NOT EXISTS weddings_couple ON weddings (couple, status);
CREATE INDEX IF NOT EXISTS marriage_effects_sid ON marriage_effects (sid, status, due);
CREATE INDEX IF NOT EXISTS news_at ON news (at);
CREATE INDEX IF NOT EXISTS friend_requests_to ON friend_requests (to_sid, status);
CREATE INDEX IF NOT EXISTS friend_requests_from ON friend_requests (from_sid, at);
CREATE INDEX IF NOT EXISTS friend_searches_sid ON friend_searches (sid, at);
CREATE INDEX IF NOT EXISTS joint_ledger_couple ON joint_ledger (couple, id);
CREATE INDEX IF NOT EXISTS joint_ledger_held ON joint_ledger (sid, status);
CREATE INDEX IF NOT EXISTS couple_requests_couple ON couple_requests (couple, status);
CREATE INDEX IF NOT EXISTS couple_debts_people ON couple_debts (lender, borrower);
CREATE INDEX IF NOT EXISTS couple_moments_couple ON couple_moments (couple, id);
CREATE INDEX IF NOT EXISTS system_gifts_sid ON system_gifts (sid, status);
CREATE INDEX IF NOT EXISTS system_gifts_created ON system_gifts (created);
CREATE INDEX IF NOT EXISTS chat_members_pid ON chat_members (pid, channel);
CREATE INDEX IF NOT EXISTS chat_messages_channel ON chat_messages (channel, id);
CREATE INDEX IF NOT EXISTS chat_messages_pid ON chat_messages (pid, id);
CREATE INDEX IF NOT EXISTS chat_messages_reported ON chat_messages (id) WHERE reports > 0;
CREATE INDEX IF NOT EXISTS chat_reacts_pid ON chat_reacts (pid);
CREATE INDEX IF NOT EXISTS chat_hides_msg ON chat_hides (msg);
CREATE INDEX IF NOT EXISTS chat_clears_pid ON chat_clears (pid);
CREATE INDEX IF NOT EXISTS live_effects_sid ON live_effects (sid, status);
CREATE INDEX IF NOT EXISTS live_effects_day ON live_effects (sid, kind, at);
CREATE INDEX IF NOT EXISTS quay_jobs_owner ON quay_jobs (owner, status);
CREATE INDEX IF NOT EXISTS quay_jobs_worker ON quay_jobs (worker, status);
CREATE INDEX IF NOT EXISTS quay_jobs_open ON quay_jobs (status, until);
CREATE INDEX IF NOT EXISTS bank_xfers_receiver ON bank_xfers (receiver, status);
CREATE INDEX IF NOT EXISTS bank_xfers_sender ON bank_xfers (sender, at);
CREATE INDEX IF NOT EXISTS bank_xfers_open ON bank_xfers (status, at);
CREATE INDEX IF NOT EXISTS live_dates_at ON live_dates (at);
CREATE INDEX IF NOT EXISTS date_bonds_b ON date_bonds (b);
CREATE INDEX IF NOT EXISTS wedding_parties_at ON wedding_parties (status, at);
CREATE INDEX IF NOT EXISTS wedding_guests_week ON wedding_guests (week, ok);
CREATE INDEX IF NOT EXISTS wedding_guests_sid ON wedding_guests (sid, day);
CREATE INDEX IF NOT EXISTS kara_tickets_sid ON kara_tickets (sid, kind, day);
CREATE INDEX IF NOT EXISTS kara_tickets_to ON kara_tickets (to_sid, kind, day) WHERE to_sid IS NOT NULL;
CREATE INDEX IF NOT EXISTS reports_kind_at ON reports (kind, at);
"""

# Store.delete, prune and prune_guests remove dependent rows before their save.
# Statistics triggers update the admin counters atomically with each write.
TRIGGER_DDL = f"""
CREATE OR REPLACE FUNCTION mnl_stat_session_born() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_births (sid, day) VALUES (NEW.sid, {VN_DAY}) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_session_active() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_active (day, sid) VALUES ({VN_DAY}, NEW.sid) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
-- A deleted save keeps its stat rows (owner, 02/10: statistics kept forever): the *_gone functions do nothing.
CREATE OR REPLACE FUNCTION mnl_stat_session_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_play_cmd() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  _at double precision := extract(epoch FROM statement_timestamp());
  _vn timestamp := (statement_timestamp() AT TIME ZONE 'UTC') + interval '7 hours';
BEGIN
  INSERT INTO stat_play AS p (day, sid, secs, sessions, cmds, first_at, last_at, hours, sess_at, lens)
  VALUES (to_char(_vn, 'YYYY-MM-DD'), NEW.sid, {PLAY_IDLE_TAIL}, 1, 1, _at, _at, 1 << extract(hour FROM _vn)::int, _at, '')
  ON CONFLICT (day, sid) DO UPDATE SET
    secs = p.secs + CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN GREATEST(round(_at - p.last_at), 0)::bigint ELSE {PLAY_IDLE_TAIL} END,
    sessions = p.sessions + CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN 0 ELSE 1 END,
    cmds = p.cmds + 1,
    last_at = GREATEST(p.last_at, _at),
    hours = p.hours | EXCLUDED.hours,
    sess_at = CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN p.sess_at ELSE _at END,
    lens = CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN p.lens
                ELSE p.lens || (round(p.last_at - p.sess_at)::bigint + {PLAY_IDLE_TAIL})::text || ',' END;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_play_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_retention_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_fb_seen() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_fb_ack (id, at) VALUES (NEW.id, NEW.updated_at) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_fb_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RETURN NULL;
END $$;
CREATE OR REPLACE TRIGGER stat_session_born AFTER INSERT ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_born();
CREATE OR REPLACE TRIGGER stat_session_active AFTER UPDATE OF updated_at ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_active();
CREATE OR REPLACE TRIGGER stat_session_gone AFTER DELETE ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_gone();
CREATE OR REPLACE TRIGGER stat_play_cmd AFTER INSERT ON receipts FOR EACH ROW EXECUTE FUNCTION mnl_stat_play_cmd();
CREATE OR REPLACE TRIGGER stat_play_gone AFTER DELETE ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_play_gone();
CREATE OR REPLACE TRIGGER stat_retention_gone AFTER DELETE ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_retention_gone();
CREATE OR REPLACE TRIGGER stat_fb_seen AFTER UPDATE OF status ON player_feedback FOR EACH ROW
  WHEN (OLD.status = 'new' AND NEW.status <> 'new') EXECUTE FUNCTION mnl_stat_fb_seen();
CREATE OR REPLACE TRIGGER stat_fb_gone AFTER DELETE ON player_feedback FOR EACH ROW EXECUTE FUNCTION mnl_stat_fb_gone();
"""

# Only changed when different (ALTER TABLE takes an exclusive lock on the table).
TUNING_DDL = """
DO $$
DECLARE want text;
BEGIN
  BEGIN
    IF (SELECT attcompression FROM pg_attribute WHERE attrelid = 'sessions'::regclass AND attname = 'state') IS DISTINCT FROM 'l' THEN
      ALTER TABLE sessions ALTER COLUMN state SET COMPRESSION lz4;
    END IF;
    IF (SELECT attcompression FROM pg_attribute WHERE attrelid = 'archive'::regclass AND attname = 'row') IS DISTINCT FROM 'l' THEN
      ALTER TABLE archive ALTER COLUMN row SET COMPRESSION lz4;
    END IF;
  EXCEPTION WHEN feature_not_supported OR invalid_parameter_value THEN
    RAISE NOTICE 'lz4 is not available on this server: TOAST keeps pglz';
  END;
  -- Every command rewrites a whole save (100 KB - 1.3 MB): vacuum the hot table and its TOAST early.
  want := 'autovacuum_vacuum_scale_factor=0.02';
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE oid = 'sessions'::regclass AND want = ANY (coalesce(reloptions, '{}'))) THEN
    ALTER TABLE sessions SET (autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.05,
                              toast.autovacuum_vacuum_scale_factor = 0.02);
  END IF;
END $$;
"""

STAGES = (("tables", TABLES_DDL), ("indexes", INDEX_DDL), ("triggers", TRIGGER_DDL), ("tuning", TUNING_DDL))

# (table, trigger) pairs installed by TRIGGER_DDL.
TRIGGERS = [('sessions', 'stat_session_born'), ('sessions', 'stat_session_active'), ('sessions', 'stat_session_gone'),
            ('player_feedback', 'stat_fb_seen'), ('player_feedback', 'stat_fb_gone'),
            ('receipts', 'stat_play_cmd'), ('sessions', 'stat_play_gone'), ('sessions', 'stat_retention_gone')]


# Runtime catalog: installed tables and their generated identity columns.
TABLES = [
    dict(name='family_children', identity=None),
    dict(name='family_custody', identity=None),
    dict(name='family_requests', identity='id'),
    dict(name='family_receipts', identity=None),
    dict(name='sessions', identity=None),
    dict(name='receipts', identity=None),
    dict(name='accounts', identity='uid'),
    dict(name='logins', identity=None),
    dict(name='tiktok_identities', identity=None),
    dict(name='tiktok_flows', identity=None),
    dict(name='player_feedback', identity='id'),
    dict(name='archive', identity=None),
    dict(name='profiles', identity=None),
    dict(name='work_visit_places', identity=None),
    dict(name='work_service_orders', identity=None),
    dict(name='work_service_reviews', identity=None),
    dict(name='visits', identity=None),
    dict(name='previews', identity='id'),
    dict(name='gifts', identity='id'),
    dict(name='market', identity='id'),
    dict(name='board', identity='id'),
    dict(name='comments', identity='id'),
    dict(name='reactions', identity=None),
    dict(name='follows', identity=None),
    dict(name='blocks', identity=None),
    dict(name='reports', identity=None),
    dict(name='inbox', identity='id'),
    dict(name='push_subs', identity=None),
    dict(name='push_queue', identity='id'),
    dict(name='push_daily', identity=None),
    dict(name='stat_births', identity=None),
    dict(name='stat_active', identity=None),
    dict(name='stat_play', identity=None),
    dict(name='stat_play_est', identity=None),
    dict(name='stat_play_daily', identity=None),
    dict(name='stat_milestones', identity=None),
    dict(name='stat_actions', identity=None),
    dict(name='stat_actions_daily', identity=None),
    dict(name='stat_rollups', identity=None),
    dict(name='stat_leaves', identity='id'),
    dict(name='stat_leave_last', identity=None),
    dict(name='stat_client_errors', identity=None),
    dict(name='stat_loads', identity=None),
    dict(name='stat_acquisition', identity=None),
    dict(name='stat_fb_ack', identity=None),
    dict(name='hits', identity=None),
    dict(name='leaderboard', identity=None),
    dict(name='leaderboard_players', identity=None),
    dict(name='leaderboard_meta', identity=None),
    dict(name='lb_weekly', identity=None),
    dict(name='marriage_people', identity=None),
    dict(name='marriage_rings', identity=None),
    dict(name='proposals', identity='id'),
    dict(name='couples', identity='id'),
    dict(name='marriage_bonds', identity=None),
    dict(name='weddings', identity='id'),
    dict(name='marriage_effects', identity=None),
    dict(name='marriage_blocks', identity=None),
    dict(name='news', identity='id'),
    dict(name='friend_prefs', identity=None),
    dict(name='friend_requests', identity='id'),
    dict(name='friends', identity=None),
    dict(name='home_guest_invites', identity=None),
    dict(name='friend_searches', identity=None),
    dict(name='joint_funds', identity=None),
    dict(name='joint_ledger', identity='id'),
    dict(name='couple_requests', identity='id'),
    dict(name='couple_debts', identity='id'),
    dict(name='couple_moments', identity='id'),
    dict(name='couple_stats', identity=None),
    dict(name='system_gifts', identity=None),
    dict(name='chat_channels', identity=None),
    dict(name='chat_members', identity=None),
    dict(name='chat_messages', identity='id'),
    dict(name='chat_mutes', identity=None),
    dict(name='chat_prefs', identity=None),
    dict(name='chat_reacts', identity=None),
    dict(name='chat_pins', identity=None),
    dict(name='chat_faces', identity=None),
    dict(name='chat_hides', identity=None),
    dict(name='chat_clears', identity=None),
    dict(name='chat_slow', identity=None),
    dict(name='donations', identity=None),
    dict(name='chat_style', identity=None),
    dict(name='live_effects', identity=None),
    dict(name='quay_jobs', identity=None),
    dict(name='quay_funding', identity=None),
    dict(name='rentals', identity=None),
    dict(name='rental_receipts', identity=None),
    dict(name='rental_closed_accounts', identity=None),
    dict(name='bank_xfers', identity=None),
    dict(name='bank_xfer_days', identity=None),
    dict(name='live_dates', identity=None),
    dict(name='date_bonds', identity=None),
    dict(name='wedding_dates', identity=None),
    dict(name='wedding_parties', identity=None),
    dict(name='wedding_guests', identity=None),
    dict(name='wedding_photos', identity=None),
    dict(name='wedding_race', identity=None),
    dict(name='player_closeness', identity=None),
    dict(name='kara_songs', identity=None),
    dict(name='kara_tickets', identity=None),
    dict(name='kara_reviews', identity=None),
    dict(name='pet_board', identity=None),
    dict(name='lux_gifts', identity=None),
    dict(name='auction_lots', identity=None),
    dict(name='auction_bids', identity=None),
    dict(name='account_birth', identity=None),
    dict(name='home_deco_grants', identity=None),
    dict(name='home_deco_log', identity='id'),
    dict(name='wed_invites', identity='id'),
    dict(name='wed_invite_seen', identity=None),
    dict(name='jail_marks', identity=None),
    dict(name='mnl_meta', identity=None),
]

TABLE = {t['name']: t for t in TABLES}


def _run(conn, script: str) -> None:
    """Run a DDL script on a psycopg connection (or a game.db.PgConnection)."""
    raw = getattr(conn, 'raw', conn)
    raw.execute(script)


def installed_version(conn) -> int:
    raw = getattr(conn, 'raw', conn)
    if raw.execute("SELECT to_regclass('mnl_meta')").fetchone()[0] is None:
        return 0
    row = raw.execute("SELECT value FROM mnl_meta WHERE key = 'schema_version'").fetchone()
    return int(row[0]) if row else 0


def missing_tables(conn) -> list:
    """Tables of TABLES that do not exist in the current schema (one catalog query)."""
    raw = getattr(conn, 'raw', conn)
    names = [t['name'] for t in TABLES]
    have = {r[0] for r in raw.execute("SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
                                      "WHERE n.nspname = current_schema() AND c.relkind IN ('r', 'p') AND c.relname = ANY(%s)", (names,))}
    return [n for n in names if n not in have]


def repair_character_names(conn) -> None:
    """One-time repair for settings renames made before schema 22.

    Lock sessions first, in sid order, then update accounts: the same lock order
    as a settings commit. A concurrent rename that finishes while this query
    waits supplies its current name through PostgreSQL's locked-row recheck,
    rather than being overwritten from an earlier snapshot of the save.
    """
    raw = getattr(conn, 'raw', conn)
    raw.execute(f"""
        WITH locked AS MATERIALIZED (
          SELECT s.sid, CASE WHEN jsonb_typeof(s.state::jsonb->'name')='string'
                 THEN btrim(s.state::jsonb->>'name', E' \\t\\n\\r') END AS name
          FROM sessions s JOIN accounts a ON a.sid=s.sid
          ORDER BY s.sid FOR UPDATE OF s
        ), renamed AS (
          UPDATE accounts a SET display=l.name, updated_at={NOW_TEXT}
          FROM locked l WHERE a.sid=l.sid AND length(l.name) BETWEEN 1 AND 24
            AND l.name <> 'Mây' AND a.display IS DISTINCT FROM l.name
          RETURNING a.sid
        )
        SELECT pg_notify('mnl_live', json_build_object('op','name','sid',sid)::text)
        FROM renamed
    """)


def ensure(conn, stages=None, force: bool = False) -> bool:
    """Create what is missing, idempotently, in the connection's current schema (search_path).
    `stages`: a subset of ("tables", "indexes", "triggers", "tuning").
    Without `force`, a database already at SCHEMA_VERSION is left alone (no DDL, no locks).
    Returns True when an upgrade ran. DDL and data repair commit separately
    so live player transactions can finish before repair takes their row locks.
    Requires an autocommit connection."""
    raw = getattr(conn, 'raw', conn)
    everything = stages is None
    previous_version = installed_version(raw)
    if everything and not force and previous_version >= SCHEMA_VERSION and not missing_tables(raw):
        return False
    with raw.transaction():
        # Serialize startup upgrades in this schema, rechecking after the wait.
        raw.execute("SELECT pg_advisory_xact_lock(17822, hashtext(current_schema()))")
        previous_version = installed_version(raw)
        if everything and not force and previous_version >= SCHEMA_VERSION and not missing_tables(raw):
            return False
        # one-off DDL (an index on a big table, a slow disk): not bound by the request timeout
        raw.execute("SELECT set_config('statement_timeout', '600s', true)")
        for name, ddl in STAGES:
            if everything or name in stages:
                raw.execute(ddl)
        if everything:
            # Schema 21 is usable if the following name repair is interrupted.
            # Never hold DDL relation locks while waiting on player session rows.
            version = 21 if previous_version < 22 else SCHEMA_VERSION
            raw.execute("INSERT INTO mnl_meta (key, value) VALUES ('schema_version', %s) "
                        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value", (str(version),))
    if everything and previous_version < 22:
        with raw.transaction():
            raw.execute("SELECT pg_advisory_xact_lock(17822, hashtext(current_schema()))")
            raw.execute("SELECT set_config('statement_timeout', '600s', true)")
            if installed_version(raw) < 22:
                repair_character_names(raw)
                raw.execute("UPDATE mnl_meta SET value=%s WHERE key='schema_version'", (str(SCHEMA_VERSION),))
    return True


def reset_sequences(conn, floors: dict | None = None) -> dict:
    """Advance identities past max(id) or supplied {table: sequence floor}.
    Returns {table: next id}. Safe to run again after a database restore."""
    raw = getattr(conn, 'raw', conn)
    floors = floors or {}
    out = {}
    for t in TABLES:
        col = t['identity']
        if not col:
            continue
        top = raw.execute(f'SELECT COALESCE(MAX({col}), 0) FROM {t["name"]}').fetchone()[0]
        top = max(int(top), int(floors.get(t['name']) or 0))
        seq = raw.execute('SELECT pg_get_serial_sequence(%s, %s)', (t['name'], col)).fetchone()[0]
        if top > 0:
            raw.execute('SELECT setval(%s, %s, true)', (seq, top))
        else:
            raw.execute('SELECT setval(%s, 1, false)', (seq,))
        out[t['name']] = top + 1
    return out
