"""PostgreSQL schema of the game: every table of the main SQLite database plus the
shared rate-limit table `hits` (formerly `<db>-limits.sqlite3`), in one database.

Faithful to the SQLite columns, so rows round-trip byte for byte:
* SQLite TEXT -> text COLLATE "C" (byte order, like SQLite's BINARY collation:
  ORDER BY, comparisons and UNIQUE behave exactly as in SQLite). Timestamps stay
  text 'YYYY-MM-DD HH:MM:SS' (UTC), the format of SQLite's CURRENT_TIMESTAMP.
* SQLite REAL -> double precision, INTEGER -> bigint.
* `sessions.state` stays text (not jsonb): the exact JSON bytes are kept. Its TOAST
  compression is lz4 when the server supports it (PG16 on Ubuntu does), else pglz.
* INTEGER PRIMARY KEY AUTOINCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY: copied
  ids are kept as they are; after a copy, call reset_sequences(conn, floors) so new
  ids continue after the copied ones (and after SQLite's sqlite_sequence, when given).

Machine-readable description: TABLES (one dict per table, see the keys below).
DDL is split in stages so a bulk copy can run between them:
  TABLES_DDL      tables, primary keys and UNIQUE constraints
  INDEX_DDL       secondary indexes (build after a bulk copy: faster)
  TRIGGER_DDL     the admin-statistics triggers (create them AFTER the initial copy:
                  on a bulk insert into `sessions` they would stamp every save as born today,
                  and one into `receipts` would count every copied command as played now)
  TUNING_DDL      lz4 TOAST compression and autovacuum settings of the hot tables
ensure(conn) runs every stage idempotently (the game server calls it at start-up) and
records SCHEMA_VERSION in `mnl_meta`, so later start-ups skip the DDL (and its locks).

Delta-sync hints (TABLES[i]["sync"]):
  {"mode": "revision", ...}  rows change in place; a row changed iff its `revision`
                             differs (sessions: every save write bumps revision;
                             updated_at is NOT touched by save migrations on read).
  {"mode": "insert_only", "column": c}  rows are only inserted (and deleted);
                             `c` grows with time. Deleted rows must be found by key.
  {"mode": "updated", "column": c}  every UPDATE sets `c` (plus inserts/deletes).
  {"mode": "full"}           small or updated without a marker: copy it whole.
"""
from __future__ import annotations

SCHEMA_VERSION = 3   # 2: leaderboard, marriage/friends/couple tables, stat_fb_created, stat_accounts_created; 3: stat_play

# The text forms SQLite produces, computed by PostgreSQL (UTC, independent of TimeZone).
NOW_TEXT = "to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"       # CURRENT_TIMESTAMP
UNIXEPOCH = "floor(extract(epoch FROM statement_timestamp()))"                                # unixepoch()
VN_DAY = "to_char((statement_timestamp() AT TIME ZONE 'UTC') + interval '7 hours', 'YYYY-MM-DD')"  # date('now','+7 hours')

# Play time (stat_play, the same rule as game/admin_stats.py SCHEMA): a command within PLAY_GAP seconds
# of the save's previous one that day continues the session (the gap counts as played); a longer gap
# starts a new session. Each session also counts PLAY_IDLE_TAIL seconds after its last command.
PLAY_GAP = 600
PLAY_IDLE_TAIL = 60

T = 'text COLLATE "C"'          # every SQLite TEXT column
ID = 'bigint GENERATED BY DEFAULT AS IDENTITY'

TABLES_DDL = f"""
CREATE TABLE IF NOT EXISTS mnl_meta (key {T} PRIMARY KEY, value {T} NOT NULL);

CREATE TABLE IF NOT EXISTS sessions (
  sid {T} PRIMARY KEY, csrf {T} NOT NULL, revision bigint NOT NULL DEFAULT 0,
  state {T} NOT NULL, updated_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS receipts (
  sid {T} NOT NULL, request_id {T} NOT NULL, request_hash {T} NOT NULL,
  result {T} NOT NULL, created_at {T} NOT NULL DEFAULT {NOW_TEXT},
  PRIMARY KEY (sid, request_id)
);
CREATE TABLE IF NOT EXISTS accounts (
  uid {ID} PRIMARY KEY, username {T} UNIQUE NOT NULL, display {T} NOT NULL,
  pw {T} NOT NULL, sid {T} UNIQUE NOT NULL,
  created_at {T} NOT NULL DEFAULT {NOW_TEXT}, updated_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS logins (
  token {T} PRIMARY KEY, sid {T} NOT NULL, csrf {T} NOT NULL,
  created_at {T} NOT NULL DEFAULT {NOW_TEXT}, seen_at {T} NOT NULL DEFAULT {NOW_TEXT}
);
CREATE TABLE IF NOT EXISTS player_feedback (
  id {ID} PRIMARY KEY, sid {T} NOT NULL, account {T},
  kind {T} NOT NULL, text {T} NOT NULL, context {T} NOT NULL DEFAULT '{{}}',
  status {T} NOT NULL DEFAULT 'new', reply {T},
  created_at double precision NOT NULL, updated_at double precision NOT NULL, replied_at double precision
);
CREATE TABLE IF NOT EXISTS archive (
  sid {T} NOT NULL, career {T} NOT NULL, kind {T} NOT NULL, seq bigint NOT NULL,
  day bigint, row {T} NOT NULL, created_at double precision NOT NULL DEFAULT {UNIXEPOCH},
  CONSTRAINT archive_rows UNIQUE (sid, career, kind, seq)
);

CREATE TABLE IF NOT EXISTS profiles (
  pid {T} PRIMARY KEY, sid {T} UNIQUE NOT NULL, name {T}, name_key {T} UNIQUE, bio {T} NOT NULL DEFAULT '',
  avatar {T} NOT NULL DEFAULT '🌸', visible bigint NOT NULL DEFAULT 0, shop {T} NOT NULL DEFAULT '{{}}',
  served bigint NOT NULL DEFAULT 0, week_key {T} NOT NULL DEFAULT '', week_base bigint NOT NULL DEFAULT 0,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0,
  created double precision NOT NULL, updated double precision NOT NULL, seen double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS visits (
  from_pid {T}, to_pid {T}, day {T}, at double precision, PRIMARY KEY (from_pid, to_pid, day)
);
CREATE TABLE IF NOT EXISTS previews (
  id {ID} PRIMARY KEY, from_pid {T} NOT NULL, to_pid {T} NOT NULL, career {T} NOT NULL, day {T} NOT NULL,
  stars bigint NOT NULL, text {T} NOT NULL, reply {T}, reply_at double precision, at double precision NOT NULL,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0, UNIQUE (from_pid, to_pid, day)
);
CREATE TABLE IF NOT EXISTS gifts (
  id {ID} PRIMARY KEY, from_pid {T} NOT NULL, to_pid {T} NOT NULL, sticker {T} NOT NULL, coins bigint NOT NULL,
  note {T} NOT NULL DEFAULT '', day {T} NOT NULL, at double precision NOT NULL, claimed bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS market (
  id {ID} PRIMARY KEY, seller {T} NOT NULL, career {T} NOT NULL, item {T} NOT NULL, qty bigint NOT NULL,
  price bigint NOT NULL, life_left bigint NOT NULL, unit_cost bigint NOT NULL, listed_day bigint NOT NULL,
  status {T} NOT NULL, buyer {T}, at double precision NOT NULL, sold_at double precision, settled bigint NOT NULL DEFAULT 0,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS board (
  id {ID} PRIMARY KEY, pid {T} NOT NULL, career {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL,
  at double precision NOT NULL, reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS comments (
  id {ID} PRIMARY KEY, post bigint NOT NULL, pid {T} NOT NULL, text {T} NOT NULL, at double precision NOT NULL,
  reports bigint NOT NULL DEFAULT 0, hidden bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS reactions (post bigint NOT NULL, pid {T} NOT NULL, emoji {T} NOT NULL, PRIMARY KEY (post, pid, emoji));
CREATE TABLE IF NOT EXISTS follows (pid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (pid, target));
CREATE TABLE IF NOT EXISTS blocks (pid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (pid, target));
CREATE TABLE IF NOT EXISTS reports (
  reporter {T} NOT NULL, kind {T} NOT NULL, target {T} NOT NULL, reason {T} NOT NULL, at double precision NOT NULL,
  PRIMARY KEY (reporter, kind, target)
);
CREATE TABLE IF NOT EXISTS inbox (
  id {ID} PRIMARY KEY, pid {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL, ref {T}, at double precision NOT NULL,
  read bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS push_subs (
  endpoint {T} PRIMARY KEY, sid {T} NOT NULL, created double precision NOT NULL, last_ok double precision,
  fails bigint NOT NULL DEFAULT 0, prefs {T} NOT NULL DEFAULT '{{}}'
);
CREATE TABLE IF NOT EXISTS push_queue (
  id {ID} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, body {T} NOT NULL, url {T} NOT NULL,
  at double precision NOT NULL, sent bigint NOT NULL DEFAULT 0, shown bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS push_daily (sid {T} PRIMARY KEY, day {T} NOT NULL);

CREATE TABLE IF NOT EXISTS stat_births (sid {T} PRIMARY KEY, day {T} NOT NULL);
CREATE TABLE IF NOT EXISTS stat_active (day {T} NOT NULL, sid {T} NOT NULL, PRIMARY KEY (day, sid));
CREATE TABLE IF NOT EXISTS stat_fb_ack (id bigint PRIMARY KEY, at double precision NOT NULL);
-- Play time per save per Vietnam day (game/admin_stats.py "Thời gian chơi"), kept by the trigger
-- stat_play_cmd on receipts (one receipt = one game command). Today's rows are updated on every
-- command: room on each page for HOT updates (no index write) and an early vacuum.
CREATE TABLE IF NOT EXISTS stat_play (
  day {T} NOT NULL, sid {T} NOT NULL, secs bigint NOT NULL, sessions bigint NOT NULL, cmds bigint NOT NULL,
  first_at double precision NOT NULL, last_at double precision NOT NULL, hours bigint NOT NULL DEFAULT 0,
  sess_at double precision NOT NULL, lens {T} NOT NULL DEFAULT '',
  PRIMARY KEY (day, sid)
) WITH (fillfactor = 90, autovacuum_vacuum_scale_factor = 0.01, autovacuum_analyze_scale_factor = 0.02);
CREATE TABLE IF NOT EXISTS stat_play_est (day {T} PRIMARY KEY, saves bigint NOT NULL, capped bigint NOT NULL, at double precision NOT NULL);

CREATE TABLE IF NOT EXISTS hits (k {T} NOT NULL, at double precision NOT NULL);

-- Bảng xếp hạng (game/leaderboard.py)
CREATE TABLE IF NOT EXISTS leaderboard (
  sid {T} NOT NULL, board {T} NOT NULL,
  score bigint NOT NULL, k1 bigint NOT NULL, k2 bigint NOT NULL,
  level bigint NOT NULL, days bigint NOT NULL, served bigint NOT NULL,
  stars bigint NOT NULL, mastered bigint NOT NULL,
  since double precision NOT NULL, updated double precision NOT NULL,
  PRIMARY KEY (sid, board)
);
CREATE TABLE IF NOT EXISTS leaderboard_players (
  sid {T} PRIMARY KEY, name {T}, show bigint, updated double precision NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS leaderboard_meta (k {T} PRIMARY KEY, v {T} NOT NULL);

-- Hôn nhân (game/marriage.py), bạn bè (game/friends.py), vợ chồng (game/couple.py)
CREATE TABLE IF NOT EXISTS marriage_people (
  sid {T} PRIMARY KEY, code {T} UNIQUE NOT NULL, accept bigint NOT NULL DEFAULT 1,
  life_day bigint, pool {T}, remarry_after double precision NOT NULL DEFAULT 0,
  notice {T}, notice_at double precision, created double precision NOT NULL, updated double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS marriage_rings (
  id {T} PRIMARY KEY, sid {T} NOT NULL, tier {T} NOT NULL, price bigint NOT NULL,
  status {T} NOT NULL, at double precision NOT NULL, metal {T}, stone {T}
);
CREATE TABLE IF NOT EXISTS proposals (
  id {ID} PRIMARY KEY, from_sid {T} NOT NULL, to_sid {T} NOT NULL, ring {T} NOT NULL,
  message {T} NOT NULL, announce bigint NOT NULL DEFAULT 1, status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS couples (
  id {ID} PRIMARY KEY, a {T} NOT NULL, b {T} NOT NULL, ring {T},
  status {T} NOT NULL, since double precision NOT NULL, married_at double precision, ended double precision, ended_by {T}
);
CREATE TABLE IF NOT EXISTS marriage_bonds (sid {T} PRIMARY KEY, couple bigint NOT NULL);
CREATE TABLE IF NOT EXISTS weddings (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, status {T} NOT NULL,
  version bigint NOT NULL DEFAULT 1, planner {T}, plan {T} NOT NULL, quote {T} NOT NULL,
  split_a bigint NOT NULL DEFAULT 50, announce_a bigint NOT NULL DEFAULT 1, announce_b bigint NOT NULL DEFAULT 1,
  days bigint NOT NULL, target_a bigint, target_b bigint, due_at double precision,
  deposit_a bigint NOT NULL DEFAULT 0, deposit_b bigint NOT NULL DEFAULT 0, result {T},
  seen_a bigint NOT NULL DEFAULT 0, seen_b bigint NOT NULL DEFAULT 0,
  created double precision NOT NULL, confirmed_at double precision, done_at double precision
);
CREATE TABLE IF NOT EXISTS marriage_effects (
  id {T} PRIMARY KEY, sid {T} NOT NULL, kind {T} NOT NULL, amount bigint NOT NULL DEFAULT 0,
  label {T} NOT NULL DEFAULT '', data {T} NOT NULL DEFAULT '{{}}', status {T} NOT NULL,
  due double precision NOT NULL DEFAULT 0, at double precision NOT NULL, applied_at double precision
);
CREATE TABLE IF NOT EXISTS marriage_blocks (sid {T} NOT NULL, target {T} NOT NULL, at double precision NOT NULL, PRIMARY KEY (sid, target));
CREATE TABLE IF NOT EXISTS news (
  id {ID} PRIMARY KEY, kind {T} NOT NULL, ref {T} UNIQUE NOT NULL, text {T} NOT NULL,
  a {T}, b {T}, at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS friend_prefs (sid {T} PRIMARY KEY, findable bigint NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS friend_requests (
  id {ID} PRIMARY KEY, from_sid {T} NOT NULL, to_sid {T} NOT NULL, status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS friends (sid {T} NOT NULL, friend {T} NOT NULL, since double precision NOT NULL, PRIMARY KEY (sid, friend));
CREATE TABLE IF NOT EXISTS friend_searches (sid {T} NOT NULL, at double precision NOT NULL);
CREATE TABLE IF NOT EXISTS joint_funds (couple bigint PRIMARY KEY, balance bigint NOT NULL DEFAULT 0, updated double precision NOT NULL);
CREATE TABLE IF NOT EXISTS joint_ledger (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, sid {T}, kind {T} NOT NULL, amount bigint NOT NULL,
  balance bigint NOT NULL, label {T} NOT NULL DEFAULT '', ref {T} UNIQUE NOT NULL, status {T} NOT NULL DEFAULT 'done', at double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS couple_requests (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, from_sid {T} NOT NULL, to_sid {T} NOT NULL, kind {T} NOT NULL,
  amount bigint NOT NULL DEFAULT 0, note {T} NOT NULL DEFAULT '', loan bigint NOT NULL DEFAULT 0, debt bigint,
  status {T} NOT NULL, at double precision NOT NULL, decided double precision
);
CREATE TABLE IF NOT EXISTS couple_debts (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, lender {T} NOT NULL, borrower {T} NOT NULL,
  amount bigint NOT NULL, repaid bigint NOT NULL DEFAULT 0, status {T} NOT NULL, note {T} NOT NULL DEFAULT '',
  ref {T} UNIQUE NOT NULL, at double precision NOT NULL, updated double precision NOT NULL
);
CREATE TABLE IF NOT EXISTS couple_moments (
  id {ID} PRIMARY KEY, couple bigint NOT NULL, sid {T} NOT NULL, kind {T} NOT NULL, text {T} NOT NULL,
  key {T} UNIQUE NOT NULL, at double precision NOT NULL, seen bigint NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS couple_stats (
  couple bigint PRIMARY KEY, happy bigint NOT NULL DEFAULT 0, streak bigint NOT NULL DEFAULT 0, best bigint NOT NULL DEFAULT 0,
  last_day bigint NOT NULL DEFAULT 0, today bigint NOT NULL DEFAULT 0
);
"""

INDEX_DDL = """
CREATE INDEX IF NOT EXISTS logins_sid ON logins (sid);
CREATE INDEX IF NOT EXISTS player_feedback_sid ON player_feedback (sid, id);
CREATE INDEX IF NOT EXISTS player_feedback_status ON player_feedback (status, id);
CREATE INDEX IF NOT EXISTS inbox_pid ON inbox (pid, id);
CREATE INDEX IF NOT EXISTS board_career ON board (career, id);
CREATE INDEX IF NOT EXISTS market_status ON market (status, career);
CREATE INDEX IF NOT EXISTS preview_to ON previews (to_pid, id);
CREATE INDEX IF NOT EXISTS gifts_to ON gifts (to_pid, claimed);
CREATE INDEX IF NOT EXISTS push_subs_sid ON push_subs (sid);
CREATE INDEX IF NOT EXISTS push_queue_sid ON push_queue (sid, id);
CREATE INDEX IF NOT EXISTS stat_sessions_seen ON sessions (updated_at, revision, sid);
CREATE INDEX IF NOT EXISTS stat_births_day ON stat_births (day);
CREATE INDEX IF NOT EXISTS stat_active_sid ON stat_active (sid);
CREATE INDEX IF NOT EXISTS stat_play_sid ON stat_play (sid);
CREATE INDEX IF NOT EXISTS hits_k ON hits (k, at);
CREATE INDEX IF NOT EXISTS stat_fb_created ON player_feedback (created_at);
CREATE INDEX IF NOT EXISTS stat_accounts_created ON accounts (created_at);
CREATE INDEX IF NOT EXISTS leaderboard_rank ON leaderboard (board, score DESC, k1 DESC, k2 DESC, since, sid);
CREATE INDEX IF NOT EXISTS marriage_rings_sid ON marriage_rings (sid, status);
CREATE INDEX IF NOT EXISTS proposals_to ON proposals (to_sid, status);
CREATE INDEX IF NOT EXISTS proposals_from ON proposals (from_sid, at);
CREATE INDEX IF NOT EXISTS weddings_couple ON weddings (couple, status);
CREATE INDEX IF NOT EXISTS marriage_effects_sid ON marriage_effects (sid, status, due);
CREATE INDEX IF NOT EXISTS news_at ON news (at);
CREATE INDEX IF NOT EXISTS friend_requests_to ON friend_requests (to_sid, status);
CREATE INDEX IF NOT EXISTS friend_requests_from ON friend_requests (from_sid, at);
CREATE INDEX IF NOT EXISTS friend_searches_sid ON friend_searches (sid, at);
CREATE INDEX IF NOT EXISTS joint_ledger_couple ON joint_ledger (couple, id);
CREATE INDEX IF NOT EXISTS joint_ledger_held ON joint_ledger (sid, status);
CREATE INDEX IF NOT EXISTS couple_requests_couple ON couple_requests (couple, status);
CREATE INDEX IF NOT EXISTS couple_debts_people ON couple_debts (lender, borrower);
CREATE INDEX IF NOT EXISTS couple_moments_couple ON couple_moments (couple, id);
"""

# No foreign keys (receipts.sid, archive.sid -> sessions.sid in SQLite): the migration's live
# pre-copy reads tables at different moments, so a child row may land before its session. The
# game deletes children before the save (Store.delete, prune, prune_guests) on both backends.

# The SQLite triggers of game/admin_stats.py, same names, same effect.
TRIGGER_DDL = f"""
CREATE OR REPLACE FUNCTION mnl_stat_session_born() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_births (sid, day) VALUES (NEW.sid, {VN_DAY}) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_session_active() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_active (day, sid) VALUES ({VN_DAY}, NEW.sid) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_session_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM stat_births WHERE sid = OLD.sid;
  DELETE FROM stat_active WHERE sid = OLD.sid;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_play_cmd() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  _at double precision := extract(epoch FROM statement_timestamp());
  _vn timestamp := (statement_timestamp() AT TIME ZONE 'UTC') + interval '7 hours';
BEGIN
  INSERT INTO stat_play AS p (day, sid, secs, sessions, cmds, first_at, last_at, hours, sess_at, lens)
  VALUES (to_char(_vn, 'YYYY-MM-DD'), NEW.sid, {PLAY_IDLE_TAIL}, 1, 1, _at, _at, 1 << extract(hour FROM _vn)::int, _at, '')
  ON CONFLICT (day, sid) DO UPDATE SET
    secs = p.secs + CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN GREATEST(round(_at - p.last_at), 0)::bigint ELSE {PLAY_IDLE_TAIL} END,
    sessions = p.sessions + CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN 0 ELSE 1 END,
    cmds = p.cmds + 1,
    last_at = GREATEST(p.last_at, _at),
    hours = p.hours | EXCLUDED.hours,
    sess_at = CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN p.sess_at ELSE _at END,
    lens = CASE WHEN _at - p.last_at <= {PLAY_GAP} THEN p.lens
                ELSE p.lens || (round(p.last_at - p.sess_at)::bigint + {PLAY_IDLE_TAIL})::text || ',' END;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_play_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM stat_play WHERE sid = OLD.sid;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_fb_seen() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO stat_fb_ack (id, at) VALUES (NEW.id, NEW.updated_at) ON CONFLICT DO NOTHING;
  RETURN NULL;
END $$;
CREATE OR REPLACE FUNCTION mnl_stat_fb_gone() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM stat_fb_ack WHERE id = OLD.id;
  RETURN NULL;
END $$;
CREATE OR REPLACE TRIGGER stat_session_born AFTER INSERT ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_born();
CREATE OR REPLACE TRIGGER stat_session_active AFTER UPDATE OF updated_at ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_active();
CREATE OR REPLACE TRIGGER stat_session_gone AFTER DELETE ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_session_gone();
CREATE OR REPLACE TRIGGER stat_play_cmd AFTER INSERT ON receipts FOR EACH ROW EXECUTE FUNCTION mnl_stat_play_cmd();
CREATE OR REPLACE TRIGGER stat_play_gone AFTER DELETE ON sessions FOR EACH ROW EXECUTE FUNCTION mnl_stat_play_gone();
CREATE OR REPLACE TRIGGER stat_fb_seen AFTER UPDATE OF status ON player_feedback FOR EACH ROW
  WHEN (OLD.status = 'new' AND NEW.status <> 'new') EXECUTE FUNCTION mnl_stat_fb_seen();
CREATE OR REPLACE TRIGGER stat_fb_gone AFTER DELETE ON player_feedback FOR EACH ROW EXECUTE FUNCTION mnl_stat_fb_gone();
"""

# Only changed when different (ALTER TABLE takes an exclusive lock on the table).
TUNING_DDL = """
DO $$
DECLARE want text;
BEGIN
  BEGIN
    IF (SELECT attcompression FROM pg_attribute WHERE attrelid = 'sessions'::regclass AND attname = 'state') IS DISTINCT FROM 'l' THEN
      ALTER TABLE sessions ALTER COLUMN state SET COMPRESSION lz4;
    END IF;
    IF (SELECT attcompression FROM pg_attribute WHERE attrelid = 'archive'::regclass AND attname = 'row') IS DISTINCT FROM 'l' THEN
      ALTER TABLE archive ALTER COLUMN row SET COMPRESSION lz4;
    END IF;
  EXCEPTION WHEN feature_not_supported OR invalid_parameter_value THEN
    RAISE NOTICE 'lz4 is not available on this server: TOAST keeps pglz';
  END;
  -- Every command rewrites a whole save (100 KB - 1.3 MB): vacuum the hot table and its TOAST early.
  want := 'autovacuum_vacuum_scale_factor=0.02';
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE oid = 'sessions'::regclass AND want = ANY (coalesce(reloptions, '{}'))) THEN
    ALTER TABLE sessions SET (autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.05,
                              toast.autovacuum_vacuum_scale_factor = 0.02);
  END IF;
END $$;
"""

STAGES = (("tables", TABLES_DDL), ("indexes", INDEX_DDL), ("triggers", TRIGGER_DDL), ("tuning", TUNING_DDL))

# (table, trigger) of TRIGGER_DDL. A copy/sync can run `ALTER TABLE t DISABLE TRIGGER USER` on these
# tables (as the table owner, no superuser needed) and ENABLE it again afterwards.
TRIGGERS = [('sessions', 'stat_session_born'), ('sessions', 'stat_session_active'), ('sessions', 'stat_session_gone'),
            ('player_feedback', 'stat_fb_seen'), ('player_feedback', 'stat_fb_gone'),
            ('receipts', 'stat_play_cmd'), ('sessions', 'stat_play_gone')]


def _cols(*spec):
    """('name type', ...) -> [(name, type), ...] in table order."""
    return [tuple(s.split(' ', 1)) for s in spec]


TXT, INT, REAL = 'text', 'bigint', 'double precision'

# One entry per table. "columns": [(name, PostgreSQL type)] in order (same names and order as
# SQLite). "key": the primary key, or the unique key rows are matched by. "unique": other UNIQUE
# keys. "identity": the AUTOINCREMENT column (see reset_sequences). "source": "main" (GAME_DB),
# "limits" (<db>-limits.sqlite3) or None (PostgreSQL only). "sqlite_table": its SQLite name.
TABLES = [
    dict(name='sessions', source='main', sqlite_table='sessions',
         columns=_cols('sid text', 'csrf text', 'revision bigint', 'state text', 'updated_at text'),
         key=('sid',), unique=[], identity=None,
         sync=dict(mode='revision', column='revision', hint='updated_at',
                   note='revision is bumped by every write of state (commands, AI rewording, save migration on '
                        'read); updated_at is not touched by the migration on read, so diff (sid, revision).')),
    dict(name='receipts', source='main', sqlite_table='receipts',
         columns=_cols('sid text', 'request_id text', 'request_hash text', 'result text', 'created_at text'),
         key=('sid', 'request_id'), unique=[], identity=None,
         sync=dict(mode='insert_only', column='created_at', note='never updated; pruned after ~2 days')),
    dict(name='accounts', source='main', sqlite_table='accounts',
         columns=_cols('uid bigint', 'username text', 'display text', 'pw text', 'sid text', 'created_at text', 'updated_at text'),
         key=('uid',), unique=[('username',), ('sid',)], identity='uid',
         sync=dict(mode='updated', column='updated_at', note='password changes set updated_at; small table')),
    dict(name='logins', source='main', sqlite_table='logins',
         columns=_cols('token text', 'sid text', 'csrf text', 'created_at text', 'seen_at text'),
         key=('token',), unique=[], identity=None,
         sync=dict(mode='full', note='seen_at is refreshed hourly; rows are deleted on logout/password change')),
    dict(name='player_feedback', source='main', sqlite_table='player_feedback',
         columns=_cols('id bigint', 'sid text', 'account text', 'kind text', 'text text', 'context text', 'status text',
                       'reply text', 'created_at double precision', 'updated_at double precision', 'replied_at double precision'),
         key=('id',), unique=[], identity='id',
         sync=dict(mode='updated', column='updated_at', note='every UPDATE sets updated_at (unix seconds, REAL)')),
    dict(name='archive', source='main', sqlite_table='archive',
         columns=_cols('sid text', 'career text', 'kind text', 'seq bigint', 'day bigint', 'row text', 'created_at double precision'),
         key=('sid', 'career', 'kind', 'seq'), unique=[], identity=None,
         sync=dict(mode='insert_only', column='created_at',
                   note='no SQLite PRIMARY KEY (rowid table); unique index archive_rows is the key. A (sid,career,kind) '
                        'history can be erased and restarted at seq 0, so upsert by key (DO UPDATE).')),
    dict(name='profiles', source='main', sqlite_table='profiles',
         columns=_cols('pid text', 'sid text', 'name text', 'name_key text', 'bio text', 'avatar text', 'visible bigint',
                       'shop text', 'served bigint', 'week_key text', 'week_base bigint', 'reports bigint', 'hidden bigint',
                       'created double precision', 'updated double precision', 'seen double precision'),
         key=('pid',), unique=[('sid',), ('name_key',)], identity=None,
         sync=dict(mode='full', note='name/reports/hidden change without touching updated/seen')),
    dict(name='visits', source='main', sqlite_table='visits',
         columns=_cols('from_pid text', 'to_pid text', 'day text', 'at double precision'),
         key=('from_pid', 'to_pid', 'day'), unique=[], identity=None,
         sync=dict(mode='insert_only', column='at', note='INSERT OR IGNORE only; pruned after 30 days')),
    dict(name='previews', source='main', sqlite_table='previews',
         columns=_cols('id bigint', 'from_pid text', 'to_pid text', 'career text', 'day text', 'stars bigint', 'text text',
                       'reply text', 'reply_at double precision', 'at double precision', 'reports bigint', 'hidden bigint'),
         key=('id',), unique=[('from_pid', 'to_pid', 'day')], identity='id', sync=dict(mode='full')),
    dict(name='gifts', source='main', sqlite_table='gifts',
         columns=_cols('id bigint', 'from_pid text', 'to_pid text', 'sticker text', 'coins bigint', 'note text', 'day text',
                       'at double precision', 'claimed bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full', note='claimed flips 0->1')),
    dict(name='market', source='main', sqlite_table='market',
         columns=_cols('id bigint', 'seller text', 'career text', 'item text', 'qty bigint', 'price bigint', 'life_left bigint',
                       'unit_cost bigint', 'listed_day bigint', 'status text', 'buyer text', 'at double precision',
                       'sold_at double precision', 'settled bigint', 'reports bigint', 'hidden bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='board', source='main', sqlite_table='board',
         columns=_cols('id bigint', 'pid text', 'career text', 'kind text', 'text text', 'at double precision',
                       'reports bigint', 'hidden bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='comments', source='main', sqlite_table='comments',
         columns=_cols('id bigint', 'post bigint', 'pid text', 'text text', 'at double precision', 'reports bigint', 'hidden bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='reactions', source='main', sqlite_table='reactions',
         columns=_cols('post bigint', 'pid text', 'emoji text'),
         key=('post', 'pid', 'emoji'), unique=[], identity=None, sync=dict(mode='full', note='toggled: insert/delete')),
    dict(name='follows', source='main', sqlite_table='follows',
         columns=_cols('pid text', 'target text', 'at double precision'),
         key=('pid', 'target'), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='blocks', source='main', sqlite_table='blocks',
         columns=_cols('pid text', 'target text', 'at double precision'),
         key=('pid', 'target'), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='reports', source='main', sqlite_table='reports',
         columns=_cols('reporter text', 'kind text', 'target text', 'reason text', 'at double precision'),
         key=('reporter', 'kind', 'target'), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='inbox', source='main', sqlite_table='inbox',
         columns=_cols('id bigint', 'pid text', 'kind text', 'text text', 'ref text', 'at double precision', 'read bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full', note='read flips 0->1; pruned after 60 days')),
    dict(name='push_subs', source='main', sqlite_table='push_subs',
         columns=_cols('endpoint text', 'sid text', 'created double precision', 'last_ok double precision', 'fails bigint', 'prefs text'),
         key=('endpoint',), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='push_queue', source='main', sqlite_table='push_queue',
         columns=_cols('id bigint', 'sid text', 'kind text', 'body text', 'url text', 'at double precision', 'sent bigint', 'shown bigint'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='push_daily', source='main', sqlite_table='push_daily',
         columns=_cols('sid text', 'day text'),
         key=('sid',), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='stat_births', source='main', sqlite_table='stat_births',
         columns=_cols('sid text', 'day text'),
         key=('sid',), unique=[], identity=None,
         sync=dict(mode='insert_only', column='day', note='written by trigger on INSERT INTO sessions; deleted with the save')),
    dict(name='stat_active', source='main', sqlite_table='stat_active',
         columns=_cols('day text', 'sid text'),
         key=('day', 'sid'), unique=[], identity=None,
         sync=dict(mode='insert_only', column='day', note='SQLite WITHOUT ROWID; one row per save per active day; kept 120 days')),
    # Derived from new receipts by a trigger, not from a copy: pg_migrate leaves it alone (source None).
    dict(name='stat_play', source=None, sqlite_table='stat_play',
         columns=_cols('day text', 'sid text', 'secs bigint', 'sessions bigint', 'cmds bigint', 'first_at double precision',
                       'last_at double precision', 'hours bigint', 'sess_at double precision', 'lens text'),
         key=('day', 'sid'), unique=[], identity=None,
         sync=dict(mode='updated', column='last_at', note='one row per save per Vietnam day it sent a command; kept 400 days')),
    dict(name='stat_play_est', source=None, sqlite_table='stat_play_est',
         columns=_cols('day text', 'saves bigint', 'capped bigint', 'at double precision'),
         key=('day',), unique=[], identity=None, sync=dict(mode='full', note='days seeded by admin_stats.backfill_play')),
    dict(name='stat_fb_ack', source='main', sqlite_table='stat_fb_ack',
         columns=_cols('id bigint', 'at double precision'),
         key=('id',), unique=[], identity=None, sync=dict(mode='full', note='id = player_feedback.id (not an identity)')),
    dict(name='hits', source='limits', sqlite_table='hits',
         columns=_cols('k text', 'at double precision'),
         key=None, unique=[], identity=None,
         sync=dict(mode='full', note='rate-limit windows (<= 24 h, no key). Copy once at cut-over; losing it only '
                                     'resets the sign-in/AI/new-save/feedback windows.')),
    # ---- Bảng xếp hạng (game/leaderboard.py): derived from the saves; a new server rebuilds it
    # (backfill) when leaderboard_meta has no 'backfill' row, so copying it is an optimisation.
    dict(name='leaderboard', source='main', sqlite_table='leaderboard',
         columns=_cols('sid text', 'board text', 'score bigint', 'k1 bigint', 'k2 bigint', 'level bigint', 'days bigint',
                       'served bigint', 'stars bigint', 'mastered bigint', 'since double precision', 'updated double precision'),
         key=('sid', 'board'), unique=[], identity=None,
         sync=dict(mode='updated', column='updated', note='every upsert that changes a row sets updated; rows of deleted saves are deleted')),
    dict(name='leaderboard_players', source='main', sqlite_table='leaderboard_players',
         columns=_cols('sid text', 'name text', 'show bigint', 'updated double precision'),
         key=('sid',), unique=[], identity=None, sync=dict(mode='updated', column='updated')),
    dict(name='leaderboard_meta', source='main', sqlite_table='leaderboard_meta',
         columns=_cols('k text', 'v text'), key=('k',), unique=[], identity=None, sync=dict(mode='full')),
    # ---- Hôn nhân, bạn bè, vợ chồng (game/marriage.py SCHEMA): small tables, rows change in place.
    dict(name='marriage_people', source='main', sqlite_table='marriage_people',
         columns=_cols('sid text', 'code text', 'accept bigint', 'life_day bigint', 'pool text', 'remarry_after double precision',
                       'notice text', 'notice_at double precision', 'created double precision', 'updated double precision'),
         key=('sid',), unique=[('code',)], identity=None, sync=dict(mode='full', note='life_day/pool/notice change without updated')),
    dict(name='marriage_rings', source='main', sqlite_table='marriage_rings',
         columns=_cols('id text', 'sid text', 'tier text', 'price bigint', 'status text', 'at double precision', 'metal text', 'stone text'),
         key=('id',), unique=[], identity=None, sync=dict(mode='full', note='metal/stone were added by ALTER TABLE in older files')),
    dict(name='proposals', source='main', sqlite_table='proposals',
         columns=_cols('id bigint', 'from_sid text', 'to_sid text', 'ring text', 'message text', 'announce bigint', 'status text',
                       'at double precision', 'decided double precision'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='couples', source='main', sqlite_table='couples',
         columns=_cols('id bigint', 'a text', 'b text', 'ring text', 'status text', 'since double precision', 'married_at double precision',
                       'ended double precision', 'ended_by text'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='marriage_bonds', source='main', sqlite_table='marriage_bonds',
         columns=_cols('sid text', 'couple bigint'), key=('sid',), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='weddings', source='main', sqlite_table='weddings',
         columns=_cols('id bigint', 'couple bigint', 'status text', 'version bigint', 'planner text', 'plan text', 'quote text',
                       'split_a bigint', 'announce_a bigint', 'announce_b bigint', 'days bigint', 'target_a bigint', 'target_b bigint',
                       'due_at double precision', 'deposit_a bigint', 'deposit_b bigint', 'result text', 'seen_a bigint', 'seen_b bigint',
                       'created double precision', 'confirmed_at double precision', 'done_at double precision'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='marriage_effects', source='main', sqlite_table='marriage_effects',
         columns=_cols('id text', 'sid text', 'kind text', 'amount bigint', 'label text', 'data text', 'status text',
                       'due double precision', 'at double precision', 'applied_at double precision'),
         key=('id',), unique=[], identity=None, sync=dict(mode='full', note='status flips pending -> applied')),
    dict(name='marriage_blocks', source='main', sqlite_table='marriage_blocks',
         columns=_cols('sid text', 'target text', 'at double precision'), key=('sid', 'target'), unique=[], identity=None,
         sync=dict(mode='full')),
    dict(name='news', source='main', sqlite_table='news',
         columns=_cols('id bigint', 'kind text', 'ref text', 'text text', 'a text', 'b text', 'at double precision'),
         key=('id',), unique=[('ref',)], identity='id', sync=dict(mode='full')),
    dict(name='friend_prefs', source='main', sqlite_table='friend_prefs',
         columns=_cols('sid text', 'findable bigint'), key=('sid',), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='friend_requests', source='main', sqlite_table='friend_requests',
         columns=_cols('id bigint', 'from_sid text', 'to_sid text', 'status text', 'at double precision', 'decided double precision'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='friends', source='main', sqlite_table='friends',
         columns=_cols('sid text', 'friend text', 'since double precision'), key=('sid', 'friend'), unique=[], identity=None,
         sync=dict(mode='full')),
    dict(name='friend_searches', source='main', sqlite_table='friend_searches',
         columns=_cols('sid text', 'at double precision'), key=None, unique=[], identity=None,
         sync=dict(mode='full', note='search rate-limit log (<= 1 day matters, no key), like hits')),
    dict(name='joint_funds', source='main', sqlite_table='joint_funds',
         columns=_cols('couple bigint', 'balance bigint', 'updated double precision'), key=('couple',), unique=[], identity=None,
         sync=dict(mode='updated', column='updated')),
    dict(name='joint_ledger', source='main', sqlite_table='joint_ledger',
         columns=_cols('id bigint', 'couple bigint', 'sid text', 'kind text', 'amount bigint', 'balance bigint', 'label text',
                       'ref text', 'status text', 'at double precision'),
         key=('id',), unique=[('ref',)], identity='id', sync=dict(mode='full', note='status flips held -> done/void')),
    dict(name='couple_requests', source='main', sqlite_table='couple_requests',
         columns=_cols('id bigint', 'couple bigint', 'from_sid text', 'to_sid text', 'kind text', 'amount bigint', 'note text',
                       'loan bigint', 'debt bigint', 'status text', 'at double precision', 'decided double precision'),
         key=('id',), unique=[], identity='id', sync=dict(mode='full')),
    dict(name='couple_debts', source='main', sqlite_table='couple_debts',
         columns=_cols('id bigint', 'couple bigint', 'lender text', 'borrower text', 'amount bigint', 'repaid bigint', 'status text',
                       'note text', 'ref text', 'at double precision', 'updated double precision'),
         key=('id',), unique=[('ref',)], identity='id', sync=dict(mode='updated', column='updated')),
    dict(name='couple_moments', source='main', sqlite_table='couple_moments',
         columns=_cols('id bigint', 'couple bigint', 'sid text', 'kind text', 'text text', 'key text', 'at double precision', 'seen bigint'),
         key=('id',), unique=[('key',)], identity='id', sync=dict(mode='full', note='seen flips 0 -> 1')),
    dict(name='couple_stats', source='main', sqlite_table='couple_stats',
         columns=_cols('couple bigint', 'happy bigint', 'streak bigint', 'best bigint', 'last_day bigint', 'today bigint'),
         key=('couple',), unique=[], identity=None, sync=dict(mode='full')),
    dict(name='mnl_meta', source=None, sqlite_table=None,
         columns=_cols('key text', 'value text'),
         key=('key',), unique=[], identity=None, sync=None),
]

TABLE = {t['name']: t for t in TABLES}


def _run(conn, script: str) -> None:
    """Run a DDL script on a psycopg connection (or a game.db.PgConnection)."""
    raw = getattr(conn, 'raw', conn)
    raw.execute(script)


def installed_version(conn) -> int:
    raw = getattr(conn, 'raw', conn)
    if raw.execute("SELECT to_regclass('mnl_meta')").fetchone()[0] is None:
        return 0
    row = raw.execute("SELECT value FROM mnl_meta WHERE key = 'schema_version'").fetchone()
    return int(row[0]) if row else 0


def missing_tables(conn) -> list:
    """Tables of TABLES that do not exist in the current schema (one catalog query)."""
    raw = getattr(conn, 'raw', conn)
    names = [t['name'] for t in TABLES]
    have = {r[0] for r in raw.execute("SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
                                      "WHERE n.nspname = current_schema() AND c.relkind IN ('r', 'p') AND c.relname = ANY(%s)", (names,))}
    return [n for n in names if n not in have]


def ensure(conn, stages=None, force: bool = False) -> bool:
    """Create what is missing, idempotently, in the connection's current schema (search_path).
    `stages`: a subset of ("tables", "indexes", "triggers", "tuning").
    Without `force`, a database already at SCHEMA_VERSION is left alone (no DDL, no locks).
    Returns True when DDL ran. Runs in one transaction (needs an autocommit connection)."""
    raw = getattr(conn, 'raw', conn)
    everything = stages is None
    if everything and not force and installed_version(raw) >= SCHEMA_VERSION and not missing_tables(raw):
        return False
    with raw.transaction():
        # one-off DDL (an index on a big table, a slow disk): not bound by the request timeout
        raw.execute("SELECT set_config('statement_timeout', '600s', true)")
        for name, ddl in STAGES:
            if everything or name in stages:
                raw.execute(ddl)
        if everything:
            raw.execute("INSERT INTO mnl_meta (key, value) VALUES ('schema_version', %s) "
                        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value", (str(SCHEMA_VERSION),))
    return True


def reset_sequences(conn, floors: dict | None = None) -> dict:
    """After copying rows with their ids: make every identity continue after
    max(id) of its table, or after floors[table] when larger (pass SQLite's
    sqlite_sequence, {name: seq}, so ids of deleted rows are never reused, as with
    AUTOINCREMENT). Returns {table: next id}. Safe to run again at any time."""
    raw = getattr(conn, 'raw', conn)
    floors = floors or {}
    out = {}
    for t in TABLES:
        col = t['identity']
        if not col:
            continue
        top = raw.execute(f'SELECT COALESCE(MAX({col}), 0) FROM {t["name"]}').fetchone()[0]
        top = max(int(top), int(floors.get(t['name']) or 0))
        seq = raw.execute('SELECT pg_get_serial_sequence(%s, %s)', (t['name'], col)).fetchone()[0]
        if top > 0:
            raw.execute('SELECT setval(%s, %s, true)', (seq, top))
        else:
            raw.execute('SELECT setval(%s, 1, false)', (seq,))
        out[t['name']] = top + 1
    return out
