"""A small step engine for paperwork careers (accounting, tax, payroll, group).

A task stores `proc`: a list of fixed steps generated by make_task (answer keys
live under private `_key` fields), plus `proc_state` with the player's progress.
Steps are solved in order; a wrong answer counts a mistake and shows a hint but
never reveals the key. Public projection hides every `_key` and every `explain`
until that step is solved.

Step kinds and answer formats:
  choice  → option id                      multi  → list of option ids (any order)
  number  → int                            order  → list of item ids in order
  match   → {left_id: right_id}            fields → {field_id: int | option id}
  entry   → [{debit, credit, amount}]      (journal lines, any order)
"""
from __future__ import annotations
import copy
from .jsoncopy import tree_copy

KINDS = ('choice', 'multi', 'number', 'order', 'match', 'fields', 'entry')


def step(id: str, kind: str, title: str, prompt: str, key, **extra) -> dict:
    assert kind in KINDS
    return dict(id=id, kind=kind, title=title, prompt=prompt, _key=key, **extra)


def initial_state() -> dict:
    return dict(at=0, solved=[], attempts={}, answers={})


# Other orders that are just as right in real life, keyed by the step's key. The steps stored in a
# save never change (validate() compares them with the original), so alternatives live here.
ALT_ORDERS = {
    # Trung thu: many schools feast first and parade after, others parade first.
    ('gather', 'parade', 'feast', 'show', 'clean'): (('gather', 'feast', 'parade', 'show', 'clean'),),
}


def orders(key) -> list:
    """Every accepted order for an order step: its key plus the listed alternatives."""
    return [list(key)] + [list(x) for x in ALT_ORDERS.get(tuple(key), ())]


def _norm_entry(lines) -> list | None:
    if not isinstance(lines, list) or not 1 <= len(lines) <= 8:
        return None
    rows = []
    for x in lines:
        if not isinstance(x, dict) or not isinstance(x.get('debit'), str) or not isinstance(x.get('credit'), str) or type(x.get('amount')) is not int:
            return None
        rows.append((x['debit'], x['credit'], x['amount']))
    return sorted(rows)


def check(st: dict, answer) -> bool:
    k = st['_key']
    kind = st['kind']
    if kind == 'choice':
        return isinstance(answer, str) and answer == k
    if kind == 'multi':
        return isinstance(answer, list) and all(isinstance(x, str) for x in answer) and len(set(answer)) == len(answer) and sorted(answer) == sorted(k)
    if kind == 'number':
        return type(answer) is int and answer == k
    if kind == 'order':
        return isinstance(answer, list) and answer in orders(k)
    if kind == 'match':
        return isinstance(answer, dict) and answer == k
    if kind == 'fields':
        return isinstance(answer, dict) and set(answer) == set(k) and all(type(answer[f]) is type(k[f]) and answer[f] == k[f] for f in k)
    if kind == 'entry':
        rows = _norm_entry(answer)
        if rows is None:
            return False
        key = sorted(tuple(x) for x in k)
        # The same voucher can be split into debit/credit pairs differently:
        # compare what each account receives on each side.
        return rows == key or _totals(rows) == _totals(key)
    return False


def _totals(rows) -> dict:
    out = {}
    for debit, credit, amount in rows:
        out[('D', debit)] = out.get(('D', debit), 0) + amount
        out[('C', credit)] = out.get(('C', credit), 0) + amount
    return out


def shape_ok(st: dict, answer) -> bool:
    """Reject malformed answers with a clear error instead of counting a mistake."""
    kind = st['kind']
    ids = {o['id'] for o in st.get('options', [])}
    # Type checks come first: unhashable values must not reach `in set`.
    if kind == 'choice':
        return isinstance(answer, str) and answer in ids
    if kind == 'multi':
        return isinstance(answer, list) and 1 <= len(answer) <= len(ids) and all(isinstance(x, str) and x in ids for x in answer)
    if kind == 'number':
        return type(answer) is int and -10**9 <= answer <= 10**9
    if kind == 'order':
        items = {o['id'] for o in st['items']}
        return isinstance(answer, list) and len(answer) == len(items) and all(isinstance(x, str) for x in answer) and set(answer) == items
    if kind == 'match':
        left = {o['id'] for o in st['left']}
        right = {o['id'] for o in st['right']}
        return isinstance(answer, dict) and set(answer) == left and all(isinstance(v, str) and v in right for v in answer.values())
    if kind == 'fields':
        fields = {f['id']: f for f in st['fields']}
        if not isinstance(answer, dict) or set(answer) != set(fields):
            return False
        for fid, v in answer.items():
            f = fields[fid]
            if f.get('options'):
                if not isinstance(v, str) or v not in [o['id'] for o in f['options']]:
                    return False
            elif type(v) is not int or not -10**9 <= v <= 10**9:
                return False
        return True
    if kind == 'entry':
        accounts = {a['id'] for a in st['accounts']}
        rows = _norm_entry(answer)
        return rows is not None and all(d in accounts and c in accounts and d != c and 0 < a <= 10**9 for d, c, a in rows)
    return False


def submit(t: dict, step_id, answer) -> tuple[bool, str]:
    """Returns (correct, message). Raises GameError on malformed/out-of-order input."""
    from .engine import need
    proc = t['proc']
    ps = t['proc_state']
    need(ps['at'] < len(proc), 'Hồ sơ đã hoàn tất mọi bước.')
    st = proc[ps['at']]
    need(step_id == st['id'], 'Làm theo thứ tự các bước của quy trình nhé.')
    need(shape_ok(st, answer), 'Câu trả lời chưa đúng định dạng của bước này.')
    ps['attempts'][st['id']] = ps['attempts'].get(st['id'], 0) + 1
    if check(st, answer):
        ps['solved'].append(st['id'])
        ps['answers'][st['id']] = copy.deepcopy(answer)
        ps['at'] += 1
        return True, st.get('explain', 'Chính xác.')
    t['mistakes'] += 1
    hints = st.get('hints') or [st.get('hint', 'Đọc lại chứng từ liên quan rồi thử lại.')]
    hint = hints[min(len(hints), ps['attempts'][st['id']]) - 1]
    if st['kind'] == 'order':  # say where it goes wrong, not only the general rule
        return False, f'{order_where(st, answer)} {hint}'
    if st['kind'] == 'multi':
        # Feedback #124: the n-th hint came on the n-th try whatever was wrong ("Pháo không an toàn" for a player
        # who never ticked the fireworks). Say what is off, then the hint about that: a wrong tick first, then a missing one.
        return False, f'{multi_where(st, answer)} {multi_hint(st, answer) or hint}'
    if st['kind'] == 'match':
        return False, f'{match_where(st, answer)} {hint}'
    return False, hint


def multi_where(st: dict, answer: list) -> str:
    """How many of the needed ticks a multiple choice got, and how many extra (never which)."""
    got, need = set(answer), set(st['_key'])
    more = len(got - need)
    return f'Đúng {len(got & need)}/{len(need)} mục cần chọn' + (f', thừa {more} mục' if more else '') + '.'


def multi_hint(st: dict, answer: list) -> str | None:
    """The step's own word about the first wrong tick (it has to go), else about the first missing one.
    `_why` is private ({option id: hint}, optional): steps without it fall back to their hints."""
    why = st.get('_why') or {}
    picked = set(answer)
    wrong = [o['id'] for o in st.get('options', []) if o['id'] in picked and o['id'] not in st['_key']]
    missing = [x for x in st['_key'] if x not in picked]
    return next((why[x] for x in wrong + missing if isinstance(why.get(x), str)), None)


def match_where(st: dict, answer: dict) -> str:
    k = st['_key']
    return f'Ghép đúng {sum(1 for a, b in k.items() if answer.get(a) == b)}/{len(k)} dòng.'


def order_where(st: dict, answer: list) -> str:
    """Where a wrong order goes off (never the right order): how many places match, the first one to look at."""
    good, first = max(((sum(a == b for a, b in zip(answer, key)), next((i for i, (a, b) in enumerate(zip(answer, key)) if a != b), 0))
                       for key in orders(st['_key'])), key=lambda x: x[0])
    return f'Đúng {good}/{len(answer)} vị trí, xem lại từ ô số {first + 1}.'


def done(t: dict) -> bool:
    return t['proc_state']['at'] >= len(t['proc'])


def public(t: dict) -> tuple[list, dict]:
    ps = t['proc_state']
    rows = []
    for i, st in enumerate(t['proc']):
        v = {k: tree_copy(val) for k, val in st.items() if not k.startswith('_')}
        solved = st['id'] in ps['solved']
        if not solved:
            v.pop('explain', None)
            # Hints unlock one per wrong attempt on the current step.
            if isinstance(v.get('hints'), list):
                v['hints'] = v['hints'][:ps['attempts'].get(st['id'], 0)] if i == ps['at'] else []
        v['state'] = 'solved' if solved else 'current' if i == ps['at'] else 'locked'
        if solved:
            v['answer'] = tree_copy(ps['answers'].get(st['id']))
        rows.append(v)
    return rows, dict(at=ps['at'], solved=list(ps['solved']), attempts=dict(ps['attempts']), total=len(t['proc']))


def validate(t: dict, original: dict) -> None:
    from .engine import need, integer
    need(t.get('proc') == original.get('proc'), 'Quy trình gốc của hồ sơ đã bị thay đổi.')
    ps = t.get('proc_state')
    need(isinstance(ps, dict) and set(initial_state()) <= set(ps), 'Tiến độ quy trình thiếu dữ liệu.')
    integer(ps['at'], 0, len(t['proc']))
    ids = [st['id'] for st in t['proc']]
    need(ps['solved'] == ids[:ps['at']], 'Tiến độ quy trình sai thứ tự.')
    need(isinstance(ps['attempts'], dict) and all(k in ids for k in ps['attempts']), 'Lượt thử quy trình sai.')
    for v in ps['attempts'].values():
        integer(v, 0, 10**6)
    need(isinstance(ps['answers'], dict) and set(ps['answers']) == set(ps['solved']), 'Đáp án đã lưu sai.')
    for sid, ans in ps['answers'].items():
        st = t['proc'][ids.index(sid)]
        need(check(st, ans), 'Đáp án đã lưu không khớp quy trình.')
