"""Review aspects: the many small things people notice (data only; logic in review_aspects.py).

Each aspect is one angle a customer, parent, student or coworker can praise or complain about:
the coffee too bland, the paper straw going soggy, the restroom, the teacher's patience, the new
colleague who wears flip-flops to the office. Lines are clauses: lower-case start, no final full
stop, so they fit "Được cái {x}." or "{pos}, mà {neg}." Tokens:

* {nv}    the person who served ("bạn nhân viên" / "anh nhân viên" / "chị nhân viên"; a rude
          reviewer says "thằng nhỏ đứng quầy" / "con nhỏ đứng quầy");
* {nho}   office jab ("con nhỏ" / "thằng nhỏ" from a harsh voice, "em ấy" / "cậu ấy" / "bạn ấy"
          otherwise; neutral wording when the player's gender is unknown);
* {owner} how the reviewer calls the player ("anh chủ" / "chị chủ" / "chủ quán");
* {item}  what was served.

Teacher lines are keyed by voice: 'p' parent, 's' student, 'o' colleague. Other lines are a list,
or a dict keyed by career id or family with '*' for everyone. A key '@signal' holds lines that are
only true when the aspect is grounded in that signal ('@rain': "trời mưa mà không trải thảm").

Grounding: `sig_neg` / `sig_pos` name signals from real state (review_aspects.signals). An aspect
with `sig_neg` complains only when one of them is true, unless it is `subjective` (taste, attitude,
music: a matter of opinion, seeded and answerable). Safety: attitude and clothing jabs are fine;
nothing about bodies, looks, age, region, religion, nothing sexual, no real brands or people.
"""
from __future__ import annotations

FAMILY = {
    'milk_tea': 'food', 'cafe_bakery': 'food', 'restaurant': 'food', 'tra_da': 'food', 'ice_cream': 'food', 'com': 'food',
    'grocery': 'shop', 'clothing': 'shop', 'pet_shop': 'shop', 'florist': 'shop', 'mother_baby': 'shop', 'pharmacy': 'shop',
    'salon': 'service', 'repair': 'service', 'pet_care': 'service', 'homestay': 'service', 'tour_guide': 'service',
    'delivery': 'service', 'farm': 'service', 'nail': 'service',
    'teacher': 'school',
    'customer_care': 'office', 'accounting': 'office', 'corp_accounting': 'office', 'tax_payroll': 'office', 'group_accounting': 'office',
    'hr_admin': 'office', 'secretary': 'office', 'it_helpdesk': 'office',
}
FAMILY_NAME = {'food': 'Ăn uống', 'shop': 'Cửa hàng', 'service': 'Dịch vụ', 'school': 'Lớp học', 'office': 'Văn phòng'}

DRINKS = ('milk_tea', 'cafe_bakery', 'tra_da')
SIT_DOWN = ('milk_tea', 'cafe_bakery', 'restaurant')
PEOPLE_FAMS = ('food', 'shop', 'service')


def A(aid, fams, label, claim, *, topic, neg=(), pos=(), sarc=(), word=('', ''), sig_neg=(), sig_pos=(), only=(), skip=(),
      need=(), subjective=False):
    return aid, dict(id=aid, fams=tuple(fams), label=label, claim=claim, topic=topic, neg=neg, pos=pos, sarc=list(sarc),
                     word=tuple(word), sig_neg=tuple(sig_neg), sig_pos=tuple(sig_pos), only=tuple(only), skip=tuple(skip),
                     need=tuple(need), subjective=bool(subjective))


ASPECTS = dict((
    # ================================================================ FOOD AND DRINK
    A('sweet', ('food',), 'Độ ngọt', 'ngọt quá so với lời dặn', topic='taste', only=('milk_tea', 'cafe_bakery'), subjective=True,
      neg=['ly nước ngọt khé, uống xong khát thêm', 'dặn ít đường mà ngọt như đổ cả hũ', 'ngọt gắt cổ, phải xin thêm đá cho loãng bớt',
           'vị ngọt lấn hết vị trà'],
      pos=['độ ngọt vừa miệng, đúng kiểu ít đường', 'ngọt thanh, uống hết ly không ngán', 'ngọt vừa phải, không bị gắt cổ',
           'dặn ba mươi phần trăm đường là ra đúng ba mươi'],
      sarc=['ngọt dữ thần, uống xong nghe tim đập theo nhịp đường 👏'], word=('Ngọt gắt.', 'Ngọt vừa.'),
      sig_neg=('slip:sugar',), sig_pos=('crit:accuracy:hi',)),
    A('coffee', ('food',), 'Vị cà phê', 'cà phê nhạt', topic='taste', only=('cafe_bakery',), subjective=True,
      neg=['cà phê nhạt quá, uống như nước màu', 'cà phê hơi loãng, không đủ đô cho buổi sáng', 'cà phê đắng mà không thơm, kiểu rang hơi cháy',
           'ly cà phê sữa toàn vị sữa, tìm mãi không thấy cà phê'],
      pos=['cà phê đậm, thơm mùi rang, tỉnh cả người', 'cà phê đậm vừa, hậu ngọt, uống là ghiền', 'cà phê đủ đô mà không gắt',
           'mở nắp ra là thơm lừng mùi cà phê'],
      sarc=['cà phê nhạt tới mức uống xong vẫn buồn ngủ y nguyên, hiệu quả thật 👏', 'ly cà phê rất "nhẹ nhàng", nhẹ tới mức tưởng trà 🙂'],
      word=('Nhạt.', 'Đậm.'), sig_neg=('slip:water', 'slip:weak', 'slip:shots', 'slip:shot', 'slip:beans'), sig_pos=('crit:taste:hi',)),
    A('tea', ('food',), 'Vị trà', 'trà nhạt', topic='taste', only=('milk_tea', 'tra_da'), subjective=True,
      neg={'milk_tea': ['vị trà nhạt, toàn thấy vị sữa', 'trà hơi chát, uống xong khô cả miệng', 'trà có vẻ ủ lâu nên hơi nồng'],
           'tra_da': ['chè hơi nhạt, đá tan cái là như nước lã', 'chè pha hơi chát, uống một hơi thấy khô cổ', 'ấm chè có vẻ pha từ sáng, hơi nồng']},
      pos={'milk_tea': ['trà thơm, hậu ngọt, uống là biết trà ngon', 'vị trà rõ, không bị sữa lấn', 'trà ủ vừa, thơm mà không chát'],
           'tra_da': ['chè đậm, chát nhẹ rồi ngọt hậu, đúng vị trà đá vỉa hè', 'cốc trà đá mát lạnh, thơm mùi chè mới pha', 'chè xanh pha vừa, uống ba cốc chưa đã']},
      word=('Nhạt.', 'Đậm vị.'), sig_neg=('slip:weak_brew', 'crit:tea:lo'), sig_pos=('crit:tea:hi',)),
    A('dish', ('food',), 'Hương vị món', 'món nêm chưa vừa', topic='taste', only=('restaurant', 'cafe_bakery'), subjective=True,
      neg={'restaurant': ['nước dùng hơi nhạt, phải thêm nước mắm mới vừa', 'món hơi mặn, về uống nước cả buổi chiều', 'nước dùng hơi ngọt bột ngọt',
                          'sợi mì hơi nở, gắp lên là đứt'],
           'cafe_bakery': ['bánh hơi khô, ăn phải chiêu nước', 'bánh mì hơi dai, cắn mỏi cả hàm', 'kem bánh ngọt quá, ăn hai miếng là ngán']},
      pos={'restaurant': ['nước dùng ngọt xương, húp cạn tô', 'nêm vừa miệng, không phải thêm gì', 'sợi mì dai vừa, trụng khéo',
                          'tô mì thơm hành phi, ăn xong còn thèm'],
           'cafe_bakery': ['bánh mềm, thơm bơ, ăn còn ấm', 'vỏ bánh giòn tan, ruột xốp', 'kem bánh ngọt vừa, ăn không ngán']},
      word=('Chưa vừa.', 'Ngon.'), sig_neg=('crit:broth:lo', 'crit:taste:lo', 'slip:spice', 'crit:bake:lo'),
      sig_pos=('crit:broth:hi', 'crit:taste:hi', 'crit:bake:hi')),
    A('temp', ('food',), 'Độ nóng lạnh', 'đồ nóng mà nguội', topic='taste', skip=('ice_cream',),
      neg=['đồ uống nóng mà đưa ra đã nguội', 'món bưng ra hơi nguội', 'ly nóng quá, cầm bỏng cả tay'],
      pos=['đồ nóng bưng ra còn bốc khói', 'ly nóng vừa tay, uống liền được', 'đồ lạnh thì lạnh buốt, đồ nóng thì nóng hổi'],
      word=('Nguội.', 'Nóng hổi.'), sig_neg=('slip:temp', 'slip:cool', 'slip:scalded', 'slip:too_warm')),
    A('ice', ('food',), 'Đá', 'đá tan nhanh', topic='drink', only=DRINKS,
      neg=['đá tan nhanh, nửa ly sau toàn nước', 'đá ít quá, uống không đã', 'thùng đá hết nên phải uống nước chè không đá'],
      pos=['đá lạnh buốt, uống giải nhiệt liền', 'đá vừa đủ, tới cuối ly vẫn ra vị', 'đá viên to, lâu tan, uống cả buổi vẫn mát'],
      word=('Đá tan.', 'Mát lạnh.'), sig_neg=('slip:melted', 'slip:ice', 'slip:no_ice', 'no_ice', 'crit:clean:lo')),
    A('portion', ('food',), 'Khẩu phần', 'phần ăn ít', topic='taste', only=SIT_DOWN, subjective=True,
      neg={'restaurant': ['phần ăn hơi ít, ăn xong vẫn đói', 'thịt trong tô đếm được trên đầu ngón tay'],
           'milk_tea': ['topping hơi ít, múc mãi mới thấy trân châu', 'ly size L mà nhìn như size M'],
           'cafe_bakery': ['miếng bánh nhỏ hơn trong hình', 'ly nhỏ mà đá chiếm nửa ly']},
      pos={'restaurant': ['tô đầy đặn, thịt không keo', 'phần ăn no căng, đáng tiền'],
           'milk_tea': ['topping nhiều, ly đầy ắp', 'trân châu nhiều, hút tới cuối vẫn còn'],
           'cafe_bakery': ['miếng bánh to, cắt đều tay', 'ly đầy, ít đá nhiều nước']},
      word=('Ít.', 'Đầy đặn.'), sig_neg=('slip:portion', 'slip:wrong_portion')),
    A('straw', ('food',), 'Ống hút', 'ống hút giấy mềm nhũn', topic='pack', only=('milk_tea', 'cafe_bakery'), subjective=True,
      neg=['ống hút giấy uống được nửa ly là mềm nhũn', 'quên đưa ống hút, tôi phải quay lại xin', 'ống hút hơi nhỏ, hút trân châu mỏi cả má',
           'ống hút giấy có mùi giấy, uống hơi lợ', 'ống hút ngắn, cắm vào ly size L là chìm luôn'],
      pos=['ống hút to vừa, hút trân châu sướng', 'ống hút giấy mà cứng cáp, uống tới cuối vẫn ổn', 'có sẵn ống hút gói riêng, sạch sẽ',
           'hỏi khách lấy ống hút hay không, chu đáo ghê'],
      sarc=['ống hút giấy thân thiện môi trường ghê, thân thiện tới mức tan luôn trong ly 👏', 'ống hút mềm dần theo thời gian, như một bài học về sự vô thường 🙂'],
      word=('Ống hút mềm.', 'Ống hút xịn.')),
    A('lid', ('food',), 'Ly và nắp', 'nắp ly không kín', topic='pack', only=('milk_tea', 'cafe_bakery'),
      neg=['nắp dán không kín, đi xe về rỉ ra ướt cả túi', 'ly mỏng, cầm hơi mạnh là móp', 'nắp ly bật ra, nước đổ một ít',
           'màng dán nhăn nhúm, cắm ống hút mãi không thủng'],
      pos=['nắp dán căng, lắc mạnh cũng không rỉ', 'ly dày dặn, cầm chắc tay', 'nắp kín, mang về tới nhà vẫn nguyên',
           'màng dán phẳng phiu, cắm ống hút một phát ăn ngay'],
      sarc=['nắp dán kiểu "tùy duyên", về tới nhà còn được nửa ly là may 👏'],
      word=('Rỉ nước.', 'Nắp kín.'), sig_neg=('slip:seal', 'slip:cup', 'slip:container', 'sealer_dirty'), sig_pos=('seal_good',)),
    A('napkin', ('food',), 'Muỗng, khăn giấy', 'thiếu khăn giấy', topic='pack', only=('restaurant', 'cafe_bakery', 'tra_da'),
      neg=['không thấy khăn giấy trên bàn, phải đi xin', 'hộp khăn giấy trên bàn hết sạch', 'đưa đồ ăn mà quên muỗng nĩa'],
      pos=['có sẵn khăn giấy, muỗng nĩa gói riêng', 'đưa kèm khăn ướt, chu đáo ghê', 'hộp khăn giấy lúc nào cũng đầy'],
      word=('Hết khăn giấy.', 'Chu đáo.'), sig_neg=('messy', 'crowded'), sig_pos=('crit:packing:hi', 'crit:presentation:hi')),
    A('table', ('food',), 'Bàn ghế', 'bàn còn dính', topic='clean',
      neg=['bàn còn dính nước đường, đặt tay là dính', 'ghế còn vụn bánh của khách trước', 'mặt bàn nhớt nhớt, lau mãi chưa sạch',
           'khách trước đi rồi mà ly cũ còn nguyên trên bàn'],
      pos=['bàn lau sạch bong, ngồi thích', 'khách trước vừa đi là dọn bàn liền', 'bàn ghế gọn gàng, không dính chút nào'],
      sarc=['bàn dính tới mức đặt điện thoại xuống là khỏi sợ rơi 👏'],
      word=('Bàn dính.', 'Bàn sạch.'), sig_neg=('messy', 'dirty_bowls')),
    A('floor', ('food',), 'Sàn nhà', 'sàn trơn', topic='clean', skip=('tra_da',),
      neg={'*': ['sàn hơi trơn, suýt trượt chân', 'dưới gầm bàn còn ly nhựa với giấy ăn', 'sàn loang vệt nước, đi phải nhìn chân'],
           '@rain': ['sàn ướt dấu dép, trời mưa mà không trải thảm', 'trời mưa, lối vào trơn trượt, suýt ngã']},
      pos=['sàn khô ráo, sạch sẽ', 'trời mưa mà có thảm chùi chân ở cửa, sàn vẫn khô', 'sàn lau thơm mùi sả'],
      word=('Sàn trơn.', 'Sàn sạch.'), sig_neg=('messy', 'rain')),
    A('restroom', ('food',), 'Nhà vệ sinh', 'nhà vệ sinh bẩn', topic='clean', only=SIT_DOWN, subjective=True,
      neg=['nhà vệ sinh hơi bí, không có quạt hút', 'nhà vệ sinh hết giấy, xà phòng cũng không có', 'sàn nhà vệ sinh ướt nhẹp',
           'nhà vệ sinh có mùi, chắc lâu chưa dọn', 'nhà vệ sinh khóa cửa hỏng, phải nhờ người đứng canh'],
      pos=['nhà vệ sinh sạch thơm, có cả xà phòng rửa tay', 'nhà vệ sinh khô ráo, sạch hơn cả nhà tôi', 'nhà vệ sinh nhỏ mà sạch, đủ giấy',
           'nhà vệ sinh có gương sáng, có móc treo túi, tinh tế ghê'],
      sarc=['nhà vệ sinh mang phong cách "sinh tồn", vào là phải nín thở 👏'],
      word=('Nhà vệ sinh bí.', 'Nhà vệ sinh sạch.'), sig_neg=('messy',)),
    A('no_restroom', ('food',), 'Nhà vệ sinh', 'không có nhà vệ sinh', topic='clean', only=('tra_da',), subjective=True,
      neg=['quán vỉa hè nên không có nhà vệ sinh, muốn đi phải chạy ra cây xăng', 'ngồi lâu mà không có chỗ đi vệ sinh, hơi bất tiện'],
      pos=['không có nhà vệ sinh nhưng chủ quán chỉ tận chỗ gần nhất'], word=('Không có WC.', '')),
    A('smell', ('food',), 'Mùi trong quán', 'quán ám mùi', topic='clean', skip=('ice_cream',),
      neg=['trong quán hơi ám mùi dầu mỡ, về áo còn mùi', 'gần thùng rác nên thoảng mùi khó chịu', 'mùi nước rửa chén hắc quá'],
      pos={'*': ['vào quán là thấy thơm, dễ chịu'], 'cafe_bakery': ['quán thơm mùi bánh nướng, đói bụng liền', 'vào cửa là thơm mùi cà phê rang'],
           'restaurant': ['thơm mùi nước dùng từ đầu hẻm'], 'milk_tea': ['quán thơm mùi trà với đường nâu'], 'tra_da': ['thoảng mùi chè mới pha, mát cả người']},
      word=('Ám mùi.', 'Thơm.'), sig_neg=('messy', 'dirty_bowls')),
    A('flies', ('food',), 'Ruồi muỗi', 'có ruồi', topic='clean',
      neg=['có vài con ruồi bay quanh bàn', 'ngồi một lúc là muỗi cắn chân', 'ruồi bu quanh xô đá, nhìn hơi ngại'],
      word=('Ruồi.', ''), sig_neg=('messy', 'garden', 'dirty_bowls', 'grimy_cups')),
    A('music', ('food',), 'Nhạc', 'nhạc mở to', topic='ambience', only=SIT_DOWN, subjective=True,
      neg=['nhạc mở to quá, nói chuyện phải hét', 'nhạc xập xình, không hợp ngồi làm việc', 'nhạc lặp đi lặp lại một bài, nghe muốn thuộc'],
      pos=['nhạc nhẹ nhàng, ngồi cả buổi không chán', 'nhạc chill đúng gu, âm lượng vừa', 'nhạc xưa nghe mà thấy thương'],
      word=('Nhạc to.', 'Nhạc hay.')),
    A('air', ('food', 'shop'), 'Máy lạnh, quạt', 'nóng, máy lạnh yếu', topic='ambience', subjective=True,
      neg={'*': ['máy lạnh yếu, ngồi mồ hôi rịn ra', 'quạt thổi thẳng vào mặt, lạnh buốt', 'trong tiệm hơi hầm, đứng lâu thấy bí'],
           '@sunny': ['trưa nắng chang chang mà trong này cũng hầm hập', 'nắng hắt vào tận chỗ ngồi, nóng ran'],
           'tra_da': ['không có quạt, ngồi chút là mồ hôi nhễ nhại'],
           'restaurant': ['quạt thổi thẳng vào tô, mì nguội nhanh', 'bếp sát chỗ ngồi, hơi nóng hầm hập']},
      pos={'*': ['máy lạnh mát rượi, trốn nắng lý tưởng', 'quạt mát, ngồi thoáng'],
           'tra_da': ['ngồi dưới gốc cây mát rượi', 'có gió sông thổi vào, mát không cần quạt']},
      word=('Nóng.', 'Mát.'), sig_neg=('sunny',), sig_pos=('breeze',)),
    A('wifi', ('food',), 'Wifi', 'wifi yếu', topic='ambience', only=('milk_tea', 'cafe_bakery'), subjective=True,
      neg=['wifi chập chờn, gửi cái file mãi không đi', 'mật khẩu wifi dài như bài văn', 'ngồi bàn trong là mất sóng wifi'],
      pos=['wifi mạnh, ngồi làm việc cả chiều', 'wifi nhanh, mật khẩu dán ngay trên bàn', 'ổ cắm sạc gần bàn, wifi ổn, ngồi làm việc sướng'],
      word=('Wifi yếu.', 'Wifi khỏe.')),
    A('parking', ('food', 'shop'), 'Giữ xe', 'chỗ để xe chật', topic='ambience',
      neg=['chỗ để xe chật, dắt ra muốn trầy xe', 'không có ai giữ xe, ngồi mà cứ ngó ra ngoài', 'xe dựng tràn ra lề, đi bộ cũng khó'],
      pos=['có người dắt xe giúp, dễ thương ghê', 'chỗ để xe rộng, có mái che', 'giữ xe cẩn thận, còn che yên xe lúc nắng'],
      word=('Chật chỗ xe.', 'Giữ xe ổn.'), sig_neg=('small_place', 'crowded', 'festival')),
    A('queue', ('food', 'shop'), 'Xếp hàng', '', topic='speed',
      neg=['hàng chờ lộn xộn, người tới sau lấy trước', 'đứng chờ mà không ai hỏi mình cần gì', 'đông quá mà không phát số, ai to tiếng thì được trước'],
      pos=['đông mà vẫn có thứ tự, không ai bị bỏ quên', 'gọi theo lượt rõ ràng, không ai chen ngang', 'đông khách mà vẫn chào từng người'],
      word=('Lộn xộn.', 'Có thứ tự.'), sig_neg=('slow_crowd',), sig_pos=('fast_crowd',)),
    A('value', ('food',), 'Giá và đáng tiền', 'giá hơi chát', topic='price', subjective=True,
      neg={'*': ['giá nhỉnh hơn mặt bằng khu này', 'giá hơi chát so với chất lượng'], 'restaurant': ['giá hơi chát so với phần ăn'],
           'milk_tea': ['thêm topping là tính thêm, cộng lại hơi đau ví'], 'tra_da': ['cốc trà đá vỉa hè mà tính giá như quán máy lạnh'],
           'cafe_bakery': ['ly cà phê với miếng bánh mà gần bằng bữa trưa'],
           'ice_cream': ['thêm một viên với chút topping là gần bằng tô bún']},
      pos={'*': ['giá mềm, sinh viên cũng ghé được', 'giá niêm yết rõ, không tính thêm gì bất ngờ'],
           'restaurant': ['đáng đồng tiền, ăn no mà không đau ví'], 'tra_da': ['vài nghìn một cốc mà ngồi mát cả buổi'],
           'milk_tea': ['ly to, topping nhiều mà giá vẫn mềm'], 'ice_cream': ['viên kem đủ gam, giá mềm cho học sinh']},
      word=('Hơi đắt.', 'Đáng tiền.'), sig_neg=('crit:value:lo', 'slip:overcharge'), sig_pos=('crit:value:hi',)),
    A('seating', ('food',), 'Chỗ ngồi', 'ghế ngồi khó chịu', topic='ambience', only=('tra_da', 'milk_tea'), subjective=True,
      neg={'tra_da': ['ghế nhựa thấp, ngồi lâu mỏi lưng', 'bàn sát lề đường, xe chạy qua là bụi bay vào cốc'],
           'milk_tea': ['chỗ ngồi chật, kéo ghế là đụng bàn bên', 'ghế cao mà không có chỗ gác chân']},
      pos={'tra_da': ['ghế đặt dưới gốc cây, ngồi mát rượi', 'chỗ ngồi thoáng, ngắm phố thích'],
           'milk_tea': ['góc ngồi xinh, chụp hình đẹp', 'ghế êm, ngồi học bài cả buổi']},
      word=('Ghế thấp.', 'Chỗ ngồi xinh.'), sig_neg=('crit:spot:lo', 'small_place'), sig_pos=('crit:spot:hi',)),
    A('cups', ('food',), 'Cốc chén sạch', 'cốc rửa chưa sạch', topic='clean', only=('tra_da',),
      neg=['cốc còn vệt ố, nhìn là ngại uống', 'cốc rửa chưa kỹ, còn mùi chè cũ', 'cốc tráng qua loa, còn dính lá chè'],
      pos=['cốc rửa sạch, trong veo', 'cốc tráng nước sôi trước mặt, yên tâm', 'cốc thủy tinh sạch bóng, cầm thích tay'],
      word=('Cốc bẩn.', 'Cốc sạch.'), sig_neg=('grimy_cups', 'crit:clean:lo', 'slip:grimy', 'slip:dirty'), sig_pos=('crit:clean:hi',)),
    A('dishes', ('food',), 'Tô đũa sạch', 'đũa muỗng chưa sạch', topic='clean', only=('restaurant',),
      neg=['đũa muỗng hơi dính, phải lau lại', 'tô còn vết mỡ ở vành', 'ống đũa để hở, bụi đường bay vào'],
      pos=['đũa muỗng sạch, có ống tráng nước nóng', 'tô chén sáng bóng, cầm yên tâm', 'bếp gọn gàng, nhìn vào là muốn ăn'],
      word=('Đũa dính.', 'Bếp sạch.'), sig_neg=('dirty_bowls', 'crit:hygiene:lo'), sig_pos=('crit:hygiene:hi',)),
    A('creamy', ('food',), 'Kem mịn, lạnh', 'kem chảy nhão', topic='taste', only=('ice_cream',),
      neg=['kem không đủ lạnh, ăn nhanh mà vẫn chảy', 'viên kem mềm oặt, chưa kịp ăn đã nhỏ giọt', 'kem hơi nhão, không mịn như mọi lần'],
      pos={'*': ['viên kem tròn, lạnh vừa, mịn mượt', 'kem lạnh mà không cứng, muỗng xắn vào mềm mịn', 'kem mát lạnh, ăn giải nhiệt buổi trưa liền'],
           '@crit:home:hi': ['kem nhà làm thơm béo, khác hẳn kem hộp', 'nếm là biết kem tự nấu, mịn mà thơm', 'kem nhà làm ăn thanh, không ngọt gắt']},
      word=('Kem nhão.', 'Kem mịn.'), sig_neg=('slip:mushy', 'slip:refrozen', 'slip:icy', 'slip:grainy', 'slip:melted', 'crit:cold:lo'),
      sig_pos=('crit:home:hi', 'crit:cold:hi')),
    # ================================================================ SHOPS
    A('shelves', ('shop',), 'Kệ hàng', 'kệ hàng lộn xộn', topic='clean',
      neg={'*': ['kệ hàng lộn xộn, tìm một món mãi không thấy', 'hàng xếp chồng lên nhau, rút một món là đổ cả dãy'],
           'clothing': ['đồ treo lộn xộn, size nào lẫn size nấy', 'móc áo chen chúc, kéo một cái là rơi ba cái'],
           'florist': ['xô hoa để lung tung, nước đổ lênh láng', 'lá cành cắt vương đầy sàn'],
           'pharmacy': ['tủ thuốc hơi lộn xộn, tìm hộp thuốc mãi mới ra'],
           'grocery': ['kệ mì gói với kệ nước mắm lẫn vào nhau', 'hàng sắp hết hạn để lẫn với hàng mới']},
      pos={'*': ['kệ hàng ngăn nắp, món nào cũng có nhãn', 'hàng xếp theo khu, tìm dễ ghê'],
           'clothing': ['đồ treo theo size, theo màu, nhìn là muốn thử'], 'florist': ['xô hoa xếp theo màu, nhìn như vườn hoa'],
           'pharmacy': ['tủ thuốc xếp gọn, có bảng tên từng loại'], 'grocery': ['hàng mới để sau, hàng gần date để trước, rất có ý']},
      word=('Lộn xộn.', 'Ngăn nắp.'), sig_neg=('messy', 'crit:fifo:lo', 'crit:dates:lo', 'slip:shelf_expired'), sig_pos=('crit:fifo:hi', 'crit:dates:hi')),
    A('fitting_room', ('shop',), 'Phòng thử', 'phòng thử bất tiện', topic='ambience', only=('clothing',),
      neg=['phòng thử chật, rèm kéo không kín', 'phòng thử không có móc treo, đồ phải vắt lên vai', 'phòng thử phải xếp hàng chờ lâu'],
      pos=['phòng thử rộng, rèm kín, có móc treo', 'phòng thử sạch, có dép đi trong', 'phòng thử có ghế ngồi, thử quần tiện lắm'],
      word=('Phòng thử chật.', 'Phòng thử xịn.'), sig_neg=('crit:care:lo', 'slip:room_loss'), sig_pos=('crit:care:hi',)),
    A('mirror', ('shop', 'service'), 'Gương và ánh sáng', 'đèn làm sai màu', topic='ambience', only=('clothing', 'salon'), subjective=True,
      neg={'clothing': ['đèn phòng thử vàng vọt, mặc lên nhìn màu khác hẳn', 'gương hơi mờ, soi không rõ'],
           'salon': ['gương có vệt nước, soi tóc không rõ', 'đèn hơi tối, nhuộm xong ra ngoài mới thấy màu khác']},
      pos={'clothing': ['gương to, đèn sáng, mặc lên nhìn đúng màu', 'ánh sáng chuẩn, chụp hình thử đồ đẹp'],
           'salon': ['gương sáng, có gương cầm tay soi cả phía sau', 'đèn sáng, nhìn rõ từng lọn tóc']},
      word=('Đèn tối.', 'Gương sáng.')),
    A('hovering', ('shop',), 'Cách tiếp khách', 'nhân viên đi theo sát', topic='people', skip=('pharmacy',), subjective=True,
      neg=['{nv} đi theo sát sau lưng, xem hàng mà thấy ngại', 'hỏi một câu thì {nv} chỉ tay chứ không lấy giúp', 'vào tiệm một lúc mới có người để ý',
           '{nv} cứ mời mua thêm, từ chối ba lần vẫn mời'],
      pos=['{nv} để khách tự xem, cần mới tới hỏi, rất thoải mái', '{nv} tư vấn nhiệt tình mà không ép mua', '{nv} hỏi đúng nhu cầu rồi mới gợi ý'],
      word=('Bị bám theo.', 'Thoải mái.'), sig_neg=('crit:ask:lo', 'crit:manner:lo'), sig_pos=('crit:ask:hi', 'crit:style:hi')),
    A('bagging', ('shop',), 'Túi và gói hàng', 'gói hàng qua loa', topic='pack',
      neg={'*': ['túi ni lông mỏng, đi được nửa đường thì rách quai', 'gói hàng qua loa, về tới nhà hộp móp một góc'],
           'florist': ['giấy gói hoa nhàu, nơ buộc lỏng', 'bó hoa không có túi nước, về tới nhà héo cả gốc'],
           'mother_baby': ['giấy gói quà dán băng keo lem nhem', 'hộp quà không có túi xách, ôm về hơi vất vả'],
           'clothing': ['đồ gấp vội, về tới nhà nhăn hết', 'bỏ đồ vào túi mà không gỡ móc treo']},
      pos={'*': ['gói hàng cẩn thận, có cả túi giấy xinh', 'bọc kỹ từng món, cầm về yên tâm'],
           'florist': ['giấy gói hoa đẹp, nơ thắt khéo', 'có túi nước ở gốc hoa, về tới nhà vẫn tươi'],
           'mother_baby': ['gói quà đẹp như ngoài tiệm lớn', 'thắt nơ khéo, người nhận chắc thích lắm'],
           'clothing': ['đồ gấp phẳng phiu, bỏ túi giấy thơm tho']},
      word=('Gói ẩu.', 'Gói khéo.'), sig_neg=('slip:wrinkled', 'crit:presentation:lo', 'crit:packing:lo'),
      sig_pos=('crit:presentation:hi', 'crit:packing:hi')),
    A('pet_smell', ('shop', 'service'), 'Mùi khu thú cưng', 'khu thú cưng có mùi', topic='clean', only=('pet_shop', 'pet_care'),
      neg=['khu để thú cưng hơi nồng mùi, vào là ngửi thấy', 'mùi cát vệ sinh bay ra tận cửa', 'tiệm hơi hắc mùi nước tiểu mèo'],
      pos=['tiệm nuôi thú mà không có mùi, thơm tho', 'khu chuồng thoáng, không ám mùi', 'vào tiệm thơm mùi sữa tắm thú cưng'],
      word=('Nồng mùi.', 'Thơm tho.'), sig_neg=('messy', 'litter')),
    A('cages', ('shop', 'service'), 'Chuồng sạch', 'chuồng chưa sạch', topic='clean', only=('pet_shop', 'pet_care'),
      neg=['chuồng còn vương lông với hạt thức ăn', 'khay nước trong chuồng hơi đục', 'lót chuồng ướt, mấy bé nằm không yên'],
      pos=['chuồng lau sạch, có lót khăn mềm', 'mấy bé trong chuồng sạch sẽ, lông mượt', 'khay nước trong veo, thay liên tục'],
      word=('Chuồng bẩn.', 'Chuồng sạch.'), sig_neg=('messy', 'litter'), sig_pos=('crit:coat:hi',)),
    A('returns', ('shop',), 'Đổi trả', 'đổi trả làm khó', topic='people', only=('clothing', 'grocery', 'mother_baby', 'pet_shop'), need=('return_task',),
      subjective=True,
      neg=['hỏi chuyện đổi trả thì trả lời vòng vo', 'đổi size mà phải giải thích mấy lần', 'đổi hàng phải chờ gọi quản lý mãi'],
      pos=['đổi trả nhanh gọn, không làm khó khách', 'nói rõ chính sách đổi trả, ai nghe cũng hiểu', 'đổi hàng mà vẫn vui vẻ như lúc bán'],
      word=('Đổi khó.', 'Đổi dễ.'), sig_neg=('slip:policy_broken', 'slip:refuse_valid'), sig_pos=('crit:accuracy:hi',)),
    A('price_tags', ('shop',), 'Tem giá', 'thiếu tem giá', topic='price', skip=('florist',),
      neg=['nhiều món không có tem giá, phải hỏi từng món', 'giá trên kệ một kiểu, tính tiền một kiểu', 'tem giá dán đè lên hạn dùng, đọc không ra'],
      pos=['món nào cũng dán giá rõ ràng', 'giá niêm yết rõ, tính đúng như trên kệ', 'tem giá to, người lớn tuổi đọc cũng dễ'],
      word=('Thiếu tem giá.', 'Giá rõ ràng.'), sig_neg=('crit:price:lo', 'slip:shelf_price', 'slip:overcharge'), sig_pos=('crit:price:hi',)),
    A('shop_price', ('shop',), 'Giá cả', 'giá hơi cao', topic='price', subjective=True,
      neg=['giá nhỉnh hơn ngoài chợ một chút', 'đồ đẹp mà giá hơi chát', 'mua nhiều mà không được bớt đồng nào'],
      pos=['giá hợp lý, có khi rẻ hơn ngoài chợ', 'giá mềm, mua nhiều còn được bớt', 'đáng tiền, chất lượng tương xứng'],
      word=('Hơi đắt.', 'Giá mềm.'), sig_neg=('crit:value:lo', 'slip:sale_high'), sig_pos=('crit:value:hi',)),
    A('fresh', ('shop', 'service'), 'Độ tươi', 'hàng không tươi', topic='taste', only=('florist', 'grocery', 'farm'),
      neg={'florist': ['hoa hơi héo mép cánh', 'lá hoa có vài chấm vàng'], 'grocery': ['rau ở kệ hơi héo', 'trái cây có mấy quả dập'],
           'farm': ['rau hơi héo lá ngoài', 'trứng có quả dính phân gà, nhìn hơi ngại']},
      pos={'florist': ['hoa tươi rói, cắm được cả tuần', 'nụ hoa chắc, nở đều'], 'grocery': ['rau quả tươi, còn giọt nước', 'trái cây chín vừa, không dập'],
           'farm': ['rau xanh mướt, trứng còn ấm', 'rau vừa hái, còn nguyên sương']},
      word=('Héo.', 'Tươi rói.'), sig_neg=('slip:wilting', 'slip:bruised', 'slip:expired', 'crit:fresh:lo'), sig_pos=('crit:fresh:hi',)),
    A('advice', ('shop',), 'Dặn dò khi bán', 'đưa thuốc không dặn', topic='people', only=('pharmacy', 'mother_baby', 'pet_shop'),
      neg={'pharmacy': ['đưa thuốc mà không dặn uống trước hay sau ăn', 'hỏi tác dụng phụ thì trả lời qua loa'],
           'mother_baby': ['hỏi sữa nào hợp với bé thì trả lời chung chung'], 'pet_shop': ['hỏi cách cho bé ăn thì chỉ nói "tùy anh chị"']},
      pos={'pharmacy': ['dặn kỹ cách uống, còn ghi lên vỏ hộp', 'hỏi kỹ tiền sử dị ứng rồi mới đưa thuốc'],
           'mother_baby': ['tư vấn kỹ từng loại sữa, không ép mua loại đắt'], 'pet_shop': ['dặn kỹ cách cho ăn, cách tắm cho bé']},
      word=('Không dặn.', 'Dặn kỹ.'), sig_neg=('crit:care:lo', 'crit:ask:lo'), sig_pos=('crit:care:hi', 'crit:ask:hi')),
    A('card', ('shop',), 'Thiệp', 'thiệp viết vội', topic='pack', only=('florist', 'mother_baby'),
      neg=['thiệp viết chữ hơi vội, nhìn không kỹ', 'thiệp in sẵn, không có lời riêng'],
      pos=['thiệp viết tay nắn nót', 'lời chúc trên thiệp viết khéo, người nhận cảm động'],
      word=('Thiệp vội.', 'Thiệp đẹp.'), sig_neg=('slip:card',)),
    A('aisle', ('shop',), 'Lối đi', 'lối đi chật', topic='ambience', only=('mother_baby', 'grocery', 'pet_shop'),
      neg=['lối đi hẹp, đẩy xe nôi vào không lọt', 'thùng hàng chắn lối đi, phải lách người'],
      pos=['lối đi rộng, đẩy xe nôi thoải mái', 'có góc cho bé ngồi chơi, mẹ yên tâm chọn đồ'],
      word=('Lối chật.', 'Rộng rãi.'), sig_neg=('small_place', 'crowded')),
    # ================================================================ FRONT-OF-HOUSE PEOPLE (food, shops, services)
    A('smile', PEOPLE_FAMS, 'Nụ cười, thái độ', 'nhân viên thái độ lạnh', topic='people', subjective=True, skip=('delivery',),
      neg=['{nv} không cười lấy một cái, hỏi gì cũng ừ hử', '{nv} trả lời nhát gừng, như đang giận ai', '{nv} mặt lạnh tanh, đưa đồ không nói câu nào',
           '{nv} khó ưa, hỏi thêm câu là thở dài', '{nv} vừa làm vừa than mệt, khách nghe cũng ngại'],
      pos=['{nv} cười tươi, chào hỏi dễ thương', '{nv} nói chuyện nhỏ nhẹ, dễ chịu', '{nv} vui vẻ, còn hỏi thăm đi làm về có mệt không',
           '{nv} lễ phép, đưa đồ bằng hai tay', '{nv} dễ thương, khách lớn tuổi hỏi mấy lần vẫn kiên nhẫn'],
      sarc=['{nv} thân thiện lắm, thân thiện tới mức không thèm nhìn khách một cái 👏', 'thái độ phục vụ mười điểm, thang điểm một trăm 🙂'],
      word=('Mặt lạnh.', 'Dễ thương.'), sig_neg=('crit:manner:lo', 'crit:attitude:lo', 'slip:rude'),
      sig_pos=('crit:manner:hi', 'crit:attitude:hi', 'crit:welcome:hi')),
    A('voice', ('food', 'shop'), 'Giọng nói', 'nói nhỏ khó nghe', topic='people', subjective=True,
      neg=['{nv} nói nhỏ quá, hỏi lại ba lần mới nghe', '{nv} gọi món to như loa phường', '{nv} nói nhanh quá, nghe không kịp'],
      pos=['{nv} nói rõ ràng, dễ nghe', 'giọng {nv} ấm, nghe dễ chịu', '{nv} đọc lại order rành mạch, yên tâm'],
      word=('Nói nhỏ.', 'Nói rõ.')),
    A('uniform', PEOPLE_FAMS, 'Tác phong, đồng phục', 'nhân viên ăn mặc luộm thuộm', topic='dress', subjective=True,
      skip=('farm', 'tour_guide', 'delivery', 'homestay'),
      neg={'*': ['{nv} mặc áo nhăn nhúm, nhìn hơi luộm thuộm'],
           'food': ['{nv} không đeo tạp dề, tóc để xõa lúc pha chế', '{nv} không đội mũ, không đeo khẩu trang lúc làm đồ ăn',
                    '{nv} đi dép lê loẹt quẹt sau quầy'],
           'shop': ['{nv} đi dép lê loẹt quẹt sau quầy', '{nv} mặc áo phông nhàu, không đeo bảng tên'],
           'pet_care': ['{nv} mặc áo dính đầy lông thú, nhìn hơi luộm thuộm'],
           'salon': ['áo choàng cho khách hơi cũ, dính tóc khách trước'], 'repair': ['{nv} tay dính dầu mà cầm luôn điện thoại khách']},
      pos={'*': ['{nv} ăn mặc gọn gàng, sạch sẽ, nhìn là yên tâm', '{nv} mặc đồng phục chỉn chu'],
           'food': ['{nv} mặc tạp dề sạch, tóc buộc gọn gàng', '{nv} đeo găng tay khi gắp đồ ăn, sạch sẽ'],
           'salon': ['áo choàng sạch thơm, thay mới cho từng khách'], 'repair': ['{nv} lót khăn sạch trước khi đặt máy khách lên bàn']},
      sarc=['{nv} ăn mặc rất "thoải mái", tưởng đang ở nhà ngủ trưa 👏'],
      word=('Luộm thuộm.', 'Gọn gàng.')),
    A('phone', ('food', 'shop'), 'Dùng điện thoại', 'nhân viên mải điện thoại', topic='people', subjective=True,
      neg=['{nv} vừa làm vừa bấm điện thoại', 'khách tới quầy mà {nv} vẫn mải nhắn tin', '{nv} kẹp điện thoại vào vai nói chuyện, tay vẫn làm đồ'],
      pos=['{nv} tập trung làm, không cầm điện thoại', 'suốt lúc làm {nv} không đụng tới điện thoại, chuyên nghiệp ghê'],
      word=('Mải điện thoại.', 'Tập trung.'), sig_neg=('slow',)),
    A('speed', PEOPLE_FAMS, 'Tốc độ', 'chờ lâu', topic='speed', skip=('homestay', 'tour_guide'),
      neg={'*': ['chờ hơi lâu, lướt hết bảng tin mới xong', 'chờ mòn mỏi, không ai báo phải đợi bao lâu'],
           'food': ['gọi món xong chờ mòn mỏi', 'bàn sau tới sau mà có đồ trước'],
           'service': ['hẹn một tiếng mà làm gần hai tiếng', 'chờ lâu mà không ai báo tiến độ']},
      pos={'*': ['làm nhanh gọn, không phải chờ', 'nhanh tay mà vẫn kỹ'],
           'food': ['ra món nhanh, chưa kịp lướt điện thoại đã có'], 'service': ['làm đúng giờ hẹn, còn xong sớm hơn']},
      word=('Chậm.', 'Nhanh.'), sig_neg=('slow', 'crit:speed:lo', 'crit:time:lo'), sig_pos=('quick',)),
    A('regular', PEOPLE_FAMS, 'Nhớ khách quen', '', topic='people',
      pos={'*': ['{nv} nhớ luôn tôi hay dặn gì', 'mới ghé vài lần mà đã được nhớ tên'],
           'food': ['{nv} nhớ luôn tôi hay uống ít đá', 'chưa kịp gọi đã được hỏi "như mọi khi hả"'],
           'service': ['{owner} nhớ cả lần trước tôi dặn gì', 'khách quen nên được hỏi han kỹ, thấy ấm lòng']},
      word=('', 'Nhớ khách.'), sig_pos=('regular', 'crit:regular:hi', 'crit:remember:hi')),
    # ================================================================ SERVICES
    A('towel', ('service',), 'Khăn gội', 'khăn gội ẩm', topic='clean', only=('salon',), subjective=True,
      neg=['khăn gội hơi ẩm, ngửi có mùi', 'khăn quấn tóc cũ sờn, xù lông', 'khăn đắp mặt nguội ngắt'],
      pos=['khăn gội thơm, khô, như mới giặt', 'có khăn nóng đắp mặt lúc gội, thư giãn ghê', 'khăn mềm, thay mới cho từng khách'],
      word=('Khăn ẩm.', 'Khăn thơm.'), sig_neg=('messy', 'worn')),
    A('hair_floor', ('service',), 'Tóc rơi dưới sàn', 'tóc rơi đầy sàn', topic='clean', only=('salon',),
      neg=['tóc khách trước còn vương đầy dưới ghế', 'cắt xong không ai quét, tóc dính đầy dép', 'tóc vụn dính trên ghế chờ'],
      pos=['cắt xong quét tóc liền, sàn sạch', 'tiệm sạch, không thấy sợi tóc nào dưới sàn', 'phủi tóc vụn trên cổ kỹ lắm'],
      word=('Tóc đầy sàn.', 'Sàn sạch.'), sig_neg=('messy', 'crowded')),
    A('wash', ('service',), 'Gội đầu', 'nước gội lúc nóng lúc lạnh', topic='taste', only=('salon',),
      neg=['nước gội lúc nóng lúc lạnh', 'gội vội, xả chưa sạch dầu'],
      pos=['nước gội ấm vừa, được massage đầu kỹ', 'gội kỹ, xả sạch, tóc thơm cả ngày', 'gội đầu nhẹ tay, suýt ngủ quên'],
      word=('Nước lạnh.', 'Gội kỹ.'), sig_neg=('slip:water', 'slip:shampoo')),
    A('upsell', ('service',), 'Tư vấn thật', 'tư vấn dịch vụ đắt tiền', topic='people', only=('salon',), subjective=True,
      neg=['{nv} cứ gợi ý thêm dịch vụ đắt tiền', 'hỏi cắt thường mà được mời hấp dầu ba lần'],
      pos=['{nv} tư vấn thật, kiểu nào hợp mới làm', 'được khuyên đừng nhuộm vì tóc đang yếu, thật lòng ghê'],
      word=('Chèo kéo.', 'Tư vấn thật.'), sig_neg=('crit:attitude:lo',), sig_pos=('crit:attitude:hi',)),
    A('gel', ('service',), 'Gel bền đẹp', 'gel mau bong', topic='taste', only=('nail',),
      neg=['mới mấy ngày gel đã bong mép', 'mặt gel nhăn nheo, sờ thấy gợn', 'màu loang, nhìn kỹ thấy cả móng bên dưới',
           'gel còn hơi dính, bám bụi cả ngày'],
      pos=['gel bóng như gương, hai tuần chưa tróc', 'màu lên đều, mỏng mà vẫn đậm', 'mặt móng láng mịn, không gợn chút nào'],
      word=('Mau bong.', 'Gel bền.'), sig_neg=('slip:wet', 'slip:lift', 'slip:thick', 'slip:patchy', 'slip:sticky', 'crit:finish:lo'),
      sig_pos=('crit:finish:hi',)),
    A('nail_tools', ('service',), 'Dụng cụ sạch', 'dụng cụ không sạch', topic='clean', only=('nail',),
      neg=['kềm lấy ra từ khay dùng rồi, không thấy hấp', 'cây dũa mòn vẹt, chắc dùng cho khách trước', 'bàn làm móng còn bụi móng của người trước'],
      pos=['dụng cụ lấy ra từ tủ hấp, dũa mới bóc trước mặt', 'mỗi khách một bộ dũa riêng, yên tâm', 'bàn lau sạch, khăn lót thay mới'],
      word=('Dụng cụ bẩn.', 'Sạch sẽ.'), sig_neg=('slip:dirty_tools', 'slip:reuse_file', 'slip:health', 'crit:clean:lo'), sig_pos=('crit:clean:hi',)),
    A('nail_gentle', ('service',), 'Nhẹ tay', 'làm đau tay', topic='people', only=('nail',),
      neg=['cắt da hơi sâu, rát cả buổi', 'hơ đèn nóng rát đầu ngón', 'tháo gel mạnh tay, móng mỏng dính'],
      pos=['{nv} đẩy da nhẹ nhàng, không đau chút nào', 'tháo gel ủ kỹ, móng thật còn nguyên', 'làm nhẹ tay, ngồi suýt ngủ quên'],
      word=('Đau tay.', 'Nhẹ tay.'), sig_neg=('slip:bleed', 'slip:pry', 'slip:heat', 'slip:over_file', 'crit:gentle:lo'), sig_pos=('crit:gentle:hi',)),
    A('nail_look', ('service',), 'Đúng ảnh mẫu', 'không giống ảnh mẫu', topic='taste', only=('nail',), subjective=True,
      neg=['dáng móng không giống ảnh mẫu lắm', 'màu ra tay hơi khác màu trong ảnh', 'mười móng dũa chưa đều nhau'],
      pos=['y chang ảnh mẫu, chụp hình đẹp lắm', 'mười móng đều tăm tắp', 'màu lên tay xinh hơn cả trong ảnh'],
      word=('Khác ảnh.', 'Y ảnh mẫu.'), sig_neg=('slip:shape', 'slip:colour', 'slip:art', 'crit:service:lo'), sig_pos=('crit:service:hi',)),
    A('fumes', ('service',), 'Mùi trong tiệm', 'tiệm nồng mùi hóa chất', topic='clean', only=('nail',), subjective=True,
      neg=['mùi acetone nồng, ngồi lâu hơi nhức đầu', 'tiệm hơi bí, mùi keo với nước tẩy lẫn lộn'],
      pos=['tiệm thoáng, có quạt hút nên không nồng mùi', 'chai lọ đậy nắp kỹ, không ngửi thấy mùi hóa chất'],
      word=('Nồng mùi.', 'Thoáng.'), sig_neg=('crowded', 'messy')),
    A('honesty', ('service',), 'Giải thích thật', 'giải thích mập mờ', topic='people', only=('repair',),
      neg=['hỏi hư chỗ nào thì nói chung chung, nghe không hiểu', 'báo giá xong mới nói thêm tiền linh kiện', 'giải thích toàn từ chuyên môn, nghe như đánh đố'],
      pos=['giải thích từng chỗ hư, đưa linh kiện cũ cho xem', 'nói thật cái nào đáng sửa, cái nào không cần', 'báo giá trước, làm xong đúng giá, không phát sinh'],
      word=('Mập mờ.', 'Thật thà.'), sig_neg=('crit:honesty:lo', 'crit:diagnosis:lo'), sig_pos=('crit:honesty:hi', 'crit:diagnosis:hi')),
    A('workshop', ('service',), 'Tiệm gọn gàng', 'tiệm bừa bộn', topic='clean', only=('repair',),
      neg=['đồ nghề bày la liệt, dầu nhớt dây ra sàn', 'ghế chờ dính dầu, ngồi xuống là bẩn quần'],
      pos=['đồ nghề treo gọn, bàn sửa sạch', 'tiệm nhỏ mà ngăn nắp, ốc vít chia hộp rõ ràng'],
      word=('Bừa bộn.', 'Gọn gàng.'), sig_neg=('messy', 'worn')),
    A('warranty', ('service',), 'Phiếu bảo hành', 'không có phiếu bảo hành', topic='comms', only=('repair',),
      neg=['không đưa phiếu bảo hành, phải tự nhớ ngày sửa'],
      pos=['có phiếu bảo hành ghi rõ ngày, rõ linh kiện', 'dặn kỹ cách dùng để máy bền'],
      word=('Không phiếu.', 'Có bảo hành.'), sig_neg=('crit:warranty:lo',), sig_pos=('crit:warranty:hi',)),
    A('gentle', ('service',), 'Nhẹ tay với bé', 'bé về còn sợ', topic='people', only=('pet_care',),
      neg=['bé nhà tôi về cứ run run, chắc bị giữ chặt quá', 'bé về trốn dưới gầm giường cả buổi'],
      pos=['nhẹ tay với bé, bé về còn vẫy đuôi', 'bé nhà tôi vốn sợ người lạ mà ở đây ngoan lắm', 'bé được vuốt ve nói chuyện suốt, không sợ chút nào'],
      word=('Bé sợ.', 'Nhẹ tay.'), sig_neg=('crit:gentle:lo', 'crit:calm:lo'), sig_pos=('crit:gentle:hi', 'crit:calm:hi')),
    A('pet_update', ('service',), 'Cập nhật hình bé', 'không báo tin về bé', topic='comms', only=('pet_care',), subjective=True,
      neg=['gửi bé cả buổi mà không nhận được tin gì', 'hỏi bé ăn chưa mà mãi mới trả lời'],
      pos=['được gửi hình bé trong lúc tắm, yên tâm ghê', 'nhắn báo bé ăn ngoan, ngủ ngoan, dễ thương quá'],
      word=('Im lặng.', 'Báo tin kỹ.')),
    A('bathroom', ('service',), 'Phòng tắm', 'phòng tắm chưa sạch', topic='clean', only=('homestay',),
      neg=['phòng tắm có vệt ố quanh vòi sen', 'thoát nước phòng tắm chậm, tắm xong ngập mắt cá', 'bồn rửa còn sợi tóc của khách trước'],
      pos=['phòng tắm sạch bóng, khăn tắm thơm', 'phòng tắm rộng, sạch, có đủ dầu gội', 'phòng tắm khô ráo, có cả dép riêng'],
      word=('Phòng tắm bẩn.', 'Phòng tắm sạch.'), sig_neg=('crit:room:lo', 'slip:dirty_room', 'slip:sloppy_room'), sig_pos=('crit:room:hi',)),
    A('sheets', ('service',), 'Ga gối', 'ga gối chưa thơm', topic='clean', only=('homestay',),
      neg=['ga giường còn nếp nhăn, gối hơi xẹp', 'chăn có mùi ẩm', 'gối có vệt ố mờ, nhìn hơi ngại'],
      pos=['ga gối trắng tinh, thơm mùi nắng', 'chăn dày ấm, ngủ một mạch tới sáng', 'nệm êm, gối vừa đầu'],
      word=('Chăn ẩm.', 'Chăn thơm.'), sig_neg=('crit:room:lo', 'slip:sloppy_room', 'slip:damp'), sig_pos=('crit:room:hi',)),
    A('noise', ('service',), 'Tiếng ồn', 'phòng ồn', topic='ambience', only=('homestay',), subjective=True,
      neg=['phòng cách âm kém, nghe rõ tiếng phòng bên', 'sáng sớm tiếng xe máy ngoài ngõ vọng vào', 'khách phòng bên hát karaoke tới khuya'],
      pos=['phòng yên tĩnh, ngủ ngon lành', 'đêm chỉ nghe tiếng dế, ngủ sâu lắm'],
      word=('Ồn.', 'Yên tĩnh.'), sig_neg=('festival', 'crowded'), sig_pos=('calm',)),
    A('hot_water', ('service',), 'Nước nóng', 'nước nóng chờ lâu', topic='ambience', only=('homestay',),
      neg=['nước nóng chờ mãi mới lên', 'tắm được nửa chừng thì hết nước nóng'],
      pos=['nước nóng có liền, tắm đêm lạnh sướng', 'bình nóng lạnh mạnh, cả nhà tắm không phải chờ'],
      word=('Nước lạnh.', 'Nước nóng ngay.'), sig_neg=('slip:no_heater', 'crit:warmth:lo'), sig_pos=('crit:warmth:hi',)),
    A('checkin', ('service',), 'Đón khách, nhận phòng', 'nhận phòng lâu', topic='people', only=('homestay',),
      neg=['tới nơi phải đứng chờ ở cổng một lúc mới có người ra', 'thủ tục nhận phòng hơi rườm rà', 'nhận phòng mà không ai chỉ chỗ bật nước nóng'],
      pos=['{owner} ra tận ngõ đón, còn mời trà gừng', 'nhận phòng nhanh, được dặn kỹ chỗ ăn chỗ chơi', 'được đón bằng ly nước chanh mát, dễ thương ghê'],
      word=('Chờ lâu.', 'Đón nồng hậu.'), sig_neg=('crit:welcome:lo', 'slip:unconfirmed', 'slip:wrong_booking'), sig_pos=('crit:welcome:hi', 'regular')),
    A('jokes', ('service',), 'Chuyện và câu đùa', 'kể chuyện khô', topic='people', only=('tour_guide',),
      neg=['hướng dẫn viên kể chuyện hơi khô, cả đoàn ngáp', 'một câu đùa kể lại ba lần', 'thuyết minh như đọc sách, không có chuyện nào vui'],
      pos=['hướng dẫn viên đùa duyên, cả đoàn cười suốt', 'kể chuyện sử mà nghe như xem phim', 'biết nhiều chuyện hay, hỏi gì cũng trả lời được'],
      word=('Khô.', 'Duyên.'), sig_neg=('crit:story:lo',), sig_pos=('crit:story:hi',)),
    A('punctual', ('service',), 'Đúng giờ', 'trễ giờ hẹn', topic='speed', only=('tour_guide', 'delivery'),
      neg={'tour_guide': ['hẹn bảy giờ mà gần tám giờ mới xuất phát', 'về trễ giờ hẹn, lỡ cả bữa tối'],
           'delivery': ['giao trễ hơn giờ hẹn gần nửa tiếng', 'báo giao buổi sáng mà chiều mới tới']},
      pos={'tour_guide': ['đi đúng giờ, không ai phải chờ', 'lịch trình chuẩn, về đúng giờ hẹn'],
           'delivery': ['giao đúng khung giờ, không phải chờ', 'giao sớm hơn hẹn mà vẫn gọi hỏi trước']},
      word=('Trễ.', 'Đúng giờ.'), sig_neg=('crit:pace:lo', 'crit:time:lo', 'slip:late', 'slip:too_late', 'overtime'),
      sig_pos=('crit:pace:hi', 'crit:time:hi')),
    A('headcount', ('service',), 'Điểm danh đoàn', 'để lạc khách', topic='people', only=('tour_guide',),
      neg=['có lúc để lạc cả nhóm nhỏ phía sau', 'lên xe mà không ai đếm lại người'],
      pos=['mỗi điểm dừng đều đếm đủ người', 'luôn đi cuối đoàn để không ai bị bỏ lại'],
      word=('Lạc đoàn.', 'Đủ người.'), sig_neg=('crit:safety:lo',), sig_pos=('crit:safety:hi',)),
    A('bus', ('service',), 'Xe đưa đón', 'xe cũ, máy lạnh yếu', topic='ambience', only=('tour_guide',), subjective=True,
      neg=['xe hơi cũ, ghế ngồi lún', 'máy lạnh trên xe lúc chạy lúc không', 'xe có mùi xăng, người say xe khổ lắm'],
      pos=['xe sạch, có sẵn nước suối lạnh', 'ghế xe êm, ngả ra ngủ một giấc ngon lành', 'tài xế chạy êm, cả đoàn không ai say xe'],
      word=('Xe cũ.', 'Xe êm.'), sig_neg=('sunny',)),
    A('itinerary', ('service',), 'Lịch trình', 'lịch trình dày đặc', topic='speed', only=('tour_guide',), subjective=True,
      neg=['lịch trình dày đặc, đi như chạy', 'mỗi điểm dừng có mười lăm phút, chưa kịp xem đã phải lên xe'],
      pos=['lịch trình thong thả, có thời gian chụp ảnh', 'điểm nào cũng được ở lâu vừa đủ, không vội'],
      word=('Vội.', 'Thong thả.'), sig_neg=('crit:pace:lo',), sig_pos=('crit:pace:hi',)),
    A('guest_care', ('service',), 'Quan tâm khách', 'không hỏi han khách', topic='people', only=('tour_guide',), subjective=True,
      neg=['đoàn có người say xe mà không ai hỏi han', 'người lớn tuổi đi chậm mà không ai đi cùng'],
      pos=['nhắc cả đoàn uống nước, che nắng', 'để ý từng người, ai mệt là cho nghỉ liền', 'dìu cả bà cụ lên dốc, dễ thương ghê'],
      word=('Bỏ mặc.', 'Chu đáo.'), sig_neg=('crit:safety:lo',), sig_pos=('crit:safety:hi',)),
    A('photo_spots', ('service',), 'Chỗ chụp ảnh', 'dừng chụp ảnh ít', topic='ambience', only=('tour_guide',), subjective=True,
      neg=['dừng chụp ảnh ít quá, chưa kịp giơ máy đã đi', 'toàn dừng chỗ ngược sáng, ảnh ai cũng đen thui'],
      pos=['dẫn tới chỗ chụp ảnh đẹp, còn chụp giúp cả đoàn', 'biết góc chụp đẹp, ảnh ai cũng ưng'],
      word=('Ít ảnh.', 'Ảnh đẹp.')),
    A('mic', ('service',), 'Giọng, micro', 'micro rè', topic='people', only=('tour_guide',), subjective=True,
      neg=['micro rè rè, ngồi cuối xe nghe không rõ', 'nói nhỏ quá, đoàn phía sau phải hỏi lại'],
      pos=['giọng to rõ, ngồi cuối xe vẫn nghe', 'giọng thuyết minh truyền cảm, nghe mãi không chán'],
      word=('Rè.', 'Rõ.')),
    A('polite', ('service',), 'Lễ phép khi giao', 'shipper cộc lốc', topic='people', only=('delivery',), subjective=True,
      neg=['shipper đưa hàng không nói câu nào', 'gọi xuống lấy hàng mà giọng như ra lệnh', 'shipper ném gói hàng qua cổng'],
      pos=['shipper chào hỏi lễ phép, đưa hàng bằng hai tay', 'shipper dễ thương, còn dặn cẩn thận hàng dễ vỡ', 'shipper cảm ơn rối rít, ai nhận cũng vui'],
      word=('Cộc lốc.', 'Lễ phép.'), sig_neg=('crit:contact:lo',), sig_pos=('crit:contact:hi',)),
    A('calls', ('service',), 'Gọi điện báo', 'không gọi trước', topic='comms', only=('delivery',),
      neg=['tới nơi không gọi, đứng ngoài cổng bấm còi', 'gọi liên tục lúc tôi đang họp', 'nhắn tin cụt lủn "xuống lấy hàng"'],
      pos=['gọi trước mười phút, báo sắp tới', 'nhắn tin báo trước, không làm phiền', 'không nghe máy thì nhắn tin, chờ thêm chút'],
      word=('Không gọi.', 'Gọi trước.'), sig_neg=('slip:no_call',), sig_pos=('crit:contact:hi',)),
    A('rider', ('service',), 'Mũ, áo shipper', 'shipper luộm thuộm', topic='dress', only=('delivery',), subjective=True,
      neg=['áo đồng phục nhăn nhúm, lấm tấm bùn', 'shipper đội mũ bảo hiểm mà không cài quai'],
      pos=['shipper mặc áo gọn gàng, đội mũ đàng hoàng', 'áo mưa trùm kín thùng hàng, chu đáo'],
      word=('Luộm thuộm.', 'Gọn gàng.')),
    A('parcel', ('service',), 'Tình trạng hàng', 'hàng móp', topic='pack', only=('delivery',),
      neg=['hộp giao tới hơi móp một góc', 'túi hàng ướt lem nhem vì mưa', 'đồ uống sóng sánh, tràn ra túi'],
      pos=['hàng bọc kỹ, tới tay còn nguyên', 'trời mưa mà hàng được bọc ni lông khô ráo', 'đồ uống giao tới còn lạnh, không đổ giọt nào'],
      word=('Móp.', 'Nguyên vẹn.'), sig_neg=('slip:broken', 'slip:spilled', 'slip:wet', 'slip:burst', 'crit:condition:lo'),
      sig_pos=('crit:condition:hi',)),
    A('farm_label', ('service',), 'Nhãn hàng', 'nhãn ghi không rõ', topic='comms', only=('farm',),
      neg=['nhãn không ghi ngày hái, không biết để được bao lâu', 'ghi rau sạch mà không nói rõ trồng thế nào'],
      pos=['nhãn ghi rõ ngày hái, nơi trồng', 'có hướng dẫn bảo quản dán kèm, chu đáo'],
      word=('Nhãn sơ sài.', 'Nhãn rõ.'), sig_neg=('crit:honest:lo', 'slip:label', 'slip:label_plain'), sig_pos=('crit:honest:hi',)),
    A('farm_stall', ('service',), 'Sạp hàng', 'sạp lấm bùn', topic='clean', only=('farm',),
      neg={'*': ['giỏ rau để dưới đất, nhìn hơi ngại', 'rau để sát lối đi, khách qua lại quệt vào'],
           '@rain': ['trời mưa, sạp bán lấm bùn, giỏ để dưới đất', 'mưa hắt vào sạp, rau lấm tấm bùn']},
      pos=['sạp gọn, rau bày trong rổ tre sạch sẽ', 'có tấm bạt che nắng, rau tươi cả buổi'],
      word=('Lấm bùn.', 'Sạp gọn.'), sig_neg=('rain', 'messy'), sig_pos=('breeze',)),
    A('weigh', ('service',), 'Cân đủ', 'cân thiếu', topic='price', only=('farm',),
      neg=['cân thiếu, về nhà cân lại hụt một lạng', 'bó rau nhìn to mà gỡ ra toàn cọng'],
      pos=['cân đủ, còn cho thêm nắm hành', 'cân trước mặt khách, rõ ràng sòng phẳng'],
      word=('Thiếu cân.', 'Đủ cân.'), sig_neg=('crit:quantity:lo', 'slip:short'), sig_pos=('crit:quantity:hi',)),
    A('farm_pack', ('service',), 'Đóng gói rau trứng', 'đóng gói sơ sài', topic='pack', only=('farm',), subjective=True,
      neg=['trứng để chung túi với rau, nhìn hơi lo', 'rau bọc túi ni lông kín mít, về tới nhà hơi úng'],
      pos=['rau buộc gọn bằng lạt, trứng lót rơm cẩn thận', 'gói bằng lá chuối, nhìn mộc mạc dễ thương'],
      word=('Gói sơ sài.', 'Gói khéo.')),
    A('svc_price', ('service',), 'Giá dịch vụ', 'giá dịch vụ hơi cao', topic='price', subjective=True, skip=('tour_guide',),
      neg=['giá hơi cao so với mặt bằng', 'làm xong mới báo thêm phụ phí'],
      pos=['giá rõ ràng, báo trước rồi mới làm', 'giá phải chăng, làm kỹ, đáng tiền'],
      word=('Hơi đắt.', 'Đáng tiền.'), sig_neg=('crit:price:lo', 'slip:overcharge', 'crit:value:lo'), sig_pos=('crit:price:hi', 'crit:clarity:hi')),
    # ================================================================ TEACHER
    A('method', ('school',), 'Cách giảng', 'giảng nhanh, khó hiểu', topic='method', subjective=True,
      neg={'p': ['con về kể cô/thầy giảng nhanh quá, con chép không kịp', 'con bảo cô/thầy giảng lý thuyết nhiều, ít ví dụ',
                 'con về làm bài không được vì trên lớp chưa hiểu', 'con kể cả tiết chỉ nghe giảng, không được hỏi câu nào'],
           's': ['cô/thầy giảng nhanh quá, em chép không kịp', 'lý thuyết nhiều quá, em nghe mà buồn ngủ', 'em chưa hiểu bài mà cô/thầy đã chuyển phần mới'],
           'o': ['tiết dạy hơi dồn, học sinh theo không kịp', 'phần lý thuyết dài, ví dụ còn ít']},
      pos={'p': ['con về giảng lại cho cả nhà nghe, chắc trên lớp dễ hiểu lắm', 'cô/thầy giảng chậm rãi, có ví dụ gần gũi nên con hiểu bài',
                 'con bảo cô/thầy chia bài thành từng bước nhỏ, dễ theo', 'con kể cô/thầy lấy ví dụ bằng chuyện đi chợ, con nhớ bài lâu'],
           's': ['cô/thầy giảng dễ hiểu ghê, có ví dụ bằng bánh kẹo luôn', 'em hiểu bài ngay trên lớp, về nhà làm bài vèo cái xong',
                 'cô/thầy vẽ sơ đồ lên bảng, nhìn là hiểu'],
           'o': ['tiết dạy mạch lạc, có ví dụ gần gũi', 'cách chia bài thành từng bước nhỏ rất đáng học hỏi']},
      word=('Giảng nhanh.', 'Dễ hiểu.'), sig_neg=('crit:care:lo',), sig_pos=('crit:care:hi',)),
    A('activities', ('school',), 'Hoạt động trên lớp', 'lớp ít hoạt động', topic='method', subjective=True,
      neg={'p': ['con bảo cả tiết chỉ ngồi chép bài, không có hoạt động gì', 'con kể lớp không được làm nhóm, ngồi im cả buổi'],
           's': ['cả tiết ngồi chép, chán ghê', 'không có hoạt động nào, em ngồi đếm quạt quay'],
           'o': ['tiết học còn ít hoạt động cho học sinh']},
      pos={'p': ['con kể lớp được chơi trò đố vui, về còn đòi chơi tiếp', 'có hoạt động nhóm nên con hào hứng đi học',
                 'con về kể được làm thí nghiệm nhỏ, mắt sáng rỡ'],
           's': ['trò đố vui cuối tiết vui xỉu', 'được làm nhóm với bạn, học mà như chơi', 'cô/thầy cho cả lớp đóng kịch, vui ghê'],
           'o': ['hoạt động nhóm tổ chức gọn, học sinh hào hứng']},
      word=('Chán.', 'Vui.')),
    A('homework', ('school',), 'Bài tập về nhà', 'bài về nhà nhiều', topic='method', subjective=True,
      neg={'p': ['bài tập về nhà hơi nhiều, con làm tới khuya', 'bài về nhà khó quá, bố mẹ cũng phải tra cứu'],
           's': ['bài về nhà nhiều quá trời, em làm tới mười giờ', 'bài về nhà có câu khó, em ngồi khóc luôn']},
      pos={'p': ['bài về nhà vừa sức, con tự làm được', 'bài tập ít mà trúng trọng tâm', 'bài về nhà có hướng dẫn, bố mẹ kèm cũng dễ'],
           's': ['bài về nhà vừa đủ, em còn thời gian chơi', 'bài về nhà dễ hiểu, em làm một mình được']},
      word=('Bài nhiều.', 'Bài vừa sức.')),
    A('patience', ('school',), 'Kiên nhẫn', 'giáo viên hơi gắt', topic='people', subjective=True,
      neg={'p': ['con hỏi lại lần hai thì cô/thầy hơi gắt', 'con kể cô/thầy hay thở dài khi bạn trả lời sai'],
           's': ['em hỏi lại mà cô/thầy nói "nãy giảng rồi"', 'bạn trả lời sai là cô/thầy nhăn mặt, em sợ không dám hỏi'],
           'o': ['đôi lúc hơi nóng khi học sinh hỏi lại']},
      pos={'p': ['con hỏi mấy lần cô/thầy vẫn kiên nhẫn giảng lại', 'cô/thầy không bao giờ quát, con thích lắm', 'con làm sai mà cô/thầy vẫn động viên'],
           's': ['em hỏi hoài mà cô/thầy vẫn cười giảng lại', 'cô/thầy không quát ai bao giờ', 'em làm sai mà cô/thầy bảo "không sao, thử lại nha"'],
           'o': ['kiên nhẫn với từng em, không nóng nảy']},
      sarc=['cô/thầy kiên nhẫn lắm, kiên nhẫn được đúng một lần giảng 🙂'],
      word=('Hơi gắt.', 'Kiên nhẫn.'), sig_neg=('crit:care:lo',), sig_pos=('crit:care:hi',)),
    A('fairness', ('school',), 'Công bằng', 'thiên vị', topic='people', subjective=True,
      neg={'p': ['con bảo cô/thầy hay gọi mấy bạn giỏi lên bảng, con giơ tay mãi không được gọi', 'hình như cô/thầy hơi thiên vị mấy bạn ngồi bàn đầu'],
           's': ['cô/thầy toàn gọi mấy bạn bàn đầu', 'bạn lớp trưởng làm sai mà không bị nhắc']},
      pos={'p': ['cô/thầy gọi đều cả lớp, bạn nào cũng được lên bảng', 'khen chê công bằng, con thấy phục'],
           's': ['bạn nào cô/thầy cũng gọi, công bằng lắm', 'cô/thầy khen cả bạn học chưa giỏi, bạn ấy vui lắm'],
           'o': ['đối xử công bằng, không thiên vị em nào']},
      word=('Thiên vị.', 'Công bằng.')),
    A('shy_kids', ('school',), 'Với bạn nhút nhát', 'con nhút nhát không được để ý', topic='people', subjective=True,
      neg={'p': ['con hơi nhút nhát, ngồi cuối lớp cả buổi không ai hỏi han', 'con ít nói nên hình như cô/thầy chưa để ý tới con'],
           's': ['em ngồi cuối lớp, cô/thầy ít khi xuống chỗ em']},
      pos={'p': ['con nhà tôi nhút nhát mà được cô/thầy động viên, giờ dám giơ tay', 'cô/thầy để ý cả bạn ít nói, con thấy được quan tâm'],
           's': ['em hay ngại mà cô/thầy xuống tận bàn hỏi nhỏ, em thích lắm', 'cô/thầy khen em trước lớp, em vui cả ngày'],
           'o': ['để ý cả những em ít nói, rất tinh tế']},
      word=('Bị bỏ quên.', 'Được quan tâm.'), sig_neg=('crit:care:lo',), sig_pos=('crit:care:hi', 'crit:feedback:hi')),
    A('parent_chat', ('school',), 'Liên lạc với phụ huynh', 'trả lời phụ huynh chậm', topic='comms', subjective=True,
      neg={'p': ['nhắn nhóm Zalo lớp từ chiều mà tối mới thấy trả lời', 'thông báo lịch học gửi sát giờ, phụ huynh trở tay không kịp',
                 'hỏi tình hình con mà chỉ được trả lời "con ổn ạ"']},
      pos={'p': ['cô/thầy nhắn Zalo rõ ràng, có cả hình con trong lớp', 'hỏi gì trong nhóm lớp cũng được trả lời lịch sự',
                 'cuối tuần nào cô/thầy cũng nhắn tình hình từng bạn']},
      word=('Trả lời chậm.', 'Liên lạc kỹ.'), sig_neg=('crit:feedback:lo',), sig_pos=('crit:feedback:hi',)),
    A('class_time', ('school',), 'Giờ giấc', 'tan lớp muộn', topic='speed',
      neg={'p': ['lớp tan muộn mười phút, phụ huynh đứng chờ ngoài cổng', 'hôm nay tan trễ, tôi lỡ cả giờ làm'],
           's': ['cô/thầy cho ra chơi trễ, em chưa kịp ăn quà', 'tan học trễ, mẹ em chờ ngoài cổng'],
           'o': ['tiết học kéo dài quá giờ']},
      pos={'p': ['vào lớp và tan lớp đúng giờ, phụ huynh dễ sắp xếp', 'lịch học báo trước rõ ràng, không đổi đột xuất'],
           's': ['ra về đúng giờ, không bị dạy lố', 'giờ ra chơi đúng giờ, không bị cắt'],
           'o': ['giữ giờ lên lớp rất chuẩn']},
      word=('Trễ giờ.', 'Đúng giờ.'), sig_neg=('overtime',)),
    A('t_voice', ('school',), 'Giọng giảng', 'giảng nhỏ khó nghe', topic='people', subjective=True,
      neg={'p': ['con ngồi cuối kể không nghe rõ cô/thầy giảng', 'con bảo cô/thầy nói đều đều, nghe dễ buồn ngủ'],
           's': ['ngồi cuối lớp em nghe không rõ', 'cô/thầy nói đều đều, em nghe mà díp mắt']},
      pos={'p': ['giọng cô/thầy truyền cảm, con về còn bắt chước', 'con bảo cô/thầy đọc thơ hay lắm'],
           's': ['giọng cô/thầy hay như đọc truyện', 'cô/thầy nói to rõ, ngồi cuối vẫn nghe'],
           'o': ['giọng giảng truyền cảm, lôi cuốn']},
      word=('Nói nhỏ.', 'Giọng hay.')),
    A('classroom', ('school',), 'Lớp gọn gàng', 'lớp ồn và bừa', topic='clean',
      neg={'p': ['lớp hơi bừa, cặp sách để lung tung dưới gầm', 'con kể lớp ồn, bàn cuối nói chuyện suốt'],
           's': ['lớp ồn quá, bàn cuối nói chuyện suốt', 'góc lớp để đồ lộn xộn, tìm vở mãi không ra'],
           'o': ['nề nếp lớp còn lỏng, học sinh hay mất trật tự']},
      pos={'p': ['lớp gọn gàng, góc nào cũng có bảng tên', 'con kể lớp có nề nếp, ai cũng xếp hàng ngay ngắn'],
           's': ['lớp gọn, có góc đọc sách xịn', 'lớp ngăn nắp, em thích ngồi học'],
           'o': ['lớp có nề nếp, góc học tập gọn gàng']},
      word=('Lớp ồn.', 'Nề nếp.'), sig_neg=('crit:order:lo', 'messy'), sig_pos=('crit:order:hi',)),
    A('marking', ('school',), 'Nhận xét bài', 'bài không có lời nhận xét', topic='comms',
      neg={'p': ['bài của con chỉ có điểm, không có lời nhận xét', 'vở con chấm xong mà không biết sai ở đâu'],
           's': ['bài em chỉ có điểm, không biết mình sai chỗ nào']},
      pos={'p': ['bài của con có lời phê chi tiết, chỉ rõ chỗ sai', 'cô/thầy phê vào vở từng chỗ cần sửa, con đọc kỹ lắm'],
           's': ['cô/thầy phê vào vở dài cả đoạn, em đọc mà vui', 'bài em có lời khen riêng, em khoe cả nhà'],
           'o': ['nhận xét bài chi tiết, học sinh biết mình cần sửa gì']},
      word=('Chỉ có điểm.', 'Phê kỹ.'), sig_neg=('crit:feedback:lo',), sig_pos=('crit:feedback:hi',)),
    A('t_dress', ('school',), 'Tác phong đứng lớp', 'giáo viên ăn mặc xuề xòa', topic='dress', subjective=True,
      neg={'p': ['cô/thầy mặc hơi xuề xòa lúc đứng đón học sinh'], 'o': ['trang phục lên lớp còn hơi tùy tiện']},
      pos={'p': ['cô/thầy ăn mặc chỉn chu, tác phong đứng lớp nghiêm túc', 'cô/thầy lúc nào cũng gọn gàng, con bảo muốn giống cô/thầy'],
           's': ['cô/thầy ăn mặc đẹp, gọn gàng'], 'o': ['tác phong đứng lớp chuẩn mực']},
      word=('Xuề xòa.', 'Chỉn chu.')),
    A('greeting', ('school',), 'Ấm áp với học trò', '', topic='people',
      pos={'p': ['sáng nào cô/thầy cũng đứng cửa lớp chào từng bạn', 'con ốm nghỉ một hôm mà cô/thầy nhắn hỏi thăm'],
           's': ['cô/thầy nhớ sinh nhật em luôn', 'sáng nào cô/thầy cũng chào em bằng tên'],
           'o': ['học sinh quý lắm, ra chơi cứ quây quanh']},
      word=('', 'Ấm áp.'), sig_pos=('regular', 'crit:feedback:hi')),
    # ================================================================ OFFICE DESKS
    A('dress', ('office',), 'Ăn mặc', 'ăn mặc luộm thuộm lên văn phòng', topic='dress', skip=('customer_care',), subjective=True,
      neg=['{nho} mới vào mà đi dép lê lên văn phòng', '{nho} mặc đồ luộm thuộm, áo sơ mi không ủi, nhìn như mới ngủ dậy',
           'ăn mặc như đi chợ, gặp khách mà không chỉnh tề', 'áo nhăn, quần lửng, gặp đối tác thấy hơi ngại',
           '{nho} mặc đồ xấu, áo phông in chữ to đùng lên họp'],
      pos=['ăn mặc gọn gàng, áo sơ mi ủi phẳng phiu', 'tác phong chỉn chu, gặp khách rất ra dáng', 'đồ công sở gọn gàng, nhìn là thấy chuyên nghiệp',
           'hôm gặp kiểm toán còn mặc vest, chu đáo ghê'],
      sarc=['bộ đồ hôm nay rất "thoải mái", tưởng đang đi dạo công viên 👏', 'dép lê lên văn phòng, phong cách tiên phong ghê 🙂'],
      word=('Dép lê?', 'Chỉn chu.')),
    A('attitude', ('office',), 'Thái độ', 'thái độ khó ưa', topic='people', subjective=True,
      neg={'*': ['{nho} khó ưa, hỏi gì cũng trả lời cộc lốc', '{nho} nói chuyện kiểu bề trên, khó ưa ghê', 'nhờ việc gì cũng thở dài, làm như ban ơn',
                 '{nho} mặt lạnh tanh, chào cũng không chào lại'],
           'customer_care': ['bạn tổng đài giọng khó ưa, như đang bực ai', 'nói chuyện cộc lốc, hỏi thêm câu là muốn cúp máy']},
      pos={'*': ['nhờ gì cũng vui vẻ giúp, không kể công', 'nói chuyện lễ phép, nhẹ nhàng, dễ làm việc chung', 'hỏi gì cũng giải thích tới nơi, không cáu'],
           'customer_care': ['giọng tổng đài vui vẻ, kiên nhẫn nghe hết', 'bạn tổng đài dễ thương, xin lỗi rất thật lòng']},
      sarc=['thái độ rất "chuyên nghiệp", chuyên nghiệp tới mức không ai dám hỏi lần hai 👏'],
      word=('Khó ưa.', 'Dễ mến.'), sig_neg=('crit:attitude:lo',), sig_pos=('crit:attitude:hi', 'regular')),
    A('email', ('office',), 'Email và tin nhắn', 'email cụt lủn', topic='comms', subjective=True,
      neg=['email trả lời cụt lủn, không chào không ký tên', 'nhắn tin công việc toàn viết tắt, đọc phải đoán', 'gửi file mà không ghi tên, không nói file gì'],
      pos=['email rõ ràng, có đầu có đuôi, đính kèm đủ', 'tin nhắn gọn, đúng việc, đọc là hiểu', 'gửi file có ghi chú từng sheet, dễ theo dõi'],
      word=('Cụt lủn.', 'Rõ ràng.'), sig_neg=('crit:handover:lo', 'crit:clarity:lo'), sig_pos=('crit:handover:hi', 'crit:clarity:hi')),
    A('o_time', ('office',), 'Đúng giờ, đúng hạn', 'trễ hạn', topic='speed', skip=('customer_care',),
      neg=['hẹn chín giờ gửi số liệu mà gần trưa mới có', 'họp trễ mười phút, cả phòng ngồi chờ', 'deadline nào cũng sát nút, làm người khác đứng tim'],
      pos=['hẹn giờ nào gửi đúng giờ đó', 'deadline nào cũng xong sớm', 'họp luôn có mặt trước, chuẩn bị sẵn tài liệu'],
      word=('Trễ hạn.', 'Đúng hạn.'), sig_neg=('crit:speed:lo', 'slow', 'overtime'), sig_pos=('crit:speed:hi', 'quick')),
    A('desk', ('office',), 'Bàn làm việc', 'bàn làm việc bừa bộn', topic='clean', skip=('customer_care',),
      neg=['bàn làm việc chất giấy tờ như núi, tìm hóa đơn mãi không thấy', 'bàn bừa bộn, ly cà phê để sát chứng từ'],
      pos=['bàn làm việc gọn, hồ sơ dán nhãn từng ngăn', 'giấy tờ kẹp theo tháng, cần là rút ra liền', 'bàn gọn, chứng từ nào để chỗ nấy'],
      word=('Bừa bộn.', 'Gọn gàng.'), sig_neg=('messy',)),
    A('pickup', ('office',), 'Nghe máy', 'gọi không bắt máy', topic='comms', subjective=True,
      neg={'*': ['gọi ba cuộc không bắt máy, cũng không gọi lại', 'nghe máy mà không xưng tên, không chào'],
           'customer_care': ['chờ máy nghe nhạc chờ mòn mỏi', 'bị chuyển máy ba lần, lần nào cũng phải kể lại từ đầu']},
      pos={'*': ['gọi là bắt máy, lỡ cuộc thì gọi lại ngay', 'nghe máy chào hỏi đàng hoàng, xưng tên rõ'],
           'customer_care': ['không phải chờ máy lâu, gặp người thật liền', 'không bắt kể lại, bạn đọc lịch sử là nắm hết']},
      word=('Không bắt máy.', 'Bắt máy liền.'), sig_neg=('slow',), sig_pos=('quick',)),
    A('selfreliant', ('office',), 'Tự xoay xở', 'việc gì cũng hỏi', topic='people', skip=('customer_care',),
      neg=['việc gì cũng chạy đi hỏi, tự xử lý chưa được', 'nhờ người khác làm hộ phần của mình'],
      pos=['tự tìm hiểu, không làm phiền ai', 'thấy người khác kẹt việc là xắn tay vào giúp', 'chỉ tận tình cho người mới, không giấu nghề'],
      word=('Hỏi suốt.', 'Tự lực.'), sig_neg=('crit:independence:lo',), sig_pos=('crit:independence:hi',)),
    A('explain', ('office',), 'Giải thích số liệu', 'giải thích vòng vo', topic='comms',
      neg=['hỏi số liệu thì giải thích vòng vo, nghe nhức đầu', 'hỏi căn cứ thì bảo "em làm theo mẫu"'],
      pos=['giải thích từng con số, có nguồn kèm theo', 'hỏi tới đâu trả lời tới đó, có chứng từ đàng hoàng'],
      word=('Vòng vo.', 'Có căn cứ.'), sig_neg=('crit:grounds:lo', 'crit:evidence:lo', 'crit:clarity:lo'),
      sig_pos=('crit:grounds:hi', 'crit:evidence:hi', 'crit:clarity:hi')),
    A('careful', ('office',), 'Cẩn thận số liệu', 'số liệu sai lặt vặt', topic='method',
      neg=['bảng tính sai lặt vặt, phải soát lại từng dòng', 'gõ nhầm số tài khoản, may mà người khác phát hiện'],
      pos=['số liệu chuẩn, soát lại không sai một đồng', 'tinh mắt, bắt được lỗi người khác bỏ sót'],
      word=('Ẩu.', 'Chuẩn.'), sig_neg=('crit:accuracy:lo', 'crit:vigilance:lo'), sig_pos=('crit:vigilance:hi',)),
    A('meeting', ('office',), 'Trong cuộc họp', 'họp mà lướt điện thoại', topic='people', skip=('customer_care',), subjective=True,
      neg=['họp mà cứ cầm điện thoại lướt', 'họp không ghi chép, xong hỏi lại từ đầu'],
      pos=['họp ghi chép cẩn thận, hỏi đúng trọng tâm', 'trình bày ngắn gọn, ai nghe cũng hiểu'],
      word=('Lơ đãng.', 'Tập trung.')),
    A('greet', ('office',), 'Chào hỏi', 'không chào ai', topic='people', skip=('customer_care',), subjective=True,
      neg=['sáng vào phòng không chào ai, cắm mặt vào máy', 'gặp sếp trong thang máy cũng không chào'],
      pos=['sáng nào cũng chào cả phòng, không khí vui hẳn', 'lễ phép với cả bác bảo vệ, cô lao công'],
      word=('Không chào.', 'Lễ phép.'), sig_pos=('regular',)),
    A('cc_voice', ('office',), 'Giọng tổng đài', 'nói nhanh khó nghe', topic='people', only=('customer_care',), subjective=True,
      neg=['bạn tổng đài nói nhanh quá, nghe không kịp', 'đọc kịch bản như máy, không nghe mình nói'],
      pos=['giọng tổng đài rõ ràng, nói chậm vừa phải', 'nghe mình kể hết rồi mới trả lời, không cắt ngang'],
      word=('Nói nhanh.', 'Nói rõ.')),
    A('cc_empathy', ('office',), 'Đồng cảm', 'trả lời như văn mẫu', topic='comms', only=('customer_care',), subjective=True,
      neg=['nghe mình kể bức xúc mà trả lời như đọc văn mẫu', 'mình đang bực mà bạn cứ "dạ quý khách vui lòng" hoài'],
      pos=['bạn tổng đài nói "em hiểu, chuyện này bực thật", nghe mà nguôi giận', 'được xin lỗi thật lòng chứ không phải câu cho có'],
      word=('Văn mẫu.', 'Thấu hiểu.')),
    A('cc_followup', ('office',), 'Gọi lại báo kết quả', 'hứa gọi lại mà không gọi', topic='speed', only=('customer_care',),
      neg=['hứa gọi lại mà chờ cả ngày không thấy', 'phải tự gọi hỏi lại mới biết đã xử lý tới đâu'],
      pos=['hẹn gọi lại là gọi lại thật, báo kết quả rõ ràng', 'xử lý xong còn nhắn tin xác nhận, yên tâm ghê'],
      word=('Bặt tin.', 'Gọi lại đúng hẹn.'), sig_neg=('crit:resolution:lo',), sig_pos=('crit:resolution:hi',)),
))

# How a reviewer frames one aspect clause ({x}) by persona and polarity. {X}: capitalised.
WRAP = {
    'sour': dict(neg=['Còn {x}, nói thật là hơi quá.', 'À, {x}. Quán tự xem lại.', 'Chưa kể {x}.', '{X}, vậy mà cũng mở cửa đón khách.'],
                 pos=['Được cái {x}, công nhận.', '{X}, cái này thì không chê.'], mix=['{X}. Khen chê cho công bằng.', '{X}, thế đấy.']),
    'bossy': dict(neg=['{X}. Tôi nói thật, cái này phải sửa.', 'Góp ý thêm: {x}, làm nghề phải để ý.', '{X}, hồi xưa tôi mà thấy là nhắc liền.'],
                  pos=['{X}, đúng như tôi vẫn dạy.', 'Được cái {x}, giữ lấy.'], mix=['{X}. Nghe tôi thì sửa nốt chỗ kia.']),
    'warm': dict(neg=['Có điều {x} xíu thôi nha.', 'Chỉ tiếc là {x}, lần sau chắc ổn hơn.', 'Góp ý nhỏ nè: {x}.'],
                 pos=['{X} nè 💛', 'Thích nhất là {x}.', 'Còn {x} nữa, dễ thương ghê.'], mix=['{X} nha 💛', '{X}, nói chung vẫn thương quán.']),
    'picky': dict(neg=['Ghi chú: {x}.', 'Điểm trừ: {x}.', 'Cần xem lại: {x}.'], pos=['Điểm cộng: {x}.', 'Ghi nhận: {x}.'],
                  mix=['Ghi chú thêm: {x}.']),
    'genz': dict(neg=['{x} nha 😵', 'ủa {x} là sao z 🥲', 'mỗi tội {x} 😮‍💨'], pos=['{x} á ✨', '{x}, mê ghê 🫶', 'chấm điểm cộng vì {x} 💯'],
                 mix=['{x} nha 🤧', '{x} 🙃']),
    'quiet': dict(neg=['{X}.'], pos=['{X}.'], mix=['{X}.']),
    'knowitall': dict(neg=['{X}. Anh làm nghề mười năm, nhìn là thấy.', 'Anh chỉ cho: {x}, sửa ngay.', '{X}, cái này thực tập sinh cũng biết em ạ.'],
                      pos=['{X}, đúng kiểu anh hay dạy.', 'Tạm được: {x}.'], mix=['{X}. Anh nói vậy thôi, tự hiểu.']),
    'rude': dict(neg=['{X}. Chán.', '{X}. Thế thôi.', 'Còn {x}. Khỏi nói.'], pos=['{X}. Được.', 'Được mỗi {x}.'], mix=['{X}. Vậy đó.']),
    'entitled': dict(neg=['{X}, khách như tôi không chịu được.', '{X}. Với khách quen thì không được phép.'],
                     pos=['{X}, vậy mới xứng với khách như tôi.'], mix=['{X}. Lần sau nhớ ưu tiên tôi.']),
    'drama': dict(neg=['{X}, mình chụp lại rồi nha 📸', '{X}, lên group là bão đó.'], pos=['{X}, cái này thì công nhận.'],
                  mix=['{X}. Ảnh mình còn giữ đó nha 📸']),
    'troll': dict(neg=['{X}, chắc vậy.', 'Hình như {x}.'], pos=['{X}, chắc thế.'], mix=['{X}, đại loại vậy.']),
    # parents (teacher reviews, voice 'p')
    'parent_worried': dict(neg=['Tôi hơi lo vì {x}.', 'Gia đình băn khoăn: {x}.'], pos=['Tôi yên tâm vì {x}.', '{X}, gia đình yên tâm hơn ạ.'],
                           mix=['{X}. Tôi vẫn hơi lo ạ.']),
    'parent_strict': dict(neg=['Ngoài ra, {x}. Tôi đề nghị giáo viên xem lại.', '{X}. Tôi cần câu trả lời.'], pos=['{X}, tôi ghi nhận.'],
                          mix=['{X}. Tôi sẽ tiếp tục theo dõi.']),
    'parent_kind': dict(neg=['Có điều {x}, mong cô/thầy để ý giúp ạ.', 'Gia đình góp ý nhỏ: {x} ạ.'], pos=['{X}, gia đình cảm ơn ạ.', '{X} ạ 💐'],
                        mix=['{X}, gia đình cảm ơn cô/thầy ạ.']),
    'parent_knowitall': dict(neg=['{X}. Tôi cũng từng đứng lớp, chuyện này phải sửa.', '{X}, cô/thầy nên tham khảo cách của tôi.'],
                             pos=['{X}, đúng phương pháp tôi vẫn đọc.'], mix=['{X}. Tôi góp ý vậy thôi.']),
    'parent_rude': dict(neg=['{X}. Thế mà cũng dạy.', '{X}. Trả lời đi.'], pos=['{X}. Được.'], mix=['{X}. Vậy thôi.']),
}
# Teacher reviews by a student or a colleague (voice 's' / 'o').
VOICE_WRAP = {
    's': dict(neg=['{X} 😥', 'Nói thật là {x}.', 'Hơi buồn vì {x}.'], pos=['{X} 🥰', 'Thích nhất là {x}.', '{X}, em thích lắm.'],
              mix=['{X} 😅']),
    'o': dict(neg=['Góp ý nhỏ: {x}.', 'Dự giờ thấy {x}.'], pos=['{X}, đáng học hỏi.', 'Dự giờ thấy {x}.'], mix=['Dự giờ thấy {x}.']),
}
# Regulars say it with the weight of many visits.
REGULAR_WRAP = dict(neg=['Khách quen nên nói thật: {x}.', 'Ghé mấy lần rồi, lần này thấy {x}.'],
                    pos=['Ghé hoài vẫn thấy {x}.', 'Khách quen xác nhận: {x}.'])
# Two aspects in one sentence.
COMBO = dict(mix=['{pos}, mà {neg}', '{pos}, có điều {neg}', '{neg}, bù lại {pos}', '{pos}, tiếc là {neg}'],
             neg=['{a}, lại còn {b}', '{a}, thêm cái {b}', '{a}; chưa hết, {b}'],
             pos=['{a}, {b} nữa', '{a}, lại còn {b}', '{a}, thêm cái {b}'])
# Styled reviews (feedback_voices.style_review) that take one more line, and how.
STYLE_WRAP = {
    'teencode': dict(neg=['mà {x} nha 😶', 'nma {x} 🥲'], pos=['{x} nữa ✨', 'thêm điểm vì {x} 🫶'], mix=['{x} 🙃']),
    'rant': dict(neg=['À quên, còn chuyện {x}.', 'Nói thêm cho đủ: {x}.'], pos=['À, phải kể thêm là {x}.', 'Còn một điểm cộng: {x}.'],
                 mix=['Tiện nói luôn: {x}.']),
    'p_long': dict(neg=['Thêm một chuyện nữa: {x}.'], pos=['Gia đình cũng muốn kể thêm là {x}.'], mix=['Thêm nữa: {x}.']),
    'regular': dict(neg=['Mà {x} nha, khách quen mới dám nói.'], pos=['Lần nào cũng thấy {x}.'], mix=['Khách quen góp ý: {x}.']),
    'sarcastic': dict(neg=['Chưa kể {x}. Hay lắm 👏'], pos=['Được mỗi {x}.'], mix=['{X}. Hay lắm 👏']),
}

# How reviewers call the people involved (gender-aware; neutral when unknown).
NV = {'polite': {'male': 'anh nhân viên', 'female': 'chị nhân viên', None: 'bạn nhân viên'},
      'harsh': {'male': 'thằng nhỏ đứng quầy', 'female': 'con nhỏ đứng quầy', None: 'bạn đứng quầy'}}
NV_FAM = {'service': {'polite': {'male': 'anh thợ', 'female': 'chị thợ', None: 'bạn thợ'},
                      'harsh': {'male': 'thằng nhỏ thợ phụ', 'female': 'con nhỏ thợ phụ', None: 'bạn thợ phụ'}}}
NV_CAREER = {'tour_guide': {'polite': {'male': 'anh hướng dẫn viên', 'female': 'chị hướng dẫn viên', None: 'hướng dẫn viên'},
                            'harsh': {'male': 'anh hướng dẫn viên', 'female': 'chị hướng dẫn viên', None: 'hướng dẫn viên'}},
             'farm': {'polite': {'male': 'anh bán hàng', 'female': 'chị bán hàng', None: 'người bán'},
                      'harsh': {'male': 'thằng nhỏ bán hàng', 'female': 'con nhỏ bán hàng', None: 'người bán'}},
             'delivery': {'polite': {'male': 'anh shipper', 'female': 'chị shipper', None: 'shipper'},
                          'harsh': {'male': 'thằng nhỏ shipper', 'female': 'con nhỏ shipper', None: 'shipper'}},
'homestay': {'polite': {'male': 'anh chủ nhà', 'female': 'chị chủ nhà', None: 'chủ nhà'},
                          'harsh': {'male': 'anh chủ nhà', 'female': 'chị chủ nhà', None: 'chủ nhà'}},
             'pet_care': {'polite': {'male': 'anh chăm bé', 'female': 'chị chăm bé', None: 'bạn chăm bé'},
                          'harsh': {'male': 'thằng nhỏ chăm bé', 'female': 'con nhỏ chăm bé', None: 'bạn chăm bé'}}}
NHO = {'polite': {'male': 'cậu ấy', 'female': 'em ấy', None: 'bạn ấy'},
       'harsh': {'male': 'thằng nhỏ', 'female': 'con nhỏ', None: 'bạn đó'}}

# Owner replies once a reviewer drops a star over an aspect nobody recorded (merged into feedback.TWIST_REPLY).
REPLY = {
    'aspect_soft': ['Ừ, chắc hôm đó tôi gặp đúng lúc chưa kịp dọn. Thấy trả lời đàng hoàng, tôi trả lại sao.',
                    'Có sổ ghi rõ vậy thì tôi tin. Chắc tôi hơi khắt khe, sửa sao nhé.',
                    'Ờ, cảm nhận riêng của tôi thôi, phần chính làm tốt thật. Trả lại sao.',
                    'Nghe giải thích cũng hợp lý. Lần sau tôi để ý lại rồi hẵng chê, sửa sao nè.'],
    'aspect_soft_parent': ['Vâng, có lẽ con kể chưa đủ ý. Cảm ơn cô/thầy đã giải thích, gia đình sửa lại đánh giá ạ.',
                           'Nghe cô/thầy nói rõ, tôi thấy mình hơi vội kết luận. Tôi sửa lại ạ.'],
}
LABEL = 'Góp ý theo cảm nhận'
CLUE = 'Chê một chuyện không có trong ghi nhận'
TRUTH = 'không có ghi nhận nào về chuyện này hôm đó; phần việc chính làm đúng'
SITUATION = ('Bạn trừ một sao vì một góc cụ thể (unfair_claim.claim) theo cảm nhận riêng; không có ghi nhận nào xác nhận chuyện đó, '
             'phần việc chính làm tốt. Nếu chủ quán/giáo viên trả lời lịch sự, đưa sự thật hoặc cách họ kiểm tra (lịch dọn, quy trình), '
             'bạn chấp nhận và trả lại sao; nếu bị cãi hoặc mỉa, bạn giữ ý kiến, xéo xắt nhưng không tục.')

# ------------------------------------------------------------------ safety
# Phrases never allowed in a review (scripted or AI): bodies and looks, age, region, religion,
# sexual content, real chains and brands. Attitude and clothing jabs are fine.
UNSAFE = (
    r'b[ée]o (ú|phì|ị|như)', r'mập(?! mờ)', r'l[ùu]n (tịt|xủn|như)', r'xấu (xí|trai|gái|người)', r'mặt (xấu|mụn|rỗ)', r'răng hô', r'đen nhẻm',
    r'gầy (nhom|trơ)', r'bụng (bự|phệ)', r'vòng (một|ba)', r'dáng người', r'gợi cảm', r'hở hang', r'sexy', r'body',
    r'già (khú|chát|háp)', r'gái già', r'bà già', r'ông già', r'nhà quê', r'quê mùa', r'bắc kỳ', r'nam kỳ', r'trung kỳ', r'parky',
    r'dân tỉnh lẻ', r'đồ mọi', r'mọi rợ', r'theo đạo', r'công giáo', r'phật tử', r'thiểu năng', r'tàn tật', r'pê đê', r'bóng lộ',
    r'đồng tính', r'khuyết tật', r'da (đen|màu)',
    r'starbucks', r'highlands?', r'phúc long', r'trung nguyên', r'katinat', r'cộng cà phê', r'gong ?cha', r'tocotoco', r'circle ?k',
    r'gs25', r'7-eleven', r'winmart', r'bách hóa xanh', r'co\.?opmart', r'grab', r'shopee', r'lazada', r'tiki', r'baemin', r'gojek',
    r'pharmacity', r'long châu', r'thế giới di động', r'vinamilk', r'coca(-cola)?', r'pepsi', r'kfc', r'lotteria', r'jollibee',
    r'mcdonald', r'mixue',
)
