"""Authored real-life situations for the v0.3 careers (teacher, tour guide, milk tea).

Plugin careers keep their situations in their own SPEC. Every option shows the
same moment from several sides (customer, staff, bystander, the player), so the
lesson is "people see this differently", not "there is one magic answer".
All people, places and rules are fictional.
"""
from __future__ import annotations


def P(who: str, emoji: str, text: str) -> dict:
    return dict(who=who, emoji=emoji, text=text)


SITUATIONS = [
    # ---------------- Teacher ----------------
    dict(id='T-S01', career='teacher', title='Phụ huynh nhắn lúc 22 giờ', npc=5, tone='tense', min_day=1,
         opening='Cô Lan nhắn tin lúc 22 giờ: “Sao hôm nay con tôi bị ghi tên lên bảng? Cô giải thích ngay cho tôi.”',
         swap='Bạn là phụ huynh vừa nghe con kể một nửa câu chuyện trong bữa tối.',
         facts=[dict(id='log', title='Sổ đầu bài', source='Sổ lớp', text='Sổ ghi: Bảo quên vở bài tập lần thứ ba trong tuần; lớp có quy ước ghi tên để nhắc, không trừ điểm.'),
                dict(id='rule', title='Quy ước lớp', source='Bảng nội quy đầu năm', text='Quy ước đã gửi phụ huynh ký đầu năm: ghi tên nhắc nhở, ba lần thì trao đổi với gia đình.'),
                dict(id='child', title='Lời Bảo kể', source='Trò chuyện giờ ra chơi', text='Bảo nói: “Tối nào con cũng trông em nên quên xếp cặp.”')],
         options=[dict(id='boundary', label='Hẹn trao đổi sáng mai trong giờ hành chính, kèm sổ lớp', requires=['log'], quality='good', stars=5,
                       review='Cô giáo hẹn gặp đúng giờ, có sổ ghi rõ ràng. Tôi hiểu chuyện hơn rồi.',
                       outcome='Sáng hôm sau cô Lan tới, đọc sổ và quy ước. Hai bên thống nhất cách nhắc Bảo xếp cặp từ tối.',
                       perspectives=[P('Cô Lan (phụ huynh)', '🤝', 'Tối qua tôi nóng quá. Nhưng cô giáo không cãi, hẹn gặp và cho xem sổ, tôi thấy được tôn trọng.'),
                                     P('Bảo', '🎒', 'Con sợ bị mắng, nhưng cô với mẹ lại cùng làm cho con cái lịch xếp cặp.'),
                                     P('Cô Hạ (đồng nghiệp)', '👩‍🏫', 'Giữ ranh giới giờ nhắn tin không phải là lạnh lùng, mà để mình trả lời tỉnh táo hơn.')]),
                  dict(id='reply_now', label='Trả lời ngay trong đêm và giải thích dài', quality='ok',
                       outcome='Cô Lan đọc xong nhưng hỏi thêm năm câu nữa tới gần nửa đêm. Sáng ra bạn mệt và lớp học kém tập trung.',
                       perspectives=[P('Cô Lan (phụ huynh)', '😟', 'Cô trả lời nhanh nên tôi bớt lo, nhưng tôi vẫn chưa hiểu con cần gì.'),
                                     P('Bạn (giáo viên)', '🌙', 'Mình muốn xoa dịu ngay, nhưng tin nhắn đêm khuya khó nói hết chuyện.')]),
                  dict(id='understand', label='Hỏi thêm hoàn cảnh ở nhà, đề xuất nhắc bằng sổ liên lạc', requires=['child', 'rule'], quality='good', stars=5,
                       review='Cô giáo biết chuyện nhà tôi mà không trách con. Cảm ơn cô.',
                       outcome='Bạn nhắn ngắn: hẹn gặp sáng mai, đề nghị dùng sổ liên lạc thay vì ghi tên. Cô Lan đồng ý và cảm ơn.',
                       perspectives=[P('Cô Lan (phụ huynh)', '🥹', 'Tôi không biết con vừa trông em vừa phải tự xếp cặp. Tôi sẽ đổi lịch ở nhà.'),
                                     P('Bảo', '😊', 'Cô không kể chuyện nhà con cho cả lớp. Con thấy nhẹ nhõm.')]),
                  dict(id='ignore', label='Không trả lời, để mai tính', quality='bad', stars=2,
                       review='Nhắn cô giáo không ai trả lời. Tôi sẽ hỏi ban giám hiệu.',
                       outcome='Sáng hôm sau cô Lan lên thẳng phòng hiệu trưởng. Chuyện nhỏ thành một cuộc họp căng thẳng.',
                       perspectives=[P('Cô Lan (phụ huynh)', '😤', 'Tôi chỉ cần một dòng “mai mình nói chuyện nhé”. Im lặng làm tôi nghĩ mọi thứ tệ hơn.'),
                                     P('Hiệu trưởng', '🏫', 'Không cần trả lời đêm khuya, nhưng một lời hẹn ngắn tránh được hiểu lầm lớn.')])],
         lesson='Giữ ranh giới giờ làm việc, nhưng luôn để lại một lời hẹn rõ ràng và đem theo dữ kiện.'),
    dict(id='T-S02', career='teacher', title='Tổ chức Trung thu cho lớp', npc=0, tone='gentle', min_day=2,
         opening='Còn một tuần là Trung thu. Cô Hạ hỏi: “Lớp mình làm gì? Quỹ lớp còn 120 xu, có bạn không mang bánh được đâu.”',
         facts=[dict(id='fund', title='Quỹ lớp', source='Sổ quỹ', text='Quỹ lớp còn 120 xu; hai gia đình đã xin miễn đóng góp tháng này.'),
                dict(id='allergy', title='Phiếu sức khỏe', source='Hồ sơ lớp', text='Vy dị ứng đậu phộng; An không ăn được đồ quá ngọt.'),
                dict(id='wish', title='Hộp mong muốn', source='Hộp thư lớp', text='Nhiều bạn viết: “Muốn làm đèn lồng”, “muốn rước đèn quanh sân”.')],
         options=[dict(id='craft', label='Cả lớp tự làm đèn ông sao, mâm cỗ chung không đậu phộng', requires=['allergy', 'wish'], cost=35, quality='good', stars=5,
                       review='Trung thu của lớp đơn giản mà vui, con tự làm đèn mang về khoe cả nhà!',
                       outcome='Buổi chiều cả lớp dán đèn, rước quanh sân. Mâm cỗ ghi nhãn thành phần, Vy ăn cùng các bạn.',
                       perspectives=[P('Vy', '🏮', 'Lần đầu con ăn cỗ với lớp mà không phải ngồi riêng.'),
                                     P('Phụ huynh', '👪', 'Không phải đóng thêm tiền mà con vẫn có một buổi tối đáng nhớ.'),
                                     P('Cô Hạ', '👩‍🏫', 'Chuẩn bị mất công hơn mua sẵn, nhưng nhìn tụi nhỏ tự hào về chiếc đèn là đủ.')]),
                  dict(id='buy', label='Mua bánh trung thu và đèn làm sẵn cho nhanh', cost=80, quality='ok',
                       outcome='Buổi liên hoan nhanh gọn, nhưng hộp bánh có đậu phộng nên Vy phải ngồi riêng.',
                       perspectives=[P('Vy', '😔', 'Các bạn ăn bánh, con ăn bánh quy mang từ nhà.'),
                                     P('Thủ quỹ phụ huynh', '💰', 'Quỹ gần hết, tháng sau lại phải xin đóng thêm.')]),
                  dict(id='collect', label='Thu thêm mỗi bạn 20 xu để làm hoành tráng', quality='bad', stars=2,
                       review='Liên hoan mà cũng phải đóng thêm, nhà tôi đang khó khăn…',
                       outcome='Hai gia đình ngại không đóng, con họ xin nghỉ buổi liên hoan.',
                       perspectives=[P('Một phụ huynh', '😞', 'Tôi không muốn con thấy mình khác bạn chỉ vì 20 xu.'),
                                     P('Cô Hạ', '👩‍🏫', 'Hoạt động của lớp nên để ai cũng tham gia được.')])],
         lesson='Sự kiện lớp tốt là sự kiện mọi bạn đều có chỗ: hỏi mong muốn, kiểm dị ứng, không đặt gánh nặng tiền lên gia đình.'),
    dict(id='T-S03', career='teacher', title='Sinh nhật bất ngờ cho Minh', npc=1, tone='gentle', min_day=2,
         opening='Cả lớp thì thầm muốn tổ chức sinh nhật bất ngờ cho Minh giờ ra chơi. Nhưng Minh là bạn rất nhút nhát.',
         facts=[dict(id='shy', title='Quan sát của bạn', source='Nhật ký lớp', text='Minh hay đỏ mặt khi bị gọi tên trước lớp; thích vẽ và nói chuyện với nhóm nhỏ.'),
                dict(id='parent', title='Tin nhắn gia đình', source='Sổ liên lạc', text='Mẹ Minh nhắn: “Nhà có bánh nhỏ cho con buổi tối, ở lớp chỉ cần vui nhẹ nhàng thôi ạ.”')],
         options=[dict(id='gentle', label='Cả lớp viết thiệp vẽ tay, tặng trong nhóm nhỏ', requires=['shy'], quality='good', stars=5,
                       review='Con về khoe tập thiệp các bạn vẽ, cả nhà cảm động lắm.',
                       outcome='Minh nhận chồng thiệp trong góc đọc sách, cười rất tươi và vẽ tặng lại cả lớp một bức.',
                       perspectives=[P('Minh', '🎨', 'Con không phải đứng trước lớp mà vẫn biết các bạn nhớ sinh nhật con.'),
                                     P('Các bạn', '✉️', 'Vẽ thiệp vui hơn tụi con tưởng.')]),
                  dict(id='surprise', label='Tắt đèn, hát to và đội mũ sinh nhật cho Minh', quality='ok',
                       outcome='Minh giật mình, bật khóc rồi mới cười. Lớp vui nhưng Minh cần một lúc mới bình tĩnh lại.',
                       perspectives=[P('Minh', '😳', 'Con vui nhưng lúc đèn tắt con sợ lắm.'),
                                     P('Các bạn', '🎉', 'Tụi con tưởng bất ngờ là ai cũng thích.')])],
         lesson='Một buổi mừng tốt nhìn từ phía người được mừng, không chỉ từ người tổ chức.'),
    dict(id='T-S04', career='teacher', title='Hai bạn giành nhau một cây bút', npc=2, tone='gentle', min_day=1,
         opening='Giờ vẽ, An và Bảo giành nhau cây bút màu xanh, An òa khóc: “Bạn ấy lấy của con!”',
         facts=[dict(id='name', title='Tên trên bút', source='Nhìn bút', text='Cây bút có dán tên “Bảo” ở thân.'),
                dict(id='before', title='Bạn ngồi cạnh kể', source='Vy', text='Vy nói: “An mượn từ sáng rồi quên trả, lúc nãy Bảo lấy lại.”')],
         options=[dict(id='listen', label='Cho mỗi bạn kể lượt mình, rồi cùng tìm cách mượn – trả', requires=['name', 'before'], quality='good',
                       outcome='Hai bạn kể lượt mình. An xin lỗi vì quên trả, Bảo cho mượn lại khi mình dùng xong.',
                       perspectives=[P('An', '😢', 'Con quên mất đó là bút của Bảo. Được nói hết con thấy đỡ tủi.'),
                                     P('Bảo', '✏️', 'Cô không mắng con vì lấy lại đồ của con.'),
                                     P('Vy', '👀', 'Con chỉ kể những gì con thấy, cô tin con.')]),
                  dict(id='punish', label='Tịch thu bút, cả hai ra đứng góc lớp', quality='bad',
                       outcome='Hai bạn im lặng suốt tiết, bài vẽ bỏ dở. Bảo về kể với mẹ là bị phạt oan.',
                       perspectives=[P('Bảo', '😠', 'Bút của con mà con cũng bị phạt.'),
                                     P('Phụ huynh Bảo', '📱', 'Tôi mong cô hỏi rõ trước khi phạt.')])],
         lesson='Xung đột nhỏ của trẻ là cơ hội dạy cách kể lượt mình và cách mượn – trả.'),
    dict(id='T-S05', career='teacher', title='Phụ huynh nghi cô chấm điểm thiên vị', npc=5, tone='tense', min_day=3,
         opening='Cô Lan gửi ảnh bài kiểm tra: “Bài con tôi giống bài bạn Vy mà con tôi 7, bạn Vy 9. Cô chấm thiên vị à?”',
         swap='Bạn là phụ huynh đặt hai bài cạnh nhau và chỉ thấy con số.',
         facts=[dict(id='rubric', title='Thang chấm', source='Đáp án tổ chuyên môn', text='Câu 3 yêu cầu trình bày cách làm (2 điểm). Bài của Bảo chỉ ghi đáp số.'),
                dict(id='paper', title='Bài của Bảo', source='Bài gốc', text='Bảo đúng đáp số câu 3 nhưng không ghi bước làm; lời phê của cô ghi rõ “Con ghi thêm cách làm nhé”.'),
                dict(id='privacy', title='Nguyên tắc riêng tư', source='Quy định trường', text='Giáo viên không đưa bài hay điểm của học sinh khác cho phụ huynh xem.')],
         options=[dict(id='explain', label='Giải thích bằng thang chấm và bài của chính Bảo, không nói về bài bạn khác', requires=['rubric', 'paper', 'privacy'], quality='good', stars=5,
                       review='Cô chỉ rõ thang chấm, tôi hiểu con thiếu phần trình bày. Cảm ơn cô.',
                       outcome='Cô Lan đọc thang chấm và lời phê, rồi nhắn: “Tôi hiểu rồi, tối nay tôi nhắc con ghi cách làm.”',
                       perspectives=[P('Cô Lan (phụ huynh)', '😌', 'Tôi chỉ thấy con số, giờ mới thấy lời phê của cô.'),
                                     P('Vy', '🔒', 'Bài của con không bị đem ra so sánh với ai.'),
                                     P('Tổ trưởng chuyên môn', '📋', 'Có thang chấm chung thì giáo viên không phải tự bảo vệ bằng cảm tính.')]),
                  dict(id='compare', label='Gửi ảnh bài của Vy để chứng minh', quality='bad', stars=2,
                       review='Cô giáo đưa bài của con người khác cho tôi xem, vậy bài con tôi cũng bị đưa cho người khác à?',
                       outcome='Cô Lan hết thắc mắc về điểm, nhưng gia đình Vy biết chuyện và phản đối việc lộ bài.',
                       perspectives=[P('Phụ huynh Vy', '😠', 'Bài của con tôi không phải bằng chứng cho chuyện nhà người khác.'),
                                     P('Hiệu trưởng', '🏫', 'Đúng về điểm nhưng sai về quyền riêng tư vẫn là sai.')]),
                  dict(id='raise', label='Nâng điểm Bảo cho êm chuyện', quality='bad', stars=4,
                       review='Cô chịu sửa điểm là tốt.',
                       outcome='Chuyện êm, nhưng tuần sau thêm ba phụ huynh khác nhắn xin nâng điểm.',
                       perspectives=[P('Cô Hạ (đồng nghiệp)', '😬', 'Sửa điểm không theo thang chấm thì lần sau mình lấy gì để giải thích?'),
                                     P('Bảo', '🤔', 'Con vẫn không biết mình sai chỗ nào.')])],
         lesson='Giải thích bằng tiêu chí và bài của chính em đó; không đổi điểm để xoa dịu, không lộ bài bạn khác.'),
    dict(id='T-S06', career='teacher', title='Chuẩn bị ngày 20/11', npc=0, tone='gentle', min_day=4,
         opening='Sắp 20/11. Ban phụ huynh hỏi cô muốn nhận quà gì, còn lớp muốn làm một tiết mục văn nghệ.',
         facts=[dict(id='policy', title='Quy định trường', source='Thông báo trường', text='Trường khuyến khích quà tinh thần; không nhận phong bì hoặc quà giá trị.'),
                dict(id='class', title='Ý kiến lớp', source='Giờ sinh hoạt', text='Lớp muốn hát một bài và làm báo tường; vài bạn ngại lên sân khấu.')],
         options=[dict(id='spirit', label='Cảm ơn ban phụ huynh, đề nghị thay quà bằng thiệp và báo tường; ai ngại hát thì làm hậu cần', requires=['policy', 'class'], quality='good', stars=5,
                       review='Cô từ chối quà rất khéo, các con tự làm báo tường rất vui.',
                       outcome='Báo tường của lớp đạt giải khuyến khích. Bạn nào cũng có việc: hát, vẽ, cắt dán, dẫn chương trình.',
                       perspectives=[P('Ban phụ huynh', '💐', 'Không phải đau đầu chọn quà, lại thấy con tham gia hết.'),
                                     P('Bảo (ngại hát)', '✂️', 'Con làm phần cắt dán, vẫn là của lớp mình.')]),
                  dict(id='accept', label='Nhận phong bì của ban phụ huynh vì “ai cũng làm vậy”', quality='bad', stars=2,
                       review='Nói là tự nguyện mà ai không đóng thì ngại lắm.',
                       outcome='Một phụ huynh phản ánh lên trường. Bạn phải giải trình và trả lại.',
                       perspectives=[P('Một phụ huynh', '😣', 'Tôi không muốn đóng nhưng sợ con bị để ý.'),
                                     P('Hiệu trưởng', '🏫', 'Quy định rõ ràng để bảo vệ cả giáo viên lẫn gia đình.')])],
         lesson='Món quà có ý nghĩa nhất là thứ không đặt áp lực lên ai.'),
    dict(id='T-S07', career='teacher', title='Học sinh ốm giữa giờ học', npc=4, tone='tense', min_day=2,
         opening='Giữa tiết, Bảo ôm bụng, mặt tái đi. Các bạn quay lại nhìn.',
         facts=[dict(id='nurse', title='Quy trình y tế', source='Sổ tay trường', text='Học sinh mệt: đưa xuống phòng y tế, báo gia đình, ghi sổ. Giáo viên không tự cho uống thuốc.'),
                dict(id='class', title='Lớp học', source='Quan sát', text='Lớp còn 15 phút bài kiểm tra; cô Hạ đang dạy phòng bên cạnh.')],
         options=[dict(id='procedure', label='Nhờ cô Hạ trông lớp, đưa Bảo xuống y tế và báo gia đình', requires=['nurse'], quality='good', stars=5,
                       review='Cô gọi cho tôi ngay và đưa con xuống y tế. Tôi rất yên tâm.',
                       outcome='Bảo được nghỉ ở phòng y tế, mẹ tới đón. Bài kiểm tra của lớp vẫn tiếp tục có người trông.',
                       perspectives=[P('Mẹ Bảo', '📞', 'Nhận cuộc gọi đúng lúc, tôi biết con đang được chăm.'),
                                     P('Cô Hạ', '🤝', 'Trông giúp 15 phút là chuyện bình thường giữa đồng nghiệp.'),
                                     P('Cô y tế', '🩺', 'Giáo viên làm đúng: đưa xuống, không tự cho uống gì.')]),
                  dict(id='wait', label='Bảo ngồi nghỉ tại chỗ đến hết giờ kiểm tra', quality='bad', stars=2,
                       review='Con mệt cả tiết mà không ai báo, tới lúc đón tôi mới biết.',
                       outcome='Hết giờ Bảo mới được đưa xuống y tế. Gia đình rất không vui.',
                       perspectives=[P('Bảo', '🤢', 'Con cố ngồi mà không làm bài được.'),
                                     P('Mẹ Bảo', '😟', 'Bài kiểm tra có thể làm lại, sức khỏe của con thì không chờ được.')])],
         lesson='Sức khỏe học sinh đi trước tiến độ bài học; làm theo quy trình, không tự xử lý y tế.'),
    dict(id='T-S08', career='teacher', title='Dã ngoại vườn rau khu phố', npc=0, tone='gentle', min_day=5,
         opening='Lớp được mời dã ngoại ở vườn rau khu phố. Cần giấy đồng ý của phụ huynh và phân công người lớn đi kèm.',
         facts=[dict(id='consent', title='Giấy đồng ý', source='Hộp thư lớp', text='Đã có 3/4 giấy đồng ý; giấy của An chưa về.'),
                dict(id='ratio', title='Tỉ lệ người lớn', source='Quy định dã ngoại', text='Mỗi nhóm tối đa 5 bạn có một người lớn đi kèm.'),
                dict(id='weather', title='Dự báo', source='Bảng tin', text='Chiều có thể mưa rào; vườn có mái che nhỏ.')],
         options=[dict(id='plan', label='Gọi gia đình An xác nhận, chia nhóm có người lớn, mang áo mưa', requires=['consent', 'ratio', 'weather'], cost=10, quality='good', stars=5,
                       review='Chuyến dã ngoại được chuẩn bị kỹ, con về kể say sưa về luống cải.',
                       outcome='Gia đình An gửi xác nhận kịp. Mưa đến lúc 3 giờ, cả lớp trú dưới mái che và chơi đoán tên rau.',
                       perspectives=[P('Mẹ An', '📝', 'May mà cô gọi, tôi quên ký giấy.'),
                                     P('Bác chủ vườn', '👨‍🌾', 'Lớp đi có nhóm, có người lớn, tôi yên tâm cho vào luống.')]),
                  dict(id='go', label='Cứ đi, giấy của An bổ sung sau', quality='bad', stars=2,
                       review='Con tôi đi dã ngoại mà tôi chưa hề ký giấy?',
                       outcome='Chuyến đi vui nhưng gia đình An phản ánh vì không được hỏi ý kiến.',
                       perspectives=[P('Mẹ An', '😠', 'Không phải tôi không cho đi, mà tôi cần được biết.')])],
         lesson='Hoạt động ngoài lớp cần đủ giấy đồng ý, người lớn đi kèm và phương án thời tiết.'),

    # ---------------- Tour guide ----------------
    dict(id='G-S01', career='tour_guide', title='Khách lạc đoàn ở chợ đêm', npc=1, tone='tense', min_day=1,
         opening='Đến giờ tập trung, bác Bình không có mặt. Điện thoại bác không liên lạc được.',
         facts=[dict(id='last', title='Lần cuối thấy', source='Trúc', text='Trúc thấy bác Bình đứng ở sạp gốm cách đây 10 phút.'),
                dict(id='plan', title='Phương án đầu chuyến', source='Bản phổ biến đầu chuyến', text='Đầu chuyến đã dặn: lạc đoàn thì đứng yên ở quầy thông tin gần nhất.'),
                dict(id='group', title='Đoàn', source='Hải', text='Hải có thể giữ đoàn ở điểm hẹn trong 20 phút.')],
         options=[dict(id='system', label='Hải giữ đoàn, bạn tới sạp gốm rồi quầy thông tin', requires=['last', 'plan', 'group'], quality='good', stars=5,
                       review='Tôi lạc mà hướng dẫn viên tìm ra ngay, không làm cả đoàn hoảng.',
                       outcome='Bác Bình đang chờ ở quầy thông tin đúng như dặn đầu chuyến. Cả đoàn chỉ trễ 12 phút.',
                       perspectives=[P('Bác Bình', '👴', 'Tôi mải xem gốm, nhớ lời dặn nên đứng yên ở quầy.'),
                                     P('Cả đoàn', '🧳', 'Có người giữ đoàn, có người đi tìm, ai cũng biết mình phải làm gì.'),
                                     P('Hải (điều phối)', '📋', 'Phổ biến đầu chuyến tưởng thừa, đến lúc cần mới thấy quý.')]),
                  dict(id='all', label='Cả đoàn tản ra đi tìm', quality='bad', stars=2,
                       review='Tìm một người mà lạc thêm hai người, chuyến đi thành hỗn loạn.',
                       outcome='Tìm thấy bác Bình nhưng Nam và Trúc lại lạc nhau. Mất 45 phút mới tập hợp đủ.',
                       perspectives=[P('Nam', '😵', 'Mọi người chạy mỗi hướng, tôi không biết quay về đâu.')])],
         lesson='Khi thiếu người: giữ phần đoàn còn lại, tìm theo dữ kiện, dựa vào điểm hẹn đã phổ biến.'),
    dict(id='G-S02', career='tour_guide', title='Nhà hàng đổi thực đơn phút chót', npc=0, tone='tense', min_day=2,
         opening='Nhà hàng báo hết món cá đã đặt cho đoàn, muốn đổi món gà cùng giá. Linh nhắc trong đoàn có người ăn chay.',
         facts=[dict(id='contract', title='Hợp đồng dịch vụ', source='Phiếu đặt bữa', text='Phiếu ghi: 6 suất cá, 1 suất chay, nhà hàng đổi món phải được trưởng đoàn đồng ý.'),
                dict(id='veg', title='Suất chay', source='Nhà bếp', text='Suất chay vẫn đủ; chỉ món cá bị thiếu.')],
         options=[dict(id='consult', label='Báo trưởng đoàn, đề nghị đổi món kèm bù đồ uống theo phiếu', requires=['contract', 'veg'], quality='good', stars=4,
                       review='Có thay đổi nhưng hướng dẫn viên báo trước và thương lượng được phần bù.',
                       outcome='Linh đồng ý đổi gà, nhà hàng tặng thêm trà. Suất chay vẫn đủ.',
                       perspectives=[P('Linh (trưởng đoàn)', '🗣️', 'Tôi được hỏi trước, không phải ngồi vào bàn mới biết.'),
                                     P('Chủ nhà hàng', '🍽️', 'Nhập cá bị lỗi, tôi cũng muốn giữ khách nên sẵn sàng bù.')]),
                  dict(id='silent', label='Âm thầm đồng ý đổi món', quality='bad', stars=2,
                       review='Đặt cá mà ăn gà, không ai nói một câu.',
                       outcome='Đoàn phát hiện khi món ra. Linh phàn nàn và yêu cầu giảm giá.',
                       perspectives=[P('Linh (trưởng đoàn)', '😒', 'Thay đổi được, nhưng phải hỏi.')])],
         lesson='Thay đổi dịch vụ phải được khách đồng ý và có phương án bù rõ ràng.'),
    dict(id='G-S03', career='tour_guide', title='Khách muốn tách đoàn đi riêng', npc=2, tone='gentle', min_day=2,
         opening='Trúc muốn tách đoàn đi chụp hoàng hôn ở đồi Mây, hẹn gặp lại ở khách sạn.',
         facts=[dict(id='policy', title='Điều khoản tour', source='Hợp đồng', text='Khách có thể tách đoàn nếu ký cam kết tự chịu trách nhiệm và báo giờ về.'),
                dict(id='route', title='Đường lên đồi', source='Bản đồ', text='Đường lên đồi Mây có đèn tới 19 giờ, có xe ôm công nghệ.')],
         options=[dict(id='sign', label='Cho ký giấy tách đoàn, lưu số liên lạc, hẹn giờ báo về', requires=['policy', 'route'], quality='good', stars=5,
                       review='Hướng dẫn viên linh hoạt mà vẫn cẩn thận, tôi có bộ ảnh hoàng hôn đẹp nhất.',
                       outcome='Trúc chụp xong nhắn “đã về” lúc 18:40. Mọi thứ ổn.',
                       perspectives=[P('Trúc', '📸', 'Tôi được tôn trọng sở thích mà không thấy bị bỏ mặc.'),
                                     P('Hải (điều phối)', '📱', 'Có giấy tờ, có giờ báo về thì mình mới yên tâm.')]),
                  dict(id='refuse', label='Từ chối, bắt đi theo đoàn', quality='ok',
                       outcome='Trúc đi theo đoàn nhưng cả buổi tối không vui, đánh giá chuyến đi “cứng nhắc”.',
                       perspectives=[P('Trúc', '😑', 'Tôi là người lớn mà.')])],
         lesson='Linh hoạt đúng quy trình: đồng ý có điều kiện rõ ràng hơn là cấm hẳn hoặc thả nổi.'),
    dict(id='G-S04', career='tour_guide', title='Mưa lớn, điểm tham quan đóng cửa', npc=5, tone='gentle', min_day=3,
         opening='Mưa lớn bất ngờ, Vườn Lá Nhỏ thông báo đóng cửa. Đoàn đã trả tiền vé trọn gói.',
         facts=[dict(id='alt', title='Điểm thay thế', source='Danh sách dự phòng', text='Nhà Gốm Kể Chuyện có mái che, còn chỗ cho đoàn.'),
                dict(id='refund', title='Chính sách vé', source='Hợp đồng', text='Điểm đóng vì thời tiết: hoàn vé hoặc đổi điểm tương đương.')],
         options=[dict(id='switch', label='Cho đoàn chọn: đổi sang Nhà Gốm hoặc nhận hoàn vé', requires=['alt', 'refund'], quality='good', stars=5,
                       review='Mưa mà chuyến đi vẫn trọn vẹn, lại được chọn phương án.',
                       outcome='Đa số chọn Nhà Gốm, hai người nhận hoàn vé và ngồi quán trà. Ai cũng vui.',
                       perspectives=[P('Bác Bình', '☔', 'Tôi mỏi chân, được ngồi uống trà là tuyệt.'),
                                     P('Cô Gốm', '🏺', 'Đoàn ghé bất ngờ nhưng tôi có dịp kể chuyện hoa văn.')]),
                  dict(id='wait', label='Chờ mưa tạnh ở xe', quality='bad', stars=2,
                       review='Ngồi xe hai tiếng nhìn mưa.',
                       outcome='Mưa không tạnh, đoàn bỏ lỡ cả buổi chiều.',
                       perspectives=[P('Linh', '😩', 'Đi du lịch mà như đi chờ.')])],
         lesson='Luôn có phương án dự phòng và để khách được chọn.'),
    dict(id='G-S05', career='tour_guide', title='Người bán hàng rong chèo kéo', npc=3, tone='gentle', min_day=1,
         opening='Một người bán hàng rong theo đoàn, nài Nam mua vòng tay với giá gấp ba.',
         facts=[dict(id='price', title='Giá tham khảo', source='Chợ địa phương', text='Vòng tay tương tự trong chợ bán khoảng 1/3 giá đề nghị.')],
         options=[dict(id='kind', label='Lịch sự từ chối thay đoàn, chỉ quầy có niêm yết giá', requires=['price'], quality='good',
                       outcome='Người bán rời đi, Nam mua ở quầy niêm yết giá. Không ai mất vui.',
                       perspectives=[P('Nam', '🙏', 'Tôi không biết từ chối sao cho khỏi ngại.'),
                                     P('Người bán hàng rong', '🧺', 'Hôm nay ế, nhưng anh hướng dẫn viên không nói nặng lời.')]),
                  dict(id='shout', label='Lớn tiếng đuổi đi', quality='bad',
                       outcome='Người bán bỏ đi nhưng đoàn thấy ngại vì cả khu chợ nhìn.',
                       perspectives=[P('Trúc', '😬', 'Tôi thấy thương người bán hơn là thấy an toàn.')])],
         lesson='Bảo vệ đoàn mà vẫn tôn trọng người lao động địa phương.'),

    # ---------------- Milk tea ----------------
    dict(id='M-S01', career='milk_tea', title='Khách nói ly trà “không giống lần trước”', npc=0, tone='gentle', min_day=1,
         opening='Linh đặt ly xuống quầy: “Ly này nhạt hơn lần trước nhiều. Có phải quán đổi công thức không?”',
         swap='Bạn là khách quen, nhớ vị ly trà tuần trước và thấy hôm nay khác.',
         facts=[dict(id='recipe', title='Phiếu công thức', source='Sổ pha chế', text='Công thức không đổi; ly hôm nay là 30% đường theo phiếu Linh gọi, tuần trước là 50%.'),
                dict(id='order', title='Phiếu gọi món', source='Máy order', text='Hôm nay Linh chọn “ít ngọt 30%”.')],
         options=[dict(id='remake', label='Giải thích nhẹ nhàng phiếu gọi món và pha lại theo mức 50%', requires=['order'], cost=6, quality='good', stars=5,
                       review='Quán giải thích rõ lại pha lại miễn phí, đúng vị mình thích.',
                       outcome='Linh cười: “À mình bấm nhầm!” Ly mới đúng vị. Linh chụp ảnh khoe bạn bè.',
                       perspectives=[P('Linh', '🧋', 'Mình tưởng quán đổi công thức, hóa ra mình chọn nhầm.'),
                                     P('Nhi (phụ quầy)', '🙂', 'Pha lại một ly tốn chút nguyên liệu nhưng giữ được khách quen.')]),
                  dict(id='argue', label='Khẳng định quán làm đúng, khách chọn nhầm thì chịu', requires=['order'], quality='bad', stars=2,
                       review='Đúng là mình chọn nhầm, nhưng cách nói làm mình không muốn quay lại.',
                       outcome='Linh im lặng trả tiền rồi đi. Tối đó có review 2 sao.',
                       perspectives=[P('Linh', '😶', 'Mình biết mình sai, nhưng quán không cần làm mình thấy ngại.')])],
         lesson='Đúng về dữ kiện chưa đủ; cách nói quyết định khách có quay lại hay không.'),
    dict(id='M-S02', career='milk_tea', title='Hàng dài giờ tan học', npc=5, tone='tense', min_day=2,
         opening='5 giờ chiều, học sinh xếp hàng tới cửa. Nhi hỏi: “Mình có nên nhận thêm đơn online không?”',
         facts=[dict(id='queue', title='Hàng chờ', source='Quầy', text='Đang có 11 ly chờ; trung bình 2 phút/ly với hai người pha.'),
                dict(id='app', title='Ứng dụng giao hàng', source='Máy tính bảng', text='Có 6 đơn online mới, tài xế sẽ tới sau 10 phút.')],
         options=[dict(id='pause', label='Tạm dừng nhận đơn online 20 phút, báo thời gian chờ cho khách tại quầy', requires=['queue', 'app'], quality='good', stars=5,
                       review='Đông mà quán báo rõ phải chờ bao lâu, không ai sốt ruột.',
                       outcome='Hàng giảm dần, ly nào cũng đúng. Mở lại đơn online khi ổn định.',
                       perspectives=[P('Học sinh', '🎒', 'Biết chờ 15 phút là mình đứng chờ được.'),
                                     P('Tài xế giao hàng', '🛵', 'Không phải đứng chờ 30 phút ở cửa quán.'),
                                     P('Nhi', '😮‍💨', 'Không bị dồn, không pha sai.')]),
                  dict(id='accept', label='Nhận hết, pha nhanh hết mức', quality='bad', stars=2,
                       review='Chờ 40 phút, ly còn sai topping.',
                       outcome='Ba ly sai topping, tài xế chờ lâu hủy đơn, khách tại quầy bực bội.',
                       perspectives=[P('Tài xế', '⏳', 'Tôi chờ nửa tiếng mất luôn cuốc khác.'),
                                     P('Nhi', '😵', 'Tay pha mà đầu không kịp nhớ.')])],
         lesson='Biết nói “tạm dừng” cũng là một kỹ năng vận hành.'),
    dict(id='M-S03', career='milk_tea', title='Khách để quên điện thoại', npc=1, tone='gentle', min_day=1,
         opening='Dọn bàn, bạn thấy một chiếc điện thoại. Mười phút sau có người gọi đến.',
         facts=[dict(id='call', title='Cuộc gọi', source='Màn hình', text='Người gọi xưng là con của bác Tư, hỏi bác có để quên máy không.'),
                dict(id='rule', title='Quy tắc quán', source='Sổ tay quán', text='Đồ thất lạc: ghi sổ, giữ ở tủ quầy, trả tận tay chủ khi xác nhận được.')],
         options=[dict(id='log', label='Ghi sổ, hẹn người nhà tới nhận có xác nhận', requires=['call', 'rule'], quality='good', stars=5,
                       review='Quán giữ máy cẩn thận, còn gọi báo cho con tôi. Tốt bụng quá!',
                       outcome='Bác Tư quay lại nhận máy, nhắc mãi chuyện “quán này thật thà”.',
                       perspectives=[P('Bác Tư', '👴', 'Tôi lo mất hết ảnh cháu trong máy.'),
                                     P('Bình (giao nguyên liệu)', '📦', 'Có sổ ghi rõ, ai trực ca nào cũng biết.')]),
                  dict(id='hand', label='Đưa máy cho người tự nhận là người nhà ghé lấy', quality='bad',
                       outcome='Người ghé lấy máy không phải người nhà bác Tư. Quán phải báo công an khu vực.',
                       perspectives=[P('Bác Tư', '😰', 'Sao quán lại đưa máy của tôi cho người lạ?')])],
         lesson='Tốt bụng cần đi kèm quy trình xác nhận.'),
    dict(id='M-S04', career='milk_tea', title='Nhà cung cấp giao trân châu cận hạn', npc=4, tone='gentle', min_day=2,
         opening='Bình giao thùng trân châu, hạn dùng còn 1 ngày thay vì 5 ngày như thường.',
         facts=[dict(id='label', title='Nhãn thùng', source='Thùng hàng', text='Hạn dùng: ngày mai. Phiếu giao ghi “hàng tiêu chuẩn”.'),
                dict(id='contract', title='Thỏa thuận nhập', source='Sổ nhà cung cấp', text='Hàng giao phải còn tối thiểu 3 ngày hạn dùng.')],
         options=[dict(id='reject', label='Từ chối nhận, ghi biên bản, đề nghị đổi', requires=['label', 'contract'], quality='good',
                       outcome='Bình gọi kho, đổi thùng mới trong chiều. Nhà cung cấp gửi lời xin lỗi.',
                       perspectives=[P('Bình (giao hàng)', '📦', 'Tôi chỉ chở theo phiếu, có biên bản thì kho mới đổi được.'),
                                     P('Khách ngày mai', '🧋', 'Trân châu vẫn dẻo, không hề biết có chuyện gì.')]),
                  dict(id='accept', label='Nhận và dùng thật nhanh', quality='bad',
                       outcome='Hết ngày còn nửa thùng phải bỏ; một khách phàn nàn trân châu cứng.',
                       perspectives=[P('Khách', '😖', 'Trân châu cứng như sỏi.')])],
         lesson='Kiểm nhận hàng là lớp bảo vệ đầu tiên cho khách.'),
    dict(id='M-S05', career='milk_tea', title='Hân xin quay clip review miễn phí', npc=3, tone='gentle', min_day=3,
         opening='Hân (người làm nội dung) đề nghị: “Cho mình 5 ly miễn phí, mình quay clip review cho quán.”',
         facts=[dict(id='reach', title='Kênh của Hân', source='Tìm hiểu', text='Kênh có người xem thật, nhưng chủ yếu ở quận khác.'),
                dict(id='privacy', title='Khách trong quán', source='Quan sát', text='Đang có khách ngồi, vài người không muốn lên hình.')],
         options=[dict(id='deal', label='Thỏa thuận rõ: 2 ly, quay góc quầy, không quay khách, ghi rõ là hợp tác', requires=['reach', 'privacy'], cost=12, quality='good',
                       outcome='Clip minh bạch “có hợp tác”, khách trong quán không bị quay. Vài người mới ghé thử.',
                       perspectives=[P('Hân', '🎥', 'Có thỏa thuận rõ ràng, mình làm clip thoải mái hơn.'),
                                     P('Khách đang ngồi', '🙈', 'Cảm ơn quán đã hỏi trước khi quay.')]),
                  dict(id='free', label='Cho 5 ly, quay thoải mái', cost=30, quality='bad',
                       outcome='Clip lọt mặt một khách, người đó yêu cầu gỡ. Quán mất 5 ly và phải xin lỗi.',
                       perspectives=[P('Khách bị quay', '😠', 'Tôi không đồng ý lên mạng.')])],
         lesson='Hợp tác quảng bá cần minh bạch và tôn trọng người xung quanh.'),
]
