"""💕 Words of the café date (live/dating.py): icebreaker cards and the little menu.

CARDS: (question, answers) with 3 or 4 answers each. Playful, street, GenZ (owner, 01/10: "vl" is fine; nothing
sexual, no heavy profanity). A date deals 3 different cards. MENU: (id, emoji, name); a date shows 6 of them for
"Chọn món cho nhau".
"""
from __future__ import annotations

CARDS = (
    ('Sáng nay uống gì?', ('Cà phê sữa đá', 'Trà đá vỉa hè', 'Trà sữa full topping', 'Nước lọc cho healthy')),
    ('Nghề mơ ước hồi nhỏ?', ('Bác sĩ', 'Phi công', 'Ca sĩ', 'Chủ tiệm tạp hóa')),
    ('Đi biển hay lên núi?', ('Biển, phải là biển', 'Núi, săn mây', 'Ở nhà bật điều hòa')),
    ('Mì gói nấu kiểu gì?', ('Có trứng, có rau', 'Bẻ vụn ăn sống', 'Thêm xúc xích là chân ái', 'Chan nước sôi, đợi 3 phút')),
    ('Đi trễ thì lý do quen nhất?', ('Kẹt xe', 'Ngủ quên', 'Không tìm thấy dép', 'Mình đâu có trễ, mọi người tới sớm')),
    ('Lương về, việc đầu tiên làm?', ('Trả nợ', 'Đi ăn lẩu', 'Bỏ heo đất', 'Săn sale')),
    ('Kiểu nhắn tin của bạn?', ('Seen rồi rep sau', 'Rep trong 3 giây', 'Gửi sticker thay lời', 'Voice note 2 phút')),
    ('Ăn vặt đầu hẻm, chọn món nào?', ('Bánh tráng trộn', 'Xiên que chiên', 'Bột chiên', 'Ốc luộc')),
    ('Mưa to bất chợt, bạn sẽ…', ('Mặc áo mưa tiện lợi', 'Trú dưới mái hiên', 'Đội mưa chạy luôn', 'Tạt vô quán ngồi chờ')),
    ('Buồn thì nghe nhạc gì?', ('Ballad thất tình', 'Remix quẩy cho quên', 'Lofi chill', 'Không nghe, đi ngủ')),
    ('Thú cưng mơ ước?', ('Mèo', 'Chó', 'Cá cảnh', 'Một bé capybara')),
    ('Cuối tuần lý tưởng?', ('Ngủ tới trưa', 'Cà phê với hội bạn', 'Đi phượt', 'Dọn nhà cho sạch')),
    ('Muốn có siêu năng lực nào?', ('Dịch chuyển tức thời', 'Đọc suy nghĩ', 'Ăn hoài không mập', 'Ngủ 2 tiếng vẫn tỉnh')),
    ('Bạn là người…', ('Cú đêm chính hiệu', 'Dậy sớm đón bình minh', 'Ngủ lúc nào cũng được')),
    ('Gặp sếp ngoài đường thì?', ('Chào to rõ ràng', 'Giả vờ không thấy', 'Quay xe gấp', 'Rủ sếp đi cà phê')),
    ('Đi lẩu, gọi lẩu gì?', ('Lẩu Thái chua cay', 'Lẩu bò nhúng giấm', 'Lẩu nấm healthy', 'Lẩu gà lá é')),
    ('Điện thoại còn 5% pin?', ('Hoảng loạn tìm sạc', 'Kệ, sập thì thôi', 'Bật tiết kiệm pin rồi cầu nguyện')),
    ('Vào quán cà phê hay ngồi đâu?', ('Sát cửa sổ', 'Góc trong cùng', 'Vỉa hè ngắm phố', 'Chỗ gần ổ điện')),
    ('Chọn một ly thôi nha:', ('Trà sữa', 'Cà phê', 'Nước mía', 'Sinh tố bơ')),
    ('Tết thích nhất điều gì?', ('Lì xì', 'Được ngủ nướng', 'Bánh chưng', 'Đi chơi khắp nơi')),
    ('Kiểu đi chợ của bạn?', ('Có list đàng hoàng', 'Thấy gì mua nấy', 'Nhờ mẹ mua giùm', 'Đặt app cho lẹ')),
    ('Xem phim, miễn là…', ('Kết có hậu', 'Có plot twist', 'Diễn viên đẹp', 'Không buồn ngủ')),
    ('Kỹ năng sống còn ở phố?', ('Lách kẹt xe', 'Trả giá', 'Tìm chỗ gửi xe', 'Biết quán ngon mà rẻ')),
    ('Bữa sáng quốc dân?', ('Bánh mì', 'Phở', 'Xôi', 'Hủ tiếu')),
    ('Crush seen không rep thì?', ('Nhắn thêm một câu', 'Đợi 3 ngày', 'Đăng story cà khịa', 'Ăn tô bún bò cho đỡ buồn')),
    ('Hát karaoke chọn bài gì?', ('Bolero sâu lắng', 'Nhạc trẻ sôi động', 'Rap như thật', 'Cầm mic cổ vũ thôi')),
    ('Màu áo hay mặc nhất?', ('Đen huyền bí', 'Trắng tinh khôi', 'Màu be an toàn', 'Càng sặc sỡ càng tốt')),
    ('Con vật giống bạn nhất?', ('Mèo lười', 'Cún năng nổ', 'Gấu trúc ăn với ngủ', 'Cú đêm')),
    ('Đi du lịch, quan trọng nhất là?', ('Ăn ngon', 'Ảnh đẹp', 'Ngủ đủ', 'Tiết kiệm')),
    ('Hẹn 7 giờ thì bạn tới lúc…', ('6 giờ 45', '7 giờ đúng', '7 giờ 5 phút', '"Đang tới rồi" khi chưa dậy')),
    ('Tráng miệng chọn gì?', ('Chè Thái', 'Kem dừa', 'Bánh flan', 'Tàu hũ nước đường')),
    ('Ở nhà hay bị sai việc gì?', ('Đổ rác', 'Rửa chén', 'Sửa wifi', 'Chạy đi mua đồ lặt vặt')),
    ('Giải stress kiểu gì?', ('Ăn', 'Ngủ', 'Đi dạo phố', 'Lướt mạng tới sáng')),
    ('Trong nhóm chat, bạn là…', ('Người nói nhiều nhất', 'Người chỉ thả tim', 'Thánh gửi meme', 'Đọc hết rồi im')),
    ('Thích mùa nào nhất?', ('Xuân mát', 'Hạ rực rỡ', 'Thu lá vàng', 'Đông se lạnh')),
    ('Lạc đường thì?', ('Mở bản đồ', 'Hỏi người đi đường', 'Cứ đi, tới đâu hay tới đó')),
    ('Trúng số 1 tỷ thì?', ('Mua nhà', 'Đi du lịch', 'Gửi tiết kiệm', 'Mở quán cà phê')),
    ('3 giờ chiều cứu đói bằng?', ('Trà sữa', 'Cà phê muối', 'Nước dừa', 'Trà tắc')),
    ('Giọng hát của bạn là?', ('Ca sĩ chưa ra mắt', 'Hát đủ nghe', 'Hát cho vui cả xóm', 'Tốt nhất là đừng hát')),
    ('Món vỉa hè đỉnh nhất?', ('Ốc xào me', 'Chân gà nướng', 'Mực khô nướng', 'Đậu hũ chiên giòn')),
    ('Hồi đi học hay bị gọi lên bảng vì?', ('Nói chuyện riêng', 'Ngủ gật', 'Quên làm bài', 'Không bao giờ, mình ngoan lắm')),
    ('Kiểu tóc mơ ước?', ('Dài lãng tử', 'Ngắn gọn gàng', 'Nhuộm màu nổi', 'Cạo trọc cho mát')),
    ('Được nghỉ một tuần thì?', ('Ngủ cả tuần', 'Về quê', 'Đi Đà Lạt', 'Học một thứ mới')),
    ('Món không thể bỏ?', ('Cơm', 'Bún', 'Bánh mì', 'Mì gói')),
    ('Trình nấu ăn của bạn?', ('Masterchef của phố', 'Nấu được vài món', 'Chỉ biết úp mì', 'Nấu nước sôi còn khét')),
    ('Trong balo luôn có?', ('Sạc dự phòng', 'Khăn giấy', 'Son hoặc lược', 'Đồ ăn vặt')),
    ('Đi xem phim thích ngồi?', ('Hàng giữa', 'Hàng cuối', 'Sát màn hình', 'Gần lối ra')),
    ('App mở nhiều nhất?', ('Mạng xã hội', 'Nghe nhạc', 'Game', 'App đồ ăn')),
    ('Khi đói thì bạn…', ('Cáu như mèo', 'Im lặng đáng sợ', 'Ăn gì cũng ngon', 'Vẫn ổn, quen rồi')),
    ('Đi lại bằng gì vui nhất?', ('Xe máy', 'Xe đạp', 'Xe buýt', 'Cuốc bộ')),
    ('Ngày mưa thích làm gì?', ('Ngủ nướng', 'Ăn lẩu', 'Đọc truyện', 'Ngồi ngắm mưa')),
    ('Ai giữ quỹ trong nhóm bạn?', ('Mình chứ ai', 'Đứa cẩn thận nhất', 'Chia app cho lẹ', 'Không ai giữ, hên xui')),
    ('Sở thích bí mật?', ('Xem video nấu ăn', 'Hát trong nhà tắm', 'Sưu tầm sticker', 'Nói chuyện với mèo')),
    ('Một ngày không mạng xã hội?', ('Dễ ợt', 'Khó nhưng được', 'Không thể nào', 'Mạng xã hội là gì?')),
    ('Thích nhận quà kiểu gì?', ('Đồ ăn', 'Đồ tự làm', 'Đồ dùng được', 'Tiền mặt cho lẹ')),
    ('Đi ăn với bạn thì ai trả?', ('Chia đều', 'Ai rủ người đó trả', 'Thay phiên nhau', 'Oẳn tù tì')),
    ('Bạn sợ nhất?', ('Gián bay', 'Ma', 'Hết tiền', 'Bị seen')),
    ('Câu cửa miệng của bạn?', ('"Ủa alo?"', '"Chill thôi"', '"Hết cứu"', '"Để mai tính"')),
    ('Ăn phở thì?', ('Thêm chanh ớt', 'Thêm tương đen tương đỏ', 'Ăn nguyên bản', 'Gọi thêm quẩy')),
    ('Đi chơi theo nhóm, bạn là người…', ('Lên lịch trình', 'Chụp ảnh cho cả nhóm', 'Ăn là chính', 'Đi theo là được')),
    ('Hẹn lần đầu nên đi đâu?', ('Quán cà phê', 'Phố đi bộ', 'Rạp phim', 'Quán ăn vỉa hè')),
    ('Tin nhắn lúc 2 giờ sáng thường là?', ('"Ngủ chưa?"', 'Meme', 'Hỏi bài', 'Rủ ăn đêm')),
    ('Chè ngon nhất?', ('Chè ba màu', 'Chè bưởi', 'Chè đậu đen', 'Chè khúc bạch')),
    ('Tối thứ Sáu xem phim gì?', ('Kinh dị', 'Hài', 'Tình cảm', 'Hoạt hình')),
    ('Bạn tin vào?', ('Duyên số', 'Cố gắng là được', 'Cung hoàng đạo', 'Bữa sáng đầy đủ')),
    ('Lần cuối khóc là vì?', ('Phim', 'Cắt hành', 'Deadline', 'Đói')),
    ('Ăn đêm số 1?', ('Mì gói', 'Cháo', 'Bánh mì', 'Xôi')),
    ('Đi dạo ở đâu thích nhất?', ('Bờ hồ', 'Chợ đêm', 'Công viên', 'Phố đi bộ')),
    ('Đặt đồ ăn online hay bị?', ('Giao sai món', 'Giao trễ', 'Quên dặn ít đá', 'Shipper gọi lúc đang tắm')),
    ('Một từ tả bạn?', ('Lầy', 'Chill', 'Nghiêm túc', 'Khó đoán')),
    ('Đồ uống: đá hay nóng?', ('Đá, mùa đông cũng đá', 'Nóng mới thơm', 'Tùy tâm trạng')),
    ('Nhân vật hoạt hình giống bạn?', ('Doraemon', 'Nobita', 'Shin', 'Conan')),
    ('Mở quán thì bán gì?', ('Cà phê', 'Trà sữa', 'Bánh mì', 'Quán nhậu')),
    ('Đi siêu thị chủ yếu để?', ('Mua đồ cần thiết', 'Ăn thử miễn phí', 'Hưởng máy lạnh', 'Đi dạo cho vui')),
    ('Quán ốc, món phải gọi?', ('Ốc hương rang muối', 'Sò điệp mỡ hành', 'Nghêu hấp sả', 'Ốc len xào dừa')),
    ('Thường ngủ lúc mấy giờ?', ('Trước 11 giờ', '12 giờ đêm', '2 giờ sáng', 'Khi điện thoại hết pin')),
    ('Đi đám cưới bạn thì?', ('Đi sớm ăn no', 'Đi đúng giờ', 'Tới lúc đã lên món', 'Gửi phong bì nhờ')),
    ('Gu thời trang?', ('Basic', 'Hầm hố', 'Dễ thương', 'Thoải mái là được')),
    ('Chuông cửa reo bất ngờ?', ('Mở liền', 'Nhìn qua lỗ cửa', 'Giả vờ đi vắng', 'Hét "Ai đó?"')),
    ('Skill sống ảo đỉnh nhất?', ('Chụp góc nghiêng', 'Viết caption hay', 'Chọn filter', 'Không biết sống ảo')),
    ('Nhắn tin hay gọi điện?', ('Nhắn tin', 'Gọi điện', 'Gọi video', 'Gặp mặt luôn')),
    ('Thấy đồ sale 50%?', ('Chốt đơn liền', 'Cân nhắc 3 ngày', 'Bỏ giỏ rồi quên', 'Kệ, ví mỏng')),
    ('Hồi nhỏ sợ nhất?', ('Ông kẹ', 'Đi tiêm', 'Bị mẹ gọi đủ họ tên', 'Kiểm tra 15 phút')),
    ('Món Tết mong nhất?', ('Bánh chưng', 'Thịt kho trứng', 'Mứt dừa', 'Hạt dưa')),
    ('Ngày đầu làm nghề mới?', ('Hồi hộp', 'Hào hứng', 'Muốn về nhà', 'Làm quen cả phố')),
    ('Thần tượng hồi teen?', ('Ca sĩ Kpop', 'Cầu thủ bóng đá', 'Diễn viên phim Hàn', 'Anh chị trong xóm')),
    ('Trà sữa thì đường đá sao?', ('100% ngọt', '50% đường', '0% đường', 'Nhiều đá ít trà')),
    ('Thích chơi game gì?', ('Bắn súng', 'Xếp hình', 'Nông trại', 'Không chơi game')),
    ('Nếu là món đường phố, bạn là?', ('Bánh mì đa năng', 'Bánh tráng nướng giòn rụm', 'Xôi dẻo dai', 'Ốc cay cay')),
    ('Kẹt xe thì?', ('Kiên nhẫn chờ', 'Lách vào hẻm', 'Bật nhạc hát', 'Than trời')),
    ('Ước mơ hiện tại?', ('Có nhà riêng', 'Đi vòng quanh thế giới', 'Ngủ đủ 8 tiếng', 'Không phải dậy sớm')),
    ('Bị tag vào ảnh xấu thì?', ('Gỡ tag liền', 'Kệ, xấu mà vui', 'Đăng ảnh xấu hơn trả đũa', 'Bình luận "ai đây?"')),
    ('Ra chợ đêm việc đầu tiên?', ('Đi một vòng ngó giá', 'Mua đồ ăn trước', 'Chụp ảnh check-in', 'Tìm chỗ ngồi')),
    ('Hàng xóm hát karaoke lúc 10 giờ tối?', ('Qua hát chung', 'Đeo tai nghe', 'Gõ cửa nhắc nhẹ', 'Chấm điểm thầm')),
)

MENU = (
    ('trasua', '🧋', 'Trà sữa trân châu'),
    ('caphemuoi', '☕', 'Cà phê muối'),
    ('tratac', '🍋', 'Trà tắc'),
    ('nuocdua', '🥥', 'Nước dừa'),
    ('sinhtobo', '🥑', 'Sinh tố bơ'),
    ('tradao', '🍑', 'Trà đào cam sả'),
    ('banhmi', '🥖', 'Bánh mì'),
    ('banhtrang', '🌶️', 'Bánh tráng trộn'),
    ('xienque', '🍢', 'Xiên que'),
    ('chekhucbach', '🍮', 'Chè khúc bạch'),
    ('kemdua', '🍨', 'Kem dừa'),
    ('banhsu', '🧁', 'Bánh su kem'),
    ('banhbao', '🥟', 'Bánh bao'),
    ('micay', '🍜', 'Mì cay 7 cấp'),
    ('bapxao', '🌽', 'Bắp xào'),
    ('nuocmia', '🥤', 'Nước mía'),
)
MENU_INDEX = {m[0]: m for m in MENU}

# Quick lines in the chat step (one tap; stored and filtered like typed text).
QUICK = ('Haha 😂', 'Cùng gu ghê!', 'Ủa sao biết 😳', 'Lần sau đi tiếp nha', 'Bạn vui tính ghê')
