import assert from 'node:assert/strict';
import {joystickAxes,nextSpeed,motionSign} from '../public/js/careers/delivery_controls.js';
import * as controls from '../public/js/careers/delivery_controls.js';
assert.deepEqual(joystickAxes(0.05,-0.05),{steer:0,drive:0});
assert.deepEqual(joystickAxes(0,-1),{steer:0,drive:1});
assert.deepEqual(joystickAxes(0,1),{steer:0,drive:-1});
const diagonal=joystickAxes(3,-3);
assert(diagonal.steer>0&&diagonal.drive>0&&Math.hypot(diagonal.steer,diagonal.drive)<=1.001);
const advance=(v,input,n=300)=>{for(let i=0;i<n;i++)v=nextSpeed(v,input,1/60);return v;};
assert(advance(0,{drive:1})>10);
assert(advance(0,{drive:.4})<advance(0,{drive:1}));
assert(advance(0,{drive:-1})>=-4&&advance(0,{drive:-1})<-3.8);
assert(nextSpeed(1,{drive:-1},.1)===0,'direction change first stops');
assert(nextSpeed(-1,{drive:1},.1)===0,'forward change first stops');
assert.equal(advance(-4,{brake:true,drive:-1}),0,'brake wins over reverse');
assert.equal(advance(10,{brake:true,drive:1}),0);
assert.equal(advance(-4,{drive:0}),0,'released reverse coasts to zero');
assert.equal(advance(4,{drive:0}),0);
assert.equal(motionSign(-2,1),-1,'while braking, monitor actual travel direction');
assert.equal(motionSign(0,-1),-1,'reverse from stationary monitors rear junction');
assert.equal(motionSign(0,0),1);
assert.equal(joystickAxes(.08,-1).steer,0,'thumb jitter must not steer while riding straight');
assert.equal(joystickAxes(1,.08).drive,0,'steering alone must not accidentally reverse');
assert.equal(advance(12,{drive:0},180),0,'releasing throttle settles within three seconds');
assert.equal(typeof controls.nextSteer,'function');
let a=0,b=0;
for(let i=0;i<60;i++)a=controls.nextSteer(a,1,1/60);
for(let i=0;i<30;i++)b=controls.nextSteer(b,1,1/30);
assert.ok(Math.abs(a-b)<1e-9,'steering smoothing is independent of frame rate');
assert.ok(controls.nextSteer(0,1,1/60)>0&&controls.nextSteer(0,1,1/60)<.3);
console.log('courier controls: joystick, reverse, braking and movement direction passed');
