import assert from 'node:assert/strict';
import {familyView,familyAction} from '../public/js/v4/family.js';
import {householdView} from '../public/js/v4/household.js';
const base={day:'2026-10-04',clock:'Ngày lịch Việt Nam (UTC+7)',child:null,copies:[],requests:[],ready:true,can_invite:false,can_leave:false,together:false,home_name:'',outfits:[]};
const married={status:'married',partner:{name:'Mây'}};
const buttons=html=>[...html.matchAll(/<button\b[^>]*>[\s\S]*?<\/button>/g)].map(x=>x[0]);
let html=familyView(base,null);
assert.match(html,/không cần kết hôn/);assert.match(html,/data-mr="nav:guests"/);
assert.ok(buttons(html).some(b=>b.includes('data-tab="friends"')));
assert.ok(!buttons(html).some(b=>b.includes('fam:home')));
html=familyView({...base,ready:false,eligibility:{self_day:12,partner_day:4,self_story:true,partner_story:true,min_day:10}},married);
assert.match(html,/Người ấy đang ở ngày sống 4/);
assert.ok(buttons(html).some(b=>b.includes('nav:home')));
assert.ok(!buttons(html).some(b=>b.includes('fam:request')));
html=familyView({...base,can_invite:true,home_name:'Nhà sen'},married);
assert.ok(buttons(html).some(b=>b.includes('fam:home')));
assert.match(html,/Nhà sen/);
html=familyView({...base,partner_can_invite:true,partner_home_name:'Nhà gió'},married);
assert.match(html,/Người ấy đang ở Nhà gió/);
assert.ok(!buttons(html).some(b=>b.includes('fam:home')));
const received={id:2,kind:'home',home:'Nhà mơ',mine:false},sent={id:3,kind:'child',name:'Mít',origin:'adopt',mine:true};
html=familyView({...base,can_invite:true,requests:[sent,received]},married);
assert.ok(html.indexOf('Lời mời cần bạn trả lời')<html.indexOf('Đã gửi · Chờ người ấy'));
assert.ok(html.indexOf('Đồng ý ở chung')<html.indexOf('Nhà của hai bạn'));
assert.ok(buttons(html).some(b=>b.includes('fam:answer')&&b.includes('data-id="2"')));
assert.ok(!buttons(html).some(b=>b.includes('fam:answer')&&b.includes('data-id="3"')));
assert.ok(buttons(html).some(b=>b.includes('fam:cancel')&&b.includes('data-id="3"')));
assert.ok(!buttons(html).some(b=>b.includes('fam:home')||b.includes('fam:request')));
html=familyView({...base,together:true,can_invite:true,can_leave:true},married);
assert.match(html,/Đang ở chung/);
assert.ok(!buttons(html).some(b=>b.includes('fam:home')));
assert.ok(html.indexOf('<details')<html.indexOf('fam:leave'));
const child={id:'shared',name:'Bông',stage:'Em bé',care_days:3,bond:20,needs:{food:80,clean:90,joy:70},acts:[{id:'milk',name:'Uống sữa',emoji:'🥛',cost:0,done:true}],owned:[],outfit:'basic'};
html=familyView({...base,child},married);
assert.match(html,/Hôm nay đã chăm đủ/);
assert.match(buttons(html).find(b=>b.includes('fam:care')),/disabled/);
assert.match(html,/<details[^>]*><summary>Tên gọi &amp; đồ của bé<\/summary>[\s\S]*family:name:shared/);
assert.ok(!buttons(html).some(b=>b.includes('fam:request')));
const posts=[];
await familyAction('fam:cancel',{id:'3'},{env:{},family:{...base,requests:[sent]},post:async(op,p)=>posts.push({op,p})});
assert.equal(posts[0].op,'family_cancel');assert.equal(posts[0].p.id,3);
let env={api:{state:{marriage:{spouse:married},journey:{household:{members:[],outfits:[],adopt:[],locked:false}}}}};
html=householdView(env);
assert.ok(html.indexOf('data-tab="family"')<html.indexOf('Con riêng &amp; thú cưng'));

// Exercise the real modal dispatcher: destinations, close-before-navigation and typing guard.
const listeners={},root={innerHTML:''},stateHandlers=[];let renders=0,opened=[];
Object.defineProperty(root,'innerHTML',{get:()=>html,set:v=>{html=v;renders++;}});
const dlg={open:false,scrollTop:0,setAttribute(){},contains:el=>Boolean(el),querySelector:s=>s==='.mr-root'?root:null,querySelectorAll:()=>[],addEventListener:(event,fn)=>listeners[event]=fn,showModal(){this.open=true;},close(){this.open=false;listeners.close?.();}};
globalThis.document={activeElement:null,hidden:false,createElement:()=>dlg,body:{append(){}},querySelector:()=>({}),querySelectorAll:()=>[],getElementById:()=>null,dispatchEvent(){}};
globalThis.window={addEventListener(){}};
const view={family:base,couple:married,catalog:{messages:[{id:'hi'}]},friends:{incoming:[]},incoming:[],rings:[],me:{}};
env={api:{state:{journey:{wallet:0}},addEventListener:(event,fn)=>stateHandlers.push(fn),json:async()=>view},openSheet:(...args)=>{assert.equal(dlg.open,false,'close before opening another sheet');opened.push(args);}};
const {openMarriage}=await import('../public/js/v4/marriage.js');
const settle=()=>new Promise(resolve=>setImmediate(resolve));
await openMarriage(env,'family');await settle();
assert.match(html,/role="tab" aria-selected="true"[^>]*data-tab="family"/);
assert.match(html,/Nhà của hai bạn/);
const prior=renders;document.activeElement={dataset:{mrField:'family:name'}};stateHandlers[0]();assert.equal(renders,prior,'state broadcasts do not redraw a family input being edited');document.activeElement=null;
function click(mr){const el={dataset:{mr},closest:()=>null};listeners.click({target:{closest:()=>el},preventDefault(){}});}
click('nav:home');await settle();assert.deepEqual(opened.pop(),['home',{jrView:'home'}]);
await openMarriage(env,'family');await settle();click('nav:personal');await settle();assert.deepEqual(opened.pop(),['home',{jrView:'household'}]);
assert.equal(dlg.open,false);
console.log('Family UX: eligibility, invitation priority/consent, care states, direct family entry, modal routes and typing guard passed.');

// A large career catalogue must not bury the home/family entry beneath workplaces.
document.addEventListener=()=>{};globalThis.addEventListener=()=>{};
const {journeyHome}=await import('../public/js/v4/journey.js');
const catalogue=Array.from({length:41},(_,i)=>({id:`career${i}`,short:`Nghề ${i}`,place:`Nơi ${i}`,category:'food'}));
const careers=Object.fromEntries(catalogue.map(m=>[m.id,{started:false,level:1,day:1,job:{},metrics:{}}]));
const journeyEnv={api:{state:{name:'An',careers,journey:{story:true,intro:true,gender:'female',chapter:1,life_day:10,wallet:100,titles:[],skills:[],places:{},unlocked:catalogue.slice(0,7).map(m=>m.id),maturity:{level:1,xp:0,floor:0,next:100,name:'Mới đến'},home:{place:{name:'Gác Bà Tám',where_id:'attic',cost:{rent:5}}}}},content:{catalogue,journey:{chapters:[],skills:[]}}},ui:{view:'home',homeMode:'list'}};
const journeyHTML=journeyHome(journeyEnv);
const characterAt=journeyHTML.indexOf('aria-label="Nhân vật của bạn"'),houseAt=journeyHTML.indexOf('aria-label="Nơi bạn ở"'),workAt=journeyHTML.indexOf('aria-label="Nơi làm việc"');
assert.ok(characterAt>=0&&houseAt>characterAt&&workAt>houseAt,'home follows the character and precedes the workplace catalogue');
assert.equal((journeyHTML.match(/aria-label="Nơi bạn ở"/g)||[]).length,1,'home card appears once');
assert.equal((journeyHTML.match(/class="jr-place /g)||[]).length,7,'fixture has seven open workplaces');
assert.ok(journeyHTML.indexOf('data-action="jrEnterHome"')<workAt,'enter-home button is above workplaces');
assert.ok(journeyHTML.indexOf('data-section="children"')<workAt,'shared-child shortcut is above workplaces');
console.log('Family findability: home entry follows character before 7 open and 34 locked careers.');
