import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as art from '../public/js/v4/deco-art.js';
import {setup} from '../public/js/v4/home-walk.js';
import * as view from '../public/js/v4/home-view.js';
import {escapeHTML,icon} from '../public/js/icons.js';
const source=(await readFile(new URL('../public/js/v4/reno.js',import.meta.url),'utf8')).replace(/^import .*;.*\r?\n/gm,'').replace(/^export /gm,'');
globalThis.document={body:{classList:{contains:()=>true}}};
const ui=new Function('A','walkSetup','live','sharedRooms','ownershipOrder','guestSession','icon','esc','Sound',source+'\nreturn {S,threeMove,dropAt,pickSkin,onClick,guest};')(art,setup,{on:()=>()=>{}},view.sharedRooms,view.ownershipOrder,view.guestSession,icon,escapeHTML,class{});
const sent=[],posts=[],chair={id:'ghe_dau',name:'Ghế',spot:'floor',cat:'table',w:1,h:1,rooms:['living'],tags:[]};
const room={id:'living',name:'Phòng',type:'living',cols:6,frows:3,wrows:2,cap:20,fix:[]};
const deco={place:{key:'attic',where:'attic'},rooms:[room],items:[{id:'a',k:chair.id,r:room.id,fx:20,fy:20,f:0}],bag:[{id:'b',k:chair.id}],owned:[]};
const state={journey:{deco},settings:{sound:false}};
const env={confirmAction:async()=>true,api:{state,content:{journey:{deco:{items:[chair],skins:[{id:'kem',part:'wall',price:0}]}}},command:async(action,payload)=>{sent.push({action,payload});return {message:'Đã lưu'};},json:async(url,options)=>{posts.push({url,body:JSON.parse(options.body)});return {message:'Đã lưu'};}}};
Object.assign(ui.S,{env,dlg:null,edit:true,room:'living'});
await ui.threeMove('a',{r:'living',x:31,y:9,f:1,face:'back'});
assert.deepEqual(sent.pop(),{action:'jr_deco_put',payload:{uid:'a',r:'living',x:31,y:9,f:1,face:'back'}});
await ui.threeMove('p:other',{r:'living',x:0,y:0});assert.equal(sent.length,0,'other residents cannot be moved');
ui.S.busy=true;await ui.threeMove('a',{r:'living',x:10,y:10});assert.equal(sent.length,0,'pending commands block another gesture');ui.S.busy=false;
ui.S.held={src:'bag',k:chair.id};await ui.dropAt({r:'living',x:40,y:20,f:0});assert.equal(sent.pop().payload.uid,'b','bag placement uses the owned uid');
await ui.pickSkin('wall','kem');assert.equal(sent.pop().action,'jr_deco_skin','paint remains server-owned');
await ui.onClick('pick',{uid:'a'});assert.equal(sent.pop().action,'jr_deco_pick','storage remains server-owned');
const remote={owner:{code:'friend'},deco};
await ui.guest.open('friend',async()=>remote);
await ui.threeMove('a',{r:'living',x:31,y:9,f:0});assert.equal(sent.length,0,'guest cannot edit even when an owned id collides');
ui.S.coop=true;await ui.threeMove('a',{r:'living',x:31,y:9,f:0});
assert.equal(sent.length,0,'cooperative edits never mutate the visitor save');assert.equal(posts.at(-1).url,'/api/home-guests/deco/act');assert.equal(posts.at(-1).body.code,'friend');assert.equal(posts.at(-1).body.action,'put');
console.log('3D home adapter: owned drag/bag/paint/storage commands, busy and guest rejection, checked cooperative endpoint passed');
