import assert from 'node:assert/strict';
import {crowd} from '../public/js/v4/home-crowd.js';
const handlers=new Map(),sent=[];
const live={state:'open',flags:{home:true},on(t,fn){handlers.set(t,fn);return ()=>handlers.delete(t);},send(f){sent.push(f);return true;}};
const emit=(t,f={})=>handlers.get(t)?.(f);
let defer=false,arrive=null;
const c=crowd({live,state:()=>({journey:{gender:'female'}}),redraw:()=>{},still:()=>true,svg:()=>null,xy:p=>p,approach:(p,fn)=>{if(defer)arrive=fn;else fn();}});
c.join('bed',[.2,.8]);c.join('bed',[.2,.8]);
assert.equal(sent.length,1,'joining is idempotent across re-renders');
emit('home_room',{room:'opaque',r:'bed',me:'me',people:[{pid:'me',x:.2,y:.8},{pid:'spouse',name:'<3',x:.5,y:.7}]});
assert.equal(c.state().people.length,1);
assert.ok(c.markup().includes('&lt;3'),'remote names are escaped');
emit('renamed',{pid:'spouse',name:'Bạn mới <3'});
assert.equal(c.state().people[0].name,'Bạn mới <3');
assert.ok(c.panel().includes('Bạn mới &lt;3'),'room labels follow the new name');
assert.equal(c.markup('kitchen'),'','previous room does not leak into next render');
assert.equal(c.markup('bed','changed-home'),'','previous home does not leak into next render');
c.walk([[.2,.8],[.4,.6]],500);
assert.equal(sent.at(-1).t,'home_mv');
c.emote('hug','spouse');
assert.deepEqual(sent.at(-1),{t:'home_emote',kind:'hug',to:'spouse'});
c.emote('hug','stranger');assert.equal(sent.at(-1).to,'spouse');
emit('home_left',{why:'other'});const count=sent.length;
c.join('bed',[.2,.8]);emit('welcome');
assert.equal(sent.length,count,'takeover does not cause automatic reclaim');
c.leave();c.join('bed',[.2,.8]);assert.equal(sent.at(-1).t,'home_in','explicit reopening can join again');
emit('home_room',{room:'old',r:'bed',me:'me',people:[]});
c.join('kitchen',[.3,.9]);
assert.deepEqual(sent.slice(-2).map(f=>f.t),['home_out','home_in']);
emit('home_left',{why:'out'});c.join('kitchen',[.3,.9]);
assert.equal(sent.at(-1).t,'home_in','old out acknowledgement does not cancel pending new join');
assert.equal(sent.filter(f=>f.t==='home_in'&&f.r==='kitchen').length,1);
emit('home_room',{room:'old',r:'bed',me:'me',people:[]});
assert.equal(c.state().room,null,'old room reply is ignored after room switch');
emit('home_room',{room:'new',r:'kitchen',me:'me',people:[]});
live.state='down';emit('down',{});assert.equal(c.state().room,null);
live.state='open';emit('welcome');assert.equal(sent.at(-1).r,'kitchen');
emit('home_room',{room:'new',r:'kitchen',me:'me',people:[]});
c.join('kitchen',[.3,.9],'different-home');
assert.deepEqual(sent.slice(-2).map(f=>f.t),['home_out','home_in'],'changing home identity re-enters even in same physical room');
emit('home_left',{why:'changed'});const blockedCount=sent.length;
c.join('kitchen',[.3,.9],'different-home');assert.equal(sent.length,blockedCount);
c.reopen();c.join('kitchen',[.3,.9],'different-home');assert.equal(sent.length,blockedCount+1);
emit('home_room',{room:'latest',r:'kitchen',me:'me',people:[{pid:'spouse',name:'Bình',x:.4,y:.8}]});
emit('home',{ev:[{k:'mv',pid:'spouse',p:[[.4,.8],[.6,.7]],ms:500}]});
assert.deepEqual(c.state().people[0].at,[.6,.7],'reduced motion updates remote position immediately');
emit('home',{ev:[{k:'emote',pid:'spouse',to:'me',kind:'heart'}]});
assert.ok(c.panel().includes('Bình thả tim cho bạn'));
emit('error',{ref:'home_emote',msg:'Chờ chút nhé'});assert.ok(c.panel().includes('Chờ chút nhé'));
defer=true;c.emote('kiss','spouse');
c.leave();const end=sent.length;emit('welcome');assert.equal(sent.length,end,'closed room stays closed');
arrive();assert.equal(sent.length,end,'leaving during approach cancels the pending affection');
live.flags.home=false;c.join('bed',[.1,.1]);assert.equal(sent.length,end,'feature disabled means no frames');
c.leave();
live.flags.home=true;
c.join('living',[.2,.8],'guest:A','HOSTA');
assert.equal(sent.at(-1).host,'HOSTA','guest join carries public owner code');
emit('home_room',{room:'a',r:'living',host:'HOSTA',me:'me',people:[{pid:'one',name:'One',x:.2,y:.8},{pid:'two',name:'Two',x:.3,y:.8}]});
assert.equal(c.state().people.length,2,'more than one peer shares the room');
assert.ok(c.panel().includes('data-to="one"')&&c.panel().includes('data-to="two"'),'each person has interaction buttons');
emit('home',{room:'a',ev:[{k:'emote',id:'offer',pid:'one',to:'me',kind:'hug',ttl:15}]});
emit('home',{room:'a',ev:[{k:'mv',pid:'two',p:[[.3,.8],[.4,.8]],ms:0}]});
assert.ok(c.panel().includes('data-id="offer"'),'unrelated movement preserves a pending response');
emit('home',{room:'a',ev:[{k:'out',pid:'two'}]});
assert.ok(c.panel().includes('data-id="offer"'),'unrelated departure preserves a pending response');
c.join('living',[.2,.8],'guest:B','HOSTB');
emit('home_room',{room:'stale-a',r:'living',host:'HOSTA',me:'me',people:[]});
assert.equal(c.state().room,null,'late reply from another host is ignored');
emit('home_room',{room:'b',r:'living',host:'HOSTB',me:'me',people:[]});
assert.equal(c.state().room,'b');
live.state='down';emit('down');live.state='open';emit('welcome');
assert.equal(sent.at(-1).host,'HOSTB','reconnect retains the selected host');
c.leave();
console.log('Home crowd: join, movement, emotes, escaping, takeover, reconnect and room changes passed');
