import assert from 'node:assert/strict';
import {householdAction,householdSubmit} from '../public/js/v4/household.js';
const J={wallet:0,bank:{open:true,pref:'account',balance:100},household:{members:[{id:'child',name:'Bông',owned:['basic'],acts:[{id:'milk',name:'Sữa',cost:4,done:false}]}],outfits:[{id:'yem',name:'Yếm',cost:18}],adopt:[{id:'cat',name:'Mèo',cost:30}]}};
const confirms=[],commands=[],env={api:{state:{journey:J}},confirmAction:async(...args)=>{confirms.push(args);return true;},cmd:async(...args)=>{commands.push(args);return null;},renderSheet:()=>{throw Error('failed API call must not render success');},toast:()=>{}};
const el={disabled:false,isConnected:true};
await householdAction('jrHhCare',{member:'child',act:'milk'},el,env);
assert.equal(confirms.at(-1)[3].cost,4);
assert.equal(confirms.at(-1)[3].payment.selected,'account');
assert.ok(confirms.at(-1)[3].payment.options.some(x=>x.id==='account'&&x.ok));
assert.equal(commands.at(-1)[1].pay,'account');
assert.equal(el.disabled,false);
assert.equal(J.household.members[0].acts[0].done,false,'API failure cannot mark care done locally');
await householdAction('jrHhStyle',{member:'child',item:'yem'},el,env);
assert.equal(confirms.at(-1)[3].cost,18);
assert.equal(commands.at(-1)[1].pay,'account');
const submit={disabled:false,isConnected:true},form={dataset:{jrForm:'hhAdopt'},querySelector:s=>s==='[name="name"]'?{value:'Miu'}:s==='[name="kind"]'?{value:'cat'}:submit};
await householdSubmit(form,env);
assert.equal(confirms.at(-1)[3].cost,30);
assert.equal(commands.at(-1)[1].pay,'account');
assert.equal(submit.disabled,false);
J.bank.balance=0;const count=commands.length;
await householdAction('jrHhCare',{member:'child',act:'milk'},el,env);
assert.equal(commands.length,count,'insufficient selected account blocks purchase');
console.log('household payment confirmation checks passed');
