import assert from 'node:assert/strict';
import * as money from '../public/js/v4/money.js';
import {feePay} from '../public/js/v4/certificates.js';
assert.equal(typeof money.personalPayment, 'function', 'shared chooser supports personal account payments');
const J={wallet:100,bank:{open:true,balance:40,pref:'account',card:{available:500,locked:null}}};
assert.equal(money.personalPayment(J,40),'account');
assert.equal(money.personalPayment(J,41),null,'no credit/cash fallback from account');
assert.equal(feePay(J,40),'account');
assert.equal(feePay(J,41),null);
assert.deepEqual(money.paymentMoney('account',40),{cost:40,pocket:'account'});
assert.match(money.paymentText('account'),/tài khoản/);
assert.equal(money.personalPayment({wallet:100},30),'cash');
assert.equal(money.personalPayment({wallet:0},30),null);
J.bank.pref='auto';assert.equal(money.personalPayment(J,30),'cash');
J.wallet=0;assert.equal(money.personalPayment(J,30),'card');
J.bank.pref='cash';assert.equal(money.personalPayment(J,30),null);
J.bank.pref='card';J.wallet=100;assert.equal(money.personalPayment(J,30),'card');
J.bank.card.locked='overdue';assert.equal(money.personalPayment(J,30),'cash');
J.bank.pref='joint';J.wallet=0;assert.equal(money.personalPayment(J,30),'auto','joint balance is validated on the server');
assert.equal(money.personalPayment(J,30,true),null,'marriage transaction cannot use joint funds or locked card');
const balances=money.balances({journey:{...J,bank:{...J.bank,pref:'account'}}},{fund:null});
assert.equal(balances.account,40,'account balance visible wherever account is the purchase preference');
assert.equal(money.confirmShort(balances,['Mua hàng'],money.paymentMoney('account',41)).miss,1);
console.log('personal payment chooser checks passed');
