import assert from 'node:assert/strict';
import {ownerQueueHTML,ownerArrivalText,counterActivity} from '../public/js/v4/quay-owner-queue.js';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const people=Array.from({length:8},(_,i)=>({ticket:i,name:i?'Cô Ba':'<Khách>',temperament:i%2?'relaxed':'fussy',mood:i%2?'calm':'angry',speech:i%2?'Tôi đợi được.':'Món của tôi đâu rồi?'}));
const html=ownerQueueHTML({crowd:people,voices:people},esc);
assert.equal((html.match(/<li /g)||[]).length,8);
assert.equal((html.match(/class="qy-queue-voice /g)||[]).length,3);
assert.match(html,/7 người chờ tới lượt/);
assert.match(html,/Đang phục vụ/);
assert.match(html,/Dễ tính/);
assert.match(html,/Món của tôi đâu rồi/);
assert.match(html,/&lt;Khách>/);
assert.doesNotMatch(html,/<Khách>/);
assert.equal(ownerQueueHTML({crowd:[]},esc),'');
assert.match(ownerArrivalText({next_at:110},{server_now:100}),/10 giây/);
assert.match(ownerArrivalText({next_at:1000000000},{server_now:100}),/Giá trên menu đang cao/);
assert.doesNotMatch(ownerArrivalText({},{}),/NaN|undefined/);
console.log('Owner queue: bounded customers/speech, escaped names and explicit arrival state passed.');

const stall={id:'q1',business:{status:'running',server_now:1000,recent:[{id:1,at:995,channel:'counter',dish:'tea'},{id:2,at:995,channel:'online'},{id:3,at:800,channel:'counter'},{id:4,at:1001,channel:'counter'}]}};
assert.deepEqual(counterActivity(stall).completed.map(p=>p.id),['sale:1'],'Only fresh confirmed counter receipts appear as completed');
stall.business.recent[0].name='An (nhân viên)';
assert.equal(counterActivity(stall).completed[0].name,'Khách','Receipt name identifies the serving employee, never the buyer');
stall.run={crowd:people.map((p,i)=>({...p,look:i}))};
assert.equal(counterActivity(stall).current.length,8);assert.equal(counterActivity(stall).completed.length,0,'Actors bounded across both sources');
stall.business.status='out_of_stock';assert.equal(counterActivity(stall).current.length,8,'Real waiting customers remain visible');assert.equal(counterActivity(stall).completed.length,0);
delete stall.run;stall.business.status='paused';assert.equal(counterActivity(stall).completed.length,0,'Stopped shops never stage purchases');
stall.business.status='running';stall.business.server_now=1200;assert.equal(counterActivity(stall).completed.length,0,'Old receipts expire on server time');
delete stall.business.server_now;assert.equal(counterActivity(stall).completed.length,0,'No timestamp means no claim that a sale is recent');
