import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {feedbackView} from '../public/js/v4/views.js';
globalThis.document={querySelector:()=>({sheet:{}})};
const f=JSON.parse(readFileSync(0,'utf8'));
const env=state=>({api:{state,content:f.content},ui:{fbPost:f.post}});
const post=state=>state.careers[state.current].feed.find(p=>p.id===f.post);
const initial=feedbackView(env(f.initial));
assert.match(initial,/Cần trả lời/,'open reviews include first replies and customer follow-ups');
assert.doesNotMatch(initial,/Chưa trả lời/);
assert.match(initial,/<form class="reply-box"/);
assert.doesNotMatch(initial,/Khách hỏi lại/);
const pending=feedbackView(env(f.pending));
assert.match(pending,/đang đọc trả lời/);
assert.doesNotMatch(pending,/<form class="reply-box"/);
const followup=structuredClone(f.after);post(followup).feedback.status='open';
assert.match(feedbackView(env(followup)),/Khách hỏi lại/);
assert.match(feedbackView(env(followup)),/<form class="reply-box"/);
const closed=structuredClone(f.after);post(closed).feedback.status='closed';
assert.match(feedbackView(env(closed)),/Đã trả lời/);
assert.doesNotMatch(feedbackView(env(closed)),/<form class="reply-box"/);
const guestOnly=structuredClone(f.initial);
post(guestOnly).feedback.thread.push({role:'guest',name:'Khách khác',side:'other',text:'Mình cũng vừa ghé tiệm.',day:1});
assert.doesNotMatch(feedbackView(env(guestOnly)),/Khách hỏi lại/,'another voice has not answered on behalf of the owner');
console.log('Review first/pending/follow-up/closed labels passed.');
