import assert from 'node:assert/strict';
import {equipmentView,hasWorkingStaff,staffRefresh,staffRefreshPaused} from '../public/js/v4/work-equipment.js';
const upgrades=[1,2,3].map(t=>({id:'kit'+t,kind:'equipment',careers:['delivery'],gear_tier:t,gear_rate:[100,115,135,160][t],requires:t>1?'kit'+(t-1):null,price:90*t,name:'Kit <'+t+'>',description:'Tăng tốc'}));
let html=equipmentView({money:1000,upgrades:[]},'delivery',upgrades);
assert.match(html,/Kit &lt;1&gt;/);assert.match(html,/Lắp thiết bị · 90 xu/);assert.match(html,/Cần bậc 1 trước/);
html=equipmentView({money:1000,upgrades:['kit1']},'delivery',upgrades);
assert.match(html,/Đã lắp bậc 1 · \+15%/);assert.match(html,/Lắp thiết bị · 180 xu/);
assert.equal(hasWorkingStaff({careers:{x:{ops:{business:{status:'paused'}}}}}),false);
assert.equal(hasWorkingStaff({careers:{x:{summary:true,business_running:true}}}),true,'Other careers continue refreshing');
let tick,cleared=false,calls=0,resolve,hidden=false,busy=false,at=100000,synced=0;
globalThis.setInterval=(fn,ms)=>{assert.equal(ms,30000);tick=fn;return 1;};globalThis.clearInterval=id=>{assert.equal(id,1);cleared=true;};
const state={careers:{x:{ops:{business:{status:'running'}}}}};
const stop=staffRefresh({state:()=>state,refresh:()=>{calls++;return new Promise(r=>resolve=r);},busy:()=>busy,visible:()=>!hidden,lastSync:()=>synced,now:()=>at});
const pending=tick();await tick();assert.equal(calls,1,'Only one refresh may be in flight');resolve();await pending;
hidden=true;await tick();assert.equal(calls,1);hidden=false;busy=true;await tick();assert.equal(calls,1);
busy=false;synced=at-1000;await tick();assert.equal(calls,1,'Recent commands already synchronized income');
synced=at-31000;const next=tick();assert.equal(calls,2);resolve();await next;
assert.equal(staffRefreshPaused({view:'home',jrView:'invest'}),true);
assert.equal(staffRefreshPaused({view:'home',jrView:'wallet'}),false);
assert.equal(staffRefreshPaused({view:'job',busy:true}),true);
assert.equal(staffRefreshPaused({view:'job'},true),true,'Open counter owns its own refresh');
assert.equal(staffRefreshPaused({view:'job'}),false);
stop();assert.equal(cleared,true);busy=false;await tick();assert.equal(calls,2,'Stopped page never fetches');
console.log('Equipment UI prerequisites, prices, escaping and visible non-overlapping staff refresh passed.');
