import assert from 'node:assert/strict';
import {workplaceBusinessView} from '../public/js/workplace-business-ui.js';
const c={open:true,ops:{staff:[],business:{status:'running',reason:'working',reason_text:'Nhân viên đang xử lý đơn riêng.',paused:false,served:7,revenue:140,net:44,expenses:96,wages:28,materials:21,goods:47,fund:99,wage_basis:'Lương từ quỹ nghề.',recent:[{id:'x1',label:'<Đơn trà>',name:'An & Bình',stars:5,revenue:20,wage:4,net:8}]}}};
let html=workplaceBusinessView(c);
assert.match(html,/140 xu/);assert.match(html,/44 xu/);assert.match(html,/&lt;Đơn trà&gt;/);assert.match(html,/An &amp; Bình/);assert.doesNotMatch(html,/ops_staff_business_pause/);
assert.match(html,/data-action="warehouse"/);assert.match(html,/data-action="decor"/);assert.match(html,/data-tab="finance"/);assert.doesNotMatch(html,/data-command="start_day"/);
c.open=false;c.ops.business.status='running';html=workplaceBusinessView(c);assert.doesNotMatch(html,/Mở ca cho đội|data-command="start_day"/);
assert.match(html,/40%/);assert.match(html,/lợi nhuận dương/);assert.doesNotMatch(html,/đóng ca thì đơn riêng dừng|Tạm dừng đơn mới/);
c.ops.business.paused=true;assert.doesNotMatch(workplaceBusinessView(c),/Cho đội tiếp tục/);
c.ops.business.status='paused';
c.ops.business.recent=[];assert.match(workplaceBusinessView(c),/Chưa có đơn riêng hoàn thành/);
c.ops.business.status='running';assert.match(workplaceBusinessView(c),/máy chủ xác nhận hoàn thành/);
assert.equal(workplaceBusinessView({ops:{}}),'','Older projections do not fabricate a running business');
assert.doesNotMatch(workplaceBusinessView(c),/Đang cập nhật các đơn lúc bạn vắng/,'Absent catch-up flag does not invent pending settlement');
c.ops.business.catching_up=true;html=workplaceBusinessView(c);
assert.match(html,/role="status">Đang cập nhật các đơn lúc bạn vắng…/);
assert.match(html,/Đơn đã ghi/);assert.match(html,/Lãi đã ghi/);
c.ops.business.catching_up=false;assert.doesNotMatch(workplaceBusinessView(c),/Đang cập nhật các đơn lúc bạn vắng/);
console.log('Workplace business UI: escaped receipts, +40% positive-profit rule, continuous staff, no pause control, resource navigation and honest pending state passed.');
