"""Chuyện oái oăm of Hãng bay Cánh Cò: the scripts for game/careers/air_odd.py (PILOT, CABIN).

One script = one exasperating person around the job and what they want:
  id, kind (charm | harass | demand | corner | bargain), rank (pax | crew | boss | kin), emoji, title,
  who ('Name · role'), text (their opening), push (what they say when pushing again, round 2 and 3),
  min_day, at ('open' morning | 'between' hops | 'any'), weight, persist (lo, hi), mood (lo, hi: 0 polite … 2 hot),
  words (own labels for the things the player can say), back / give / report / stuck (own outcome lines),
  npc (a PEOPLE index when a regular is the one pushing) + review {how: [stars, text]},
  breach (conduct points when a demand is given in to and it breaks a rule), severe (a corner cut given in to),
  fx {how: {patience, money}}, follow / need_mark (a follow-up: the same person again), and for a bargain:
  ask, limit (what the rules or common sense allow), unit, pay (xu per unit accepted, < 0 = the player pays),
  tire (fatigue per unit), cost (xu docked on a penalty), press (extra pressure).
Tone: the airline's people and passengers are properly annoying, slang and rude banter included; seduction and
harassment stay PG-13 (pressure and remarks, never sexual detail), and giving in is never the right answer.
"""

# ---------------------------------------------------------------- Phi công (people: 0 Vân, 1 Lộc, 2 Thu, 3 Mẫn, 4 bà Chín, 5 Kiệt, 6 bé Na)
PILOT = [
    # --- seduction: decline, set the line, report if it keeps coming
    dict(id='pl-bar', kind='charm', rank='pax', emoji='🍸', title='Ly rượu ở Phú Quốc', who='Chị Diệp · khách hạng thương gia',
         text='“Anh cơ phó ơi, tối nay tổ bay ngủ lại Phú Quốc hả? Em bao một ly ở bar khách sạn, chỉ hai đứa mình thôi nha 😉”',
         push=['“Có ai biết đâu mà anh ngại. Một ly thôi mà, đừng làm giá.”', '“Anh khó gần vl. Số phòng thôi cũng không cho à?”'],
         persist=(1, 3), mood=(0, 1), weight=3,
         back='Chị Diệp nhún vai: “Nghiêm túc ghê.” Rồi quay sang bấm điện thoại.',
         give='Bạn nhận lời. Sáng hôm sau ảnh hai người ở quầy bar nằm trong nhóm chat của cả hãng, kèm câu “tổ bay đi công tác vui ghê”.'),
    dict(id='pl-dm', kind='charm', rank='pax', emoji='📱', title='Tin nhắn của hot TikToker', who='Mi Mi · TikToker 800k follow',
         text='Mi Mi tag bạn vào clip “anh phi công đẹp trai nhất tuyến đảo 😍” rồi nhắn: “Tối nay ghé homestay em quay clip chung nha, cho có content.”',
         push=['“Clip đôi thôi mà, triệu view đó anh. Hãng còn phải cảm ơn em.”', '“Anh không quay thì em đăng clip anh từ chối, cho cả mạng xã hội phán xử nha 🙃”'],
         persist=(2, 3), mood=(0, 2), weight=2,
         words={'alt': 'Cần quay gì thì liên hệ phòng truyền thông nhé.'},
         back='Mi Mi thả một icon mặt lè lưỡi rồi thôi. Clip vẫn lên, nhưng chỉ có máy bay.',
         give='Bạn tới homestay. Clip “hậu trường cùng anh phi công” lên xu hướng, và phòng an toàn mời bạn lên uống trà.'),
    dict(id='pl-wife', kind='charm', rank='boss', emoji='💍', title='Du thuyền của “phu nhân đối tác”', who='Bà Hằng · vợ đối tác lớn của hãng',
         text='“Cuối tuần chị có chuyến du thuyền riêng. Em đi cùng cho vui. Chồng chị nói một câu là em lên cơ trưởng sớm hai năm đấy.”',
         push=['“Chị thích người biết điều. Đừng để chị phải nhắc hai lần.”', '“Em nghĩ kỹ đi. Cơ hội không gõ cửa lần thứ ba đâu.”'],
         persist=(2, 3), mood=(0, 1), weight=2,
         words={'rule': 'Thăng chức ở hãng đi theo giờ bay, không đi đường khác.', 'alt': 'Em cảm ơn chị, em bận lịch bay rồi.'},
         back='Bà Hằng cười nhạt: “Cứng đầu. Được.” Tuần sau đối tác vẫn ký hợp đồng, như chưa có chuyện gì.',
         give='Bạn lên du thuyền. Hai tuần sau cả hãng đồn bạn “đi cửa sau”, và hội đồng thăng hạng hoãn hồ sơ bạn vô thời hạn.'),
    dict(id='pl-door', kind='charm', rank='pax', emoji='🚪', title='Gõ cửa lúc 11 giờ đêm', who='Cô khách phòng bên · khách sạn tổ bay',
         text='Tổ bay ngủ lại Côn Đảo. 11 giờ đêm có tiếng gõ cửa, giọng con gái cầm chai vang: “Anh phi công ơi, mở cửa nói chuyện chút đi, em buồn quá.”',
         push=['“Nói chuyện thôi mà, anh sợ gì. Mở cửa đi.”', '“Em đứng đây tới sáng luôn đó.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'alt': 'Có gì mai gặp ở sảnh nhé.'},
         back='Tiếng bước chân xa dần. Bạn đặt báo thức 4 giờ và ngủ tiếp.',
         give='Bạn mở cửa “nói chuyện chút”. Sáng ra lễ tân kể lại với chị Vân, và buổi bay sáng đó bạn ngáp suốt.'),
    dict(id='pl-note', kind='charm', rank='pax', emoji='💌', title='Mảnh giấy kẹp trong ly cà phê', who='Cô khách ghế 2A',
         text='Chị Thu đưa vào buồng lái một mảnh giấy: “Số em đây nè 😘 Tối 8h quán cà phê cạnh sân bay, không tới là em giận.”',
         push=['Cô khách nhắn tiếp qua chị Thu: “Anh chê em à? Em đẹp mà.”', '“Không tới thì em ngồi lì ở cổng nhân viên chờ anh.”'],
         persist=(0, 2), mood=(0, 1), weight=2,
         words={'alt': 'Nhờ chị Thu cảm ơn cô ấy giúp.'},
         back='Mảnh giấy vào thùng rác cùng vỏ bánh. Chị Thu cười: “Đẹp trai cũng khổ ha.”',
         give='Bạn tới quán. Cô ấy dắt theo ba đứa bạn để “ra mắt anh phi công”, và chụp ảnh đăng khắp nơi kèm tên hãng.'),
    dict(id='pl-agent', kind='charm', rank='pax', emoji='🎁', title='Chị đại lý vé “dễ thương”', who='Chị Kiều · đại lý vé máy bay',
         text='Chị Kiều gửi túi quà hàng hiệu, nháy mắt: “Tuần sau khách chị kín chuyến Côn Đảo, em xếp cho họ lên trước nha. Chị không quên em đâu 😉”',
         push=['“Quà nhỏ thôi mà cưng, ai mà không nhận. Đừng ngây thơ vậy chứ.”', '“Không giúp thì thôi, chị nói với trưởng phòng là em làm khó chị nhé.”'],
         persist=(1, 2), mood=(0, 2), weight=2,
         words={'rule': 'Xếp khách là việc của phòng vé, không phải của tổ bay.', 'alt': 'Chị gửi trả quà giúp em.'},
         back='Túi quà được gửi trả kèm một câu cảm ơn lịch sự. Chị Kiều đi tìm “mối” khác.',
         give='Bạn nhận quà và nhắn phòng vé. Hai tuần sau hãng kiểm toán đại lý, tên bạn nằm trong danh sách “có quà”.'),
    # --- harassment of the crew, seen from the flight deck
    dict(id='pl-thu', kind='harass', rank='pax', emoji='🚨', title='Khách say quấy rối chị Thu', who='Anh khách say ghế 5C',
         text='Chị Thu gọi vào buồng lái, giọng run: khách ghế 5C say, cứ níu tay chị, buông lời khiếm nhã, “tiếp viên mà làm giá”.',
         push=['Chị Thu gọi lại: “Hắn vẫn chưa thôi, còn quay sang trêu bạn đồng nghiệp chị.”', '“Hắn đứng dậy chặn lối đi rồi em ơi.”'],
         persist=(2, 3), mood=(1, 2), weight=2,
         words={'stop': 'Qua loa: “Khách 5C ngồi yên ngay.”', 'no': 'Bảo chị Thu đổi chỗ, tách hắn ra.',
                'rule': 'Báo trước: xuống tàu có công an sân bay chờ.', 'duty': 'Tôi đang lái, chị tự lo nhé.',
                'joke': 'Khách say mà, chị cười cho qua.', 'later': 'Hạ cánh rồi tính.', 'yes': 'Chị chiều hắn chút cho yên.'},
         back='Nghe qua loa là buồng lái đã biết, 5C ngồi im thin thít. Chị Thu thở phào.',
         report='Bạn báo mặt đất. Hạ cánh, công an sân bay lên tàu mời 5C xuống lập biên bản; hãng cấm bay hắn 6 tháng. Chị Thu siết tay bạn: “Cảm ơn em.”',
         stuck='5C quậy tới lúc hạ cánh rồi đi thẳng, không biên bản nào. Chị Thu im lặng suốt chặng về. Lần sau: báo luôn.',
         give='Không ai được “chiều” kẻ quấy rối. Chị Thu tự xoay xở cả chặng, mắt đỏ hoe.'),
    # --- corners cut: say it, then report (reports are no-blame)
    dict(id='pl-skip', kind='corner', rank='crew', emoji='📋', title='“Checklist đọc lướt thôi”', who='Cơ trưởng Tài · bay thay chị Vân hôm nay',
         text='“Tàu này anh bay mười năm, nhắm mắt cũng lái được. Checklist đọc lướt thôi em, đọc từng dòng như học sinh ấy.”',
         push=['“Em mới bay mấy năm mà dạy anh à? Ok, đọc lướt nha.”', '“Chậm vl. Khách chửi là em chịu nhé.”'],
         persist=(1, 3), mood=(0, 2), weight=3,
         back='Anh Tài cằn nhằn nhưng vẫn đọc từng dòng. Tới dòng đèn chống va thì anh khựng lại: quên thật.',
         give='Hai người đọc lướt. Lăn ra đầu đường băng mới thấy quên bật đèn chống va, đài nhắc ngay trên tần số chung, cả sân bay nghe.'),
    dict(id='pl-fuel', kind='corner', rank='boss', emoji='⛽', title='Bớt dầu cho “tối ưu chi phí”', who='Anh Quang · trưởng phòng khai thác',
         text='“Tháng này hãng lỗ tiền dầu. Từ nay bớt 100 kg dự phòng mỗi chặng. Trời đẹp mà, mang nặng làm gì.”',
         push=['“Anh nói rồi đấy. Người khác làm được sao em không làm được?”', '“Ai cũng cãi như em thì hãng đóng cửa, cả đám thất nghiệp.”'],
         persist=(2, 3), mood=(0, 1), weight=2, severe=3,
         words={'rule': 'Dầu dự phòng là luật hàng không, không ai được bớt.', 'alt': 'Tiết kiệm bằng cách bay đúng độ cao, đúng tốc độ.'},
         back='Anh Quang gãi đầu: “Ừ thì… làm đúng luật.” Bản kế hoạch dầu về như cũ.',
         give='Bạn bớt dầu dự phòng. Hôm đó giông ở đảo, phải bay chờ, hạ cánh với cái đồng hồ dầu đỏ chót. Phòng an toàn mời lên họp.'),
    dict(id='pl-mel', kind='corner', rank='boss', emoji='🔧', title='“Ký lùi sổ kỹ thuật giùm anh”', who='Anh Bảo · giám sát kỹ thuật ca đêm',
         text='“Cái đèn cảnh báo chập chờn ấy mà, sửa sau. Em ký nhận tàu đi, anh ghi lỗi vào sổ tối nay, ngày giờ lùi lại chút là được.”',
         push=['“Ký một chữ thôi mà khó thế. Chú Mẫn còn ký cho anh bao lần.”', '“Tàu đứng đất một giờ mất bao nhiêu tiền em biết không?”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=3,
         words={'alt': 'Gọi chú Mẫn kiểm tra, ghi sổ đúng giờ.'},
         back='Anh Bảo gọi chú Mẫn. Hai mươi phút sau đèn được thay, sổ ghi đúng giờ, tàu cất cánh sạch sẽ.',
         give='Bạn ký. Chiều đó đèn cảnh báo tắt hẳn giữa chặng, tổ bay phải quay về. Sổ kỹ thuật có chữ ký của bạn ở dòng sai giờ.'),
    dict(id='pl-drunk', kind='corner', rank='crew', emoji='🍺', title='Hơi men của cơ trưởng', who='Cơ trưởng Tài · bay thay chị Vân hôm nay',
         text='Anh Tài lên buồng lái, người thoang thoảng mùi bia: “Tối qua nhậu sinh nhật thằng bạn, giờ tỉnh rồi. Em đừng nói ai nha, anh em với nhau.”',
         push=['“Anh tỉnh mà! Em muốn anh mất việc à?”', '“Báo lên là cả tổ ở nhà, khách về đâu? Nghĩ cho khách đi.”'],
         persist=(3, 3), mood=(1, 2), weight=2, severe=4, min_day=4,
         words={'alt': 'Anh nghỉ đi, gọi cơ trưởng dự bị.'},
         back='Anh Tài im một lúc rồi tự gọi điều phái xin nghỉ. Cơ trưởng dự bị lên thay, chuyến trễ 40 phút.',
         report='Bạn báo điều phái. Anh Tài được đưa đi thổi nồng độ cồn, tổ dự bị lên thay. Không ai trách người báo: đó là luật để giữ mạng người.',
         give='Bạn im lặng và bay cùng anh Tài. Lúc hạ cánh anh chạm bánh mạnh như đập. Trạm kiểm tra ngẫu nhiên ở sân bay đến đang chờ sẵn…'),
    dict(id='pl-log', kind='corner', rank='boss', emoji='📒', title='Sửa giờ bay trong sổ', who='Chị Nga · phòng lập lịch bay',
         text='“Tuần này em bay vượt giờ quy định hai tiếng. Em sửa giờ trong sổ bớt đi, không thì chị phải xếp người khác, rối lắm.”',
         push=['“Ai cũng sửa, có mình em trong sạch à?”', '“Sửa hay không tùy em, nhưng lịch tháng sau chị xếp sao thì đừng kêu.”'],
         persist=(2, 3), mood=(0, 1), weight=2, severe=3,
         words={'alt': 'Chị xếp người bay thay chặng cuối tuần giúp em.'},
         back='Chị Nga thở dài, xếp người bay thay. Sổ của bạn vẫn đúng từng phút.',
         give='Bạn sửa sổ. Ba tuần sau cục hàng không thanh tra, giờ bay lệch với dữ liệu hộp đen. Cả hai cùng lên giải trình.'),
    # --- awkward, pushy, strange demands
    dict(id='pl-vip', kind='demand', rank='pax', emoji='🕶️', title='Sếp to bắt giữ máy bay', who='Ông Long · tổng giám đốc bất động sản',
         text='Điều phái chuyển máy: “Giữ máy bay 25 phút cho tao. Tao là ai mày biết không? Tao mua cả cái hãng này cũng được.”',
         push=['“Mày làm phi công được mấy năm? Để tao gọi thẳng chủ tịch.”', '“Cả tàu chờ tao chút thì chết ai? Giữ máy bay!”'],
         persist=(2, 3), mood=(1, 2), weight=3, breach=1, fx={'give': {'patience': -12}},
         words={'alt': 'Đổi sang chuyến sau, chỗ đẹp nhất.', 'rule': 'Giờ cất cánh đã xin với đài, không giữ riêng ai.'},
         back='Ông Long chửi một tràng rồi lên chuyến sau. Sáu mươi tám khách còn lại cất cánh đúng giờ.',
         give='Tàu chờ 25 phút. Ông Long lên muộn, không một câu xin lỗi; sáu mươi tám người còn lại nhìn cổng lên tàu bằng ánh mắt hình viên đạn.'),
    dict(id='pl-selfie', kind='demand', rank='pax', emoji='🤳', title='“Cho vào buồng lái chụp tấm hình”', who='Anh khách hơi say · hàng ghế 8',
         text='Lúc lên tàu, anh khách mùi bia gõ cửa buồng lái: “Cho anh vào chụp với cơ trưởng tấm hình, anh bo 500 cành luôn.”',
         push=['“Chụp tấm thôi mà làm như bí mật quốc gia. Keo vl.”', '“Không cho thì anh đứng đây luôn, không ai đóng cửa được.”'],
         persist=(1, 3), mood=(1, 2), weight=2, breach=2,
         words={'alt': 'Hạ cánh rồi chụp ở chân cầu thang nhé.'},
         back='Anh khách lầm bầm về chỗ. Hạ cánh xong anh chụp với tàu ở chân cầu thang, cười tít mắt.',
         give='Anh khách vào buồng lái, suýt vịn trúng cần ga. Chị Vân quay lại, mặt lạnh tanh: “Ai cho vào?”'),
    dict(id='pl-propose', kind='demand', rank='pax', emoji='💐', title='Cầu hôn qua loa lúc hạ độ cao', who='Anh Tuấn · khách ghế 11C',
         text='“Anh phi công ơi, lúc máy bay hạ cánh anh đọc qua loa giúp em: ‘Linh ơi, lấy anh nhé!’ Em chuẩn bị nhẫn rồi 🥹”',
         push=['“Đọc có một câu thôi mà, lãng mạn thế cơ mà!”', '“Anh không đọc là em mất vợ đó, anh chịu trách nhiệm nha.”'],
         persist=(0, 2), mood=(0, 1), weight=2, breach=1,
         words={'rule': 'Lúc hạ độ cao buồng lái chỉ lo bay.', 'alt': 'Đỗ ở bến rồi tổ bay đọc cho cả khoang cùng vỗ tay.'},
         back='Tàu đỗ xong, chị Thu đọc lời cầu hôn qua loa. Cả khoang vỗ tay, cô Linh khóc nhòe mascara.',
         give='Bạn đọc lời cầu hôn đúng lúc đang tiếp cận. Đài gọi mà buồng lái trả lời chậm hai nhịp. Chị Vân không vỗ tay.'),
    dict(id='pl-durian', kind='demand', rank='pax', emoji='🍈', title='Ba trái sầu riêng xách tay', who='Chú Sáu · khách về quê',
         text='“Ba trái sầu riêng Ri6 chín cây, chú gói kỹ rồi. Cho chú xách lên khoang nha con, hôi vl nhưng mà ngon.”',
         push=['“Gói ba lớp nilon rồi mà, mùi đâu mà mùi!”', '“Mấy đứa trẻ bây giờ khó tính quá. Hồi xưa đi xe đò mang cả con gà.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=1, fx={'give': {'patience': -8}},
         words={'alt': 'Gửi khoang hàng, đóng thùng kín giúp chú.'},
         back='Chú Sáu gửi sầu riêng xuống khoang hàng, thùng đóng kín. Tới nơi còn chia cho tổ bay một múi.',
         give='Sầu riêng lên khoang. Mười phút sau cả tàu nồng nặc, hai khách xin túi nôn, một khách đòi xuống.'),
    dict(id='pl-swap', kind='demand', rank='crew', emoji='🔁', title='Đổi ca lần thứ ba', who='Minh · cơ phó cùng khóa',
         text='“Ông ơi, đổi ca sáng mai cho tôi nha, tôi đi đám cưới. Lần này thật, lần trước là đám giỗ, lần trước nữa là đám hỏi.”',
         push=['“Anh em mà tính toán thế. Bạn bè kiểu gì vậy.”', '“Thôi, ông không đổi thì tôi xin ốm vậy, để điều phái tìm người.”'],
         persist=(1, 2), mood=(0, 1), weight=2, fx={'give': {'patience': -4}},
         words={'alt': 'Đổi được, nhưng qua điều phái, tuần sau ông trả ca.', 'rule': 'Đổi ca phải qua điều phái mới đúng.'},
         back='Minh làm đơn đổi ca qua điều phái, hứa tuần sau trả. Lần này ghi giấy trắng mực đen.',
         give='Bạn đổi ca, không giấy tờ. Sáng hôm sau cả hai cùng có tên trong lịch, điều phái gọi điện chửi từ 4 giờ sáng.'),
    dict(id='pl-parcel', kind='demand', rank='boss', emoji='📦', title='Thùng hàng “của sếp” trong buồng lái', who='Anh Quang · trưởng phòng khai thác',
         text='“Có thùng hàng nhỏ của sếp tổng gửi ra đảo. Em để dưới ghế buồng lái giùm anh, khỏi soi chiếu, khỏi khai báo, nhanh.”',
         push=['“Sếp tổng đấy em. Em biết mình đang nói không với ai không?”', '“Có gì anh chịu. Để ở đó thôi, đâu cần mở.”'],
         persist=(2, 3), mood=(0, 1), weight=2, breach=3,
         words={'rule': 'Hàng lên tàu phải soi chiếu, có trong bảng kê.', 'alt': 'Gửi hàng qua quầy hàng hóa, em ký nhận nhanh.'},
         back='Thùng hàng đi qua máy soi như mọi thùng khác. Bên trong là… mười hộp bánh pía. Anh Quang đỏ mặt.',
         give='Bạn để thùng dưới ghế. Ra đảo, an ninh sân bay kiểm tra ngẫu nhiên buồng lái. “Hàng không khai báo” đứng tên bạn.'),
    dict(id='pl-kiet', kind='demand', rank='pax', emoji='⏱️', title='“Bay tắt cho kịp họp đi”', who='Anh Kiệt · khách đi công tác', npc=5,
         text='“Chín giờ tôi họp với đối tác. Các anh bay tắt qua mây, cắt góc chút cho nhanh. Tôi là khách, tôi trả tiền.”',
         push=['“Có mười phút thôi mà cũng không làm được? Hãng gì mà cùi bắp.”', '“Tôi sẽ viết review một sao, kể từng phút một.”'],
         persist=(1, 3), mood=(1, 2), weight=2, breach=1,
         words={'rule': 'Đường bay do đài chỉ huy, không ai bay tắt.', 'alt': 'Tôi báo mặt đất đặt xe đón anh sẵn ở chân cầu thang.'},
         back='Anh Kiệt hừ một tiếng rồi đeo tai nghe. Tới nơi, xe đón đã đứng chờ; anh gật đầu cụt lủn thay lời cảm ơn.',
         give='Bạn xin đài bay tắt, bị từ chối, rồi cố xin thêm lần nữa. Chị Vân tắt micro, nhìn bạn: “Mình lái máy bay, không lái taxi.”',
         review={'back': [4, 'Không bay nhanh hơn được, nhưng có xe đón sẵn. Tạm chấp nhận.'], 'stuck': [1, 'Hãng bay gì mà khách nói không ai nghe. Một sao.']}),
    dict(id='pl-press', kind='demand', rank='pax', emoji='🎤', title='Phóng viên đòi “nói đại một câu”', who='Anh Phong · phóng viên báo mạng',
         text='“Vụ tàu hạ cánh lệch tim đường băng tuần trước ấy, anh nói đại một câu đi, giấu tên cũng được. Cả nước đang hóng.”',
         push=['“Anh không nói thì em viết ‘phi công né tránh’, anh thấy sao?”', '“Một câu thôi, off the record. Anh em cả mà.”'],
         persist=(1, 3), mood=(0, 1), weight=1, breach=2, at='any',
         words={'rule': 'Phát ngôn là việc của phòng truyền thông hãng.', 'alt': 'Anh liên hệ phòng truyền thông, em cho số.'},
         back='Anh Phong lấy số phòng truyền thông. Bài báo hôm sau có đủ thông tin chính thức, không có tên bạn.',
         give='Bạn “nói đại một câu”. Sáng mai câu đó thành tít bài, kèm ảnh bạn làm mờ không kỹ. Phòng pháp chế gọi.'),
    # --- family and the phố
    dict(id='pl-mom', kind='demand', rank='kin', emoji='🦑', title='Mẹ đặt hàng Phú Quốc', who='Mẹ · ở nhà', at='open',
         text='Mẹ gọi 5 giờ sáng: “Con bay Phú Quốc thì xách tay về cho mẹ 5 ký mực khô với hai can nước mắm nhĩ nha. Phi công mà, ai dám kiểm tra con.”',
         push=['“Hai can thôi mà. Con làm phi công chứ có phải làm hải quan đâu.”', '“Nuôi con lớn chừng này nhờ có hai can nước mắm cũng không được.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=1,
         words={'rule': 'Chất lỏng quá 100 ml không lên khoang được mẹ ơi.', 'alt': 'Con gửi hàng ký gửi về, mẹ nhận ở nhà.'},
         back='Mẹ lầm bầm “con với cái”, rồi vẫn chỉ tên chỗ bán nước mắm ngon nhất. Hàng ký gửi về tới nhà trước cả bạn.',
         give='Hai can nước mắm vào vali xách tay. Máy soi ở Phú Quốc kêu inh ỏi, cả tổ bay chờ bạn giải trình với an ninh.'),
    dict(id='pl-tickets', kind='demand', rank='kin', emoji='🎟️', title='Chú Bảy xin vé nội bộ', who='Chú Bảy · hàng xóm đầu hẻm', at='open',
         text='“Cháu làm phi công, lo cho chú bốn vé giá nội bộ đi Phú Quốc tuần sau. Chú nói là bà con, ai biết đâu.”',
         push=['“Có bốn vé mà làm khó. Hồi nhỏ chú cõng mày đi tiêm chủng đó.”', '“Thôi được, ba vé. Không thì cả hẻm biết mày chảnh.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Vé nhân viên chỉ cho người nhà trong sổ.', 'alt': 'Cháu săn vé khuyến mãi giúp chú, rẻ gần bằng.'},
         back='Chú Bảy càu nhàu nhưng nhận link khuyến mãi. Tuần sau cả nhà chú đi Phú Quốc, gửi về một bịch ghẹ.',
         give='Bạn khai chú Bảy là “bà con”. Phòng nhân sự rà danh sách vé nội bộ, gọi bạn lên hỏi “bà con kiểu gì mà bốn người”.'),
    dict(id='pl-match', kind='demand', rank='kin', emoji='💘', title='Cô Sáu mai mối', who='Cô Sáu · bà mai của hẻm', at='open',
         text='“Phi công mà ế là phí của giời. Tối mai 9 giờ đi xem mắt con bé nhà bên, không đi là cô giận cả đời.”',
         push=['“9 giờ tối chứ có phải nửa đêm đâu. Trẻ khỏe mà!”', '“Nó đã mua váy mới rồi. Mày không đi thì cô biết ăn nói sao?”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Mai bay sớm, tổ bay phải ngủ đủ giờ.', 'alt': 'Cuối tuần cháu nghỉ, gặp buổi trưa được không cô?'},
         back='Cô Sáu dời sang trưa chủ nhật. Con bé nhà bên cũng là… kiểm soát viên không lưu. Hai người nói chuyện tần số radio cả buổi.',
         give='Bạn đi xem mắt tới 11 giờ đêm. Sáng hôm sau 4 giờ dậy bay, mắt díp lại suốt bản tin thời tiết.', fx={'give': {'patience': -4}}),
    dict(id='pl-rent', kind='demand', rank='kin', emoji='🏠', title='Chủ nhà tăng giá “vì cháu lương cao”', who='Bà Tư · chủ nhà trọ', at='open',
         text='“Làm phi công lương nghìn đô mà ở phòng này rẻ quá. Tháng sau bà tăng 30% nha, người giàu thì chịu khó chút.”',
         push=['“Phòng có cửa sổ nhìn ra hẻm đó, view đẹp vậy mà.”', '“Không chịu thì dọn, thiếu gì người thuê.”'],
         persist=(1, 3), mood=(0, 1), weight=1, fx={'give': {'money': -25}},
         words={'rule': 'Hợp đồng ghi tăng tối đa 5% mỗi năm bà ơi.', 'alt': 'Cháu ký thêm một năm, bà giữ giá nhé.'},
         back='Bà Tư tặc lưỡi, giữ giá, còn dặn “có vé rẻ nhớ bà”.', give='Bạn chịu tăng giá. Bà Tư đi kể khắp hẻm, tuần sau phòng bên cũng tăng giá “theo phi công”.'),
    dict(id='pl-cousin', kind='demand', rank='kin', emoji='🧑‍🎓', title='Em họ xin “nói một câu”', who='Tí · em họ mới tốt nghiệp', at='open',
         text='“Anh ơi xin cho em vào hãng làm tiếp viên đi. Em không cần thi đâu, anh nói với sếp một câu là được mà.”',
         push=['“Anh làm phi công mà một câu cũng không nói được à? Vô dụng thế.”', '“Mẹ em bảo anh chảnh lắm rồi, anh đừng để cả họ nói nữa.”'],
         persist=(1, 2), mood=(0, 1), weight=1, breach=1,
         words={'rule': 'Vào hãng ai cũng phải thi, anh cũng thi.', 'alt': 'Anh ôn cho em mấy buổi phỏng vấn.'},
         back='Tí càu nhàu nhưng ngồi ôn với bạn ba tối. Tháng sau Tí đỗ vòng một, gọi khoe cả họ.',
         give='Bạn “nói một câu” với trưởng phòng. Tí đi phỏng vấn thì trượt thẳng, còn tên bạn thì bị ghi “can thiệp tuyển dụng”.'),
    # --- the office bargains: accept what the rules allow, say why, bring the union
    dict(id='pl-extra', kind='bargain', rank='boss', emoji='📈', title='Bay thêm chặng chiều', who='Anh Quang · trưởng phòng khai thác',
         text='“Tuần này thiếu người. Em bay thêm 3 chặng chiều nhé, vượt giờ tí không sao đâu, ai mà đo.”',
         push=['“Thôi được, anh bớt cho. Nhưng thiếu người thật đấy, em không nhận thì ai?”', '“Người ta mong có việc mà không có. Em cứ làm giá.”'],
         ask=3, limit=1, unit='chặng', pay=10, tire=1, cost=12, weight=3, persist=(1, 2), mood=(0, 1),
         words={'rule': 'Vượt giờ bay tối đa là trái luật.', 'alt': 'Em nhận một chặng, gọi tổ dự bị cho hai chặng kia.'},
         lawful='Anh Quang hậm hực gọi tổ dự bị. Quy định giờ bay không phải để “ai mà đo”.'),
    dict(id='pl-leave', kind='bargain', rank='boss', emoji='🧧', title='Hủy phép Tết', who='Chị Nga · phòng lập lịch bay',
         text='“Tết này em trực hết nha, người có gia đình về quê hết rồi. Hủy 3 ngày phép của em, chị ghi nợ.”',
         push=['“Em còn trẻ, Tết nào chả là Tết. Chị bớt một ngày.”', '“Không ai muốn trực Tết cả em. Mỗi mình em ngoại lệ à?”'],
         ask=3, limit=1, unit='ngày phép', pay=7, tire=1, cost=10, weight=2, persist=(1, 2), mood=(0, 1), at='open',
         words={'rule': 'Phép năm là quyền, chỉ đổi khi em đồng ý.', 'alt': 'Em trực mùng 1, đổi lại nghỉ bù ra Giêng.'},
         lawful='Chị Nga xếp lại lịch, luân phiên cả tổ. Bạn ăn Tết ở nhà hai ngày, trực một ngày.'),
    dict(id='pl-sim', kind='bargain', rank='boss', emoji='🕹️', title='Tự đóng tiền bay mô phỏng', who='Trung tâm huấn luyện Cánh Cò',
         text='“Hãng cắt ngân sách. Kỳ kiểm tra tới các cơ phó tự đóng tiền 3 buổi bay mô phỏng nhé. Không đóng thì xếp cuối danh sách thăng hạng.”',
         push=['“Đầu tư cho bản thân mà em. Hai buổi thôi cũng được.”', '“Ai cũng đóng. Không đóng là tự loại mình.”'],
         ask=3, limit=0, unit='buổi tự đóng tiền', pay=-8, tire=0, cost=8, weight=1, persist=(1, 2), mood=(0, 1), at='open',
         words={'rule': 'Huấn luyện định kỳ là trách nhiệm của hãng.', 'alt': 'Em học lý thuyết thêm, buổi mô phỏng theo lịch hãng.'},
         lawful='Trung tâm rút lại thông báo sau khi công đoàn hỏi. Huấn luyện bắt buộc thì hãng trả, như luật.'),
]

# ---------------------------------------------------------------- Tiếp viên (people: 0 Thu, 1 Kiệt, 2 bà Chín, 3 ông Tư, 4 chị Mai, 5 chú Hải, 6 Vân, 7 Vy)
CABIN = [
    # --- harassment: set the line, bring in the purser, report (always legitimate)
    dict(id='fa-3c', kind='harass', rank='pax', emoji='🔔', title='Chuông gọi “em gái xinh”', who='Anh khách ghế 3C', follow='fa-3c-back',
         text='Khách 3C bấm chuông lần thứ sáu: “Em gái xinh ơi, cho anh xin số đi. Không cho là anh bấm chuông tới hạ cánh.”',
         push=['“Làm giá à? Tiếp viên mà khó tính thế ai thèm.”', '“Anh nói với sếp em là em phục vụ thái độ đấy nhé.”'],
         persist=(2, 3), mood=(0, 2), weight=3,
         back='3C thôi bấm chuông, quay ra ngủ. Chị Thu nháy mắt: “Lần sau cứ báo chị luôn nha.”',
         report='Bạn báo chị Thu, ghi biên bản. Hạ cánh, đại diện hãng mời 3C ở lại làm việc; tên hắn vào danh sách theo dõi.'),
    dict(id='fa-3c-back', kind='harass', rank='pax', emoji='😒', title='Anh 3C lại bay chuyến này', who='Anh khách 3C hôm trước', need_mark='fa-3c-back',
         text='Anh 3C hôm trước lại bay chuyến này, nhìn bạn cười nhếch mép: “Lại gặp nhau rồi. Duyên đấy em. Hôm nay cho số chưa?”',
         push=['“Hôm trước em chưa trả lời mà. Anh kiên nhẫn lắm.”', '“Anh nhớ lịch bay của em rồi đấy.”'],
         persist=(3, 3), mood=(0, 1), weight=4, min_day=3, follow='fa-3c-back',
         report='Lần này bạn báo ngay. Hãng đối chiếu biên bản, cấm bay 3C một năm. Chị Thu: “Thấy chưa, báo là có tác dụng.”'),
    dict(id='fa-hand', kind='harass', rank='pax', emoji='✋', title='Bàn tay “vô tình”', who='Ông khách ghế 9A', follow='fa-hand-back',
         text='Lúc bạn đưa ly nước, ông khách 9A cố nắm lấy tay bạn: “Tay mềm thế em. Ngồi xuống đây nói chuyện chút đã.”',
         push=['“Đùa tí mà căng thế. Gái bây giờ khó tính ghê.”', 'Ông ta lại giơ tay chặn xe đẩy: “Chưa trả lời anh mà đi đâu.”'],
         persist=(2, 3), mood=(0, 1), weight=2),
    dict(id='fa-hand-back', kind='harass', rank='pax', emoji='✋', title='Ông 9A lại chặn xe đẩy', who='Ông khách 9A hôm trước', need_mark='fa-hand-back',
         text='Ông khách 9A hôm trước lại ngồi đúng hàng ghế bạn phục vụ, chìa tay ra cười: “Hôm nay tay còn mềm không em?”',
         push=['“Làm gì mà mặt lạnh thế.”', '“Anh là khách quen của hãng đấy.”'], persist=(3, 3), mood=(0, 1), weight=4, min_day=3, follow='fa-hand-back'),
    dict(id='fa-photo', kind='harass', rank='pax', emoji='📸', title='Ảnh chụp lén lên story', who='Cậu khách ghế 14B',
         text='Cậu khách 14B chụp lén lúc bạn cúi cất hành lý, đăng story: “Tiếp viên hãng Cò nhìn cũng được đấy 🔥”, còn tag tên hãng.',
         push=['“Chụp tí mà, có lộ gì đâu. Ảnh đẹp mà em.”', '“Xóa gì mà xóa, điện thoại anh, story anh.”'],
         persist=(1, 3), mood=(0, 2), weight=2,
         words={'stop': 'Xóa ảnh ngay.', 'rule': 'Chụp, đăng ảnh người khác không xin phép là vi phạm.'},
         back='14B xóa ảnh trước mặt bạn, ngồi im tới lúc hạ cánh.',
         report='Chị Thu lập biên bản, hãng gửi yêu cầu gỡ ảnh. Story biến mất trước khi tàu hạ cánh.'),
    dict(id='fa-drunk', kind='harass', rank='pax', emoji='🍻', title='Nhóm khách say trêu đồng phục', who='Nhóm khách say hàng 12',
         text='Nhóm khách say hàng 12 huýt sáo mỗi lần bạn đi qua: “Váy ngắn thế em? Hãng may đồng phục cho khách ngắm à?” Cả hàng cười ầm.',
         push=['“Khen mà cũng dỗi. Đùa tí mà mặt nặng thế.”', 'Một người chìa chân chặn lối đi, cả nhóm lại cười.'],
         persist=(2, 3), mood=(1, 2), weight=2,
         back='Cả nhóm im bặt khi chị Thu đứng cạnh bạn. Tới lúc hạ cánh không ai dám huýt thêm tiếng nào.',
         report='Bạn báo chị Thu và cơ trưởng. Hạ cánh, an ninh sân bay mời cả nhóm lên làm việc. Cơ trưởng Vân nói qua loa: “Cảm ơn tổ tiếp viên.”'),
    dict(id='fa-dm', kind='harass', rank='pax', emoji='💬', title='Tin nhắn không dứt', who='Anh khách chuyến hôm qua', at='open',
         text='Khách chuyến hôm qua tìm ra Facebook của bạn, nhắn 40 tin từ đêm: “Đi cà phê không em? Không đi anh chê hãng trên mạng.”',
         push=['“Seen mà không rep à? Anh nhớ tên em, nhớ cả số hiệu chuyến bay.”', '“Anh gửi ảnh em cho bạn anh xem rồi đấy.”'],
         persist=(2, 3), mood=(0, 1), weight=2,
         words={'stop': 'Chặn, không nhắn nữa.', 'rule': 'Nhắn tin đe dọa là vi phạm, tôi sẽ báo.'},
         back='Bạn chặn tài khoản. Trang cá nhân để chế độ riêng tư. Đêm đó ngủ ngon.',
         report='Bạn gửi ảnh chụp tin nhắn cho phòng an ninh hãng. Hãng liên hệ công an, người kia xóa tài khoản trong ngày.'),
    dict(id='fa-vip', kind='harass', rank='pax', emoji='🥂', title='Khách VIP “bạn của sếp”', who='Ông Khánh · khách hạng thương gia',
         text='“Em ngồi cạnh anh nói chuyện chút đi. Anh là bạn thân tổng giám đốc hãng em đấy, một câu của anh là em lên tiếp viên trưởng.”',
         push=['“Anh đã nói anh là ai rồi. Em không ngồi là em thiệt.”', '“Để anh gọi cho tổng giám đốc ngay bây giờ nhé.”'],
         persist=(3, 3), mood=(0, 1), weight=2,
         words={'rule': 'Tiếp viên không ngồi cùng khách, ai cũng vậy.'},
         back='Ông Khánh cười khẩy rồi đeo kính ngủ. Ông không gọi ai cả.',
         report='Bạn báo chị Thu, ghi biên bản. Tuần sau tổng giám đốc gửi thư cho tổ bay: “Không có ‘bạn của sếp’ nào đứng trên quy định.”'),
    dict(id='fa-copilot', kind='harass', rank='crew', emoji='😏', title='Anh cơ phó mới buông lời', who='Anh Hưng · cơ phó mới chuyển về',
         text='Trước mặt cả tổ, anh cơ phó mới cười: “Tối nay ngủ lại Côn Đảo, em qua phòng anh xem phim nha. Đùa thôi… mà thật cũng được.”',
         push=['“Đùa mà cũng không hiểu à. Tiếp viên gì mà khô khan.”', '“Anh nói vậy ai cũng cười, có mình em làm căng.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Nói vậy với đồng nghiệp là quấy rối.'},
         back='Anh Hưng đỏ mặt, lí nhí xin lỗi. Cả tổ không ai cười nữa.',
         report='Bạn báo chị Thu và phòng nhân sự. Anh Hưng bị nhắc nhở bằng văn bản, phải học lại khóa ứng xử nơi làm việc.'),
    dict(id='fa-trip', kind='charm', rank='pax', emoji='🌸', title='“Đi Đà Lạt với anh”', who='Anh Việt · doanh nhân hay bay',
         text='“Tuần nào anh cũng bay chuyến em. Cuối tuần đi Đà Lạt với anh, anh lo hết, resort năm sao, em chỉ cần mang theo nụ cười.”',
         push=['“Anh nghiêm túc mà. Em đừng tỏ ra khó thế.”', '“Không Đà Lạt thì Phú Quốc. Em chọn đi.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Tổ bay không nhận lời mời riêng của khách.', 'alt': 'Cảm ơn anh, chúc anh chuyến đi vui.', 'duty': 'Em đang làm nhiệm vụ.'},
         back='Anh Việt gật gù, lần sau vẫn bay chuyến bạn, nhưng chỉ gọi nước suối.',
         give='Bạn nhận lời. Tuần sau ảnh resort năm sao lọt vào nhóm chat tiếp viên, phòng nhân sự nhắc về quy định quan hệ với khách.'),
    # --- the office: KPI, rotations, the gym, holidays
    dict(id='fa-kpi', kind='bargain', rank='boss', emoji='📈', title='KPI: chạy thêm chuyến đêm', who='Chị Loan · phòng điều hành tiếp viên',
         text='“Tháng này em mới 38 chuyến, team ai cũng 45. Tuần này nhận thêm 4 chuyến đêm nhé, không thì khó xét thưởng lắm.”',
         push=['“Thôi được, bớt cho em một chuyến. Chị cũng bị ép KPI mà.”', '“Người khác làm được, em thì than. Tính sao?”'],
         ask=4, limit=2, unit='chuyến đêm', pay=9, tire=1, cost=12, weight=3, persist=(1, 2), mood=(0, 1),
         words={'rule': 'Vượt giờ bay, giờ nghỉ tối thiểu rồi chị.', 'alt': 'Em nhận hai chuyến, tuần sau thêm một.'},
         lawful='Chị Loan thở dài, ghi hai chuyến. “Đúng luật thì chị chịu.”'),
    dict(id='fa-sales', kind='bargain', rank='boss', emoji='🧴', title='KPI bán nước hoa trên tàu', who='Anh Dũng · phòng kinh doanh',
         text='“Từ tuần này mỗi chuyến tiếp viên phải bán 5 hộp nước hoa miễn thuế. Thiếu thì trừ thưởng. Khách ngủ thì đánh thức mời.”',
         push=['“Bán hàng cũng là phục vụ mà em. Bốn hộp nhé.”', '“Đánh thức khách một tí có sao đâu, họ cảm ơn còn không kịp.”'],
         ask=5, limit=2, unit='hộp mỗi chuyến', pay=2, tire=1, cost=10, weight=2, persist=(1, 2), mood=(0, 1),
         words={'rule': 'Không đánh thức khách để bán hàng.', 'health': 'Vừa phục vụ vừa chạy doanh số, em không kham nổi.',
                'alt': 'Mời lúc phát đồ, khách nào quan tâm thì bán.'},
         lawful='Anh Dũng lẩm bẩm rồi sửa thông báo: “mời khách khi phù hợp”. Khách ngủ vẫn được ngủ.'),
    dict(id='fa-gym', kind='bargain', rank='boss', emoji='🏋️', title='Ép tập gym giữ dáng', who='Chị Hoa · trưởng phòng tiếp viên',
         text='“Em lên 2 ký rồi đấy. Đăng ký gym 5 buổi một tuần, tự túc phí nhé. Tháng sau cân lại, không đạt thì tạm nghỉ bay.”',
         push=['“Chị nói vì muốn tốt cho em thôi. Bốn buổi được chưa?”', '“Hình ảnh hãng là hình ảnh của em đấy. Đừng để khách chê.”'],
         ask=5, limit=2, unit='buổi gym tự túc', pay=-6, tire=0, cost=10, weight=2, persist=(1, 2), mood=(0, 1),
         words={'rule': 'Tiêu chuẩn bay là sức khỏe, không phải số cân.', 'health': 'Bác sĩ hãng khám em đủ sức khỏe rồi.',
                'alt': 'Em tập hai buổi, đi bộ lên xuống cầu thang tàu là đủ ạ.'},
         penalty='Chị Hoa xếp bạn vào lịch bay đêm liên tục “cho đến khi có ý thức”. Bị trừ {cost} xu thưởng.',
         lawful='Chị Hoa ậm ừ, rút lại chuyện “không đạt thì nghỉ bay”. Sức khỏe đủ bay thì bay.'),
    dict(id='fa-tet', kind='bargain', rank='boss', emoji='🧧', title='Trực hết Tết', who='Chị Loan · phòng điều hành tiếp viên', at='open',
         text='“Tết này em trực 3 ngày nhé. Em chưa chồng chưa con, về quê làm gì, để chị em có gia đình nghỉ.”',
         push=['“Chưa chồng thì Tết ở đâu chẳng thế. Hai ngày được không?”', '“Em ích kỷ thế. Ai cũng muốn về mà.”'],
         ask=3, limit=1, unit='ngày trực Tết', pay=8, tire=1, cost=10, weight=2, persist=(1, 2), mood=(0, 1),
         words={'rule': 'Lịch Tết phải luân phiên, không theo chuyện chồng con.', 'alt': 'Em trực mùng 1, mùng 2 về quê.'},
         lawful='Chị Loan xếp lại lịch luân phiên. Mùng 2 bạn về quê, mẹ nấu nồi thịt kho trứng chờ sẵn.'),
    dict(id='fa-weigh', kind='demand', rank='boss', emoji='⚖️', title='Cân trước ca bay', who='Chị Hoa · trưởng phòng tiếp viên', at='open',
         text='Sáng nay cả tổ bị gọi lên cân trước ca. Chị Hoa đọc to: “Em này hơn tháng trước 1,2 ký. Lên nữa là cho nghỉ bay nhé.”',
         push=['“Chị nói thẳng vì thương thôi. Nhịn ăn tối đi em.”', '“Đọc to cho cả tổ cùng cố gắng, có gì đâu mà ngại.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Cân nặng là chuyện riêng, tiêu chuẩn là sức khỏe.', 'alt': 'Có gì chị trao đổi riêng với em.', 'why': 'Tiêu chuẩn nào ghi vậy ạ?'},
         back='Chị Hoa gấp sổ, từ tuần sau không đọc to số cân nữa. Cả tổ nhìn bạn như nhìn anh hùng.',
         give='Bạn nhịn ăn tối ba ngày. Chuyến sáng thứ tư bạn hoa mắt ngay lúc đang làm mẫu an toàn.', fx={'give': {'patience': -4}}),
    dict(id='fa-smile', kind='demand', rank='boss', emoji='😁', title='Nụ cười tám răng, học không lương', who='Anh Tùng · phòng đào tạo',
         text='“Khách phản ánh em cười chưa đủ tươi. Thứ bảy lên học lại lớp ‘nụ cười tám răng’, không lương, không bù.”',
         push=['“Đào tạo là quyền lợi của em mà. Ai học chẳng tốt.”', '“Không học thì đánh giá quý này khó đẹp lắm.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         words={'rule': 'Học bắt buộc thì phải tính giờ làm.', 'why': 'Khách nào phản ánh, chuyến nào ạ?', 'alt': 'Em học trong giờ làm, tuần sau.'},
         back='Anh Tùng dời lớp vào giờ làm. Thứ bảy bạn ngủ tới 9 giờ.', give='Bạn học ngày thứ bảy. Ảnh “cười tám răng” của bạn được treo ở phòng đào tạo làm mẫu.'),
    # --- passengers: pushy, strange, rude
    dict(id='fa-upgrade', kind='demand', rank='pax', emoji='💺', title='“Cho anh lên hạng thương gia đi”', who='Anh Kiệt · khách đi công tác', npc=1,
         text='“Hàng đầu còn trống kìa. Cho anh lên ngồi đi, anh quen sếp em. Vali to thế này ngồi sau chật lắm.”',
         push=['“Ghế trống để làm cảnh à? Hãng gì cứng nhắc.”', '“Anh đi chuyến này mỗi tuần đấy. Nhớ mặt em rồi.”'],
         persist=(1, 3), mood=(1, 2), weight=2, breach=1,
         words={'rule': 'Đổi hạng ghế phải mua ở quầy.', 'alt': 'Em đổi anh lên hàng ghế thoát hiểm, rộng chân hơn.'},
         back='Anh Kiệt ngồi hàng ghế rộng chân, lầm bầm “cũng được”.', give='Bạn cho anh Kiệt lên hạng thương gia. Hai khách khác thấy vậy cũng đòi lên. Chị Thu lắc đầu.',
         review={'back': [4, 'Không được lên hạng trên, nhưng tiếp viên xếp chỗ rộng chân. Được.'], 'stuck': [2, 'Nói mãi không ai nghe. Hãng này cứng nhắc vl.']}),
    dict(id='fa-window', kind='demand', rank='pax', emoji='🪟', title='Bà muốn mở cửa sổ', who='Bà Chín · lần đầu đi máy bay', npc=2,
         text='“Cháu mở cái cửa sổ cho bà hít gió biển tí. Kín mít thế này bà ngột quá.”',
         push=['“Mở hé thôi cũng được mà cháu.”', '“Thế tắt máy lạnh đi, bà lạnh run rồi.”'],
         persist=(0, 2), mood=(0, 0), weight=2,
         words={'why': 'Bà thấy ngột ở đâu ạ?', 'alt': 'Cháu chỉnh quạt gió, mang cho bà cái chăn.', 'rule': 'Cửa sổ máy bay không mở được bà ơi.'},
         back='Bà Chín đắp chăn, quạt gió chỉnh nhẹ, lát sau ngủ khò.', review={'back': [5, 'Cô tiếp viên kiên nhẫn với bà già lẩm cẩm này ghê.']}),
    dict(id='fa-exit', kind='demand', rank='pax', emoji='👶', title='Bế em bé đòi ngồi hàng thoát hiểm', who='Chị Mai · bế bé Bơ', npc=4,
         text='“Chị ngồi hàng thoát hiểm cho rộng, bế con dễ hơn. Ghế trống mà em, cho chị ngồi đi.”',
         push=['“Có mỗi chị với con thôi mà, làm gì căng.”', '“Em không có con nên không hiểu đâu.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Hàng thoát hiểm không cho người bế trẻ nhỏ.', 'alt': 'Em đổi chị lên hàng 2, có chỗ để nôi.'},
         back='Chị Mai ngồi hàng 2, có chỗ đặt nôi. Bé Bơ ngủ ngon cả chặng.', give='Chị Mai ngồi hàng thoát hiểm. Chị Thu đi kiểm tra thấy, bắt đổi chỗ ngay trước giờ cất cánh; cả khoang chờ.',
         fx={'give': {'patience': -6}}),
    dict(id='fa-tiktok', kind='demand', rank='pax', emoji='🎬', title='Quay clip trong bếp tàu', who='Vy · nhóm bạn đi phượt', npc=7,
         text='“Chị ơi cho em quay 30 giây trong bếp tàu thôi, trend ‘một ngày làm tiếp viên’, mấy triệu view đó. Chị cũng nổi mà!”',
         push=['“Chị khó tính quá. Tiếp viên hãng khác còn nhảy cùng em.”', '“Không cho thì em quay lén, chị chịu nhé 😝”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Bếp tàu là khu vực tổ bay, khách không vào.', 'alt': 'Em quay ở ghế, chị tạo dáng chào cho một cảnh.'},
         back='Vy quay ở ghế, bạn chào một cái đúng chuẩn. Clip vẫn lên xu hướng.', give='Vy vào bếp tàu quay, vấp dây xe đẩy, đổ cả bình trà nóng. Clip lên xu hướng, kèm tiếng la của chị Thu.',
         review={'back': [5, 'Không được vào bếp nhưng chị tiếp viên dễ thương vl, clip vẫn đẹp.'], 'stuck': [2, 'Tiếp viên khó tính, không có tí vibe nào.']}),
    dict(id='fa-noodle', kind='demand', rank='pax', emoji='🍜', title='Mì tôm lúc tàu rung', who='Chú khách ghế 16D',
         text='Đèn thắt dây vừa sáng, chú 16D giơ gói mì: “Pha cho chú gói mì, nước sôi vào. Chú trả tiền mà, đói lắm rồi.”',
         push=['“Rung tí mà, pha nhanh tay lên.”', '“Tiền mất tật mang. Hãng gì mà khách đói không cho ăn.”'],
         persist=(1, 3), mood=(1, 2), weight=2, breach=2,
         words={'rule': 'Đèn thắt dây sáng, không pha nước sôi.', 'alt': 'Hết rung em pha ngay, giờ chú ăn tạm bánh nhé.'},
         back='Chú 16D ăn tạm bánh quy, hết rung thì có mì. Chú ăn sạch cả nước.', give='Bạn pha mì giữa lúc tàu rung. Nước sôi sóng sánh ra tay, bạn phỏng một vết đỏ au.'),
    dict(id='fa-karaoke', kind='demand', rank='pax', emoji='🎂', title='Hát mừng sinh nhật cả khoang', who='Nhóm khách hàng 10',
         text='“Hôm nay sinh nhật con bạn. Chị cho mượn loa, cả khoang cùng hát ‘Happy birthday’ với tụi em đi, 5 phút thôi!”',
         push=['“Khoang có ai ngủ đâu. Vui mà chị!”', '“Chị chán thế. Cả nhóm đòi đấy.”'],
         persist=(0, 2), mood=(0, 1), weight=1,
         words={'rule': 'Loa trên tàu chỉ để thông báo.', 'alt': 'Tổ bay chúc mừng lúc hạ cánh, tặng bạn một chiếc bánh.'},
         back='Hạ cánh, chị Thu đọc lời chúc qua loa, bạn mang ra chiếc bánh nhỏ cắm que pháo. Cả nhóm hét ầm.'),
    dict(id='fa-rude', kind='demand', rank='pax', emoji='🤬', title='“Cút mẹ mày đi, gọi đứa khác”', who='Ông khách ghế 7B',
         text='Hết bánh mì chay, ông khách 7B đập bàn: “Cút mẹ mày đi, gọi đứa khác ra đây. Không có bánh thì đền tiền!”',
         push=['“Mày nói lại xem nào? Tao mua vé chứ có xin đâu.”', '“Tao quay clip đăng lên cho cả nước xem cái hãng mất dạy này.”'],
         persist=(2, 3), mood=(2, 2), weight=2, fx={'give': {'money': -8}},
         words={'alt': 'Em còn xôi chay, hoặc hoàn tiền suất ăn ạ.', 'rule': 'Xúc phạm tổ bay, em phải báo trưởng tàu.'},
         back='Ông 7B hầm hầm nhận hộp xôi chay, lát sau ăn sạch không nói câu nào.', give='Bạn móc tiền túi đền cho ông 7B. Ông cầm tiền, chửi tiếp.'),
    # --- the crew
    dict(id='fa-demo', kind='corner', rank='crew', emoji='🦺', title='“Khỏi làm mẫu an toàn”', who='Chị Hạnh · tiếp viên trưởng thay ca',
         text='“Tuyến này khách đi quen rồi, khỏi làm mẫu an toàn. Chiếu video là được, mình còn kịp phát nước.”',
         push=['“Em mới vào nghề mà dạy chị à?”', '“Trễ là em chịu nhé. Làm nhanh cho chị.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=2,
         words={'rule': 'Làm mẫu an toàn là bắt buộc mỗi chuyến.', 'alt': 'Em làm mẫu, chị phát nước hàng đầu trước.'},
         back='Chị Hạnh chép miệng nhưng đứng làm mẫu cùng bạn. Hàng 17 có bà cụ lần đầu hỏi cách đeo mặt nạ.',
         give='Không ai làm mẫu. Tới lúc rung mạnh, hai khách không biết mặt nạ ở đâu, la hoảng.'),
    dict(id='fa-door', kind='corner', rank='crew', emoji='🚪', title='“Khỏi kiểm chéo cửa”', who='Anh Sơn · tiếp viên cùng ca',
         text='“Cửa anh gạt rồi, khỏi kiểm chéo. Trễ ba phút rồi đấy, cơ trưởng đang hỏi kìa.”',
         push=['“Anh làm mười năm chưa sai bao giờ.”', '“Em cứ nói ‘đã kiểm’ là được, ai biết.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=3,
         words={'speak': 'Mười giây thôi, mình kiểm chéo.', 'rule': 'Kiểm chéo cửa là bắt buộc.'},
         back='Bạn kiểm chéo: cần gạt cửa sau chưa vào hẳn chốt. Anh Sơn im lặng gạt lại.',
         give='Bạn báo “đã kiểm”. Lúc lăn ra, đèn cảnh báo cửa sau sáng đỏ. Tàu quay về bến.'),
    dict(id='fa-cover', kind='demand', rank='crew', emoji='🙊', title='Nói dối giùm đồng nghiệp', who='Trâm · tiếp viên cùng tổ',
         text='“Tí chị Thu hỏi thì bảo tao đi kiểm hàng ghế cuối nha. Tao ra ngoài gọi điện cho bồ, chia tay tới nơi rồi.”',
         push=['“Bạn bè mà mày thế à? Có một câu thôi.”', '“Mày nói thật với chị Thu là tao nghỉ chơi mày luôn.”'],
         persist=(1, 2), mood=(0, 2), weight=2, breach=1,
         words={'alt': 'Mày nói với chị Thu xin 5 phút, tao làm giùm phần mày.', 'rule': 'Tao không nói dối trưởng tàu được.'},
         back='Trâm xin chị Thu 5 phút. Chị Thu cho luôn 10, còn đưa khăn giấy.', give='Bạn nói dối chị Thu. Chị Thu đi ra cuối tàu, không thấy Trâm đâu, nhìn bạn rất lâu.'),
    # --- family and the phố
    dict(id='fa-aunt', kind='demand', rank='kin', emoji='🎟️', title='Dì xin giá vé nhân viên', who='Dì Tư · em mẹ', at='open',
         text='“Con xin cho dì giá vé nhân viên đi Đà Lạt nha. Dì khai là mẹ con, dì con cũng như mẹ con mà.”',
         push=['“Có cái vé mà cũng tính toán với dì.”', '“Mẹ con mà biết con đối xử với dì thế này…”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Vé nhân viên chỉ cho người có tên trong sổ.', 'alt': 'Con săn vé khuyến mãi cho dì, rẻ lắm.'},
         back='Dì Tư đi vé khuyến mãi, gửi về cho bạn một hộp mứt dâu.', give='Bạn khai dì là mẹ. Mẹ thật của bạn cũng đặt vé đi Đà Lạt cùng tuần, bằng đúng tên đó.'),
    dict(id='fa-lipstick', kind='demand', rank='kin', emoji='💄', title='Em gái đặt mười thỏi son', who='Út · em gái bán hàng online', at='open',
         text='“Chị mua giùm em 10 thỏi son miễn thuế trên máy bay, giá nhân viên nha. Em bán online, lời chia đôi.”',
         push=['“Có 10 thỏi thôi mà. Chị không thương em à?”', '“Người ta tiếp viên ai chẳng làm vậy.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Hàng miễn thuế không mua để bán lại.', 'alt': 'Chị tặng em một thỏi, mua đúng giá.'},
         back='Út nhận một thỏi son làm quà, đăng ảnh “quà của bà chị tiếp viên” lên mạng.', give='Bạn mua 10 thỏi giá nhân viên. Tháng sau hãng kiểm tra hóa đơn nội bộ, tên bạn nổi bần bật.'),
    dict(id='fa-marry', kind='demand', rank='kin', emoji='💒', title='Mẹ giục lấy chồng', who='Mẹ · ở quê', at='open',
         text='“28 tuổi rồi, suốt ngày bay nhảy. Cuối tuần về xem mắt con trai bác Hai, làm ngân hàng, nhà có ba tầng.”',
         push=['“Bay mãi rồi ai nuôi con lúc về già?”', '“Mẹ hứa với bác Hai rồi. Con làm mẹ mất mặt à?”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Chuyện chồng con để con tự quyết mẹ ạ.', 'alt': 'Con về ăn cơm với mẹ, gặp làm bạn thôi nhé.', 'why': 'Mẹ lo con điều gì nhất?'},
         back='Mẹ thở dài, bảo “thì về ăn cơm”. Bữa cơm hôm đó không nhắc chuyện chồng con, chỉ hỏi bay có mệt không.',
         give='Bạn về xem mắt. Con trai bác Hai hỏi câu đầu tiên: “Làm tiếp viên thì có được vé rẻ không em?”'),
    dict(id='fa-parcel', kind='demand', rank='kin', emoji='📦', title='Gói hàng không rõ gì của bà Tám', who='Bà Tám · hàng xóm đầu hẻm', at='open',
         text='“Cháu mang hộ gói này ra đảo cho con bà. Gói kỹ rồi, đừng mở, hàng dễ vỡ. Có đứa ra sân bay đón.”',
         push=['“Bà nuôi cháu từ bé, cháu nghi bà à?”', '“Cầm giùm có tí mà hỏi như công an.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=3,
         words={'rule': 'Tổ bay không mang hàng không rõ của người khác.', 'why': 'Trong đó có gì hả bà?', 'alt': 'Cháu gửi hàng qua bưu điện hàng không cho bà.'},
         back='Bà Tám mở gói ra: hai hũ mắm tép và một cuốn album ảnh. Gửi bưu điện hàng không, con bà nhận sau hai ngày.',
         give='Bạn cầm gói hàng. Máy soi báo động: trong có ba hũ mắm tép và một con dao làm bếp. Bạn giải trình với an ninh mất một tiếng.'),
]
