"""Thư viện – Lưu trữ phường Mây: content (people, shelves, books, readers' asks, rules, surprises, situations).

Rules live in game/careers/library.py. Everything here is fixed content; the jobs are rolled from it by day and
slot. Words are what the player reads: no developer words, one short line per thing. The ward, its library, its
rules (fines, fees, access levels) are fictional game rules.
"""
from __future__ import annotations

# ---------------------------------------------------------------- the people
# (name, role, note, persona). Index 0 is cô Nguyệt, who runs the library and the ward archive.
PEOPLE = [
    ('Cô Nguyệt', 'Phụ trách Thư viện – Lưu trữ phường', 'Ba mươi năm giữ sách, giữ hồ sơ của phường. Nhìn gáy sách là đọc được ký hiệu.', 'warm'),
    ('Ông Thạc', 'Cụ hưu đọc báo mỗi sáng', 'Sáu giờ đã đứng chờ cửa, ghế gần cửa sổ là “ghế của tôi”, ai ồn là ông lườm.', 'sour'),
    ('Vy', 'Sinh viên năm cuối ôn thi', 'Ôm laptop, trà sữa, ba cục sạc; ngủ gục trên bàn lúc nào không hay.', 'genz'),
    ('Chị Loan', 'Mẹ của hai bé Su và Bi', 'Dắt con đi giờ kể chuyện cuối tuần, cái gì cũng muốn “ưu tiên cho con chị”.', 'picky'),
    ('Anh Tuấn', 'Nghiên cứu sinh ngành sử', 'Viết luận án về phường Mây xưa, cần hồ sơ gì là cần “ngay bây giờ”.', 'picky'),
    ('Ông Bính', 'Phó Chủ tịch phường', 'Bận họp suốt, cần tài liệu là gọi thẳng xuống: “Đưa lên đây, nhanh!”', 'bossy'),
    ('Bà Xuân', 'Người dân xin trích lục hồ sơ', 'Lần đầu làm giấy tờ ở phường, giấy nào cũng mang theo một bản, trừ đúng bản cần.', 'quiet'),
    ('Đạt', 'Học sinh lớp 8 mê truyện tranh', 'Mượn truyện tranh nhiều nhất phường, trả trễ cũng nhiều nhất phường.', 'genz'),
]

# ---------------------------------------------------------------- the shelves (a simplified ten-class scheme)
CLASSES = [
    ('000', 'Tổng loại, tin học, bách khoa'), ('100', 'Triết học, tâm lý'), ('200', 'Tôn giáo'),
    ('300', 'Xã hội: luật, kinh tế, giáo dục, văn hóa dân gian'), ('400', 'Ngôn ngữ, từ điển tiếng'),
    ('500', 'Khoa học tự nhiên, toán'), ('600', 'Công nghệ: y học, nấu ăn, trồng trọt'),
    ('700', 'Nghệ thuật, nhiếp ảnh, thể thao'), ('800', 'Văn học: thơ, truyện, tiểu thuyết'), ('900', 'Lịch sử, địa lý'),
]
CLASS_IDS = tuple(k for k, _ in CLASSES)
CLASS_NAME = dict(CLASSES)
# The desk card next to the cart: the few rules people get wrong.
CLASS_TIPS = (
    'Ký hiệu xếp giá = lớp + 3 chữ đầu của TÊN tác giả (chữ cuối của họ tên), viết hoa, bỏ dấu.',
    'Truyện cổ tích, ca dao, tục ngữ (văn hóa dân gian) xếp lớp 300, không phải 800.',
    'Từ điển một thứ tiếng (chính tả, Anh – Việt) xếp 400; bách khoa nhiều chủ đề xếp 000.',
    'Sách cũ chưa chắc là sách hỏng: sách in xưa còn tốt là của quý, giữ lại.',
)

# id: (title, author, class, what shows on the cover and the back, junk reason or None, cover price)
# A junk reason means the book should be weeded out, not shelved: moc (mould), cu (outdated law/tech),
# lau (pirated photocopy), rach (torn, pages missing).
BOOKS = {
    'bep_mua': ('Bếp nhà ngày mưa', 'Trần Thị Mơ', '600', 'Công thức canh chua, cá kho, mẹo đi chợ.', None, 30),
    'goc_bang': ('Tuổi thơ dưới gốc bàng', 'Phạm Văn Gió', '800', 'Mười hai truyện ngắn về tuổi thơ trong phố.', None, 28),
    'mai_ngoi': ('Phố cổ qua từng mái ngói', 'Ngô Thu Hà', '900', 'Ảnh tư liệu, bản đồ phố xưa, các mốc năm.', None, 45),
    'lap_trinh': ('Lập trình cho người mới bắt đầu', 'Đỗ Quang Bình', '000', 'Máy tính, mã lệnh, bài tập từng bước.', None, 40),
    'hieu_minh': ('Hiểu mình trước khi hiểu người', 'Vũ An Nhiên', '100', 'Cảm xúc, thói quen, cách nghĩ của con người.', None, 32),
    'luat_gt': ('Sổ tay luật giao thông cho học sinh', 'Lý Văn Đường', '300', 'Biển báo, mũ bảo hiểm, quy định mới nhất.', None, 18),
    'tieng_anh': ('Tiếng Anh giao tiếp 30 ngày', 'Hoàng Lan Anh', '400', 'Mẫu câu chào hỏi, hỏi đường, gọi món.', None, 35),
    'troi_xanh': ('Vì sao bầu trời màu xanh?', 'Mai Khoa Học', '500', 'Ánh sáng, không khí, thí nghiệm nhỏ tại nhà.', None, 26),
    'cau_long': ('Cầu lông từ cơ bản đến nâng cao', 'Trịnh Văn Vũ', '700', 'Cách cầm vợt, bước chân, luật thi đấu.', None, 24),
    'co_tich': ('Truyện cổ tích làng ven sông', 'Bùi Thị Kể', '300', 'Truyện dân gian do các cụ trong làng kể lại, người soạn ghi chép.', None, 22),
    'dao_phat': ('Đạo Phật trong đời sống thường ngày', 'Lê Tịnh Minh', '200', 'Lời dạy, lễ chùa, ngày rằm, ăn chay.', None, 30),
    'mau_nuoc': ('Vẽ màu nước cho người bận rộn', 'Châu Họa Mi', '700', 'Cọ, giấy, pha màu, mười lăm bức tranh mẫu.', None, 38),
    'tho_ha': ('Thơ tình mùa hạ', 'Đinh Xuân Thi', '800', 'Năm mươi bài thơ ngắn.', None, 20),
    'nguoi_gia': ('Chăm sóc người cao tuổi tại nhà', 'Phan Thảo Y', '600', 'Dinh dưỡng, vận động, phòng té ngã.', None, 34),
    'vung_mien': ('Địa lý các vùng miền', 'Tạ Sơn Hà', '900', 'Núi, sông, khí hậu từng vùng, có bản đồ màu.', None, 42),
    'giao_duc': ('Dạy con từ ba tuổi', 'Kiều Minh Tâm', '300', 'Giáo dục sớm, nề nếp, chơi mà học.', None, 30),
    'chinh_ta': ('Từ điển chính tả tiếng Việt', 'Hồ Văn Chữ', '400', 'Viết đúng s hay x, dấu hỏi hay ngã.', None, 36),
    'rau_sach': ('Trồng rau sạch trên sân thượng', 'Lương Văn Lộc', '600', 'Đất, hạt giống, tưới nhỏ giọt.', None, 27),
    'bach_khoa': ('Bách khoa tri thức cho thiếu nhi', 'Quách Tổng Hợp', '000', 'Vũ trụ, động vật, máy móc, lịch sử: mỗi trang một chủ đề.', None, 60),
    'tuoi_teen': ('Tâm lý tuổi mới lớn', 'Ông Bình An', '100', 'Bạn bè, áp lực học, cảm xúc tuổi mười lăm.', None, 29),
    'toan_vui': ('Toán vui lớp năm', 'Lâm Số Học', '500', 'Đố vui, bài toán hình, mẹo tính nhẩm.', None, 19),
    'anh_dt': ('Chụp ảnh đẹp bằng điện thoại', 'Tô Ánh Sáng', '700', 'Bố cục, ánh sáng, chỉnh màu.', None, 25),
    'khoi_nghia': ('Những cuộc khởi nghĩa thời xưa', 'Đoàn Văn Sử', '900', 'Nhân vật, trận đánh, niên biểu.', None, 33),
    'tiet_kiem': ('Kinh tế gia đình: tiêu tiền thông minh', 'Trương Thu Hiền', '300', 'Lập ngân sách, tiết kiệm, tránh nợ.', None, 28),
    'kieu_1960': ('Truyện Kiều (bản in năm 1960)', 'Nguyễn Du', '800', 'Giấy ngả vàng nhưng còn nguyên, gáy chắc, không mốc.', None, 90),
    # junk that turns up in donations
    'thue_1998': ('Hỏi đáp luật thuế năm 1998', 'Ban Biên Soạn', '300', 'In năm 1998; quy định trong sách đã thay nhiều lần.', 'cu', 0),
    'chuong_photo': ('Tuyển tập truyện chưởng (bản photo)', 'Nhiều Tác Giả', '800', 'Giấy photo, đóng gáy lò xo, không có nhà xuất bản.', 'lau', 0),
    'nau_moc': ('Món ngon ba miền (bìa ố)', 'Lê Thị Bếp', '600', 'Bìa loang mốc xanh, mùi ẩm, trang dính vào nhau.', 'moc', 0),
    'tap_chi': ('Tạp chí thời trang số cũ', 'Nhiều Tác Giả', '700', 'Thiếu nửa quyển, xé mất hai mươi trang.', 'rach', 0),
    'win98': ('Giáo trình tin học Windows 98', 'Phạm Văn Máy', '000', 'Hướng dẫn phần mềm từ năm 1999, máy bây giờ không còn dùng.', 'cu', 0),
    'tieu_thuyet_lau': ('Tiểu thuyết ngôn tình (in lậu)', 'Không Rõ', '800', 'Chữ in nhòe, lệch trang, không có giấy phép xuất bản.', 'lau', 0),
}
GOOD_BOOKS = tuple(k for k, v in BOOKS.items() if not v[4])
JUNK_BOOKS = tuple(k for k, v in BOOKS.items() if v[4])
WEED = {'moc': 'Mốc ẩm nặng', 'cu': 'Lỗi thời, sai quy định mới', 'lau': 'Sách in lậu, photo', 'rach': 'Rách, mất trang'}

# ---------------------------------------------------------------- the circulation desk
# Books readers ask for at the desk: (title, call number, shelf note). Reference books never leave the room.
LOANS = {
    'tham_tu': ('Thám tử mèo mướp', '800 THA', 'Kệ thiếu nhi'),
    'an_mang': ('Án mạng ở ngõ Hoa Sữa', '800 SUA', 'Kệ văn học'),
    'muoi_hai': ('Mười hai ngày mưa', '800 MUA', 'Kệ văn học'),
    'thoi_quen': ('Thói quen nhỏ, đổi đời lớn', '100 LON', 'Kệ kỹ năng'),
    'quan_tien': ('Quản lý tiền cho người trẻ', '300 TRE', 'Kệ xã hội'),
    'pho_may': ('Phố Mây trăm năm', '900 MAY', 'Kệ lịch sử'),
    'vua_chua': ('Chuyện vua chúa kể cho trẻ', '900 TRE', 'Kệ thiếu nhi'),
    'com_nha': ('Cơm nhà mười lăm phút', '600 NHA', 'Kệ nấu ăn'),
    'banh_mi': ('Tự làm bánh mì ở nhà', '600 HAN', 'Kệ nấu ăn'),
    'thu_tinh': ('Thư tình gửi người phố cũ', '800 LIN', 'Kệ văn học'),
    'luyen_thi': ('Luyện thi vào lớp mười', '300 HOA', 'Kệ học tập'),
    'truyen_tranh': ('Truyện tranh Siêu nhân Lá Chuối tập 12', '800 CHU', 'Kệ truyện tranh'),
    'bach_khoa_lon': ('Bách khoa toàn thư (bộ 12 tập)', '000 TOA', 'Phòng tra cứu'),
    'dia_chi': ('Địa chí phường Mây', '900 MAY', 'Phòng tra cứu'),
    'tu_dien_lon': ('Đại từ điển tiếng Việt', '400 VIE', 'Phòng tra cứu'),
    'atlas': ('Tập bản đồ thế giới khổ lớn', '900 GIO', 'Phòng tra cứu'),
}
REFERENCE = ('bach_khoa_lon', 'dia_chi', 'tu_dien_lon', 'atlas')
# Genres and tastes for a recommendation: (genre, easy?, short?)
TASTE = {
    'tham_tu': ('trinh_tham', True, True), 'an_mang': ('trinh_tham', False, False),
    'muoi_hai': ('tinh_cam', True, True), 'thu_tinh': ('tinh_cam', False, False),
    'thoi_quen': ('ky_nang', True, True), 'quan_tien': ('ky_nang', False, False),
    'vua_chua': ('lich_su', True, True), 'pho_may': ('lich_su', False, False),
    'com_nha': ('nau_an', True, True), 'banh_mi': ('nau_an', False, False),
}
GENRE = {'trinh_tham': 'trinh thám', 'tinh_cam': 'tình cảm', 'ky_nang': 'kỹ năng sống', 'lich_su': 'lịch sử', 'nau_an': 'nấu ăn'}
# What a reader says when asked (clue lines by what is hidden).
TASTE_LAST = {
    'trinh_tham': '“Cuốn gần nhất mê là truyện phá án, đọc tới khuya để biết ai là hung thủ.”',
    'tinh_cam': '“Chị thích chuyện tình, đọc mà khóc được càng tốt.”',
    'ky_nang': '“Dạo này muốn đọc gì giúp mình sống gọn gàng hơn, đỡ lười.”',
    'lich_su': '“Hồi đi học mê môn sử, thích chuyện ngày xưa phố mình ra sao.”',
    'nau_an': '“Mới ra ở riêng, tối nào cũng úp mì, muốn tự nấu mà không biết bắt đầu.”',
}
TASTE_MOOD = {True: '“Đang mệt, muốn đọc gì nhẹ nhàng, dễ hiểu thôi.”', False: '“Muốn cuốn gì sâu sâu, đọc phải nghĩ mới đã.”'}
TASTE_TIME = {True: '“Chỉ đọc được lúc đi xe buýt, mỗi ngày hai mươi phút.”', False: '“Cuối tuần rảnh cả ngày, cuốn dày cũng được.”'}

FINE_DAY = 1          # xu per day late, per book (fictional ward rule)
FINE_CAP = 15         # at most this per book
CARD_FEE = 5          # renewing a reader's card for a year
COPY_FEE = 6          # a certified copy of an archive record
LOAN_DAYS = 14
LOAN_MAX = 3
DAMAGE = {'none': ('Còn nguyên', 0), 'pen': ('Bị viết bút bi vào trang', 3), 'torn': ('Rách gáy, bung vài trang', 5),
          'wet': ('Bị ướt nước, giấy phồng', 10), 'lost': ('Làm mất sách', None)}
REPAIR = {
    'bang_giay': ('Dán băng giấy sửa sách, ép lại gáy', 'torn'),
    'bang_keo': ('Dán băng keo trong cho nhanh', None),
    'tham': ('Kẹp giấy thấm từng trang, ép phẳng, hong chỗ mát', 'wet'),
    'say': ('Sấy máy sấy tóc, phơi nắng cho mau khô', None),
    'ghi': ('Ghi chú tình trạng vào phiếu sách, không tẩy xóa', 'pen'),
}
# A reader's reason when asked why the book is late: valid ones let you waive the late fee (with a note).
EXCUSE = {
    'vien': ('“Bà nằm viện hai tuần, giấy ra viện đây cháu xem.”', True),
    'lu': ('“Đợt ngập vừa rồi nhà ngập nửa mét, đi đâu cũng không được.”', True),
    'quen': ('“Quên thôi. Bận quá, ai mà nhớ.”', False),
    'di_choi': ('“Đi Đà Lạt chơi một tuần, mang theo đọc luôn.”', False),
    'none': ('“Thì trễ thôi, mấy ngày có sao đâu.”', False),
}

# ---------------------------------------------------------------- the reading room
# Offences: id → (emoji, title, what you see, best answers, fine answers, bad answers {how: sev}, safety, the offer label)
# Answers: soft (nhắc nhỏ tận nơi), rule (chỉ bảng nội quy), offer (a way that fits), out (mời ra khỏi phòng), ignore.
OFFENCES = {
    'on_ao': ('🗣️', 'Nhóm học bàn tán to', 'Bốn bạn chụm đầu tranh luận đề cương, cười ầm cả góc phòng.',
              ('soft', 'offer'), ('rule',), {'ignore': 1, 'out': 1}, False, 'Mời sang phòng thảo luận nhóm'),
    'dien_thoai': ('📞', 'Nghe điện thoại oang oang', 'Một anh nghe máy: “Alo! Ừ! Đang ở thư viện nè! NÓI TO LÊN!”',
                   ('offer', 'soft'), ('rule',), {'ignore': 1, 'out': 1}, False, 'Mời ra hành lang nghe máy'),
    'an_uong': ('🥖', 'Ăn bánh mì trên bàn đọc', 'Mùi pate thơm lừng, vụn bánh rơi lên trang sách mở.',
                ('offer', 'rule'), ('soft',), {'ignore': 1}, False, 'Mời ra bàn ăn ở sảnh'),
    'ngu_ngay': ('😴', 'Ngủ gục, ngáy to', 'Một bạn gục trên chồng sách, ngáy đều như máy bơm.',
                 ('soft',), ('offer',), {'ignore': 1, 'out': 1}, False, 'Mời ra ghế đá rửa mặt cho tỉnh'),
    'cap_doi': ('💕', 'Đôi bạn tình tứ quá trớn', 'Ở góc kệ cuối phòng, một đôi ôm nhau tình tứ, mấy bạn bàn bên ngại không dám nhìn.',
                ('soft',), ('rule',), {'ignore': 1}, False, 'Mời ra ghế đá sân sau nói chuyện riêng'),
    'giu_cho': ('🎒', 'Balo giữ chỗ cả buổi', 'Ba ghế để balo, áo khoác từ sáng, chủ đi đâu mất; người tới sau đứng chờ.',
                ('rule', 'offer'), ('soft',), {'ignore': 1}, False, 'Gom đồ vào tủ gửi, nhường ghế cho người chờ'),
    'day_sac': ('🔌', 'Dây sạc vắt ngang lối đi', 'Sợi dây sạc laptop căng ngang lối đi, cụ ông chống gậy suýt vấp.',
                ('offer', 'soft'), ('rule',), {'ignore': 2}, False, 'Chỉ ổ cắm sát bàn, gom dây gọn'),
    'hut_thuoc': ('🚬', 'Hút thuốc ở cầu thang thoát hiểm', 'Khói thuốc bay từ cầu thang thoát hiểm vào, sát cửa kho lưu trữ giấy.',
                  ('rule',), ('out', 'soft'), {'ignore': 3, 'offer': 1}, True, 'Mời ra hẳn ngoài cổng hút'),
    'chup_ca_cuon': ('📸', 'Chụp nguyên cuốn sách', 'Một bạn lật từng trang, chụp cả cuốn giáo trình mới bằng điện thoại.',
                     ('offer', 'rule'), ('soft',), {'ignore': 1}, False, 'Hướng dẫn photo một chương đúng quy định'),
    'xe_trang': ('📄', 'Xé trang sách mang về', 'Bạn ở bàn số 5 khẽ xé một trang bản đồ trong tập Atlas.',
                 ('rule',), ('soft',), {'ignore': 2, 'offer': 1}, False, 'Chỉ cách photo trang đó'),
    'tre_chay': ('🏃', 'Trẻ con chạy nhảy la hét', 'Hai bé đuổi nhau quanh kệ sách, hét vang, mẹ mải lướt điện thoại.',
                 ('offer', 'soft'), ('rule',), {'ignore': 1, 'out': 1}, False, 'Dắt hai bé sang góc thiếu nhi, nhắc mẹ bé'),
    'xem_video': ('📱', 'Xem video không tai nghe', 'Tiếng phim hành động bùm chíu từ điện thoại một anh, cả dãy bàn quay lại nhìn.',
                  ('offer', 'soft'), ('rule',), {'ignore': 1}, False, 'Cho mượn tai nghe của thư viện'),
    'gac_chan': ('🦶', 'Gác chân lên bàn đọc', 'Một anh duỗi chân, gác cả đôi dép lên bàn đọc chung.',
                 ('soft',), ('rule',), {'ignore': 1}, False, 'Mời ra ghế dài ở sảnh cho thoải mái'),
    'livestream': ('🎥', 'Livestream giữa phòng đọc', 'Một bạn quay livestream “học cùng mình”, máy quay lia cả mặt những người bàn bên.',
                   ('rule', 'soft'), ('offer',), {'ignore': 1}, False, 'Quay góc riêng, không quay người khác'),
    'nguoi_say': ('🍺', 'Người say vào phòng đọc', 'Một người say xỉn loạng choạng vào, nói lớn, vịn vào kệ sách.',
                  ('offer',), ('out', 'soft'), {'ignore': 2}, False, 'Mời ra sảnh ngồi, nhờ bảo vệ phường hỗ trợ'),
}
ANSWERS = ('soft', 'rule', 'offer', 'out', 'ignore')
ANSWER_LABEL = {'soft': '🤫 Nhắc nhỏ tận nơi', 'rule': '📋 Chỉ bảng nội quy', 'offer': '🙏', 'out': '🚪 Mời ra khỏi phòng', 'ignore': '🙈 Để kệ'}

# ---------------------------------------------------------------- the ward archive
# Access levels of a record and the decision at the window.
LEVELS = {'mo': 'Tài liệu mở: ai cũng được đọc, sao', 'rieng': 'Hồ sơ cá nhân: chỉ chính chủ, người thân có giấy tờ, người được ủy quyền',
          'han_che': 'Hạn chế: phải có lãnh đạo phường ký duyệt'}
DECISIONS = {'give': '✅ Cấp bản sao', 'paper': '📝 Hướng dẫn bổ sung giấy tờ', 'approve': '✍️ Trình lãnh đạo duyệt', 'refuse': '🙅 Từ chối, giải thích lý do'}
DOCS = {'cccd': 'Căn cước công dân', 'phieu': 'Phiếu yêu cầu khai thác (đã điền)', 'uy_quyen': 'Giấy ủy quyền có chứng thực',
        'uy_quyen_tay': 'Giấy ủy quyền viết tay (chưa chứng thực)', 'gioi_thieu': 'Giấy giới thiệu của trường', 'chung_tu': 'Giấy chứng tử của bố',
        'quan_he': 'Giấy tờ chứng minh là con', 'cong_van': 'Công văn của phòng ban'}
# (npc, title, what they say, the record, purpose, docs they bring, level, the right decision, fragile,
#  lost: None | 'misfiled' | 'lent', min_day)
REQUESTS = [
    (6, 'Bà Xuân xin bản sao giấy phép xây nhà', '“Bà cần bản sao giấy phép xây nhà năm 1996 để làm sổ đỏ, của chính nhà bà.”',
     'Giấy phép xây dựng nhà bà Xuân, 1996', 'Làm sổ đỏ nhà mình', ('cccd',), 'rieng', 'give', False, None, 1),
    (4, 'Anh Tuấn tìm biên bản họp tổ dân phố', '“Tôi cần biên bản họp tổ dân phố những năm 1976 – 1980 cho luận án.”',
     'Biên bản họp tổ dân phố số 3, 1976 – 1980', 'Nghiên cứu luận án', ('cccd', 'gioi_thieu'), 'mo', 'give', True, None, 1),
    (1, 'Ông Thạc xin bản sao giấy khen', '“Năm 1985 tôi được phường khen “gương mẫu”, cho tôi xin bản sao treo nhà.”',
     'Quyết định khen thưởng năm 1985', 'Kỷ niệm của chính mình', ('cccd',), 'rieng', 'give', True, None, 1),
    (7, 'Đạt xin bản đồ phường xưa', '“Cô giao bài tập lịch sử phường mình, cho em xem bản đồ phường hồi xưa với.”',
     'Bản đồ phường Mây năm 1960', 'Bài tập lịch sử', (), 'mo', 'give', True, None, 1),
    (3, 'Chị Loan xin hồ sơ đất nhà hàng xóm', '“Cho chị xem hồ sơ đất nhà bên cạnh, nó xây lấn sang nhà chị, chị cần bằng chứng.”',
     'Hồ sơ đất nhà số 14 ngõ 7', 'Tranh chấp với hàng xóm', ('cccd',), 'rieng', 'refuse', False, None, 2),
    (6, 'Bà Xuân làm thủ tục thừa kế', '“Bố tôi mất rồi, tôi cần sổ hộ khẩu cũ của bố để làm thừa kế.”',
     'Hồ sơ hộ khẩu cũ của ông Năm', 'Làm thủ tục thừa kế', ('cccd', 'chung_tu', 'quan_he'), 'rieng', 'give', False, None, 2),
    (6, 'Bà Xuân quên giấy tờ', '“Tôi xin hồ sơ hộ khẩu cũ của bố để làm thừa kế. Giấy chứng tử để quên ở nhà rồi.”',
     'Hồ sơ hộ khẩu cũ của ông Năm', 'Làm thủ tục thừa kế', ('cccd',), 'rieng', 'paper', False, None, 2),
    (4, 'Anh Tuấn cần lý lịch cán bộ cũ', '“Cho tôi chép lý lịch các cán bộ phường thập niên 90, tôi viết sách về họ.”',
     'Hồ sơ lý lịch cán bộ phường 1990 – 1999', 'Viết sách', ('cccd', 'gioi_thieu'), 'han_che', 'approve', False, None, 3),
    (5, 'Ông Bính cần hồ sơ dự án ngõ 7', '“Mang hồ sơ dự án chỉnh trang ngõ 7 lên phòng họp ngay, tôi đang họp dân.”',
     'Hồ sơ dự án chỉnh trang ngõ 7, 2019', 'Họp dân', ('cong_van',), 'mo', 'give', False, None, 2),
    (2, 'Vy xin danh sách chủ nhà', '“Công ty em làm môi giới, cho em xin danh sách chủ nhà cả phường kèm số điện thoại.”',
     'Sổ đăng ký nhà đất toàn phường', 'Tìm khách mua bán nhà', ('cccd',), 'rieng', 'refuse', False, None, 2),
    (3, 'Chị Loan nhờ luật sư xin hồ sơ', '“Luật sư của chị lấy hồ sơ nhà chị giùm, chị viết giấy ủy quyền tay rồi nè.”',
     'Hồ sơ nhà chị Loan', 'Làm hợp đồng mua bán', ('cccd', 'uy_quyen_tay'), 'rieng', 'paper', False, None, 3),
    (4, 'Anh Tuấn không thấy hồ sơ', '“Mục lục ghi hồ sơ ở hộp 12 mà mở ra không thấy! Mất rồi hay sao?”',
     'Sổ đăng ký chợ Mây năm 1975', 'Nghiên cứu luận án', ('cccd', 'gioi_thieu'), 'mo', 'give', True, 'misfiled', 3),
    (5, 'Ông Bính mượn bản gốc', '“Cho mượn bản gốc hồ sơ quy hoạch, mang ra Ủy ban họp, chiều trả.”',
     'Bản gốc hồ sơ quy hoạch phường 2015', 'Họp ở Ủy ban', ('cong_van',), 'han_che', 'approve', False, None, 3),
    (1, 'Ông Thạc tìm hồ sơ cũ', '“Hồ sơ nhà tôi năm 2002 đâu? Hôm trước còn thấy trong mục lục mà giờ không có.”',
     'Hồ sơ cấp số nhà ông Thạc, 2002', 'Làm lại số nhà', ('cccd',), 'rieng', 'give', False, 'lent', 4),
]
# Shelf codes of the archive boxes (the right one comes from the request; two neighbours as decoys).
FONDS = 'Phông UBND phường Mây'
# The five questions of cô Nguyệt's archive briefing (the training before the first request): (question, options, right)
TRAINING = [
    ('Người dân xin bản sao hồ sơ của chính mình, có căn cước. Cấp được không?',
     (('a', 'Được, ghi phiếu yêu cầu rồi cấp bản sao'), ('b', 'Không, phải xin lãnh đạo'), ('c', 'Đưa luôn bản gốc')), 'a'),
    ('Ai đó xin xem hồ sơ cá nhân của người khác, không có giấy ủy quyền.',
     (('a', 'Cho xem nhanh thôi'), ('b', 'Từ chối, giải thích cần giấy tờ hợp lệ'), ('c', 'Cho chụp một trang')), 'b'),
    ('Bản gốc trong kho có được mang ra khỏi thư viện không?',
     (('a', 'Được nếu người quen'), ('b', 'Không: chỉ cấp bản sao, bản gốc ở lại kho'), ('c', 'Được trong một buổi')), 'b'),
    ('Mở hộp hồ sơ cũ bụi bặm thì cần gì?',
     (('a', 'Găng tay vải và khẩu trang'), ('b', 'Không cần gì'), ('c', 'Khăn ướt lau trang giấy')), 'a'),
    ('Mục lục ghi hồ sơ ở hộp 12 mà không thấy. Làm gì trước?',
     (('a', 'Lập biên bản mất ngay'), ('b', 'Tìm các hộp kế bên, xem sổ giao nhận'), ('c', 'Bảo người ta về')), 'b'),
]

# ---------------------------------------------------------------- the morning
PESTS = {'none': 'Bẫy sạch, không thấy dấu vết gì.', 'mot': 'Dưới kệ sách cũ có bụi gỗ vàng li ti, vài trang thủng lỗ nhỏ: mọt sách!',
         'gian': 'Bẫy dính có ba con gián, góc bàn ăn của nhân viên còn vụn bánh.', 'chuot': 'Có phân chuột sau tủ hồ sơ, một bìa hộp bị gặm nham nhở.'}
PEST_FIX = {'cach_ly': 'Cách ly sách bị mọt vào túi kín, báo dịch vụ khử trùng', 'bay': 'Dọn đồ ăn, đặt bẫy, bịt lỗ, báo tổ vệ sinh',
            'xit': 'Xịt thuốc diệt côn trùng thẳng lên kệ sách', 'ke': 'Để đó, mai tính'}
PEST_BEST = {'none': 'ke', 'mot': 'cach_ly', 'gian': 'bay', 'chuot': 'bay'}
HUM_OK = (45, 60)     # % độ ẩm kho giấy (fictional ward rule)

# ---------------------------------------------------------------- the day's weather
MODS = [
    dict(id='normal', emoji='📚', label='Ngày thường', hint='Bạn đọc đều đều: mượn trả, biên mục, một vòng phòng đọc.', weight=3),
    dict(id='thi', emoji='📝', label='Mùa thi', hint='Sinh viên kín phòng đọc từ sáng: giữ chỗ, ăn vặt, ngủ gục, sạc pin.', min_day=2, weight=2),
    dict(id='nom', emoji='🌫️', label='Trời nồm ẩm', hint='Độ ẩm kho dễ vượt 60%: nhớ bật máy hút ẩm, soi mọt, mốc.', min_day=2, weight=2),
    dict(id='he', emoji='☀️', label='Nghỉ hè', hint='Trẻ con đông, giờ kể chuyện, phụ huynh nhờ đủ thứ.', min_day=3, weight=1),
    dict(id='kiem_tra', emoji='🗂️', label='Tuần chỉnh lý hồ sơ', hint='Phường cần nhiều hồ sơ: phiếu yêu cầu, mục lục, găng tay.', min_day=3, weight=1),
]

INTRO = dict(
    title='Giới thiệu nghề: cán bộ thư viện – lưu trữ',
    lead='Thư viện nhỏ trên tầng hai nhà văn hóa phường Mây, sau lưng là kho lưu trữ hồ sơ của phường. Cô Nguyệt giữ sách, giữ hồ sơ ba mươi năm; bạn về phụ cô.',
    work=[('🌡️', 'Sáng: xem ẩm kế kho, soi bẫy mọt, mở phòng đọc'), ('🔖', 'Quầy: tra ký hiệu, kiểm thẻ, cho mượn, nhận trả'),
          ('💰', 'Tự đề xuất tiền phạt trả trễ, miễn khi có lý do chính đáng'), ('🏷️', 'Biên mục: xếp lớp, ghi ký hiệu tác giả, lọc sách hỏng'),
          ('🤫', 'Phòng đọc: nhắc ồn ào, ăn uống, điện thoại, người ngủ gục'), ('🗂️', 'Kho lưu trữ: kiểm giấy tờ, mức tiếp cận, tìm đúng hộp'),
          ('🧤', 'Găng tay vải, khẩu trang khi mở hộp cũ; bản gốc không rời kho'), ('💬', 'Gợi ý sách theo sở thích, từ chối khéo việc sai')],
    meet=[('👓', 'Ông Thạc: cụ hưu khó tính, ghế của ông'), ('🎧', 'Vy: sinh viên ôn thi, trà sữa, ngủ gục'),
          ('👩‍👧‍👦', 'Chị Loan: phụ huynh muốn “ưu tiên”'), ('📜', 'Anh Tuấn: nghiên cứu sinh cần “ngay”'),
          ('🏛️', 'Ông Bính: Phó Chủ tịch, “đưa lên đây”'), ('🧓', 'Bà Xuân: làm giấy tờ lần đầu'),
          ('📗', 'Đạt: mượn truyện tranh, trả trễ'), ('🐭', 'Mọt, chuột, trời nồm và đủ thứ nhờ vả')],
    stars=[('📋', 'Đúng nội quy, không làm khó vô cớ'), ('⚖️', 'Phí phạt công bằng, có lý do khi miễn'), ('🔒', 'Giữ kín hồ sơ, sổ mượn của người khác'),
           ('🏷️', 'Phân loại đúng, ký hiệu đúng'), ('🤫', 'Phòng đọc yên mà không ai bị bẽ mặt'), ('🧤', 'Giữ gìn bản gốc, sách cũ')],
)

# ---------------------------------------------------------------- the regulars' little story lines
REG_STORY = {
    1: ('Ông Thạc: “Ghế gần cửa sổ là ghế của tôi, ba mươi năm rồi.”', 'Ông Thạc mang tặng thư viện chồng báo Tết xưa ông giữ.',
        'Ông Thạc dặn cả xóm: “Lên thư viện thì đi nhẹ nói khẽ nghe chưa.”'),
    2: ('Vy: “Chị ơi cho em ngồi tới tối, thi xong em khao trà sữa.”', 'Vy thi đậu, ghé khoe bảng điểm.', 'Vy về làm cộng tác viên giờ kể chuyện.'),
    3: ('Chị Loan: “Con chị đọc sách là ngoan hẳn.”', 'Chị Loan đăng ký làm thẻ cho cả nhà.', 'Chị Loan rủ cả nhóm phụ huynh đi giờ kể chuyện.'),
    4: ('Anh Tuấn: “Tài liệu phường mình quý lắm, phải giữ cẩn thận.”', 'Anh Tuấn ghi tên thư viện phường trong lời cảm ơn luận án.',
        'Anh Tuấn tặng thư viện cuốn sách đầu tay về phố Mây.'),
    5: ('Ông Bính: “Làm nhanh nhưng làm đúng, tôi hiểu.”', 'Ông Bính duyệt kinh phí mua máy hút ẩm mới cho kho.',
        'Ông Bính khen thư viện trong buổi giao ban phường.'),
    6: ('Bà Xuân: “Giấy tờ khó quá cháu ơi.”', 'Bà Xuân làm xong sổ đỏ, mang biếu túi ổi.', 'Bà Xuân dẫn hàng xóm tới nhờ chỉ cách làm giấy tờ.'),
    7: ('Đạt: “Em hứa lần này trả đúng hạn!”', 'Đạt trả đúng hạn ba lần liền, khoe được cô khen.', 'Đạt rủ cả lớp đăng ký thẻ thư viện.'),
}


# ================================================================ the awkward asks (dozens of them)
# Readers, parents, officials, colleagues, family, neighbours and passers-by ask for things in the middle of a job.
# The player answers in their own way: yes (chiều theo), alt (the way that fits the rules), no (từ chối lịch sự),
# boss (nhờ cô Nguyệt). Each person takes it by their hidden traits (street_folk); `best` answers are what a good
# librarian does, `bad` ones are mistakes with a severity. Giving in to something wrong is never rewarded.
def D(did, kinds, who, text, alt, lose='', best=('alt',), bad=None, yes='Chiều theo luôn', no='Từ chối lịch sự',
      npc=None, persona='picky', typ='rule', min_day=1, alt_out='', yes_out=''):
    return dict(id=did, kinds=tuple(kinds), who=who, text=text, alt=alt, lose=lose, best=tuple(best),
                bad=dict(bad if bad is not None else {'yes': 1}), yes=yes, no=no, npc=npc, persona=persona, typ=typ,
                min_day=min_day, alt_out=alt_out, yes_out=yes_out)


ANY = ('desk', 'catalog', 'room', 'archive')
DEMANDS = [
    # ------------------------------------------------ at the desk
    D('gia_han_dt', ('desk',), 'Chị Loan', '“Gia hạn giùm chị qua điện thoại tới tháng sau nha, chị đi Đà Lạt, tính gì kỹ vậy em.”',
      'Gia hạn một lần 14 ngày theo nội quy, nhắn ngày trả', lose='Cho người ta giữ sách cả tháng, người chờ đọc thì sao.', npc=3,
      alt_out='Chị Loan nhận tin nhắn ngày trả mới, thả tim.'),
    D('muon_10', ('desk',), 'Chị Loan', '“Cho chị mượn mười cuốn một lần, nhà chị ba đứa đọc chung, đi lại mệt lắm.”',
      'Mỗi thẻ ba cuốn: làm thêm thẻ cho hai bé', lose='Một người ôm mười cuốn, kệ thiếu nhi trống trơn.', npc=3),
    D('giu_sach', ('desk',), 'Ông Thạc', '“Giữ cuốn đó cho tôi tới thứ bảy, cấm cho đứa nào mượn, nghe chưa!”',
      'Ghi phiếu đặt trước, giữ đúng ba ngày', lose='Sách để dành riêng cho người quen cả tuần.', npc=1),
    D('muon_tu_dien', ('desk',), 'Vy', '“Cho em mang cuốn bách khoa về một đêm thôi, mai em trả liền, hứa luôn á!”',
      'Đọc tại phòng tra cứu, photo vài trang cần', lose='Sách tra cứu mang về nhà, sáng sau người khác cần tra không có.', bad={'yes': 2}, npc=2),
    D('xem_so_muon', ('desk',), 'Một bà mẹ', '“Cho cô xem con trai cô đang mượn sách gì. Dạo này nó lạ lắm, cô lo.”',
      'Khuyên cô hỏi chuyện con, sổ mượn là chuyện riêng của bạn đọc', lose='Thư viện đưa sổ mượn sách của người ta cho người khác xem.',
      best=('alt', 'no'), bad={'yes': 3}, persona='warm', typ='privacy'),
    D('ck_rieng', ('desk', 'archive'), 'Một bạn đọc', '“Chị chuyển khoản vào số riêng của em cho nhanh, khỏi biên lai lằng nhằng.”',
      'Nộp tại quầy, lấy biên lai của thư viện', lose='Tiền phí nộp vào tài khoản riêng của cán bộ, không biên lai.', bad={'yes': 2}, persona='genz'),
    D('the_vo', ('desk',), 'Một anh khách', '“Anh mượn bằng thẻ của vợ anh nha, thẻ anh hết hạn rồi, có gì đâu.”',
      'Gia hạn thẻ của anh, hai phút là xong', lose='Mượn bằng thẻ người khác, mất sách không biết ai chịu.', persona='bossy'),
    D('goi_y_nhanh', ('desk',), 'Chị Loan', '“Gợi ý sách đọc hè cho con chị đi, nhanh nha, chị đậu xe dưới lòng đường.”',
      'Đưa danh sách sách hè in sẵn, chọn nhanh ba cuốn', best=('alt', 'yes'), bad={}, yes='Lấy đại ba cuốn đưa chị', npc=3, typ='favor'),
    D('bia_xanh', ('desk',), 'Ông Thạc', '“Tìm giùm tôi cuốn bìa xanh xanh. Tên quên rồi. Nội dung về… ờ… cuộc đời.”',
      'Hỏi thêm vài câu, tra theo chủ đề', best=('alt',), bad={}, yes='Lôi đại một cuốn bìa xanh', npc=1, typ='favor',
      alt_out='Hỏi ra là cuốn hồi ký ông đọc dở năm ngoái. Ông Thạc gật gù: “Được, nhớ dai đấy.”'),
    D('ban_sach', ('desk',), 'Một ông khách', '“Bán lại cuốn này cho tôi đi, kệ để đó có ai đọc đâu, 50 xu được không?”',
      'Giới thiệu nhà sách còn bán, hoặc photo trang cần', lose='Cán bộ thư viện bán sách của phường lấy tiền riêng.', bad={'yes': 2}, persona='bossy'),
    D('den_sach_khac', ('desk',), 'Vy', '“Em làm mất cuốn đó rồi, đền cuốn khác nha, cuốn này dày hơn, lời quá còn gì!”',
      'Đền đúng đầu sách, hoặc tiền theo giá bìa', lose='Đền sách mất bằng cuốn cũ không ai đọc.', npc=2),
    D('wifi_phim', ('desk', 'room'), 'Một anh sinh viên', '“Pass wifi là gì chị? Cho em tải bộ phim 20 GB luôn, mạng phòng trọ yếu xìu.”',
      'Đưa wifi, nhắc không tải phim nặng giờ đông', best=('alt',), bad={}, yes='Đưa wifi, tải thoải mái', persona='genz', typ='favor'),
    D('photo_ca_cuon', ('desk',), 'Vy', '“Photo nguyên cuốn giáo trình giùm em, mua thì 200 xu, sinh viên nghèo mà.”',
      'Photo một chương (dưới một phần mười), giới thiệu bản điện tử', lose='Thư viện photo nguyên cuốn sách đang bán, vi phạm bản quyền.', bad={'yes': 2}, npc=2),
    D('tre_sach_lon', ('desk',), 'Bé Bi', '“Cô ơi cho con mượn cuốn truyện ma kinh dị người lớn bằng thẻ của mẹ con.”',
      'Gợi ý truyện trinh thám thiếu nhi, hỏi ý mẹ bé', lose='Đưa truyện kinh dị người lớn cho bé sáu tuổi.', persona='genz'),
    D('chen_hang', ('desk', 'archive'), 'Một bà khách', '“Tôi người quen cô Nguyệt đấy, cho tôi làm trước, đứng chờ mỏi chân lắm.”',
      'Mời xếp hàng, phục vụ theo thứ tự, mời ghế ngồi', lose='Người quen thì được chen ngang, bọn tôi đứng chờ như phỗng.', persona='bossy', typ='rude'),
    D('quay_clip', ('desk',), 'Một anh khách', '“Cả nhà ơi thủ thư mặt khó đăm đăm nè, làm có cái thẻ mà lâu như rùa!” (giơ điện thoại quay)',
      'Mỉm cười, làm tiếp, nhờ anh đừng quay người khác', best=('alt',), bad={'yes': 1}, yes='Quay lại cãi tay đôi trên sóng', persona='sour', typ='rude',
      lose='Thủ thư cãi nhau với khách trên livestream.'),
    D('xin_so', ('desk', 'room'), 'Một anh khách', '“Cho anh xin số em đi, mượn sách là phụ, gặp em là chính.” (đứng lì ở quầy)',
      'Cười lịch sự, chỉ đưa số điện thoại thư viện', lose='Cán bộ đưa số riêng cho khách đứng ve vãn ở quầy.', bad={'yes': 2},
      yes='Đưa số riêng cho xong chuyện', persona='genz', typ='flirt'),
    D('gui_do_cho', ('desk',), 'Chị Loan', '“Gửi giùm chị túi đồ chợ sau quầy, có cá tươi đó, chị đi đón con nửa tiếng.”',
      'Chỉ tủ gửi đồ có khóa, nhắc đồ tươi nên mang theo', best=('alt',), bad={}, npc=3, typ='favor'),
    D('in_mien_phi', ('desk',), 'Một anh khách', '“In giùm anh năm mươi trang hồ sơ xin việc, máy của thư viện mà, tính gì.”',
      'In theo bảng giá dịch vụ, có biên lai', lose='Máy in của phường in miễn phí cho người quen.', persona='bossy'),
    D('tra_bang_keo', ('desk',), 'Đạt', '“Em có mười xu à, cô bớt phí cho em đổi cây kẹo mút này được không?” (chìa cây kẹo)',
      'Cảm ơn, không nhận quà; tính phí đúng hoặc miễn nếu có lý do', best=('alt',), bad={'yes': 1}, yes='Nhận kẹo, bỏ qua phí',
      lose='Thu phí bằng kẹo mút, quỹ thư viện hụt.', npc=7, typ='bribe'),
    # ------------------------------------------------ at the cataloguing table
    D('tang_ca_thung', ('catalog',), 'Người tặng sách', '“Tôi tặng nguyên thùng này, xếp hết lên kệ, dán tên tôi to to vào bìa cho bà con biết.”',
      'Cảm ơn, nói rõ chỉ xếp sách còn tốt, ghi tên vào sổ người tặng', lose='Xếp cả sách mốc, sách lậu lên kệ cho vừa lòng người tặng.', persona='bossy'),
    D('tang_anh', ('catalog',), 'Người tặng sách', '“Chụp tôi tấm ảnh trao sách, đăng trang phường, ghi “mạnh thường quân” nghe.”',
      'Chụp một tấm, gửi bộ phận văn hóa duyệt đăng', best=('alt', 'yes'), bad={}, yes='Chụp, đăng ngay trang phường', persona='bossy', typ='favor'),
    D('xep_theo_mau', ('catalog',), 'Chị bên văn hóa phường', '“Xếp sách theo màu bìa cho đẹp đi em, tuần sau đoàn kiểm tra xuống chụp ảnh.”',
      'Giữ xếp theo ký hiệu, trưng riêng một kệ đẹp ở sảnh', lose='Sách xếp theo màu, bạn đọc tìm cả buổi không ra.', bad={'yes': 2}, persona='bossy'),
    D('dan_800_het', ('catalog',), 'Anh trực bảo vệ', '“Dán đại nhãn 800 hết cho nhanh, sách nào chẳng là sách, ai mà kiểm.”',
      'Cảm ơn, vẫn phân loại đúng từng cuốn', lose='Cả xe sách dán chung một nhãn, tra không ra cuốn nào.', bad={'yes': 2}, persona='genz'),
    D('dem_ve_doc', ('catalog',), 'Chị bên văn hóa phường', '“Cuốn mới này hay quá, chị mang về đọc trước, khỏi nhập sổ vội, tuần sau chị trả.”',
      'Nhập sổ trước, chị mượn bằng thẻ như mọi người', lose='Sách mới chưa vào sổ đã có người mang về nhà.', bad={'yes': 2}, persona='warm'),
    D('the_tron_doi', ('catalog',), 'Người tặng sách', '“Tôi tặng sách thế này thì thư viện cho tôi thẻ miễn phí trọn đời chứ nhỉ?”',
      'Cảm ơn, tặng giấy cảm ơn; thẻ vẫn theo quy định', lose='Tặng vài cuốn sách cũ đổi được thẻ trọn đời.', persona='sour'),
    D('sach_nong', ('catalog',), 'Người tặng sách', '“Tặng thư viện bộ tiểu thuyết này, hơi “nóng” tí nhưng người lớn đọc được mà.”',
      'Cảm ơn, không nhận sách không hợp thư viện công cộng', lose='Sách người lớn lẫn vào kệ chung, trẻ con cũng với tới.', bad={'yes': 2}, persona='genz'),
    D('go_sach', ('catalog',), 'Chị Loan', '“Cuốn này có chữ “nụ hôn”, gỡ khỏi kệ thiếu nhi ngay, không thì chị lên phường!”',
      'Lắng nghe, xem lại nội dung, giải thích tiêu chí chọn sách', best=('alt',), bad={'yes': 1}, yes='Gỡ ngay cho êm chuyện',
      lose='Gỡ sách chỉ vì một chữ, chẳng ai xem nội dung.', npc=3),
    D('tang_cu_rich', ('catalog',), 'Người tặng sách', '“Sách cũ này quý lắm đấy, thư viện mua lại của tôi 300 xu đi, coi như tặng một nửa.”',
      'Cảm ơn, thư viện nhận tặng chứ không mua lại', lose='Thư viện mua sách cũ giá trên trời.', bad={'yes': 2}, persona='sour'),
    # ------------------------------------------------ in the reading room
    D('tat_quat', ('room',), 'Ông Thạc', '“Tắt cái quạt kia đi! Gió bay hết báo của tôi!” (cả phòng đang nóng hầm hập)',
      'Mời ông ra bàn sát cửa sổ, khuất gió', lose='Tắt quạt cả phòng cho một người, ai cũng toát mồ hôi.', npc=1),
    D('nhac_lofi', ('room',), 'Vy', '“Chị mở nhạc lofi cho cả phòng nghe đi, cho chill, học mới vô á!”',
      'Đeo tai nghe nghe riêng, phòng đọc giữ im lặng', lose='Thư viện mở nhạc cả phòng, người cần yên thì chịu.', npc=2),
    D('giu_5_ghe', ('room',), 'Vy', '“Giữ giùm em năm ghế cho hội bạn nha, tụi nó mười giờ mới tới, em bao trà sữa.”',
      'Ai tới trước ngồi trước; có phòng nhóm đặt trước', lose='Ghế để trống cả buổi cho người quen, người tới trước phải đứng.', npc=2),
    D('sac_qua_dem', ('room',), 'Một bạn sinh viên', '“Cho em cắm sạc laptop qua đêm ở đây, mai em lấy, nhà trọ cúp điện.”',
      'Không giữ đồ điện qua đêm; chỉ sạc trong giờ mở cửa', lose='Đồ sạc cắm qua đêm cạnh kho giấy, chập điện là cháy.', bad={'yes': 2}, persona='genz'),
    D('doc_to_bao', ('room',), 'Ông Thạc', '“Tôi đọc báo to cho mấy đứa trẻ nó nghe tin tức, có gì sai!”',
      'Mời ông sang góc báo, đọc nhỏ cho bàn bên', best=('alt',), bad={'yes': 1}, yes='Để ông đọc tiếp', lose='Cả phòng nghe đọc báo như loa phường.', npc=1),
    D('mo_cua_som', ('room',), 'Vy', '“Mai mở cửa sáu giờ cho em ôn thi nha chị, chị có chìa khóa mà!”',
      'Giờ mở cửa theo quy định; chỉ chỗ tự học mở sớm của nhà văn hóa', lose='Thư viện mở cửa riêng cho người quen ngoài giờ, không ai trực.', npc=2),
    D('an_trua', ('room',), 'Một nhóm học sinh', '“Cho tụi em ăn trưa trong phòng đọc nha cô, ngoài trời nắng chảy mỡ.”',
      'Mời ra sảnh có bàn ghế, quạt mát', lose='Cả phòng đọc mùi cơm hộp, kiến bò lên sách.', persona='genz'),
    D('song_ao', ('room',), 'Một hội bạn', '“Cho tụi em chụp ảnh sống ảo giữa kệ sách tí, có bật flash xíu thôi à.”',
      'Chụp nhanh ở góc sảnh, tắt flash, không chụp người khác', best=('alt',), bad={'yes': 1}, lose='Flash nháy liên tục, người đọc bị chụp mặt lên mạng.', persona='genz'),
    D('sac_du_phong', ('room',), 'Một anh khách', '“Cho anh mượn cục sạc dự phòng của em đi, máy anh hết pin rồi.”',
      'Chỉ ổ cắm ở bàn số ba', best=('alt', 'yes'), bad={}, yes='Đưa sạc riêng của mình', persona='warm', typ='favor'),
    D('nho_trong_con', ('room', 'desk'), 'Chị Loan', '“Trông hai đứa nhỏ giùm chị một tiếng nha, chị đi làm tóc, tụi nó ngoan lắm.”',
      'Thư viện không trông trẻ; mời chị ở lại cùng con, có góc thiếu nhi', lose='Cán bộ thư viện bỏ quầy đi trông con cho người quen.', bad={'yes': 2}, npc=3),
    # ------------------------------------------------ at the archive window
    D('vip_now', ('archive',), 'Ông Bính', '“Đưa hồ sơ đây, phiếu với sổ má gì, tôi Phó Chủ tịch phường đấy!”',
      'Đưa ngay, xin anh ký phiếu và sổ ba mươi giây', lose='Hồ sơ ra khỏi kho không ai ký nhận, mai không biết ở đâu.', bad={'yes': 2}, npc=5,
      alt_out='Ông Bính ký vội: “Ừ, làm vậy là đúng, lần sau tôi tự ký trước.”'),
    D('ho_hang_xom', ('archive',), 'Một ông khách', '“Cho tôi xem hồ sơ đất nhà bên, nó lấn sang nhà tôi nửa mét!”',
      'Hướng dẫn đề nghị qua bộ phận địa chính; hồ sơ người khác không xem được', lose='Lưu trữ đưa hồ sơ đất nhà người ta cho hàng xóm xem.',
      bad={'yes': 3}, persona='sour', typ='privacy'),
    D('sua_nam_sinh', ('archive',), 'Bà Xuân', '“Sửa giùm cái năm sinh trong sổ cũ cho khớp căn cước đi cháu, một nét bút thôi mà.”',
      'Hướng dẫn thủ tục đính chính ở bộ phận hộ tịch', lose='Hồ sơ lưu trữ bị sửa tay, mất giá trị pháp lý.', bad={'yes': 3}, npc=6),
    D('rut_trang', ('archive',), 'Một anh khách', '“Rút tờ này ra cho anh mang đi công chứng, chiều anh trả, hứa danh dự.”',
      'Làm bản sao có đóng dấu sao y', lose='Tờ gốc trong hồ sơ bị rút ra mang đi mất.', bad={'yes': 3}, persona='bossy'),
    D('phong_bi', ('archive',), 'Một anh khách', '“Chút cà phê thôi.” (dúi phong bì) “Làm nhanh giùm anh, bỏ qua cái giấy ủy quyền nha.”',
      'Từ chối phong bì, hướng dẫn làm giấy ủy quyền', lose='Nhận phong bì bỏ qua giấy tờ.', bad={'yes': 3}, yes='Nhận phong bì, làm nhanh',
      persona='bossy', typ='bribe'),
    D('chup_ca_ho_so', ('archive',), 'Anh Tuấn', '“Cho tôi chụp bằng điện thoại cả hồ sơ cho nhanh, khỏi bản sao.”',
      'Cấp bản sao có xác nhận; chụp phần tài liệu mở nếu được phép', best=('alt',), bad={'yes': 1}, lose='Chụp tràn lan cả hồ sơ, không ai kiểm.', npc=4),
    D('luan_an_gap', ('archive',), 'Anh Tuấn', '“Tôi cần hồ sơ trong mười phút! Chiều nay nộp luận án! Thư viện làm ăn kiểu gì vậy!”',
      'Hẹn giờ cụ thể, làm nhanh trong quy trình', best=('alt',), bad={'yes': 1}, yes='Bỏ bớt bước cho kịp', lose='Làm ẩu cho kịp, hồ sơ lấy sai hộp.',
      npc=4, typ='rude'),
    D('tu_vao_kho', ('archive',), 'Một ông khách', '“Để tôi tự vào kho tìm cho nhanh, cô chỉ chỗ là được, tôi biết đọc mà.”',
      'Mời ngồi chờ: không ai vào kho một mình', lose='Người lạ tự lục kho lưu trữ, hồ sơ xáo trộn.', bad={'yes': 2}, persona='bossy'),
    D('photo_ngoai', ('archive',), 'Bà Xuân', '“Cho bà mang bản gốc ra tiệm photo đầu ngõ, ở đó rẻ hơn cháu ạ.”',
      'Sao tại thư viện; bản gốc không rời kho', lose='Bản gốc mang ra tiệm photo, quăn mép, dính mực.', bad={'yes': 2}, npc=6),
    D('tim_giay_cu', ('archive',), 'Ông Thạc', '“Nhân tiện tìm luôn giấy khai sinh của bố tôi năm 1950, chắc ở đâu đó trong kho.”',
      'Làm phiếu yêu cầu riêng, hẹn ngày tra mục lục', best=('alt',), bad={}, yes='Lục cả kho tìm luôn', npc=1, typ='favor'),
    D('nha_bao', ('archive',), 'Một phóng viên', '“Cho tôi chụp sổ hộ tịch có tên ca sĩ nổi tiếng hồi nhỏ ở phường mình, viết bài thôi.”',
      'Từ chối: hồ sơ cá nhân cần người đó đồng ý', lose='Lưu trữ để phóng viên chụp hồ sơ cá nhân của người khác.', best=('alt', 'no'), bad={'yes': 3},
      persona='genz', typ='privacy'),
    # ------------------------------------------------ anywhere: family, neighbours, the office, passers-by
    D('me_goi', ANY, 'Mẹ bạn (gọi điện)', '“Con xem giùm mẹ hồ sơ đất nhà bác Tư đầu ngõ, mẹ tò mò thôi, ai biết đâu.”',
      'Nói mẹ: hồ sơ của người khác con không được xem', lose='Cán bộ lưu trữ tra hồ sơ nhà người ta cho mẹ mình.', best=('alt', 'no'), bad={'yes': 3},
      persona='warm', typ='privacy'),
    D('hang_xom_sgk', ANY, 'Chị hàng xóm (nhắn tin)', '“Lấy giùm chị mấy cuốn sách giáo khoa của thư viện về cho con chị, sách thanh lý mà em.”',
      'Hướng dẫn đăng ký buổi thanh lý sách công khai', lose='Sách của phường lấy về cho người quen trước khi thanh lý.', persona='warm'),
    D('bao_cao_ao', ANY, 'Cán bộ văn phòng phường', '“Ghi sổ lượt đọc tháng này hai nghìn lượt cho đẹp báo cáo nha em, ai mà đếm.”',
      'Báo số thật, đề xuất thêm buổi kể chuyện để tăng lượt đọc', lose='Sổ lượt đọc ghi khống cho đẹp báo cáo.', bad={'yes': 2}, persona='bossy'),
    D('ban_ru_cafe', ANY, 'Bạn thân (ghé quầy)', '“Đi cà phê đi bà, bỏ quầy ba mươi phút có chết ai đâu, cô Nguyệt đi họp rồi mà.”',
      'Hẹn sau giờ làm', lose='Thư viện treo biển “chờ năm phút” cả nửa tiếng.', persona='genz'),
    D('shipper', ANY, 'Anh shipper', '“Nhận giùm em mấy đơn hàng của cả dãy phố nha, để ở quầy thư viện, chiều người ta qua lấy.”',
      'Chỉ chỗ nhận hàng của tổ dân phố', lose='Quầy thư viện thành điểm nhận hàng, mất đơn ai chịu.', persona='genz'),
    D('ve_so', ('room', 'desk'), 'Cô bán vé số', '“Mua giùm cô tờ vé số, cô vào mời mấy bàn đọc một vòng thôi nha.”',
      'Mua một tờ ủng hộ ở sảnh, nhờ cô không vào phòng đọc', best=('alt',), bad={'yes': 1}, yes='Để cô vào mời từng bàn',
      lose='Người bán hàng rong đi mời từng bàn trong phòng đọc.', persona='warm', typ='favor'),
    D('ong_thac_bao', ('desk', 'room'), 'Ông Thạc', '“Báo hôm nay đâu? Sáu giờ tôi đứng cửa, bảy rưỡi mới có báo, làm ăn thế à!”',
      'Xin lỗi, giải thích giờ báo về, để ông tờ đầu tiên', best=('alt',), bad={}, yes='Chạy ra sạp mua báo riêng cho ông', npc=1, typ='rude'),
    D('sach_giai_san', ('desk',), 'Chị Loan', '“Gợi ý sách cho con chị thi chuyên, mà phải sách có giải sẵn hết đáp án nha.”',
      'Gợi ý sách luyện tập có hướng dẫn giải, kèm sách đọc thêm', best=('alt',), bad={}, yes='Đưa toàn sách giải sẵn', npc=3, typ='favor'),
    D('nguoi_say', ('room', 'desk'), 'Một người say', '“Cho… cho tôi ngủ nhờ cái ghế này… thư viện của dân mà…” (nói lớn, lảo đảo)',
      'Bình tĩnh mời ra sảnh ngồi, gọi bảo vệ phường', best=('alt', 'boss'), bad={'yes': 1}, yes='Để ông ngủ trong phòng đọc',
      lose='Người say nằm giữa phòng đọc, cả phòng bỏ về.', persona='sour', typ='safety'),
    D('tre_lac', ANY, 'Một bé đi lạc', '“Huhu… mẹ con đâu rồi…” (bé bốn tuổi đi lạc vào thư viện)',
      'Giữ bé ở quầy, hỏi tên, nhờ loa nhà văn hóa, báo công an phường nếu cần', best=('alt',), bad={'yes': 2, 'no': 2},
      yes='Dắt bé ra đường tìm mẹ', no='Bảo bé ra ngoài tìm mẹ', lose='Bé đi lạc được dắt ra đường một mình với người lạ.', persona='quiet', typ='safety'),
    D('sep_tang_ca', ANY, 'Cán bộ văn phòng phường', '“Tối nay ở lại sắp xếp hội trường giúp bên văn hóa nha, việc thư viện để mai.”',
      'Hỏi cô Nguyệt việc nào trước, báo lại giờ xong', best=('alt', 'boss'), bad={}, yes='Nhận hết, bỏ dở việc thư viện', persona='bossy', typ='boss'),
    D('may_quay_game', ANY, 'Anh trực bảo vệ', '“Ê cho anh mượn cái máy tính quầy chơi game tí, giờ này vắng mà.”',
      'Máy quầy có dữ liệu bạn đọc, không cho dùng việc riêng', lose='Máy quầy có dữ liệu bạn đọc bị dùng chơi game.', bad={'yes': 2}, persona='genz'),
    D('thanh_tra_gia', ANY, 'Người tự xưng thanh tra', '“Tôi thanh tra quận đây. Đưa tôi xem sổ mượn của bạn đọc tên Hùng, không cần giấy tờ.”',
      'Xin xem giấy giới thiệu, báo cô Nguyệt trước khi đưa', lose='Đưa sổ mượn cho người lạ chỉ vì họ tự xưng thanh tra.', best=('alt', 'boss'), bad={'yes': 3},
      persona='bossy', typ='privacy'),
]
DEMAND = {x['id']: x for x in DEMANDS}
CHOICES = ('yes', 'alt', 'no', 'boss')
# How people take an answer that is not what they asked for (street_folk.word: calm, sulk, blowup).
TAKE = {
    'calm': ('{who} gật gù: “Ừ, vậy cũng được.”', '{who}: “À, thì ra là vậy. Cảm ơn nha.”'),
    'sulk': ('{who} lầm bầm “làm gì căng” rồi cũng thôi.', '{who} bĩu môi: “Quy định, quy định…” nhưng không nói gì thêm.'),
    'blowup': ('{who} gắt lên: “Có tí việc mà làm khó người ta, để tôi lên phường!”', '{who} đập bàn: “Thư viện gì mà cứng như gỗ, khỏi!”'),
}


# ================================================================ surprises between jobs (kit desk scripts)
def _o(oid, label, outcome, good=None, hint='', **effects):
    return dict(id=oid, label=label, hint=hint, effects=effects, good=good, outcome=outcome)


DESK = [
    dict(id='ke_chuyen', title='Giờ kể chuyện loạn cả lên', emoji='🧸', npc=3, min_day=2, tone='tense', at='between', weight=3, mods=None,
         text='Giờ kể chuyện cuối tuần: mười hai bé ngồi chưa yên, một bé khóc đòi mẹ, hai bé giật sách, chị Loan giơ điện thoại quay: “Cô kể hay vô nha!”',
         options=[_o('song', 'Cho cả lớp hát bài vỗ tay, chia nhóm nhỏ, mời bé khóc ngồi cạnh mình', 'Hát xong cả lớp ngồi im nghe chuyện. Bé khóc nín, xin kể lại lần nữa.',
                     True, xp=5, patience=-2),
                  _o('loud', 'Quát to “Im lặng!”', 'Cả lớp im được ba giây rồi khóc hai bé.', False, review=[2, 'Cô kể chuyện quát tụi nhỏ, con tôi về sợ không dám đi nữa.']),
                  _o('cut', 'Kể nhanh cho xong, phát kẹo cho về', 'Mười phút xong buổi. Tụi nhỏ vui vì kẹo, quên chuyện.', None)],
         default='cut'),
    dict(id='mua_dot', title='Mưa dột kho lưu trữ', emoji='🌧️', npc=0, min_day=2, tone='tense', at='between', weight=2, mods=('nom', 'normal'),
         text='Mưa lớn, trần kho lưu trữ dột một chỗ ngay trên dãy hộp hồ sơ năm 1980. Nước nhỏ tong tỏng xuống nắp hộp.',
         options=[_o('move', 'Dời hộp sang kệ khô, phủ ni-lông, đặt thau hứng, báo sửa mái', 'Hộp hồ sơ còn khô. Cô Nguyệt gọi thợ sửa mái chiều nay.', True, xp=5),
                  _o('dry', 'Lấy máy sấy sấy luôn hộp ướt', 'Giấy cong vênh, mực loang. Lẽ ra phải hong chỗ mát.', False, patience=-3),
                  _o('later', 'Đặt cái xô rồi làm việc tiếp', 'Xô đầy tràn lúc nào không hay, hai hộp ướt sũng đáy.', False)],
         default='later'),
    dict(id='mat_dien', title='Cúp điện giữa buổi', emoji='🔌', npc=0, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Cả nhà văn hóa cúp điện. Phòng đọc tối om, máy hút ẩm kho tắt ngúm, máy tính quầy sập.',
         options=[_o('manual', 'Mở rèm cửa sổ, ghi sổ mượn trả bằng tay, mở cửa kho cho thoáng', 'Phòng đọc sáng lại nhờ nắng. Sổ tay ghi đủ từng lượt mượn.', True, xp=4),
                  _o('close', 'Đóng cửa thư viện cho về hết', 'Bạn đọc về hết. Ông Thạc càu nhàu suốt cầu thang.', None, patience=-4),
                  _o('guess', 'Cho mượn, nhớ trong đầu, lúc có điện nhập sau', 'Có điện thì quên mất hai cuốn ai mượn.', False)],
         default='close'),
    dict(id='quy_phat', title='Hộp tiền phạt cuối ngày', emoji='💰', npc=0, min_day=3, tone='gentle', at='between', weight=1, mods=None,
         text='Cô Nguyệt đi họp. Hộp tiền phạt có hơn 30 xu, không ai đếm. Anh bảo vệ nháy mắt: “Lấy ít uống cà phê, ai biết đâu.”',
         options=[_o('count', 'Đếm, ghi sổ quỹ, khóa hộp, chờ cô Nguyệt ký', 'Sổ quỹ khớp từng đồng. Cô Nguyệt ký, gật đầu.', True, xp=5),
                  _o('take', 'Lấy 10 xu uống cà phê', 'Cuối tháng kế toán phường đối chiếu, sổ lệch 10 xu.', False, money=10,
                     review=[1, 'Nghe nói tiền phạt thư viện bị hụt, ai cầm thì tự biết.', 0])],
         default='count'),
    dict(id='lop_bat_ngo', title='Cả lớp kéo tới không báo trước', emoji='🚌', npc=3, min_day=2, tone='tense', at='between', weight=2, mods=('he', 'normal'),
         text='Bốn mươi học sinh lớp 4 ùa vào: “Cô giáo dẫn đi tham quan thư viện!” Không ai báo trước, phòng đọc chỉ có hai mươi ghế.',
         options=[_o('tour', 'Chia hai nhóm: một nhóm đi tham quan kho sách, một nhóm đọc truyện, rồi đổi', 'Tụi nhỏ ríu rít nhưng có trật tự. Cô giáo xin lịch tham quan hằng tháng.', True, xp=5, patience=-2),
                  _o('all', 'Cho vào hết, tự xoay xở', 'Kệ thiếu nhi tan hoang, ba cuốn rách gáy.', False, patience=-5),
                  _o('no', 'Mời về, hẹn đăng ký lịch tuần sau', 'Cô giáo hơi ngượng nhưng hiểu. Tụi nhỏ tiu nghỉu.', None)],
         default='no'),
    dict(id='mua_tru', title='Người vô gia cư trú mưa', emoji='☔', npc=0, min_day=2, tone='gentle', at='between', weight=1, mods=('nom', 'normal'),
         text='Mưa như trút. Một cụ ông quần áo ướt sũng ngồi co ro ở sảnh, mấy bạn đọc nhìn rồi xì xào.',
         options=[_o('tea', 'Mời cụ ngồi ghế sảnh, rót cốc trà nóng, cho mượn tờ báo', 'Cụ ngồi đọc báo tới tạnh mưa, lúc về cúi đầu cảm ơn.', True, xp=4),
                  _o('shoo', 'Mời cụ đi chỗ khác cho khỏi phiền', 'Cụ lặng lẽ ra đứng dưới mái hiên. Ông Thạc lắc đầu.', False,
                     review=[2, 'Thư viện của phường mà đuổi cụ già ra mưa.', 1]),
                  _o('let', 'Để cụ ngồi, làm việc tiếp', 'Cụ ngồi tới tạnh mưa rồi đi.', None)],
         default='let'),
    dict(id='moc_sach', title='Phát hiện sách mốc trên kệ', emoji='🍄', npc=0, min_day=2, tone='gentle', at='between', weight=2, mods=('nom',),
         text='Kệ sát tường có ba cuốn mốc trắng mép, mùi ẩm. Hai cuốn bên cạnh bắt đầu lấm tấm.',
         options=[_o('isolate', 'Cách ly vào túi, lau kệ, kéo kệ cách tường, báo cô Nguyệt', 'Mốc không lan sang cuốn khác. Cô Nguyệt ghi kệ đó vào sổ theo dõi.', True, xp=4),
                  _o('wipe', 'Lau mốc bằng khăn ướt rồi xếp lại', 'Khăn ướt làm mốc ăn sâu hơn, tuần sau cả dãy lấm tấm.', False),
                  _o('leave', 'Để đó, mai xem', 'Hai hôm sau mốc lan sang cả kệ.', False)],
         default='leave'),
    dict(id='vi_roi', title='Bạn đọc bỏ quên ví', emoji='👛', npc=2, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Dọn bàn số 4, bạn thấy một cái ví có căn cước, thẻ sinh viên và ít tiền. Chủ ví đã về.',
         options=[_o('log', 'Ghi sổ đồ thất lạc, cất tủ khóa, gọi theo số trong thẻ', 'Vy chạy lại lấy ví, rối rít cảm ơn, hứa khao trà sữa.', True, xp=4),
                  _o('desk', 'Để trên quầy chờ ai tới nhận', 'Một người lạ tới nhận bừa, may mà bạn hỏi tên trên căn cước.', None),
                  _o('peek', 'Mở ví xem có gì', 'Bạn đọc bàn bên thấy, xì xào “thủ thư lục ví khách”.', False,
                     review=[2, 'Thấy cán bộ thư viện lục ví người ta bỏ quên.', 1])],
         default='desk'),
    dict(id='doan_kiem_tra', title='Đoàn kiểm tra của quận', emoji='🗂️', npc=5, min_day=3, tone='tense', at='between', weight=2, mods=('kiem_tra', 'normal'),
         text='Đoàn kiểm tra công tác lưu trữ của quận xuống bất ngờ, xin xem sổ đăng ký, sổ khai thác và nhiệt ẩm kế kho.',
         options=[_o('show', 'Mở sổ thật, chỉ chỗ chưa tốt và kế hoạch khắc phục', 'Đoàn ghi nhận làm thật, góp ý mua thêm máy hút ẩm.', True, xp=6),
                  _o('fake', 'Ghi bù sổ khai thác cho đẹp trước khi đưa', 'Đoàn soi thấy mực mới tinh, lập biên bản nhắc nhở.', False,
                     review=[1, 'Lưu trữ phường ghi bù sổ sách đối phó kiểm tra.', 5]),
                  _o('busy', 'Xin đoàn quay lại hôm khác', 'Đoàn không vui, hẹn tuần sau kiểm kỹ hơn.', None, patience=-3)],
         default='busy'),
    dict(id='chuot_kho', title='Chuột chạy trong kho', emoji='🐭', npc=0, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Mở cửa kho, một con chuột phóng qua chân, chui vào sau dãy hộp hồ sơ. Góc hộp bị gặm nham nhở.',
         options=[_o('trap', 'Đặt bẫy, bịt lỗ thủng, chuyển hộp bị gặm sang hộp mới, báo tổ vệ sinh', 'Hôm sau bẫy dính một con. Hồ sơ trong hộp còn nguyên.', True, xp=4),
                  _o('poison', 'Rải thuốc chuột khắp kho', 'Chuột chết trong khe kệ, cả kho bốc mùi một tuần.', False, patience=-3),
                  _o('ignore', 'Đóng cửa kho lại, kệ nó', 'Tuần sau thêm hai hộp bị gặm.', False)],
         default='ignore'),
    dict(id='sach_hiem_mat', title='Cuốn sách quý không thấy đâu', emoji='📕', npc=4, min_day=3, tone='tense', at='between', weight=1, mods=None,
         text='Kiểm kệ quý hiếm, cuốn “Địa chí phường Mây” bản in 1938 không có chỗ. Sổ mượn không ghi ai mượn.',
         options=[_o('search', 'Tìm các kệ lân cận, xem sổ đọc tại chỗ, báo cô Nguyệt', 'Thấy cuốn sách kẹp nhầm giữa kệ báo cũ. Bạn đặt lại, ghi sổ.', True, xp=5),
                  _o('blame', 'Đổ cho bạn đọc hôm qua, nhắn hỏi khắp nhóm', 'Nhóm phụ huynh xôn xao. Sau mới thấy sách kẹp nhầm kệ.', False,
                     review=[2, 'Thư viện chưa tìm đã nghi bạn đọc ăn cắp sách.', 3]),
                  _o('quiet', 'Lờ đi, chắc ai đó cất', 'Cuối tháng kiểm kê ghi “thất lạc chưa rõ lý do”.', None)],
         default='quiet'),
    dict(id='loa_phuong', title='Loa phường ngay cửa sổ', emoji='📢', npc=1, min_day=2, tone='gentle', at='between', weight=1, mods=None,
         text='Loa phường ngay cửa sổ phòng đọc phát thông báo tiêm phòng chó mèo, ba lần liền. Ông Thạc: “Tắt cái loa đi!”',
         options=[_o('close', 'Đóng cửa sổ, bật quạt, xin ông thông cảm năm phút', 'Năm phút sau loa tắt. Ông Thạc lẩm bẩm nhưng đọc tiếp.', True, xp=3),
                  _o('call', 'Gọi văn phòng phường xin dời loa đi chỗ khác', 'Văn phòng ghi nhận, hẹn họp bàn. Hôm nay vẫn ồn.', None),
                  _o('agree', 'Hùa với ông: “Loa gì mà ồn như chợ!”', 'Ông Thạc đi rêu rao khắp phường là thư viện chê loa phường.', False)],
         default='close'),
    dict(id='tra_qua_khe', title='Thùng trả sách ngoài giờ', emoji='📮', npc=7, min_day=2, tone='gentle', at='open', weight=2, mods=None,
         text='Sáng mở thùng trả sách ngoài giờ: năm cuốn sách, một hộp sữa uống dở đổ lênh láng, một mảnh giấy “em xin lỗi” của Đạt.',
         options=[_o('dry', 'Lau sách bằng giấy thấm, hong chỗ mát, ghi nhận ngày trả', 'Bốn cuốn khô ráo, một cuốn phồng nhẹ. Bạn ghi phiếu tình trạng.', True, xp=4),
                  _o('shelf', 'Xếp thẳng lên kệ cho nhanh', 'Hai hôm sau sách dính sữa bốc mùi, kiến kéo lên kệ.', False),
                  _o('fine', 'Phạt Đạt gấp đôi cho nhớ', 'Mẹ Đạt lên thư viện hỏi quy định nào phạt gấp đôi.', False,
                     review=[2, 'Phạt trẻ con không theo nội quy nào cả.', 7])],
         default='shelf'),
    dict(id='may_hut_am', title='Máy hút ẩm kêu lạ', emoji='💧', npc=0, min_day=2, tone='gentle', at='open', weight=1, mods=('nom',),
         text='Máy hút ẩm kho kêu lục cục, đèn báo đầy nước nhấp nháy từ đêm qua. Ẩm kế chỉ 68%.',
         options=[_o('empty', 'Đổ nước, lau lưới lọc, bật lại, báo sửa nếu còn kêu', 'Máy chạy êm. Trưa ẩm kế còn 58%.', True, xp=4),
                  _o('off', 'Tắt máy cho đỡ ồn', 'Chiều ẩm kế lên 74%, giấy trong kho hơi mềm.', False),
                  _o('fan', 'Bật quạt thổi vào kho thay máy', 'Quạt chỉ đẩy hơi ẩm đi vòng vòng.', None)],
         default='off'),
    dict(id='chua_ke', title='Chú Tư tặng kệ gỗ', emoji='🪵', npc=1, min_day=3, tone='gentle', at='between', weight=1, mods=None,
         text='Ông Thạc dẫn chú Tư sửa đồ lên: “Kệ gỗ nhà tôi thừa, tặng thư viện để sách quý.” Kệ đẹp nhưng gỗ còn ẩm, có lỗ mọt.',
         options=[_o('thanks', 'Cảm ơn, nhận kệ để sảnh trưng báo, sách quý giữ kệ sắt', 'Ông Thạc vui, kệ gỗ thành góc báo xinh. Sách quý an toàn.', True, xp=4),
                  _o('take', 'Nhận, xếp ngay sách quý lên', 'Mọt từ kệ lan sang hai cuốn sách in năm 1960.', False),
                  _o('refuse', 'Từ chối thẳng: “Kệ mọt ai dùng”', 'Ông Thạc tự ái, ba hôm không lên thư viện.', False)],
         default='thanks'),
    dict(id='hoc_sinh_khoc', title='Học sinh khóc vì điểm kém', emoji='😢', npc=7, min_day=2, tone='gentle', at='between', weight=1, mods=None,
         text='Đạt ngồi góc phòng đọc, gục mặt khóc thút thít. Tờ bài kiểm tra toán 3 điểm nằm dưới cuốn truyện tranh.',
         options=[_o('talk', 'Ngồi xuống hỏi nhỏ, gợi ý cuốn Toán vui, hẹn cùng đọc', 'Đạt lau nước mắt, mượn cuốn Toán vui lớp năm. Hôm sau ghé khoe làm được hai bài.', True, xp=4),
                  _o('tissue', 'Đưa hộp giấy, để em yên', 'Đạt ngồi thêm một lúc rồi về.', None),
                  _o('shh', 'Nhắc “phòng đọc phải im lặng”', 'Đạt xách cặp về luôn, mấy hôm không thấy lên.', False)],
         default='tissue'),
]

# ================================================================ situations (the sit_ engine: real-life choices, many perspectives)
SITUATIONS = [
    dict(id='TV-S01', title='Sổ mượn sách của người khác', npc=0, tone='tense', min_day=1,
         opening='Một người đàn ông nói là bố của Vy, xin xem Vy đã mượn những sách gì tháng này: “Tôi là bố nó, tôi có quyền biết!”',
         swap='Bạn là người bố: lo con dạo này buồn, muốn biết con đọc gì.',
         facts=[dict(id='age', title='Bạn đọc', source='Thẻ thư viện', text='Vy hai mươi hai tuổi, thẻ đứng tên Vy.'),
                dict(id='rule', title='Nội quy', source='Bảng nội quy quầy', text='Thông tin mượn sách của bạn đọc chỉ cung cấp cho chính bạn đọc.'),
                dict(id='worry', title='Người bố', source='Nói chuyện', text='Ông lo con căng thẳng mùa thi, nói giọng run run.')],
         options=[dict(id='kind_no', label='Không đưa sổ, thông cảm, khuyên ông nói chuyện với con', requires=['age', 'rule'], quality='good', stars=5,
                       review='Cán bộ thư viện giữ kín chuyện riêng của tôi mà vẫn nói chuyện tử tế với bố tôi.',
                       outcome='Ông bố ngồi lặng một lúc, rồi nhắn rủ Vy đi ăn tối.',
                       perspectives=[dict(who='Vy', emoji='🎧', text='May quá, chuyện mình đọc gì là của mình.'),
                                     dict(who='Người bố', emoji='👨', text='Ừ, hỏi thẳng con vẫn hơn.')]),
                  dict(id='show', label='Cho ông xem, bố mẹ mà', requires=['worry'], quality='bad', stars=1,
                       review='Thư viện đưa lịch sử mượn sách của tôi cho người khác xem. Không thể chấp nhận.',
                       outcome='Vy biết chuyện, khóa thẻ thư viện, không lên nữa.',
                       perspectives=[dict(who='Vy', emoji='😠', text='Mình hai mươi hai tuổi rồi mà.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Sổ mượn là chuyện riêng, ai cũng vậy.')]),
                  dict(id='hint', label='Không đưa sổ nhưng kể sơ “dạo này em ấy đọc sách tâm lý”', quality='bad', stars=2,
                       review='Không đưa sổ mà lại kể miệng, cũng như nhau thôi.', outcome='Ông bố về nhà hỏi dồn Vy về “sách tâm lý”.',
                       perspectives=[dict(who='Vy', emoji='😟', text='Ai kể với bố vậy trời.'),
                                     dict(who='Người bố', emoji='👨', text='Biết thêm một chút, lo thêm một chút.')])],
         lesson='Sổ mượn sách là thông tin riêng của bạn đọc: chỉ nói với chính bạn đọc, kể cả khi người hỏi là người thân.'),
    dict(id='TV-S02', title='Photo nguyên cuốn giáo trình', npc=2, tone='gentle', min_day=1,
         opening='Vy ôm giáo trình mới: “Photo hết giùm em, sinh viên nghèo, mua thì hai trăm xu, cả lớp đang chờ em gửi.”',
         facts=[dict(id='law', title='Bản quyền', source='Nội quy dịch vụ photo', text='Thư viện chỉ sao chụp một phần nhỏ (một chương, dưới một phần mười cuốn) để học tập.'),
                dict(id='ebook', title='Bản điện tử', source='Máy tra cứu', text='Thư viện có tài khoản đọc bản điện tử của giáo trình này, đọc tại chỗ.'),
                dict(id='class', title='Cả lớp', source='Vy', text='Vy định chia bản photo cho bốn mươi bạn.')],
         options=[dict(id='part', label='Photo một chương đang cần, chỉ cách đọc bản điện tử', requires=['law', 'ebook'], quality='good', stars=5,
                       review='Không photo hết được nhưng chị chỉ em đọc bản điện tử, đỡ hẳn tiền.',
                       outcome='Vy đọc bản điện tử tại phòng máy, nhắn cả lớp lên thư viện đọc.',
                       perspectives=[dict(who='Vy', emoji='🎧', text='Hóa ra có bản điện tử, ai biết đâu.'),
                                     dict(who='Tác giả giáo trình', emoji='✍️', text='Sách mình viết được đọc đúng cách, vui.')]),
                  dict(id='all', label='Photo cả cuốn cho sinh viên', requires=['class'], quality='bad', stars=2,
                       review='Photo được cả cuốn, mà nghe nói thư viện bị nhắc vì vi phạm bản quyền.',
                       outcome='Bản photo lan ra cả khoa. Nhà xuất bản gửi thư nhắc thư viện.',
                       perspectives=[dict(who='Cô Nguyệt', emoji='📚', text='Thư viện mà làm lậu sách thì ai giữ sách.'),
                                     dict(who='Vy', emoji='😬', text='Rẻ thì rẻ, mà áy náy.')]),
                  dict(id='no', label='Từ chối, không giải thích gì', quality='ok', stars=3, review='Không photo thì thôi, mà nói câu cộc lốc.',
                       outcome='Vy về tự mua bản photo lậu ngoài tiệm.',
                       perspectives=[dict(who='Vy', emoji='😒', text='Biết vậy ra tiệm luôn.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Từ chối đúng, nhưng phải chỉ đường khác.')])],
         lesson='Sao chụp để học chỉ một phần nhỏ của cuốn sách; nói rõ lý do và chỉ cách khác hợp lệ.'),
    dict(id='TV-S03', title='“Đưa lên đây, nhanh!”', npc=5, tone='tense', min_day=2,
         opening='Ông Bính gọi xuống: “Mang ngay hồ sơ quy hoạch lên phòng họp, đoàn khách đang chờ. Phiếu với sổ để sau!”',
         facts=[dict(id='log', title='Sổ khai thác', source='Quy định kho', text='Hồ sơ ra khỏi kho phải ghi sổ, người nhận ký phiếu.'),
                dict(id='time', title='Thời gian', source='Đồng hồ', text='Ghi sổ, ký phiếu chỉ mất một phút.'),
                dict(id='past', title='Chuyện cũ', source='Cô Nguyệt', text='Năm ngoái một hồ sơ mang lên họp “để sau ký” rồi thất lạc ba tháng.')],
         options=[dict(id='quick', label='Mang lên ngay, kèm phiếu, xin ông ký một chữ', requires=['log', 'time'], quality='good', stars=5,
                       review='Nhanh mà vẫn đúng quy định. Tôi ký mất có mười giây.',
                       outcome='Hồ sơ lên kịp. Họp xong, ông Bính tự mang trả, sổ ghi đủ.',
                       perspectives=[dict(who='Ông Bính', emoji='🏛️', text='Đúng là có phiếu thì khỏi ai hỏi ai.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Lãnh đạo cũng phải ký, vậy mới giữ được hồ sơ.')]),
                  dict(id='skip', label='Mang lên luôn, sổ để sau', requires=['time'], quality='bad', stars=2,
                       review='Mang hồ sơ lên mà không ai ký, giờ không biết đang ở bàn ai.',
                       outcome='Họp xong hồ sơ nằm lẫn trong chồng giấy phòng họp, ba hôm sau mới tìm thấy.',
                       perspectives=[dict(who='Ông Bính', emoji='😓', text='Tôi tưởng cô ấy mang về rồi.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='“Để sau” là lúc hồ sơ đi lạc.')]),
                  dict(id='wait', label='Bắt ông xuống tận kho làm đủ thủ tục', requires=['log'], quality='ok', stars=3,
                       review='Đúng quy định nhưng cứng quá, đoàn khách chờ mười lăm phút.',
                       outcome='Ông Bính xuống ký, mặt không vui. Đoàn khách chờ lâu.',
                       perspectives=[dict(who='Ông Bính', emoji='😤', text='Mang phiếu lên cho tôi ký có phải nhanh không.'),
                                     dict(who='Đoàn khách', emoji='👔', text='Phường làm việc chậm quá.')])],
         lesson='Việc gấp vẫn ghi sổ, ký phiếu; mang phiếu tới tận nơi là vừa nhanh vừa đúng.'),
    dict(id='TV-S04', title='Cuốn sách cũ quý hiếm', npc=1, tone='gentle', min_day=2,
         opening='Trong thùng sách tặng có cuốn Truyện Kiều in năm 1960. Một ông khách lạ đứng xem, ngỏ ý mua lại 200 xu “cho thư viện có tiền”.',
         facts=[dict(id='rare', title='Cuốn sách', source='Trang bản quyền', text='Bản in năm 1960, còn nguyên, ít nơi còn giữ.'),
                dict(id='gift', title='Người tặng', source='Sổ tặng sách', text='Ông Thạc tặng, ghi “để bà con cùng đọc”.'),
                dict(id='rule', title='Quy định', source='Cô Nguyệt', text='Sách tặng là tài sản của thư viện, không bán cho cá nhân.')],
         options=[dict(id='keep', label='Giữ lại, đưa vào kệ sách quý, đọc tại chỗ', requires=['rare', 'gift'], quality='good', stars=5,
                       review='Cuốn sách của tôi được giữ đúng ý: để bà con cùng đọc.',
                       outcome='Cuốn sách lên kệ quý. Ông Thạc ngày nào cũng ghé nhìn một cái.',
                       perspectives=[dict(who='Ông Thạc', emoji='👓', text='Tôi tặng là để người ta đọc, không phải để bán.'),
                                     dict(who='Đạt', emoji='📗', text='Sách gì mà cũ hơn cả ông nội em.')]),
                  dict(id='sell', label='Bán lấy tiền mua sách mới', requires=['rare'], quality='bad', stars=1,
                       review='Sách tôi tặng mà thư viện đem bán cho người lạ!',
                       outcome='Ông Thạc biết chuyện, giận cả tháng.',
                       perspectives=[dict(who='Ông Thạc', emoji='😠', text='Biết vậy tôi giữ ở nhà.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Sách tặng không phải để mình mang đi bán.')]),
                  dict(id='weed', label='Sách cũ quá, loại khỏi kho', quality='bad', stars=2, review='Sách quý vậy mà định bỏ.',
                       outcome='Cô Nguyệt nhặt lại từ thùng thanh lý, lắc đầu.',
                       perspectives=[dict(who='Cô Nguyệt', emoji='📚', text='Cũ không phải là hỏng.'),
                                     dict(who='Anh Tuấn', emoji='📜', text='Bản in năm 1960 là tư liệu đó.')])],
         lesson='Sách cũ chưa chắc là sách hỏng: sách quý giữ lại cho bạn đọc, không bán cho cá nhân.'),
    dict(id='TV-S05', title='Tiền phạt của cậu bé', npc=7, tone='gentle', min_day=2,
         opening='Đạt trả sách trễ mười hai ngày. Theo nội quy phải nộp 12 xu, mà em chỉ có 3 xu, mắt đỏ hoe.',
         facts=[dict(id='why', title='Lý do', source='Đạt', text='Em ở nhà trông em gái hai tuần vì mẹ nằm viện, có giấy ra viện của mẹ.'),
                dict(id='rule', title='Nội quy', source='Bảng nội quy', text='Trả trễ vì ốm đau, thiên tai, có giấy tờ: cán bộ được miễn phí trễ hạn, ghi rõ lý do.'),
                dict(id='book', title='Cuốn sách', source='Kiểm sách', text='Sách còn nguyên.')],
         options=[dict(id='waive', label='Miễn phí trễ hạn, ghi lý do vào sổ', requires=['why', 'rule'], quality='good', stars=5,
                       review='Cô hiểu chuyện nhà em, còn dặn em mượn tiếp.',
                       outcome='Đạt cười toe, mượn thêm cuốn Toán vui. Sổ ghi rõ lý do miễn.',
                       perspectives=[dict(who='Đạt', emoji='📗', text='Em tưởng bị phạt hết tiền ăn sáng.'),
                                     dict(who='Kế toán phường', emoji='🧾', text='Có lý do, có ghi sổ, vậy là đúng.')]),
                  dict(id='full', label='Phạt đủ 12 xu, ghi nợ phần thiếu', requires=['rule'], quality='ok', stars=3,
                       review='Đúng nội quy nhưng nhà em đang khó mà.', outcome='Đạt nộp 3 xu, nợ 9 xu, mấy hôm không dám lên thư viện.',
                       perspectives=[dict(who='Đạt', emoji='😢', text='Em không dám mượn nữa.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Nội quy có chỗ cho lý do chính đáng.')]),
                  dict(id='quiet', label='Lờ đi, không ghi gì cả', quality='bad', stars=3, review='Không phạt thì tốt, mà sổ không ghi gì.',
                       outcome='Cuối tháng sổ phí lệch, kế toán phường hỏi, không ai nhớ vì sao.',
                       perspectives=[dict(who='Kế toán phường', emoji='🧾', text='Miễn được, nhưng phải ghi.'),
                                     dict(who='Đạt', emoji='📗', text='Ơ, vậy là được à?')])],
         lesson='Miễn phí khi có lý do chính đáng là đúng, nhưng phải ghi rõ lý do vào sổ.'),
    dict(id='TV-S06', title='Phụ huynh đòi gỡ sách', npc=3, tone='tense', min_day=3,
         opening='Chị Loan cầm cuốn truyện thiếu nhi về tình bạn của hai bạn nhỏ: “Truyện có cảnh hai bạn cãi nhau với bố mẹ, gỡ ngay, dạy hư con tôi!”',
         facts=[dict(id='age', title='Cuốn sách', source='Bìa sau', text='Sách ghi độ tuổi 9 – 12, được nhiều trường giới thiệu.'),
                dict(id='policy', title='Tiêu chí chọn sách', source='Sổ tay thư viện', text='Sách được chọn theo độ tuổi, nội dung cả cuốn; ý kiến bạn đọc được ghi nhận, xem xét.'),
                dict(id='kid', title='Bé Su', source='Hỏi chuyện', text='Bé Su bảy tuổi, mới lớp hai.')],
         options=[dict(id='listen', label='Ghi nhận, gợi ý sách hợp tuổi bé Su, giữ sách trên kệ 9 – 12', requires=['age', 'kid', 'policy'], quality='good', stars=5,
                       review='Cô nghe tôi nói hết, còn chọn giúp sách hợp tuổi con.',
                       outcome='Chị Loan mượn ba cuốn cho tuổi lên bảy. Cuốn kia vẫn ở kệ 9 – 12.',
                       perspectives=[dict(who='Chị Loan', emoji='👩‍👧‍👦', text='Ừ, sách đó cho bé lớn, chị chọn nhầm.'),
                                     dict(who='Một bé lớp 5', emoji='🧒', text='Truyện đó hay mà, may không bị gỡ.')]),
                  dict(id='remove', label='Gỡ sách ngay cho chị vui', quality='bad', stars=2, review='Gỡ thì gỡ, mà có ai xem nội dung đâu.',
                       outcome='Tuần sau một phụ huynh khác hỏi sao cuốn sách trường giới thiệu không còn.',
                       perspectives=[dict(who='Cô Nguyệt', emoji='📚', text='Một người không thích thì chưa phải lý do gỡ sách.'),
                                     dict(who='Phụ huynh khác', emoji='👨‍👧', text='Con tôi đang cần cuốn đó.')]),
                  dict(id='argue', label='Cãi lại: “Chị không hiểu sách thiếu nhi”', requires=['age'], quality='bad', stars=1,
                       review='Hỏi một câu mà bị nói như tát nước.', outcome='Chị Loan đăng bài trong nhóm phụ huynh.',
                       perspectives=[dict(who='Chị Loan', emoji='😤', text='Tôi là mẹ, tôi có quyền lo.'),
                                     dict(who='Cô Nguyệt', emoji='📚', text='Đúng mà nói kiểu đó thì thành sai.')])],
         lesson='Nghe ý kiến bạn đọc, xem cả cuốn và độ tuổi trước khi quyết; gợi ý sách hợp với từng em.'),
]

STORIES = [('Chùm chìa khóa kho', ('Cô Nguyệt đưa bạn chùm chìa khóa kho lưu trữ, chiếc nào cũng buộc một mẩu vải màu.',
                                    'Cô dặn: “Hồ sơ của dân là của dân. Mình chỉ giữ hộ.”',
                                    'Lần đầu bạn tự tìm đúng hộp hồ sơ, cô Nguyệt gật đầu, trao luôn chìa khóa đỏ.')),
           ('Ẩm kế trên tường', ('Cái ẩm kế kim đồng hồ treo trên tường kho từ năm 1995.',
                                 'Trời nồm, kim nhích lên 70%, cô Nguyệt bật máy hút ẩm, mở từng hộp xem giấy.',
                                 'Bạn chép lịch đo độ ẩm mỗi sáng vào cuốn sổ mới, dán ngay cạnh ẩm kế.')),
           ('Giờ kể chuyện', ('Cuối tuần, tầng hai nhà văn hóa rộn tiếng trẻ con.',
                              'Lần đầu bạn kể chuyện, mười hai bé ngồi không yên.',
                              'Tuần thứ tư, các bé tự kéo ghế ngồi thành vòng tròn chờ bạn.'))]
REVIEW_ASIDES = ['Tra ký hiệu nhanh như máy, tìm sách trúng phóc.', 'Phí phạt rõ ràng, có biên lai đàng hoàng.',
                 'Phòng đọc yên tĩnh mà không ai bị nói nặng.', 'Hồ sơ lấy đúng hộp, bản sao rõ nét.']
