"""Người gác hải đăng: the people around the light (game/careers/lighthouse.py).

* DESK        surprises (game/careers/kit.py desk scripts): one good choice each, a default for when nobody decides.
* ODD         the chuyện oái oăm (game/careers/air_odd.py scripts): the player answers in their own tone and words,
              the other side decides by hidden traits. Charm stays PG-13, harassment is reported, giving in is never
              rewarded, corners cut are reported without blame.
* SITUATIONS  the sit_ engine: read the facts, choose, see it from two or three sides.
Everything is fictional; the island's rules are game rules.
"""
from __future__ import annotations

from .lighthouse_content import BAY, YEN, KHOI, SAU, LUC, VY, DUC, THAM

# ================================================================ surprises (kit desk scripts)
DESK = [
    dict(id='hd-blackout', title='Mất điện giữa đêm', emoji='🔌', npc=BAY, min_day=2, tone='tense', at='any', weight=3, mods=None,
         text='Đèn trong nhà trạm phụt tắt. Trên đỉnh tháp, đèn biển chớp một cái rồi tối hẳn. Ắc quy báo lỗi.',
         options=[dict(id='backup', label='Chạy máy phát dự phòng, kiểm đèn sáng lại đúng đặc tính, gọi đài báo đèn tắt mấy phút', hint='', effects=dict(xp=6), good=True,
                       outcome='Máy phát nổ giòn, đèn sáng lại sau bốn phút. Đài ghi nhận, phát tin cho tàu thuyền gần đó.'),
                  dict(id='wait', label='Chờ xem ắc quy có tự lên lại không', hint='', effects=dict(review=[1, 'Đèn biển tắt mà trạm ngồi chờ, không báo đài.', 1]), good=False,
                       outcome='Hai mươi phút đèn tắt. Một tàu hàng gọi đài hỏi “đèn Hòn Gió đâu rồi?”.'),
                  dict(id='quiet', label='Chạy máy phát, đèn sáng lại thì thôi, khỏi báo cho đỡ rầy', hint='Đỡ bị hỏi', effects=dict(xp=2), good=None,
                       outcome='Đèn sáng lại. Sáng mai đài hỏi sao đêm qua có tàu thấy đèn tắt mà trạm không báo.')],
         default='wait'),
    dict(id='hd-bird', title='Chim đâm vào kính đèn', emoji='🐦', npc=BAY, min_day=2, tone='gentle', at='any', weight=2, mods=None,
         text='Một con chim biển lao vào kính phòng đèn trong gió, rơi xuống ban công, cánh còn đập yếu ớt.',
         options=[dict(id='care', label='Kiểm kính có nứt không, lau sạch, đặt chim vào hộp giấy nơi kín gió', hint='', effects=dict(xp=5), good=True,
                       outcome='Kính chỉ trầy nhẹ. Sáng hôm sau con chim vỗ cánh bay đi, Mun nhìn theo tiếc rẻ.'),
                  dict(id='leave', label='Kệ, chim trời mà', hint='', effects={}, good=None, outcome='Vết máu với lông chim dính trên kính, đêm đó tia sáng mờ một góc.'),
                  dict(id='mun', label='Để mèo Mun “xử lý”', hint='', effects=dict(review=[3, 'Để mèo vờn chim bị thương ngay ban công đèn. Hơi kỳ.']), good=False,
                       outcome='Mun lôi con chim chạy vòng ban công, lông bay tứ tung, dính cả vào khe kính.')],
         default='leave'),
    dict(id='hd-lightning', title='Giông sét kéo tới', emoji='⚡', npc=BAY, min_day=2, tone='tense', at='any', weight=2, mods=('storm', 'breeze'),
         text='Mây đen kéo sát đỉnh tháp, sét đánh ngoài khơi liên tục. Đèn vẫn chạy, cửa ban công đang mở.',
         options=[dict(id='safe', label='Đóng cửa ban công, xuống khỏi tháp, theo dõi đèn qua bảng điều khiển dưới nhà', hint='', effects=dict(xp=6), good=True,
                       outcome='Sét đánh trúng cột thu lôi lúc bạn đã xuống nhà. Đèn vẫn quét đều.'),
                  dict(id='stay', label='Đứng trên ban công quay video sét cho đẹp', hint='', effects=dict(review=[2, 'Đứng trên đỉnh tháp lúc giông sét để quay clip.', 1]), good=False,
                       outcome='Một tiếng nổ chát chúa ngay trên đầu. Bạn ù tai cả buổi, điện thoại rơi vỡ màn.'),
                  dict(id='unplug', label='Rút điện cả đèn biển cho chắc', hint='Đèn tắt', effects=dict(review=[1, 'Tự tắt đèn biển giữa giông.', 1]), good=False,
                       outcome='Đèn tắt giữa lúc tàu thuyền chạy giông tìm đường vào bờ. Đài gọi hỏi dồn dập.')],
         default='stay'),
    dict(id='hd-mun-lost', title='Mèo Mun mất tích', emoji='🐈‍⬛', npc=BAY, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Cả buổi không thấy Mun đâu. Gió đang lên, mỏm đá phía bắc sóng đánh trắng xóa.',
         options=[dict(id='search', label='Tìm quanh nhà trạm, kho, bể nước; không ra mỏm đá khi sóng lớn', hint='', effects=dict(xp=4), good=True,
                       outcome='Mun nằm khoanh tròn trong thùng giẻ ở kho máy phát, ngủ ngon lành.'),
                  dict(id='rocks', label='Leo ra mỏm đá phía bắc tìm', hint='Sóng lớn', effects=dict(review=[2, 'Ra mỏm đá lúc sóng lớn tìm mèo, suýt bị sóng cuốn.', 1]), good=False,
                       outcome='Một con sóng chồm qua mỏm đá, bạn ướt sũng, trầy cả hai tay. Mun thì ở trong kho.'),
                  dict(id='later', label='Mèo đói tự về', hint='', effects={}, good=None, outcome='Tối Mun về, kêu meo meo đòi ăn như chưa có gì.')],
         default='later'),
    dict(id='hd-water', title='Bể nước ngọt cạn đáy', emoji='💧', npc=BAY, min_day=3, tone='tense', at='any', weight=2, mods=None,
         text='Bể nước mưa chỉ còn một gang tay. Tàu tiếp tế còn mấy ngày nữa mới ra.',
         options=[dict(id='ration', label='Chia khẩu phần nước, hứng nước mưa, gọi đài nhắn xí nghiệp gửi nước sớm', hint='', effects=dict(xp=5), good=True,
                       outcome='Xí nghiệp nhờ tàu cá tiện đường mang ra mười bình nước. Đêm đó còn có mưa rào.'),
                  dict(id='sea', label='Nấu nước biển uống tạm', hint='', effects=dict(review=[2, 'Nấu nước biển để uống, ngộ độc muối cả ngày.', 1]), good=False,
                       outcome='Nước mặn chát, uống vào khát thêm. Bạn mệt lả cả buổi chiều.'),
                  dict(id='buy', label='Mua lại nước của tàu cá đi ngang, giá cắt cổ', hint='Mất 15 xu', effects=dict(money=-15), good=None,
                       outcome='Ông chủ tàu cá bán mười lăm xu năm bình nước. Đắt, nhưng có nước.')],
         default='buy'),
    dict(id='hd-dolphin', title='Cá heo mắc cạn', emoji='🐬', npc=YEN, min_day=3, tone='gentle', at='between', weight=1, mods=None,
         text='Một con cá heo nhỏ mắc cạn ở bãi đá lúc triều rút, thở phì phò, da khô dần.',
         options=[dict(id='wet', label='Giữ ướt da bằng khăn và nước biển, gọi đài báo cơ quan thủy sản, không kéo đuôi', hint='', effects=dict(xp=5), good=True,
                       outcome='Bạn tưới nước suốt hai tiếng. Triều lên, con cá heo trườn ra, quẫy một vòng rồi lặn mất.'),
                  dict(id='pull', label='Nắm đuôi kéo ra nước cho nhanh', hint='', effects=dict(review=[3, 'Kéo đuôi cá heo, nó bị thương.']), good=False,
                       outcome='Con cá heo giãy mạnh, trầy một vệt dài trên bụng.'),
                  dict(id='film', label='Quay clip đăng mạng trước đã', hint='', effects={}, good=None, outcome='Clip được vài trăm lượt thích. Con cá heo khô da thêm nửa tiếng.')],
         default='film'),
    dict(id='hd-drum', title='Thùng phuy lạ trôi dạt vào bãi', emoji='🛢️', npc=YEN, min_day=3, tone='tense', at='between', weight=2, mods=None,
         text='Một thùng phuy gỉ sét dạt vào bãi đá, nắp còn kín, có mùi hắc, vỏ in chữ nước ngoài.',
         options=[dict(id='report', label='Không mở, không lại gần, rào lối, gọi đài báo xí nghiệp và biên phòng', hint='', effects=dict(xp=6), good=True,
                       outcome='Đội xử lý môi trường ra đảo lấy thùng phuy: hóa chất công nghiệp. Họ khen trạm không đụng vào.'),
                  dict(id='open', label='Cạy nắp xem bên trong có gì', hint='', effects=dict(review=[1, 'Tự cạy nắp thùng hóa chất trôi dạt.', 1]), good=False,
                       outcome='Hơi hắc xộc lên làm bạn chóng mặt, ho sặc sụa cả buổi.'),
                  dict(id='push', label='Đẩy nó ra biển lại cho xong', hint='', effects=dict(review=[2, 'Đẩy thùng hóa chất ra biển cho trôi đi chỗ khác.']), good=None,
                       outcome='Thùng phuy trôi đi, ba hôm sau dạt vào bãi tắm Cửa Lở.')],
         default='push'),
    dict(id='hd-shell', title='Vật lạ hình quả đạn', emoji='💣', npc=BAY, min_day=4, tone='tense', at='between', weight=1, mods=None,
         text='Đào luống rau mới, xẻng chạm vào một vật kim loại gỉ hình quả đạn, dài chừng gang tay.',
         options=[dict(id='leave', label='Dừng tay, cắm cờ đánh dấu, tránh xa, gọi đài báo biên phòng', hint='', effects=dict(xp=6), good=True,
                       outcome='Công binh ra đảo xử lý: đạn cối còn từ thời chiến. Họ dặn ai thấy cũng làm như bạn.'),
                  dict(id='dig', label='Đào lên xem cho rõ', hint='', effects=dict(review=[1, 'Tự đào vật nghi là bom đạn.', 1]), good=False,
                       outcome='Chú Bảy chạy ra quát giữ tay bạn lại. Mặt chú tái mét.'),
                  dict(id='sell', label='Để dành bán phế liệu', hint='', effects=dict(review=[1, 'Định bán bom đạn làm phế liệu.', 1]), good=False,
                       outcome='Chú Bảy nghe xong lắc đầu, tự gọi đài báo biên phòng.')],
         default='dig'),
    dict(id='hd-inspect', title='Anh Khôi kiểm tra đột xuất', emoji='📋', npc=KHOI, min_day=2, tone='tense', at='any', weight=3, mods=None,
         text='Anh Khôi gọi bộ đàm: “Đọc tôi nghe sổ dầu ba ngày qua. Hôm kia đốt bao nhiêu lít máy phát?”',
         options=[dict(id='read', label='Đọc đúng từng dòng, nói rõ chỗ hôm kia ghi thiếu giờ chạy máy', hint='', effects=dict(xp=6), good=True,
                       outcome='Anh Khôi im một lúc: “Thật thà là được. Bổ sung ngay.” Rồi ghi nhận kiểm tra đạt.'),
                  dict(id='round', label='Đọc số tròn cho đẹp', hint='Sửa miệng', effects=dict(review=[2, 'Đọc sổ dầu “cho tròn”, số không khớp bồn.']), good=False,
                       outcome='Anh Khôi cộng lại: thiếu mười hai lít không ai giải thích được.'),
                  dict(id='static', label='Giả vờ bộ đàm rè, hẹn gọi lại', hint='', effects=dict(review=[2, 'Kiểm tra mà giả vờ mất sóng.']), good=None,
                       outcome='Anh Khôi gọi lại bằng điện thoại vệ tinh. Không khí căng hơn.')],
         default='static'),
    dict(id='hd-toothache', title='Đau răng giữa đêm', emoji='🦷', npc=YEN, min_day=3, tone='gentle', at='any', weight=1, mods=None,
         text='Răng hàm đau nhức từ chiều, má sưng nhẹ. Bác sĩ gần nhất ở đất liền, cách mười hai hải lý.',
         options=[dict(id='advice', label='Gọi đài xin nối máy tư vấn y tế từ xa, làm theo hướng dẫn, ghi sổ trực', hint='', effects=dict(xp=4), good=True,
                       outcome='Bác sĩ trực dặn súc nước muối ấm, theo dõi sưng sốt, tàu tiếp tế gần nhất thì vào bờ khám.'),
                  dict(id='pills', label='Lục tủ thuốc uống đại thứ gì có chữ “giảm đau”', hint='', effects=dict(review=[2, 'Uống thuốc lung tung không hỏi ai.']), good=False,
                       outcome='Thuốc hết hạn từ năm ngoái. Đau thì vẫn đau, bụng còn cồn cào thêm.'),
                  dict(id='endure', label='Ráng chịu, không nói ai', hint='', effects={}, good=None, outcome='Cả đêm không ngủ, sáng ra mắt thâm quầng.')],
         default='endure'),
    dict(id='hd-fumes', title='Mùi dầu trong nhà máy phát', emoji='🛢️', npc=BAY, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Mở cửa nhà máy phát, mùi dầu nồng nặc. Dưới chân bồn có một vũng dầu loang.',
         options=[dict(id='vent', label='Mở cửa thông gió, không bật lửa hay công tắc, thấm dầu bằng cát, ghi sổ, báo xí nghiệp', hint='', effects=dict(xp=6), good=True,
                       outcome='Khớp ống dưới đáy bồn bị nứt. Xí nghiệp gửi ống mới theo chuyến tàu gần nhất.'),
                  dict(id='light', label='Bật đèn, châm thuốc cho tỉnh rồi tìm chỗ rò', hint='', effects=dict(review=[1, 'Hút thuốc trong nhà máy phát đang rò dầu.', 1]), good=False,
                       outcome='Chú Bảy giật điếu thuốc khỏi miệng bạn, đẩy bạn ra ngoài. Không ai nói câu nào.'),
                  dict(id='mop', label='Lau sạch vũng dầu là xong', hint='', effects={}, good=None, outcome='Hôm sau vũng dầu lại loang đúng chỗ cũ.')],
         default='mop'),
    dict(id='hd-panels', title='Hải âu làm tổ trên tấm pin', emoji='🕊️', npc=BAY, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Một cặp hải âu tha rác làm tổ ngay trên dàn pin mặt trời. Đồng hồ sạc tụt rõ.',
         options=[dict(id='move', label='Dọn tổ khi chưa có trứng, giăng dây ruy băng xua chim, lau pin', hint='', effects=dict(xp=4), good=True,
                       outcome='Cặp hải âu chuyển sang làm tổ trên mỏm đá phía nam. Pin sạc lại đầy.'),
                  dict(id='shoot', label='Ném đá đuổi cho bõ tức', hint='', effects=dict(review=[3, 'Ném đá vào chim, trúng cả tấm pin.']), good=False,
                       outcome='Một hòn đá trượt, nứt góc tấm pin. Cặp hải âu bay đi rồi lại về.'),
                  dict(id='leave', label='Để đó, chạy máy phát sạc bù', hint='Tốn dầu', effects={}, good=None, outcome='Dầu máy phát hụt nhanh hơn thường lệ.')],
         default='leave'),
    dict(id='hd-ghost-light', title='Ánh đèn lạ ngoài bãi đá', emoji='🔦', npc=BAY, min_day=3, tone='gentle', at='any', weight=1, mods=('fog', 'calm'),
         text='Nửa đêm có ánh đèn chập chờn ngoài bãi đá phía tây. Dân làng chài vẫn đồn là “ma đèn”.',
         options=[dict(id='look', label='Dùng ống nhòm xem kỹ từ trạm, ghi phương vị, hỏi đài có tàu nào quanh đó không', hint='', effects=dict(xp=5), good=True,
                       outcome='Là một thuyền thúng câu mực thắp đèn bình. Đài xác nhận, bạn ghi vào sổ trực, ngủ ngon.'),
                  dict(id='go', label='Cầm đèn pin một mình ra bãi đá xem', hint='', effects=dict(review=[2, 'Một mình ra bãi đá lúc nửa đêm sương mù.', 1]), good=False,
                       outcome='Bạn trượt chân trên đá rêu, đèn pin rơi xuống khe. Mò mẫm mãi mới về được.'),
                  dict(id='pray', label='Thắp nhang khấn vái cho yên', hint='', effects={}, good=None, outcome='Ánh đèn vẫn chập chờn tới sáng. Bạn thức trắng.')],
         default='pray'),
    dict(id='hd-stray-buoy', title='Phao đánh dấu luồng trôi khỏi vị trí', emoji='🟢', npc=YEN, min_day=3, tone='tense', at='any', weight=2, mods=('storm', 'breeze', 'calm'),
         text='Qua ống nhòm, phao số 3 đánh dấu luồng vào Cửa Lở không còn ở chỗ cũ, trôi lệch về phía bãi đá.',
         options=[dict(id='report', label='Ghi phương vị, gọi đài để phát thông báo hàng hải, báo xí nghiệp', hint='', effects=dict(xp=6), good=True,
                       outcome='Đài phát SÉCURITÉ cho tàu thuyền. Tàu công tác của xí nghiệp ra kéo phao về chỗ cũ.'),
                  dict(id='later', label='Để chuyến tàu tiếp tế báo luôn', hint='', effects=dict(review=[1, 'Phao luồng trôi mà trạm để mấy ngày mới báo.', 1]), good=False,
                       outcome='Một tàu cá chạy theo phao lệch, suýt cạn trên bãi đá.'),
                  dict(id='call_sau', label='Nhắn ông Sáu Ghe báo cho dân làng', hint='', effects=dict(xp=2), good=None,
                       outcome='Dân làng biết, nhưng tàu lạ thì không ai báo. Đài hỏi sao không gọi.')],
         default='later'),
    dict(id='hd-solar-thief', title='Ghe lạ cập bến lúc khuya', emoji='🚤', npc=BAY, min_day=4, tone='tense', at='any', weight=1, mods=None,
         text='Một chiếc ghe tắt đèn cập bến lúc khuya. Hai người lom khom đi về phía dàn pin mặt trời.',
         options=[dict(id='light', label='Bật đèn pha sân trạm, lên tiếng từ trong nhà, gọi đài báo biên phòng', hint='', effects=dict(xp=6), good=True,
                       outcome='Hai người giật mình chạy xuống ghe. Biên phòng chặn được ghe ở cửa luồng.'),
                  dict(id='fight', label='Cầm gậy ra đuổi một mình', hint='', effects=dict(review=[2, 'Cầm gậy một mình ra đuổi người lạ giữa đêm.', 1]), good=False,
                       outcome='Họ bỏ chạy, nhưng bạn trượt chân trên bậc đá, đầu gối tím bầm.'),
                  dict(id='hide', label='Tắt đèn trốn trong nhà', hint='', effects=dict(money=-10), good=None,
                       outcome='Sáng ra mất hai tấm pin. Xí nghiệp trừ mười xu tiền trách nhiệm vì không báo.')],
         default='hide'),
    dict(id='hd-tet', title='Tết trên đảo', emoji='🧧', npc=BAY, min_day=5, tone='gentle', at='any', weight=1, mods=None,
         text='Ba mươi Tết. Trên đảo chỉ có bạn, chú Bảy và Mun. Bộ đàm rộn tiếng các trạm chúc nhau.',
         options=[dict(id='share', label='Gói bánh với chú Bảy, gọi chúc Tết đài và các trạm, vẫn trực đèn đủ giờ', hint='', effects=dict(xp=5), good=True,
                       outcome='Đêm giao thừa, cả vịnh vang tiếng còi tàu chúc Tết. Đèn Hòn Gió quét đều qua năm mới.'),
                  dict(id='drink', label='Nhậu một bữa cho quên nhớ nhà', hint='', effects=dict(review=[2, 'Say sưa đêm giao thừa, quên giờ kiểm đèn.']), good=False,
                       outcome='Gần sáng đèn báo lỗi bộ đổi bóng, bạn ngủ say không nghe. Chú Bảy lên sửa một mình.'),
                  dict(id='sad', label='Ngồi một mình xem ảnh nhà', hint='', effects={}, good=None, outcome='Nhớ nhà quay quắt. Chú Bảy gõ cửa đưa chén trà nóng.')],
         default='sad'),
    dict(id='hd-squid-light', title='Tàu câu mực rọi đèn vào đảo', emoji='🦑', npc=SAU, min_day=3, tone='gentle', at='any', weight=2, mods=('calm', 'fog'),
         text='Mấy tàu câu mực neo sát đảo, bật dàn đèn trắng chói lóa. Từ xa, ánh đèn biển lẫn hẳn vào đám đèn câu.',
         options=[dict(id='ask', label='Gọi kênh 16 nhờ các tàu dời ra xa luồng, báo đài lưu ý tàu qua lại', hint='', effects=dict(xp=5), good=True,
                       outcome='Các tàu câu mực dời ra ngoài hai hải lý. Đèn Hòn Gió lại rõ trên nền trời đêm.'),
                  dict(id='shout', label='Ra bến quát cho họ đi', hint='', effects=dict(review=[3, 'Ra bến quát tháo ngư dân.']), good=None,
                       outcome='Họ không nghe thấy gì, chỉ thấy bạn vung tay.'),
                  dict(id='ignore', label='Kệ, biển rộng mà', hint='', effects=dict(review=[2, 'Để đèn biển lẫn vào đèn câu mực.', 1]), good=False,
                       outcome='Một tàu hàng nhận nhầm đèn, chạy lệch luồng mười phút.')],
         default='ignore'),
]

# ================================================================ chuyện oái oăm (air_odd scripts)
WORDS = {
    'charm': dict(no='Em xin phép từ chối.', duty='Em đang trực đèn.', rule='Nội quy trạm không cho người ngoài ở lại, không hẹn hò khi trực.',
                  alt='Cảm ơn, chúc bạn đi biển bình an.', joke='Cười cười cho qua.', later='Để hôm khác nha…', yes='Nhận lời.'),
    'harass': dict(stop='Dừng lại ngay.', no='Không. Tôi không đồng ý.', rule='Quấy rối người đang trực là vi phạm.',
                   duty='Tôi đang trực đèn.', joke='Cười trừ cho qua.', later='Thôi, bỏ qua đi.', yes='Chiều cho xong chuyện.'),
    'demand': dict(no='Dạ không được ạ.', rule='Nội quy trạm đèn không cho phép.', alt='Có cách khác nè…', why='Mình cần vậy vì sao ạ?',
                   joke='Đùa cho qua.', later='Để em xem đã.', yes='Chiều theo.'),
    'corner': dict(speak='Mình chưa làm đủ bước.', rule='Quy trình bắt buộc mà.', alt='Làm nhanh mà vẫn đủ bước.',
                   joke='Cười xòa cho qua.', yes='Làm theo.'),
    'bargain': dict(rule='Vượt thời gian trực quy định rồi.', health='Sức khỏe em không cho phép.', alt='Em đề xuất cách khác.',
                    paper='Cho em xin văn bản phân công.', yes='Nhận hết.'),
}
TEXT = {
    'charm': dict(report='Bạn báo chú Bảy và ghi sổ trực. Xí nghiệp nhắc khéo {who}; hồ sơ bạn thêm dòng “xử lý đúng mực”.',
                  stuck='Chuyện cứ lấp lửng không dứt. Ở bến Cửa Lở bắt đầu có người xì xào.'),
    'corner': dict(report='Bạn báo xí nghiệp (người báo không bị phạt). Phòng kỹ thuật cho người kiểm tra lại; {who} phải học lại quy trình.',
                   stuck='{who} vẫn làm tắt. Hôm nay qua êm, nhưng bạn biết mình đã im lặng.'),
}


def _odd(sid, kind, rank, emoji, title, who, text, push, **kw):
    x = dict(id=sid, kind=kind, rank=rank, emoji=emoji, title=title, who=who, text=text, push=list(push), **kw)
    x['words'] = {**WORDS[kind], **kw.get('words', {})}
    for k, v in TEXT.get(kind, {}).items():
        x.setdefault(k, v)
    return x


ODD = [
    # --- charm (PG-13): decline, set the line, report if it keeps coming
    _odd('hd-radio-flirt', 'charm', 'pax', '📻', 'Giọng ngọt trên kênh 16', 'Bé Thủy · con gái chủ vựa cá Cửa Lở',
         '“Anh gác đèn ơi, đêm nào em cũng nghe giọng anh trên kênh 16. Tối nay anh mở đèn pha sân trạm nháy ba cái cho em biết anh nhớ em nha 😘”',
         ['“Nháy ba cái thôi mà, có ai biết đâu.”', '“Anh không nháy là em buồn, mai em chèo thúng ra tận đảo đó nha.”'],
         persist=(1, 3), mood=(0, 1), weight=2, words={'rule': 'Đèn trạm là tín hiệu hàng hải, không phải để nhắn tin.', 'alt': 'Muốn nói chuyện thì gọi điện ban ngày nhé, đừng dùng kênh 16.'},
         back='Bé Thủy cười khúc khích rồi tắt máy. Kênh 16 im lặng trở lại.',
         give='Bạn nháy đèn pha ba cái. Một tàu cá gần đó tưởng tín hiệu cầu cứu, gọi đài hỏi rối rít.'),
    _odd('hd-vy-collab', 'charm', 'pax', '💌', 'Vy Vlog rủ “collab hẹn hò”', 'Vy Vlog · 300k follow',
         '“Anh ơi làm series “hẹn hò với anh gác đèn” với em nha! Anh chỉ cần đóng vai người yêu em ba ngày trên đảo thôi, view nổ luôn á!”',
         ['“Anh cute mà, lên hình là có fan liền. Thử một tập thôi!”', '“Không đóng thì em đăng cảnh anh từ chối, caption “anh gác đèn lạnh lùng” 😏”'],
         persist=(2, 3), mood=(0, 2), weight=2, npc=VY, words={'alt': 'Muốn quay về nghề thì liên hệ xí nghiệp, quay ở sân trạm ban ngày.'},
         back='Vy bĩu môi: “Okela, anh nghiêm túc ghê.” Rồi chuyển sang quay đàn hải âu.',
         give='Bạn nhận lời. Ba ngày quay phim, sổ trực bỏ trống hai buổi quan trắc, đài gọi hỏi liên tục.'),
    _odd('hd-stargaze', 'charm', 'pax', '🌌', 'Cô khách xin ở lại “ngắm sao cùng anh”', 'Cô khách tàu du lịch',
         '“Đoàn về rồi, em xin ở lại đảo một đêm ngắm sao với anh nha. Em ngủ ở đâu cũng được, kể cả… phòng anh 😉”',
         ['“Có một đêm thôi, ai mà biết.”', '“Anh sợ gì? Em đâu có ăn thịt anh.”'],
         persist=(1, 3), mood=(0, 1), weight=2, words={'alt': 'Tàu Biển Ngọc còn chuyến chiều, mình gọi giữ chỗ cho bạn nhé.'},
         back='Cô khách cười gượng rồi xuống tàu chuyến chiều. Cô Thắm nháy mắt với bạn.',
         give='Bạn cho cô ở lại. Sáng mai cô Thắm báo xí nghiệp: khách của tour ngủ lại đảo trái nội quy.'),
    _odd('hd-captain-gift', 'charm', 'boss', '🎁', 'Giỏ quà “làm quen” của chủ vựa', 'Ông Năm Vựa · chủ vựa cá Cửa Lở',
         '“Giỏ quà nhỏ cho cậu. Đêm tàu tôi về, cậu thương thì quay đèn pha rọi giùm cái bến riêng của tôi.”',
         ['“Quà nhỏ thôi, ai mà chả nhận.”', '“Không nhận là coi thường tôi đó nghe.”'],
         persist=(1, 2), mood=(0, 2), weight=2, words={'rule': 'Đèn của trạm rọi theo nội quy, không theo quà.', 'alt': 'Bác mang giỏ quà về, bến bác cần đèn thì xin xí nghiệp lắp.'},
         back='Ông Năm Vựa xách giỏ quà về, lắc đầu: “Cậu này cứng thiệt.”',
         give='Bạn nhận giỏ quà. Tuần sau đoàn kiểm tra hỏi chuyện “quà của vựa cá”, tên bạn đứng đầu biên bản.'),
    _odd('hd-lonely-dm', 'charm', 'pax', '📱', 'Tin nhắn lạ lúc nửa đêm', 'Một số lạ · “người quen cũ”',
         '“Ở đảo một mình buồn không anh? Em chèo ghe ra ngồi với anh tới sáng nha, mang theo bia luôn 🍺”',
         ['“Ngồi chơi thôi mà, có làm gì đâu.”', '“Em ra tới bến rồi nè, mở cổng đi.”'],
         persist=(1, 3), mood=(0, 1), weight=1, words={'alt': 'Hẹn hôm vào bờ, ngồi quán cho đàng hoàng.'},
         back='Không có tiếng ghe nào nữa. Bạn ghi giờ quan trắc kế tiếp vào sổ.',
         give='Bạn mở cổng. Bia rượu tới khuya, sáng ra bạn ngủ quên giờ tắt đèn.'),
    # --- harassment
    _odd('hd-harass-radio', 'harass', 'pax', '🚨', 'Lời bẩn trên kênh 16', 'Một tàu cá giấu số hiệu',
         'Nửa đêm, một giọng say rượu chiếm kênh 16: “Trạm Hòn Gió có em gác đèn nào không? Ra đây anh chở đi chơi, đảo lạnh lắm hả em…”',
         ['Giọng đó cười hô hố, đọc đúng tên bạn trên bản tin.', '“Đêm nay anh ghé đảo nghe em.”'],
         persist=(2, 3), mood=(1, 2), weight=2,
         words={'stop': 'Kênh 16 là kênh cấp cứu. Dừng ngay.', 'no': 'Không. Tôi không đồng ý.', 'rule': 'Ghi giờ, báo đài và biên phòng.',
                'duty': 'Tôi đang trực.', 'joke': 'Cười trừ cho qua.', 'later': 'Thôi kệ.', 'yes': 'Trả lời cho hắn vui.'},
         back='Kênh 16 im bặt. Có lẽ ai đó trên tàu đã giật bộ đàm khỏi tay hắn.',
         report='Bạn ghi giờ, báo đài. Đài dò ra tàu, biên phòng mời chủ tàu lên làm việc. Chị Hải Yến: “Báo là đúng, em.”',
         stuck='Hắn chán rồi thôi. Không ai ghi lại gì, nên đêm sau hắn lại lên kênh. Không phải lỗi của bạn: báo là quyền của bạn.',
         give='Không ai phải “chiều” kẻ quấy rối. Hắn được đà nói tiếp, chiếm kênh cấp cứu nửa tiếng. Lần sau cứ báo đài.', follow='hd_radio_creep'),
    _odd('hd-harass-visitor', 'harass', 'pax', '😡', 'Ông khách sàm sỡ cô hướng dẫn viên', 'Ông khách say trên tàu du lịch',
         'Ở bến đá, một ông khách say cứ quàng vai cô Thắm, buông lời khiếm nhã: “Hướng dẫn viên xinh vầy, tối ở lại đảo với anh.”',
         ['Ông ta càng lấn tới, giữ tay cô Thắm không cho đi.', 'Cô Thắm nhìn sang bạn, mắt đỏ hoe.'],
         persist=(2, 3), mood=(1, 2), weight=2, npc=THAM,
         words={'stop': 'Quát: “Buông tay ra!”', 'no': 'Đứng chắn giữa hai người.', 'rule': 'Gọi đài báo biên phòng tới bến.', 'duty': 'Chuyện của đoàn, tôi đang trực.',
                'joke': 'Say mà, cười cho qua.', 'later': 'Để tàu về rồi tính.', 'yes': 'Chị chịu khó chiều ông ấy chút.'},
         back='Ông khách lủi xuống tàu, lầm bầm. Cô Thắm cảm ơn bạn, tay vẫn run.',
         report='Bạn gọi đài báo biên phòng. Tàu về tới bến, biên phòng lập biên bản ông khách; công ty du lịch cấm ông ta đi tour.',
         stuck='Ông ta quấy tới khi tàu nhổ neo. Không ai ghi lại, nên chuyến sau ông ta vẫn đi. Lần sau: báo luôn.',
         give='Không ai phải “chiều” kẻ quấy rối. Cô Thắm tự xoay xở, chạy vội xuống tàu, trượt chân trên bậc đá.'),
    _odd('hd-harass-boss', 'harass', 'boss', '🙅', 'Lời đùa “có ý” của anh Khôi', 'Anh Khôi · phó phòng kỹ thuật',
         'Giao ban qua bộ đàm, anh Khôi cười khẩy: “Ở đảo một mình chắc thèm hơi người lắm hả? Tối anh ra kiểm tra… riêng nhé.”',
         ['“Đùa tí mà căng thế. Anh ra thật đấy.”', '“Bọn trẻ bây giờ đùa tí cũng không biết.”'],
         persist=(1, 3), mood=(0, 2), weight=1, npc=KHOI,
         words={'stop': 'Anh dừng lại.', 'no': 'Tôi không đùa kiểu đó.', 'rule': 'Bộ đàm là kênh công việc, tôi sẽ báo công đoàn.', 'duty': 'Em đang trực.',
                'joke': 'Cười trừ.', 'later': 'Thôi bỏ qua.', 'yes': 'Ừ cho xong.'},
         back='Bộ đàm im một lúc. Anh Khôi chuyển sang hỏi sổ dầu, giọng nghiêm hẳn.',
         report='Bạn báo công đoàn xí nghiệp, kèm giờ và kênh. Anh Khôi bị kỷ luật khiển trách, phải xin lỗi bằng văn bản.',
         stuck='Anh Khôi cười cho qua. Chẳng ai ghi lại, nên tuần sau lại thế. Không phải lỗi của bạn; báo là quyền của bạn.',
         give='Bạn ậm ừ cho xong. Anh Khôi được đà nhắn tin riêng liên tục. Không phải lỗi của bạn; cứ báo, xí nghiệp có quy trình bảo vệ.'),
    _odd('hd-harass-fans', 'harass', 'pax', '📲', 'Fan của Vy Vlog kéo vào trang cá nhân', 'Đám fan ẩn danh',
         'Sau clip “anh gác đèn từ chối Vy”, hàng trăm tài khoản lạ nhắn tin chửi bới, đăng cả ảnh nhà má bạn.',
         ['Tin nhắn mới: “Biết nhà mày rồi đó.”', 'Có người gọi điện vào số của trạm, cười rồi cúp máy.'],
         persist=(2, 3), mood=(1, 2), weight=1,
         words={'stop': 'Khóa trang, chụp màn hình lại.', 'no': 'Không trả lời ai cả.', 'rule': 'Báo công an mạng, nhờ xí nghiệp lên tiếng.', 'duty': 'Tôi chỉ làm đúng nội quy.',
                'joke': 'Đăng clip cà khịa lại.', 'later': 'Kệ, vài bữa hết.', 'yes': 'Đăng bài xin lỗi Vy cho yên.'},
         back='Bạn khóa trang, chụp lại hết. Vài hôm sau đám fan cũng chán.',
         report='Bạn báo công an và xí nghiệp. Xí nghiệp đăng thông báo bảo vệ nhân viên làm đúng nội quy; Vy gỡ clip, xin lỗi công khai.',
         stuck='Đám fan chửi thêm mấy hôm. Không phải lỗi của bạn: báo công an và xí nghiệp là quyền của bạn.',
         give='Bạn xin lỗi vì một việc mình làm đúng. Đám fan càng hăng. Không phải lỗi của bạn; lần sau cứ báo.'),
    # --- odd demands from everyone around the light
    _odd('hd-nets', 'demand', 'pax', '🎣', '“Quay đèn về phía lưới giùm”', 'Ông Sáu Ghe · chủ tàu cá',
         '“Cậu quay cái đèn rọi về hướng đông bắc giùm tui, cá mực thấy sáng là lên đầy lưới. Có một đêm thôi!”',
         ['“Đèn của nhà nước, rọi chút có mất gì đâu.”', '“Hồi xưa ông trạm trưởng cũ còn cho mà!”'],
         persist=(1, 3), mood=(0, 2), weight=3, npc=SAU,
         words={'rule': 'Đèn quay đều theo danh mục đèn, tàu cả vịnh dựa vào nó.', 'alt': 'Ông dùng đèn câu trên tàu, đúng luật mà cá vẫn lên.'},
         back='Ông Sáu Ghe càu nhàu: “Ờ, thì thôi.” Rồi gọi hỏi bản tin gió đêm nay.',
         give='Bạn hứa “để xem”. Ông Sáu kể khắp bến là trạm sắp rọi đèn cho ông. Xí nghiệp gọi hỏi ngay chiều đó.', breach=3,
         review={'back': [4, 'Không chiều tui, nhưng nói có lý, còn chỉ cách.'], 'give': [2, 'Hứa rồi để đó. Nói cho vui à?']}),
    _odd('hd-horn-fish', 'demand', 'pax', '📯', '“Tắt còi đi, cá sợ chạy hết”', 'Tổ lưới chụp Cửa Lở',
         '“Đêm sương cậu kéo còi ầm ầm, cá chạy hết! Tắt còi giùm tụi tui một đêm thôi!”',
         ['“Tụi tui biết đường về, cần gì còi!”', '“Không tắt là tụi tui làm đơn lên xã đó!”'],
         persist=(1, 3), mood=(1, 2), weight=2,
         words={'rule': 'Sương mù là còi phải chạy, tàu lạ không biết đảo ở đâu.', 'alt': 'Các anh thả lưới cách đảo hai hải lý, tiếng còi nhỏ hẳn.'},
         back='Tổ lưới chụp lầm bầm rồi dời ra xa hơn. Đêm đó còi vẫn kêu đều.',
         give='Bạn tắt còi. Ba giờ sáng, một tàu hàng lạ suýt mắc cạn ở hòn Mõ trong sương.', breach=4),
    _odd('hd-day-light', 'demand', 'pax', '📸', '“Bật đèn ban ngày cho em chụp”', 'Đoàn khách tàu du lịch',
         '“Anh ơi bật cái đèn lên cho tụi em chụp ảnh đèn sáng đi, ban ngày nhìn không ra gì hết!”',
         ['“Năm phút thôi, có tốn bao nhiêu điện đâu.”', '“Tụi em trả tiền tour rồi mà anh!”'],
         persist=(1, 2), mood=(0, 1), weight=2, npc=THAM,
         words={'rule': 'Đèn chỉ bật theo giờ, bật bậy tàu ngoài khơi tưởng tín hiệu.', 'alt': 'Chiều nay tàu Biển Ngọc có tour hoàng hôn, xem đèn thắp thật luôn.'},
         back='Đoàn khách tiếc rẻ nhưng chụp tấm hình cái tháp trắng dưới nắng. Cô Thắm ghi luôn tour hoàng hôn.',
         give='Bạn bật đèn giữa trưa. Đài gọi hỏi sao đèn Hòn Gió sáng lúc mười hai giờ.', breach=3),
    _odd('hd-marriage', 'demand', 'kin', '💒', '“Về quê xem mặt đi con!”', 'Má bạn',
         '“Má hẹn nhà bác Tư rồi, chủ nhật này con về xem mặt con gái/con trai bác. Đèn đóm gì một hôm, nhờ ông trạm trưởng trực giùm!”',
         ['“Con ở đảo hoài, ai mà chịu lấy?”', '“Má già rồi, má muốn bồng cháu…”'],
         persist=(1, 3), mood=(0, 2), weight=3,
         words={'rule': 'Ca trực có lịch, con không bỏ trạm được má ơi.', 'alt': 'Đợt nghỉ phép tháng sau con về, má hẹn lại giùm con nha.'},
         back='Má thở dài: “Ừ, tháng sau về đó nha.” Rồi gửi theo tàu một hũ mắm.',
         give='Bạn bỏ trạm về quê một ngày. Chú Bảy trực một mình ba mươi sáu tiếng, ngã ở cầu thang tháp.', breach=3),
    _odd('hd-cousin-money', 'demand', 'kin', '💸', 'Cô Út hỏi mượn tiền', 'Cô Út',
         '“Con ở đảo đâu có tiêu gì, lương dư nhiều lắm phải không? Cho cô mượn hai trăm sửa nhà, Tết cô trả.”',
         ['“Cô nuôi con hồi nhỏ mà…”', '“Không cho mượn thì nói luôn đi!”'],
         persist=(1, 3), mood=(0, 2), weight=2,
         words={'rule': 'Lương con còn lo cho má với tiền học em, con không dư nhiều vậy.', 'alt': 'Con gửi cô ít tiền mua vật liệu, còn lại cô hỏi thêm mấy anh chị nha.'},
         back='Cô Út im một lúc rồi bảo: “Ừ, thôi cô hỏi chỗ khác.”',
         give='Bạn chuyển hai trăm. Tết năm đó cô Út không nhắc gì tới chuyện trả.', fx={'give': {'money': -30}}),
    _odd('hd-boss-paint', 'demand', 'boss', '🎨', '“Sơn tháp màu hồng cho clip quảng bá”', 'Anh Khôi · phó phòng kỹ thuật',
         '“Tỉnh làm clip du lịch. Cậu sơn giùm cái ban công màu hồng pastel cho lên hình đẹp. Tự mua sơn, về xí nghiệp thanh toán sau.”',
         ['“Có cái ban công thôi mà, làm trong một buổi.”', '“Lãnh đạo tỉnh thích màu hồng, cậu hiểu chưa?”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=KHOI,
         words={'rule': 'Màu tháp là dấu hiệu nhận biết ban ngày trong danh mục đèn, không tự đổi được.', 'alt': 'Em gửi anh ảnh tháp lúc hoàng hôn, lên clip đẹp mà đúng màu.'},
         back='Anh Khôi im một lúc: “Ừ… gửi ảnh hoàng hôn đi.” Clip du lịch dùng ảnh của bạn.',
         give='Bạn sơn hồng ban công. Tháng sau Cục hàng hải gửi công văn hỏi vì sao dấu hiệu ban ngày của đèn Hòn Gió bị đổi.', breach=3),
    _odd('hd-boss-seagull', 'demand', 'boss', '🕊️', '“Đếm hải âu báo cáo hằng ngày”', 'Anh Khôi · phó phòng kỹ thuật',
         '“Xí nghiệp có đề tài môi trường. Từ mai cậu đếm hải âu trên đảo, sáng trưa chiều, gửi báo cáo kèm ảnh từng con.”',
         ['“Có đếm thôi mà, cậu rảnh mà.”', '“Không làm thì cuối năm khỏi thi đua.”'],
         persist=(1, 3), mood=(0, 1), weight=2, npc=KHOI,
         words={'rule': 'Em ưu tiên quan trắc và đèn trước, việc thêm cần văn bản giao.', 'alt': 'Em đếm một lần buổi sáng, ghi chung vào sổ quan trắc nhé.', 'why': 'Đề tài cần số liệu gì ạ?'},
         back='Anh Khôi lầm bầm: “Ừ, một lần sáng là được.” Sổ quan trắc có thêm cột “hải âu”.',
         give='Bạn đếm hải âu cả ngày, trễ giờ quan trắc trưa. Đài gọi hỏi bản tin ba lần.', breach=1),
    _odd('hd-boss-report', 'demand', 'boss', '📞', '“Báo cáo thời tiết mỗi nửa tiếng”', 'Anh Khôi · phó phòng kỹ thuật',
         '“Mùa bão rồi. Từ giờ cậu gọi tôi báo thời tiết mỗi nửa tiếng, cả đêm, gọi số riêng của tôi.”',
         ['“Gọi có mấy giây thôi mà.”', '“Tôi là sếp, tôi cần biết.”'],
         persist=(1, 3), mood=(0, 2), weight=1, npc=KHOI,
         words={'rule': 'Quan trắc theo giờ quy định gửi đài, đài phát cho mọi người.', 'alt': 'Có gì bất thường em gọi anh ngay, còn lại anh nghe bản tin của đài nhé.'},
         back='Anh Khôi hừ một tiếng: “Bất thường thì gọi ngay đấy.” Rồi cúp máy.',
         give='Bạn gọi anh Khôi suốt đêm. Gần sáng gục trên bàn trực, quên ghi giờ quan trắc năm giờ.', breach=1),
    _odd('hd-writer-stay', 'demand', 'pax', '✍️', 'Nhà văn xin ở lại thêm', 'Anh Đức · nhà văn',
         '“Cho tôi ở thêm năm ngày thôi. Tôi cần cảm nhận cái cô đơn thật sự của đêm thứ bảy trên đảo…”',
         ['“Tôi ngủ nhà kho cũng được, tự nấu ăn.”', '“Tác phẩm này sẽ làm người ta hiểu nghề của các anh hơn mà.”'],
         persist=(1, 3), mood=(0, 1), weight=2, npc=DUC,
         words={'rule': 'Giấy của xí nghiệp chỉ cho tham quan trong ngày.', 'alt': 'Anh xin xí nghiệp giấy ở lại, hoặc em kể anh nghe qua điện thoại mỗi tối.'},
         back='Anh Đức gật đầu, xuống tàu chiều. Tối đó anh gọi điện hỏi chuyện đèn tới khuya.',
         give='Bạn cho anh Đức ở lại. Đêm thứ ba anh lên phòng đèn hút thuốc “tìm cảm hứng”.', breach=3),
    _odd('hd-ghost-off', 'demand', 'pax', '👻', 'Kênh ma xin tắt đèn mười phút', 'Kênh YouTube “Đêm Rợn Người”',
         '“Anh tắt đèn mười phút thôi, tụi em quay cảnh “đèn tự tắt”, sau đó bật lại liền! View triệu đó anh!”',
         ['“Giờ này làm gì có tàu nào, anh lo xa quá!”', '“Tụi em chia anh nửa tiền quảng cáo!”'],
         persist=(1, 3), mood=(0, 2), weight=2,
         words={'rule': 'Đèn biển không được tắt dù một phút.', 'alt': 'Các bạn quay cảnh đèn quét trong sương, rợn hơn nhiều.'},
         back='Nhóm làm phim quay cảnh đèn quét trong sương. Clip “ánh sáng ma quái” vẫn hút view.',
         give='Bạn tắt đèn. Đúng mười phút đó một tàu hàng gọi đài hỏi đèn Hòn Gió đâu rồi.', breach=4),
    _odd('hd-village-fest', 'demand', 'boss', '🏮', 'Làng xin làm lễ trên mỏm đá lúc nửa đêm', 'Ông trưởng thôn Cửa Lở',
         '“Rằm này làng làm lễ cầu ngư trên mỏm đá cạnh trạm. Cậu mở cổng trạm cho bà con đi qua, tắt đèn pha sân cho linh thiêng.”',
         ['“Xã đồng ý miệng rồi.”', '“Cả làng có một đêm, cậu khó gì thế.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Nửa đêm đông người qua sân trạm trên đá là không an toàn.', 'alt': 'Làng làm lễ lúc chiều, có giấy của xí nghiệp, em mở lối và đi kèm.'},
         back='Ông trưởng thôn gật gù dời lễ sang buổi chiều. Bà con còn để lại cho trạm mâm xôi gà.',
         give='Bạn mở cổng lúc nửa đêm. Một cụ bà trượt chân trên đá rêu, phải gọi ghe đưa vào bờ gấp.', breach=3),
    _odd('hd-fridge', 'demand', 'pax', '🧊', 'Gửi cá trong tủ đông của trạm', 'Ông Sáu Ghe · chủ tàu cá',
         '“Cho tui gửi hai thùng cá trong tủ đông của trạm vài hôm, máy tàu tui hư. Chạy máy phát thêm chút có sao!”',
         ['“Dầu của nhà nước mà, có mất của cậu đâu.”', '“Cá ươn hết là tui lỗ cả tháng.”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=SAU,
         words={'rule': 'Dầu máy phát là dầu giữ đèn, sổ dầu phải khớp.', 'alt': 'Ông nhờ tàu tiếp tế chở cá vào bờ, em gọi chú Tư Lực giùm.'},
         back='Ông Sáu Ghe gọi chú Tư Lực chở cá vào bờ. Mất ít tiền xăng nhưng cá còn tươi.',
         give='Bạn cho gửi cá, chạy máy phát thêm bốn tiếng mỗi ngày. Cuối tuần sổ dầu hụt ba mươi lít.', breach=2),
    _odd('hd-statue', 'demand', 'pax', '🗿', 'Đặt tượng Phật trên đỉnh tháp', 'Bà Hai · hội thiện nguyện',
         '“Hội tụi bà cúng một pho tượng nhỏ, muốn đặt trên ban công đỉnh tháp cho tàu thuyền nhìn thấy mà bình an.”',
         ['“Có linh thiêng lắm con, đặt đi cho cả vịnh nhờ.”', '“Con không đặt là con mang tội đó.”'],
         persist=(1, 3), mood=(0, 1), weight=1,
         words={'rule': 'Ban công đèn không được đặt vật che ánh sáng.', 'alt': 'Mình đặt tượng ở miếu Bà cạnh trạm, ai đi biển cũng ghé được.'},
         back='Bà Hai gật đầu, đặt tượng ở miếu Bà. Từ đó ngày rằm miếu đông hơn.',
         give='Bạn đặt tượng trên ban công. Một vệt tối chạy qua tia sáng mỗi vòng quét.', breach=3),
    _odd('hd-supply-ride', 'demand', 'pax', '⛴️', 'Xin quá giang tàu tiếp tế', 'Anh Hùng · thợ lặn tự do',
         '“Cho anh quá giang tàu tiếp tế ra mấy bãi đá ngầm lặn bắt tôm hùm, rồi ghé đảo ngủ nhờ một đêm.”',
         ['“Đi chung một chuyến, tốn gì đâu.”', '“Anh biếu trạm hai con tôm hùm.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         words={'rule': 'Tàu tiếp tế không chở khách, trạm không cho ngủ nhờ.', 'alt': 'Anh thuê ghe ở bến Cửa Lở, có người đi kèm cho an toàn.'},
         back='Anh Hùng gật gù thuê ghe ở bến. Chú Tư Lực thở phào.',
         give='Bạn xin chú Tư Lực cho anh Hùng đi nhờ. Anh lặn quá giờ, cả tàu chờ hai tiếng giữa sóng.', breach=2),
    # --- corners cut (reported without blame)
    _odd('hd-sign-full', 'corner', 'crew', '✍️', '“Ký đủ hai trăm lít đi”', 'Chú Tư Lực · thuyền trưởng tàu tiếp tế',
         '“Bồn thiếu có chút đỉnh, ký đủ hai trăm lít cho chú. Chuyến sau chú bù, ai mà kiểm.”',
         ['“Xí nghiệp có ai đo đâu con.”', '“Con làm khó chú, chuyến sau chú chở rau héo cho coi.”'],
         persist=(1, 3), mood=(0, 2), weight=3, npc=LUC,
         words={'speak': 'Ký đúng số đo được.', 'alt': 'Ghi đúng số đo, thêm ghi chú “còn thiếu, chuyến sau bù”.'},
         back='Chú Tư Lực lầm bầm, ghi thêm dòng “giao thiếu, chuyến sau bù”. Hai bên cùng ký.',
         give='Bạn ký đủ hai trăm lít. Cuối tháng sổ dầu của trạm hụt, người ký là bạn.', severe=3),
    _odd('hd-skip-obs', 'corner', 'crew', '🌧️', '“Mưa vầy khỏi lên quan trắc”', 'Anh Lâm · người trực ca phụ',
         '“Mưa to thế này lên đài quan trắc làm gì, ướt hết. Báo đài số liệu như hôm qua, có ai kiểm đâu.”',
         ['“Gió cũng vậy vậy thôi mà.”', '“Em đi một mình thì đi, anh không đi.”'],
         persist=(1, 2), mood=(0, 1), weight=2,
         back='Anh Lâm càu nhàu, mặc áo mưa lên cùng. Áp kế tụt bốn hPa, khác hẳn hôm qua.',
         give='Bạn báo số liệu cũ. Chiều đó gió giật cấp 7, đài phát cảnh báo trễ hai tiếng.', severe=3),
    _odd('hd-log-ok', 'corner', 'boss', '📝', '“Ghi đèn sáng bình thường”', 'Anh Khôi · phó phòng kỹ thuật',
         '“Đêm qua đèn tắt hai mươi phút thì ghi “bình thường” nhé. Ghi ra là lên tới Cục, rắc rối lắm.”',
         ['“Có hai mươi phút, tàu nào thấy đâu.”', '“Anh nói thế mà em không nghe à?”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=KHOI,
         words={'alt': 'Em ghi đúng giờ tắt, ghi rõ nguyên nhân và cách đã xử lý.'},
         back='Anh Khôi im một lúc: “Ừ. Ghi nguyên nhân vào.” Báo cáo lên Cục có đủ lý do, không ai bị kỷ luật.',
         give='Bạn ghi “bình thường”. Tháng sau một tàu hàng gửi phản ánh đèn tắt đúng đêm đó. Sổ trực vênh.', severe=3),
    _odd('hd-lens-motor', 'corner', 'crew', '⚙️', '“Lau kính khỏi tắt mô-tơ”', 'Anh Tấn · thợ máy xí nghiệp',
         '“Lau kính thì cứ để mô-tơ quay, tắt đi bật lại mất công. Né né cái là được.”',
         ['“Anh làm hai chục năm có sao đâu.”', '“Tắt mô-tơ thì phải ghi sổ, rườm rà.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         back='Anh Tấn chép miệng, tắt mô-tơ, treo biển “Đang lau kính, cấm bật”. Lau xong mới bật lại.',
         give='Bạn lau khi mô-tơ đang quay. Bệ đèn xoay kẹp vạt áo, suýt kéo tay bạn vào khe.', severe=3),
    _odd('hd-gen-door', 'corner', 'crew', '🚪', '“Chạy máy phát đóng cửa cho đỡ ồn”', 'Anh Lâm · người trực ca phụ',
         '“Đóng cửa nhà máy phát lại cho đỡ ồn, khói nó tự thoát ra ống mà.”',
         ['“Ồn quá anh không ngủ được.”', '“Có sao đâu, mấy năm nay vẫn vậy.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         back='Anh Lâm lầm bầm, đeo nút tai đi ngủ. Cửa nhà máy phát mở thông gió như quy định.',
         give='Bạn đóng cửa. Nửa đêm anh Lâm vào kiểm máy, chóng mặt buồn nôn vì khói, phải dìu ra ngoài.', severe=3),
    _odd('hd-buoy-skip', 'corner', 'crew', '🛟', '“Phao cứu sinh hết hạn kệ đi”', 'Anh Lâm · người trực ca phụ',
         '“Phao cứu sinh ở bến hết hạn kiểm định từ năm ngoái. Ghi “đạt” đi, xin phao mới lâu lắm.”',
         ['“Phao vẫn nổi mà.”', '“Ghi hết hạn là xí nghiệp hỏi tới.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         back='Anh Lâm thở dài, ghi phiếu xin phao mới. Chuyến tàu sau có hai chiếc phao mới tinh.',
         give='Bạn ghi “đạt”. Tháng sau ném phao cứu người, dây phao mục đứt ngay khúc giữa.', severe=3),
    _odd('hd-cousin-tower', 'corner', 'kin', '🏠', 'Em họ xin lên phòng đèn chơi', 'Thằng Bin · em họ bạn',
         '“Anh ơi cho em lên phòng đèn quay TikTok, em không đụng gì đâu! Em ra tận đây mà!”',
         ['“Em quay có mười giây thôi.”', '“Mẹ em bảo anh chiều em mà.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         words={'speak': 'Phòng đèn không phải chỗ chơi.', 'rule': 'Người ngoài không được vào phòng đèn.', 'alt': 'Em quay ở sân trạm, anh kể chuyện đèn cho nghe.'},
         back='Thằng Bin phụng phịu quay ở sân trạm. Clip “anh tui gác đèn” được cả lớp thả tim.',
         give='Bạn cho lên. Thằng Bin táy máy chạm tay vào kính đèn, để lại năm dấu tay mỡ.', severe=2),
    # --- bargains with the company and the family
    _odd('hd-extend', 'bargain', 'boss', '🏝️', 'Ở đảo thêm ba tuần', 'Anh Khôi · phó phòng kỹ thuật',
         '“Người thay ca bị ốm. Cậu ở đảo thêm ba tuần nữa nhé, cuối năm xét thưởng.”',
         ['“Cả xí nghiệp đang khó, cậu chịu khó chút.”', '“Không nhận thì khó xét thưởng đó.”'],
         ask=3, limit=1, unit='tuần', pay=8, tire=2, cost=10, weight=3, npc=KHOI,
         lawful='Anh Khôi hậm hực nhưng đành tìm người thay: luật giờ nghỉ đứng về phía bạn.'),
    _odd('hd-tet-duty', 'bargain', 'boss', '🧧', 'Trực xuyên Tết', 'Trưởng phòng kỹ thuật',
         '“Tết này cậu trực liền năm ngày nhé, người khác về quê hết rồi.”',
         ['“Tết nào chả thế, ráng đi em.”', '“Có ai được nghỉ đâu.”'],
         ask=5, limit=2, unit='ngày trực', pay=7, tire=2, cost=12, weight=2),
    _odd('hd-cover-bay', 'bargain', 'crew', '🔁', 'Trực thay chú Bảy', 'Chú Bảy Đèn',
         '“Chú về đất liền khám mắt hai hôm. Con trực thay chú hai ca đêm nhé?”',
         ['“Mắt chú mờ lắm rồi con.”', '“Chú nhờ mỗi con thôi.”'],
         ask=2, limit=2, unit='ca đêm', pay=6, tire=1, cost=0, weight=2, npc=BAY,
         deal='Chú Bảy: “Ừ, {n} {unit} thôi cũng được, chú cảm ơn con.”', penalty='Chú Bảy cười buồn: “Thôi để chú nhờ xí nghiệp cử người.”'),
    _odd('hd-paint-weekend', 'bargain', 'boss', '🖌️', 'Sơn lại tháp cuối tuần', 'Anh Khôi · phó phòng kỹ thuật',
         '“Tháp tróc sơn rồi. Cậu tranh thủ bốn ngày nghỉ sơn lại giùm, xí nghiệp trả công thêm.”',
         ['“Sơn thôi mà, có gì khó.”', '“Ai cũng phải gánh thêm việc.”'],
         ask=4, limit=2, unit='ngày nghỉ', pay=5, tire=1, cost=10, weight=2, npc=KHOI),
    _odd('hd-mom-money', 'bargain', 'kin', '💰', 'Má xin gửi lương về sớm', 'Má bạn',
         '“Nhà mình đang cần tiền sửa mái. Con gửi về trước ba tháng lương được không con?”',
         ['“Má biết con cực, mà nhà đang khó.”', '“Mái dột rồi con ơi.”'],
         ask=3, limit=1, unit='tháng lương', pay=-10, tire=0, cost=0, weight=1,
         deal='Má bạn: “Ừ, {n} {unit} cũng đỡ lắm rồi. Con giữ sức khỏe nha.”', lawful='Má nghe con giải thích, thở dài: “Ừ, gửi được bao nhiêu thì gửi.”',
         penalty='Má buồn, cúp máy ngang. Tối đó má nhắn: “Thôi, má tự lo.”', give='Bạn gửi hết {n} {unit}. Má mừng rơi nước mắt, còn bạn ăn mì gói tới cuối tháng.'),
]

# ================================================================ situations (sit_ engine)
SITUATIONS = [
    dict(id='HD-S01', title='Cầu hôn trên đỉnh tháp lúc nửa đêm', npc=BAY, tone='gentle', min_day=1,
         opening='Mười một giờ đêm. Một cặp đôi gõ cửa trạm, chàng trai chìa hộp nhẫn: “Anh cho em lên ban công đèn mười phút thôi, cả đời có một lần!”',
         swap='Bạn là chàng trai: bạn lên kế hoạch cả năm, ghe đã về bờ, cô ấy đang đứng sau lưng.',
         facts=[dict(id='rule', title='Nội quy trạm', source='Bảng nội quy', text='Người ngoài không vào phòng đèn, không lên tháp ban đêm.'),
                dict(id='glare', title='Phòng đèn', source='Chú Bảy', text='Đứng trên ban công lúc đèn quét là che mất tia sáng, lại dễ trượt ngã vì sương.'),
                dict(id='boat', title='Chuyến ghe', source='Chàng trai', text='Ghe hẹn hai giờ sáng mới quay lại đón.')],
         options=[dict(id='yard', label='Chúc mừng, mời hai bạn ra sân trạm, đứng đúng chỗ ánh đèn quét qua đầu, cho ngồi nhà trạm chờ ghe', requires=['rule', 'glare'],
                       quality='good', stars=5, review='Anh gác đèn không cho lên tháp nhưng chỉ chỗ đẹp nhất sân trạm. Cô ấy nói đồng ý!',
                       outcome='Dưới vệt sáng quét qua đầu, cô gái gật đầu. Hai bạn ngồi nhà trạm uống trà chờ ghe.',
                       perspectives=[dict(who='Chàng trai', emoji='💍', text='Không lên được đỉnh tháp, mà ảnh sân trạm còn đẹp hơn.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Mình giữ đèn, nhưng không phải để làm người ta buồn.')]),
                  dict(id='up', label='Cho lên mười phút, mình đứng canh', quality='bad', stars=2,
                       review='Cho người lạ lên ban công đèn lúc nửa đêm, cô gái suýt trượt chân vì sương.', outcome='Cô gái trượt chân trên sàn ban công ướt sương, may chàng trai đỡ kịp.',
                       perspectives=[dict(who='Chú Bảy', emoji='😠', text='Lỡ có chuyện thì ai chịu?'),
                                     dict(who='Cô gái', emoji='😨', text='Em sợ muốn khóc, quên cả nhận nhẫn.')]),
                  dict(id='no', label='“Không là không”, đóng cửa', requires=['rule'], quality='ok', stars=3,
                       review='Đúng nội quy, nhưng để hai bạn đứng ngoài bến lạnh tới hai giờ sáng.', outcome='Hai bạn ngồi co ro ở bến đá chờ ghe.',
                       perspectives=[dict(who='Chàng trai', emoji='😔', text='Ít ra cũng chúc tụi em một câu.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Giữ nội quy bằng tay, nói chuyện bằng lòng.')])],
         lesson='Nội quy giữ đèn và giữ người; từ chối được mà vẫn tử tế.'),
    dict(id='HD-S02', title='Quay đèn về phía lưới', npc=SAU, tone='gentle', min_day=1,
         opening='Ông Sáu Ghe gọi kênh 16: “Cậu quay đèn rọi về đông bắc giùm tui một đêm, mực đang lên!”',
         swap='Bạn là ông Sáu: cả tháng biển động, tàu nằm bờ, nợ tiền dầu chưa trả.',
         facts=[dict(id='list', title='Danh mục đèn', source='Sổ tay trạm', text='Đèn Hòn Gió: chớp nhóm 3 trắng, 15 giây, quay đều. Tàu cả vịnh nhận đèn bằng đặc tính này.'),
                dict(id='light', title='Đèn câu', source='Ông Sáu', text='Tàu ông có dàn đèn câu mực riêng.'),
                dict(id='storm', title='Bản tin', source='Đài', text='Đêm nay biển êm, gió cấp 3.')],
         options=[dict(id='explain', label='Giải thích đèn quay đều theo danh mục, gợi ý dùng đèn câu, đọc bản tin đêm nay cho ông', requires=['list', 'light'],
                       quality='good', stars=5, review='Cậu gác đèn không chiều, mà nói có lý, còn đọc bản tin cho tui.',
                       outcome='Ông Sáu bật dàn đèn câu, mực vẫn lên. Gần sáng ông gọi cảm ơn bản tin.',
                       perspectives=[dict(who='Ông Sáu', emoji='🎣', text='Đèn câu tui có sẵn, quên mất.'),
                                     dict(who='Thuyền trưởng tàu hàng', emoji='🚢', text='Đêm đó tôi nhận ra Hòn Gió từ hai mươi hải lý. Cảm ơn.')]),
                  dict(id='bend', label='Dừng mô-tơ, rọi về đông bắc một tiếng', quality='bad', stars=1,
                       review='Đèn đứng yên một tiếng, tàu hàng gọi đài hỏi đèn gì lạ.', outcome='Một tàu hàng nhận nhầm đèn, lệch luồng. Đài gọi trạm hỏi dồn dập.',
                       perspectives=[dict(who='Chị Hải Yến', emoji='📻', text='Đèn sai đặc tính là tàu nhận nhầm đèn.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Một tiếng đó có thể là một con tàu.')]),
                  dict(id='hang', label='Tắt bộ đàm, không trả lời', requires=['storm'], quality='ok', stars=3,
                       review='Không chiều, nhưng gọi mà không trả lời, mất lòng bà con.', outcome='Ông Sáu kể khắp bến là trạm “làm quan”.',
                       perspectives=[dict(who='Ông Sáu', emoji='😤', text='Gọi mà không thèm trả lời.'),
                                     dict(who='Chị Hải Yến', emoji='📻', text='Kênh 16 thì phải trực nghe, em ạ.')])],
         lesson='Đèn biển là của mọi con tàu; từ chối kèm lý do và một cách khác.'),
    dict(id='HD-S03', title='Pháo hiệu đỏ giữa đêm bão', npc=YEN, tone='tense', min_day=2,
         opening='Gió cấp 7. Một pháo hiệu đỏ vọt lên phía đông nam. Xuồng của trạm nằm ngay dưới bến.',
         facts=[dict(id='flare', title='Pháo hiệu đỏ', source='Sổ tay trạm', text='Pháo hiệu đỏ là tín hiệu cấp cứu: có người gặp nguy hiểm tính mạng.'),
                dict(id='boat', title='Xuồng của trạm', source='Chú Bảy', text='Xuồng nhỏ chỉ dùng ven bờ lúc biển êm.'),
                dict(id='relay', title='Báo đài', source='Nội quy', text='Thấy tín hiệu cấp cứu: báo đài MAYDAY RELAY, phương vị, khoảng cách, số người; canh giữ mục tiêu.')],
         options=[dict(id='relay', label='Báo đài MAYDAY RELAY, đọc phương vị, khoảng cách, số người, rồi canh giữ mục tiêu suốt đêm', requires=['flare', 'relay'],
                       quality='good', stars=5, review='Trạm Hòn Gió báo rõ, canh sát mục tiêu. Tàu cứu nạn tìm thấy tàu cá trong bốn mươi phút.',
                       outcome='Tàu cứu nạn theo phương vị của bạn, vớt được sáu ngư dân.',
                       perspectives=[dict(who='Chị Hải Yến', emoji='📻', text='Phương vị, khoảng cách, số người: đủ, đài điều tàu được ngay.'),
                                     dict(who='Ngư dân được cứu', emoji='🙏', text='Thấy đèn pha trạm rọi theo, tụi tui biết có người đang canh.')]),
                  dict(id='boat', label='Lấy xuồng của trạm ra cứu cho nhanh', quality='bad', stars=1,
                       review='Một mình ra khơi bằng xuồng giữa bão, thành người thứ hai cần cứu.', outcome='Xuồng lật ngay cửa bến. Chú Bảy phải ném phao kéo bạn vào.',
                       perspectives=[dict(who='Chú Bảy', emoji='😠', text='Cứu người mà mất thêm người thì cứu ai?'),
                                     dict(who='Chị Hải Yến', emoji='📻', text='Đài mất mười phút vì trạm không ai trực máy.')]),
                  dict(id='wait', label='Chờ xem có pháo hiệu thứ hai cho chắc', requires=['boat'], quality='bad', stars=2,
                       review='Thấy pháo hiệu đỏ mà chờ thêm mới báo.', outcome='Mười lăm phút sau mới báo đài. Tàu cứu nạn tìm mãi mới thấy.',
                       perspectives=[dict(who='Chị Hải Yến', emoji='😟', text='Một pháo hiệu là đủ để báo.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Ngoài đó từng phút là từng người.')])],
         lesson='Thấy tín hiệu cấp cứu: báo đài ngay, đúng mức khẩn cấp, đủ thông tin, canh giữ mục tiêu; không tự ra khơi.'),
    dict(id='HD-S04', title='Chú Tư Lực đòi ký đủ hai trăm lít', npc=LUC, tone='tense', min_day=2,
         opening='Đo bồn trước và sau khi bơm: chỉ vào 170 lít. Chú Tư Lực chìa phiếu ghi 200: “Ký đi con, chuyến sau chú bù.”',
         facts=[dict(id='dip', title='Thước đo bồn', source='Bạn đo', text='Trước bơm 412 lít, sau bơm 582 lít: vào 170 lít.'),
                dict(id='log', title='Sổ dầu', source='Nội quy', text='Sổ dầu ghi đúng số đo, người ký chịu trách nhiệm.'),
                dict(id='rice', title='Chuyện cũ', source='Chú Bảy', text='Chú Tư Lực từng dọa chở rau héo nếu bị làm khó.')],
         options=[dict(id='true', label='Ký đúng 170 lít, ghi chú “giao thiếu 30 lít”, mời chú Tư cùng ký', requires=['dip', 'log'],
                       quality='good', stars=5, review='Cậu gác đèn ký đúng số, có ghi chú rõ ràng. Không ai phải giấu gì.',
                       outcome='Chú Tư Lực càu nhàu nhưng ký. Chuyến sau chú chở đủ, còn bù thêm can nhớt.',
                       perspectives=[dict(who='Chú Tư Lực', emoji='⛴️', text='Thằng này cứng. Mà ký đúng thì chú cũng đỡ bị hỏi.'),
                                     dict(who='Anh Khôi', emoji='📋', text='Sổ dầu khớp bồn từng lít. Kiểm là thấy.')]),
                  dict(id='full', label='Ký đủ 200 cho êm chuyện', quality='bad', stars=1,
                       review='Ký nhận 200 lít mà bồn chỉ vào 170.', outcome='Cuối tháng sổ dầu hụt 30 lít, người ký là bạn.',
                       perspectives=[dict(who='Anh Khôi', emoji='📋', text='Ba mươi lít đi đâu, cậu giải trình đi.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Chữ ký của mình là lời của mình.')]),
                  dict(id='refuse', label='Không ký gì cả, đuổi tàu đi', requires=['rice'], quality='ok', stars=3,
                       review='Không ký sai, nhưng cũng không có giấy tờ gì, trạm thiếu dầu tới chuyến sau.', outcome='Tàu đi, bồn có thêm 170 lít mà không giấy nào ghi lại.',
                       perspectives=[dict(who='Chú Tư Lực', emoji='😤', text='Không ký thì thôi, chú về báo xí nghiệp.'),
                                     dict(who='Anh Khôi', emoji='📋', text='Có giao mà không có phiếu, khó cho cả hai.')])],
         lesson='Ký đúng số đo được, ghi rõ phần thiếu; chữ ký là trách nhiệm.'),
    dict(id='HD-S05', title='Nhà văn xin ở lại một tuần', npc=DUC, tone='gentle', min_day=2,
         opening='Anh Đức có giấy tham quan trong ngày. Chiều rồi, anh xin: “Cho tôi ở lại một tuần thôi, tôi cần sống thử.”',
         facts=[dict(id='paper', title='Giấy của xí nghiệp', source='Anh Đức', text='Giấy ghi: tham quan, phỏng vấn trong ngày.'),
                dict(id='boat', title='Chuyến tàu', source='Cô Thắm', text='Tàu Biển Ngọc còn chuyến năm giờ chiều.'),
                dict(id='rule', title='Nội quy trạm', source='Bảng nội quy', text='Không cho ở lại qua đêm, trừ người gặp nạn.')],
         options=[dict(id='day', label='Dẫn anh Đức đi hết trạm, kể chuyện nghề tới chiều, tiễn lên tàu năm giờ, hẹn gọi điện kể thêm', requires=['paper', 'rule'],
                       quality='good', stars=5, review='Cậu gác đèn kể chuyện cả buổi, tiễn tôi lên tàu, tối còn gọi điện kể tiếp. Đủ cho cả cuốn sách.',
                       outcome='Anh Đức về bờ với cả xấp ghi chép. Cuốn sách sau này có cả chuyện mèo Mun.',
                       perspectives=[dict(who='Anh Đức', emoji='✍️', text='Tôi tưởng phải ở mới hiểu. Hóa ra phải nghe mới hiểu.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Khách thương thì kể cho đủ, rồi tiễn cho đúng giờ.')]),
                  dict(id='stay', label='Cho ở lại, nhà kho còn chỗ', quality='bad', stars=2,
                       review='Cho người ngoài ở lại đảo trái nội quy.', outcome='Đêm thứ hai anh Đức lên phòng đèn hút thuốc, để mở cửa ban công.',
                       perspectives=[dict(who='Anh Khôi', emoji='📋', text='Ai cho phép?'),
                                     dict(who='Anh Đức', emoji='😳', text='Tôi không biết phòng đèn cấm lửa.')]),
                  dict(id='rush', label='Hết giờ thăm, mời anh xuống tàu ngay', requires=['boat'], quality='ok', stars=3,
                       review='Đúng giờ, nhưng chưa kể được gì đã mời về.', outcome='Anh Đức xuống tàu, cuốn sổ ghi chép còn trống trơn.',
                       perspectives=[dict(who='Anh Đức', emoji='😔', text='Tôi đi cả buổi mà chưa nghe được câu chuyện nào.'),
                                     dict(who='Cô Thắm', emoji='🚤', text='Tàu còn chờ được nửa tiếng mà.')])],
         lesson='Giấy cho tham quan trong ngày thì đón cho chu đáo và tiễn đúng giờ; không ai ở lại trái nội quy.'),
    dict(id='HD-S06', title='Tàu cá bỏ ngoài tai cảnh báo', npc=SAU, tone='tense', min_day=3,
         opening='Đài vừa phát tin áp thấp. Tàu ông Sáu Ghe vẫn nổ máy rời bến, mũi hướng ra khơi.',
         swap='Bạn là ông Sáu: cá đang lên, nợ dầu chưa trả, bản tin năm nào chả dọa.',
         facts=[dict(id='bulletin', title='Bản tin', source='Đài', text='Áp thấp cách bờ 150 km, gió giật cấp 8, sóng cao 3–4 mét đêm nay.'),
                dict(id='border', title='Lệnh cấm', source='Đồn biên phòng', text='Có lệnh cấm tàu thuyền ra khơi từ trưa nay.'),
                dict(id='family', title='Gia đình', source='Bến Cửa Lở', text='Con trai ông Sáu mười sáu tuổi đi theo tàu chuyến này.')],
         options=[dict(id='warn', label='Gọi kênh 16 đọc bản tin, khuyên vào âu tránh trú; ông không nghe thì báo đồn biên phòng qua đài', requires=['bulletin', 'border'],
                       quality='good', stars=5, review='Cậu gọi tui hai lần, rồi báo biên phòng. Lúc đó tui giận, giờ thì cảm ơn.',
                       outcome='Tàu biên phòng chặn ở cửa luồng. Đêm đó gió giật cấp 8, cả bến bình an.',
                       perspectives=[dict(who='Ông Sáu', emoji='🎣', text='Tui giận cả tuần. Rồi nghe tin tàu bên Hòn Đỏ mất tích, tui không giận nữa.'),
                                     dict(who='Con trai ông Sáu', emoji='👦', text='Con sợ lắm mà không dám nói với ba.')]),
                  dict(id='leave', label='Ông Sáu đi biển bốn chục năm, ông tự biết', quality='bad', stars=1,
                       review='Thấy tàu ra khơi lúc có lệnh cấm mà không gọi, không báo.', outcome='Nửa đêm tàu ông Sáu chết máy giữa sóng, đài phải điều tàu cứu nạn.',
                       perspectives=[dict(who='Chị Hải Yến', emoji='📻', text='Trạm thấy mà không báo, đài biết thì đã muộn.'),
                                     dict(who='Vợ ông Sáu', emoji='😭', text='Cả đêm tôi đứng ở bến.')]),
                  dict(id='beg', label='Gọi năn nỉ ông về, ông không nghe thì thôi', requires=['family'], quality='ok', stars=3,
                       review='Có gọi, nhưng không báo biên phòng khi tàu vẫn đi.', outcome='Tàu ông Sáu ra tới hòn Đá Bia thì sóng đánh vỡ cabin, phải quay về trong đêm.',
                       perspectives=[dict(who='Ông Sáu', emoji='😓', text='Cậu gọi mà tui không nghe. Lẽ ra cậu phải báo luôn.'),
                                     dict(who='Chú Bảy', emoji='💡', text='Cảnh báo không xong thì báo người có quyền ngăn.')])],
         lesson='Cảnh báo sớm và rõ; không ngăn được thì báo người có thẩm quyền, đừng để một con tàu đi vào bão.'),
]
