"""Content of the nurse career (game/careers/nurse.py): Khoa Nội tổng hợp, Bệnh viện phường Lá Sen.

Everything here is fictional: the hospital, its people, the drug names (Penilá, Cefsen, Sulfasen, Dạ An…) and the
"Thẻ màu Lá Sen" triage scale are game rules written to teach the habits of the job (two identifiers before any
procedure, hand hygiene, allergy and label checks, consent, escalating to the doctor, honest charting). Nothing here
is medical advice: no dose, no amount, no treatment is ever given; the doctor decides, the nurse checks and reports.

Case ids are part of saved tasks (`_v`): never rename or remove one, only add.
"""
from __future__ import annotations

# ---------------------------------------------------------------- the people (index = npc number - 1)
PEOPLE = [
    ('Chị Hoa', 'Điều dưỡng trưởng khoa Nội', 'Hai mươi năm đi buồng, nhớ tên từng người bệnh. Ghét nhất là làm tắt.', 'picky'),
    ('Bác sĩ Khang', 'Bác sĩ điều trị khoa Nội', 'Ít nói, y lệnh rõ ràng, câu cửa miệng: “Bất thường thì gọi anh, đừng ngại.”', 'quiet'),
    ('Bà Tư', 'Người bệnh giường 3, 82 tuổi', 'Con cháu ở xa, bấm chuông nhiều nhất khoa chỉ để có người nói chuyện.', 'warm'),
    ('Ông Bảy', 'Người bệnh giường 5, tiểu đường', 'Khó tính, ghét bị đánh thức đo huyết áp, ngày nào cũng đòi về.', 'sour'),
    ('Chị Ngân', 'Con gái ông Bảy', 'Đi đâu cũng đòi “bác sĩ giỏi nhất”, điện thoại lúc nào cũng sẵn số “người quen”.', 'bossy'),
    ('Tuấn', 'Người bệnh giường 8, gãy tay', 'Hai mươi tuổi, té xe máy, livestream từ giường bệnh, gọi ai cũng là “bro”.', 'genz'),
    ('Cô Liên', 'Người bệnh giường 6, chờ nội soi', 'Hay lo, đọc tin trên mạng nhiều, có hôm đòi hoãn thủ thuật.', 'quiet'),
    ('Cô Mỹ', 'Nhân viên quầy tiếp đón', 'Đứng quầy tiếp đón mười năm, nghe giọng là biết ai làm quá, ai đang nguy.', 'warm'),
]
HOA, KHANG, TU, BAY, NGAN, TUAN, LIEN, MY = range(8)

# ---------------------------------------------------------------- the ward
BEDS = {
    'g3': dict(bed=3, npc=TU, name='Trần Thị Tư', dob='12/03/1944', band='LS-0312', allergy='p', dx='Viêm phổi, đang truyền kháng sinh',
               fall=True, sign='Nguy cơ té ngã'),
    'g5': dict(bed=5, npc=BAY, name='Lê Văn Bảy', dob='05/09/1958', band='LS-0509', allergy=None, dx='Tiểu đường, vết loét bàn chân',
               fall=True, sign='Nguy cơ té ngã'),
    'g6': dict(bed=6, npc=LIEN, name='Phạm Thị Liên', dob='20/11/1971', band='LS-2011', allergy='s', dx='Đau dạ dày, chờ nội soi',
               fall=False, sign=''),
    'g8': dict(bed=8, npc=TUAN, name='Võ Minh Tuấn', dob='14/02/2005', band='LS-1402', allergy='p', dx='Gãy xương cẳng tay, chờ mổ',
               fall=False, sign=''),
}
ALLERGY = {'p': 'Dị ứng kháng sinh nhóm P', 's': 'Dị ứng thuốc nhóm S'}
# Fictional drugs: a name and a group (the allergy band names groups). Never a dose.
DRUGS = {
    'hs1': dict(name='Viên hạ sốt HS-1', group=None),
    'penila': dict(name='Kháng sinh Penilá', group='p'),
    'cefsen': dict(name='Kháng sinh Cefsen', group=None),
    'sulfa': dict(name='Viên Sulfasen', group='s'),
    'daan': dict(name='Thuốc dạ dày Dạ An', group=None),
    'nhuc': dict(name='Thuốc giảm đau Giảm Nhức', group=None),
    'pen': dict(name='Bút tiêm tiểu đường', group=None),
}
ROUTES = {'uong': 'Uống', 'tm': 'Tiêm tĩnh mạch', 'dd': 'Tiêm dưới da'}

# ---------------------------------------------------------------- the handover book (slot 0)
# Per bed: the night nurse's note when something needs eyes first (flag), and a quiet one.
NOTES = {
    'g3': ('Đêm sốt 38,6 °C lúc 3 giờ, đã báo bác sĩ trực. Đo lại ngay đầu ca.', 'Ngủ được, ăn nửa bát cháo. Hay bấm chuông gọi nói chuyện.'),
    'g5': ('Huyết áp lúc 5 giờ thấp hơn mọi ngày, ông kêu chóng mặt. Đo lại ngay đầu ca.', 'Đòi về sớm. Vết loét bàn chân đã thay băng tối qua.'),
    'g6': ('Lúc 4 giờ máy kẹp ngón báo SpO2 thấp rồi tự lên lại. Đo lại ngay đầu ca.', 'Nhịn ăn từ 22 giờ, chờ nội soi 10 giờ. Còn lo lắng.'),
    'g8': ('Tay sưng hơn, kêu đau nhiều, tê ngón lúc 5 giờ. Đã kê cao tay. Xem lại ngay đầu ca.', 'Đau vừa, chờ mổ. Thức khuya dùng điện thoại.'),
}
# The first round's check on the flagged bed (slot 1): the vitals case that goes with each note.
FLAG_VITALS = {'g3': 'v-tu-fever', 'g5': 'v-bay-lowbp', 'g6': 'v-lien-probe', 'g8': 'v-tuan-pain'}

# ---------------------------------------------------------------- vital signs
# The game's alarm card ("Thẻ báo động Lá Sen", a simplified game rule): outside these → report to the doctor.
SIGNS = {
    'temp': dict(name='Nhiệt độ', emoji='🌡️', unit='°C', card='từ 38,0 trở lên hoặc 35,5 trở xuống'),
    'pulse': dict(name='Mạch', emoji='💓', unit='lần/phút', card='trên 110 hoặc dưới 50'),
    'bp': dict(name='Huyết áp', emoji='🩺', unit='mmHg', card='số trên dưới 90 hoặc trên 180'),
    'spo2': dict(name='SpO2', emoji='🫁', unit='%', card='dưới 94'),
    'pain': dict(name='Điểm đau', emoji='😣', unit='/10', card='từ 7 trở lên'),
}
SIGN_IDS = ('temp', 'pulse', 'bp', 'spo2', 'pain')
VITALS = {
    'v-tu-fever': dict(bed='g3', vals=dict(temp='38,9', pulse='104', bp='126/78', spo2='95', pain='2'),
                       look='Bà Tư má đỏ, người nóng ran, thở hơi nhanh.'),
    'v-tu-ok': dict(bed='g3', vals=dict(temp='37,0', pulse='84', bp='132/80', spo2='96', pain='1'), look='Bà Tư ngồi dậy chải tóc, cười móm mém.'),
    'v-tu-spo2': dict(bed='g3', vals=dict(temp='37,6', pulse='108', bp='138/84', spo2='89', pain='2'),
                      look='Bà Tư thở dốc từng hơi, môi hơi tím.'),
    'v-bay-lowbp': dict(bed='g5', vals=dict(temp='36,8', pulse='118', bp='86/52', spo2='96', pain='3'),
                        look='Ông Bảy mặt tái, vịn thành giường: “Đứng dậy là tối sầm.”'),
    'v-bay-ok': dict(bed='g5', vals=dict(temp='36,7', pulse='78', bp='136/82', spo2='97', pain='2'), look='Ông Bảy càu nhàu vì bị đánh thức.'),
    'v-lien-probe': dict(bed='g6', vals=dict(temp='36,6', pulse='80', bp='118/74', spo2='84', pain='3'), recheck=dict(spo2='98'),
                         look='Cô Liên nói chuyện bình thường, môi hồng. Kẹp ngón lỏng, tay cô lạnh ngắt.'),
    'v-lien-ok': dict(bed='g6', vals=dict(temp='36,9', pulse='86', bp='122/76', spo2='98', pain='3'), look='Cô Liên hỏi lần thứ ba: “Mai nội soi có đau không?”'),
    'v-tuan-pain': dict(bed='g8', vals=dict(temp='37,2', pulse='102', bp='134/80', spo2='98', pain='8'),
                        look='Tuấn nhăn mặt, các ngón tay trái sưng căng.'),
    'v-tuan-ok': dict(bed='g8', vals=dict(temp='36,8', pulse='76', bp='124/72', spo2='99', pain='3'), look='Tuấn vừa chơi game vừa giơ tay cho đo.'),
}
VITALS_ROTATION = ('v-tu-ok', 'v-bay-ok', 'v-lien-ok', 'v-tuan-ok', 'v-tu-spo2', 'v-tu-fever', 'v-bay-lowbp', 'v-tuan-pain', 'v-lien-probe')

# ---------------------------------------------------------------- medication rounds
# variant: ok (give) · allergy · wrongpt (the card is another patient's) · label (tray ≠ order) · refuse (consent) ·
#          npo (oral med while nil by mouth) · lowsugar (the order's own hold rule)
MEDS = {
    'm-tu-ok': dict(bed='g3', drug='cefsen', route='tm', time='08:00', variant='ok'),
    'm-tu-allergy': dict(bed='g3', drug='penila', route='tm', time='08:00', variant='allergy'),
    'm-tu-wrongpt': dict(bed='g3', drug='hs1', route='uong', time='12:00', variant='wrongpt',
                         card=dict(name='Trần Thị Tứ', dob='03/07/1949', bed=4)),
    'm-bay-pen-ok': dict(bed='g5', drug='pen', route='dd', time='06:30', variant='ok', sugar='ok'),
    'm-bay-pen-low': dict(bed='g5', drug='pen', route='dd', time='06:30', variant='lowsugar', sugar='low'),
    'm-bay-refuse': dict(bed='g5', drug='daan', route='uong', time='08:00', variant='refuse',
                         refuse='Ông Bảy gạt tay: “Thuốc gì to như viên phấn, uống vô là xót ruột. Không uống!”'),
    'm-lien-npo': dict(bed='g6', drug='daan', route='uong', time='08:00', variant='npo'),
    'm-lien-ok': dict(bed='g6', drug='daan', route='uong', time='16:00', variant='ok'),
    'm-tuan-ok': dict(bed='g8', drug='nhuc', route='uong', time='12:00', variant='ok'),
    'm-tuan-label': dict(bed='g8', drug='cefsen', route='tm', time='08:00', variant='label', tray='penila'),
    'm-tuan-refuse': dict(bed='g8', drug='nhuc', route='uong', time='20:00', variant='refuse',
                          refuse='Tuấn lắc đầu: “Em đọc trên mạng thuốc giảm đau hại gan lắm bro, em không uống đâu.”'),
}
MED_ROTATION = ('m-tu-ok', 'm-bay-pen-ok', 'm-lien-ok', 'm-tuan-ok', 'm-tu-allergy', 'm-bay-refuse', 'm-tu-wrongpt', 'm-lien-npo',
                'm-bay-pen-low', 'm-tuan-label', 'm-tuan-refuse')
HOLD_REASONS = {'allergy': 'Trùng nhóm dị ứng của người bệnh', 'wrongpt': 'Phiếu không đúng người bệnh', 'label': 'Nhãn khay khác y lệnh',
                'refuse': 'Người bệnh từ chối', 'npo': 'Đang nhịn ăn uống chờ thủ thuật', 'lowsugar': 'Đường huyết thấp theo dòng dặn của y lệnh',
                'unsure': 'Chưa rõ, hỏi lại bác sĩ'}

# ---------------------------------------------------------------- call bells
# options: (id, label, grade good|ok|bad|unsafe, outcome, touches the patient)
BELLS = {
    'b-tu-chat': dict(bed='g3', detail='Bà Tư nắm tay bạn: “Cháu ngồi với bà chút. Con bà ở xa, cả tuần không ai gọi.”', options=[
        ('sit', '🪑 Ngồi nói chuyện vài phút, hẹn giờ quay lại', 'good', 'Bà Tư kể chuyện hồi bán vải ở chợ. Bạn hẹn hai giờ chiều ghé, bà gật gù yên tâm.', False),
        ('family', '📞 Giúp bà gọi video cho con, nhờ nhóm tình nguyện ghé chơi', 'good', 'Con trai bà ở xa bắt máy, bà cười suốt mười phút. Nhóm tình nguyện hẹn chiều mai ghé đọc báo cho bà.', False),
        ('long', '☕ Ngồi tán gẫu cả buổi', 'ok', 'Bà vui lắm, nhưng chuông giường khác réo nãy giờ không ai nghe.', False),
        ('brush', '🙅 “Bà đừng bấm chuông lung tung nữa”', 'bad', 'Bà Tư buông tay, quay mặt vào tường. Chiều đó bà không bấm chuông nữa, cả lúc khó thở.', False)]),
    'b-tu-chest': dict(bed='g3', detail='Bà Tư thở dốc, tay ôm ngực: “Tức ngực quá cháu ơi…”', options=[
        ('call', '🚨 Đỡ bà ngồi dậy, đo nhanh, gọi bác sĩ ngay', 'good', 'Bác sĩ Khang tới sau hai phút, cho làm điện tim ngay tại giường. Bà Tư nắm tay bạn không rời.', True),
        ('own', '💊 Đưa bà viên thuốc trong túi mình cho đỡ', 'unsafe', 'Thuốc không có y lệnh, không ai biết bà có hợp không. Chị Hoa giật mình lập biên bản sự cố.', True),
        ('wait', '⏳ Bảo bà nằm nghỉ, lát quay lại', 'unsafe', 'Mười phút sau bà Tư tím tái, cả khoa chạy tới. May mà kịp.', False),
        ('window', '🌬️ Mở cửa sổ cho thoáng rồi đi', 'bad', 'Gió vào mát thật, nhưng cơn tức ngực vẫn còn và không ai biết.', False)]),
    'b-tu-fall': dict(bed='g3', detail='Bà Tư đang cố trèo qua thanh chắn giường để nhặt cái điện thoại rơi dưới sàn.', options=[
        ('help', '🛑 Bảo bà nằm yên, nhặt giúp, kéo thanh chắn, để chuông và điện thoại trong tầm tay', 'good', 'Bà Tư cảm ơn rối rít. Điện thoại, ly nước, chuông gọi giờ nằm ngay cạnh gối.', True),
        ('scold', '😠 Mắng bà một trận cho nhớ', 'bad', 'Bà Tư im thin thít, mắt đỏ hoe. Bà sợ gọi y tá luôn từ đó.', False),
        ('tie', '🪢 Buộc tay bà vào thành giường cho chắc', 'unsafe', 'Không ai được tự trói người bệnh. Chị Hoa tháo dây, lập biên bản.', True)]),
    'b-bay-toilet': dict(bed='g5', detail='Ông Bảy đã tự thả chân xuống giường: “Đi vệ sinh, tự đi được, khỏi đỡ!” Ông đang truyền dịch, chân còn băng.', options=[
        ('help', '🤝 Hạ giường thấp, đi dép chống trượt, đỡ ông đi cùng cọc truyền', 'good', 'Ông Bảy càu nhàu suốt đường nhưng tới nơi an toàn, về tới giường cũng an toàn.', True),
        ('pan', '🚽 Đưa bô tại giường, kéo rèm cho kín', 'good', 'Ông Bảy lầm bầm “phiền phức”, nhưng không phải đứng dậy lúc đang chóng mặt.', True),
        ('alone', '👍 “Dạ, bác tự đi nhé”', 'unsafe', 'Ông Bảy trượt chân ở cửa nhà vệ sinh, đập gối xuống nền. Phải chụp phim kiểm tra.', False),
        ('later', '⏳ “Bác chờ con xíu, đang bận”', 'bad', 'Ông Bảy chờ không nổi, tự đi. May mà chị Ngân đỡ kịp.', False)]),
    'b-bay-drip': dict(bed='g5', detail='Máy truyền dịch kêu bíp bíp: chai dịch đã hết, trong dây còn một đoạn.', options=[
        ('clamp', '🔒 Khóa dây truyền, xem chỗ kim, báo theo y lệnh', 'good', 'Bạn khóa dây, chỗ kim sạch, ghi giờ hết dịch. Bác sĩ Khang dặn ngưng truyền theo y lệnh.', True),
        ('new', '🧴 Tự lắp chai mới loại nào cũng được', 'unsafe', 'Dịch truyền không có y lệnh. Chị Hoa tháo ra kịp, lập biên bản.', True),
        ('mute', '🔇 Tắt tiếng máy rồi đi', 'unsafe', 'Dây để mở, máu trào ngược lên dây. Phải đặt lại kim.', False),
        ('family', '👨‍👩‍👧 Nhờ người nhà rút kim giùm', 'bad', 'Chị Ngân rút vụng, máu chảy ướt ga giường.', False)]),
    'b-tuan-pain': dict(bed='g8', detail='Tuấn nhăn mặt: “Tay em nhức kinh khủng bro ơi, ngón tay tê tê.”', options=[
        ('assess', '🩺 Hỏi điểm đau, xem ngón tay (màu, ấm, cử động), báo bác sĩ', 'good', 'Ngón tay hơi tím, Tuấn chấm đau 8/10. Bác sĩ Khang tới nới nẹp ngay và cho y lệnh mới.', True),
        ('own', '💊 Cho Tuấn viên giảm đau trong túi mình', 'unsafe', 'Thuốc không có y lệnh. Cơn đau dịu đi nên chẳng ai biết tay đang chèn ép.', True),
        ('loose', '✂️ Tự nới băng nẹp cho đỡ', 'bad', 'Nới xong đỡ đau thật, nhưng xương lệch đi một chút. Bác sĩ phải chỉnh lại.', True),
        ('ignore', '📱 “Gãy tay thì đau là bình thường”', 'unsafe', 'Hai tiếng sau ngón tay Tuấn tím ngắt. Phải mổ cấp cứu.', False)]),
    'b-tuan-live': dict(bed='g8', detail='Tuấn đang livestream: “Mọi người ơi chị y tá tới nè, chào mọi người đi!” Giường bên cạnh lọt vào khung hình.', options=[
        ('privacy', '🙅 Nhờ tắt máy khi đang chăm sóc, không quay người bệnh khác', 'good', 'Tuấn xoay máy vào tường: “Ok bro, quyền riêng tư nha mọi người.” Giường bên gật đầu cảm ơn.', False),
        ('wave', '👋 Vẫy tay chào cho vui', 'bad', 'Clip có cả mặt ông cụ giường bên đang ngủ há miệng. Con ông cụ gọi lên khoa phản ánh.', False),
        ('grab', '📵 Giật điện thoại', 'bad', 'Tuấn la lên: “Y tá cướp điện thoại!” Cả phòng quay sang nhìn.', False),
        ('ok', '🤷 Kệ, làm việc của mình', 'ok', 'Bạn làm xong việc. Clip vẫn chạy, may mà không quay ai khác.', False)]),
    'b-lien-cold': dict(bed='g6', detail='Cô Liên run run: “Lạnh quá, cho cô xin cái chăn. Mà mai nội soi có đau không cháu?”', options=[
        ('blanket', '🧣 Mang chăn, đo nhiệt độ, nói sơ quy trình, hẹn bác sĩ giải thích thêm', 'good', 'Cô Liên ấm người, bớt run. Chiều bác sĩ Khang ghé nói chuyện, cô ngủ ngon hơn.', True),
        ('only', '🧣 Mang chăn rồi đi', 'ok', 'Cô Liên đỡ lạnh nhưng nằm trằn trọc lo tới tối.', False),
        ('scare', '😬 “Đau lắm cô ơi, ráng chịu”', 'bad', 'Cô Liên khóc cả buổi, tối đó gọi con đòi về.', False)]),
    'b-lien-fever': dict(bed='g6', detail='Cô Liên: “Người cô hâm hấp, cho cô xin viên hạ sốt.”', options=[
        ('measure', '🌡️ Đo nhiệt độ, báo bác sĩ xem y lệnh, lau mát', 'good', 'Nhiệt độ 38,2 °C. Bác sĩ Khang cho y lệnh, dặn theo dõi lại sau một giờ.', True),
        ('own', '💊 Lấy viên hạ sốt trong túi mình đưa cô', 'unsafe', 'Cô Liên dị ứng nhóm S, mà viên thuốc trong túi bạn chẳng ai biết thuộc nhóm nào.', True),
        ('later', '⏳ “Hạ sốt thì chờ bác sĩ đi buồng”', 'bad', 'Cô Liên sốt tới trưa mới có người hỏi.', False)]),
}
BELL_ROTATION = ('b-tu-chat', 'b-bay-toilet', 'b-lien-cold', 'b-tuan-live', 'b-bay-drip', 'b-tu-chest', 'b-tuan-pain', 'b-lien-fever', 'b-tu-fall')

# ---------------------------------------------------------------- triage at reception ("Thẻ màu Lá Sen", a game rule)
COLORS = {'do': ('🔴', 'Đỏ', 'Vào ngay, gọi bác sĩ ngay'), 'cam': ('🟠', 'Cam', 'Trong 10 phút'),
          'vang': ('🟡', 'Vàng', 'Trong 30 phút'), 'xanh': ('🟢', 'Xanh', 'Chờ theo lượt')}
COLOR_ORDER = ('do', 'cam', 'vang', 'xanh')
TRIAGE = {
    'tr-chest': dict(who='Ông cụ ngồi góc ghế chờ', emoji='👴', text='Ngồi im, tay ôm ngực, trán lấm tấm mồ hôi. Không kêu ca gì.',
                     ask='“Tức ngực nửa tiếng nay, lan ra tay trái… chắc mệt thôi, để người khác khám trước.”', quick='Mạch 112, SpO2 94%, da lạnh ẩm.', best='do'),
    'tr-scrape': dict(who='Thanh niên áo đội bóng', emoji='🧑', text='La hét ầm ĩ, giơ cánh tay trầy: “Khám tôi trước, đau muốn xỉu!”',
                      ask='“Té xe đạp, trầy tay thôi mà rát lắm, có chảy máu đâu.”', quick='Mạch 88, SpO2 99%, vết trầy nông, sạch.', best='xanh'),
    'tr-baby': dict(who='Chị bế bé 2 tuổi', emoji='👶', text='Bé nằm lả trên vai mẹ, không khóc.',
                    ask='“Bé sốt từ đêm, nôn mấy lần, từ sáng tới giờ chưa đi tiểu.”', quick='Nhiệt 39,4 °C, môi khô, bé lừ đừ, gọi mới mở mắt.', best='cam', ok=('do',)),
    'tr-cut': dict(who='Chị bán rau', emoji='🔪', text='Tay quấn khăn thấm máu: “Dao thái rau trượt.”',
                   ask='“Ép khăn nãy giờ thì máu ngưng rồi, vết cắt sâu ở ngón cái.”', quick='Mạch 90, máu đã cầm, ngón cử động được.', best='vang'),
    'tr-stroke': dict(who='Bà cụ được con dâu dìu vào', emoji='👵', text='Miệng hơi méo, nói ngọng, tay phải buông thõng.',
                      ask='Con dâu: “Mẹ đang ăn sáng thì tự nhiên nói không rõ, chừng bốn mươi phút trước.”', quick='Huyết áp 182/100, một bên mặt xệ, tay phải yếu.', best='do'),
    'tr-cough': dict(who='Anh shipper', emoji='🛵', text='Ho khụ khụ, đeo khẩu trang, mắt dán vào app.',
                     ask='“Ho với sốt nhẹ hai ngày, vẫn chạy đơn được, khám lẹ giùm em.”', quick='Nhiệt 37,8 °C, SpO2 98%, thở êm.', best='xanh'),
    'tr-allergy': dict(who='Cô gái đi cùng bạn', emoji='🦐', text='Mặt nổi mẩn, môi sưng, thở khò khè.',
                       ask='Bạn đi cùng: “Mới ăn bún hải sản ở chợ, mười phút sau là vậy.”', quick='SpO2 90%, thở rít, nổi mẩn khắp người.', best='do'),
    'tr-head': dict(who='Chú say rượu được bạn nhậu dìu vào', emoji='🍺', text='Trán sưng một cục, cứ hỏi đi hỏi lại “sao tao ở đây”.',
                    ask='Bạn nhậu: “Trượt chân đập đầu vô bậc thềm, có xỉu chừng một phút.”', quick='Mạch 96, lơ mơ, hỏi lặp lại, nôn một lần.', best='cam', ok=('do',)),
    'tr-belly': dict(who='Em học sinh lớp 10', emoji='🎒', text='Ôm bụng phải, đi khom khom.',
                     ask='“Đau quanh rốn từ tối qua, giờ chuyển xuống bụng dưới bên phải, ấn vô là đau.”', quick='Nhiệt 38,0 °C, mạch 98.', best='vang', ok=('cam',)),
    'tr-refill': dict(who='Cô giáo về hưu', emoji='📋', text='Cầm sổ khám bệnh, đứng xếp hàng ngay ngắn.',
                      ask='“Cô tới lấy thuốc huyết áp tháng này thôi, không có gì khác.”', quick='Huyết áp 128/80, mạch 76.', best='xanh'),
    'tr-burn': dict(who='Anh thợ hàn', emoji='🔥', text='Cẳng chân đỏ rộp, chườm khăn ướt.',
                    ask='“Nồi nước sôi đổ trúng, rộp cỡ bàn tay, rát lắm.”', quick='Mạch 100, bỏng rộp cỡ một bàn tay ở cẳng chân.', best='vang'),
    'tr-sugar': dict(who='Ông cụ được vợ dìu', emoji='🍬', text='Run rẩy, vã mồ hôi, trả lời lộn xộn.',
                     ask='Bà vợ: “Ổng tiểu đường, sáng tiêm thuốc rồi mà chưa kịp ăn gì.”', quick='Máy đo đường huyết báo THẤP, mạch 110, da ẩm lạnh.', best='do'),
    'tr-headache': dict(who='Chị nhân viên văn phòng', emoji='🤕', text='Ôm đầu, nhắm nghiền mắt, sợ ánh đèn.',
                        ask='“Đang họp thì đau đầu dữ dội, đột ngột, đau nhất từ trước tới giờ.”', quick='Huyết áp 168/96, cổ hơi cứng.', best='cam', ok=('do',)),
    'tr-nose': dict(who='Ông chú bịt mũi bằng khăn', emoji='🩸', text='Khăn đỏ thẫm, áo dính máu.',
                    ask='“Chảy máu cam hai mươi phút rồi không cầm, tôi đang uống thuốc chống đông.”', quick='Mạch 104, huyết áp 150/90, máu vẫn rỉ.', best='cam'),
    'tr-dog': dict(who='Bé trai 6 tuổi và bố', emoji='🐕', text='Bắp chân có vết răng nhỏ, bé mếu máo.',
                   ask='Bố: “Chó nhà hàng xóm cắn, chưa rõ đã tiêm phòng chưa.”', quick='Vết cắn nông, đã rửa nước, bé tỉnh táo.', best='vang'),
    'tr-sprain': dict(who='Chị chạy bộ buổi sáng', emoji='🏃‍♀️', text='Đi khập khiễng, cổ chân sưng.',
                      ask='“Lật cổ chân lúc chạy, vẫn đi được nhưng đau.”', quick='Mạch 80, cổ chân sưng, ngón chân hồng ấm.', best='xanh'),
}
TRIAGE_IDS = tuple(TRIAGE)

# ---------------------------------------------------------------- getting someone ready for a procedure
PROC_CHECKS = {'consent': ('📝', 'Xem giấy cam đoan'), 'fasting': ('🍽️', 'Hỏi nhịn ăn uống'), 'allergy': ('🔴', 'Xem vòng dị ứng'),
               'jewel': ('💍', 'Trang sức, răng giả')}
PROCS = {
    'p-lien-ready': dict(bed='g6', name='Nội soi dạ dày', time='10:00', consent='signed', fasting='yes', jewel=False, variant='ready'),
    'p-lien-ate': dict(bed='g6', name='Nội soi dạ dày', time='10:00', consent='signed', fasting='no', jewel=False, variant='ate'),
    'p-lien-scared': dict(bed='g6', name='Nội soi dạ dày', time='10:00', consent='unsigned', fasting='yes', jewel=False, variant='unsigned'),
    'p-tuan-ring': dict(bed='g8', name='Mổ kết hợp xương cẳng tay', time='14:00', consent='signed', fasting='yes', jewel=True, variant='ring'),
    'p-tuan-refuse': dict(bed='g8', name='Mổ kết hợp xương cẳng tay', time='14:00', consent='signed', fasting='yes', jewel=False, variant='refuse'),
    'p-tuan-ready': dict(bed='g8', name='Mổ kết hợp xương cẳng tay', time='14:00', consent='signed', fasting='yes', jewel=False, variant='ready'),
}
PROC_ROTATION = ('p-lien-ready', 'p-tuan-ring', 'p-lien-ate', 'p-lien-scared', 'p-tuan-refuse', 'p-tuan-ready')
PROC_TEXT = {
    'consent': {'signed': 'Giấy cam đoan đã ký, có chữ ký bác sĩ giải thích.', 'unsigned': 'Giấy cam đoan còn trống. Cô Liên: “Cô sợ lắm, trên mạng nói nội soi thủng dạ dày…”'},
    'fasting': {'yes': 'Nhịn ăn uống từ 22 giờ tối qua.', 'no': '“Sáng nay đói quá, cô lỡ uống ly sữa với cái bánh bao rồi.”'},
    'jewel': {True: 'Còn đeo dây chuyền vàng và nhẫn.', False: 'Không đeo trang sức, không răng giả.'},
}

# ---------------------------------------------------------------- going home
TEACH = {'tai_kham': ('📅', 'Lịch tái khám'), 'dau_hieu': ('🚩', 'Dấu hiệu phải quay lại ngay'),
         'thuoc': ('💊', 'Thuốc theo đơn in sẵn, không tự thêm bớt'), 'an_uong': ('🥗', 'Ăn uống, đường huyết'),
         'vet': ('🩹', 'Giữ vết thương, nẹp khô sạch'), 'giay': ('📄', 'Giấy ra viện, thẻ BHYT')}
DISCHARGES = {
    'd-bay': dict(bed='g5', paper='signed', bhyt='ok', topics=('tai_kham', 'dau_hieu', 'thuoc', 'an_uong', 'vet'), cannula=True),
    'd-bay-unsigned': dict(bed='g5', paper='unsigned', bhyt='ok', topics=('tai_kham', 'dau_hieu', 'thuoc', 'an_uong'), cannula=True,
                           rush='Chị Ngân: “Xe đợi dưới cổng rồi, bác sĩ ký sau cũng được, cho bố chị về luôn đi!”'),
    'd-tu': dict(bed='g3', paper='signed', bhyt='expired', topics=('tai_kham', 'dau_hieu', 'thuoc', 'giay'), cannula=True),
    'd-tuan': dict(bed='g8', paper='signed', bhyt='ok', topics=('tai_kham', 'dau_hieu', 'thuoc', 'vet'), cannula=False),
}
DISCHARGE_ROTATION = ('d-bay', 'd-tuan', 'd-bay-unsigned', 'd-tu')
DISCHARGE_TEXT = {
    'paper': {'signed': 'Giấy ra viện đã có chữ ký bác sĩ Khang.', 'unsigned': 'Giấy ra viện chưa có chữ ký bác sĩ.'},
    'bhyt': {'ok': 'Thẻ BHYT còn hạn tới cuối năm.', 'expired': 'Thẻ BHYT hết hạn hôm qua: mời người nhà ra quầy BHYT làm thủ tục trước khi về.'},
    'cannula': {True: 'Kim luồn ở mu bàn tay vẫn còn: rút trước khi về.', False: 'Không còn kim luồn.'},
}

# ---------------------------------------------------------------- the day's mood
MODS = [
    dict(id='normal', emoji='🌤️', label='Ngày thường', hint='Khoa đủ giường, việc đều tay.', weight=3),
    dict(id='busy', emoji='🚑', label='Khoa đông', hint='Phòng khám chuyển lên nhiều ca: quầy tiếp đón chật kín.', min_day=2, weight=2),
    dict(id='audit', emoji='🧴', label='Đoàn kiểm tra rửa tay', hint='Hôm nay có đoàn kiểm soát nhiễm khuẩn: chạm người bệnh nào cũng sát khuẩn tay trước.', min_day=2, weight=2),
    dict(id='flu', emoji='🤧', label='Mùa cúm', hint='Nhiều người sốt, ho: đeo khẩu trang, phân loại kỹ ở quầy.', min_day=3, weight=2),
    dict(id='visit', emoji='👨‍👩‍👧', label='Chủ nhật thăm bệnh', hint='Người nhà kéo vào đông: giữ giờ thăm, mỗi giường hai người.', min_day=3, weight=1),
]

INTRO = dict(
    title='Giới thiệu nghề: điều dưỡng khoa Nội',
    lead='Bệnh viện phường Lá Sen, khoa Nội tổng hợp. Bác sĩ quyết điều trị; điều dưỡng chăm người bệnh, làm đúng y lệnh, '
         'kiểm từng bước và báo ngay khi có gì bất thường. Chị Hoa kèm bạn mấy ca đầu.',
    work=[('📋', 'Nhận giao ca, đọc sổ, chọn giường xem trước'), ('🧴', 'Sát khuẩn tay trước khi chạm người bệnh'),
          ('🪪', 'Hỏi họ tên và ngày sinh, đối chiếu vòng tay'), ('🌡️', 'Đo dấu hiệu sinh tồn, ghi phiếu cho đúng'),
          ('💊', 'Đối chiếu y lệnh, dị ứng, nhãn khay trước khi cho thuốc'), ('🚦', 'Phân loại người tới khám theo thẻ màu'),
          ('🔔', 'Trả lời chuông gọi'), ('📞', 'Bất thường thì báo bác sĩ ngay')],
    meet=[('👵', 'Bà Tư: cô đơn, bấm chuông hoài'), ('👴', 'Ông Bảy: tiểu đường, khó tính'), ('📱', 'Chị Ngân: đòi bác sĩ giỏi nhất'),
          ('🤳', 'Tuấn: gãy tay, livestream'), ('😟', 'Cô Liên: sợ nội soi'), ('🧾', 'Người nhà dúi phong bì, xin giường đẹp'),
          ('🌿', 'Ông “thần y” mang thuốc nam'), ('🍺', 'Khách say quậy ca tối')],
    stars=[('🪪', 'Đúng người bệnh'), ('🧴', 'Tay sạch'), ('📝', 'Ghi phiếu thật, đủ'), ('📞', 'Báo bác sĩ kịp lúc'),
           ('🙏', 'Tôn trọng người bệnh từ chối'), ('🚫', 'Không nhận phong bì, không làm tắt')],
)

# ---------------------------------------------------------------- regulars
REG_STORY = {
    TU: ('Bà Tư: “Cháu giống đứa cháu gái của bà ghê.”', 'Bà Tư đan cho bạn cái móc khóa hình bông sen.',
         'Bà Tư dặn con trai: “Cô điều dưỡng này tốt, nhớ cảm ơn bằng lá thư nghe.”'),
    BAY: ('Ông Bảy: “Đo gì đo hoài.”', 'Ông Bảy chịu ăn đúng bữa, không giấu kẹo dưới gối nữa.', 'Ông Bảy bắt tay: “Cô cứng mà tốt.”'),
    NGAN: ('Chị Ngân: “Em biết ai giỏi nhất ở đây không?”', 'Chị Ngân bớt gọi “người quen”, hỏi thẳng bạn trước.',
           'Chị Ngân viết thư khen gửi phòng Điều dưỡng.'),
    TUAN: ('Tuấn: “Chị điều dưỡng chill ghê.”', 'Tuấn quay clip “một ngày nằm viện đúng quy định”, không lộ mặt ai.',
           'Tuấn tặng cả khoa hộp bánh flan mẹ làm.'),
    LIEN: ('Cô Liên: “Cô lo quá cháu ơi.”', 'Cô Liên tự đọc giấy hướng dẫn, gạch chân từng dòng.', 'Cô Liên khoe: “Nội soi xong rồi, nhẹ hều!”'),
    MY: ('Cô Mỹ: “Ở quầy này, người la to chưa chắc là người nặng.”', 'Cô Mỹ dúi cho bạn ly trà gừng giữa ca.', 'Cô Mỹ khen bạn phân loại tinh như người cũ.'),
}

# ---------------------------------------------------------------- surprises (kit desk scripts)
DESK = [
    dict(id='power', title='Cúp điện năm phút', emoji='🔌', npc=HOA, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Đèn tắt phụt, máy phát chưa chạy. Người nhà la ó, máy truyền dịch chuyển sang pin kêu bíp bíp.',
         options=[dict(id='check', label='Đi một vòng xem ngay người thở oxy, đang truyền dịch, trấn an người nhà', hint='', effects=dict(xp=6), good=True,
                       outcome='Bình oxy giường 3 vẫn chạy, máy truyền dịch còn pin. Năm phút sau đèn sáng lại, cả phòng vỗ tay.'),
                  dict(id='post', label='Đăng lên mạng “bệnh viện gì cúp điện hoài”', hint='', effects=dict(review=[2, 'Nhân viên bệnh viện lên mạng chê chính bệnh viện mình giữa lúc cúp điện.', HOA]), good=False,
                       outcome='Bài đăng lan nhanh hơn cả máy phát. Chị Hoa gọi bạn vào hỏi chuyện.'),
                  dict(id='wait', label='Đứng chờ có điện lại', hint='', effects=dict(patience=-6), good=None,
                       outcome='Có điện lại thì mấy giường đã bấm chuông inh ỏi.')],
         default='wait'),
    dict(id='audit', title='Đoàn kiểm tra rửa tay', emoji='🧴', npc=HOA, min_day=2, tone='gentle', at='between', weight=3, mods=('audit',),
         text='Một chị trong đoàn kiểm soát nhiễm khuẩn cầm bảng, đứng cuối phòng ghi từng lần bạn sát khuẩn tay.',
         options=[dict(id='normal', label='Làm như mọi ngày: trước và sau khi chạm người bệnh đều sát khuẩn', hint='', effects=dict(xp=6), good=True,
                       outcome='Phiếu chấm của khoa đạt điểm tối đa. Chị Hoa dán phiếu lên bảng tin.'),
                  dict(id='show', label='Rửa tay thật kỹ chỉ lúc đoàn đang nhìn', hint='', effects={}, good=None,
                       outcome='Đoàn đi rồi bạn lại quên. Chị lao công nhìn thấy hết.'),
                  dict(id='hide', label='Lánh sang phòng khác cho đỡ bị chấm', hint='', effects=dict(patience=-5), good=False,
                       outcome='Phòng bạn phụ trách không ai trực suốt nửa tiếng.')],
         default='show'),
    dict(id='cat', title='Mèo hoang vào phòng bệnh', emoji='🐈', npc=TU, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Một con mèo vàng chui qua cửa sổ, nhảy lên giường bà Tư nằm cuộn tròn. Bà Tư cười tít mắt.',
         options=[dict(id='out', label='Nhẹ nhàng bế mèo ra ngoài, thay ga giường, đóng lưới cửa sổ', hint='', effects=dict(xp=4), good=True,
                       outcome='Mèo được đưa ra vườn. Bà Tư hơi tiếc nhưng gật gù: “Ừ, bệnh viện phải sạch.”'),
                  dict(id='keep', label='Để mèo nằm cho bà vui', hint='', effects=dict(review=[3, 'Phòng bệnh mà có mèo hoang nằm trên giường.', NGAN]), good=False,
                       outcome='Người nhà giường bên dị ứng lông mèo hắt hơi suốt buổi.'),
                  dict(id='chase', label='Cầm chổi đuổi', hint='', effects=dict(patience=-4), good=None,
                       outcome='Mèo chạy loạn khắp khoa, làm đổ khay bông băng.')],
         default='out'),
    dict(id='lottery', title='Người bán vé số vào phòng bệnh', emoji='🎟️', npc=BAY, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Một chú bán vé số đi dọc các giường mời: “Mua đi bác, nằm viện mua vé số là trúng!” Ông Bảy móc ví.',
         options=[dict(id='guide', label='Lịch sự mời chú ra ngoài, nhắc giờ thăm và quy định khoa', hint='', effects=dict(xp=3), good=True,
                       outcome='Chú bán vé số đi ra, còn chúc cả phòng mau khỏe.'),
                  dict(id='buy', label='Mua một tờ cho chú đi lẹ', hint='−2 xu', effects=dict(money=-2), good=None,
                       outcome='Chú đi rồi lại có chú khác vào.'),
                  dict(id='shout', label='Quát đuổi trước mặt mọi người', hint='', effects=dict(review=[3, 'Y tá quát người ta như quát trộm.', BAY]), good=False,
                       outcome='Cả phòng im phăng phắc, ông Bảy lắc đầu.')],
         default='guide'),
    dict(id='escape', title='Ông Bảy trốn ra căng tin', emoji='🍧', npc=BAY, min_day=3, tone='gentle', at='between', weight=2, mods=None,
         text='Giường 5 trống trơn. Chị lao công báo: ông Bảy đang ngồi căng tin, trước mặt là ly chè đậu ngọt lịm.',
         options=[dict(id='talk', label='Ra ngồi cạnh, nói chuyện đường huyết, mời ông về đo lại', hint='', effects=dict(xp=5, patience=-2), good=True,
                       outcome='Ông Bảy đẩy ly chè sang một bên: “Thôi, về đo. Mà cô đừng méc con Ngân.”'),
                  dict(id='scold', label='Giật ly chè, mắng giữa căng tin', hint='', effects=dict(review=[2, 'Bị mắng như con nít giữa căng tin.', BAY]), good=False,
                       outcome='Ông Bảy giận, cả chiều không cho ai đo huyết áp.'),
                  dict(id='ignore', label='Kệ ông, người lớn tự biết', hint='', effects=dict(patience=-3), good=None,
                       outcome='Chiều đó đường huyết ông vọt lên, bác sĩ Khang nhíu mày.')],
         default='ignore'),
    dict(id='wetfloor', title='Sàn ướt không biển báo', emoji='🧽', npc=HOA, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Chị lao công vừa lau hành lang, sàn còn loáng nước, không có biển báo. Một bà cụ chống gậy đang đi tới.',
         options=[dict(id='sign', label='Đỡ bà cụ đi vòng, đặt biển “Sàn ướt”, nhắc chị lao công', hint='', effects=dict(xp=4), good=True,
                       outcome='Bà cụ đi qua an toàn. Chị lao công cảm ơn, từ đó luôn mang biển theo.'),
                  dict(id='shout', label='Hét từ xa: “Bà ơi coi chừng trơn!”', hint='Hên xui', effects={},
                       luck=dict(p=0.5, win=dict(effects={}, good=None, outcome='Bà cụ giật mình đứng lại kịp.'),
                                 lose=dict(effects=dict(patience=-6), good=False, outcome='Bà cụ giật mình quay lại, trượt chân ngồi bệt. May không gãy gì.'))),
                  dict(id='pass', label='Không phải việc của mình', hint='', effects=dict(review=[1, 'Mẹ tôi trượt ngã ở hành lang mà điều dưỡng đứng nhìn.', NGAN]), good=False,
                       outcome='Bà cụ trượt chân. Khoa phải viết báo cáo sự cố té ngã.')],
         default='pass'),
    dict(id='outlets', title='Tranh ổ cắm sạc điện thoại', emoji='🔌', npc=NGAN, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Hai nhà người bệnh cãi nhau vì ổ cắm duy nhất ở đầu giường. Một người định rút phích máy hút đờm ra cắm sạc.',
         options=[dict(id='rule', label='Giữ nguyên ổ cắm máy y tế, chỉ chỗ sạc chung ở phòng chờ', hint='', effects=dict(xp=4), good=True,
                       outcome='Máy hút đờm vẫn chạy. Hai nhà xách điện thoại ra phòng chờ, vừa sạc vừa làm quen nhau.'),
                  dict(id='turns', label='Cho hai nhà thay phiên cắm ổ đầu giường', hint='', effects=dict(patience=-3), good=None,
                       outcome='Lúc cắm lúc rút, máy hút đờm tắt lúc nào không hay.'),
                  dict(id='leave', label='Kệ họ tự giải quyết', hint='', effects=dict(review=[2, 'Người nhà cãi nhau om sòm, điều dưỡng làm ngơ.', NGAN]), good=False,
                       outcome='Hai nhà lớn tiếng tới mức bảo vệ phải lên.')],
         default='leave'),
    dict(id='sharps', title='Kim tiêm trong thùng rác thường', emoji='🗑️', npc=HOA, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Thấy một cây kim tiêm đã dùng nằm chỏng chơ trong thùng rác thường, chị lao công sắp thò tay gom rác.',
         options=[dict(id='box', label='Bảo chị dừng tay, dùng kẹp gắp kim bỏ vào hộp kim, báo trưởng ca', hint='', effects=dict(xp=6), good=True,
                       outcome='Chị lao công thở phào. Chị Hoa nhắc cả khoa: kim xong là vào hộp kim ngay tại chỗ.'),
                  dict(id='hand', label='Tự nhặt bằng tay cho nhanh', hint='', effects=dict(patience=-2), good=False,
                       outcome='Suýt bị kim đâm vào ngón tay. Tim đập thình thịch cả buổi.'),
                  dict(id='ignore', label='Không phải kim mình, kệ', hint='', effects={}, good=False,
                       outcome='Chiều đó chị lao công bị kim đâm, phải đi xét nghiệm theo dõi.')],
         default='ignore'),
    dict(id='lost_kid', title='Bé con đi lạc trong khoa', emoji='🧒', npc=MY, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Một bé gái chừng bốn tuổi đứng khóc ở hành lang: “Con tìm bà ngoại…”',
         options=[dict(id='care', label='Dỗ bé, đứng một chỗ, nhờ cô Mỹ gọi loa tìm người nhà', hint='', effects=dict(xp=4), good=True,
                       outcome='Năm phút sau bà ngoại bé chạy tới, ôm chầm lấy cháu.'),
                  dict(id='walk', label='Dắt bé đi khắp các phòng tìm', hint='', effects=dict(patience=-5), good=None,
                       outcome='Tìm được bà, nhưng ba giường bấm chuông không ai trực.'),
                  dict(id='leave', label='Bảo bé đứng chờ, mình đi làm tiếp', hint='', effects=dict(review=[2, 'Bé lạc khóc ngoài hành lang mà nhân viên đi ngang qua.', MY]), good=False,
                       outcome='Bé đi lang thang tới tận cầu thang.')],
         default='care'),
    dict(id='press', title='Phóng viên mạng hỏi chuyện', emoji='🎙️', npc=HOA, min_day=3, tone='tense', at='between', weight=1, mods=None,
         text='Một bạn tự xưng phóng viên trang tin mạng chĩa micro: “Nghe nói khoa có ca sĩ Mi Mi nằm viện, bệnh gì vậy chị?”',
         options=[dict(id='refer', label='Không nói gì về người bệnh, mời liên hệ phòng truyền thông bệnh viện', hint='', effects=dict(xp=5), good=True,
                       outcome='Bạn phóng viên đi ra, bài viết chỉ có ảnh cổng bệnh viện.'),
                  dict(id='hint', label='Hé chút xíu “không nặng đâu”', hint='', effects=dict(review=[1, 'Nhân viên bệnh viện kể bệnh của người khác cho báo.', NGAN]), good=False,
                       outcome='Tối đó có bài “nguồn tin trong bệnh viện tiết lộ”. Phòng điều dưỡng mời bạn lên.'),
                  dict(id='shoo', label='Xua tay đuổi', hint='', effects={}, good=None, outcome='Bạn phóng viên quay luôn cảnh bị đuổi, nhưng không có gì để viết.')],
         default='refer'),
    dict(id='stove', title='Bếp cồn trong phòng bệnh', emoji='🔥', npc=NGAN, min_day=3, tone='tense', at='between', weight=1, mods=None,
         text='Người nhà giường 7 lén đặt bếp cồn dưới gầm giường hâm nồi cháo, ngay cạnh bình oxy của giường bên.',
         options=[dict(id='stop', label='Tắt bếp ngay, giải thích nguy cơ cháy cạnh oxy, chỉ chỗ hâm đồ ăn ở căng tin', hint='', effects=dict(xp=6), good=True,
                       outcome='Bếp tắt. Người nhà giật mình: “Trời, không biết oxy nguy hiểm vậy.”'),
                  dict(id='later', label='Nhắc khéo, lát quay lại xem', hint='', effects=dict(patience=-3), good=False,
                       outcome='Lát quay lại, nồi cháo đã sôi trào, mùi cồn khắp phòng.'),
                  dict(id='ignore', label='Thương người nhà, kệ cho họ nấu', hint='', effects=dict(review=[1, 'Phòng bệnh có bếp cồn cạnh bình oxy mà không ai nhắc.', HOA]), good=False,
                       outcome='Bảo vệ đi tuần phát hiện, khoa bị nhắc nhở trong giao ban.')],
         default='later'),
    dict(id='onestar', title='Dọa đánh giá một sao', emoji='⭐', npc=NGAN, min_day=2, tone='tense', at='between', weight=2, mods=None,
         text='Chị Ngân giơ điện thoại: “Đợi bác sĩ hai mươi phút rồi. Không gọi ngay là chị cho bệnh viện một sao, kèm tên em!”',
         options=[dict(id='explain', label='Xin lỗi vì chờ, nói rõ bác sĩ đang ở ca nào, hẹn giờ cụ thể', hint='', effects=dict(xp=4), good=True,
                       outcome='Chị Ngân bớt nóng. Mười phút sau bác sĩ Khang tới đúng như hẹn.'),
                  dict(id='lie', label='“Bác sĩ tới liền” (thật ra chưa biết)', hint='', effects=dict(review=[2, 'Hứa “tới liền” rồi để chờ thêm nửa tiếng.', NGAN]), good=False,
                       outcome='Nửa tiếng sau bác sĩ mới tới, chị Ngân đăng một sao thật.'),
                  dict(id='dare', label='“Chị cứ đánh giá đi”', hint='', effects=dict(review=[1, 'Điều dưỡng thách người nhà đánh giá. Thái độ!', NGAN]), good=False,
                       outcome='Chị Ngân đăng bài dài, tag cả trang bệnh viện.')],
         default='explain'),
    dict(id='breakfast', title='Chị Hoa mua bánh mì cho cả ca', emoji='🥖', npc=HOA, min_day=2, tone='gentle', at='open', weight=2, mods=None,
         text='Đầu ca, chị Hoa đặt túi bánh mì lên bàn trực: “Ăn đi rồi đi buồng. Đói bụng là dễ sót việc.”',
         options=[dict(id='eat', label='Ăn nhanh ở phòng trực, rửa tay rồi vào ca', hint='', effects=dict(xp=3), good=True,
                       outcome='No bụng, đầu óc tỉnh táo. Chị Hoa gật gù.'),
                  dict(id='skip', label='Thôi, vào làm luôn cho kịp', hint='', effects=dict(patience=-2), good=None,
                       outcome='Mười giờ bụng réo, tay hơi run khi đo huyết áp.'),
                  dict(id='ward', label='Mang bánh mì vào ăn ở phòng bệnh', hint='', effects={}, good=False,
                       outcome='Chị Hoa nhắc: không ăn uống ở khu chăm sóc người bệnh.')],
         default='eat'),
    dict(id='flu_mask', title='Người nhà ho không đeo khẩu trang', emoji='😷', npc=MY, min_day=3, tone='gentle', at='between', weight=2, mods=('flu', 'busy'),
         text='Một anh người nhà ho sù sụ, không khẩu trang, ngồi sát giường bà Tư đang viêm phổi.',
         options=[dict(id='mask', label='Đưa khẩu trang, mời ngồi xa giường, nhắc rửa tay', hint='', effects=dict(xp=4), good=True,
                       outcome='Anh người nhà đeo khẩu trang ngay, còn xin thêm cái cho vợ.'),
                  dict(id='scold', label='“Ho vậy mà còn vào thăm?”', hint='', effects=dict(review=[2, 'Bị y tá nói như tôi mang dịch vào.', MY]), good=False,
                       outcome='Anh người nhà bỏ ra ngoài, đập cửa hơi mạnh.'),
                  dict(id='ignore', label='Kệ, ai cũng ho mùa này', hint='', effects=dict(patience=-3), good=None,
                       outcome='Tối đó bà Tư ho nhiều hơn.')],
         default='ignore'),
]

# ---------------------------------------------------------------- situations (sit_ engine)
SITUATIONS = [
    dict(id='DD-S01', title='Phong bì “bồi dưỡng”', npc=NGAN, tone='gentle', min_day=1,
         opening='Ngày ông Bảy ra viện, chị Ngân dúi vào túi áo bạn một phong bì: “Chút lòng thành, em cầm uống cà phê.”',
         swap='Bạn là chị Ngân: thấy điều dưỡng chăm bố mình chu đáo, muốn cảm ơn bằng cách quen thuộc nhất.',
         facts=[dict(id='rule', title='Quy định', source='Bảng nội quy khoa', text='Nhân viên y tế không nhận tiền, quà của người bệnh, người nhà.'),
                dict(id='heart', title='Tấm lòng', source='Chị Ngân', text='Chị Ngân thật lòng muốn cảm ơn, không đòi hỏi gì thêm.'),
                dict(id='book', title='Cách cảm ơn khác', source='Chị Hoa', text='Khoa có sổ góp ý, cảm ơn; một lá thư khen gửi phòng Điều dưỡng được đọc trong giao ban.')],
         options=[dict(id='decline', label='Cảm ơn thật lòng, trả lại phong bì, gợi ý viết vài dòng vào sổ góp ý', requires=['rule', 'book'], quality='good', stars=5,
                       review='Cô điều dưỡng không nhận phong bì, chỉ mong mình ghi vài dòng. Cả nhà quý lắm.',
                       outcome='Chị Ngân viết một trang dài vào sổ. Giao ban sáng thứ hai, chị Hoa đọc to.',
                       perspectives=[dict(who='Chị Ngân', emoji='📱', text='Ngại ghê, mà thấy người ta đàng hoàng thiệt.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Lời khen trong sổ quý hơn phong bì nhiều.')]),
                  dict(id='fund', label='Nhận rồi bỏ vào quỹ chung của khoa', requires=['heart'], quality='bad', stars=2,
                       review='Đưa thì nhận, nói là bỏ quỹ khoa. Ai biết được.',
                       outcome='Quỹ “chung” thành chuyện riêng. Phòng điều dưỡng hỏi tới.',
                       perspectives=[dict(who='Chị Ngân', emoji='🤔', text='Vậy là nhận rồi còn gì.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Không nhận nghĩa là không nhận, đổi tên gọi cũng vậy.')]),
                  dict(id='take', label='Nhận cho chị vui', quality='bad', stars=1,
                       review='Thì ra ở đây phải có phong bì mới được chăm kỹ.',
                       outcome='Người nhà giường bên thấy hết, hôm sau ai cũng hỏi “gửi bao nhiêu thì được”.',
                       perspectives=[dict(who='Người nhà giường bên', emoji='👀', text='Không có phong bì chắc bị bỏ rơi quá.'),
                                     dict(who='Chị Hoa', emoji='😞', text='Một phong bì làm mất lòng tin của cả phòng.')])],
         lesson='Không nhận phong bì; lời cảm ơn có chỗ của nó: sổ góp ý, thư khen.'),
    dict(id='DD-S02', title='Hai bà Tư trong một khoa', npc=TU, tone='tense', min_day=2,
         opening='Khoa nhận thêm bà Trần Thị Tứ giường 4. Phiếu thuốc trưa của hai bà nằm cạnh nhau trên xe tiêm.',
         facts=[dict(id='names', title='Hai cái tên', source='Bảng phân giường', text='Trần Thị Tư (1944, giường 3) và Trần Thị Tứ (1949, giường 4).'),
                dict(id='band', title='Vòng tay', source='Vòng đeo tay', text='Vòng tay ghi họ tên, ngày sinh và mã người bệnh, không ghi số giường.'),
                dict(id='hear', title='Tai bà Tư', source='Ghi chú giao ca', text='Bà Tư lãng tai, hỏi gì cũng “ờ, phải”.')],
         options=[dict(id='two', label='Hỏi họ tên và ngày sinh, đối chiếu vòng tay; báo khoa dán cảnh báo “trùng tên” lên hai hồ sơ', requires=['names', 'band'], quality='good', stars=5,
                       review='Khoa có hai bà trùng tên mà không nhầm một lần nào. Dán cả cảnh báo trùng tên.',
                       outcome='Hai hồ sơ có nhãn “trùng tên”. Ca sau ai cũng nhìn thấy.',
                       perspectives=[dict(who='Bà Tư', emoji='👵', text='Hỏi ngày sinh hoài, mà thôi vậy là cẩn thận.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Hai thông tin, mỗi lần, mọi người bệnh.')]),
                  dict(id='call', label='Gọi “Bà Tư ơi” rồi đưa thuốc cho người dạ', requires=['hear'], quality='bad', stars=1,
                       review='Gọi tên một tiếng là đưa thuốc. Hên mà chưa nhầm.',
                       outcome='Bà Tứ cũng “dạ”. Suýt nữa thì nhầm thuốc.',
                       perspectives=[dict(who='Bà Tứ', emoji='👵', text='Ai gọi tôi cũng dạ, tưởng gọi mình.'),
                                     dict(who='Bác sĩ Khang', emoji='🩺', text='Cái tên không phải là cách nhận diện người bệnh.')]),
                  dict(id='bed', label='Phát thuốc theo số giường cho nhanh', quality='bad', stars=2,
                       review='Ca đêm đổi giường cho hai bà, sáng ra suýt phát nhầm.',
                       outcome='Đêm qua ca trực đổi giường vì quạt hỏng. Số giường không còn đúng người.',
                       perspectives=[dict(who='Điều dưỡng ca đêm', emoji='🌙', text='Tôi có ghi đổi giường trong sổ mà.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Số giường đổi được, ngày sinh thì không.')])],
         lesson='Nhận diện người bệnh bằng hai thông tin (họ tên, ngày sinh) đối chiếu vòng tay, không dùng số giường.'),
    dict(id='DD-S03', title='Người bệnh không muốn truyền dịch', npc=BAY, tone='gentle', min_day=2,
         opening='Ông Bảy kéo tay lại: “Truyền gì truyền hoài, sưng hết tay. Hôm nay tôi không truyền!”',
         facts=[dict(id='right', title='Quyền của người bệnh', source='Nội quy khoa', text='Người bệnh có quyền từ chối; điều dưỡng giải thích, báo bác sĩ, ghi hồ sơ.'),
                dict(id='why', title='Vì sao ông sợ', source='Hỏi ông Bảy', text='Hôm qua chỗ kim cũ sưng đau, ông nghĩ truyền thêm là hỏng tay.'),
                dict(id='doc', title='Bác sĩ', source='Bác sĩ Khang', text='Bác sĩ có thể xem lại chỗ kim, đổi vị trí hoặc đổi cách điều trị.')],
         options=[dict(id='listen', label='Hỏi vì sao ông ngại, xem chỗ kim, báo bác sĩ cùng ông bàn lại', requires=['right', 'why', 'doc'], quality='good', stars=5,
                       review='Không ép, hỏi han kỹ, mời bác sĩ tới bàn. Tôi đồng ý truyền ở tay kia.',
                       outcome='Bác sĩ Khang xem chỗ kim, đặt lại ở tay kia. Ông Bảy gật đầu.',
                       perspectives=[dict(who='Ông Bảy', emoji='👴', text='Được hỏi ý kiến thì tôi nghe.'),
                                     dict(who='Bác sĩ Khang', emoji='🩺', text='Từ chối là có lý do, hỏi ra là xong.')]),
                  dict(id='force', label='Nhờ người nhà giữ tay ông để truyền cho xong', quality='bad', stars=1,
                       review='Bị giữ tay bắt truyền như phạm nhân.', outcome='Ông Bảy giật kim ra, máu chảy đầy ga. Chị Ngân làm đơn khiếu nại.',
                       perspectives=[dict(who='Ông Bảy', emoji='😠', text='Tôi là người bệnh, không phải tù nhân.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Không bao giờ ép người bệnh bằng sức.')]),
                  dict(id='skip', label='Không truyền, cũng không báo ai', requires=['right'], quality='bad', stars=2,
                       review='Không truyền thì thôi, chẳng ai hỏi han gì.', outcome='Tới chiều bác sĩ mới biết, cả ngày điều trị bị lỡ.',
                       perspectives=[dict(who='Bác sĩ Khang', emoji='🩺', text='Từ chối thì báo anh, đừng im lặng.'),
                                     dict(who='Ông Bảy', emoji='👴', text='Tôi tưởng ai cũng biết rồi.')])],
         lesson='Tôn trọng quyền từ chối: hỏi lý do, giải thích, báo bác sĩ, ghi hồ sơ. Không ép.'),
    dict(id='DD-S04', title='Phiếu theo dõi “cho đẹp”', npc=HOA, tone='tense', min_day=3,
         opening='Gần giao ca, chị Thắm cùng ca đưa bạn xấp phiếu: “Giường 6, 7 ổn định mà, điền số đẹp giống hôm qua cho kịp.”',
         facts=[dict(id='paper', title='Phiếu theo dõi', source='Hồ sơ', text='Phiếu ghi dấu hiệu sinh tồn là căn cứ để bác sĩ quyết điều trị.'),
                dict(id='time', title='Thời gian', source='Đồng hồ', text='Đo hai giường mất khoảng mười phút.'),
                dict(id='last', title='Hôm qua', source='Sổ giao ca', text='Giường 6 hôm qua ổn định, nhưng đêm nay có lúc máy báo SpO2 thấp.')],
         options=[dict(id='measure', label='Đi đo thật hai giường, ghi đúng số; nói với chị Thắm vì sao', requires=['paper', 'time'], quality='good', stars=5,
                       review='Ca giao đúng số đo thật. Giường 6 có chỉ số lạ, báo bác sĩ kịp.',
                       outcome='SpO2 giường 6 đúng là hơi thấp. Bác sĩ cho thở oxy sớm.',
                       perspectives=[dict(who='Chị Thắm', emoji='😅', text='Ờ… may mà đo thật.'),
                                     dict(who='Cô Liên', emoji='😟', text='Ca sau biết mà theo dõi tôi kỹ.')]),
                  dict(id='copy', label='Chép số hôm qua cho kịp giờ', quality='bad', stars=1,
                       review='Phiếu ghi SpO2 98, mà lúc đó tôi đang thở khó.', outcome='Ca đêm đọc phiếu “ổn định”, không ai để ý giường 6.',
                       perspectives=[dict(who='Bác sĩ Khang', emoji='🩺', text='Số giả còn nguy hiểm hơn không có số.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Ghi khống là chuyện kỷ luật.')]),
                  dict(id='half', label='Đo giường 6, giường 7 chép số cũ', requires=['last'], quality='ok', stars=3,
                       review='Giường 6 được đo kỹ, giường 7 thì… ai biết.', outcome='May mà giường 7 ổn thật.',
                       perspectives=[dict(who='Chị Hoa', emoji='👩‍⚕️', text='Ổn là may, không phải là đúng.'),
                                     dict(who='Chị Thắm', emoji='😅', text='Thôi lần sau đo hết.')])],
         lesson='Chỉ ghi điều mình thật sự đo, thật sự làm. Phiếu theo dõi là căn cứ điều trị.'),
    dict(id='DD-S05', title='Thang thuốc của “thần y”', npc=TU, tone='gentle', min_day=3,
         opening='Ông Tám, người quen nhà bà Tư, xách vào một can thuốc nam: “Ngưng kháng sinh đi, uống cái này ba ngày là hết viêm phổi.”',
         facts=[dict(id='mix', title='Dùng chung', source='Bác sĩ Khang', text='Thuốc không rõ thành phần có thể tương tác với thuốc đang dùng hoặc gây dị ứng.'),
                dict(id='belief', title='Niềm tin', source='Bà Tư', text='Bà Tư tin ông Tám vì ông chữa đau lưng cho chồng bà ngày trước.'),
                dict(id='ask', title='Đường đúng', source='Chị Hoa', text='Muốn dùng gì thêm thì báo bác sĩ điều trị quyết.')],
         options=[dict(id='doctor', label='Không cho dùng lúc này, giải thích nhẹ nhàng, mời bác sĩ nói chuyện với gia đình', requires=['mix', 'ask'], quality='good', stars=5,
                       review='Không chê bai ông Tám, nói lý lẽ rõ ràng, có bác sĩ giải thích. Bà yên tâm.',
                       outcome='Bác sĩ Khang nói chuyện với ông Tám. Can thuốc mang về, hẹn khi nào khỏi bệnh sẽ hỏi lại.',
                       perspectives=[dict(who='Bà Tư', emoji='👵', text='Bác sĩ nói vậy thì bà nghe.'),
                                     dict(who='Ông Tám', emoji='🌿', text='Thôi thì để bác sĩ làm, tôi về.')]),
                  dict(id='mock', label='Cười: “Thần y gì, thuốc lá cây mà đòi chữa viêm phổi”', quality='bad', stars=2,
                       review='Y tá chế giễu người quen của mẹ tôi trước mặt bà.', outcome='Bà Tư tủi thân, đêm đó lén uống thuốc nam.',
                       perspectives=[dict(who='Bà Tư', emoji='😢', text='Người ta có lòng mà.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Chê người khác không làm người bệnh nghe mình hơn.')]),
                  dict(id='allow', label='Cho uống chút ít cho bà vui', requires=['belief'], quality='bad', stars=1,
                       review='Uống thuốc nam xong bà nổi mẩn khắp người.', outcome='Bà Tư nổi mẩn, phải ngưng cả thuốc đang dùng.',
                       perspectives=[dict(who='Bác sĩ Khang', emoji='🩺', text='Giờ không biết mẩn ngứa vì thuốc nào.'),
                                     dict(who='Bà Tư', emoji='😣', text='Ngứa quá trời.')])],
         lesson='Người nhà muốn dùng thêm gì thì báo bác sĩ quyết; giải thích tôn trọng, không chế giễu.'),
    dict(id='DD-S06', title='Clip quay trong phòng bệnh', npc=TUAN, tone='tense', min_day=2,
         opening='Clip Tuấn quay trong phòng bệnh có cả mặt ông cụ giường bên và bảng tên bệnh án. Clip đang lên xu hướng.',
         facts=[dict(id='privacy', title='Riêng tư', source='Nội quy', text='Không quay, đăng hình người bệnh khác khi chưa được đồng ý.'),
                dict(id='tuan', title='Tuấn', source='Hỏi Tuấn', text='Tuấn không cố ý, chỉ muốn kể chuyện nằm viện cho vui.'),
                dict(id='family', title='Nhà ông cụ', source='Con ông cụ', text='Con ông cụ gọi lên khoa, rất bức xúc.')],
         options=[dict(id='talk', label='Nói chuyện riêng với Tuấn, nhờ gỡ clip, báo chị Hoa để khoa xin lỗi gia đình ông cụ', requires=['privacy', 'tuan'], quality='good', stars=5,
                       review='Khoa xử lý nhanh, đàng hoàng. Clip gỡ trong mười phút.',
                       outcome='Tuấn gỡ clip, quay lại bản mới chỉ có tay mình bó bột. Nhà ông cụ nhận lời xin lỗi.',
                       perspectives=[dict(who='Tuấn', emoji='🤳', text='Em không nghĩ tới, sorry nha.'),
                                     dict(who='Con ông cụ', emoji='👨', text='Xử lý vậy là được.')]),
                  dict(id='ban', label='Tịch thu điện thoại của Tuấn tới lúc ra viện', quality='bad', stars=2,
                       review='Bị lấy điện thoại như học sinh.', outcome='Tuấn làm clip mới “bị y tá tịch thu điện thoại”, còn hot hơn.',
                       perspectives=[dict(who='Tuấn', emoji='😤', text='Ủa quyền gì vậy?'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Không ai được lấy đồ của người bệnh.')]),
                  dict(id='none', label='Không phải việc của khoa', quality='bad', stars=1,
                       review='Khoa để người bệnh bị quay đăng lên mạng mà không làm gì.', outcome='Nhà ông cụ khiếu nại lên giám đốc bệnh viện.',
                       perspectives=[dict(who='Con ông cụ', emoji='😠', text='Bố tôi nằm viện chứ không phải đóng phim.'),
                                     dict(who='Chị Hoa', emoji='👩‍⚕️', text='Riêng tư của người bệnh là việc của mình.')])],
         lesson='Giữ riêng tư cho mọi người bệnh trong phòng: không quay, không đăng khi chưa được đồng ý.'),
]

# ---------------------------------------------------------------- the awkward people (air_odd engine: one script = one person)
# Shapes: see game/careers/air_odd_content.py. Harassment and seduction stay PG-13; giving in is never rewarded.
ODD = [
    # --- charm: gifts, flirting, favours that come with strings
    dict(id='dd-zalo', kind='charm', rank='pax', emoji='📱', title='“Cho anh xin số Zalo”', who='Anh Long · con trai người bệnh giường 2',
         text='“Em điều dưỡng ơi, cho anh xin số Zalo đi. Tối anh mời em đi ăn lẩu, cảm ơn em chăm ba anh 😉”',
         push=['“Có số thôi mà, anh hỏi thăm ba anh cho tiện.”', '“Khó gần vl. Thôi cho anh cái Facebook cũng được.”'],
         persist=(1, 3), mood=(0, 1), weight=3,
         words={'alt': 'Có gì về ba anh, anh gọi số trực của khoa nhé.'},
         back='Anh Long gãi đầu: “Ờ… vậy anh gọi số khoa.” Rồi quay vào ngồi với ba.',
         give='Bạn cho số. Tối đó anh Long nhắn hai mươi tin, có tin hỏi luôn “bệnh án ba anh có gì giấu không”.'),
    dict(id='dd-envelope', kind='charm', rank='pax', emoji='✉️', title='Phong bì “uống cà phê”', who='Bà Hạnh · người nhà giường 7',
         text='Bà Hạnh nắm tay bạn, dúi một phong bì: “Nhận cho bà vui, cháu chăm ông nhà bà chu đáo quá.”',
         push=['“Ai cũng nhận mà cháu, có gì đâu.”', '“Không nhận là chê bà nghèo à?”'],
         persist=(1, 3), mood=(0, 1), weight=3,
         words={'rule': 'Bệnh viện không cho nhân viên nhận phong bì.', 'alt': 'Bà ghi vài dòng vào sổ góp ý là cháu vui lắm rồi.'},
         back='Bà Hạnh cất phong bì, cười hiền: “Ừ, vậy bà viết thư khen.”',
         give='Bạn nhận. Người nhà giường bên thấy hết, hôm sau cả phòng hỏi nhau “gửi bao nhiêu thì được chăm kỹ”.'),
    dict(id='dd-rep', kind='charm', rank='pax', emoji='🎁', title='Trình dược viên “dễ thương”', who='Chị Kiều · trình dược viên công ty thuốc',
         text='Chị Kiều đặt túi quà lên bàn trực: “Em nhắc bác sĩ kê thuốc bên chị nha, cuối tháng chị không quên em đâu 😉”',
         push=['“Quà nhỏ thôi mà, ai mà không nhận.”', '“Không giúp thì thôi, chị nói với trưởng khoa là em khó tính.”'],
         persist=(1, 2), mood=(0, 2), weight=2,
         words={'rule': 'Thuốc kê theo bệnh, không theo quà.', 'alt': 'Chị gặp phòng vật tư theo đúng đường nhé.'},
         back='Chị Kiều xách túi quà đi, lầm bầm “nghiêm túc ghê”.',
         give='Bạn nhận quà và nói khéo với bác sĩ. Hai tuần sau thanh tra dược hỏi tới tên bạn.'),
    dict(id='dd-karaoke', kind='charm', rank='boss', emoji='🎤', title='Rủ đi karaoke đổi lịch trực', who='Anh Quý · phó phòng hành chính',
         text='“Tối nay đi hát với anh, chỉ hai đứa. Mai anh xếp lịch trực đẹp cho em cả tháng.”',
         push=['“Anh nói rồi đó, lịch trực tháng sau nằm trong tay anh.”', '“Em nghĩ kỹ đi. Người khác muốn còn không được.”'],
         persist=(2, 3), mood=(0, 1), weight=2,
         words={'rule': 'Lịch trực xếp theo quy định khoa, không đổi bằng cuộc hẹn.', 'alt': 'Em cảm ơn anh, tối em bận rồi.'},
         back='Anh Quý cười nhạt: “Cứng ghê.” Lịch trực tháng sau vẫn đúng như khoa xếp.',
         give='Bạn đi hát. Cả bệnh viện đồn ầm, phòng tổ chức mời bạn lên “nói chuyện”.'),
    dict(id='dd-tiktok', kind='charm', rank='pax', emoji='🎬', title='Quay clip “một ngày làm y tá”', who='Mi Mi · TikToker nằm phòng dịch vụ',
         text='“Chị ơi quay clip chung nha, mặc đồ điều dưỡng nhảy trend một tí thôi, triệu view đó!”',
         push=['“Chút xíu thôi mà, bệnh viện còn phải cảm ơn em quảng bá.”', '“Không quay thì em quay chị từ chối, cho mạng xã hội phán xử nha 🙃”'],
         persist=(2, 3), mood=(0, 2), weight=2,
         words={'rule': 'Không quay clip giải trí trong khu điều trị.', 'alt': 'Cần quay gì thì liên hệ phòng truyền thông nhé.'},
         back='Mi Mi thả icon lè lưỡi. Clip vẫn lên, chỉ có cảnh cổng bệnh viện.',
         give='Bạn nhảy trend giữa hành lang. Clip có cả người bệnh nằm phía sau, phòng điều dưỡng gọi lên.'),
    dict(id='dd-flirt9', kind='charm', rank='pax', emoji='😍', title='“Tay em mát quá”', who='Anh Cường · người bệnh giường 9',
         text='Lúc bạn đo huyết áp, anh Cường cười: “Tay em mát quá, đo thêm lần nữa đi, tim anh đập nhanh rồi nè 😍”',
         push=['“Ra viện anh mời em đi cà phê nha, anh nghiêm túc đó.”', '“Lạnh lùng vậy, anh buồn là huyết áp lên đó.”'],
         persist=(0, 2), mood=(0, 1), weight=2,
         words={'duty': 'Em đang làm việc, anh nằm yên để em đo cho đúng.', 'alt': 'Chúc anh mau khỏe.'},
         back='Anh Cường cười trừ, nằm im cho đo. Số đo lần này đẹp hẳn.',
         give='Bạn nhận lời cà phê. Anh Cường kể với cả phòng là “có bồ điều dưỡng”, chị Hoa nghe được.'),
    # --- harassment: never the nurse's fault; reporting is always right
    dict(id='dd-drunk', kind='harass', rank='pax', emoji='🍺', title='Khách say quậy ca tối', who='Ông khách say · người nhà giường 4',
         text='Ca tối, một ông người nhà nồng nặc mùi rượu chặn cửa phòng, nắm cổ tay bạn: “Em gái lại đây ngồi với anh tí, làm gì mà làm giá.”',
         push=['“Anh nói chuyện đàng hoàng mà, sợ gì.”', 'Ông ta đứng chắn lối đi, giọng to dần: “Y tá gì mà kiêu!”'],
         persist=(2, 3), mood=(1, 2), weight=3,
         words={'stop': 'Buông tay ra. Ngay.', 'rule': 'Quấy rối nhân viên y tế là vi phạm, tôi gọi bảo vệ.', 'duty': 'Tôi đang trực, ông về chỗ.'},
         back='Ông ta buông tay, lảo đảo đi ra hành lang. Chị Hoa vỗ vai bạn: “Lần sau cứ gọi bảo vệ ngay.”',
         report='Bảo vệ lên trong hai phút, mời ông ta ra khỏi khoa, lập biên bản. Gia đình giường 4 xin lỗi bạn.',
         stuck='Ông ta lải nhải tới khuya rồi mới về. Không ai ghi lại gì. Không phải lỗi của bạn: gọi bảo vệ là quyền của bạn.',
         give='Không ai được “chiều” kẻ quấy rối. Bạn né được, nhưng cả ca tối run tay.', follow='drunk_back'),
    dict(id='dd-drunk2', kind='harass', rank='pax', emoji='🍾', title='Ông khách say quay lại', who='Ông khách say · người nhà giường 4',
         text='Ông người nhà say hôm trước lại tới, cầm chai bia: “Hôm trước em làm anh quê, giờ phải uống với anh một ly mới xong.”',
         push=['“Một ly thôi, không thì đừng hòng anh về.”', 'Ông ta đập chai xuống bàn trực.'],
         persist=(2, 3), mood=(2, 2), weight=4, need_mark='drunk_back',
         words={'stop': 'Dừng lại. Tôi gọi bảo vệ.', 'rule': 'Mang rượu vào khoa là vi phạm.'},
         back='Ông ta đi ra, chai bia để lại trên bàn. Bạn cất vào phòng trực, ghi sổ.',
         report='Lần này bảo vệ cấm ông ta vào khoa sau 20 giờ. Biên bản có đủ hai lần.',
         stuck='Ông ta ngồi lì tới khi người nhà kéo về. Lần sau gọi bảo vệ ngay nhé.',
         give='Không ai được bắt bạn chiều kẻ say. Bạn nên báo ngay.', follow='drunk_back'),
    dict(id='dd-remarks', kind='harass', rank='pax', emoji='🙄', title='Lời khiếm nhã lúc đo huyết áp', who='Anh Cường · người bệnh giường 9',
         text='Anh Cường nói to cho cả phòng nghe: “Mai em mặc váy ngắn đi làm đi, anh khỏe liền.” Mấy người cười khẩy.',
         push=['“Nói đùa thôi mà, căng vậy.”', '“Y tá mà không biết đùa thì làm nghề gì.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'stop': 'Anh dừng kiểu nói đó lại.', 'rule': 'Nói vậy với nhân viên là quấy rối.'},
         back='Anh Cường im, mấy người cười khẩy cũng quay đi. Cô điều dưỡng giường bên giơ ngón cái.',
         report='Chị Hoa nói chuyện riêng với anh Cường, ghi vào sổ khoa. Từ đó anh nói năng đàng hoàng.',
         stuck='Anh ta vẫn buông lời vài lần nữa. Không phải lỗi của bạn: báo là quyền của bạn.',
         give='Bạn cười cho qua, anh ta càng được đà. Lần sau cứ báo chị Hoa.'),
    dict(id='dd-intern', kind='harass', rank='crew', emoji='🧑‍⚕️', title='Đồng nghiệp trêu bạn thực tập', who='Anh Dũng · hộ lý khoa bên',
         text='Bạn thấy anh Dũng ép cô thực tập sinh vào góc kho: “Tối nay đi chơi với anh, không thì anh báo em làm sai đó.”',
         push=['“Chuyện tụi anh, em xen vô làm gì?”', '“Báo đi, ai tin con nhỏ thực tập?”'],
         persist=(2, 3), mood=(1, 2), weight=2,
         words={'stop': 'Anh để bạn ấy đi.', 'rule': 'Ép buộc như vậy là quấy rối, khoa có quy trình.', 'duty': 'Em cần bạn ấy phụ ca ngay.'},
         back='Anh Dũng bỏ đi. Cô thực tập run run cảm ơn bạn.',
         report='Bạn đi cùng cô thực tập lên phòng tổ chức. Anh Dũng bị đình chỉ để xác minh; cô bé được chuyển ca an toàn.',
         stuck='Anh Dũng đi rồi nhưng cô bé sợ không dám kể ai. Lần sau đi báo cùng bạn ấy.',
         give='Bạn quay đi. Cô bé thực tập nghỉ ngang tuần sau.'),
    dict(id='dd-creep', kind='harass', rank='pax', emoji='📷', title='Quay lén điều dưỡng', who='Một thanh niên ở hành lang',
         text='Bạn thấy một thanh niên giơ điện thoại quay lén chân các chị điều dưỡng đang cúi thay ga giường.',
         push=['“Quay cảnh bệnh viện thôi mà, ai cấm.”', 'Anh ta bỏ điện thoại vào túi, định chuồn.'],
         persist=(1, 2), mood=(1, 2), weight=2,
         words={'stop': 'Anh dừng quay, xóa ngay.', 'rule': 'Quay lén người khác là vi phạm, bảo vệ sẽ xem.'},
         back='Anh ta xóa clip trước mặt bạn rồi đi thẳng.',
         report='Bảo vệ giữ anh ta lại, kiểm tra điện thoại, lập biên bản. Các chị trong khoa cảm ơn bạn.',
         stuck='Anh ta chuồn mất. Clip đi đâu không ai biết. Lần sau gọi bảo vệ ngay.',
         give='Bạn làm lơ cho đỡ phiền. Clip lên một nhóm kín tối hôm đó.'),
    dict(id='dd-threat', kind='harass', rank='pax', emoji='😡', title='Người nhà dọa đánh', who='Anh Thành · người nhà giường 1',
         text='Anh Thành đập bàn trực: “Mẹ tao đau mà tụi mày chậm như rùa! Tao đánh mày bây giờ!”',
         push=['Anh ta giơ tay lên, mặt đỏ gay.', '“Gọi ai thì gọi, tao không sợ!”'],
         persist=(2, 3), mood=(2, 2), weight=2,
         words={'stop': 'Anh bình tĩnh, lùi lại.', 'rule': 'Hành hung nhân viên y tế là phạm luật.', 'duty': 'Em đang báo bác sĩ cho mẹ anh.'},
         back='Anh Thành lùi lại, thở hồng hộc. Bạn hẹn giờ bác sĩ tới, anh ngồi xuống chờ.',
         report='Bảo vệ đứng cạnh suốt lúc anh Thành nói chuyện với bác sĩ. Biên bản ghi rõ lời đe dọa.',
         stuck='Anh ta la hét tới lúc bác sĩ tới. Không ai ghi lại. Lần sau giữ khoảng cách và gọi bảo vệ.',
         give='Bạn xin lỗi rối rít như thể lỗi của mình. Anh ta càng lớn tiếng với ca sau.'),
    # --- corners cut: say it, then report (no-blame)
    dict(id='dd-hands', kind='corner', rank='crew', emoji='🧤', title='“Đeo găng rồi khỏi rửa tay”', who='Chị Thắm · điều dưỡng cùng ca',
         text='“Đeo găng rồi thì khỏi sát khuẩn tay, mỗi lần mười giây, cả ngày mất cả tiếng đó em.”',
         push=['“Chị làm mười năm có ai sao đâu.”', '“Chậm vl, ca này mình còn hai chục giường.”'],
         persist=(1, 3), mood=(0, 1), weight=3, severe=2,
         words={'rule': 'Găng tay không thay được rửa tay.', 'alt': 'Chai sát khuẩn treo ở đầu mỗi giường, mất có vài giây.'},
         back='Chị Thắm cằn nhằn nhưng vẫn bóp chai sát khuẩn. Đoàn kiểm tra chiều đó chấm khoa điểm tối đa.',
         give='Hai người bỏ qua sát khuẩn. Tuần sau ba giường cùng phòng bị nhiễm khuẩn vết loét.'),
    dict(id='dd-fakechart', kind='corner', rank='crew', emoji='📝', title='“Ghi đại số đẹp”', who='Chị Thắm · điều dưỡng cùng ca',
         text='“Mấy giường ổn định mà, ghi đại số đẹp giống hôm qua vào phiếu, khỏi đo cho kịp giao ca.”',
         push=['“Ai mà kiểm tra từng số.”', '“Em mới vào mà làm như thanh tra.”'],
         persist=(1, 3), mood=(0, 1), weight=3, severe=3,
         words={'speak': 'Phiếu là căn cứ điều trị, phải đo thật.', 'alt': 'Mình chia nhau đo, mười phút là xong.'},
         back='Chị Thắm thở dài, cầm máy đo đi cùng bạn. Giường 6 có chỉ số lạ, báo kịp.',
         give='Bạn ghi khống. Đêm đó giường 6 khó thở, ca đêm đọc phiếu “ổn định” nên phát hiện trễ.'),
    dict(id='dd-sign', kind='corner', rank='crew', emoji='✍️', title='Ký thay phiếu thuốc', who='Anh Tiến · điều dưỡng ca trước',
         text='“Em ký giùm anh mấy dòng thuốc sáng nay, anh quên ký. Anh cho thuốc rồi mà, tin anh đi.”',
         push=['“Anh em cùng khoa mà không tin nhau à?”', '“Ký chút xíu thôi, không thì anh bị nhắc nhở.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=3,
         words={'speak': 'Ai làm thì người đó ký.', 'alt': 'Anh quay lại ký, ghi rõ giờ ký bổ sung.'},
         back='Anh Tiến quay lại tự ký, ghi rõ giờ ký bổ sung. Hóa ra một dòng anh chưa cho thật.',
         give='Bạn ký thay. Một dòng thuốc anh Tiến chưa hề cho, giờ phiếu ghi tên bạn.'),
    dict(id='dd-phone', kind='corner', rank='boss', emoji='☎️', title='Y lệnh qua điện thoại', who='Bác sĩ Lâm · bác sĩ trực (gọi điện)',
         text='“Giường 5 cho thêm một ống thuốc như hôm qua, em làm luôn đi, mai anh ghi y lệnh sau.”',
         push=['“Anh bận, nói một lần thôi. Làm đi.”', '“Em không tin bác sĩ à?”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=2,
         words={'speak': 'Anh đọc lại tên thuốc, đường dùng giúp em, em nhắc lại để xác nhận.', 'rule': 'Y lệnh miệng phải nhắc lại và ghi ngay.',
                'alt': 'Em ghi y lệnh miệng, anh ký bổ sung khi tới khoa.'},
         back='Bác sĩ Lâm đọc lại rõ ràng, bạn nhắc lại, ghi giờ. Sáng ra anh ký bổ sung ngay.',
         give='Bạn làm theo câu “như hôm qua”. Hôm qua là thuốc khác. Phải báo cáo sự cố.'),
    dict(id='dd-reuse', kind='corner', rank='crew', emoji='💉', title='Dùng lại bơm tiêm', who='Chị Thắm · điều dưỡng cùng ca',
         text='“Khoa đang thiếu bơm tiêm, cái này mới dùng hút thuốc một lần, rửa sạch dùng tiếp đi em.”',
         push=['“Có ai biết đâu.”', '“Hết bơm tiêm thì lấy gì làm, em nghĩ đi.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=4,
         words={'speak': 'Đồ dùng một lần là một lần.', 'alt': 'Em lên khoa bên mượn, ghi phiếu báo thiếu.'},
         back='Chị Thắm gật đầu. Bạn chạy sang khoa bên mượn một hộp, ghi phiếu báo thiếu vật tư.',
         give='Hai người dùng lại bơm tiêm. Chuyện này mà lộ ra là cả khoa lên báo.'),
    dict(id='dd-noid', kind='corner', rank='crew', emoji='🪪', title='“Giường 5 thì là ông Bảy”', who='Chị Thắm · điều dưỡng cùng ca',
         text='“Giường 5 thì là ông Bảy chứ ai, hỏi tên với ngày sinh làm gì cho mất công. Phát thuốc lẹ lên.”',
         push=['“Ông ấy nằm đó cả tuần rồi.”', '“Hỏi hoài người ta khó chịu đó em.”'],
         persist=(1, 3), mood=(0, 1), weight=3, severe=2,
         words={'speak': 'Đêm qua có đổi giường không chị?', 'rule': 'Hai thông tin trước mỗi lần cho thuốc.'},
         back='Chị Thắm lật sổ giao ca: đêm qua đổi giường thật. Ông Bảy giờ nằm giường 7.',
         give='Bạn phát theo số giường. Đêm qua đổi giường vì quạt hỏng. Phải viết báo cáo sự cố.'),
    dict(id='dd-cover', kind='corner', rank='crew', emoji='🤫', title='“Đừng báo nhé”', who='Anh Tiến · điều dưỡng ca trước',
         text='“Anh lỡ cho giường 3 uống thuốc trễ hai tiếng. Em đừng báo nhé, bà cụ có sao đâu.”',
         push=['“Báo lên anh bị kỷ luật đó.”', '“Anh em với nhau mà.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=3,
         words={'speak': 'Mình báo bác sĩ xem bà cần theo dõi gì.', 'alt': 'Anh tự viết báo cáo, khoa không phạt người tự báo.'},
         back='Anh Tiến tự viết báo cáo. Chị Hoa cảm ơn, không phạt ai, còn sửa lại giờ nhắc thuốc cho cả khoa.',
         report='Bạn gửi báo cáo sự cố tự nguyện (không nêu tên để phạt). Khoa đổi lịch nhắc thuốc; bác sĩ theo dõi bà Tư thêm.',
         give='Bạn im lặng. Ca sau không biết, cho bà thêm liều đúng giờ cũ. Bác sĩ Khang phải theo dõi bà sát cả đêm.'),
    dict(id='dd-alarm', kind='corner', rank='crew', emoji='🔕', title='Tắt chuông báo máy theo dõi', who='Chị Thắm · điều dưỡng cùng ca',
         text='“Máy theo dõi giường 3 kêu hoài điếc tai, em tắt chuông báo đi cho yên.”',
         push=['“Nó báo giả hoài mà.”', '“Người nhà phàn nàn ồn đó.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=3,
         words={'speak': 'Máy báo thì mình xem người bệnh trước.', 'alt': 'Chỉnh lại kẹp ngón, dây đo cho đúng thì hết báo giả.'},
         back='Bạn chỉnh lại kẹp ngón. Máy hết báo giả, chuông vẫn bật.',
         give='Chuông tắt. Hai giờ chiều SpO2 bà Tư tụt mà không ai hay.'),
    # --- awkward, pushy, strange demands
    dict(id='dd-bestdoc', kind='demand', rank='pax', emoji='🏅', title='“Bác sĩ giỏi nhất”', who='Chị Ngân · con gái ông Bảy',
         text='“Đổi cho bố chị bác sĩ giỏi nhất khoa đi, giáo sư gì đó. Tiền không thành vấn đề!”',
         push=['“Chị quen phó giám đốc đó nha. Gọi một cuộc là xong.”', '“Bác sĩ trẻ quá, chị không tin.”'],
         persist=(2, 3), mood=(1, 2), weight=3, npc=NGAN,
         words={'alt': 'Em báo bác sĩ điều trị tới giải thích kế hoạch cho chị.', 'rule': 'Khoa phân bác sĩ theo bệnh, ai cũng được chăm như nhau.'},
         back='Chị Ngân ngồi nghe bác sĩ Khang giải thích hai mươi phút, cuối cùng gật gù: “Ờ, cũng được.”',
         give='Bạn hứa “để em xin đổi”. Chẳng ai đổi được, chị Ngân thấy bị lừa.',
         review={'back': [4, 'Không đổi được bác sĩ nhưng được giải thích kỹ, yên tâm.'], 'give': [2, 'Hứa đổi bác sĩ rồi im luôn.']}),
    dict(id='dd-bribe', kind='demand', rank='pax', emoji='💵', title='500 xu đổi giường đẹp', who='Anh Hào · người nhà người bệnh mới',
         text='Anh Hào kẹp tờ 500 xu dưới xấp hồ sơ: “Xếp cho mẹ anh giường gần cửa sổ, cho ông cụ kia ra hành lang.”',
         push=['“Thêm 500 nữa nha. Không ai biết đâu.”', '“Ở đây ai chẳng có giá, đừng làm giá.”'],
         persist=(2, 3), mood=(0, 1), weight=3, breach=4,
         words={'rule': 'Giường xếp theo bệnh, không theo tiền.', 'no': 'Em không nhận, anh cất tiền lại.',
                'alt': 'Có giường trống gần cửa sổ em báo anh ngay.'},
         back='Anh Hào cất tiền, lầm bầm. Chiều có giường trống thật, mẹ anh được chuyển đúng lượt.',
         give='Bạn nhận tiền, đẩy ông cụ ra hành lang. Con ông cụ quay clip, tối đó cả phường biết.'),
    dict(id='dd-vip', kind='demand', rank='pax', emoji='👑', title='“Dọn một phòng riêng ra”', who='Bà Diệu · vợ một “sếp lớn”',
         text='“Chồng tôi không nằm chung với ai. Hết phòng dịch vụ thì dọn một phòng ra, chuyển mấy người kia đi.”',
         push=['“Cô có biết chồng tôi là ai không?”', '“Tôi gọi giám đốc là cô mất việc.”'],
         persist=(2, 3), mood=(1, 2), weight=2, breach=2,
         words={'alt': 'Em đăng ký phòng dịch vụ, có phòng trống em báo bà ngay.', 'rule': 'Không chuyển người bệnh khác đi vì ai cả.'},
         back='Bà Diệu hừ một tiếng rồi ngồi xuống. Tối có phòng dịch vụ trống, ông được chuyển đúng lượt.',
         give='Bạn chuyển ba người bệnh ra hành lang. Cả khoa bị giám đốc gọi lên.'),
    dict(id='dd-visitors', kind='demand', rank='pax', emoji='👨‍👩‍👧‍👦', title='Cả họ vào thăm', who='Gia đình ông Bảy · bảy người',
         text='Bảy người nhà ông Bảy kéo vào, xách mâm cơm và cái loa: “Cả họ vào thăm, cho vào hết, mở nhạc cho ông vui!”',
         push=['“Ở quê lên mà, cho vào chút xíu.”', '“Khoa gì khó như quân đội.”'],
         persist=(1, 3), mood=(0, 2), weight=3, breach=1, fx={'give': {'patience': -10}},
         words={'alt': 'Mỗi lần hai người, cả nhà thay phiên, ngồi phòng chờ.', 'rule': 'Giờ thăm mỗi giường hai người, không mở nhạc.'},
         back='Cả nhà chia phiên. Ông Bảy được gặp đủ bảy người, phòng vẫn yên tĩnh cho giường khác ngủ.',
         give='Bảy người, mâm cơm, loa nhạc. Bà Tư giường bên không ngủ được, ho cả buổi.'),
    dict(id='dd-herbs', kind='demand', rank='pax', emoji='🌿', title='“Thần y” mang thuốc nam', who='Ông Tám · người quen nhà bà Tư',
         text='“Ngưng thuốc tây đi, uống thang này ba ngày là hết. Tôi chữa khỏi cả trăm người rồi.”',
         push=['“Bác sĩ tây biết gì thuốc nam.”', '“Cô ngăn là cô chịu trách nhiệm nếu bà không khỏi nha.”'],
         persist=(2, 3), mood=(1, 2), weight=3, breach=3,
         words={'alt': 'Bác để em báo bác sĩ xem có dùng chung được không.', 'rule': 'Đang điều trị thì dùng gì thêm phải có bác sĩ đồng ý.',
                'why': 'Thang thuốc này có những vị gì ạ?'},
         back='Ông Tám xách can thuốc về, hẹn khi nào bà Tư khỏi sẽ hỏi bác sĩ.',
         give='Bà Tư uống thuốc nam, chiều nổi mẩn khắp người. Giờ không ai biết mẩn vì thuốc nào.'),
    dict(id='dd-peek', kind='demand', rank='pax', emoji='🗂️', title='Xin xem bệnh án hàng xóm', who='Chị Hằng · hàng xóm cô Liên',
         text='“Cho chị xem bệnh án cô Liên chút, chị là hàng xóm thân mà. Cô ấy bị gì nặng không?”',
         push=['“Có gì đâu mà giấu.”', '“Chị hỏi giùm cả xóm đó em.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Hồ sơ chỉ người bệnh và người được ủy quyền mới xem.', 'alt': 'Chị hỏi thẳng cô Liên nhé, cô muốn kể thì kể.'},
         back='Chị Hằng tự đi hỏi cô Liên. Cô Liên chỉ kể vừa đủ, chị Hằng cũng thôi.',
         give='Bạn kể sơ. Chiều đó cả xóm biết bệnh cô Liên, cô khóc cả tối.'),
    dict(id='dd-hide', kind='demand', rank='pax', emoji='🤐', title='“Đừng nói với mẹ anh”', who='Anh Quang · con trai bà Tư',
         text='“Đừng nói với mẹ anh là viêm phổi nặng nha. Cứ bảo cảm sơ thôi, mẹ anh yếu tim.”',
         push=['“Em nói ra mà mẹ anh có chuyện là em chịu.”', '“Nhà anh quyết rồi, em làm theo đi.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=1,
         words={'alt': 'Để bác sĩ cùng gia đình nói với bà, chọn cách nhẹ nhàng.', 'why': 'Anh lo điều gì nhất ạ?'},
         back='Bác sĩ Khang gặp anh Quang trước, rồi cùng nói với bà thật nhẹ nhàng. Bà Tư nghe xong chỉ hỏi: “Vậy bà phải uống thuốc mấy ngày?”',
         give='Bạn nói dối bà “cảm sơ”. Bà Tư không chịu nằm viện tiếp, đòi về.'),
    dict(id='dd-morepain', kind='demand', rank='pax', emoji='💊', title='“Cho em thêm thuốc giảm đau”', who='Tuấn · người bệnh giường 8',
         text='“Chị cho em thêm một liều giảm đau đi, em chịu hết nổi rồi bro.”',
         push=['“Có một viên thôi mà, chị lấy trong tủ đi.”', '“Chị không thương bệnh nhân hả?”'],
         persist=(1, 3), mood=(1, 2), weight=2, npc=TUAN, breach=3,
         words={'rule': 'Thuốc chỉ cho theo y lệnh bác sĩ.', 'alt': 'Em chấm điểm đau, xem tay rồi báo bác sĩ ngay.', 'why': 'Đau chỗ nào, kiểu gì?'},
         back='Bạn chấm đau, xem ngón tay, báo bác sĩ Khang. Bác sĩ tới khám và cho y lệnh phù hợp.',
         give='Bạn lấy thêm thuốc trong tủ trực. Không có y lệnh, chị Hoa phải lập biên bản.',
         review={'back': [5, 'Chị điều dưỡng không cho bừa mà gọi bác sĩ tới liền. Respect.'], 'give': [2, 'Được thêm thuốc mà chị điều dưỡng bị mắng, kỳ ghê.']}),
    dict(id='dd-smoke', kind='demand', rank='pax', emoji='🚬', title='Đòi ra cầu thang hút thuốc', who='Ông Bảy · người bệnh giường 5',
         text='“Cho tôi ra cầu thang hút một điếu, nằm cả tuần ngứa miệng quá.”',
         push=['“Một điếu thôi mà cô.”', '“Không cho thì tôi tự đi.”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=BAY, breach=1,
         words={'rule': 'Bệnh viện cấm hút thuốc, có bình oxy khắp khoa.', 'alt': 'Bác ra vườn đi dạo với cháu một vòng nhé.'},
         back='Ông Bảy lầm bầm nhưng chịu ra vườn đi dạo. Về còn khen gió mát.',
         give='Ông hút ở cầu thang, khói bay vào phòng có bình oxy. Bảo vệ lập biên bản.'),
    dict(id='dd-gohome', kind='demand', rank='pax', emoji='🏠', title='Đòi về khi chưa có giấy', who='Chị Ngân · con gái ông Bảy',
         text='“Cho bố chị về luôn bây giờ, bác sĩ ký giấy sau. Xe đợi dưới cổng rồi!”',
         push=['“Chị tự chịu trách nhiệm, được chưa?”', '“Giữ người ta như giữ tù vậy.”'],
         persist=(1, 3), mood=(1, 2), weight=2, npc=NGAN, breach=2,
         words={'alt': 'Em gọi bác sĩ khám lại và ký ngay, chị chờ mười phút.', 'rule': 'Chưa có giấy ra viện thì khoa chưa bàn giao người bệnh được.'},
         back='Bác sĩ Khang tới khám lại, ký giấy trong mười phút. Ông Bảy về với đủ đơn thuốc và lịch tái khám.',
         give='Ông Bảy về không giấy, không đơn. Hai hôm sau quay lại cấp cứu vì không biết uống thuốc gì.'),
    dict(id='dd-insure', kind='demand', rank='pax', emoji='🧾', title='Ghi thêm ngày nằm viện', who='Chị Ngân · con gái ông Bảy',
         text='“Em ghi thêm hai ngày nằm viện giùm chị, bảo hiểm trả nhiều hơn. Ai biết đâu.”',
         push=['“Có hai ngày thôi mà.”', '“Làm ơn mắc oán ghê.”'],
         persist=(1, 3), mood=(0, 1), weight=2, npc=NGAN, breach=4,
         words={'rule': 'Hồ sơ ghi đúng ngày, sửa là gian lận bảo hiểm.', 'alt': 'Em chỉ chị quầy BHYT hỏi các khoản được thanh toán.'},
         back='Chị Ngân ra quầy BHYT hỏi, hóa ra còn một khoản được thanh toán mà chị chưa biết.',
         give='Bạn sửa ngày. Cuối quý bảo hiểm đối chiếu, khoa bị xuất toán và bạn bị kỷ luật.'),
    dict(id='dd-film', kind='demand', rank='pax', emoji='🎥', title='“Tôi quay hết đây”', who='Anh Toàn · người nhà giường 1',
         text='Anh Toàn chĩa điện thoại sát mặt bạn: “Tôi quay hết đây, chị làm sai là lên mạng liền.”',
         push=['“Sợ gì mà không cho quay?”', '“Quay cả phòng cho mọi người thấy bệnh viện tệ cỡ nào.”'],
         persist=(1, 3), mood=(1, 2), weight=2, breach=1,
         words={'alt': 'Anh quay người nhà mình thôi, đừng quay người bệnh khác.', 'rule': 'Không quay người bệnh khác khi chưa được đồng ý.',
                'why': 'Anh đang lo điều gì, em giải thích luôn.'},
         back='Anh Toàn hạ máy, hỏi thẳng điều anh lo. Bạn giải thích từng bước, anh gật gù.',
         give='Anh Toàn quay cả phòng, có cả ông cụ đang thay đồ. Clip lên mạng, khoa xin lỗi mệt nghỉ.'),
    dict(id='dd-cutline', kind='demand', rank='pax', emoji='⏩', title='“Tôi quen giám đốc”', who='Bà Lụa · khách ở quầy tiếp đón',
         text='“Tôi quen giám đốc bệnh viện. Cho tôi khám trước, đứng chờ chi cho mỏi chân.”',
         push=['“Gọi giám đốc ra đây tôi nói chuyện.”', '“Cô biết tôi là ai không?”'],
         persist=(1, 3), mood=(1, 2), weight=3, breach=1, fx={'give': {'patience': -8}},
         words={'rule': 'Khám theo mức độ bệnh, ai nặng hơn vào trước.', 'alt': 'Em mời bà ngồi ghế, đo huyết áp cho bà trong lúc chờ.'},
         back='Bà Lụa ngồi xuống, đo huyết áp bình thường. Bà chờ đúng lượt, còn khen ghế êm.',
         give='Bạn cho bà Lụa vào trước. Ông cụ đau ngực đang ngồi im ở góc phải chờ thêm mười phút.'),
    dict(id='dd-noBP', kind='demand', rank='pax', emoji='😤', title='“Đo gì đo hoài”', who='Ông Bảy · người bệnh giường 5',
         text='Năm giờ sáng, ông Bảy giấu tay vào chăn: “Đo gì đo hoài! Hôm nay không cho đo!”',
         push=['“Tôi khỏe re, đo làm chi.”', '“Đánh thức người già lúc năm giờ là ác lắm.”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=BAY, breach=1,
         words={'why': 'Bác khó chịu chuyện gì nhất ạ?', 'alt': 'Con đo nhanh nửa phút, lần sau con hẹn bác đúng giờ dậy.',
                'rule': 'Bác sĩ cần số đo sáng để chỉnh thuốc tiểu đường.'},
         back='Ông Bảy chìa tay ra: “Nửa phút thôi đó.” Bạn ghi vào sổ giao ca: ông thích đo lúc sáu giờ.',
         give='Bạn bỏ qua lượt đo. Sáng đó bác sĩ chỉnh thuốc mà không có số đo.'),
    dict(id='dd-che', kind='demand', rank='pax', emoji='🍧', title='Lén mang chè cho ông Bảy', who='Chị Ngân · con gái ông Bảy',
         text='“Bố chị thèm chè quá, chị mang ba ly chè đậu ngọt lịm vào. Em đừng nói với ai nha.”',
         push=['“Ăn chút xíu có sao đâu.”', '“Ông già rồi, cho ông vui.”'],
         persist=(1, 3), mood=(0, 1), weight=2, npc=NGAN, breach=1,
         words={'alt': 'Em hỏi chị dinh dưỡng món ngọt nào ông dùng được.', 'why': 'Ông thèm món gì nhất ạ?'},
         back='Chị dinh dưỡng gợi ý chè hạt sen không đường. Ông Bảy ăn sạch, khen ngon.',
         give='Ông ăn ba ly chè. Chiều đường huyết vọt lên, bác sĩ Khang phải chỉnh thuốc.'),
    dict(id='dd-plug', kind='demand', rank='pax', emoji='🔌', title='Rút máy để sạc điện thoại', who='Người nhà giường 7',
         text='“Ổ cắm có một cái à? Rút phích máy hút đờm ra cho tôi sạc điện thoại chút, mười phút thôi.”',
         push=['“Máy đó đang có ai dùng đâu.”', '“Điện thoại tôi sắp tắt, có việc gấp.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=2,
         words={'rule': 'Ổ cắm đầu giường chỉ dành cho máy y tế.', 'alt': 'Phòng chờ có chỗ sạc chung, em chỉ anh.'},
         back='Người nhà ra phòng chờ sạc. Máy hút đờm vẫn cắm, nửa tiếng sau giường 7 cần dùng thật.',
         give='Bạn cho rút máy. Nửa tiếng sau giường 7 cần hút đờm gấp, máy không có điện.'),
    dict(id='dd-floor', kind='demand', rank='pax', emoji='🛏️', title='Năm người ngủ dưới gầm giường', who='Gia đình giường 4',
         text='“Cho cả nhà trải chiếu ngủ dưới gầm giường. Năm người thôi, về quê xa lắm.”',
         push=['“Ở viện khác người ta cho mà.”', '“Không cho thì cả nhà ngủ ngoài hành lang.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=1, fx={'give': {'patience': -8}},
         words={'alt': 'Một người ở lại với giường, cả nhà nghỉ ở nhà trọ người thân bệnh viện có danh sách.',
                'rule': 'Đêm chỉ một người nhà ở lại với người bệnh.'},
         back='Một người ở lại, cả nhà ra nhà trọ gần cổng giá rẻ trong danh sách của khoa.',
         give='Năm người nằm kín lối đi. Đêm đó ca trực vấp chân hai lần khi chạy tới giường 3.'),
    dict(id='dd-photo', kind='demand', rank='boss', emoji='📸', title='Dọn người nhà cho đẹp ảnh', who='Anh Quý · phó phòng hành chính',
         text='“Chiều nay đoàn khách tham quan. Dọn hết người nhà ra ngoài, giường nào xấu thì kéo rèm, chụp ảnh cho đẹp.”',
         push=['“Lệnh trên đó, em làm đi.”', '“Mất điểm thi đua là cả khoa chịu.”'],
         persist=(2, 3), mood=(0, 1), weight=2, breach=1,
         words={'alt': 'Em sắp xếp người nhà gọn gàng, người bệnh vẫn được ở cạnh người thân.', 'why': 'Đoàn muốn xem điều gì ạ?'},
         back='Đoàn đi qua, thấy khoa gọn gàng mà vẫn có người nhà ngồi bón cháo. Đoàn khen “rất thật”.',
         give='Người nhà bị đẩy ra ngoài nắng một tiếng. Bà Tư không có ai đỡ dậy uống nước.'),
    dict(id='dd-neighbour', kind='demand', rank='kin', emoji='👵', title='“Xem giùm bà toa thuốc”', who='Bà Sáu · hàng xóm trong hẻm',
         text='Tối về hẻm, bà Sáu chìa toa thuốc: “Cháu làm bệnh viện, xem giùm bà uống mấy viên, khỏi đi khám nữa.”',
         push=['“Có chút xíu mà không giúp bà.”', '“Đi khám tốn tiền lắm cháu.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=2,
         words={'alt': 'Mai bà ra nhà thuốc hỏi dược sĩ, hoặc đi khám lại cho chắc.', 'rule': 'Cháu không tự đổi thuốc của ai được.'},
         back='Bà Sáu hẹn mai ra quầy thuốc Bình An hỏi cô Thu.',
         give='Bạn đoán đại số viên. Hai hôm sau bà Sáu chóng mặt, con bà sang hỏi “ai bảo uống vậy”.'),
    dict(id='dd-sicknote', kind='demand', rank='kin', emoji='🗒️', title='Xin giấy nghỉ ốm giả', who='Dì Út · dì ruột (gọi điện)',
         text='“Con làm bệnh viện, xin giùm dì giấy nghỉ ốm ba ngày nha. Dì đi Đà Lạt với hội bạn.”',
         push=['“Người nhà mà không giúp.”', '“Ai chẳng làm vậy.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=4,
         words={'rule': 'Giấy tờ y tế giả là phạm luật.', 'alt': 'Dì xin nghỉ phép đàng hoàng đi, Đà Lạt vẫn còn đó.'},
         back='Dì Út càu nhàu rồi xin nghỉ phép. Về còn mang mứt dâu cho bạn.',
         give='Bạn nhờ người làm giấy. Công ty dì kiểm tra, giấy giả bị phát hiện, tên bạn trong biên bản.'),
    dict(id='dd-mommatch', kind='demand', rank='kin', emoji='💘', title='Mẹ làm mai bác sĩ', who='Mẹ bạn · gọi video',
         text='“Bác sĩ Khang còn độc thân không con? Mời cậu ấy về nhà ăn cơm, mẹ nấu canh chua.”',
         push=['“Mẹ chỉ hỏi thôi mà. Con gửi mẹ cái ảnh cậu ấy đi.”', '“Con lớn rồi, mẹ lo chứ.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'no': 'Con không mai mối đồng nghiệp đâu mẹ.', 'alt': 'Cuối tuần con về ăn canh chua với mẹ nha.', 'why': 'Mẹ lo chuyện gì vậy?'},
         back='Mẹ cười xòa: “Thôi được, cuối tuần về ăn cơm.”',
         give='Bạn gửi ảnh bác sĩ Khang cho mẹ. Mẹ chia sẻ vào nhóm họ hàng. Cả khoa biết.'),
    dict(id='dd-kinline', kind='demand', rank='kin', emoji='👪', title='Mẹ dẫn người quen lên', who='Mẹ bạn · dẫn bà Năm hàng xóm',
         text='“Mẹ dẫn bà Năm lên nè. Con cho bà khám trước nha, người quen mà, chờ chi.”',
         push=['“Có người nhà làm bệnh viện mà vẫn phải chờ à?”', '“Bà Năm mỏi chân rồi con.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=1,
         words={'rule': 'Ai cũng khám theo mức độ bệnh, kể cả người quen.', 'alt': 'Con đo huyết áp cho bà trong lúc chờ, mời bà ngồi ghế.'},
         back='Bà Năm ngồi chờ, uống ly nước. Mẹ hơi phụng phịu nhưng tối về khen con “đàng hoàng”.',
         give='Bạn cho bà Năm vào trước. Người xếp hàng phía sau quay clip “có người quen là được chen”.'),
    # --- bargains with the ward
    dict(id='dd-triple', kind='bargain', rank='boss', emoji='🌙', title='Trực liền ba ca', who='Chị Hoa · điều dưỡng trưởng',
         text='“Ca đêm thiếu người. Em trực luôn ba ca liền nha, có phụ cấp đàng hoàng.”',
         push=['“Ráng giúp chị đợt này.”', '“Ai cũng ráng mà em.”'],
         persist=(1, 2), mood=(0, 1), weight=2, ask=3, limit=1, unit='ca', pay=6, tire=1, cost=8,
         words={'rule': 'Trực liền quá giờ quy định thì dễ sai sót.', 'alt': 'Em nhận một ca, chị gọi thêm người khoa bên.'},
         lawful='Chị Hoa thở dài: “Ừ, đúng luật.” Chị gọi thêm người khoa bên.'),
    dict(id='dd-training', kind='bargain', rank='boss', emoji='📚', title='Học quy trình mới ngày nghỉ', who='Phòng Điều dưỡng',
         text='“Chủ nhật này học quy trình mới bốn buổi, không tính công. Ai vắng ghi tên.”',
         push=['“Quy trình mới bắt buộc mà.”', '“Không học thì sao làm.”'],
         persist=(1, 2), mood=(0, 1), weight=2, ask=4, limit=2, unit='buổi', pay=0, tire=1, cost=6,
         words={'paper': 'Cho em xin lịch học có tính công.', 'alt': 'Em học hai buổi, hai buổi còn lại học trong giờ.'},
         lawful='Phòng Điều dưỡng xếp lại: hai buổi trong giờ làm, có tính công.'),
    dict(id='dd-tet', kind='bargain', rank='crew', emoji='🧧', title='Trực Tết thay đồng nghiệp', who='Anh Tiến · điều dưỡng cùng khoa',
         text='“Tết này em trực thay anh hai ngày nha, anh về quê. Anh trả em phong bao.”',
         push=['“Năm sau anh trực bù cho em.”', '“Năm nay anh chưa về quê lần nào.”'],
         persist=(1, 2), mood=(0, 1), weight=2, ask=2, limit=1, unit='ngày', pay=5, tire=1, cost=0,
         words={'health': 'Em cũng cần nghỉ cho kịp sức.', 'alt': 'Em trực một ngày, ngày kia anh hỏi thêm chị Thắm.'},
         lawful='Anh Tiến gật gù: “Ừ, một ngày cũng quý rồi.”'),
    dict(id='dd-beds', kind='bargain', rank='boss', emoji='🛏️', title='Thêm giường cho mỗi người', who='Anh Quý · phòng kế hoạch',
         text='“Tiết kiệm nhân sự: từ mai mỗi điều dưỡng nhận thêm bốn giường.”',
         push=['“Bệnh viện khác làm được.”', '“Không hợp tác thì quý này khỏi thưởng.”'],
         persist=(2, 3), mood=(0, 1), weight=2, ask=4, limit=1, unit='giường', pay=0, tire=1, cost=10, press=1,
         words={'rule': 'Quá nhiều giường một người là mất an toàn người bệnh.', 'paper': 'Anh cho em xin văn bản và số liệu.'},
         lawful='Anh Quý rút lại đề xuất. Khoa giữ số giường như cũ.'),
]
