"""Thợ dầu khí: the static content of game/careers/oil.py (not a career itself: not in careers.ORDER).

Everything is fictional: Công ty Dầu khí Sóng Bạc, giàn Hải Âu on mỏ Sao Biển, Cảng trực thăng Mũi Sao, the rig's
own alarm tones, limits and forms. The safety behaviour taught is the real one: a permit before maintenance, every
worker's own lock on every isolation point, bleed and prove zero energy, test the air, a fire watch for hot work and a
standby person at a tank, stop-work authority for anyone, report near-misses, muster upwind and never by the lift.

Pieces:
* PEOPLE, STAFF; the day's weather MODS;
* the helicopter: BAG items, GEAR, the HUET QUIZ; the arrival: ALARMS (tones), BUNKS;
* the toolbox talk: PPE, HAZARDS; the maintenance JOBS (permit, isolation points, bleed, extra precautions);
* the rounds: GAUGES and AREAS; the storm: LOOSE items; the handover: OPEN items;
* the shore day: REQUESTS from the family (the remittance haggle) and the words to answer with;
* ODD (game/careers/air_odd.py scripts: the awkward, pushy people around the job), DESK (kit desk surprises, `mods`
  = the hitch phase they fit), SITUATIONS (sit_ engine), INTRO, stories.
"""
from __future__ import annotations

# ---------------------------------------------------------------- the people
# Odd npc ids (_npc_01, _03…) wear long hair in the portraits: the women sit on the even indexes.
PEOPLE = [
    ('Chị Hạnh', 'Cán bộ an toàn (HSE) của giàn', 'Mười năm đi biển, nói nhỏ nhẹ mà không bỏ qua một chữ ký nào trên giấy phép.', 'quiet'),
    ('Chú Toàn', 'Trưởng ca vận hành, người kèm bạn', 'Hai mươi hai năm trên giàn. Câu cửa miệng: “Không chắc thì dừng, dừng không ai trách.”', 'picky'),
    ('Cô Sáu', 'Bếp trưởng nhà ăn giàn', 'Nấu cho tám mươi người ba bữa một ngày, nhớ ai ăn cay, ai kiêng hành.', 'warm'),
    ('Anh Bảo', 'Giám sát bảo dưỡng', 'Lúc nào cũng dí tiến độ, điện thoại kẹp tai, “nhanh lên em, tàu dịch vụ chờ”.', 'bossy'),
    ('Má', 'Má ở quê, xóm Rạch Tràm', 'Gọi video mỗi tối, hỏi con ăn chưa, rồi tới chuyện tiền nhà.', 'warm'),
    ('Tuấn “Gấu”', 'Bạn cùng phòng, thợ vận hành', 'Hiền khô, ngáy như máy nén khí, mê bóng đá với mì cay.', 'genz'),
    ('Chị Thoa', 'Y tá giàn', 'Phòng y tế nhỏ xíu nhưng chị nhớ huyết áp của từng người trên giàn.', 'picky'),
]
HSE, TOAN, SAU, BAO, MA, GAU, THOA = range(7)

STAFF = [('Khang', 'roust', 'Thợ phụ boong lanh lẹ, chằng buộc hàng chưa bao giờ sót dây.', 82, 88),
         ('Ngân', 'ccr', 'Trực phòng điều khiển, đọc màn hình nhanh như đọc tin nhắn.', 74, 94),
         ('Phát', 'roust', 'Khỏe, vui tính, hay hát vọng cổ lúc kéo ống.', 88, 78),
         ('Mỹ', 'ccr', 'Học kỹ thuật hóa dầu, thuộc sơ đồ công nghệ từng van.', 72, 95)]
ROLES = {'roust': 'Thợ phụ boong', 'ccr': 'Trực phòng điều khiển'}

COMPANY = 'Dầu khí Sóng Bạc'
RIG = 'giàn Hải Âu'
FIELD = 'mỏ Sao Biển'
HELIPORT = 'Cảng trực thăng Mũi Sao'

MODS = [
    dict(id='calm', emoji='🌤️', label='Biển êm', hint='Gió nhẹ, sóng thấp: ngày đẹp để làm bảo dưỡng.', weight=4),
    dict(id='swell', emoji='🌊', label='Sóng lừng', hint='Giàn rung nhẹ, người mới dễ say sóng. Lên xuống cầu thang nhớ vịn tay.', min_day=2, weight=2),
    dict(id='monsoon', emoji='🌬️', label='Gió mùa đông bắc', hint='Gió mạnh: quá 35 nút cẩu phải dừng, làm trên cao phải móc dây.', min_day=2, weight=2),
    dict(id='fog', emoji='🌫️', label='Sương mù', hint='Trực thăng có thể hoãn chuyến; trên boong tầm nhìn kém, đi chậm.', min_day=2, weight=1),
    dict(id='typhoon', emoji='🌀', label='Áp thấp nhiệt đới', hint='Bão gần: chằng buộc boong, trực thăng không bay, đợt có thể kéo dài.', min_day=4, weight=1),
]

# ---------------------------------------------------------------- the helicopter out (heli)
BAG_LIMIT = 15   # kg in the soft bag, by the heliport's own rule
BAG = [
    dict(id='quan_ao', emoji='👕', name='Quần áo cho 14 ngày', kg=5, banned=False, why=''),
    dict(id='thuoc', emoji='💊', name='Thuốc riêng có đơn bác sĩ', kg=0.5, banned=False, why=''),
    dict(id='sac', emoji='🔋', name='Một sạc dự phòng nhỏ', kg=0.5, banned=False, why=''),
    dict(id='laptop', emoji='💻', name='Laptop xem phim tối', kg=2, banned=False, why=''),
    dict(id='mi', emoji='🍜', name='Thùng mì cay', kg=4, banned=False, why=''),
    dict(id='ta', emoji='🏋️', name='Cặp tạ tay 5 kg', kg=5, banned=False, why=''),
    dict(id='banh', emoji='🍪', name='Hộp bánh Má gói', kg=1, banned=False, why=''),
    dict(id='bat_lua', emoji='🔥', name='Bật lửa', kg=0.1, banned=True, why='Nguồn lửa: giàn cấm mang bật lửa, diêm lên khu công nghệ.'),
    dict(id='xit', emoji='🧴', name='Chai keo xịt tóc', kg=0.3, banned=True, why='Bình xịt áp suất dễ cháy: cấm trên trực thăng.'),
    dict(id='dao', emoji='🔪', name='Dao gấp đi câu', kg=0.2, banned=True, why='Vật sắc nhọn: không mang lên trực thăng.'),
    dict(id='ruou', emoji='🍶', name='Chai rượu thuốc ba gửi', kg=1, banned=True, why='Giàn cấm hoàn toàn đồ uống có cồn.'),
    dict(id='vape', emoji='💨', name='Thuốc lá điện tử', kg=0.2, banned=True, why='Pin và hơi nóng: cấm như thuốc lá trên giàn.'),
]
BAG_INDEX = {x['id']: x for x in BAG}
GEAR = [
    dict(id='suit', emoji='🦺', name='Bộ đồ bơi giữ nhiệt', note='Kéo khóa kín cổ, đeo găng.'),
    dict(id='vest', emoji='🛟', name='Áo phao trực thăng', note='Thắt dây bụng, không bơm hơi trong khoang.'),
    dict(id='ebs', emoji='🫁', name='Bình thở khẩn cấp', note='Kiểm đồng hồ áp, biết chỗ ngậm.'),
    dict(id='ear', emoji='🎧', name='Chụp tai chống ồn', note='Ồn cánh quạt: không đeo là ù tai cả ngày.'),
]
GEAR_IDS = tuple(x['id'] for x in GEAR)
# HUET: what the helicopter underwater escape training drills, as a quick check before boarding.
QUIZ = [
    dict(id='q_sink', text='Trực thăng hạ khẩn cấp xuống biển và lật úp. Bạn làm gì trước?',
         options=[('a', 'Tháo dây ngay rồi bơi ra'), ('b', 'Giữ tư thế, một tay nắm mốc cửa sổ, chờ khoang ngừng lật và ngập rồi mới tháo dây'),
                  ('c', 'Bơm áo phao ngay trong khoang')], answer='b',
         why='Tháo dây khi khoang còn lật là bị cuốn trôi, mất phương hướng. Chờ ngừng lật, tay giữ mốc lối thoát, rồi mới tháo dây.'),
    dict(id='q_vest', text='Khi nào bơm hơi áo phao?',
         options=[('a', 'Ngay khi có báo động'), ('b', 'Khi đã ra khỏi khoang trực thăng'), ('c', 'Lúc ngồi xuống ghế cho chắc')], answer='b',
         why='Áo phao bơm trong khoang sẽ ép bạn lên trần, không bơi ra cửa được.'),
    dict(id='q_brace', text='Phi công hô “Chuẩn bị va chạm!”. Tư thế đúng?',
         options=[('a', 'Ngồi thẳng, lưng áp ghế, dây thắt chặt, tay ôm người'), ('b', 'Cúi xuống nhặt điện thoại rơi'), ('c', 'Đứng dậy ra gần cửa')], answer='a',
         why='Lưng áp ghế, dây chặt, tay ôm người giảm chấn thương khi chạm nước.'),
    dict(id='q_ebs', text='Bình thở khẩn cấp dùng lúc nào?',
         options=[('a', 'Khi bị chìm trong khoang và chưa thoát ra được'), ('b', 'Khi say sóng'), ('c', 'Khi buồn chán trên chuyến bay')], answer='a',
         why='Bình thở cho thêm thời gian khi còn kẹt dưới nước trong khoang.'),
]
QUIZ_INDEX = {x['id']: x for x in QUIZ}

# ---------------------------------------------------------------- arrival (induct)
# The rig's own alarm tones (a game rule; every real installation posts its own).
ALARMS = [
    dict(id='ga', emoji='📯', tone='Còi ngắt quãng, đèn đỏ nhấp nháy', name='Báo động chung',
         do='Dừng việc, để thiết bị an toàn, về điểm tập trung của mình, quẹt thẻ.'),
    dict(id='gas', emoji='🟡', tone='Còi hai nhịp trầm bổng, đèn vàng', name='Báo rò khí',
         do='Rời khu vực ngược hướng gió, không bật lửa, không bấm điện thoại, về điểm tập trung.'),
    dict(id='ab', emoji='🚨', tone='Còi kéo dài liên tục', name='Lệnh bỏ giàn',
         do='Mặc áo phao, ra xuồng cứu sinh của mình, nghe trưởng xuồng.'),
]
ALARM_IDS = tuple(x['id'] for x in ALARMS)
BUNKS = (104, 108, 112, 203, 207, 211)
STATIONS = {'A': 'Xuồng cứu sinh A · mạn trái', 'B': 'Xuồng cứu sinh B · mạn phải'}

# ---------------------------------------------------------------- the toolbox talk (toolbox)
PPE = [
    dict(id='helmet', emoji='⛑️', name='Mũ bảo hộ'), dict(id='glasses', emoji='🥽', name='Kính bảo hộ'),
    dict(id='gloves', emoji='🧤', name='Găng tay'), dict(id='boots', emoji='🥾', name='Giày mũi thép'),
    dict(id='coverall', emoji='🧥', name='Áo liền quần chống cháy'), dict(id='ear', emoji='🔇', name='Nút tai'),
    dict(id='monitor', emoji='📟', name='Máy đo khí cá nhân'),
]
PPE_IDS = tuple(x['id'] for x in PPE)
HAZARDS = {
    'pressure': ('💥', 'Áp suất còn trong ống', 'Cô lập, xả áp, kiểm về không trước khi mở.'),
    'gas': ('☁️', 'Khí dễ cháy, khí độc H₂S', 'Đo khí trước và trong khi làm, đeo máy đo cá nhân.'),
    'fire': ('🔥', 'Tia lửa khi hàn, mài', 'Giấy phép làm nóng, che tia lửa, người canh lửa, bình chữa cháy.'),
    'elec': ('⚡', 'Điện áp còn trên thiết bị', 'Cắt cầu dao, khóa, treo thẻ, thử không còn điện.'),
    'height': ('🪜', 'Làm việc trên cao', 'Dây an toàn móc điểm neo, cột dây dụng cụ chống rơi.'),
    'confined': ('🛢️', 'Không gian hạn chế, thiếu ôxy', 'Thông gió, đo ôxy, người trực ở cửa, không vào một mình.'),
    'lift': ('🏗️', 'Cẩu nâng hàng trên đầu', 'Không đứng dưới tải treo, đối chiếu giấy phép cẩu.'),
    'hot': ('🌡️', 'Bề mặt nóng, nắng nóng', 'Găng chịu nhiệt, uống nước, nghỉ trong bóng mát.'),
    'slip': ('💧', 'Sàn trơn dầu, sóng làm giàn rung', 'Lau sạch dầu, bám tay vịn, đi chậm.'),
    'noise': ('🔊', 'Tiếng ồn máy nén', 'Nút tai, ra hiệu tay khi không nghe được.'),
}

# ---------------------------------------------------------------- maintenance under permit (ptw)
PERMITS = {
    'cold': ('🧊', 'Giấy phép làm nguội', 'Việc không sinh lửa: tháo lắp, thay thế.'),
    'hot': ('🔥', 'Giấy phép làm nóng', 'Hàn, cắt, mài: có tia lửa.'),
    'confined': ('🛢️', 'Giấy phép vào không gian hạn chế', 'Vào bồn, bể, két kín.'),
    'elec': ('⚡', 'Giấy phép làm việc điện', 'Làm trên thiết bị điện, cần cô lập điện.'),
}
# Isolation point kinds: a process valve closed and locked, a breaker locked off, a drain/vent to bleed.
JOBS = [
    dict(id='seal', title='Thay phớt bơm nước biển P-201B', tag='P-201B', permit='cold', hazards=('pressure', 'elec', 'slip'),
         points=[('V-11', 'Van hút', 'valve'), ('V-12', 'Van đẩy', 'valve'), ('CB-201B', 'Cầu dao bơm', 'breaker')], bleed='V-13 · van xả đáy bơm',
         prove='Đồng hồ áp bơm', work='Tháo vỏ phớt, thay phớt cơ khí mới, siết bu lông theo lực.', watch=None),
    dict(id='filter', title='Thay lõi lọc dầu bôi trơn F-310', tag='F-310', permit='cold', hazards=('pressure', 'gas', 'slip'),
         points=[('V-31', 'Van vào lọc', 'valve'), ('V-32', 'Van ra lọc', 'valve')], bleed='V-33 · van xả về bồn thu',
         prove='Đồng hồ áp bình lọc', work='Mở nắp bình lọc, thay lõi lọc, thay gioăng nắp.', watch=None),
    dict(id='weld', title='Hàn lại chân lan can chiếu nghỉ boong dưới', tag='Boong dưới · khu 2', permit='hot', hazards=('fire', 'gas', 'height'),
         points=[], bleed=None, prove=None, work='Che chắn tia lửa, hàn lại chân lan can, mài nhẵn mối hàn.', watch='fire'),
    dict(id='tank', title='Vào bồn nước ngọt T-40 kiểm tra cặn', tag='T-40', permit='confined', hazards=('confined', 'elec', 'slip'),
         points=[('V-41', 'Van cấp nước vào bồn', 'valve'), ('CB-40', 'Cầu dao bơm cấp', 'breaker')], bleed='V-42 · van xả cạn bồn',
         prove='Mực nước và bơm cấp', work='Vào bồn, soi đèn kiểm tra cặn và vết gỉ, chụp ảnh thành bồn.', watch='standby'),
    dict(id='motor', title='Thay ổ bi quạt làm mát E-55', tag='E-55', permit='elec', hazards=('elec', 'height', 'noise'),
         points=[('CB-55', 'Cầu dao quạt', 'breaker')], bleed=None,
         prove='Bút thử điện và nút chạy thử', work='Tháo cánh quạt, thay ổ bi, cân lại cánh.', watch=None),
    dict(id='psv', title='Thay van an toàn PSV-120 bình tách V-120', tag='PSV-120', permit='cold', hazards=('pressure', 'gas', 'lift'),
         points=[('V-121', 'Van chặn trước PSV', 'valve'), ('V-122', 'Van chặn sau PSV', 'valve')], bleed='V-123 · van xả về đuốc',
         prove='Đồng hồ áp giữa hai van', work='Tháo PSV cũ bằng pa lăng, lắp PSV đã hiệu chuẩn, gioăng mới.', watch=None),
    dict(id='gauge', title='Thay đồng hồ áp suất PG-77 đường khí', tag='PG-77', permit='cold', hazards=('pressure', 'gas', 'noise'),
         points=[('V-77', 'Van gốc đồng hồ', 'valve')], bleed='V-78 · vít xả đồng hồ',
         prove='Vít xả: không còn xì', work='Tháo đồng hồ cũ, quấn băng tan, lắp đồng hồ mới.', watch=None),
    dict(id='grind', title='Mài gỉ bệ máy nén khí K-90', tag='K-90 · khu 3', permit='hot', hazards=('fire', 'gas', 'noise'),
         points=[('CB-90', 'Cầu dao máy nén', 'breaker')], bleed=None, prove='Nút chạy thử máy nén',
         work='Che chắn, mài gỉ bệ máy, sơn chống gỉ.', watch='fire'),
]
JOB_INDEX = {x['id']: x for x in JOBS}
# A trap waits behind one of the player's own checks. `seen` is the check that shows it.
TRAPS = {
    'passing': dict(seen='verify', reason='passing', text='Đồng hồ vẫn {v} bar sau khi xả: một van đang lọt, chưa về không.',
                    fix='Chú Toàn cho đóng thêm van chặn phía trước (cô lập hai lớp), xả lại: đồng hồ về 0.', jobs=('seal', 'filter', 'psv', 'gauge', 'tank'),
                    harm='Mở bích khi đường ống còn áp: dầu nóng phụt ra, bạn lùi kịp, ướt cả người.'),
    'gas': dict(seen='gas', reason='gas', text='Máy đo khí báo {v}% LEL ở mép bích: có khí dễ cháy.',
                fix='Chị Hạnh cho thông gió, tìm ra mối rò ở khớp nối bên cạnh, siết lại; đo lại 0% LEL.', jobs=('filter', 'weld', 'psv', 'gauge', 'grind'),
                harm='Làm tiếp khi máy đo còn báo khí: tia lửa bén vào khí, lửa bùng một khắc rồi tắt, may chưa ai bị bỏng.'),
    'o2': dict(seen='gas', reason='gas', text='Ôxy trong bồn chỉ {v}%: thiếu ôxy, vào là ngất.', fix='Chị Hạnh cho quạt thổi khí vào bồn 30 phút, đo lại ôxy 20,9%.',
               jobs=('tank',), harm='Bước vào bồn thiếu ôxy: hoa mắt, người trực cửa phải kéo dây đưa bạn ra.'),
    'simops': dict(seen='xref', reason='simops', text='Bảng giấy phép đang mở: cẩu nâng container ngay trên đầu khu làm việc lúc {v}.',
                   fix='Chú Toàn gọi cẩu trưởng: dời việc nâng sang chiều, khu làm việc được rào lại.', jobs=('seal', 'weld', 'psv', 'grind'),
                   harm='Làm bên dưới tải treo: một dây chằng tuột, thùng hàng chao qua đầu bạn chưa tới một mét.'),
    'live': dict(seen='verify', reason='live', text='Bút thử vẫn sáng {v}: cầu dao vừa khóa ghi nhầm nhãn, thiết bị còn điện.',
                 fix='Thợ điện dò lại sơ đồ, khóa đúng cầu dao, sửa nhãn; thử lại: hết điện.', jobs=('motor', 'grind', 'seal'),
                 harm='Chạm vào thiết bị còn điện: bị giật tê tay, chị Thoa phải đưa vào phòng y tế theo dõi.'),
}
STOP_REASONS = {
    'passing': '💥 Chưa về không áp',
    'gas': '☁️ Đo khí không đạt',
    'simops': '🏗️ Trùng việc với cẩu',
    'live': '⚡ Còn điện',
    'unsure': '🤔 Thấy không chắc, hỏi lại',
}
GAS_LIMIT = dict(lel=10, lel_hot=0, h2s=5, o2_lo=19.5, o2_hi=23.5)
WATCH = {'fire': ('🧯', 'Bố trí người canh lửa, bình chữa cháy'), 'standby': ('🧍', 'Bố trí người trực ở cửa bồn, dây cứu')}

# ---------------------------------------------------------------- rounds (round)
# (tag, name, unit, normal low, normal high, value when fine)
GAUGES = [
    ('PT-101', 'Áp đầu giếng W-3', 'bar', 42, 58, 50), ('TT-210', 'Nhiệt dầu ra bình tách', '°C', 55, 75, 64),
    ('LT-120', 'Mực chất lỏng bình tách V-120', '%', 35, 65, 48), ('PT-305', 'Áp khí nhiên liệu', 'bar', 6, 9, 7),
    ('FT-401', 'Lưu lượng nước bơm ép', 'm³/h', 120, 160, 140), ('PT-520', 'Áp nước cứu hỏa', 'bar', 10, 14, 12),
    ('TT-610', 'Nhiệt dầu bôi trơn máy nén', '°C', 40, 60, 52), ('PT-711', 'Áp khí điều khiển van', 'bar', 6, 8, 7),
]
GAUGE_INDEX = {x[0]: x for x in GAUGES}
AREAS = {
    'wellhead': ('🛢️', 'Khu đầu giếng'), 'separator': ('⚗️', 'Khu bình tách'), 'compressor': ('🌀', 'Khu máy nén khí'),
    'pump': ('💧', 'Khu bơm nước ép'), 'deck': ('🧰', 'Boong chính'),
}
LEAKS = {
    'hiss': 'Có tiếng xì nhỏ ở mặt bích, ngửi thấy mùi khí.',
    'drip': 'Một vệt dầu nhỏ giọt từ gioăng van xuống sàn.',
    'sheen': 'Mặt nước dưới chân giàn có vệt dầu óng ánh.',
}
CALM_LOOK = {
    'wellhead': 'Đầu giếng khô ráo, van chặn ở đúng vị trí.', 'separator': 'Bình tách êm, kính thăm mực trong.',
    'compressor': 'Máy nén chạy đều tiếng, không rung lạ.', 'pump': 'Bơm chạy êm, sàn sạch.', 'deck': 'Lối đi thông, bình chữa cháy đủ niêm.',
}

# ---------------------------------------------------------------- the storm (secure)
LOOSE = [
    dict(id='container', emoji='📦', name='Container phụ tùng trên boong hàng', do='lash', note='Chằng thêm dây, kiểm khóa góc.'),
    dict(id='scaffold', emoji='🪜', name='Giàn giáo dở dang ở mạn phải', do='lash', note='Tháo tấm sàn lỏng, buộc chặt khung.'),
    dict(id='drums', emoji='🛢️', name='Phuy dầu nhớt rời ngoài boong', do='inside', note='Đưa vào kho, đứng thẳng, có khay hứng.'),
    dict(id='hoses', emoji='🧵', name='Cuộn ống mềm vắt trên lan can', do='inside', note='Cuộn gọn, cất vào kho.'),
    dict(id='chairs', emoji='🪑', name='Ghế nhựa khu hút thuốc', do='inside', note='Gió mạnh là thành vật bay.'),
    dict(id='lifeboat', emoji='🛶', name='Xuồng cứu sinh', do='check', note='Đã kiểm định kỳ, chỉ cần kiểm dây treo.'),
    dict(id='helideck', emoji='🚁', name='Lưới sân trực thăng', do='lash', note='Siết lại chốt lưới chống trượt.'),
]
LOOSE_INDEX = {x['id']: x for x in LOOSE}

# ---------------------------------------------------------------- the handover (handover)
OPEN_ITEMS = [
    dict(id='vib', emoji='📳', text='Bơm P-201A rung nhẹ hơn bình thường, chưa rõ lý do.', must=True),
    dict(id='filter', emoji='🧽', text='Lọc F-310 chưa thay vì thiếu lõi lọc, đã đặt hàng tàu sau.', must=True),
    dict(id='sensor', emoji='📡', text='Đầu dò khí khu 3 báo chập chờn hai lần trong đêm.', must=True),
    dict(id='wrench', emoji='🔧', text='Mình suýt làm rơi cờ lê từ sàn trên xuống, đã báo suýt sự cố.', must=True),
    dict(id='coffee', emoji='☕', text='Máy pha cà phê nhà ăn hỏng nút, cô Sáu đang mượn ấm.', must=False),
    dict(id='permit', emoji='📋', text='Giấy phép thay PSV-120 còn mở, cô lập vẫn giữ khóa.', must=True),
    dict(id='karaoke', emoji='🎤', text='Phòng giải trí đòi mua thêm micro karaoke.', must=False),
]
OPEN_INDEX = {x['id']: x for x in OPEN_ITEMS}

# ---------------------------------------------------------------- the shore day (shore): the family's requests
# kind: need (a real need), want (nice to have), gift (a custom: some is fine), loan (risky), scam (never).
# fact: what "Hỏi rõ" brings out. Amounts in xu.
REQUESTS = [
    dict(id='med', who='Má', emoji='👵', kind='need', ask=20, need=20, line='Thuốc huyết áp tháng này hết rồi con, 20 xu.',
         fact='Má gửi ảnh toa thuốc của trạm y tế: đúng 20 xu một tháng.'),
    dict(id='roof', who='Ba', emoji='👴', kind='need', ask=30, need=22, line='Bão sắp vô, mái tôn nhà mình dột ba chỗ. Ba tính thay luôn, chừng 30 xu.',
         fact='Chú thợ trong xóm báo giá: thay ba tấm tôn dột hết 22 xu, thay cả mái mới 30.'),
    dict(id='tuition', who='Bé Vy', emoji='🎒', kind='need', ask=25, need=25, line='Học phí học kỳ này 25 xu, hạn thứ Sáu nè. Gửi sớm giùm em nha 🥺',
         fact='Giấy báo học phí của trường ghi rõ: 25 xu, hạn thứ Sáu.'),
    dict(id='eyes', who='Bà ngoại', emoji='👓', kind='need', ask=15, need=15, line='Bà đi tái khám mắt ở huyện, tiền xe với tiền khám chừng 15 xu con ơi.',
         fact='Giấy hẹn tái khám có ghi giá khám; cộng tiền xe đúng chừng đó.'),
    dict(id='phone', who='Thằng Tí', emoji='📱', kind='want', ask=40, need=0, line='Mua cho em con điện thoại mới đi, đứa nào trong lớp cũng có, 40 xu thôi mà 😤',
         fact='Điện thoại của Tí vẫn xài tốt, chỉ là đời cũ, màn hình hơi trầy.'),
    dict(id='tv', who='Má', emoji='📺', kind='want', ask=30, need=0, line='Má muốn mua cái tivi to xem cải lương cho đã, 30 xu thôi.',
         fact='Tivi ở nhà vẫn xem tốt. Má chỉ muốn màn hình to hơn.'),
    dict(id='party', who='Hội bạn thân', emoji='🍻', kind='want', ask=20, need=0, line='Về bờ rồi bao tụi tao chầu lẩu đi, đi dầu khí giàu vl mà!',
         fact='Hội bạn đã đặt bàn lẩu, mỗi người góp 5 xu là đủ.'),
    dict(id='bike', who='Thằng Tí', emoji='🚲', kind='want', ask=35, need=8, line='Xe đạp em gãy sên rồi… hay mua luôn xe điện đi, 35 xu.',
         fact='Tiệm xe đầu xóm: thay sên xe đạp hết 8 xu.'),
    dict(id='wedding', who='Dì Năm', emoji='💒', kind='gift', ask=30, need=10, line='Đám cưới con dì tuần sau. Đi làm dầu khí lương cao, mừng ít người ta cười đó nghen.',
         fact='Trong xóm mừng cưới người thân thường 10–15 xu.'),
    dict(id='loan', who='Chú Ba', emoji='🚤', kind='loan', ask=40, need=10, line='Cho chú mượn 40 xu xoay vốn ghe cá, tháng sau chú trả liền.',
         fact='Má nói nhỏ: chú Ba còn mượn hàng xóm hai lần chưa trả. Mùa này ghe nằm bờ.'),
    dict(id='hui', who='Má', emoji='🪙', kind='loan', ask=30, need=0, line='Má tính chơi hụi với bà Tư đầu xóm, con góp 30 xu cho má nha.',
         fact='Năm ngoái dây hụi của bà Tư bể, cả xóm mất tiền.'),
    dict(id='crypto', who='Anh Tuấn họ', emoji='🕶️', kind='scam', ask=50, need=0, line='Góp 50 xu vô dự án tiền ảo của anh đi, một tháng lời gấp ba, bao lỗ luôn!',
         fact='Dự án không có giấy phép, chỉ “lời” khi kéo thêm người vào: kiểu đa cấp.'),
    dict(id='pills', who='Cô Bích hàng xóm', emoji='💊', kind='scam', ask=25, need=0, line='Mua giùm cô gói thuốc “chữa bách bệnh” cho má con, 25 xu, cô đang chạy doanh số.',
         fact='Gói “thuốc” không có số đăng ký, trạm y tế xã từng cảnh báo.'),
    dict(id='prize', who='Tin nhắn lạ', emoji='📩', kind='scam', ask=15, need=0, line='Chúc mừng! Bạn trúng xe máy. Chuyển 15 xu “phí nhận thưởng” vào số tài khoản này.',
         fact='Không có chương trình nào thu phí để nhận thưởng: lừa đảo.'),
]
REQUEST_INDEX = {x['id']: x for x in REQUESTS}
SHORE_WORDS = {
    'explain': 'Con phải để dành',
    'later': 'Đợt sau gửi thêm',
    'love': 'Hỏi han cả nhà',
    'no': 'Từ chối thẳng',
}

# ---------------------------------------------------------------- the intro card
INTRO = dict(
    title='Giới thiệu nghề: thợ dầu khí ngoài khơi',
    lead='Bạn là kỹ thuật viên vận hành của Dầu khí Sóng Bạc trên giàn Hải Âu, mỏ Sao Biển. Đi biển theo đợt 14 ngày: bay trực thăng ra giàn, '
         'làm ca 12 tiếng, rồi về bờ với gia đình. Lương cao, nhưng nhớ nhà, và không có bước an toàn nào được bỏ.',
    work=[('🚁', 'Ngày bay: soạn túi, mặc đồ bơi giữ nhiệt, nghe hướng dẫn thoát hiểm'), ('🪪', 'Lên giàn: gắn thẻ, nhớ điểm tập trung, nghe tiếng còi'),
          ('🗣️', 'Đầu ca: họp an toàn, đồ bảo hộ, thử máy đo khí'), ('📋', 'Bảo dưỡng: giấy phép, cô lập, khóa và treo thẻ, xả áp, đo khí'),
          ('🔎', 'Đi tuần: đọc đồng hồ, nghe, nhìn, ngửi, báo phòng điều khiển'), ('🚨', 'Báo động: đi ngược gió về điểm tập trung, không đi thang máy'),
          ('✋', 'Thấy không an toàn: quyền dừng việc của bạn'), ('🏠', 'Về bờ: bàn giao thật thà, rồi cả nhà… hỏi tiền')],
    meet=[('🦺', 'Chị Hạnh: an toàn, giấy phép'), ('👷', 'Chú Toàn: trưởng ca, người kèm bạn'), ('📞', 'Anh Bảo: giám sát, dí tiến độ'),
          ('🍲', 'Cô Sáu: bếp trưởng'), ('😴', 'Tuấn Gấu: bạn cùng phòng ngáy to'), ('👵', 'Má: gọi video mỗi tối'), ('🩺', 'Chị Thoa: y tá giàn')],
    stars=[('🔒', 'Khóa đủ mọi điểm cô lập, khóa của chính mình'), ('0️⃣', 'Kiểm về không, đo khí trước khi mở'), ('✋', 'Dám dừng việc khi thấy lạ'),
           ('📝', 'Báo cả suýt sự cố, kể cả của mình'), ('🧭', 'Đi ngược gió về đúng điểm tập trung'), ('🏠', 'Lo cho nhà mà không bị lừa')],
)

# ---------------------------------------------------------------- chuyện oái oăm (air_odd engine scripts)
# Ranks: crew (colleagues, contractors), boss (supervisors, the office), kin (family: only you can answer), pax (outsiders:
# visitors, passengers, the supply boat). need_mark 'ashore' = only on shore days; no_mark 'ashore' = only on the rig.
ODD = [
    # --- corners cut: say it, use stop-work authority, report (reports are no-blame)
    dict(id='dk-skipgas', kind='corner', rank='boss', emoji='☁️', title='“Bỏ qua đo khí đi em”', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='“Khu này tuần nào chả đo, sạch boong. Bỏ bước đo khí đi, tàu dịch vụ chờ lấy phụ tùng kìa, trễ là anh bị trừ KPI đó!”',
         push=['“Mười năm anh làm có thấy nổ bao giờ đâu. Nhanh!”', '“Em mà làm chậm nữa là anh ghi em vào danh sách thiếu hợp tác nha.”'],
         persist=(2, 3), mood=(0, 2), weight=3, severe=3, no_mark='ashore',
         words={'speak': 'Em dùng quyền dừng việc: chưa đo khí thì chưa làm.', 'rule': 'Giấy phép ghi rõ đo khí trước khi mở.', 'alt': 'Em đo nhanh hai phút, xong làm liền.'},
         back='Anh Bảo cằn nhằn nhưng đứng chờ. Máy đo báo 0% LEL, việc xong trước khi tàu dịch vụ rời giàn.',
         give='Bạn bỏ bước đo khí. Lúc mở bích nghe mùi khí xộc lên, cả hai lùi ra. Chị Hạnh khóa giấy phép, mời hai người lên phòng họp.',
         review={'report': [5, 'Em dừng việc đúng lúc. Anh xin lỗi vì dí em.'], 'give': [2, 'Lần sau anh không dám bảo bỏ bước nữa. Mà em cũng đừng nghe anh.']}),
    dict(id='dk-fakecheck', kind='corner', rank='crew', emoji='📝', title='Checklist giàn giáo ký sẵn', who='Anh Lực · thợ giàn giáo nhà thầu',
         text='Anh Lực đưa tờ checklist giàn giáo đã ký sẵn đủ mười ô: “Ký vô ô người nhận đi em, giàn anh dựng chắc như bê tông, kiểm chi cho mất công.”',
         push=['“Nhà thầu làm cả trăm cái giàn rồi. Em không tin anh hả?”', '“Em không ký thì anh báo sếp em là em làm khó nhà thầu.”'],
         persist=(1, 3), mood=(0, 2), weight=3, severe=2, no_mark='ashore',
         words={'speak': 'Chưa kiểm tận tay thì em không ký.', 'alt': 'Mình đi kiểm cùng nhau năm phút.'},
         back='Hai người đi kiểm. Tới ô thứ bảy thì thấy thiếu một chốt ở tấm sàn tầng hai. Anh Lực im lặng lắp vào.',
         give='Bạn ký. Chiều đó một tấm sàn giàn giáo bật ra khi thợ bước lên, may người đó móc dây an toàn.',
         report='Bạn báo chị Hạnh. Nhà thầu phải kiểm lại cả ba bộ giàn giáo; một bộ thiếu chốt. Không ai trách người báo.'),
    dict(id='dk-onelock', kind='corner', rank='crew', emoji='🔒', title='“Xài chung ổ khóa cho nhanh”', who='Hoàng · thợ cơ khí ca ngày',
         text='Hoàng treo một ổ khóa lên cầu dao: “Khóa của tao rồi, mày khỏi treo khóa mày. Tao giữ chìa, có gì tao mở cho.”',
         push=['“Rườm rà vl, có hai đứa thôi mà.”', '“Tao làm ở đây ba năm, chưa ai treo hai khóa một cầu dao hết.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=2, no_mark='ashore',
         words={'speak': 'Mỗi người một khóa, chìa ai nấy giữ.', 'rule': 'Quy định khóa và treo thẻ: ai làm người đó khóa.', 'alt': 'Gắn kẹp nhiều khóa, mỗi đứa một ổ.'},
         back='Hoàng lấy kẹp nhiều khóa ra. Hai ổ khóa, hai tấm thẻ tên. Cầu dao chỉ mở khi cả hai người cùng tháo khóa.',
         give='Bạn làm dưới khóa của Hoàng. Giữa chừng Hoàng đi ăn trưa, người ca chiều thấy cầu dao không có thẻ của bạn, suýt đóng điện.'),
    dict(id='dk-inhibit', kind='corner', rank='boss', emoji='📡', title='Tắt tạm đầu dò khí', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='“Đầu dò khí khu 3 cứ báo giả, cả giàn chạy ra điểm tập trung hai lần rồi. Vào phòng điều khiển tắt nó đi, mai sửa.”',
         push=['“Báo giả mà, tắt một đêm thôi. Em muốn cả giàn mất ngủ hả?”', '“Anh chịu trách nhiệm, em cứ bấm đi.”'],
         persist=(2, 3), mood=(0, 2), weight=2, severe=4, no_mark='ashore', min_day=3,
         words={'speak': 'Tắt đầu dò là mất mắt ở khu 3. Phải có giấy phép vô hiệu hóa.', 'alt': 'Gọi thợ đo lường kiểm ngay, trực người canh khu 3.'},
         back='Thợ đo lường tới kiểm: đầu dò bám muối biển. Lau sạch, thử bằng khí mẫu, hết báo giả.',
         give='Bạn tắt đầu dò. Nửa đêm một khớp nối ở khu 3 rò khí thật, không còi nào kêu. Ca trực ngửi thấy mùi mới phát hiện.',
         report='Bạn báo chị Hạnh. Đầu dò được đưa vào danh sách sửa gấp, có người canh khu 3 với máy đo cầm tay tới sáng.'),
    dict(id='dk-cranewind', kind='corner', rank='crew', emoji='🏗️', title='Nâng nốt container lúc gió mạnh', who='Chú Đực · cẩu trưởng',
         text='Đồng hồ gió báo 41 nút, giới hạn của cẩu là 35. Chú Đực vẫy bạn: “Móc dây vô đi con, nâng nốt cái này cho tàu dịch vụ về sớm.”',
         push=['“Gió giật thôi, lát nó êm. Móc lẹ đi.”', '“Chú lái cẩu ba chục năm, chú biết chừng nào nguy hiểm.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=3, no_mark='ashore',
         words={'speak': 'Gió 41 nút, quá giới hạn 35. Mình dừng nâng.', 'alt': 'Chờ gió xuống dưới 35 rồi nâng tiếp.'},
         back='Chú Đực hạ móc, châm trà ngồi chờ. Bốn mươi phút sau gió xuống 28 nút, container lên tàu êm ru.',
         give='Bạn móc dây. Container xoay vòng giữa trời vì gió, đập vào lan can tàu dịch vụ. Không ai bị thương, nhưng cả giàn dừng cẩu ba ngày.'),
    dict(id='dk-harness', kind='corner', rank='crew', emoji='🪢', title='“Lên ba mét thôi, khỏi móc dây”', who='Lính mới Quý · thợ phụ',
         text='Quý leo lên giàn giáo ba mét, dây an toàn để dưới đất: “Lên tháo cái bóng đèn thôi anh/chị, móc dây vướng tay lắm.”',
         push=['“Mấy anh khác cũng không móc mà.”', '“Xíu là xong rồi, đừng có làm quá.”'],
         persist=(0, 2), mood=(0, 1), weight=2, severe=2, no_mark='ashore',
         words={'speak': 'Xuống đeo dây đã, móc vào điểm neo rồi lên.', 'alt': 'Để mình giữ thang, em móc dây rồi làm.'},
         back='Quý tụt xuống, đeo dây, móc vào điểm neo. Lúc tháo bóng đèn thì trượt chân, dây giữ lại, chỉ hú hồn.',
         give='Bạn để Quý làm. Quý trượt chân, may túm được lan can, trầy cả cánh tay. Chị Thoa băng bó, chị Hạnh lập biên bản.'),
    dict(id='dk-signfor', kind='corner', rank='crew', emoji='✍️', title='“Ký nhận giấy phép giùm anh”', who='Anh Hưng · thợ điện',
         text='“Anh đang kẹt dưới boong dưới. Em ký tên anh vô ô người thực hiện giùm, chị Hạnh có hỏi thì nói anh ký rồi.”',
         push=['“Chữ ký thôi mà, có ai so đâu.”', '“Anh em với nhau mà, giúp có xíu.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=2, no_mark='ashore',
         words={'speak': 'Giấy phép ai làm người đó ký, em không ký thay.', 'alt': 'Anh lên ký, em giữ giấy chờ anh.'},
         back='Anh Hưng lên ký, tiện đọc lại phần cô lập. Hóa ra anh chưa biết van V-12 phải khóa.',
         give='Bạn ký thay. Giấy phép ghi tên người không có mặt ở hiện trường. Lúc diễn tập, trưởng ca đếm người theo giấy phép thì thiếu một.'),
    dict(id='dk-smoke', kind='corner', rank='crew', emoji='🚬', title='Hút điếu thuốc sau container', who='Bác Sửu · thợ sơn',
         text='Bác Sửu rút gói thuốc, ngoắc bạn ra sau container: “Phòng hút thuốc xa quá. Hút ở đây, gió thổi bay hết, ai biết.”',
         push=['“Một điếu thôi, làm gì căng.”', '“Tụi trẻ bây giờ nhát quá.”'],
         persist=(1, 2), mood=(0, 1), weight=2, severe=3, no_mark='ashore',
         words={'speak': 'Ở đây là khu nguy hiểm, cấm lửa. Bác vô phòng hút thuốc đi.', 'alt': 'Con đi cùng bác vô phòng hút thuốc.'},
         back='Bác Sửu lầm bầm rồi cất gói thuốc, đi vô phòng hút thuốc có quạt hút và cửa chống cháy.',
         give='Bạn đứng hút cùng. Đầu dò khói gần đó kêu, cả giàn báo động. Hai bác cháu đứng trước chị Hạnh mà không ai nói được câu nào.'),
    dict(id='dk-booze', kind='corner', rank='crew', emoji='🍶', title='Chai rượu giấu trong vali', who='Anh Khôi · thợ vận hành ca đêm',
         text='Anh Khôi mở hé vali: một chai rượu nếp quấn khăn. “Tối nay sinh nhật tao. Một ly thôi rồi ngủ, sáng tỉnh như sáo.”',
         push=['“Có ai thổi nồng độ trên giàn đâu.”', '“Không uống là không phải anh em nha.”'],
         persist=(1, 3), mood=(0, 2), weight=2, severe=3, no_mark='ashore',
         words={'speak': 'Trên giàn cấm cồn tuyệt đối. Em không uống, anh cũng đừng.', 'alt': 'Xuống nhà ăn, cô Sáu làm bánh kem, mình hát mừng.'},
         back='Anh Khôi cất chai rượu, mai giao cho chị Hạnh niêm phong gửi về bờ. Tối đó cô Sáu làm bánh flan, cả ca hát mừng sinh nhật.',
         give='Bạn uống một ly. Ca đêm anh Khôi đọc nhầm đồng hồ áp. Sáng hôm sau cả hai bị đưa về bờ chuyến trực thăng đầu tiên.',
         report='Bạn báo chị Hạnh. Chai rượu được niêm phong gửi về bờ, anh Khôi bị nhắc nhở. Tối đó cả ca vẫn có bánh mừng sinh nhật.'),
    dict(id='dk-hidenm', kind='corner', rank='boss', emoji='🙊', title='“Đừng báo vụ rơi cờ lê”', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='“Vụ cái cờ lê rơi hôm qua đó, không trúng ai thì thôi, đừng báo. Giàn đang sắp đủ 1.000 ngày không sự cố, có thưởng cả đội.”',
         push=['“Báo lên là cả đội mất thưởng vì em đó.”', '“Có ai bị gì đâu mà báo.”'],
         persist=(2, 3), mood=(0, 1), weight=2, severe=2, no_mark='ashore', min_day=3,
         words={'speak': 'Suýt sự cố cũng phải báo, lần sau có thể trúng người.', 'alt': 'Báo kèm cách sửa: dây chống rơi cho dụng cụ.'},
         back='Anh Bảo gãi đầu rồi gật. Báo cáo gửi đi, tuần sau cả giàn được phát dây chống rơi cho dụng cụ.',
         give='Bạn im lặng. Ba hôm sau một cái mỏ lết rơi đúng chỗ đó, sượt qua vai một thợ nhà thầu.',
         report='Bạn gửi báo cáo suýt sự cố. Chị Hạnh cảm ơn trước cả đội: báo suýt sự cố không bao giờ làm mất thưởng an toàn.'),
    dict(id='dk-skipdrill', kind='corner', rank='boss', emoji='🗂️', title='“Diễn tập thì điểm danh giùm”', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='“Chiều nay diễn tập bỏ giàn. Em ở lại làm nốt cái bơm, anh nhờ thằng Gấu quẹt thẻ điểm danh giùm em.”',
         push=['“Diễn tập thôi mà, có cháy thật đâu.”', '“Bơm không xong mai tàu dầu tới không có nước làm mát đâu đó.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=2, no_mark='ashore',
         words={'speak': 'Có báo động là em dừng việc ra điểm tập trung, không ai quẹt thẻ thay.', 'alt': 'Diễn tập xong em làm bù, xin thêm một tiếng.'},
         back='Bạn đi diễn tập. Trưởng xuồng đếm đủ người trong bốn phút. Bơm xong trước giờ cơm tối.',
         give='Gấu quẹt thẻ giùm. Bảng đếm người báo bạn ở xuồng, mà bạn đang ở phòng bơm. Lỡ cháy thật, đội cứu hộ sẽ không ai đi tìm bạn.'),
    dict(id='dk-mute', kind='corner', rank='crew', emoji='🔕', title='Tắt chuông báo cho đỡ ồn', who='Vinh · trực phòng điều khiển',
         text='Vinh bật nhạc to trong phòng điều khiển, tay gạt tắt tiếng chuông cảnh báo: “Báo mức cao bình tách hoài, tao nghe mỏi tai rồi.”',
         push=['“Có màn hình mà, nhìn là thấy.”', '“Mày ở phòng điều khiển bao giờ chưa mà dạy tao?”'],
         persist=(1, 2), mood=(0, 2), weight=2, severe=3, no_mark='ashore', min_day=3,
         words={'speak': 'Chuông báo phải bật, báo mức cao là phải xử lý.', 'alt': 'Báo chú Toàn kiểm van điều khiển mức.'},
         back='Vinh tắt nhạc, bật lại chuông. Chú Toàn xuống kiểm: van điều khiển mức bị kẹt, sửa xong là hết báo.',
         give='Chuông tắt. Hai tiếng sau bình tách đầy tràn sang đường khí, cả giàn phải dừng sản xuất khẩn cấp.'),
    # --- awkward, pushy, strange demands
    dict(id='dk-snore', kind='demand', rank='crew', emoji='😴', title='Bạn cùng phòng ngáy như máy nén', who='Tuấn “Gấu” · bạn cùng phòng', npc=GAU,
         text='Hai giờ sáng. Gấu ngáy rung cả giường tầng, còn mở loa điện thoại coi bóng đá: “Mày ngủ chưa? Đá pen nè, coi chung đi!”',
         push=['“Có xíu nữa hết hiệp phụ mà, mày khó tính quá.”', '“Tao ngáy hồi nào? Mày ngáy thì có.”'],
         persist=(1, 3), mood=(0, 1), weight=3, no_mark='ashore',
         words={'no': 'Tắt loa đi, mai tụi mình ca 6 giờ.', 'rule': 'Giờ nghỉ là giờ nghỉ, ca sau cần tỉnh.', 'alt': 'Đeo tai nghe đi, mai mình kể tỉ số.',
                'why': 'Mày mất ngủ hả, có chuyện gì không?'},
         back='Gấu đeo tai nghe, quay vô tường. Tiếng ngáy vẫn còn, nhưng bạn có nút tai của chị Thoa phát. Sáng ra Gấu mua bù hộp sữa.',
         give='Bạn coi bóng đá tới ba giờ. Ca sáng bạn ngáp liên tục, đọc nhầm số đồng hồ hai lần.',
         review={'back': [5, 'Ừ thì tao ngáy thật 😅 Cảm ơn mày không chửi tao.'], 'stuck': [3, 'Đêm qua tụi mình cãi nhau vụ cái loa, xin lỗi nha.']}),
    dict(id='dk-galley', kind='demand', rank='crew', emoji='🍲', title='“Cơm như cơm tù”', who='Anh Tâm · thợ hàn nhà thầu',
         text='Anh Tâm đập khay xuống bàn: “Cơm gì như cơm tù! Mày quen cô Sáu, lên nói cô nấu lẩu mắm cho anh em, không thì tao đăng nhóm công ty.”',
         push=['“Đi dầu khí lương cao mà ăn uống như này à?”', '“Nói giùm có câu mà cũng không dám.”'],
         persist=(1, 3), mood=(1, 2), weight=3, no_mark='ashore',
         words={'no': 'Anh góp ý thì ghi vào sổ góp ý nhà ăn nha.', 'rule': 'Thực đơn do bộ phận hậu cần duyệt, không đổi theo một người.',
                'alt': 'Tối thứ Bảy nhà ăn có buổi món quê, anh đề xuất lẩu mắm đi.', 'why': 'Món nào anh không ăn được?'},
         back='Anh Tâm ghi vào sổ góp ý. Thứ Bảy cô Sáu nấu lẩu mắm thật, anh Tâm ăn ba chén, khen nức nở.',
         give='Bạn lên “xin” cô Sáu đổi thực đơn. Cô Sáu buồn cả buổi: “Cô nấu cho tám chục người chứ đâu nấu cho một người.”'),
    dict(id='dk-rice', kind='demand', rank='crew', emoji='🍚', title='Vác bao gạo 25 kg lên ba tầng', who='Cô Sáu · bếp trưởng', npc=SAU,
         text='“Con ơi, thang máy hàng hư rồi, con vác giùm cô bao gạo 25 kg lên kho trên tầng ba nha. Cô yếu tay quá.”',
         push=['“Có ba tầng thôi mà, trai tráng/con gái khỏe mạnh.”', '“Lát nữa tới giờ nấu rồi con ơi.”'],
         persist=(0, 2), mood=(0, 0), weight=2, no_mark='ashore',
         words={'no': 'Một mình con không vác 25 kg lên thang dốc được cô ơi.', 'rule': 'Hàng nặng phải hai người hoặc dùng pa lăng.',
                'alt': 'Con gọi Gấu, hai đứa chia bao nhỏ ra chuyển.', 'why': 'Thang máy hàng báo sửa chưa cô?'},
         back='Bạn với Gấu chia gạo ra bốn bao nhỏ, chuyển hai chuyến. Cô Sáu dúi cho mỗi đứa một cái bánh bao.',
         give='Bạn vác một mình. Tới chiếu nghỉ tầng hai thì nhói lưng, phải ngồi bệt. Chị Thoa cho nghỉ việc nặng hai hôm.',
         review={'back': [5, 'Con chịu khó mà biết giữ lưng. Cô thương.'], 'give': [3, 'Cô nhờ bậy làm con đau lưng, cô áy náy quá.']}),
    dict(id='dk-wifi', kind='demand', rank='crew', emoji='📶', title='Mượn tài khoản Wi-Fi', who='Lính mới Quý · thợ phụ',
         text='“Cho em mượn tài khoản Wi-Fi của anh/chị nha, quota em hết rồi, tối nay em live bán hàng cho mẹ em.”',
         push=['“Một tối thôi mà, keo vl.”', '“Anh/chị có xài hết đâu.”'],
         persist=(1, 2), mood=(0, 1), weight=2, no_mark='ashore',
         words={'no': 'Tài khoản đứng tên mình, không cho mượn được.', 'rule': 'Mỗi người một tài khoản, mất an toàn thông tin.',
                'alt': 'Em xin thêm quota ở phòng hành chính giàn.', 'why': 'Live gì mà cần nhiều vậy em?'},
         back='Quý lên phòng hành chính xin thêm quota cho “việc gia đình”. Chị Hạnh duyệt cho ba ngày.',
         give='Bạn cho mượn. Hôm sau tài khoản của bạn bị khóa vì tải dữ liệu vượt mức, đúng lúc Má gọi video.'),
    dict(id='dk-borrowmon', kind='demand', rank='crew', emoji='📟', title='Mượn máy đo khí cá nhân', who='Anh Hưng · thợ điện',
         text='“Cho anh mượn máy đo khí cá nhân của em, máy anh để quên trong phòng. Em làm bên ngoài, khỏi đeo cũng được mà.”',
         push=['“Em ở boong chính, có khí đâu mà sợ.”', '“Đi về phòng lấy mất mười lăm phút đó.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=2, no_mark='ashore',
         words={'no': 'Máy này em đang đeo, em không đưa được.', 'rule': 'Ai vào khu công nghệ cũng phải có máy đo riêng.',
                'alt': 'Kho an toàn còn máy dự phòng, anh mượn ở đó.'},
         back='Anh Hưng lên kho an toàn lấy máy dự phòng, thử khí mẫu xong mới đi làm.',
         give='Bạn đưa máy rồi đi tuần tay không. Đi ngang khu bình tách thì nghe mùi lạ, mà không có máy để biết là bao nhiêu.'),
    dict(id='dk-tiktok', kind='demand', rank='crew', emoji='🤳', title='Quay TikTok trên sân trực thăng', who='Lính mới Quý · thợ phụ',
         text='“Quay giúp em clip ‘một ngày làm dầu khí’ ở sân trực thăng với khu đầu giếng đi, trend đang hot, triệu view luôn!”',
         push=['“Mấy anh khác cũng quay mà.”', '“Có lộ gì đâu, quay cho đẹp thôi.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=1, no_mark='ashore',
         words={'no': 'Không quay trong khu công nghệ được em.', 'rule': 'Điện thoại thường không mang vào khu nguy hiểm, quay phải xin phép.',
                'alt': 'Quay ở nhà ăn với phòng giải trí thôi, lấy cảnh biển lúc hoàng hôn.', 'why': 'Em định đăng ở đâu?'},
         back='Hai người quay ở boong nghỉ lúc hoàng hôn, cảnh biển đẹp như phim. Clip có vài nghìn tim, không lộ gì của giàn.',
         give='Bạn quay ở khu đầu giếng. Clip lộ sơ đồ van và biển số giếng. Phòng truyền thông công ty gọi điện, giọng không vui.'),
    dict(id='dk-vip', kind='demand', rank='pax', emoji='🕶️', title='Khách VIP không chịu đội mũ', who='Ông Hùng · khách mời của đối tác',
         text='Ông khách mời đi thăm giàn, kính đen, giày tây: “Tôi là khách của tổng giám đốc. Đội mũ hư tóc, cho tôi vào khu máy nén chụp vài tấm.”',
         push=['“Cậu có biết tôi là ai không?”', '“Gọi sếp cậu ra đây.”'],
         persist=(2, 3), mood=(1, 2), weight=2, breach=2, no_mark='ashore',
         words={'no': 'Dạ chưa đủ đồ bảo hộ thì không vào được ạ.', 'rule': 'Ai vào khu công nghệ cũng phải đủ đồ bảo hộ, khách cũng vậy.',
                'alt': 'Con dẫn chú ra boong nghỉ, chụp toàn cảnh giàn đẹp hơn.', 'why': 'Chú cần ảnh để làm gì ạ?'},
         back='Ông khách đội mũ, đeo kính, chụp ảnh ở boong nghỉ. Về bờ ông khen giàn “làm việc chuyên nghiệp”.',
         give='Bạn cho ông vào khu máy nén không đồ bảo hộ. Ông trượt chân trên vệt dầu, kính đen văng xuống lưới sàn.'),
    dict(id='dk-press', kind='demand', rank='pax', emoji='📸', title='“Phóng viên” xin chụp khu xử lý khí', who='Cô Vân · tự giới thiệu là phóng viên',
         text='Một cô đi theo đoàn kiểm tra, đeo thẻ “báo chí”: “Cho chị chụp khu xử lý khí với phòng điều khiển, chị viết bài khen giàn mình.”',
         push=['“Chị có thẻ mà em, sợ gì.”', '“Không cho chụp thì chị viết bài ‘giàn khoan bí ẩn’ nha.”'],
         persist=(1, 3), mood=(0, 1), weight=2, breach=1, no_mark='ashore',
         words={'no': 'Em không tự cho chụp được ạ.', 'rule': 'Chụp ảnh trên giàn phải có giấy phép của công ty.', 'alt': 'Chị liên hệ phòng truyền thông, họ có ảnh chính thức.',
                'why': 'Chị đi theo đoàn nào ạ?'},
         back='Cô Vân hẹn liên hệ phòng truyền thông. Sau mới biết cô không thuộc đoàn nào: một người bán hàng muốn chụp để quảng cáo.',
         give='Bạn dẫn cô chụp. Tuần sau ảnh phòng điều khiển lên trang quảng cáo một công ty lạ, kèm dòng “đối tác của giàn Hải Âu”.'),
    dict(id='dk-helimam', kind='demand', rank='pax', emoji='🫙', title='Hũ mắm ruốc lên trực thăng', who='Chú Lộc · hành khách cùng chuyến bay',
         text='Ở cảng trực thăng, chú Lộc dúi hũ mắm ruốc vào túi bạn: “Túi chú quá ký rồi. Con cầm giùm, lên giàn chú lấy. Mắm nhà làm, ngon lắm.”',
         push=['“Hũ nhỏ xíu mà con.”', '“Giúp người già có xíu cũng không được.”'],
         persist=(1, 2), mood=(0, 1), weight=2, breach=1,
         words={'no': 'Con không cầm đồ của người khác lên trực thăng được chú.', 'rule': 'Hành lý ai nấy khai, ai nấy cân.',
                'alt': 'Chú gửi tàu dịch vụ chuyến sau, đóng thùng kín.'},
         back='Chú Lộc gửi hũ mắm theo tàu dịch vụ. Ba hôm sau cả bàn ăn có mắm ruốc xào sả.',
         give='Bạn cầm giùm. Máy soi hành lý phát hiện thêm cái bật lửa chú giấu trong hũ. Bạn đứng giải trình nửa tiếng.'),
    dict(id='dk-seatswap', kind='demand', rank='pax', emoji='💺', title='Đòi ngồi cạnh cửa mà không thắt dây', who='Anh Phong · kỹ sư lần đầu ra giàn',
         text='Anh Phong run run: “Tôi sợ bay. Cho tôi ngồi sát cửa thoát hiểm, dây an toàn tôi để lỏng để lỡ có gì nhảy ra liền.”',
         push=['“Tôi tự lo cho tôi được.”', '“Thắt chặt vậy tôi thở không nổi.”'],
         persist=(0, 2), mood=(0, 1), weight=2, breach=1,
         words={'no': 'Dây phải thắt chặt anh ơi.', 'rule': 'Lúc bay dây an toàn phải chặt, có sự cố mới tháo.',
                'alt': 'Đổi chỗ được, nhưng anh thắt dây chặt, em chỉ anh tay nắm mốc cửa.', 'why': 'Anh sợ nhất lúc nào?'},
         back='Anh Phong ngồi cạnh cửa, dây thắt chặt, tay đặt lên mốc cửa như bạn chỉ. Xuống giàn anh bắt tay bạn thật lâu.',
         give='Anh Phong ngồi với dây lỏng. Trực thăng rung qua vùng gió, anh bị xô vào vách khoang, bầm cả vai.'),
    dict(id='dk-newbie', kind='demand', rank='crew', emoji='🤢', title='Lính mới say sóng nhờ làm thay', who='Lính mới Quý · thợ phụ',
         text='Quý mặt tái mét: “Em say sóng quá, anh/chị đi tuần khu bơm giùm em luôn nha, em nằm xíu. Đừng nói chú Toàn nha.”',
         push=['“Em ói ba lần rồi, thương em đi.”', '“Nói chú Toàn là em bị đánh giá kém đó.”'],
         persist=(0, 2), mood=(0, 1), weight=2, no_mark='ashore',
         words={'no': 'Say sóng thì phải báo, không giấu được em.', 'rule': 'Không khỏe thì báo trưởng ca, ca sẽ xếp lại người.',
                'alt': 'Đưa em xuống chị Thoa, rồi mình báo chú Toàn xếp lại việc.', 'why': 'Em ăn uống gì chưa?'},
         back='Chị Thoa cho Quý nằm phòng y tế, uống nước. Chú Toàn xếp người khác đi tuần khu bơm. Không ai đánh giá kém người say sóng.',
         give='Bạn làm thay mà không báo. Bảng tuần tra ghi tên Quý mà người đi là bạn; Quý nằm một mình trong phòng, không ai biết.'),
    dict(id='dk-latechat', kind='demand', rank='boss', emoji='💬', title='Sếp nhắn nhóm lúc 11 giờ đêm', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='11 giờ đêm, nhóm chat “Bảo dưỡng giàn Hải Âu 🔧”: “Em xem lại kế hoạch tuần, trả lời anh trong 5 phút. Sáng mai họp với bờ.”',
         push=['“Seen mà không rep hả em?”', '“Thôi, mai họp anh nói em không hợp tác.”'],
         persist=(1, 3), mood=(0, 2), weight=2, no_mark='ashore',
         words={'no': 'Em đang giờ nghỉ, 6 giờ sáng em gửi anh.', 'rule': 'Giờ nghỉ giữa hai ca phải đủ, em làm sai số liệu thì nguy.',
                'alt': 'Em gửi anh bản nháp ba ý chính, sáng em bổ sung.', 'why': 'Họp bờ cần phần nào nhất anh?'},
         back='Anh Bảo thả một like. Sáu giờ sáng bạn gửi bản kế hoạch, cuộc họp với bờ suôn sẻ.',
         give='Bạn thức tới một giờ sửa kế hoạch. Ca sáng bạn lơ mơ, quên khóa một van trong danh sách cô lập.'),
    dict(id='dk-callsignal', kind='demand', rank='kin', emoji='📵', title='Má gọi video lúc sóng chập chờn', who='Má · ở quê', npc=MA,
         text='Đang giờ nghỉ trưa thì Má gọi, hình đứng hình nhòe nhoẹt: “Alo… con… nghe… không? Sao… mặt… con… ốm vậy? Con… ăn… gì… chưa?”',
         push=['“Alo? Mất rồi… Con có nghe má nói không? Gọi lại đi con!”', '“Con không thương má hả, sao không nói gì hết?”'],
         persist=(1, 3), mood=(0, 1), weight=3, no_mark='ashore',
         words={'no': 'Sóng yếu quá má ơi, con nhắn tin nha.', 'rule': 'Tối con xong ca, lên phòng giải trí có sóng con gọi lại.',
                'alt': 'Con nhắn tin hình bữa trưa cho má coi.', 'why': 'Ở nhà có chuyện gì không má?', 'joke': 'Con ăn ba chén cơm, mập lên rồi nè má.'},
         back='Bạn nhắn ảnh khay cơm có cá kho. Má thả ba cái tim. Tối đó gọi video ở phòng giải trí, hình rõ, Má cười tít mắt.',
         give='Bạn leo lên lan can sân trực thăng tìm sóng. Chị Hạnh gọi xuống: khu đó cấm vào khi không có chuyến bay.',
         review={'back': [5, 'Con nhắn hình là má yên tâm rồi. Ăn nhiều vô nghe con.'], 'stuck': [3, 'Gọi hoài không được, má lo muốn chết.']}),
    dict(id='dk-matchmake', kind='demand', rank='kin', emoji='💘', title='Má mai mối giữa đợt đi biển', who='Má · ở quê', npc=MA,
         text='“Con gái/con trai bà Tư mới đi làm về, ngoan lắm. Chủ nhật này con xin về sớm xem mắt nha, má hẹn người ta rồi.”',
         push=['“Ba mươi rồi chứ ít gì, đi biển hoài ai lấy.”', '“Má hẹn rồi, con không về là má mất mặt với bà Tư đó.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'no': 'Con chưa muốn xem mắt má ơi.', 'rule': 'Đợt đi biển là 14 ngày, con không về giữa chừng được.',
                'alt': 'Đợt sau về con mời bạn ấy uống cà phê, tự nói chuyện.', 'why': 'Sao tự nhiên má lo chuyện này vậy?', 'joke': 'Con lấy giàn khoan rồi má ơi.'},
         back='Má thở dài, rồi cười: “Ừ, về rồi tính.” Má hẹn lại bà Tư sang tháng.',
         give='Bạn xin về sớm. Chú Toàn phải tìm người thay gấp, cả ca làm bù hai ngày. Buổi xem mắt kéo dài đúng mười lăm phút.'),
    dict(id='dk-jealous', kind='demand', rank='kin', emoji='💔', title='“Chọn em hay cái giàn?”', who='Người yêu · ở thành phố',
         text='Tin nhắn liên tục: “Sao tối qua không nghe máy? Trên đó có ai hả? Bỏ cái nghề đi biển đi, chọn em hay cái giàn?”',
         push=['“Lại bận. Lúc nào cũng bận.”', '“Không trả lời là biết rồi đó.”'],
         persist=(1, 3), mood=(1, 2), weight=2, no_mark='ashore',
         words={'no': 'Anh/em không bỏ nghề được, nhưng anh/em không bỏ mình.', 'rule': 'Trong ca không cầm điện thoại, an toàn của cả giàn.',
                'alt': 'Mỗi tối 9 giờ mình gọi video, mình hẹn giờ cố định nha.', 'why': 'Dạo này có chuyện gì làm mình buồn hả?', 'joke': 'Trên này chỉ có Gấu ngáy thôi 😅'},
         back='Hai người hẹn giờ gọi cố định mỗi tối. Đêm đó gọi tới khi cả hai ngủ quên, màn hình còn sáng.',
         give='Bạn hứa sẽ nghỉ việc cho vui lòng. Một tuần sau hai người lại cãi nhau, lần này vì chuyện tiền.'),
    dict(id='dk-schoolday', kind='demand', rank='kin', emoji='🎒', title='Bé Vy giận vì vắng khai giảng', who='Bé Vy · em gái lớp 6',
         text='Bé Vy nhắn tin thoại, giọng mếu: “Khai giảng ai cũng có anh chị đưa đi, có mình em không. Anh/chị về đi, về liền đi!”',
         push=['“Lúc nào cũng đi biển, em ghét cái giàn khoan!”', '“Không về thì em không nói chuyện nữa.”'],
         persist=(0, 2), mood=(0, 1), weight=2, no_mark='ashore',
         words={'no': 'Lần này anh/chị không về được, Vy ơi.', 'rule': 'Đợt đi biển chưa xong, giàn cần đủ người.',
                'alt': 'Sáng khai giảng mình gọi video, Vy cho anh/chị coi áo mới nha.', 'why': 'Ở trường có chuyện gì làm Vy buồn hả?'},
         back='Sáng khai giảng bé Vy xoay điện thoại cho bạn xem sân trường. Cả lớp vẫy tay chào “anh/chị dầu khí”.',
         give='Bạn hứa về mà không về được. Bé Vy giận cả tuần, Má phải dỗ mãi.'),
    # --- the family asks for money (bargains: the player pays per unit accepted)
    dict(id='dk-roofmoney', kind='bargain', rank='kin', emoji='🏚️', title='Má xin tiền sửa nhà mùa bão', who='Má · ở quê', npc=MA,
         text='“Mái nhà dột rồi con, bão lại sắp vô. Con gửi về năm phần, mỗi phần 6 xu, má gom thay mái luôn cho chắc.”',
         push=['“Thêm chút nữa đi con, mua tôn rồi còn tiền công.”', '“Con đi dầu khí lương cao mà, có nhiêu đâu.”'],
         persist=(1, 2), mood=(0, 1), weight=3, ask=5, limit=3, unit='phần', pay=-6, tire=0, cost=2,
         words={'rule': 'Con phải để dành, tháng sau còn đóng bảo hiểm.', 'health': 'Tháng này con cũng kẹt má ơi.',
                'alt': 'Con gửi đủ thay ba tấm dột trước, mái mới để đợt sau.', 'paper': 'Má gửi con báo giá của thợ nha.', 'yes': 'Gửi hết.'},
         deal='Má: “Ừ, {n} phần, má lo được.”', lawful='Má thở dài mà hiểu: “Ừ, con cũng phải để dành.”',
         penalty='Má buồn, cúp máy. Tối đó em gái nhắn “má khóc đó”; bạn gửi thêm {cost} xu tiền mua trái cây cho má.',
         give='Bạn gửi hết {n} phần. Má mừng ra mặt; tháng này bạn chỉ còn đúng tiền ăn sáng.'),
    dict(id='dk-iphone', kind='bargain', rank='kin', emoji='📱', title='Em trai đòi điện thoại mới', who='Thằng Tí · em trai lớp 10',
         text='“Anh/chị ơi, mua cho em cái điện thoại đời mới đi, 4 phần mỗi phần 8 xu thôi. Bạn em đứa nào cũng có, em quê lắm 😭”',
         push=['“Đi dầu khí giàu mà keo vậy?”', '“Thôi 3 phần cũng được, đi mà.”'],
         persist=(1, 3), mood=(0, 1), weight=2, ask=4, limit=1, unit='phần', pay=-8, tire=0, cost=0,
         words={'rule': 'Máy em vẫn xài tốt, anh/chị không mua máy mới.', 'health': 'Tiền này để đóng học cho Vy.',
                'alt': 'Anh/chị góp một phần, phần còn lại em tự để dành.', 'paper': 'Em kể anh/chị nghe máy cũ hư chỗ nào.', 'yes': 'Mua luôn.'},
         deal='Tí: “Ok, {n} phần cũng được, em tự góp thêm.”', lawful='Tí hờn một buổi, rồi nhắn “thôi em để dành”.',
         penalty='Tí giận, block bạn hai ngày.',
         give='Bạn chuyển đủ {n} phần. Tí khoe máy mới trên mạng, còn bạn thì nhịn trà sữa cả tháng.'),
    dict(id='dk-crypto', kind='bargain', rank='kin', emoji='🕶️', title='Anh họ rủ góp vốn “tiền ảo”', who='Anh Tuấn · anh họ',
         text='“Góp với anh 5 phần, mỗi phần 10 xu vô dự án tiền ảo, tháng sau lời gấp ba. Người nhà anh mới rủ đó nghen!”',
         push=['“Không góp là tiếc cả đời đó em.”', '“Một phần thôi cũng được, cho có duyên.”'],
         persist=(2, 3), mood=(0, 1), weight=2, ask=5, limit=0, unit='phần', pay=-10, tire=0, cost=0,
         words={'rule': 'Lời gấp ba một tháng thì không phải đầu tư anh ơi.', 'health': 'Em không có tiền nhàn rỗi.',
                'alt': 'Anh gửi giấy phép của dự án em xem.', 'paper': 'Cho em xem hợp đồng, giấy phép.', 'yes': 'Góp liền.'},
         deal='Anh Tuấn: “Ờ, {n} phần thì {n} phần.”', lawful='Anh Tuấn bĩu môi: “Không tin người nhà.” Hai tháng sau dự án sập, anh Tuấn mất trắng.',
         penalty='Anh Tuấn kể với cả họ là bạn keo.',
         give='Bạn góp {n} phần. Hai tháng sau trang web dự án biến mất, cùng số tiền.'),
    dict(id='dk-weddinggift', kind='bargain', rank='kin', emoji='💒', title='Dì Năm định mức mừng cưới', who='Dì Năm · dì ruột',
         text='“Đám cưới con dì, con mừng ít nhất 5 phần, mỗi phần 6 xu nghen. Làm dầu khí mà mừng ít, họ hàng người ta cười cho.”',
         push=['“Thằng con bà Bảy làm công nhân còn mừng nhiêu đó.”', '“Bốn phần thôi, không thể ít hơn.”'],
         persist=(1, 3), mood=(0, 1), weight=2, ask=5, limit=2, unit='phần', pay=-6, tire=0, cost=0,
         words={'rule': 'Con mừng theo sức con, dì đừng so.', 'health': 'Tháng này con lo học phí cho Vy.',
                'alt': 'Con mừng hai phần, về con phụ dì dọn rạp.', 'paper': 'Trong xóm thường mừng nhiêu dì?', 'yes': 'Mừng đủ.'},
         deal='Dì Năm: “Ừ, {n} phần, có lòng là được.”', lawful='Dì Năm hơi phật ý, rồi nói “có lòng là quý”.',
         penalty='Dì Năm nói bóng gió cả buổi tiệc.',
         give='Bạn mừng đủ {n} phần. Dì Năm khoe cả xóm, còn bạn ăn mì gói tới đợt lương sau.'),
    # --- work bargains: the company leans on its people
    dict(id='dk-extend', kind='bargain', rank='boss', emoji='📆', title='Ở lại thêm thay người ốm', who='Phòng điều phối nhân sự · trên bờ',
         text='“Bạn ca sau bị ốm. Em ở lại thêm 2 đợt ngắn nha, mỗi đợt ba ngày, có phụ cấp. Ai cũng phải xoay mà.”',
         push=['“Thiếu người thật mà em, giúp công ty lần này.”', '“Không ở thì giàn thiếu người vận hành, em tính sao?”'],
         persist=(1, 3), mood=(0, 1), weight=2, ask=2, limit=1, unit='đợt ngắn', pay=12, tire=2, cost=8, no_mark='ashore', min_day=3,
         words={'rule': 'Quá 21 ngày liên tục là vượt quy định giờ làm.', 'health': 'Em mệt rồi, cần về nghỉ.',
                'alt': 'Em ở thêm ba ngày, gọi người dự bị từ bờ ra.', 'paper': 'Cho em xin quyết định bằng văn bản.', 'yes': 'Ở hết.'},
         deal='Phòng nhân sự: “Ok, {n} đợt ngắn, có phụ cấp đầy đủ.”', lawful='Phòng nhân sự gọi người dự bị từ bờ ra. Quy định giờ làm đứng về phía bạn.',
         penalty='Phòng nhân sự: “Không hợp tác thì đợt sau xếp lịch khó đó.” Trừ {cost} xu thưởng chuyên cần.',
         give='Bạn ở thêm cả {n} đợt. Phụ cấp về đủ, còn bạn thì mệt rũ, nằm đâu ngủ đó.'),
    dict(id='dk-overtime', kind='bargain', rank='boss', emoji='🌙', title='Làm thêm ca đêm cho kịp tiến độ', who='Anh Bảo · giám sát bảo dưỡng', npc=BAO,
         text='“Tuần này dồn việc. Em làm thêm 3 ca đêm, mỗi ca 4 tiếng nha. Sáng làm, đêm làm, trẻ mà, khỏe re!”',
         push=['“Hai ca thôi cũng được.”', '“Người ta tranh nhau làm thêm, em được ưu tiên đó.”'],
         persist=(1, 3), mood=(0, 1), weight=2, ask=3, limit=1, unit='ca đêm', pay=6, tire=1, cost=6, no_mark='ashore',
         words={'rule': 'Làm 12 tiếng rồi, thêm nữa là quá giờ nghỉ tối thiểu.', 'health': 'Thiếu ngủ thì đọc đồng hồ sai.',
                'alt': 'Em làm thêm một ca, xếp người khác ca còn lại.', 'paper': 'Anh gửi lịch làm thêm có chữ ký trưởng giàn.', 'yes': 'Nhận hết.'},
         deal='Anh Bảo: “Chốt {n} ca đêm.”', lawful='Anh Bảo hậm hực, xếp thêm người. Quy định giờ nghỉ đứng về phía bạn.',
         penalty='Anh Bảo: “Không hợp tác thì tháng này khỏi thưởng nhóm.” Trừ {cost} xu.',
         give='Bạn nhận cả {n} ca đêm. Tiền về túi, mắt thâm như gấu trúc.'),
    # --- PG-13 charm: decline, set the line
    dict(id='dk-charmboat', kind='charm', rank='pax', emoji='⚓', title='Thuyền viên tàu dịch vụ rủ hóng gió', who='Một thuyền viên tàu dịch vụ',
         text='Tin nhắn lạ: “Tối nay tàu mình neo cạnh giàn. 1 giờ sáng ra boong sau hóng gió với mình đi, mình mang trà sữa 😉”',
         push=['“Chỉ hóng gió thôi mà, đâu có gì.”', '“Khó gần ghê, mai mình gửi quà lên giàn nha.”'],
         persist=(1, 2), mood=(0, 1), weight=2, no_mark='ashore',
         words={'rule': 'Ban đêm không ai ra boong sau một mình, khu đó hạn chế.', 'alt': 'Cảm ơn nha, chúc chuyến tàu bình an.'},
         back='Tin nhắn dừng ở đó. Sáng ra tàu dịch vụ nhổ neo, kéo còi chào cả giàn.',
         give='Bạn ra boong sau lúc 1 giờ sáng. Bảo vệ ca đêm soi đèn, ghi tên bạn vào sổ “ra khu hạn chế không lý do”.'),
    dict(id='dk-charmaudit', kind='charm', rank='boss', emoji='🍷', title='Kiểm toán viên mời ăn tối riêng', who='Ông Khiêm · kiểm toán viên đoàn đánh giá',
         text='“Hồ sơ an toàn của em còn vài lỗi nhỏ. Tối về bờ đi ăn riêng với anh, anh ‘bỏ qua’ cho, em lên hạng nhanh.”',
         push=['“Ăn tối thôi mà, em ngại gì.”', '“Em nghĩ kỹ đi, hồ sơ nằm trong tay anh đó.”'],
         persist=(2, 3), mood=(0, 1), weight=1, min_day=4,
         words={'rule': 'Lỗi trong hồ sơ em sửa theo quy trình, không cần ai bỏ qua.', 'alt': 'Có gì anh trao đổi ở buổi họp chung nha.'},
         back='Ông Khiêm cười gượng. Buổi họp chung hôm sau ông đọc lỗi, bạn đã sửa xong từ trước.',
         give='Bạn đi ăn tối. Tuần sau cả đoàn biết chuyện, hồ sơ của bạn bị đánh dấu “cần xem lại tính độc lập”.'),
    # --- harassment and bullying: never the victim's fault; reporting is always right
    dict(id='dk-harassmedic', kind='harass', rank='crew', emoji='🚨', title='Thợ nhà thầu buông lời khiếm nhã với chị Thoa', who='Một thợ nhà thầu ở nhà ăn',
         text='Ở nhà ăn, một thợ nhà thầu cứ chắn đường chị Thoa, buông lời trêu khiếm nhã: “Y tá gì mà xinh vậy, khám riêng cho anh đi.” Chị Thoa nhìn bạn.',
         push=['Gã vẫn cười hô hố, kéo ghế chặn lối ra của chị Thoa.', '“Đùa xíu thôi mà, làm gì căng.”'],
         persist=(2, 3), mood=(1, 2), weight=2, follow='dk_harass_back', no_mark='ashore',
         words={'stop': 'Dừng lại ngay. Tránh đường cho chị Thoa.', 'no': 'Đứng giữa, mời chị Thoa đi trước.', 'rule': 'Quấy rối trên giàn là vi phạm, sẽ bị lập biên bản.',
                'duty': 'Tôi đang trực, anh về chỗ đi.', 'joke': 'Cười cho qua.', 'later': 'Thôi, bỏ qua đi.', 'yes': 'Kệ, chuyện của người khác.'},
         back='Gã lầm bầm rồi về chỗ. Chị Thoa nói nhỏ: “Cảm ơn em. Lần sau mình báo luôn nha.”',
         report='Bạn báo chú Toàn và chị Hạnh. Gã bị lập biên bản, đưa về bờ chuyến trực thăng sau. Chị Thoa được cả giàn đứng về phía mình.',
         stuck='Gã quậy tới hết bữa rồi bỏ đi, không biên bản nào. Không phải lỗi của chị Thoa; lần sau báo luôn.',
         give='Không ai được làm ngơ trước quấy rối. Chị Thoa phải tự xoay xở, mắt đỏ hoe.'),
    dict(id='dk-harassback', kind='harass', rank='crew', emoji='⚠️', title='Gã thợ nhà thầu lại giở giọng', who='Gã thợ nhà thầu hôm trước', need_mark='dk_harass_back',
         text='Gã thợ nhà thầu hôm trước lại đứng chờ ở cửa phòng y tế, gọi với vào: “Y tá ơi, anh đau tim nè, ra khám đi.”',
         push=['Gã gõ cửa phòng y tế, cười cợt.', '“Có ai làm gì được tao đâu.”'],
         persist=(2, 3), mood=(1, 2), weight=3, no_mark='ashore',
         back='Gã bỏ đi khi thấy bạn đứng chắn cửa và gọi bộ đàm.',
         report='Lần này có biên bản. Nhà thầu rút gã khỏi giàn, cấm quay lại. Chị Thoa ôm chầm chị Hạnh.',
         stuck='Gã vẫn lởn vởn. Báo là quyền của chị Thoa và của bạn: hãy báo.',
         give='Không ai được làm ngơ. Chị Thoa khóa cửa phòng y tế cả buổi chiều.'),
    dict(id='dk-hazing', kind='harass', rank='crew', emoji='📹', title='Ma cũ “thử lòng” ma mới', who='Nhóm thợ ca đêm',
         text='Mấy thợ ca đêm bắt lính mới Quý chui vào gầm bơm dính dầu “cho quen nghề”, còn quay clip cười hô hố.',
         push=['“Truyền thống mà, đứa nào mới cũng vậy.”', '“Mày lo chuyện mày đi.”'],
         persist=(1, 3), mood=(1, 2), weight=2, no_mark='ashore',
         words={'stop': 'Dừng lại. Quý ra đây.', 'no': 'Không ai phải làm vậy hết.', 'rule': 'Bắt nạt và quay clip người khác là vi phạm.',
                'duty': 'Gầm bơm đang chạy, nguy hiểm.', 'joke': 'Cười theo cho qua.', 'later': 'Để mai tính.', 'yes': 'Đứng xem.'},
         back='Nhóm thợ tản ra. Quý chui ra, run run cảm ơn. Clip bị xóa ngay tại chỗ.',
         report='Bạn báo chú Toàn. Clip bị xóa, nhóm thợ bị nhắc nhở trước cả ca. Quý được kèm cặp đàng hoàng.',
         stuck='Clip vẫn lan trong nhóm chat. Quý im lặng cả tuần. Lần sau, báo luôn.',
         give='Bạn đứng xem. Quý trầy cả tay, clip lan khắp nhóm chat.'),
    # --- shore-day oddities (the neighbourhood when you are home)
    dict(id='dk-neighbouroil', kind='corner', rank='kin', emoji='🛢️', title='Chú hàng xóm xin “ít dầu nhớt công ty”', who='Chú Tư · hàng xóm',
         text='“Con làm dầu khí mà, lần sau ra giàn lấy giùm chú can dầu nhớt về chạy ghe. Công ty lớn vậy mất vài lít ai biết.”',
         push=['“Có vài lít mà con, chú trả tiền xăng xe.”', '“Thằng con bà Bảy làm giàn khác nó lấy cho người ta hoài.”'],
         persist=(1, 3), mood=(0, 1), weight=2, severe=3, need_mark='ashore',
         words={'speak': 'Đồ của công ty là của công ty, con không lấy được chú.', 'rule': 'Lấy đồ công ty là trộm cắp, bị đuổi việc.',
                'alt': 'Con chỉ chú tiệm bán nhớt ghe giá tốt ở chợ.'},
         back='Chú Tư cười xòa: “Ừ thôi, chú giỡn.” Bạn chở chú ra tiệm nhớt ở chợ, được bớt giá.',
         give='Bạn hứa lấy giùm. Đợt sau bảo vệ cảng trực thăng soi túi, thấy can nhớt không có phiếu xuất kho.'),
    dict(id='dk-relatives', kind='demand', rank='kin', emoji='🧓', title='Cả họ hỏi lương', who='Bác Hai · trưởng họ',
         text='Đám giỗ, bác Hai nói to giữa mâm: “Nghe nói đi dầu khí lương trăm mấy xu một ngày hả? Vậy đám giỗ năm sau cháu bao hết nghen!”',
         push=['“Giàu rồi quên họ hàng hả cháu?”', '“Nói lương đi, có gì đâu mà giấu.”'],
         persist=(1, 3), mood=(0, 1), weight=2, need_mark='ashore',
         words={'no': 'Dạ lương là chuyện riêng của con bác ơi.', 'rule': 'Lương đi biển cao vì đi xa, nguy hiểm, mỗi tháng con ở nhà có nửa tháng thôi bác.',
                'alt': 'Năm sau con góp phần của con như mọi người bác nha.', 'why': 'Sao bác hỏi vậy bác?', 'joke': 'Lương cao mà toàn ăn mì gói đó bác.'},
         back='Cả mâm cười. Bác Hai gật gù: “Ừ, góp như mọi người là được.”',
         give='Bạn hứa bao đám giỗ năm sau. Cả họ nhớ lời hứa đó còn kỹ hơn nhớ ngày giỗ.'),
    dict(id='dk-taxi', kind='demand', rank='pax', emoji='🚕', title='Xe ôm ở cảng hét giá', who='Anh xe ôm · cổng cảng trực thăng',
         text='Vừa ra cổng cảng trực thăng, anh xe ôm giành túi: “Dân dầu khí mà, về thị trấn 30 xu, khỏi trả giá cho mất sang!”',
         push=['“Dân giàu mà trả giá như bà bán cá.”', '“Đi thì đi, không thì thôi, chiều mưa đó.”'],
         persist=(1, 2), mood=(0, 2), weight=2, need_mark='ashore',
         words={'no': 'Giá thường 8 xu anh ơi.', 'rule': 'Bảng giá ở cổng cảng ghi 8 xu.', 'alt': 'Em đi xe đưa đón của công ty.', 'why': 'Sao giá cao vậy anh?'},
         back='Bạn lên xe đưa đón của công ty, miễn phí, còn có máy lạnh. Anh xe ôm quay sang mời người khác.',
         give='Bạn trả 30 xu. Tới nơi mới thấy bảng giá ở cổng cảng ghi 8 xu.', fx={'give': {'money': -6}}),
]

# ---------------------------------------------------------------- surprises (kit desk scripts; mods = hitch phase)
RIG_DAYS = ('rig', 'stay')
DESK = [
    dict(id='gull', title='Hải âu làm tổ trên lan can sân trực thăng', emoji='🐦', npc=HSE, min_day=2, tone='gentle', at='between', weight=2, mods=RIG_DAYS,
         text='Một cặp hải âu làm tổ ngay lan can sân trực thăng. Gấu đề nghị leo ra hất tổ đi “cho trực thăng đáp an toàn”.',
         options=[dict(id='report', label='Báo chị Hạnh và tổ sân bay, không tự leo ra mép giàn', hint='Đúng người, đúng việc', effects=dict(xp=6), good=True,
                       outcome='Tổ sân bay dời tổ chim sang góc khuất có lưới che. Chuyến trực thăng chiều đáp êm.'),
                  dict(id='climb', label='Leo qua lan can hất tổ cho nhanh', hint='Nhanh…', effects=dict(review=[2, 'Leo qua lan can mép giàn không dây an toàn. Không bao giờ nhé.']),
                       good=False, outcome='Bạn chới với ở mép giàn, chị Hạnh hét giật lại. Tổ chim vẫn ở đó.'),
                  dict(id='leave', label='Kệ, không phải việc của mình', hint='', effects={}, good=None, outcome='Chuyến trực thăng chiều phải lượn thêm một vòng vì chim bay lên.')],
         default='leave'),
    dict(id='dolphin', title='Đàn cá heo quanh chân giàn', emoji='🐬', npc=SAU, min_day=2, tone='gentle', at='between', weight=2, mods=RIG_DAYS,
         text='Đàn cá heo bơi quanh chân giàn lúc hoàng hôn. Mấy người đòi ném bánh mì, vỏ chai xuống “cho tụi nó chơi”.',
         options=[dict(id='watch', label='Ngắm từ boong nghỉ, nhắc mọi người không ném gì xuống biển', hint='', effects=dict(xp=5), good=True,
                       outcome='Cả ca đứng ngắm, cô Sáu chụp được tấm ảnh đẹp nhất mùa. Không mảnh rác nào rơi xuống biển.'),
                  dict(id='throw', label='Ném mẩu bánh mì xuống cho vui', hint='', effects=dict(review=[3, 'Rác từ giàn xuống biển là vi phạm môi trường đó con.']), good=False,
                       outcome='Bánh mì trôi lềnh bềnh cùng túi ni-lông ai đó ném theo. Chị Hạnh nhắc cả ca.')],
         default='watch'),
    dict(id='nofishsauce', title='Nhà ăn hết nước mắm', emoji='🐟', npc=SAU, min_day=2, tone='gentle', at='between', weight=2, mods=RIG_DAYS,
         text='Tàu dịch vụ trễ hai ngày, nhà ăn hết nước mắm. Cô Sáu rầu rĩ, nửa giàn kêu “ăn gì cũng nhạt”.',
         options=[dict(id='help', label='Phụ cô Sáu làm muối sả ớt, nhắn bờ gửi nước mắm chuyến sau', hint='Mất chút giờ nghỉ', effects=dict(xp=5, patience=-2), good=True,
                       outcome='Bữa tối có muối sả ớt chấm gà luộc, cả giàn khen ngon hơn cả nước mắm.'),
                  dict(id='complain', label='Đăng nhóm công ty chê nhà ăn', hint='', effects=dict(review=[2, 'Cô biết cơm nhạt, mà con đăng nhóm làm cô buồn.']), good=False,
                       outcome='Phòng hậu cần trên bờ gọi điện hỏi cô Sáu. Cô Sáu buồn cả ngày.'),
                  dict(id='ignore', label='Ăn đỡ, không nói gì', hint='', effects={}, good=None, outcome='Bữa cơm nhạt trôi qua trong im lặng.')],
         default='ignore'),
    dict(id='nosignal', title='Mất sóng đúng lúc Má gọi', emoji='📵', npc=MA, min_day=2, tone='gentle', at='between', weight=2, mods=RIG_DAYS,
         text='Giờ nghỉ, Má gọi video, sóng chập chờn. Có người chỉ: “Leo lên lan can sân trực thăng là có 4G!”',
         options=[dict(id='text', label='Nhắn tin hẹn tối gọi ở phòng giải trí có Wi-Fi', hint='', effects=dict(xp=4), good=True,
                       outcome='Tối gọi video rõ nét, Má khoe con gà mái mới đẻ trứng.'),
                  dict(id='climb', label='Leo lên lan can sân trực thăng bắt sóng', hint='Có 4G…', effects=dict(review=[2, 'Khu sân trực thăng cấm vào khi không có chuyến bay.', HSE]), good=False,
                       outcome='Tổ sân bay gọi bạn xuống. Má chỉ kịp thấy mặt bạn nhòe nhoẹt rồi mất.'),
                  dict(id='skip', label='Thôi, mai gọi', hint='', effects={}, good=None, outcome='Má gọi thêm ba cuộc nhỡ. Tối bạn mới thấy.')],
         default='skip'),
    dict(id='blocked', title='Thùng sơn chắn lối thoát hiểm', emoji='🚪', npc=HSE, min_day=2, tone='tense', at='between', weight=2, mods=RIG_DAYS,
         text='Đi ngang hành lang khu ở, bạn thấy ba thùng sơn của nhà thầu chắn ngang lối thoát hiểm ra xuồng B.',
         options=[dict(id='move', label='Dời thùng vào kho sơn, báo chị Hạnh nhắc nhà thầu', hint='', effects=dict(xp=6), good=True,
                       outcome='Lối thoát hiểm thông. Chiều đó diễn tập, cả ca ra xuồng B nhanh hơn mọi lần.'),
                  dict(id='later', label='Ghi nhớ, lát báo', hint='', effects={}, good=None, outcome='Tới tối mới nhớ ra. Thùng sơn vẫn nằm đó cả buổi.'),
                  dict(id='ignore', label='Kệ, của nhà thầu', hint='', effects=dict(review=[2, 'Lối thoát hiểm bị chắn cả ngày mà không ai báo.', HSE]), good=False,
                       outcome='Lúc diễn tập, hai người vấp thùng sơn ở hành lang.')],
         default='later'),
    dict(id='falsealarm', title='Còi báo khí kêu lúc nửa đêm', emoji='🟡', npc=TOAN, min_day=2, tone='tense', at='between', weight=2, mods=RIG_DAYS,
         text='Hai giờ sáng, còi báo khí kêu. Gấu trùm chăn: “Báo giả đó, tuần này kêu hai lần rồi, ngủ tiếp đi.”',
         options=[dict(id='go', label='Dậy mặc đồ, gọi Gấu, đi về điểm tập trung', hint='Coi mọi còi là thật', effects=dict(xp=8, patience=-2), good=True,
                       outcome='Lần này là báo giả thật. Chú Toàn khen hai đứa có mặt trong ba phút: “Coi mọi tiếng còi là thật.”'),
                  dict(id='sleep', label='Ngủ tiếp, chắc báo giả', hint='', effects=dict(review=[1, 'Còi kêu mà hai đứa nằm trong phòng. Lỡ thật thì sao?', TOAN]), good=False,
                       outcome='Đội tìm kiếm phải lên tận phòng gõ cửa vì bảng đếm thiếu hai người.')],
         default='sleep'),
    dict(id='plastic', title='Có người định vứt rác xuống biển', emoji='🗑️', npc=HSE, min_day=3, tone='gentle', at='between', weight=1, mods=RIG_DAYS,
         text='Một thợ nhà thầu cầm túi rác định quăng qua lan can: “Biển rộng mà, thùng rác xa quá.”',
         options=[dict(id='stop', label='Nhắc anh ấy bỏ vào thùng phân loại, chỉ chỗ thùng gần nhất', hint='', effects=dict(xp=5), good=True,
                       outcome='Túi rác vào đúng thùng. Rác trên giàn được gom về bờ xử lý.'),
                  dict(id='ignore', label='Kệ', hint='', effects=dict(review=[2, 'Rác từ giàn xuống biển là vi phạm môi trường.']), good=False,
                       outcome='Túi rác trôi dập dềnh dưới chân giàn. Tàu dịch vụ phải vớt lên.')],
         default='ignore'),
    dict(id='seasick', title='Say sóng trên trực thăng', emoji='🤢', npc=THOA, min_day=1, tone='gentle', at='open', weight=2, mods=('out',),
         text='Trực thăng rung qua vùng gió, bạn nôn nao. Người ngồi cạnh dúi cho viên thuốc lạ: “Uống đi, thuốc say xe của tôi, hay lắm.”',
         options=[dict(id='bag', label='Cảm ơn, không uống thuốc của người khác; nhìn đường chân trời, dùng túi nôn, báo tổ bay', hint='', effects=dict(xp=5), good=True,
                       outcome='Bạn nhìn đường chân trời, hít thở chậm. Lên giàn chị Thoa hỏi han, cho nằm nghỉ mười phút.'),
                  dict(id='pill', label='Uống luôn cho đỡ', hint='', effects=dict(review=[2, 'Không uống thuốc của người khác khi chưa hỏi y tế, nhất là trước ca làm.', THOA]),
                       good=False, outcome='Bạn buồn ngủ díp mắt suốt buổi chiều. Chị Thoa cho bạn nghỉ ca đầu.')],
         default='bag'),
    dict(id='helidelay', title='Trực thăng đổi giờ vì sương', emoji='🌫️', npc=HSE, min_day=2, tone='gentle', at='open', weight=2, mods=('out', 'wait'),
         text='Cảng trực thăng báo hoãn 90 phút vì sương. Anh Bảo gọi: “Có tàu cá quen ra gần giàn, đi nhờ cho kịp ca!”',
         options=[dict(id='wait', label='Chờ chuyến trực thăng ở phòng chờ, báo anh Bảo giờ mới', hint='Đúng quy trình', effects=dict(xp=6), good=True,
                       outcome='Sương tan, trực thăng cất cánh. Bạn tới giàn trễ, nhưng đúng đường, đủ đồ bảo hộ.'),
                  dict(id='boat', label='Đi nhờ tàu cá cho kịp', hint='Không có áo phao…', effects=dict(review=[1, 'Đi tàu cá ra giàn không đăng ký, không áo phao. Tuyệt đối không.', HSE]),
                       good=False, outcome='Tàu cá không được cập giàn. Bạn lênh đênh hai tiếng rồi quay vào bờ, ướt sũng.')],
         default='wait'),
    dict(id='weighin', title='Khai cân nặng trước giờ bay', emoji='⚖️', npc=GAU, min_day=2, tone='gentle', at='open', weight=2, mods=('out',),
         text='Quầy cảng trực thăng cân người kèm đồ bơi. Gấu thì thầm: “Khai bớt năm ký đi mày, tao khai bớt bảy ký rồi, ai mà biết.”',
         options=[dict(id='true', label='Khai đúng cân nặng, nhắc Gấu khai lại cho đúng', hint='Trực thăng tính tải theo từng người',
                       effects=dict(xp=5), good=True, outcome='Tổ bay tính lại tải, xếp chỗ cân hai bên. Gấu gãi đầu khai lại, quầy cảm ơn hai đứa.'),
                  dict(id='less', label='Khai bớt cho đỡ ngại', hint='', effects=dict(review=[2, 'Khai sai cân nặng là tổ bay tính sai tải. Đừng vậy nữa.', HSE]), good=False,
                       outcome='Nhân viên cảng cân lại, thấy lệch, bắt khai lại trước cả hàng người.')],
         default='true'),
    dict(id='shower', title='Nước ngọt trên giàn sắp cạn', emoji='🚿', npc=TOAN, min_day=3, tone='gentle', at='between', weight=2, mods=RIG_DAYS,
         text='Máy lọc nước ngọt hỏng một dàn, phòng điều khiển xin mọi người tắm nhanh. Phòng bên cạnh vẫn có người tắm ba mươi phút, vừa tắm vừa hát.',
         options=[dict(id='note', label='Gõ cửa nhắc nhẹ, dán thông báo tiết kiệm nước ở phòng tắm chung', hint='', effects=dict(xp=4), good=True,
                       outcome='Tiếng hát ngưng, vòi nước tắt. Tối đó bồn nước ngọt còn đủ cho ca đêm.'),
                  dict(id='same', label='Mình cũng tắm lâu, ai cũng vậy mà', hint='', effects=dict(review=[3, 'Thiếu nước mà cả dãy tắm như ở nhà, ca đêm không còn nước rửa tay.', TOAN]),
                       good=False, outcome='Nửa đêm bồn nước ngọt cạn, ca đêm phải chờ máy lọc chạy lại.')],
         default='note'),
    dict(id='taxiwait', title='Về bờ: cả họ chờ ở cổng', emoji='🎉', npc=MA, min_day=2, tone='gentle', at='open', weight=2, mods=('home',),
         text='Vừa ra cổng cảng trực thăng, cả nhà đứng chờ, mang theo… ba người họ hàng muốn “đi ké xe về thành phố”.',
         options=[dict(id='hug', label='Ôm Má trước, rồi hẹn họ hàng đi xe khách', hint='', effects=dict(xp=4), good=True,
                       outcome='Má khóc rồi cười. Họ hàng đi xe khách, hẹn tối qua nhà ăn cơm.'),
                  dict(id='pay', label='Bao taxi cho cả đám', hint='Tốn tiền', effects=dict(money=-10), good=None, outcome='Taxi chật cứng, ai cũng vui, ví bạn thì mỏng đi.')],
         default='hug'),
    dict(id='sleepvs', title='Ngủ bù hay đi nhậu?', emoji='🛏️', npc=GAU, min_day=2, tone='gentle', at='between', weight=2, mods=('home', 'wait'),
         text='Về bờ ngày đầu, hội bạn rủ đi nhậu tới khuya. Mắt bạn vẫn còn lệch giờ sau 14 ngày làm ca.',
         options=[dict(id='sleep', label='Hẹn bạn cà phê sáng mai, tối nay ngủ bù', hint='', effects=dict(xp=4), good=True,
                       outcome='Bạn ngủ một mạch mười tiếng. Sáng cà phê với hội bạn, tỉnh như sáo.'),
                  dict(id='drink', label='Đi tới bến', hint='', effects=dict(money=-6), good=None, outcome='Vui thì vui, sáng hôm sau đầu đau như búa bổ.')],
         default='sleep'),
    dict(id='stormcall', title='Bão: cả nhà gọi liên tục', emoji='🌀', npc=MA, min_day=4, tone='tense', at='open', weight=3, mods=('stay',),
         text='Tin bão trên tivi. Má gọi năm cuộc liền: “Giàn có sập không con? Sao không về? Công ty có cho con về không?”',
         options=[dict(id='calm', label='Gọi video trấn an: giàn chịu được bão, mọi người theo kế hoạch, về khi trực thăng bay được', hint='', effects=dict(xp=6), good=True,
                       outcome='Má thấy bạn ngồi trong khu ở chắc chắn, đèn sáng, mới yên tâm đi nấu cơm.'),
                  dict(id='scare', label='Kể sóng cao như nhà ba tầng cho Má biết mà lo', hint='', effects=dict(review=[2, 'Con kể sóng to như vậy, má thức trắng đêm.', MA]), good=False,
                       outcome='Má thức trắng đêm, gọi cả xóm đi thắp nhang.')],
         default='calm'),
    dict(id='leakroom', title='Nước mưa rò vào khu ở', emoji='💧', npc=TOAN, min_day=4, tone='gentle', at='between', weight=2, mods=('stay',),
         text='Mưa bão tạt, nước rò qua khe cửa sổ phòng 207, nhỏ giọt ngay ổ cắm điện.',
         options=[dict(id='report', label='Ngắt điện ổ cắm, lau khô, báo trưởng ca gọi thợ điện', hint='', effects=dict(xp=6), good=True,
                       outcome='Thợ điện bọc ổ cắm, dán kín khe cửa. Phòng 207 khô ráo qua đêm.'),
                  dict(id='towel', label='Nhét khăn vào khe, kệ ổ cắm', hint='', effects={}, good=None, outcome='Ổ cắm xẹt điện lúc nửa đêm, cầu dao nhảy cả dãy phòng.')],
         default='towel'),
]

# ---------------------------------------------------------------- situations (sit_ engine)
SITUATIONS = [
    dict(id='DK-S01', title='Ép kịp tàu dịch vụ', npc=BAO, tone='tense', min_day=1,
         opening='Anh Bảo giục: “Thay lọc F-310 cho kịp tàu dịch vụ 10 giờ. Bỏ bước đo khí, khu này tuần nào cũng sạch!”',
         swap='Bạn là anh Bảo, bị bờ gọi điện dí tiến độ, tàu dịch vụ đang chờ.',
         facts=[dict(id='permit', title='Giấy phép làm việc', source='Bảng giấy phép', text='Giấy phép ghi: đo khí trước khi mở bình lọc, giới hạn 10% LEL.'),
                dict(id='time', title='Mất bao lâu', source='Chị Hạnh', text='Đo khí mất hai phút. Tàu dịch vụ đợi được tới 10 giờ 30.'),
                dict(id='stop', title='Quyền dừng việc', source='Sổ tay an toàn giàn', text='Ai trên giàn cũng có quyền dừng việc khi thấy không an toàn, không bị phạt vì dừng.')],
         options=[dict(id='test', label='Dùng quyền dừng việc: đo khí hai phút rồi làm, báo anh Bảo giờ xong', requires=['permit', 'time'], quality='good', stars=5,
                       review='Em không nghe anh bỏ bước. Hai phút mà anh yên tâm cả tuần.',
                       outcome='Máy đo báo 0% LEL. Lọc thay xong 10 giờ 15, tàu dịch vụ còn chờ.',
                       perspectives=[dict(who='Anh Bảo', emoji='📞', text='Tôi dí vì sợ bờ trách. Nhưng nếu có chuyện, bờ sẽ hỏi tôi vì sao bỏ bước.'),
                                     dict(who='Chị Hạnh', emoji='🦺', text='Dừng việc đúng lúc là làm đúng nghề.')]),
                  dict(id='quick', label='Đo nhanh ở một điểm cho có', requires=['permit'], quality='ok', stars=3,
                       review='Có đo, nhưng chỉ một điểm xa mặt bích.', outcome='Không sao lần này, nhưng chị Hạnh dặn phải đo sát chỗ làm.',
                       perspectives=[dict(who='Chị Hạnh', emoji='🦺', text='Đo cho có là chưa đo.'), dict(who='Chú Toàn', emoji='👷', text='Đo ở chỗ mình mở, không phải chỗ mình đứng.')]),
                  dict(id='skip', label='Nghe anh Bảo, bỏ bước đo khí', quality='bad', stars=1,
                       review='Bỏ bước đo khí, mở bình thì nghe mùi khí xộc lên. Không bao giờ nữa.',
                       outcome='Mùi khí xộc lên khi mở nắp. Cả khu phải sơ tán, giấy phép bị khóa.',
                       perspectives=[dict(who='Anh Bảo', emoji='😰', text='Tôi tưởng tiết kiệm được hai phút.'),
                                     dict(who='Chị Hạnh', emoji='🦺', text='Hai phút đó là thứ giữ mạng người.')])],
         lesson='Không tiến độ nào đáng để bỏ một bước an toàn. Ai cũng có quyền dừng việc.'),
    dict(id='DK-S02', title='Van lọt “chút xíu”', npc=TOAN, tone='tense', min_day=2,
         opening='Xả áp xong, đồng hồ vẫn 4 bar. Thợ nhà thầu bảo: “Lọt chút xíu thôi, nới bích từ từ cho xì hết.”',
         facts=[dict(id='gauge', title='Đồng hồ áp', source='Đồng hồ giữa hai van', text='Xả mười phút mà kim vẫn đứng 4 bar: một van đang lọt.'),
                dict(id='double', title='Cô lập hai lớp', source='Chú Toàn', text='Đóng thêm van chặn phía trước, xả lại: cô lập hai lớp.'),
                dict(id='oil', title='Trong ống', source='Sơ đồ công nghệ', text='Đường ống chứa dầu nóng 64 °C.')],
         options=[dict(id='stop', label='Dừng việc, báo chú Toàn, cô lập thêm một lớp rồi xả lại', requires=['gauge', 'double'], quality='good', stars=5,
                       review='Thấy kim không về 0 là dừng. Đúng bài.', outcome='Cô lập hai lớp, xả lại: kim về 0. Mở bích an toàn.',
                       perspectives=[dict(who='Chú Toàn', emoji='👷', text='Không về không thì không mở. Không có “chút xíu”.'),
                                     dict(who='Thợ nhà thầu', emoji='🧰', text='Tôi quen làm ẩu, lần này học được.')]),
                  dict(id='wait', label='Chờ thêm mười phút xem có về không', requires=['gauge'], quality='ok', stars=3,
                       review='Có chờ, nhưng chờ thì van vẫn lọt.', outcome='Mười phút sau kim vẫn 4 bar. Cuối cùng vẫn phải báo chú Toàn.',
                       perspectives=[dict(who='Chú Toàn', emoji='👷', text='Chờ không sửa được van lọt.')]),
                  dict(id='crack', label='Nới bích từ từ cho xì hết', quality='bad', stars=1,
                       review='Nới bích khi còn áp, dầu nóng phụt ra. May lùi kịp.', outcome='Dầu nóng phụt ra khỏi bích, bắn lên sàn. Cả khu phải dừng.',
                       perspectives=[dict(who='Chị Thoa', emoji='🩺', text='Dầu 64 độ, trúng mặt là bỏng nặng.'),
                                     dict(who='Chị Hạnh', emoji='🦺', text='Bích không phải van xả.')])],
         lesson='Chưa chứng minh được về không áp, về không điện thì chưa được mở. Van lọt thì cô lập thêm lớp nữa.'),
    dict(id='DK-S03', title='Checklist ký khống', npc=HSE, tone='tense', min_day=2,
         opening='Anh Lực nhà thầu đưa checklist giàn giáo đã ký đủ mười ô, chỉ chờ bạn ký nhận.',
         swap='Bạn là anh Lực, nhà thầu bị dí tiến độ, tin tay nghề của đội mình.',
         facts=[dict(id='form', title='Tờ checklist', source='Tờ giấy anh Lực đưa', text='Mười ô đã ký cùng một nét bút, cùng giờ 7:00, trước cả lúc dựng xong.'),
                dict(id='walk', title='Kiểm tận nơi', source='Quy định giàn giáo', text='Người nhận giàn giáo phải tự kiểm từng mục tại chỗ rồi mới ký.'),
                dict(id='tag', title='Thẻ giàn giáo', source='Chị Hạnh', text='Thẻ xanh chỉ treo khi đã kiểm đủ; chưa kiểm là thẻ đỏ.')],
         options=[dict(id='check', label='Đi kiểm cùng anh Lực từng mục, thiếu thì sửa rồi mới ký, báo chị Hạnh tờ ký sẵn', requires=['form', 'walk'], quality='good', stars=5,
                       review='Kiểm từng mục, phát hiện thiếu chốt tấm sàn. Cảm ơn em.', outcome='Thiếu một chốt sàn tầng hai. Lắp xong mới treo thẻ xanh.',
                       perspectives=[dict(who='Anh Lực', emoji='🧰', text='Tôi tưởng mình chắc tay. Hóa ra thằng phụ quên chốt.'),
                                     dict(who='Chị Hạnh', emoji='🦺', text='Chữ ký là lời hứa đã kiểm.')]),
                  dict(id='sample', label='Kiểm vài mục chính rồi ký', requires=['walk'], quality='ok', stars=3,
                       review='Kiểm được phần chính, còn sót tầng hai.', outcome='Chị Hạnh kiểm lại, thấy thiếu chốt. Bạn phải ký lại.',
                       perspectives=[dict(who='Chị Hạnh', emoji='🦺', text='Kiểm một nửa là ký một nửa sự thật.')]),
                  dict(id='sign', label='Ký luôn cho nhanh', quality='bad', stars=1, review='Ký khống, tấm sàn bật ra khi có người bước lên.',
                       outcome='Tấm sàn bật ra, thợ đứng trên may có móc dây an toàn.',
                       perspectives=[dict(who='Thợ trên giàn giáo', emoji='😨', text='Tôi tin cái thẻ xanh.'),
                                     dict(who='Chị Hạnh', emoji='🦺', text='Chữ ký của bạn ở ô người nhận.')])],
         lesson='Không ký vào điều mình chưa tận mắt kiểm. Thấy giấy ký sẵn thì báo.'),
    dict(id='DK-S04', title='Cái cờ lê suýt rơi', npc=HSE, tone='gentle', min_day=3,
         opening='Bạn làm trên sàn lưới tầng trên, cờ lê tuột tay rơi xuống, cắm xuống sàn dưới cách một thợ hai mét. Không ai thấy bạn.',
         facts=[dict(id='what', title='Chuyện gì xảy ra', source='Bạn', text='Cờ lê 1,2 kg rơi từ độ cao 6 m, cách người hai mét.'),
                dict(id='noblame', title='Báo suýt sự cố', source='Sổ tay an toàn giàn', text='Người tự báo không bị phạt. Báo cáo dùng để sửa cách làm cho cả giàn.'),
                dict(id='lanyard', title='Dây chống rơi dụng cụ', source='Kho an toàn', text='Kho có dây cột dụng cụ, chưa ai bắt buộc dùng ở sàn lưới.')],
         options=[dict(id='report', label='Tự báo suýt sự cố, đề xuất dây cột dụng cụ ở sàn lưới', requires=['what', 'noblame'], quality='good', stars=5,
                       review='Em tự báo, lại đề xuất được cách sửa. Tuần sau cả giàn dùng dây cột dụng cụ.', outcome='Cả giàn có quy định mới: làm trên sàn lưới phải cột dụng cụ.',
                       perspectives=[dict(who='Chị Hạnh', emoji='🦺', text='Mỗi báo cáo thật là một tai nạn không xảy ra.'),
                                     dict(who='Thợ ở sàn dưới', emoji='👷', text='Biết vậy tôi đội mũ cài quai chặt hơn.')]),
                  dict(id='sorry', label='Xin lỗi người thợ, hứa cẩn thận', quality='ok', stars=3, review='Biết lỗi là tốt, nhưng cả giàn không học được gì.',
                       outcome='Tuần sau ở sàn lưới khác lại rơi một cái mỏ lết.',
                       perspectives=[dict(who='Chị Hạnh', emoji='🦺', text='Lỗi một người có thể là bẫy cho người khác.')]),
                  dict(id='hide', label='Nhặt cờ lê, im lặng', quality='bad', stars=2, review='Im lặng thì lần sau có thể trúng người.',
                       outcome='Camera boong ghi lại. Chị Hạnh hỏi, bạn phải giải trình.',
                       perspectives=[dict(who='Chị Hạnh', emoji='🦺', text='Tự báo thì không bị phạt. Bị phát hiện thì khác.')])],
         lesson='Báo suýt sự cố, kể cả của chính mình, là cách giữ an toàn cho người sau.'),
    dict(id='DK-S05', title='Tiền gửi về nhà', npc=MA, tone='gentle', min_day=2,
         opening='Đợt này bạn nhận 60 xu phụ cấp đi biển. Má cần thuốc 20 xu, em Vy học phí 25 xu, anh họ rủ góp 50 xu “tiền ảo lời gấp ba”.',
         swap='Bạn là Má: con đi biển xa, lương cao, ai trong họ cũng nhờ vả.',
         facts=[dict(id='needs', title='Việc cần', source='Toa thuốc, giấy báo học phí', text='Thuốc 20 xu, học phí 25 xu: hai việc có giấy tờ, có hạn.'),
                dict(id='scam', title='Dự án của anh họ', source='Hỏi kỹ', text='Không giấy phép, chỉ “lời” khi kéo thêm người: kiểu đa cấp.'),
                dict(id='save', title='Để dành', source='Sổ của bạn', text='Đi biển có rủi ro, nên giữ lại một phần làm quỹ dự phòng.')],
         options=[dict(id='plan', label='Gửi thuốc và học phí, từ chối dự án, giữ 15 xu để dành, gọi video giải thích', requires=['needs', 'scam'], quality='good', stars=5,
                       review='Con lo đủ việc cần, còn để dành được. Má yên tâm.', outcome='Thuốc và học phí đủ, quỹ dự phòng có 15 xu, anh họ tự rút lui.',
                       perspectives=[dict(who='Má', emoji='👵', text='Con nói rõ ràng, má hiểu.'), dict(who='Bé Vy', emoji='🎒', text='Em đóng học đúng hạn rồi!')]),
                  dict(id='all', label='Chia đều cho ai xin cũng có', quality='bad', stars=2, review='Có tiền cho dự án mà thiếu tiền học của Vy.',
                       outcome='Phần cho anh họ mất trắng, học phí của Vy thiếu 5 xu.',
                       perspectives=[dict(who='Bé Vy', emoji='🎒', text='Em phải xin cô cho đóng trễ.'), dict(who='Anh họ', emoji='🕶️', text='(Dự án biến mất cùng số tiền.)')]),
                  dict(id='none', label='Không gửi gì, để dành hết', quality='ok', stars=3, review='Con để dành là tốt, mà thuốc của má hết rồi con.',
                       outcome='Má phải vay hàng xóm tiền thuốc. Quỹ của bạn thì đầy.',
                       perspectives=[dict(who='Má', emoji='👵', text='Má không trách, mà má tủi.')])],
         lesson='Lo việc cần trước, hỏi rõ trước khi gửi, không góp vào thứ “lời gấp ba”, và giữ một phần để dành.'),
    dict(id='DK-S06', title='Bão tới, ở lại thêm', npc=TOAN, tone='tense', min_day=4,
         opening='Áp thấp mạnh lên thành bão, trực thăng không bay. Má gọi khóc đòi về. Gấu rủ: “Có tàu dịch vụ chạy vô bờ tránh bão, xin quá giang đi!”',
         facts=[dict(id='plan', title='Kế hoạch ứng phó bão', source='Trưởng giàn', text='Tàu dịch vụ chỉ chở hàng khi tránh bão, không chở người nếu không có lệnh di tản.'),
                dict(id='safe', title='Khu ở', source='Chú Toàn', text='Khu ở của giàn thiết kế chịu bão cấp 12, có đủ đồ ăn nước uống 30 ngày.'),
                dict(id='family', title='Gia đình', source='Má', text='Má chỉ cần nghe giọng con mỗi tối để yên tâm.')],
         options=[dict(id='stay', label='Ở lại theo kế hoạch, giúp chằng buộc boong, mỗi tối gọi Má', requires=['plan', 'safe'], quality='good', stars=5,
                       review='Con ở lại đúng kế hoạch, tối nào cũng gọi má. Bão qua, con về khỏe re.', outcome='Bão đi qua sau hai ngày. Chuyến trực thăng đầu tiên đưa bạn về.',
                       perspectives=[dict(who='Má', emoji='👵', text='Nghe giọng con là má ngủ được.'), dict(who='Chú Toàn', emoji='👷', text='Ở lại là an toàn nhất.')]),
                  dict(id='call', label='Ở lại nhưng than với Má sóng to gió lớn', requires=['safe'], quality='ok', stars=3,
                       review='Con ở lại là đúng, mà kể chi cho má sợ.', outcome='Bạn an toàn, Má thì mất ngủ hai đêm.',
                       perspectives=[dict(who='Má', emoji='👵', text='Má thắp nhang cả đêm.')]),
                  dict(id='boat', label='Xin quá giang tàu dịch vụ vào bờ', quality='bad', stars=1,
                       review='Xin đi tàu dịch vụ giữa bão mà không có lệnh. Trưởng tàu từ chối, cả giàn biết chuyện.',
                       outcome='Trưởng tàu từ chối. Trưởng giàn nhắc tên bạn trong buổi họp an toàn.',
                       perspectives=[dict(who='Trưởng tàu dịch vụ', emoji='⚓', text='Tàu tôi không có chỗ cho người lúc bão.'),
                                     dict(who='Chú Toàn', emoji='👷', text='Giàn mới là chỗ an toàn nhất lúc này.')])],
         lesson='Lúc bão, kế hoạch ứng phó là luật. Ở lại an toàn, và gọi về cho gia đình yên tâm.'),
]

# ---------------------------------------------------------------- small stories of the people you work with
REG_STORY = {
    HSE: ('Chị Hạnh: “Chị không ghét người làm chậm. Chị ghét người làm tắt.”', 'Chị Hạnh kể con gái chị học lớp 3, vẽ giàn khoan có cầu vồng.',
          'Chị Hạnh để bạn đọc buổi họp an toàn đầu ca: “Em nói dễ hiểu đó.”'),
    TOAN: ('Chú Toàn: “Hồi chú mới ra giàn, chưa có máy đo khí cá nhân đâu.”', 'Chú Toàn chỉ bạn nghe tiếng máy nén: “Kêu đều là khỏe, kêu lạ là bệnh.”',
           'Chú Toàn ghi vào sổ kèm cặp: “Biết dừng đúng lúc. Có thể tự trưởng ca.”'),
    SAU: ('Cô Sáu dúi cho bạn hộp sữa chua: “Ăn đi con, ca dài lắm.”', 'Cô Sáu kể con trai cô cũng đi biển, tàu cá ở Phú Quốc.',
          'Cô Sáu nấu món canh chua bông điên điển như ở quê bạn.'),
    BAO: ('Anh Bảo càu nhàu: “Lại trễ tiến độ.”', 'Anh Bảo lần đầu nói “cảm ơn em đã dừng việc”.',
          'Anh Bảo đề xuất tên bạn vào danh sách thăng bậc.'),
    MA: ('Má: “Ăn uống đầy đủ nghe con, đừng có bỏ bữa.”', 'Má gửi lên giàn hộp mắm ruốc xào sả, dán băng keo ba lớp.',
         'Má kể cả xóm khen con Má đi làm dầu khí mà vẫn hiền.'),
    GAU: ('Gấu: “Tao ngáy hả? Đâu có đâu 😅”', 'Gấu mua cho bạn hộp nút tai xịn nhất ở cảng.', 'Gấu xin đổi ca ngủ cho bạn đỡ nghe tiếng ngáy.'),
    THOA: ('Chị Thoa đo huyết áp cho bạn: “Ngủ đủ chưa đó?”', 'Chị Thoa dạy cả ca cách sơ cứu bỏng dầu.', 'Chị Thoa khen bạn biết giữ lưng khi bê đồ nặng.'),
}

STORIES = [
    ('Ổ khóa mang tên mình', ('Ngày đầu ra giàn, chị Hạnh đưa bạn một ổ khóa đỏ khắc tên.',
                              '“Khóa này chỉ một chìa, chìa nằm trong túi em. Không ai được mở thay.”',
                              'Bạn treo ổ khóa lên cầu dao đầu tiên, tay hơi run.')),
    ('Tiếng còi lúc nửa đêm', ('Còi báo động kêu lúc hai giờ sáng.',
                               'Bạn kéo Gấu dậy, đi ngược gió về xuồng B, quẹt thẻ.',
                               'Chú Toàn đứng ở cửa xuồng, gật đầu: “Ba phút. Giỏi.”')),
    ('Hộp mắm của Má', ('Tàu dịch vụ mang lên hộp mắm ruốc dán ba lớp băng keo.',
                        'Cô Sáu xào với sả, cả bàn ăn hết sạch nồi cơm.',
                        'Tối đó bạn gọi video, cả bàn ăn cùng vẫy tay chào Má.')),
]
REVIEW_ASIDES = ['Khóa đủ điểm cô lập, không sót ổ nào.', 'Dừng việc đúng lúc, nói rõ lý do.', 'Đi tuần kỹ, đọc đồng hồ chuẩn.',
                 'Về điểm tập trung nhanh mà không chạy.']
