"""Gác chắn đường ngang Bến Mây: the fixed content of the railway career (game/careers/railway.py).

Everything is fictional: Xí nghiệp Đường sắt Sông Mây, ga Bến Mây and ga Bến Gỗ, the crossing at Km 7+250 on phố Ray,
the forms and the timings ("Nội quy gác chắn của xí nghiệp") are GAME rules. What they teach is the real habit of the
trade: read back every radio order, ring the bell before the arm comes down, never lift it for anyone while a train is
due, watch the whole train go by (the tail lamp!), ask the station before opening again, protect a dangerous defect
first and report it through the right channel. Safety is always the right answer; giving in is never rewarded.

Shapes (all lists and dicts, so a stored task equals its regenerated original after a JSON round trip):
* PEOPLE  (name, role, note, persona) — NPC ids railway_npc_01…
* CROWD   what can be on the crossing before it closes: works = the ways that clear it, steps = taps needed
* PUSH    the people at the lowered barrier: best / ok / bad answers, soft (reporting them would be cruel),
          sneaky (may duck under the arm), lines (first words, the push again)
* FINDS   what a track patrol can find, with what it needs: fix / protect / talk and the forms
* DESK    surprises (game/careers/kit.py desk scripts), ODD encounters (game/careers/air_odd.py scripts),
          SITUATIONS (the sit_ engine)
"""
from __future__ import annotations

COMPANY = 'Xí nghiệp Đường sắt Sông Mây'
STATION = 'Ga Bến Mây'
PREV = 'ga Bến Gỗ'
CROSSING = 'Đường ngang Km 7+250 · phố Ray'
DETOUR = 'cầu vượt Km 9'

PEOPLE = [
    ('Chú Sáu Cờ', 'Gác chắn lâu năm, người kèm bạn', 'Hai mươi tám năm cầm cờ ở đường ngang Bến Mây, nghe ray rung là biết tàu gì sắp tới.', 'warm'),
    ('Chị Nguyệt', 'Trực ban ga Bến Mây', 'Giọng bộ đàm sang sảng, ghét nhất ai nhắc lại lệnh ậm ừ.', 'bossy'),
    ('Anh Quý', 'Cung trưởng cung đường Sông Mây', 'Kiểm tra đột xuất bất kể giờ nào; sổ sai một dòng là nhắc cả tuần.', 'sour'),
    ('Bà Bông', 'Hàng nước chè sát đường ray', 'Ba chục năm bán nước đầu đường ngang, phơi đủ thứ lên ray, ghét nhất tiếng còi tàu.', 'sour'),
    ('Anh Tài', 'Tài xế xe ôm công nghệ', 'Ngày chạy hai chục cuốc, cuốc nào cũng “gấp lắm em ơi”.', 'genz'),
    ('Cô Mận', 'Chủ quán cà phê đường tàu', 'Quán nhỏ sát ray, khách tới chụp ảnh; cô muốn khách ngồi càng sát ray càng tốt.', 'picky'),
    ('Chú Hớn', 'Hàng xóm hay say', 'Hiền khô, chỉ tội chiều nào cũng vài chén, hay ngủ quên ở bờ ray.', 'quiet'),
    ('Anh Khải', 'Thợ tuần đường cung Sông Mây', 'Ít nói, mỗi ngày đi bộ mấy cây số ray, thuộc từng thanh tà vẹt.', 'quiet'),
]
SAU, HANH, QUY, LANH, TAI, MAN, LAM, KHAI = range(8)

# ---------------------------------------------------------------- the trains
TRAINS = [
    dict(id='se', code='SE', name='Tàu khách Thống Nhất', emoji='🚆', cars=(10, 14), kind='khach'),
    dict(id='tn', code='TN', name='Tàu khách nhanh', emoji='🚆', cars=(8, 12), kind='khach'),
    dict(id='dp', code='ĐP', name='Tàu địa phương', emoji='🚃', cars=(4, 6), kind='khach'),
    dict(id='h', code='H', name='Tàu hàng', emoji='🚂', cars=(18, 30), kind='hang'),
]
TRAIN = {x['id']: x for x in TRAINS}
# Odd numbers run north to south, even ones south to north (the habit of the real line, kept here).
DIRS = {1: 'Bắc → Nam', 0: 'Nam → Bắc'}

# ---------------------------------------------------------------- the morning hand-over: the equipment
EQUIP = [
    dict(id='bell', emoji='🔔', name='Chuông & đèn đỏ', test='Bấm thử chuông, nhìn hai cụm đèn đỏ', ok='Chuông kêu giòn, hai cụm đèn đỏ nhấp nháy đều.'),
    dict(id='arm', emoji='🚧', name='Cần chắn hai bên', test='Hạ thử rồi nâng cần chắn', ok='Cần chắn hạ êm, nâng êm, khóa chốt chắc.'),
    dict(id='radio', emoji='📻', name='Bộ đàm & điện thoại ga', test='Gọi thử ga Bến Mây', ok='Chị Nguyệt: “Ga nghe rõ. Chào ca mới.”'),
    dict(id='flags', emoji='🚩', name='Cờ đỏ, cờ xanh, đèn cầm tay, còi', test='Kiểm cờ, đèn, còi', ok='Cờ lành, đèn cầm tay sáng, còi kêu rõ.'),
    dict(id='book', emoji='📒', name='Sổ nhật ký & bảng giờ tàu', test='Đọc sổ giao ca, chép giờ tàu lên bảng', ok='Sổ giao ca đã đọc, bảng giờ tàu hôm nay đã chép.'),
    dict(id='vest', emoji='🦺', name='Đồng phục & áo phản quang', test='Mặc áo phản quang, đội mũ', ok='Áo phản quang, mũ, thẻ ngành: đủ.'),
]
EQUIP_IDS = [x['id'] for x in EQUIP]
FORMS = {
    'giao_ca': dict(emoji='📒', name='Ghi sổ giao ca', hint='việc nhỏ đã tự xử lý, ca sau cần biết'),
    'phieu': dict(emoji='🧾', name='Phiếu báo hỏng gửi cung', hint='cần thợ cung đường tới sửa'),
    'ga': dict(emoji='📞', name='Điện báo ga ngay', hint='ảnh hưởng an toàn chạy tàu'),
}
# Faults found at the hand-over: fix = the keeper can sort it out (spare battery, spare flag, hand crank); forms = what
# must be filed; danger = the station must know before the next train.
FAULTS = {
    'bulb': dict(item='bell', text='Một bóng đèn đỏ phía Nam không sáng.', fix=None, forms=['phieu'], danger=False,
                 why='Đèn đỏ thiếu một bóng, xe phía Nam khó thấy. Thợ cung phải thay bóng.'),
    'bell': dict(item='bell', text='Bấm mãi chuông chỉ rè rè rồi tắt.', fix='Lấy chuông tay dự phòng treo ở cửa chòi', forms=['phieu', 'ga'], danger=True,
                 why='Chuông hỏng: ga phải dặn lái tàu kéo còi dài từ xa, mình dùng chuông tay.'),
    'motor': dict(item='arm', text='Mô-tơ cần chắn phía Bắc kêu ù ù, cần không nhúc nhích.', fix='Lắp tay quay, hạ nâng bằng tay', forms=['phieu', 'ga'], danger=True,
                  why='Cần chắn kẹt: hôm nay phải quay tay, chậm hơn một phút. Ga cần biết để báo tàu sớm hơn.'),
    'battery': dict(item='radio', text='Bộ đàm nháy đèn pin yếu, tiếng rè rè.', fix='Thay pin dự phòng trong tủ', forms=['giao_ca'], danger=False,
                    why='Pin yếu thì mình tự thay; ghi sổ để ca sau sạc pin cũ.'),
    'lamp': dict(item='flags', text='Đèn cầm tay bật không lên.', fix='Thay pin đèn cầm tay', forms=['giao_ca'], danger=False,
                 why='Đèn cầm tay là tín hiệu ban đêm: thay pin ngay, ghi sổ.'),
    'flag': dict(item='flags', text='Lá cờ đỏ rách một đường dài, bạc màu.', fix='Lấy cờ đỏ dự phòng', forms=['phieu'], danger=False,
                 why='Cờ đỏ phải rõ màu. Dùng cờ dự phòng, xin cờ mới qua phiếu.'),
}
HANDOVER = [
    'Chú Sáu ghi: “Đêm qua tàu hàng H6 chậm 20 phút. Chốt cần chắn phía Nam hơi khô, chú đã tra dầu.”',
    'Chú Sáu ghi: “Chiều qua có thằng thanh niên chui chắn, đã ghi biển số. Ca sau để ý giờ tan tầm.”',
    'Chú Sáu ghi: “Bà Bông lại phơi ớt trên ray. Nhắc khéo, đừng to tiếng, bà dỗi cả tuần.”',
    'Chú Sáu ghi: “Cô Mận xin kê thêm ghế sát ray cho khách chụp ảnh. Chú không cho. Con cũng đừng cho.”',
    'Chú Sáu ghi: “Đèn chòi gác chập chờn, đã báo cung. Pin dự phòng còn hai cục trong tủ.”',
    'Chú Sáu ghi: “Chú Hớn hôm qua ngủ quên ở bờ ray lúc chập tối. Thấy là dìu vô, đừng để chú nằm đó.”',
]

# ---------------------------------------------------------------- before closing: what can be on the crossing
# works: whistle (thổi còi, phất cờ từ chòi) · go (ra tận nơi nhắc, dẫn vào lề) · help (phụ đẩy, lùa ra)
CROWD = {
    'selfie': dict(emoji='🤳', name='Hai bạn trẻ đứng giữa ray chụp ảnh', works=['whistle', 'go'], steps=1, npc=None,
                   line='“Chờ xíu anh ơi, tấm nữa thôi, góc này lên hình xịn lắm!”', miss='Hai bạn vẫn tạo dáng, chẳng ai quay lại.'),
    'kids': dict(emoji='🧒', name='Mấy đứa nhỏ ngồi bắn bi trên ray', works=['go'], steps=1, npc=None,
                 line='“Tụi con chơi xíu nữa thôi mà chú!”', miss='Tụi nhỏ vẫy tay chào, rồi bắn bi tiếp.'),
    'drunk': dict(emoji='🥴', name='Chú Hớn ngủ gục sát mép ray', works=['go'], steps=2, npc=LAM,
                  line='“Ơ… tàu hả… để chú nằm xíu…”', miss='Chú Hớn ngáy to hơn cả tiếng còi.'),
    'cow': dict(emoji='🐄', name='Con bò ai thả gặm cỏ giữa đường ray', works=['help'], steps=2, npc=None,
                line='Con bò nhai cỏ, nhìn bạn bằng ánh mắt vô cảm.', miss='Con bò vẫy đuôi đuổi ruồi, không nhúc nhích.'),
    'cart': dict(emoji='🛺', name='Xe ba gác chở dưa kẹt bánh vào khe ray', works=['help'], steps=2, npc=None,
                 line='“Kẹt bánh rồi em ơi, đẩy phụ chị với!”', miss='Chị bán dưa vẫn loay hoay, bánh xe kẹt cứng.'),
    'stalled': dict(emoji='🏍️', name='Xe máy chết máy ngay giữa ray', works=['help'], steps=1, npc=None,
                    line='“Đề mãi không nổ, khổ quá trời!”', miss='Anh kia đạp đề lia lịa, xe vẫn nằm im trên ray.'),
    'vendor': dict(emoji='🧺', name='Cô bán xôi đẩy xe băng ngang ray', works=['whistle', 'go'], steps=1, npc=None,
                   line='“Cô qua liền, qua liền mà!”', miss='Cô bán xôi đứng lại mời khách giữa ray.'),
    'chairs': dict(emoji='🪑', name='Ghế nhựa quán cà phê bày sát mép ray', works=['go'], steps=1, npc=MAN,
                   line='Cô Mận: “Khách đang ngồi chụp ảnh mà, dẹp gì sớm vậy!”', miss='Mấy cái ghế vẫn chĩa ra sát mép ray.'),
    'chili': dict(emoji='🌶️', name='Nong ớt bà Bông phơi trên thanh ray', works=['go'], steps=1, npc=LANH,
                  line='Bà Bông: “Nắng đẹp thế này không phơi thì phí!”', miss='Bà Bông giả vờ không nghe, quạt nồi nước chè.'),
    'dog': dict(emoji='🐕', name='Con chó vàng nằm phơi nắng giữa ray', works=['whistle', 'go'], steps=1, npc=None,
                line='Con chó ngóc đầu nhìn bạn, đuôi đập đập xuống đá ba-lát.', miss='Con chó lăn ra ngủ tiếp.'),
    'ducks': dict(emoji='🦆', name='Đàn vịt lạch bạch băng qua ray', works=['help'], steps=1, npc=None,
                  line='Ông chủ đàn vịt: “Từ từ, từ từ, vịt nó sợ!”', miss='Đàn vịt quay vòng giữa hai thanh ray.'),
    'tourist': dict(emoji='🧳', name='Ông khách Tây kéo vali dọc đường ray tìm homestay', works=['go'], steps=1, npc=None,
                    line='“Sorry! Homestay… this way?”', miss='Ông khách vẫy tay cảm ơn rồi kéo vali tiếp dọc ray.'),
}
CLEAR = {
    'whistle': dict(emoji='📯', name='Thổi còi, phất cờ từ chòi'),
    'go': dict(emoji='🚶', name='Ra tận nơi nhắc, dẫn vào lề'),
    'help': dict(emoji='💪', name='Phụ đẩy, lùa ra khỏi ray'),
}
CLEARED = {
    'selfie': 'Hai bạn trẻ giật mình, chạy ra ngoài vạch: “Xin lỗi anh, tụi em không biết!”',
    'kids': 'Bạn dắt tụi nhỏ vào lề, dặn: “Ray là đường tàu, không phải sân chơi nha.” Tụi nhỏ cắp bi chạy về.',
    'drunk': 'Bạn lay chú Hớn dậy, dìu chú vào hiên nhà bà Bông, rót cho chú cốc nước.',
    'cow': 'Bạn với ông hàng xóm lùa con bò ra bãi cỏ, buộc dây vào gốc xoan.',
    'cart': 'Ba người hè nhau nhấc bánh xe khỏi khe ray. Chị bán dưa cảm ơn rối rít.',
    'stalled': 'Bạn đẩy phụ chiếc xe ra khỏi ray, anh kia dắt vào lề đạp tiếp.',
    'vendor': 'Cô bán xôi đẩy xe lùi lại sau vạch dừng, miệng vẫn mời “xôi nóng đây”.',
    'chairs': 'Bạn xếp gọn mấy cái ghế vào trong quán. Cô Mận bĩu môi nhưng không cãi.',
    'chili': 'Bạn bê nong ớt vào hiên. Bà Bông càm ràm: “Lại đây phơi nhờ cái nắng cũng không yên.”',
    'dog': 'Con chó vàng giật mình, chạy tót vào gầm bàn quán nước.',
    'ducks': 'Bạn với ông chủ vịt dang tay lùa cả đàn qua bên kia, không sót con nào.',
    'tourist': 'Bạn dẫn ông khách ra đường đất, chỉ lối tới homestay. “Thank you! Train… dangerous, yes!”',
}

# ---------------------------------------------------------------- the barrier is down: who pushes, and how
# Answers: hold (giữ chắn) · explain (chỉ bảng giờ) · detour (chỉ đường vòng) · calm (mời lùi, chờ cùng)
#          · report (ghi biển số, báo công an phường) · open (nâng chắn cho qua: never)
ANSWERS = {
    'hold': dict(emoji='✋', name='Giữ chắn: “Không qua được ạ.”'),
    'explain': dict(emoji='🕐', name='Chỉ bảng giờ: tàu sắp tới'),
    'detour': dict(emoji='↪️', name=f'Chỉ đường vòng qua {DETOUR}'),
    'calm': dict(emoji='🤝', name='Mời lùi sau vạch dừng, chờ cùng'),
    'report': dict(emoji='📝', name='Ghi biển số, báo công an phường'),
    'open': dict(emoji='⚠️', name='Nâng chắn cho qua'),
}


def _push(pid, emoji, who, line, again, best, ok=(), bad=(), soft=False, sneaky=False, npc=None, min_day=1, weight=2, mods=None):
    return dict(id=pid, emoji=emoji, who=who, line=line, again=again, best=list(best), ok=list(ok), bad=list(bad), soft=soft,
                sneaky=sneaky, npc=npc, min_day=min_day, weight=weight, mods=mods)


PUSH = [
    _push('grab', '🛵', 'Anh Tài · xe ôm công nghệ', '“Em ơi nâng xíu cho anh qua, khách hủy cuốc là anh toang, tàu còn xa lắc mà!”',
          '“Anh có thấy đèn tàu đâu đâu. Hai giây thôi, anh phóng nhanh lắm!”', ['explain', 'detour'], ['hold'], sneaky=True, npc=TAI, weight=3),
    _push('funeral', '⚱️', 'Đoàn đưa tang nhà ông Tư', '“Cháu ơi, giờ đẹp đưa cụ ra đồng rồi, trễ giờ là cả họ không yên…”',
          '“Thầy cúng dặn đúng giờ Tỵ, cháu thương mà mở cho đoàn qua trước…”', ['calm', 'explain'], ['hold'], ['report'], soft=True, weight=2, mods=['normal', 'rain', 'rush', 'heat']),
    _push('wedding', '💐', 'Xe hoa rước dâu', '“Giờ hoàng đạo chín giờ mười lăm, trễ một phút là cả đời xui đó em ơi!”',
          '“Anh lì xì em phong bao nè, mở chắn lấy hên đi!”', ['explain', 'calm'], ['detour', 'hold'], ['report'], soft=True, weight=2, mods=['normal', 'rain', 'rush', 'heat']),
    _push('ambulance', '🚑', 'Xe cứu thương hú còi', '“Bệnh nhân nặng! Nâng chắn ngay!”',
          '“Mỗi phút là một mạng người đấy!”', ['explain'], ['calm', 'detour'], ['report'], soft=True, weight=1, min_day=3),
    _push('bribe', '🚚', 'Anh tài xế xe tải', '“Bồi dưỡng em hai chục xu, nâng chắn cho xe anh qua, hàng giao gấp.”',
          '“Ba chục. Chốt. Ai biết đâu mà em ngại.”', ['report', 'hold'], ['explain'], ['calm'], weight=2, min_day=2),
    _push('vip', '🕶️', 'Ông đeo kính đen tự xưng cán bộ', '“Biết tôi là ai không? Gọi cung trưởng của cậu ra đây!”',
          '“Tôi nói một câu là cậu mất việc. Mở chắn!”', ['hold', 'explain'], ['report'], ['calm'], weight=2, min_day=2),
    _push('charm', '😉', 'Cô gái đi xe tay ga', '“Anh gác chắn đẹp trai ơi, nâng cho em qua xíu đi, em xin info nha 😘”',
          '“Anh khó tính vậy, em buồn đó. Một xíu thôi mà…”', ['hold', 'explain'], ['calm'], weight=2, min_day=2),
    _push('student', '🎒', 'Cậu học sinh trễ giờ thi', '“Em trễ giờ thi học kỳ rồi anh ơi, cho em chui qua đi!”',
          '“Thi rớt là ba em đánh em chết anh ơi…”', ['explain', 'calm'], ['hold'], ['report'], soft=True, sneaky=True, weight=2),
    _push('shipper', '🍦', 'Shipper giao kem', '“Kem chảy hết rồi anh, khách đánh giá một sao là em toang luôn.”',
          '“Tàu còn xa mà, em qua cái vèo là xong!”', ['explain', 'detour'], ['hold'], sneaky=True, weight=2),
    _push('tiktok', '📱', 'TikToker đang livestream', '“Cả nhà ơi, thử thách vượt chắn tàu nè! Thả tim lên để em chui qua nha!”',
          '“Anh gác chắn căng vl. Cả nhà vào chửi anh này đi!”', ['report', 'hold'], ['explain'], ['calm'], sneaky=True, weight=2, min_day=2),
    _push('cyclist', '🚲', 'Bác đạp xe đi chợ', '“Tôi dắt xe đi bộ qua nhanh mà, tàu còn xa.”',
          '“Ba chục năm nay tôi qua đây có sao đâu.”', ['explain', 'hold'], ['calm'], ['report'], sneaky=True, weight=2),
    _push('mom', '👩‍🍼', 'Chị bế con đang khóc', '“Con chị sốt, chị phải đi khám, cho chị qua đi em…”',
          '“Em không có con nên em không hiểu đâu…”', ['calm', 'explain'], ['hold'], ['report'], soft=True, weight=2),
    _push('truck', '🚛', 'Xe tải dừng sát cần chắn', '“Xe anh đuôi dài, lùi không được, chiếm hết đường rồi, nâng đi em!”',
          '“Đằng sau bấm còi ầm ầm kìa, em chịu trách nhiệm à?”', ['hold', 'explain'], ['calm'], weight=1, min_day=2),
    _push('cafe', '☕', 'Cô Mận · quán cà phê đường tàu', '“Đóng chắn sớm vậy khách Tây chụp ảnh sao kịp? Cho khách ra ngồi sát ray tí đi!”',
          '“Quán cô sống nhờ cái ảnh tàu chạy sát mặt khách đó con.”', ['hold', 'explain'], ['calm'], ['report'], npc=MAN, weight=2),
    _push('drunk', '🍶', 'Chú Hớn đang say', '“Mày là ai mà cản tao? Đường ray này ông cha tao đi từ hồi chưa có mày!”',
          '“Tao đi qua đó, làm gì nhau!”', ['calm'], ['hold'], ['report'], soft=True, sneaky=True, npc=LAM, weight=2),
    _push('honk', '📣', 'Đoàn xe máy bấm còi inh ỏi', '“Bíp bíp bíp! Mở chắn đi! Chờ gì mà chờ lâu thế!”',
          '“Tàu đâu? Tàu đâu? Đóng chắn để ngắm à?”', ['explain', 'hold'], ['calm'], weight=3),
    _push('grandma', '👵', 'Bà cụ dắt xe đạp chở rau', '“Bà già rồi chạy không nổi, bà dắt qua chậm thôi mà con.”',
          '“Rau héo hết rồi con ơi, bà đi đây…”', ['calm'], ['explain', 'hold'], ['report'], soft=True, sneaky=True, weight=2),
    _push('bus', '🚌', 'Hướng dẫn viên xe du lịch', '“Đoàn em trễ giờ ra sân bay rồi chị ơi, nâng giùm năm giây thôi.”',
          '“Khách đánh giá tour thấp là em bị trừ lương đó.”', ['explain', 'detour'], ['hold'], weight=1, min_day=3),
    _push('neighbour', '🙋', 'Anh hàng xóm đầu ngõ', '“Ngày nào anh chả qua đây, quen rồi. Em nâng cho anh đi.”',
          '“Chú Sáu ngày xưa còn cho anh qua đấy!”', ['hold', 'explain'], ['calm'], sneaky=True, weight=2),
    _push('kite', '🪁', 'Mấy đứa nhỏ', '“Chú ơi cho tụi con ra lượm con diều rơi trên ray!”',
          '“Diều của bạn con mà, mất là bạn khóc!”', ['calm', 'hold'], ['explain'], ['report'], soft=True, sneaky=True, weight=2, mods=['normal', 'rain', 'rush', 'heat']),
    _push('wife', '👜', 'Chị tự xưng vợ anh Quý', '“Chị là vợ anh Quý cung trưởng đây. Em nâng cho chị qua, có gì anh ấy lo.”',
          '“Em không tin chị gọi anh ấy cho em nghe nhé!”', ['hold', 'explain'], ['report'], ['calm'], weight=1, min_day=3),
    _push('rev', '🏍️', 'Thanh niên rồ ga', '“Tàu còn xa vl, né cái là qua!”',
          '“Thách mày cản được tao!”', ['report', 'hold'], ['explain'], ['calm'], sneaky=True, weight=2),
    _push('xoi', '🍙', 'Cô bán xôi', '“Cho cô đẩy xe qua kịp mối giao xôi cho trường mẫu giáo!”',
          '“Tụi nhỏ đói meo rồi kia kìa!”', ['explain', 'calm'], ['hold'], ['report'], sneaky=True, weight=2),
    _push('pilgrims', '🙏', 'Đoàn các cụ đi lễ chùa', '“Đoàn đi lễ chùa Gió Lành, các cụ đứng lâu mỏi chân lắm cháu.”',
          '“Cháu tích đức, mở cho các cụ qua.”', ['calm', 'explain'], ['hold'], ['report'], soft=True, weight=1, min_day=2, mods=['normal', 'rain', 'rush', 'heat']),
    _push('guard', '🦺', 'Người mặc áo bảo vệ', '“Anh làm bảo vệ khu này. Anh cho phép em mở chắn!”',
          '“Anh chịu trách nhiệm, em cứ mở.”', ['hold', 'report'], ['explain'], weight=1, min_day=3),
    _push('photo', '📷', 'Nhiếp ảnh gia ôm máy ảnh to', '“Cho anh vào trong chắn một xíu thôi, chụp đoàn tàu lao tới mới có hồn!”',
          '“Ảnh này đi thi đó em, anh đứng sát vạch thôi mà.”', ['hold', 'explain'], ['calm'], sneaky=True, weight=2),
    _push('buffalo', '🐃', 'Ông dắt trâu về chuồng', '“Con trâu nó không chờ được đâu cháu ơi, nó húc chắn bây giờ!”',
          '“Trâu nó sợ còi, cho nó qua trước đi!”', ['calm'], ['hold', 'explain'], ['report'], soft=True, weight=1, mods=['rain', 'heat', 'normal']),
    _push('friend', '🧢', 'Thằng bạn học cũ', '“Ủa mày gác chắn hả? Nâng cho tao qua, bạn bè mà!”',
          '“Làm gác chắn có tí mà làm giá ghê.”', ['hold', 'explain'], ['calm'], weight=1, min_day=2),
]
PUSH_INDEX = {x['id']: x for x in PUSH}
PUSH_OK = {   # how a pusher backs off, by kind of answer
    'hold': '{who} lùi lại, lầm bầm nhưng đứng chờ.',
    'explain': '{who} nhìn bảng giờ: “Ờ… còn có {eta} phút thật à.” Rồi đứng chờ.',
    'detour': '{who} quay đầu xe chạy về phía cầu vượt.',
    'calm': '{who} dịu giọng, lùi sau vạch dừng chờ cùng bạn.',
    'report': 'Bạn ghi biển số, gọi công an phường. {who} xụ mặt lùi lại.',
}
PUSH_SULK = '{who} hậm hực đứng chờ, miệng chưa thôi càm ràm.'
PUSH_SNEAK = '{who} lách xuống chui qua cần chắn, đang đứng giữa đường ray!'
PUSH_BLOWUP = '{who} chửi đổng một tràng, quay clip mặt bạn: “Gác chắn gì mà như quan!”'
PUSH_OPEN = 'Bạn nâng cần chắn cho {who} qua. Đúng lúc đó còi tàu rúc lên từ khúc cua. Tim bạn muốn rớt ra ngoài.'
PUSH_SOFT_REPORT = 'Ghi biển số một người đang lo việc hiếu, việc bệnh thì nặng tay quá. {who} nhìn bạn, mắt đỏ hoe.'

# ---------------------------------------------------------------- the track patrol
POINTS = [
    dict(id='p1', km='Km 7+000', name='Mối nối ray đầu cầu', emoji='🔩'),
    dict(id='p2', km='Km 7+180', name='Đoạn ray qua xóm phố Ray', emoji='🏘️'),
    dict(id='p3', km='Km 7+420', name='Cống thoát nước dưới nền đường', emoji='🌊'),
    dict(id='p4', km='Km 7+650', name='Đường cong qua vườn chuối', emoji='🍌'),
    dict(id='p5', km='Km 7+900', name='Cột đèn tín hiệu vào ga', emoji='🚦'),
    dict(id='p6', km='Km 8+100', name='Hàng rào sau chợ', emoji='🧱'),
]
PATROL_FORMS = {
    'so': dict(emoji='📒', name='Sổ tuần đường', short='Ghi sổ', hint='việc nhỏ, đã xử lý tại chỗ'),
    'phieu': dict(emoji='🧾', name='Phiếu báo hỏng gửi cung', short='Phiếu báo hỏng', hint='cần tổ thợ tới sửa'),
    'khan': dict(emoji='📞', name='Điện khẩn cho ga', short='Điện khẩn ga', hint='nguy hiểm: ga dừng hoặc cho tàu chạy chậm'),
    'phuong': dict(emoji='🏛️', name='Báo tổ dân phố, phường', short='Báo phường', hint='người dân lấn chiếm, phá rào'),
}
HANDLE = {
    'fix': dict(emoji='🔧', name='Tự xử lý tại chỗ', short='Tự xử lý'),
    'protect': dict(emoji='🚩', name='Cắm cờ đỏ phòng vệ hai đầu', short='Cắm cờ phòng vệ'),
    'talk': dict(emoji='🗣️', name='Nói chuyện, nhắc nhở', short='Nhắc nhở'),
}
# need: the handling it needs ('fix' / 'protect' / 'talk' / None); forms: what must be filed; danger: trains must be stopped or slowed.
FINDS = {
    'ok': dict(emoji='✅', text='Mọi thứ ổn: bu lông chặt, tà vẹt lành, đá đầy.', need=None, forms=[], danger=False),
    'bolt': dict(emoji='🔩', text='Hai con bu lông mối nối ray lỏng, lắc tay thấy rơ.', need='fix', forms=['so'], danger=False,
                 done='Bạn siết lại bằng cờ lê, đánh dấu sơn trắng lên đầu bu lông.'),
    'sleeper': dict(emoji='🪵', text='Một thanh tà vẹt bê tông nứt chân, lòi cốt thép.', need=None, forms=['phieu'], danger=False),
    'fishplate': dict(emoji='🔗', text='Thanh lập lách thiếu một con bu lông.', need=None, forms=['phieu'], danger=False),
    'ballast': dict(emoji='🌊', text='Mưa đêm qua cuốn trôi đá ba-lát, ray treo hẫng một đoạn dài hai gang tay!', need='protect', forms=['khan'],
                    danger=True, mods=['rain']),
    'crack': dict(emoji='⚡', text='Một vết nứt ngang chạy qua đầu ray, sáng loáng dưới nắng!', need='protect', forms=['khan'], danger=True),
    'buckle': dict(emoji='〰️', text='Nắng gắt, ray giãn nở, cong vênh như sợi mì!', need='protect', forms=['khan'], danger=True, mods=['heat']),
    'signal': dict(emoji='🚦', text='Đèn tín hiệu vào ga tắt ngóm, không hiện màu nào.', need=None, forms=['khan', 'phieu'], danger=True),
    'branch': dict(emoji='🌿', text='Một cành xoan gãy đè ngang thanh ray.', need='fix', forms=['so'], danger=False,
                   done='Bạn kéo cành xoan ra khỏi ray, chặt gọn để bên lề.'),
    'trash': dict(emoji='🗑️', text='Ai đó vứt cả bao rác sát mép ray.', need='fix', forms=['so'], danger=False,
                  done='Bạn lôi bao rác ra xa, buộc miệng lại để tổ thu gom lấy.'),
    'chili': dict(emoji='🌶️', text='Bà Bông trải nong ớt lên hai thanh ray phơi nắng.', need='talk', forms=['so'], danger=False, npc=LANH,
                  done='Bà Bông càm ràm nhưng bê nong ớt vào hiên.'),
    'coins': dict(emoji='🪙', text='Mấy đứa nhỏ đặt đồng xu lên ray chờ tàu cán dẹt.', need='talk', forms=['so'], danger=False,
                  done='Bạn gom đồng xu, dắt tụi nhỏ vào ngõ, nhờ người lớn để ý.'),
    'shack': dict(emoji='🏚️', text='Ai đó dựng mái tôn bán hàng lấn vào hành lang an toàn đường sắt.', need=None, forms=['phuong'], danger=False),
    'fence': dict(emoji='🧱', text='Hàng rào bị đập một lỗ, người ta mở lối đi tắt băng qua ray.', need=None, forms=['phuong', 'phieu'], danger=False),
}
LOCALS = ('chili', 'coins')

# ---------------------------------------------------------------- the log after a train
REMARKS = {
    'ontime': '✅ Tàu qua đúng giờ, an toàn',
    'late': '⏳ Tàu chậm so với giờ',
    'violator': '📝 Có người vượt chắn / bị ghi biển số',
    'stopped': '🟥 Đã báo dừng tàu vì có vật cản',
    'tail': '🏮 Toa cuối không thấy đèn đuôi, đã báo ga',
    'defect': '⚠️ Phát hiện bất thường trên tàu, đã báo ga',
    'second': '🚆 Có tàu thứ hai qua liền sau',
}
DEFECTS = {
    'hot': dict(emoji='💨', text='Một bầu trục toa số {n} bốc khói, mùi khét lẹt.'),
    'door': dict(emoji='🚪', text='Cửa toa hàng số {n} mở toang, tấm bạt bay phần phật.'),
    'drag': dict(emoji='⛓️', text='Có sợi xích lòng thòng quệt tóe lửa dưới gầm toa số {n}.'),
}

# ---------------------------------------------------------------- intro
INTRO = dict(
    title='Giới thiệu nghề: gác chắn đường ngang',
    lead=f'Một cái chòi nhỏ, hai cần chắn sọc đỏ trắng, cái chuông, cờ đỏ, cờ xanh và cái bộ đàm. Chú Sáu đã gác {CROSSING} hai mươi tám năm; '
         f'bạn vào {COMPANY}, theo chú học nghề.',
    work=[('📻', 'Nghe ga báo tàu, nhắc lại lệnh cho đúng từng chữ'), ('👀', 'Nhìn đường ngang: ai, cái gì còn trên ray thì dẹp'),
          ('🔔', 'Bật chuông, đèn đỏ rồi mới hạ cần chắn'), ('✋', 'Chắn đã hạ thì không mở cho bất kỳ ai'),
          ('🚩', 'Đứng cờ đón tàu: xanh là đường thông, đỏ là dừng'), ('🏮', 'Nhìn hết đoàn tàu, thấy đèn đuôi toa cuối'),
          ('📞', 'Hỏi ga còn tàu không rồi mới nâng chắn'), ('🔩', 'Tuần đường: bu lông, tà vẹt, đá ba-lát, đèn tín hiệu')],
    meet=[('🛵', 'Anh Tài xe ôm: cuốc nào cũng gấp'), ('🌶️', 'Bà Bông: phơi ớt trên ray, ghét còi tàu'), ('☕', 'Cô Mận: quán cà phê sát ray'),
          ('🥴', 'Chú Hớn: hay ngủ quên ở bờ ray'), ('📻', 'Chị Nguyệt trực ban ga: nhắc lại lệnh cho rõ'), ('📋', 'Anh Quý cung trưởng: kiểm tra đột xuất'),
          ('⚱️', 'Đám tang, xe hoa, xe cứu thương, người dúi tiền'), ('🐄', 'Bò, vịt, chó, tụi nhỏ, khách chụp ảnh trên ray')],
    stars=[('📻', 'Nhắc lại lệnh đúng'), ('⏱️', 'Hạ chắn đúng lúc, không sớm không muộn'), ('✋', 'Không mở chắn cho ai'),
           ('🏮', 'Nhìn đủ đoàn tàu, báo bất thường'), ('📞', 'Hỏi ga trước khi nâng chắn'), ('📒', 'Ghi sổ đúng sự thật')],
)

# ---------------------------------------------------------------- regulars' small stories (by PEOPLE index)
REG_STORY = {
    SAU: ('Chú Sáu: “Gác chắn là nghề chờ. Chờ cho đúng thì người ta mới sống.”',
          'Chú Sáu kể hồi năm chín mấy, chú cầm cờ đỏ chạy ngược về phía tàu cứu một xe bò.',
          'Chú Sáu đưa bạn cái còi đồng cũ: “Giữ lấy. Nó thổi cứu được người rồi đó.”'),
    HANH: ('Chị Nguyệt: “Nhắc lại lệnh rõ thế là chị yên tâm.”', 'Chị Nguyệt bảo cả ga khen ca của bạn nhắc lệnh rành rọt.',
           'Chị Nguyệt gửi qua tàu địa phương một hộp bánh gai: “Cho ca gác Bến Mây.”'),
    QUY: ('Anh Quý: “Sổ ghi đúng, chắn hạ đúng giờ. Được.”', 'Anh Quý đưa ca của bạn ra làm gương ở buổi giao ban cung.',
          'Anh Quý đề nghị xí nghiệp khen thưởng “ca gác an toàn tuyệt đối”.'),
    KHAI: ('Anh Khải gật đầu: “Mắt tinh đấy.”', 'Anh Khải chỉ bạn cách nghe tiếng bu lông lỏng bằng cái búa nhỏ.',
           'Anh Khải rủ bạn đi tuần cả đoạn Km 8 vào sáng chủ nhật, “cho biết đường”.'),
}

# ---------------------------------------------------------------- surprises (kit desk scripts)
DESK = [
    dict(id='rw-inspect', title='Cung trưởng kiểm tra đột xuất', emoji='📋', npc=QUY, min_day=2, tone='tense', at='any', weight=3, mods=None,
         text='Anh Quý dựng xe trước chòi, chìa tay: “Đưa sổ nhật ký đây. Hôm qua tàu nào chậm, ghi thế nào?”',
         options=[dict(id='show', label='Đưa sổ, chỉ đúng từng dòng, nói rõ chỗ mình ghi thiếu hôm qua', hint='', effects=dict(xp=6), good=True,
                       outcome='Anh Quý gõ bút vào dòng ghi thiếu: “Thật thà là tốt. Bổ sung ngay.” Rồi ký kiểm tra.'),
                  dict(id='patch', label='Xin năm phút “sắp xếp lại sổ” rồi mới đưa', hint='Sửa lén cho đẹp', effects=dict(review=[2, 'Sổ nhật ký mà sửa lấy được trước mặt cung trưởng. Không ổn.']),
                       good=False, outcome='Anh Quý thấy vết tẩy mới tinh: “Sổ nhật ký là văn bản, không phải vở nháp.”'),
                  dict(id='blame', label='“Ca trước ghi chứ không phải em”', hint='', effects=dict(review=[2, 'Hỏi sổ thì đổ cho ca trước.']), good=False,
                       outcome='Anh Quý lật trang: dòng đó là chữ của bạn. Không khí trong chòi đặc quánh.')],
         default='show'),
    dict(id='rw-horn', title='Bà Bông kêu còi tàu', emoji='📯', npc=LANH, min_day=2, tone='gentle', at='any', weight=3, mods=None,
         text='Bà Bông đập bàn: “Năm giờ sáng tàu kéo còi inh ỏi, cháu bà mất ngủ! Cháu bảo lái tàu đừng kéo nữa!”',
         options=[dict(id='explain', label='Giải thích còi là tín hiệu an toàn bắt buộc, ghi ý kiến của bà vào phiếu gửi xí nghiệp', hint='', effects=dict(xp=5),
                       good=True, outcome='Bà Bông vẫn càu nhàu, nhưng thấy bạn ghi phiếu đàng hoàng thì dịu đi: “Ừ, có người nghe là được.”'),
                  dict(id='promise', label='“Để cháu bảo lái tàu thôi kéo còi”', hint='Hứa cho xong', effects=dict(review=[2, 'Hứa bảo tàu thôi kéo còi mà sáng nay vẫn kéo. Nói cho vui à?']),
                       good=False, outcome='Sáng hôm sau còi vẫn rúc. Bà Bông bảo bạn “hứa hão”.'),
                  dict(id='shrug', label='“Ở cạnh đường tàu thì chịu thôi bà ơi”', hint='', effects=dict(review=[2, 'Nói chuyện với người già mà cộc lốc.']), good=None,
                       outcome='Bà Bông nguýt dài, cả buổi không mời bạn chén chè nào.')],
         default='explain'),
    dict(id='rw-power', title='Mất điện cả khu', emoji='🔌', npc=SAU, min_day=2, tone='tense', at='any', weight=2, mods=('rain', 'heat', 'normal'),
         text='Cả phố Ray tối om. Tủ điều khiển cần chắn tắt đèn. Còn mười phút nữa có tàu.',
         options=[dict(id='manual', label='Lắp tay quay, thử hạ nâng bằng tay, gọi điện báo ga đang mất điện', hint='', effects=dict(xp=6), good=True,
                       outcome='Tay quay nặng trịch nhưng cần chắn vẫn lên xuống. Ga dặn lái tàu chú ý đường ngang Bến Mây.'),
                  dict(id='wait', label='Chờ điện có lại rồi tính', hint='', effects=dict(patience=-4, review=[2, 'Mất điện mà gác chắn ngồi chờ, không báo ga.', 1]),
                       good=False, outcome='Điện chưa có, tàu sắp tới. Bạn cuống cuồng lắp tay quay, gọi ga muộn mất năm phút.'),
                  dict(id='flag', label='Cầm cờ đỏ ra giữa đường, đứng chặn xe bằng tay', hint='Tạm thời', effects=dict(xp=2), good=None,
                       outcome='Xe dừng lại vì cờ đỏ, nhưng không có cần chắn thì người ta cứ len. May có tay quay trong tủ.')],
         default='wait'),
    dict(id='rw-lost', title='Bé lạc ở đường ngang', emoji='🧒', npc=SAU, min_day=2, tone='tense', at='any', weight=2, mods=None,
         text='Một bé gái chừng bốn tuổi đứng khóc cạnh chòi gác, tay cầm que kem, không biết nhà ở đâu.',
         options=[dict(id='keep', label='Cho bé ngồi trong chòi, xa đường ray, gọi tổ dân phố và công an phường', hint='', effects=dict(xp=6), good=True,
                       outcome='Mười lăm phút sau mẹ bé chạy tới, ôm chầm lấy con. Tổ dân phố đăng tin cảm ơn ca gác.'),
                  dict(id='walk', label='Bỏ chòi, dắt bé đi hỏi từng nhà', hint='Chòi không người', effects=dict(review=[2, 'Bỏ chòi gác không người lúc sắp có tàu.', 2]),
                       good=False, outcome='Bạn đi được hai ngõ thì nghe chuông bộ đàm réo. Chòi không ai trực.'),
                  dict(id='post', label='Chụp ảnh bé đăng nhóm phố rồi để bé ngồi chờ', hint='', effects=dict(xp=2), good=None,
                       outcome='Tin lan nhanh, mẹ bé tới. Có người nhắc: đừng đăng mặt trẻ con lung tung.')],
         default='keep'),
    dict(id='rw-phone', title='Điện thoại rơi trên ray', emoji='📱', npc=TAI, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Anh Tài hét: “Điện thoại anh rơi trên ray kìa! Em nâng chắn cho anh chạy vào nhặt, nhanh lắm!” Tàu vừa báo còn bốn phút.',
         options=[dict(id='after', label='Giữ chắn, hứa nhặt giúp ngay khi tàu qua, ga đồng ý', hint='', effects=dict(xp=5), good=True,
                       outcome='Tàu qua, bạn nhặt chiếc điện thoại còn nguyên, chỉ xước cái ốp. Anh Tài cảm ơn rối rít.'),
                  dict(id='run', label='Tự chạy vào nhặt cho nhanh', hint='Còn bốn phút', effects=dict(review=[1, 'Gác chắn chạy vào đường ray lúc tàu sắp tới!', 2]), good=False,
                       outcome='Bạn nhặt được, nhưng anh Quý đứng bên kia đường nhìn thấy hết. Tối đó bạn viết bản tường trình.'),
                  dict(id='no', label='“Ai bảo làm rơi”', hint='', effects=dict(review=[2, 'Nhờ có tí cũng không giúp.']), good=None,
                       outcome='Tàu qua, điện thoại bị cán nát. Anh Tài đứng nhìn, mặt buồn so.')],
         default='after'),
    dict(id='rw-journalist', title='Phóng viên hỏi chuyện tai nạn cũ', emoji='🎤', npc=QUY, min_day=3, tone='gentle', at='any', weight=1, mods=None,
         text='Một cô phóng viên chìa micro: “Năm ngoái ở đây có vụ xe máy đâm tàu phải không? Gác chắn ngủ gật hả anh?”',
         options=[dict(id='refer', label='Lịch sự nói chuyện đó xí nghiệp có thông tin chính thức, cho số phòng truyền thông', hint='', effects=dict(xp=4), good=True,
                       outcome='Cô phóng viên ghi số, cảm ơn. Bài báo sau đó trích đúng lời xí nghiệp.'),
                  dict(id='gossip', label='Kể hết chuyện nghe được ngoài quán nước', hint='', effects=dict(review=[2, 'Gác chắn đi kể chuyện nội bộ với báo chí.']), good=False,
                       outcome='Bài báo giật tít “Gác chắn tố…”. Anh Quý gọi bạn lên phòng.'),
                  dict(id='shoo', label='Xua tay: “Đi chỗ khác, đang làm việc”', hint='', effects={}, good=None,
                       outcome='Cô phóng viên chụp ảnh cái chòi, chú thích “gác chắn từ chối trả lời”.')],
         default='refer'),
    dict(id='rw-flood', title='Mưa to, nước tràn đường ngang', emoji='⛈️', npc=HANH, min_day=2, tone='tense', at='any', weight=3, mods=('rain',),
         text='Mưa như trút. Nước ngập ngang mặt ray ở đoạn cống Km 7+420. Chị Nguyệt gọi: “Đường ngang Bến Mây thấy gì báo ngay!”',
         options=[dict(id='report', label='Báo ga nước ngập mặt ray, đề nghị tàu chạy chậm, xin thợ cung ra kiểm tra', hint='', effects=dict(xp=6), good=True,
                       outcome='Ga ra lệnh tàu chạy chậm qua Km 7. Anh Khải đội mưa ra cắm cờ, kiểm tra nền đường.'),
                  dict(id='later', label='Chờ tạnh mưa rồi ra xem', hint='', effects=dict(review=[1, 'Nước ngập ray mà không báo ga.', 1]), good=False,
                       outcome='Tàu SE chạy qua chỗ ngập ở tốc độ thường, rung lắc mạnh. Ga gọi hỏi sao không báo.'),
                  dict(id='guess', label='“Chắc không sao, năm nào chả ngập”', hint='', effects=dict(review=[2, 'Coi thường nước ngập nền đường.', 2]), good=False,
                       outcome='Sáng ra đá ba-lát trôi một đoạn. Anh Khải lắc đầu.')],
         default='later'),
    dict(id='rw-cafe-stools', title='Quán cà phê kê ghế sát ray', emoji='☕', npc=MAN, min_day=2, tone='gentle', at='between', weight=3, mods=None,
         text='Cô Mận kê thêm dãy ghế nhựa sát mép ray, treo biển “Check-in tàu chạy sát mặt”. Khách xếp hàng chờ ngồi.',
         options=[dict(id='talk', label='Nói rõ hành lang an toàn, xin cô dời ghế vào trong, ghi phiếu báo phường nếu cô không dời', hint='', effects=dict(xp=5),
                       good=True, outcome='Cô Mận cằn nhằn nhưng dời ghế lùi ba mét. Khách vẫn chụp được, mà an toàn.'),
                  dict(id='allow', label='Thôi kệ, quán người ta làm ăn', hint='', effects=dict(review=[1, 'Gác chắn để quán kê ghế sát ray, khách suýt bị gương tàu quệt.', 2]),
                       good=False, outcome='Chiều đó gương chiếu hậu tàu địa phương quệt sát một vị khách. Ai cũng tái mặt.'),
                  dict(id='kick', label='Tự tay dẹp hết ghế ra giữa ngõ', hint='', effects=dict(review=[2, 'Gác chắn vào tận quán quăng ghế.']), good=None,
                       outcome='Ghế được dẹp, nhưng cô Mận đăng bài tố bạn “hành xử như côn đồ”.')],
         default='allow'),
    dict(id='rw-kids-coins', title='Tụi nhỏ đặt xu lên ray', emoji='🪙', npc=SAU, min_day=2, tone='gentle', at='between', weight=2, mods=None,
         text='Ba đứa nhỏ rủ nhau đặt đồng xu lên ray chờ tàu cán dẹt “làm huy hiệu”. Tàu tiếp theo còn hai mươi phút.',
         options=[dict(id='teach', label='Gom xu, dắt tụi nhỏ vào, kể cho tụi nhỏ nghe vì sao xu trên ray nguy hiểm', hint='', effects=dict(xp=5), good=True,
                       outcome='Tụi nhỏ há hốc nghe chuyện đồng xu văng như đạn. Chiều đó tụi nó về kể cho cả xóm.'),
                  dict(id='shout', label='Quát cho tụi nó chạy', hint='', effects={}, good=None,
                       outcome='Tụi nhỏ chạy mất, để lại ba đồng xu trên ray. Bạn phải ra nhặt.'),
                  dict(id='ignore', label='Kệ, có đồng xu thôi mà', hint='', effects=dict(review=[2, 'Gác chắn thấy trẻ con nghịch trên ray mà kệ.', 2]), good=False,
                       outcome='Tàu cán qua, một đồng xu văng trúng cửa kính quán nước. May không ai sao.')],
         default='shout'),
    dict(id='rw-sleep', title='Mắt díp lại giữa ca', emoji='😴', npc=SAU, min_day=2, tone='gentle', at='between', weight=2, mods=('night',),
         text='Đã khuya. Hai chuyến tàu nữa mới hết ca. Cái ghế trong chòi êm quá, mắt bạn cứ díp lại.',
         options=[dict(id='wake', label='Rửa mặt nước lạnh, đứng dậy đi quanh chòi, gọi ga hỏi giờ tàu', hint='', effects=dict(xp=4, patience=-1), good=True,
                       outcome='Nước lạnh làm bạn tỉnh hẳn. Chị Nguyệt còn đọc cho bạn nghe giờ tàu đêm.'),
                  dict(id='nap', label='Chợp mắt năm phút thôi, có chuông bộ đàm thì dậy', hint='', effects=dict(review=[1, 'Gác chắn ngủ gật trong ca, ga gọi ba lần không ai nghe.', 2]),
                       good=False, outcome='Năm phút thành hai mươi phút. Bộ đàm réo, bạn giật mình đánh rơi cả cốc trà.'),
                  dict(id='coffee', label='Pha cốc cà phê đặc', hint='', effects=dict(xp=2), good=None, outcome='Tỉnh được một lúc, nhưng tim đập thình thịch.')],
         default='nap'),
    dict(id='rw-gift', title='Phong bì “cảm ơn” của chủ xe tải', emoji='✉️', npc=QUY, min_day=3, tone='tense', at='any', weight=2, mods=None,
         text='Một ông chủ xe tải dúi phong bì: “Tuần sau xe anh qua đây đêm, em nâng sẵn chắn chờ nhé, đỡ mất thời gian.”',
         options=[dict(id='refuse', label='Từ chối phong bì, nói rõ chắn chỉ nâng khi đã an toàn, báo đội trưởng', hint='', effects=dict(xp=6), good=True,
                       outcome='Ông chủ xe ngượng ngùng cất phong bì. Đội trưởng ghi nhận ca của bạn.'),
                  dict(id='take', label='Nhận, hứa “để em xem”', hint='', effects=dict(money=20, review=[1, 'Gác chắn nhận phong bì của chủ xe tải.', 2]), good=False,
                       outcome='Tuần sau ông ta gọi điện “nhắc”. Bạn mất ngủ cả đêm, rồi phải nộp lại phong bì cho đội.'),
                  dict(id='laugh', label='Cười trừ, không nhận không từ', hint='', effects={}, good=None,
                       outcome='Ông ta để phong bì lại trên bàn rồi đi. Bạn phải mang nộp lên đội.')],
         default='laugh'),
    dict(id='rw-photo-shoot', title='Đoàn chụp ảnh cưới trên ray', emoji='👰', npc=MAN, min_day=3, tone='gentle', at='between', weight=2, mods=None,
         text='Một đôi cô dâu chú rể cùng thợ ảnh bày cả váy cưới trên đường ray: “Ảnh cưới đường tàu đang hot lắm anh ơi, cho chụp mười phút thôi!”',
         options=[dict(id='move', label='Chúc mừng, mời ra bãi cỏ cạnh ray chụp, chỉ chỗ vẫn thấy đường tàu mà an toàn', hint='', effects=dict(xp=5), good=True,
                       outcome='Ảnh chụp từ bãi cỏ, đường ray làm nền đẹp không kém. Cô dâu còn mời bạn kẹo cưới.'),
                  dict(id='let', label='Cho chụp, tàu tới thì đuổi', hint='', effects=dict(review=[1, 'Gác chắn cho cả đoàn chụp ảnh cưới trên ray.', 2]), good=False,
                       outcome='Đang chụp thì ga báo tàu. Cả đoàn ôm váy chạy toán loạn, chân váy mắc vào ray.'),
                  dict(id='no', label='“Không là không”', hint='', effects=dict(review=[3, 'Gác chắn khó đăm đăm, không chúc mừng được câu nào.']), good=None,
                       outcome='Đoàn cưới dọn đồ đi, cô dâu phụng phịu.')],
         default='no'),
    dict(id='rw-sick-colleague', title='Ca sau xin vào muộn', emoji='🤒', npc=SAU, min_day=3, tone='gentle', at='any', weight=1, mods=None,
         text='Chú Sáu gọi: “Chú sốt, chiều chú vào trễ hai tiếng. Con gác thêm giúp chú, đừng báo đội nhé, phiền.”',
         options=[dict(id='report', label='Gác thêm giúp chú, nhưng báo đội trưởng để có người thay đúng quy định', hint='', effects=dict(xp=5), good=True,
                       outcome='Đội cử anh Lộc vào thay. Chú Sáu được nghỉ ốm đàng hoàng, còn cảm ơn bạn đã báo.'),
                  dict(id='cover', label='Gác thêm, im lặng cho chú yên', hint='', effects=dict(patience=-3), good=None,
                       outcome='Bạn gác một mạch mười bốn tiếng, cuối ca mắt mờ đi. Chú Sáu áy náy mãi.'),
                  dict(id='leave', label='Hết giờ là về, ca sau tự lo', hint='', effects=dict(review=[1, 'Bỏ chòi gác không người lúc giao ca.', 2]), good=False,
                       outcome='Hai tiếng không ai gác. Ga phải báo tàu chạy chậm qua Bến Mây.')],
         default='cover'),
    dict(id='rw-train-fan', title='Hội mê tàu hỏa', emoji='🚂', npc=SAU, min_day=3, tone='gentle', at='between', weight=1, mods=None,
         text='Mấy bạn trẻ mê tàu hỏa xin vào chòi xem bạn làm việc, xin chụp bảng giờ tàu “cho hội nhóm”.',
         options=[dict(id='outside', label='Cảm ơn, mời đứng ngoài vạch an toàn, kể vài điều về nghề, không cho vào chòi', hint='', effects=dict(xp=4), good=True,
                       outcome='Hội mê tàu nghe say sưa, hứa nhắc cả nhóm không bao giờ đứng trong vạch.'),
                  dict(id='inside', label='Cho vào chòi bấm thử chuông', hint='', effects=dict(review=[2, 'Gác chắn cho người lạ vào chòi bấm chuông.', 2]), good=False,
                       outcome='Một bạn bấm nhầm nút hạ chắn giữa lúc xe đang qua. Một phen hú vía.'),
                  dict(id='shoo', label='Đuổi đi cho đỡ vướng', hint='', effects={}, good=None, outcome='Hội mê tàu đi, đăng bài “gác chắn Bến Mây khó tính”.')],
         default='shoo'),
    dict(id='rw-heat', title='Nắng bốn mươi độ', emoji='🌡️', npc=KHAI, min_day=3, tone='tense', at='any', weight=2, mods=('heat',),
         text='Nắng gắt, mặt ray nóng bỏng tay. Anh Khải gọi: “Trưa nay để ý đoạn cong Km 7+650, ray dễ giãn.”',
         options=[dict(id='watch', label='Đội mũ, mang nước, ra soi đoạn cong, thấy lạ là báo ga ngay', hint='', effects=dict(xp=5), good=True,
                       outcome='Đoạn cong vẫn ổn. Anh Khải dặn chiều mai đi soi lại lúc nắng nhất.'),
                  dict(id='skip', label='Nắng quá, chiều mát hẵng đi', hint='', effects=dict(review=[2, 'Được dặn soi ray lúc nắng mà để chiều.', 7]), good=False,
                       outcome='Chiều ra thì ray đã nguội. Không ai biết trưa nay nó ra sao.'),
                  dict(id='phone', label='Nhờ chú Hớn nhà gần đó ra nhìn hộ', hint='', effects={}, good=None, outcome='Chú Hớn bảo “thẳng tắp”. Chú vừa uống xong hai chén.')],
         default='skip'),
    dict(id='rw-cow-owner', title='Chủ bò đòi đền', emoji='🐄', npc=SAU, min_day=3, tone='tense', at='between', weight=1, mods=None,
         text='Ông chủ con bò hôm qua tới chòi: “Hôm qua cậu lùa bò tôi, nó trượt chân què. Đền đi, 30 xu!”',
         options=[dict(id='facts', label='Bình tĩnh kể lại, mời tổ dân phố làm chứng, nhắc ông buộc bò xa hành lang đường sắt', hint='', effects=dict(xp=5), good=True,
                       outcome='Hàng xóm làm chứng con bò vẫn đi lại bình thường. Ông chủ bò lẳng lặng về, từ đó buộc bò xa ray.'),
                  dict(id='pay', label='Đền cho xong chuyện', hint='Mất 30 xu', effects=dict(money=-30), good=None,
                       outcome='Bạn mất 30 xu. Con bò chiều đó vẫn gặm cỏ tung tăng.'),
                  dict(id='fight', label='“Bò ông thả trên ray, tôi chưa phạt là may”', hint='', effects=dict(review=[2, 'Gác chắn cãi tay đôi với người dân.']), good=False,
                       outcome='Hai bên to tiếng. Bà Bông phải bưng chè ra can.')],
         default='pay'),
]

# ---------------------------------------------------------------- situations (sit_ engine)
SITUATIONS = [
    dict(id='RW-S01', title='Đám tang xin qua trước', npc=SAU, tone='tense', min_day=1,
         opening='Chắn vừa hạ. Đoàn đưa tang dừng lại, ông trưởng họ xin: “Giờ đẹp sắp qua rồi cháu, mở cho đoàn qua trước, tàu còn xa.”',
         swap='Bạn là ông trưởng họ: thầy cúng dặn đúng giờ, cả họ đang nhìn vào ông.',
         facts=[dict(id='eta', title='Bảng giờ', source='Bộ đàm', text='Ga báo tàu SE còn ba phút tới đường ngang.'),
                dict(id='brake', title='Đoàn tàu', source='Chú Sáu', text='Tàu khách nặng mấy trăm tấn, phanh khẩn cấp cũng trượt cả trăm mét.'),
                dict(id='rule', title='Nội quy', source='Nội quy gác chắn', text='Chắn đã hạ chỉ được nâng khi tàu đã qua hết và ga xác nhận.')],
         options=[dict(id='wait', label='Chia buồn, giải thích tàu còn ba phút, mời đoàn chờ sau vạch, qua ngay khi tàu qua', requires=['eta', 'rule'], quality='good', stars=5,
                       review='Cậu gác chắn lễ phép, nói rõ ràng, đoàn chờ có ba phút rồi qua.', outcome='Đoàn chờ ba phút. Tàu qua, bạn nâng chắn và cúi đầu chào đoàn.',
                       perspectives=[dict(who='Ông trưởng họ', emoji='🧓', text='Ba phút thôi mà mình cứ tưởng lâu lắm.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Thương người là giữ chắn cho người ta về nhà lành lặn.')]),
                  dict(id='open', label='Nâng chắn cho đoàn qua nhanh', quality='bad', stars=1,
                       review='Đang qua thì còi tàu rúc, cả đoàn chạy tán loạn. Suýt nữa thì…', outcome='Còi tàu rúc lên khi người cuối cùng vừa ra khỏi ray.',
                       perspectives=[dict(who='Lái tàu', emoji='🚆', text='Tôi kéo phanh mà tay run cả buổi.'),
                                     dict(who='Ông trưởng họ', emoji='😨', text='Tôi giục bậy, xin lỗi cháu.')]),
                  dict(id='cold', label='“Không là không, đứng đó mà chờ”', requires=['rule'], quality='ok', stars=3,
                       review='Đúng quy định nhưng nói năng lạnh lùng với người đang có tang.', outcome='Đoàn chờ, nhưng ai cũng nhìn bạn không vui.',
                       perspectives=[dict(who='Bà con trong đoàn', emoji='😔', text='Đúng thì đúng, nhưng nói một câu chia buồn cũng được mà.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Giữ chắn bằng tay, nói chuyện bằng lòng.')])],
         lesson='Chắn đã hạ thì không nâng cho ai; nói rõ còn mấy phút và nói bằng sự tôn trọng.'),
    dict(id='RW-S02', title='Nhắc lại lệnh ậm ừ', npc=HANH, tone='gentle', min_day=1,
         opening='Bộ đàm rè rè: “Đường ngang Bến Mây, tàu TN… rời Bến Gỗ lúc… dự kiến qua…” Bạn nghe được nửa câu.',
         facts=[dict(id='noise', title='Bộ đàm', source='Tai bạn', text='Tiếng rè to, không nghe rõ số hiệu tàu lẫn giờ.'),
                dict(id='rule', title='Nội quy', source='Sổ tay ca gác', text='Lệnh nào cũng phải nhắc lại đủ số hiệu, giờ đi, giờ qua; không rõ thì hỏi lại.'),
                dict(id='hanh', title='Chị Nguyệt', source='Ga Bến Mây', text='Chị Nguyệt đang trực một mình, bận nhiều đường dây.')],
         options=[dict(id='ask', label='Xin ga nhắc lại, rồi đọc lại đủ số hiệu, giờ đi, giờ qua', requires=['noise', 'rule'], quality='good', stars=5,
                       review='Ca gác hỏi lại cho rõ rồi nhắc lệnh rành rọt. Yên tâm.', outcome='Chị Nguyệt đọc lại: TN2, rời 10:05, qua đường ngang 10:12. Bạn nhắc lại đúng.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='📻', text='Hỏi lại mất mười giây, nhầm thì mất cả đời.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Không rõ mà “rõ” là tội to nhất của gác chắn.')]),
                  dict(id='guess', label='“Rõ!” rồi đoán theo bảng giờ', quality='bad', stars=2,
                       review='Nhận lệnh kiểu đoán mò, tàu chậm mười phút mà ca gác không biết.', outcome='Tàu TN2 chậm mười phút. Bạn hạ chắn theo giờ cũ, xe dồn ứ cả phố.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='😠', text='Tôi đọc chậm mười phút, cậu “rõ” cái gì?'),
                                     dict(who='Anh Tài', emoji='🛵', text='Chờ mười lăm phút mà không thấy tàu đâu!')]),
                  dict(id='later', label='Để đó, lát gọi lại hỏi', requires=['hanh'], quality='ok', stars=3,
                       review='Có hỏi lại, nhưng chậm mất mấy phút quý.', outcome='Gọi lại thì ga đang bận, mãi mới được nghe.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='📻', text='Không rõ thì hỏi ngay, đừng để lát.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Tàu không chờ mình “lát nữa”.')])],
         lesson='Không rõ lệnh thì hỏi lại ngay; nhắc lại đủ số hiệu tàu, giờ đi, giờ qua.'),
    dict(id='RW-S03', title='Tàu qua mà không thấy đèn đuôi', npc=HANH, tone='tense', min_day=2,
         opening='Tàu hàng hai mươi sáu toa vừa qua. Bạn nhìn theo toa cuối: không thấy cái đèn đuôi đỏ đâu.',
         facts=[dict(id='lamp', title='Đèn đuôi', source='Chú Sáu', text='Đèn đuôi cho biết đoàn tàu còn nguyên. Không có đèn đuôi có thể là đứt toa, toa còn nằm lại trên đường.'),
                dict(id='next', title='Tàu sau', source='Bảng giờ', text='Hai mươi phút nữa có tàu khách chạy cùng chiều.'),
                dict(id='who', title='Ai cần biết', source='Nội quy', text='Thấy bất thường của đoàn tàu: báo ngay trực ban ga.')],
         options=[dict(id='radio', label='Gọi ngay ga: “Tàu H vừa qua không có đèn đuôi”, ghi giờ, giữ chắn chờ ga trả lời', requires=['lamp', 'who'], quality='good', stars=5,
                       review='Ca gác báo ngay đoàn tàu thiếu đèn đuôi. Ga kiểm tra kịp, hóa ra móc nối toa cuối lỏng.', outcome='Ga dừng tàu H ở Bến Mây kiểm tra: móc nối toa cuối lỏng thật. Tàu khách sau chạy an toàn.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='📻', text='Một cuộc gọi cứu cả chuyến tàu khách sau.'),
                                     dict(who='Lái tàu hàng', emoji='🚂', text='Tôi không biết toa cuối lỏng. Cảm ơn ca gác.')]),
                  dict(id='maybe', label='Chắc đèn hỏng thôi, ghi sổ cuối ca báo', requires=['next'], quality='bad', stars=2,
                       review='Thấy tàu không có đèn đuôi mà để cuối ca mới báo.', outcome='Tàu khách sau phải dừng gấp vì ga mãi mới biết.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='😟', text='Cái đó không chờ cuối ca được.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Đèn đuôi là đèn của cả đoàn tàu.')]),
                  dict(id='nothing', label='Không có gì, tàu qua là xong', quality='bad', stars=1,
                       review='Gác chắn không nhìn tàu đi qua.', outcome='Toa cuối bị tuột nằm lại ở Km 6. May tàu sau thấy từ xa.',
                       perspectives=[dict(who='Anh Quý', emoji='📋', text='Gác chắn không chỉ nâng hạ cần chắn.'),
                                     dict(who='Chị Nguyệt', emoji='😨', text='Suýt nữa thì…')])],
         lesson='Nhìn hết đoàn tàu; không thấy đèn đuôi hay có khói, cửa toa mở: báo ga ngay.'),
    dict(id='RW-S04', title='Ray treo hẫng sau mưa', npc=KHAI, tone='tense', min_day=2,
         opening='Đi tuần sau trận mưa đêm, bạn thấy đá ba-lát dưới một đoạn ray trôi mất, ray treo hẫng. Mười lăm phút nữa có tàu.',
         facts=[dict(id='hang', title='Đoạn ray', source='Mắt bạn', text='Ray treo hẫng hai gang tay, tà vẹt lơ lửng.'),
                dict(id='time', title='Thời gian', source='Bảng giờ', text='Tàu khách SE tới sau mười lăm phút.'),
                dict(id='rule', title='Nội quy tuần đường', source='Sổ tay', text='Thấy chỗ nguy hiểm: cắm cờ đỏ phòng vệ hai đầu, điện khẩn ngay cho ga.')],
         options=[dict(id='protect', label='Điện khẩn cho ga, cắm cờ đỏ phòng vệ hai đầu, đứng chờ tổ thợ', requires=['hang', 'rule'], quality='good', stars=5,
                       review='Thợ tuần đường báo khẩn kịp, tàu dừng trước đoạn hỏng. Đúng quy trình.', outcome='Ga dừng tàu SE ở Bến Gỗ. Tổ thợ chèn đá xong, tàu qua chậm an toàn.',
                       perspectives=[dict(who='Anh Khải', emoji='🔩', text='Báo khẩn mà sai thì mất mười phút. Không báo mà đúng thì mất cả chuyến tàu.'),
                                     dict(who='Hành khách tàu SE', emoji='🧳', text='Trễ hai mươi phút, không ai biết mình vừa thoát cái gì.')]),
                  dict(id='form', label='Ghi phiếu báo hỏng gửi cung, mai thợ tới', requires=['hang'], quality='bad', stars=1,
                       review='Ray treo hẫng mà chỉ ghi phiếu, không báo khẩn.', outcome='Tàu SE qua đoạn ray hẫng, rung lắc dữ dội. Ga gọi hỏi tại sao không báo.',
                       perspectives=[dict(who='Lái tàu', emoji='🚆', text='Tôi tưởng tàu trật bánh.'), dict(who='Anh Quý', emoji='📋', text='Sai kênh báo là sai to.')]),
                  dict(id='fill', label='Tự xúc đá chèn tạm rồi đi tiếp', requires=['time'], quality='bad', stars=2,
                       review='Tự chèn tạm mà không báo ga, không phòng vệ.', outcome='Chèn được ít đá, ray vẫn lún. Tàu qua chậm vì lái tàu tự thấy.',
                       perspectives=[dict(who='Anh Khải', emoji='🔩', text='Việc đó của tổ thợ, việc của mình là báo và phòng vệ.'),
                                     dict(who='Chị Nguyệt', emoji='📻', text='Ga mà biết sớm thì đâu cần lái tàu tự thấy.')])],
         lesson='Chỗ hỏng nguy hiểm: phòng vệ trước và báo khẩn cho ga; phiếu báo hỏng chỉ cho việc không gấp.'),
    dict(id='RW-S05', title='Sếp bảo ghi giờ cho đẹp', npc=QUY, tone='gentle', min_day=3,
         opening='Cuối tháng, anh Quý nói nhỏ: “Mấy chuyến chậm tuần này em ghi đúng giờ hết cho báo cáo cung đẹp nhé.”',
         facts=[dict(id='log', title='Sổ nhật ký', source='Nội quy', text='Sổ nhật ký đường ngang là văn bản gốc khi điều tra sự cố.'),
                dict(id='late', title='Sự thật', source='Sổ của bạn', text='Tuần này có ba chuyến chậm trên mười lăm phút.'),
                dict(id='kpi', title='Thưởng', source='Anh Quý', text='Cung đạt chỉ tiêu đúng giờ thì cả cung được thưởng.')],
         options=[dict(id='true', label='Ghi đúng sự thật, đề nghị ghi chú lý do chậm để cung giải trình', requires=['log', 'late'], quality='good', stars=5,
                       review='Ca gác ghi sổ trung thực, có ghi chú lý do. Báo cáo giải trình rõ ràng.', outcome='Anh Quý im lặng một lúc rồi gật: “Ừ. Ghi lý do vào.”',
                       perspectives=[dict(who='Anh Quý', emoji='📋', text='Cấp trên đọc thấy lý do, chẳng ai trách.'),
                                     dict(who='Chú Sáu', emoji='🚩', text='Sổ sai một lần thì không ai tin sổ nữa.')]),
                  dict(id='fake', label='Ghi đúng giờ như sếp bảo', requires=['kpi'], quality='bad', stars=1,
                       review='Sổ nhật ký ghi giờ không đúng thực tế.', outcome='Tháng sau có sự cố, đoàn kiểm tra đối chiếu sổ với ga: vênh hết.',
                       perspectives=[dict(who='Đoàn kiểm tra', emoji='🔎', text='Sổ ghi một đằng, ga ghi một nẻo.'), dict(who='Anh Quý', emoji='😓', text='Tôi sai khi bảo cậu vậy.')]),
                  dict(id='dodge', label='Ừ cho qua, rồi vẫn ghi đúng', requires=['log'], quality='ok', stars=4,
                       review='Ghi đúng, nhưng không nói thẳng nên sếp tưởng cậu đã sửa.', outcome='Báo cáo vẫn đúng, nhưng anh Quý bất ngờ và phật lòng.',
                       perspectives=[dict(who='Anh Quý', emoji='😒', text='Không đồng ý thì nói thẳng chứ.'), dict(who='Chú Sáu', emoji='🚩', text='Đúng rồi, nhưng nói ra thì tốt hơn.')])],
         lesson='Sổ nhật ký phải ghi đúng sự thật; muốn đẹp thì ghi rõ lý do, không sửa giờ.'),
    dict(id='RW-S06', title='Xe tải chết máy giữa ray', npc=SAU, tone='tense', min_day=3,
         opening='Ga vừa báo tàu còn bốn phút. Một xe tải chở gạch chết máy ngay giữa đường ngang, tài xế đạp đề mãi không nổ.',
         facts=[dict(id='time', title='Thời gian', source='Bộ đàm', text='Tàu còn bốn phút, đang chạy tốc độ thường.'),
                dict(id='stop', title='Báo dừng tàu', source='Nội quy', text='Đường ngang có vật cản không dẹp kịp: báo ga dừng tàu, ra cờ đỏ về phía tàu tới.'),
                dict(id='push', title='Đẩy xe', source='Chú Sáu', text='Xe tải chở gạch nặng hơn mười tấn, người không đẩy nổi.')],
         options=[dict(id='stop', label='Báo ga dừng tàu ngay, cầm cờ đỏ chạy ngược về phía tàu tới, gọi xe cứu hộ', requires=['time', 'stop'], quality='good', stars=5,
                       review='Ca gác báo dừng tàu kịp thời, cờ đỏ ra đúng hướng. Không ai bị gì.', outcome='Tàu dừng cách đường ngang ba trăm mét. Xe cứu hộ kéo xe tải ra sau hai mươi phút.',
                       perspectives=[dict(who='Lái tàu', emoji='🚆', text='Thấy cờ đỏ từ xa là tôi phanh luôn.'),
                                     dict(who='Tài xế xe tải', emoji='🚚', text='Tôi tưởng hết đời rồi.')]),
                  dict(id='push', label='Gọi mọi người ra đẩy xe', requires=['time'], quality='bad', stars=1,
                       review='Gọi người dân ra đẩy xe tải giữa ray lúc tàu sắp tới. Quá liều.', outcome='Xe không nhúc nhích. Tàu tới, mọi người chạy tán loạn, lái tàu phanh khẩn cấp.',
                       perspectives=[dict(who='Bà Bông', emoji='👵', text='Tôi già rồi mà còn chạy không kịp thở.'), dict(who='Lái tàu', emoji='😱', text='Tôi thấy người đứng đầy trên ray.')]),
                  dict(id='hope', label='Giục tài xế đề tiếp, chắc nổ kịp', quality='bad', stars=1,
                       review='Không báo dừng tàu khi có vật cản trên ray.', outcome='Xe vẫn không nổ. Lái tàu thấy xe tải từ xa, phanh khẩn cấp, dừng sát nút.',
                       perspectives=[dict(who='Chị Nguyệt', emoji='📻', text='Sao không báo ga?'), dict(who='Chú Sáu', emoji='🚩', text='Hy vọng không phải là biện pháp an toàn.')])],
         lesson='Vật cản không dẹp kịp: báo ga dừng tàu và ra cờ đỏ về phía tàu tới, đừng đặt hy vọng vào may mắn.'),
]


# ---------------------------------------------------------------- chuyện oái oăm (game/careers/air_odd.py scripts)
# Railway words for what the player can say (air_odd.LABELS speaks airline); every script gets them unless it says its own.
WORDS = {
    'charm': dict(no='Em xin phép từ chối.', duty='Em đang trong ca gác.', rule='Xí nghiệp không cho nhận quà, hẹn hò khi trực.',
                  alt='Cảm ơn, chúc mọi người đi đường bình an.', joke='Cười cười cho qua.', later='Để hôm khác nha…', yes='Nhận lời.'),
    'harass': dict(stop='Dừng lại ngay.', no='Không. Tôi không đồng ý.', rule='Quấy rối người đang làm việc là vi phạm.',
                   duty='Tôi đang làm việc.', joke='Cười trừ cho qua.', later='Thôi, bỏ qua đi.', yes='Chiều cho xong chuyện.'),
    'demand': dict(no='Dạ không được ạ.', rule='Nội quy gác chắn không cho phép.', alt='Có cách khác nè…', why='Mình cần vậy vì sao ạ?',
                   joke='Đùa cho qua.', later='Để em xem đã.', yes='Chiều theo.'),
    'corner': dict(speak='Mình chưa làm đủ bước.', rule='Quy trình bắt buộc mà.', alt='Làm nhanh mà vẫn đủ bước.',
                   joke='Cười xòa cho qua.', yes='Làm theo.'),
    'bargain': dict(rule='Vượt giờ làm quy định rồi.', health='Sức khỏe em không cho phép.', alt='Em đề xuất cách khác.',
                    paper='Cho em xin văn bản phân công.', yes='Nhận hết.'),
}


# Railway outcome lines where air_odd.TEXT would speak of the airline (a script's own line still wins).
TEXT = {
    'charm': dict(report='Bạn báo đội trưởng. Đội ghi nhận và nhắc khéo {who}; hồ sơ bạn thêm dòng “xử lý đúng mực”.',
                  stuck='Chuyện cứ lấp lửng không dứt. Ngoài quán nước bắt đầu có người xì xào.'),
    'corner': dict(report='Bạn báo cung trưởng (người báo không bị phạt). Cung cử người kiểm tra lại; {who} phải học lại quy trình.',
                   stuck='{who} vẫn làm tắt. Hôm nay qua êm, nhưng bạn biết mình đã im lặng.'),
}


def _odd(sid, kind, rank, emoji, title, who, text, push, **kw):
    x = dict(id=sid, kind=kind, rank=rank, emoji=emoji, title=title, who=who, text=text, push=list(push), **kw)
    x['words'] = {**WORDS[kind], **kw.get('words', {})}
    for k, v in TEXT.get(kind, {}).items():
        x.setdefault(k, v)
    return x


ODD = [
    # --- charm: decline, set the line, report if it keeps coming
    _odd('rw-tea', 'charm', 'pax', '🍵', 'Chén chè “có ý”', 'Cô Thơm · bán bánh đa đầu ngõ',
         '“Anh gác chắn ơi, tối nay hết ca ghé nhà em ăn cơm nha, mẹ em đi vắng, em nấu riêng cho anh 😊”',
         ['“Có ai biết đâu mà anh ngại. Một bữa cơm thôi mà.”', '“Anh khó gần thế. Em mang cơm ra tận chòi luôn nhé?”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         back='Cô Thơm cười ngượng: “Thôi được, anh nghiêm túc ghê.” Rồi đạp xe đi.',
         give='Bạn nhận lời. Hôm sau cả phố Ray xì xào, cô Thơm thì nhắn tin suốt giờ trực, bạn lỡ cả cuộc gọi của ga.'),
    _odd('rw-selfie-girl', 'charm', 'pax', '🤳', 'Hot girl xin chụp chung trong chòi', 'Linh Linh · 300k follow',
         '“Anh ơi cho em vào chòi chụp chung một tấm, mặc đồng phục của anh nha, content “crush anh gác chắn” đang hot lắm!”',
         ['“Có một tấm thôi mà anh, em tag cả xí nghiệp luôn cho nổi.”', '“Anh không chụp thì em đăng clip anh từ chối, cho mạng xã hội phán nha 🙃”'],
         persist=(2, 3), mood=(0, 2), weight=2, words={'alt': 'Muốn quay thì liên hệ xí nghiệp nhé, đứng ngoài vạch thôi.'},
         back='Linh Linh bĩu môi rồi quay clip con tàu từ ngoài vạch. Vẫn lên xu hướng.',
         give='Bạn cho vào chòi. Clip “anh gác chắn mặc đồng phục tạo dáng” lên xu hướng, kèm cảnh nút hạ chắn bị chạm nhầm.'),
    _odd('rw-trucker-gift', 'charm', 'boss', '🎁', 'Giỏ quà của chủ bãi xe', 'Ông Bảy Lộc · chủ bãi xe tải',
         '“Tết nhất có giỏ quà cho cậu. Đêm xe tôi qua, cậu thương thì nâng chắn sớm chút, đỡ cho tài xế chờ.”',
         ['“Quà nhỏ thôi, ai mà chả nhận. Đừng làm khó nhau.”', '“Không nhận thì tôi nói với cung trưởng là cậu làm khó xe tôi.”'],
         persist=(1, 2), mood=(0, 2), weight=2, words={'rule': 'Nâng chắn theo tàu, không theo quà.', 'alt': 'Bác mang giỏ quà về giúp cháu.'},
         back='Ông Bảy Lộc xách giỏ quà về, lắc đầu: “Cậu này cứng.”',
         give='Bạn nhận giỏ quà. Hai tuần sau đội kiểm tra hỏi chuyện “quà của bãi xe”, tên bạn nằm đầu danh sách.'),
    _odd('rw-date-dm', 'charm', 'pax', '💌', 'Tin nhắn lúc ca đêm', 'Một số lạ · “bạn cũ”',
         '“Ca đêm buồn không anh? Em qua chòi ngồi nói chuyện cho đỡ buồn nha, em mang trà sữa 😉”',
         ['“Ngồi nói chuyện thôi mà, có làm gì đâu.”', '“Em đứng ngoài chòi rồi nè, mở cửa đi.”'],
         persist=(1, 3), mood=(0, 1), weight=1, words={'alt': 'Hẹn hôm khác ngoài giờ, ngồi quán cho đàng hoàng.'},
         back='Không có tiếng gõ cửa nữa. Bạn ghi giờ tàu kế tiếp lên bảng.',
         give='Bạn mở cửa chòi. Mải nói chuyện, bạn nghe chậm cuộc gọi báo tàu của ga hai phút.'),
    # --- harassment around the crossing
    _odd('rw-harass-vendor', 'harass', 'pax', '🚨', 'Gã say trêu chị bán xôi', 'Gã đàn ông say ở quán nước',
         'Một gã say xỉn cứ níu tay cô bán xôi đang chờ chắn, buông lời khiếm nhã: “Bán xôi hay bán gì, cho anh mua cả người nha.”',
         ['Gã càng lấn tới, chặn xe xôi không cho cô đi.', 'Cô bán xôi rơm rớm nước mắt nhìn sang chòi gác.'],
         persist=(2, 3), mood=(1, 2), weight=2,
         words={'stop': 'Quát: “Dừng tay lại!”', 'no': 'Đứng chắn giữa hai người.', 'rule': 'Gọi công an phường tới.', 'duty': 'Tôi đang gác, chị tự lo nhé.',
                'joke': 'Say mà, chị cười cho qua.', 'later': 'Tàu qua rồi tính.', 'yes': 'Chị chịu khó chiều hắn chút.'},
         back='Gã say lủi đi, lầm bầm. Cô bán xôi cảm ơn bạn, tay vẫn run.',
         report='Bạn gọi công an phường. Họ tới lập biên bản gã say; cô bán xôi được đưa về tận nhà. Tổ dân phố cảm ơn ca gác.',
         stuck='Gã say quấy tới khi chắn nâng rồi bỏ đi. Không ai ghi lại gì, nên mai hắn lại ra quán. Lần sau: báo luôn.',
         give='Không ai phải “chiều” kẻ quấy rối. Cô bán xôi tự xoay xở, đẩy xe chạy vội, đổ cả nồi xôi.', follow='rw_drunkman'),
    _odd('rw-harass-me', 'harass', 'pax', '😡', 'Tài xế quay clip lăng mạ', 'Gã tài xế xe con biển lạ',
         'Bị giữ chắn, gã tài xế quay điện thoại sát mặt bạn: “Gác chắn mặt mũi thế này mà cũng làm giá. Cả nhà xem nè, đánh giá mấy điểm?”',
         ['Gã quay tiếp, chĩa máy vào thẻ tên của bạn đọc to họ tên.', '“Tao đăng lên, cho mày nổi tiếng luôn.”'],
         persist=(2, 3), mood=(1, 2), weight=2,
         words={'stop': 'Anh dừng quay, lùi ra sau vạch.', 'no': 'Tôi không đồng ý bị quay mặt.', 'rule': 'Lăng mạ người đang trực gác là vi phạm.',
                'duty': 'Tôi đang trực gác.', 'joke': 'Cười cho qua.', 'later': 'Thôi kệ.', 'yes': 'Đứng yên cho hắn quay.'},
         back='Gã tắt máy, lẩm bẩm chửi rồi ngồi im trong xe. Chắn nâng là phóng đi mất.',
         report='Bạn báo đội và công an phường, đọc biển số. Clip đăng lên bị bình luận ngược: “người ta làm đúng mà”. Xí nghiệp gửi văn bản bảo vệ nhân viên.',
         stuck='Gã đăng clip, cắt mất đoạn tàu chạy qua. Không phải lỗi của bạn; báo đội để xí nghiệp lên tiếng giúp.',
         give='Bạn đứng chịu trận. Clip lan đi với chú thích sai sự thật. Không phải lỗi của bạn: lần sau cứ báo đội.'),
    _odd('rw-harass-colleague', 'harass', 'crew', '🙅', 'Ông trưởng ca bên kia buông lời', 'Ông Toại · trưởng ca đường ngang Km 6',
         'Giao ban qua bộ đàm, ông Toại cười khẩy: “Gác chắn Bến Mây ca này có em nào xinh không? Cho anh xin số, tối anh ghé chòi.”',
         ['“Đùa tí mà căng thế. Tối anh ghé thật đấy.”', '“Bọn trẻ bây giờ đùa tí cũng không biết.”'],
         persist=(1, 3), mood=(0, 2), weight=1,
         words={'stop': 'Anh dừng lại.', 'no': 'Tôi không đùa kiểu đó.', 'rule': 'Bộ đàm là kênh công việc.', 'duty': 'Em đang trực.',
                'joke': 'Cười trừ.', 'later': 'Thôi bỏ qua.', 'yes': 'Cho số cho xong.'},
         back='Bộ đàm im một lúc. Ông Toại chuyển sang đọc giờ tàu, giọng nghiêm hẳn.',
         report='Bạn báo đội trưởng, kèm giờ và kênh bộ đàm. Ông Toại bị nhắc nhở bằng văn bản và phải xin lỗi.',
         stuck='Ông Toại cười cho qua. Chẳng ai ghi lại, nên tuần sau ông lại thế. Không phải lỗi của bạn; báo đội là quyền của bạn.',
         give='Bạn cho số. Tối đó ông Toại nhắn tin liên tục. Không phải lỗi của bạn; cứ báo đội, xí nghiệp có quy trình bảo vệ.'),
    # --- odd demands
    _odd('rw-horn-stop', 'demand', 'pax', '📯', '“Bảo tàu đừng kéo còi”', 'Bà Bông · hàng nước sát ray',
         '“Cháu gọi cho ga bảo tàu năm giờ sáng đừng kéo còi nữa! Cháu bà ôn thi mà cứ giật mình!”',
         ['“Cháu là người nhà nước, cháu nói chắc ga nghe!”', '“Không nói được thì cháu gác chắn làm gì?”'],
         persist=(1, 3), mood=(0, 2), weight=3, npc=LANH,
         words={'rule': 'Còi là tín hiệu an toàn bắt buộc khi tới đường ngang.', 'alt': 'Cháu ghi phiếu ý kiến của bà gửi xí nghiệp.'},
         back='Bà Bông nguýt dài nhưng nhận tờ phiếu ý kiến: “Ừ, có giấy tờ thì bà chờ.”',
         give='Bạn hứa sẽ bảo tàu thôi kéo còi. Sáng mai còi vẫn rúc, bà Bông bảo bạn nói dối cả phố.',
         review={'give': [2, 'Hứa bảo tàu thôi kéo còi rồi để đó. Nói cho vui à?'], 'back': [4, 'Không bỏ được còi nhưng có người chịu nghe, chịu ghi.']}),
    _odd('rw-close-festival', 'demand', 'boss', '🏮', 'Chặn đường ngang làm hội', 'Ông Tổ trưởng · tổ dân phố phố Ray',
         '“Tối mai phố làm Trung thu. Cậu đóng chắn luôn từ bảy đến chín giờ cho tụi nhỏ rước đèn trên ray, chụp ảnh cho đẹp.”',
         ['“Phường đồng ý miệng rồi, cậu cứ đóng.”', '“Cả phố có một tối, cậu khó gì thế.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Chắn chỉ hạ theo giờ tàu; đường ray không phải chỗ rước đèn.', 'alt': 'Rước đèn ở bãi đất trống, em chỉ chỗ thấy tàu mà an toàn.'},
         back='Ông tổ trưởng gật gù dời đoàn rước đèn ra bãi đất trống. Tụi nhỏ vẫn vẫy tàu từ xa, an toàn.',
         give='Bạn đồng ý miệng. Tối đó tàu hàng tới đúng lúc đoàn rước đèn kéo ra ray. Bạn phải cầm cờ đỏ chạy dọc đường.', breach=3),
    _odd('rw-mom-call', 'demand', 'kin', '📞', 'Mẹ gọi về sửa bóng đèn', 'Mẹ bạn',
         '“Con về ngay sửa giúp mẹ cái bóng đèn nhà tắm! Nửa tiếng thôi, chắn tàu để đó ai lấy mà lo.”',
         ['“Con làm gì mà bận hơn cả mẹ?”', '“Mẹ gọi chú Hớn sang trông giúp chòi nha?”'],
         persist=(1, 2), mood=(0, 1), weight=2,
         words={'rule': 'Chòi gác không được bỏ trống, mẹ ơi.', 'alt': 'Hết ca con về sửa liền, mẹ để đèn bàn tạm nhé.'},
         back='Mẹ thở dài: “Ừ, hết ca về sớm nha con.” Tối đó bạn mua bóng mới mang về.',
         give='Bạn bỏ chòi chạy về. Đúng lúc đó ga gọi báo tàu, không ai nghe. Anh Quý biết chuyện ngay chiều đó.', breach=3),
    _odd('rw-raise-early', 'demand', 'pax', '⏱️', '“Tàu khuất rồi, nâng đi!”', 'Đám đông chờ ở vạch dừng',
         'Đuôi tàu vừa qua khỏi đường ngang, cả đám đông nhao nhao: “Qua rồi! Qua rồi! Nâng chắn đi còn chờ gì nữa!”',
         ['“Tàu đi xa rồi, chờ gì nữa ông gác!”', '“Đóng chắn để ngắm à?”'],
         persist=(1, 3), mood=(1, 2), weight=3,
         words={'rule': 'Phải hỏi ga xem còn tàu nào không rồi mới nâng.', 'alt': 'Mọi người chờ em nửa phút, em hỏi ga ngay.'},
         back='Đám đông lầm bầm nhưng chờ. Ga xác nhận không còn tàu, bạn nâng chắn.',
         give='Bạn nâng vội. Đúng lúc đó còi tàu thứ hai rúc lên từ hướng ngược lại. Bạn hạ chắn khẩn cấp, xe phanh rít cả dãy.', breach=4),
    _odd('rw-borrow-flag', 'demand', 'pax', '🚩', 'Mượn cờ đỏ chụp ảnh', 'Nhóm sinh viên làm phim ngắn',
         '“Anh cho tụi em mượn cờ đỏ với đèn cầm tay quay cảnh “cô gái chặn tàu” nha, mười phút trả liền!”',
         ['“Cờ thôi mà, có phải súng đâu anh.”', '“Tụi em đứng xa ray mà, không sao đâu.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         words={'rule': 'Cờ và đèn là tín hiệu chạy tàu, không cho mượn.', 'alt': 'Em mua cờ vải đỏ ngoài chợ, quay ở bãi cỏ nhé.'},
         back='Nhóm sinh viên chạy ra chợ mua vải đỏ. Phim vẫn quay được, ở bãi cỏ xa ray.',
         give='Bạn cho mượn. Lái tàu địa phương thấy cờ đỏ vẫy từ xa, phanh gấp giữa đồng.', breach=4),
    _odd('rw-cafe-later', 'demand', 'pax', '☕', 'Cô Mận xin “nâng muộn chút”', 'Cô Mận · quán cà phê đường tàu',
         '“Lúc tàu qua cháu đóng chắn muộn chút nha, khách đứng sát ray quay clip tàu chạy cho “phê”, quán cô sống nhờ cái đó.”',
         ['“Có sao đâu, khách tự chịu mà.”', '“Cô biếu cháu tháng một trăm xu, cháu nghĩ đi.”'],
         persist=(2, 3), mood=(0, 2), weight=2, npc=MAN,
         words={'rule': 'Hạ chắn đúng giờ, người phải ở ngoài vạch.', 'alt': 'Cô kê ghế lùi ba mét, khách vẫn quay được mà an toàn.'},
         back='Cô Mận cằn nhằn nhưng kẻ vạch sơn trước quán: “Khách đứng sau vạch.”',
         give='Bạn đồng ý. Một vị khách đứng sát ray bị luồng gió tàu giật bay điện thoại, suýt ngã.', breach=4,
         review={'back': [4, 'Cậu gác chắn cứng nhưng chỉ cách cho quán vẫn có ảnh đẹp.'], 'give': [2, 'Hôm nay khách suýt ngã, quán bị nhắc nhở.']}),
    _odd('rw-carry-goods', 'demand', 'pax', '📦', 'Gửi hàng lên tàu', 'Chị Duyên · bán hàng online',
         '“Em gửi thùng hàng này, lúc tàu địa phương qua em ném lên toa cho người nhà đứng chờ, tiết kiệm phí ship!”',
         ['“Tàu chạy chậm mà, ném cái là lên.”', '“Anh không giúp thì thôi, em tự ném.”'],
         persist=(1, 3), mood=(0, 2), weight=1,
         words={'rule': 'Không ai được ném, chuyền đồ lên tàu đang chạy.', 'alt': 'Chị gửi hàng ở ga Bến Mây, có quầy gửi hàng.'},
         back='Chị Duyên ôm thùng hàng ra ga. Quầy gửi hàng rẻ hơn chị tưởng.',
         give='Bạn để chị đứng sát ray chờ ném. Thùng hàng dội lại, văng trúng cột đèn.', breach=3),
    _odd('rw-neighbor-park', 'demand', 'pax', '🛻', 'Gửi xe trong hành lang ray', 'Anh Hiếu · nhà mặt phố Ray',
         '“Cho anh để tạm xe ba gác sát ray tối nay nhé, nhà anh hết chỗ. Sáng anh dắt đi sớm.”',
         ['“Có một tối thôi mà em.”', '“Chú Sáu ngày xưa vẫn cho mà.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         words={'rule': 'Hành lang an toàn đường sắt không được để xe.', 'alt': 'Anh gửi bãi xe chợ, em gọi giúp ông bảo vệ.'},
         back='Anh Hiếu dắt xe sang bãi chợ, còn cảm ơn bạn gọi trước cho ông bảo vệ.',
         give='Bạn cho để. Đêm đó gió lật tấm bạt trên xe trùm lên ray, tàu hàng phải giảm tốc.', breach=3),
    # --- corners cut: say it, then report (reports are no-blame)
    _odd('rw-sign-early', 'corner', 'crew', '✍️', '“Ký nhận ca trước giùm”', 'Anh Lộc · gác chắn ca sau',
         '“Em ký sổ giao ca trước giùm anh, ghi “thiết bị bình thường” luôn, anh tới trễ nửa tiếng, khỏi kiểm.”',
         ['“Có hỏng gì đâu mà kiểm, ngày nào chả vậy.”', '“Em mới vào nghề mà khó tính ghê.”'],
         persist=(1, 3), mood=(0, 2), weight=3,
         back='Anh Lộc thở dài, tới nơi tự thử chuông, thử cần chắn. Đèn đỏ phía Nam hôm đó mờ thật.',
         give='Bạn ký thay “bình thường”. Chiều đó đèn đỏ phía Nam tắt mà không ai biết, một xe máy suýt lao vào chắn.', severe=3),
    _odd('rw-nap', 'corner', 'crew', '😴', '“Chợp mắt đi, anh canh cho”', 'Anh Lộc · gác chắn ca sau',
         '“Tàu đêm chậm bốn mươi phút đấy, em ngả lưng đi, anh ngồi đây nghe bộ đàm cho.”',
         ['“Ai mà biết, chợp mắt tí thôi.”', '“Anh làm hai chục năm rồi, em yên tâm.”'],
         persist=(1, 3), mood=(0, 1), weight=2,
         back='Bạn cảm ơn, rửa mặt rồi ngồi thẳng lưng. Anh Lộc cười: “Ừ, chắc vậy là đúng.”',
         give='Bạn ngủ. Anh Lộc cũng ngủ gật. Bộ đàm gọi ba lần mới có người nghe.', severe=3),
    _odd('rw-skip-patrol', 'corner', 'crew', '🌧️', '“Mưa thế này khỏi tuần đường”', 'Anh Khải · thợ tuần đường',
         '“Mưa to thế này đi tuần làm gì, ướt hết. Ghi sổ “đã tuần, bình thường” rồi vào chòi uống trà.”',
         ['“Đoạn đó năm nào chả thế, có sao đâu.”', '“Em đi một mình thì đi, anh không đi.”'],
         persist=(1, 2), mood=(0, 1), weight=2, npc=KHAI,
         back='Anh Khải càu nhàu, mặc áo mưa đi cùng. Ở cống Km 7+420, đá ba-lát trôi một đoạn thật.',
         give='Bạn ghi “đã tuần, bình thường”. Sáng hôm sau đoạn cống Km 7+420 lún, tàu phải dừng khẩn cấp.', severe=3),
    _odd('rw-fake-time', 'corner', 'boss', '📝', '“Ghi giờ cho đẹp báo cáo”', 'Anh Quý · cung trưởng',
         '“Chuyến SE chậm hai mươi phút sáng nay em ghi đúng giờ nhé, tháng này cung đang thi đua.”',
         ['“Có mỗi dòng thôi, ai soát đâu.”', '“Anh nói thế mà em không nghe à?”'],
         persist=(1, 3), mood=(0, 2), weight=2, npc=QUY,
         words={'alt': 'Em ghi đúng giờ, thêm ghi chú lý do chậm cho cung giải trình.'},
         back='Anh Quý im một lúc: “Ừ. Ghi lý do vào.” Báo cáo tháng đó có ghi chú rõ ràng.',
         give='Bạn sửa giờ. Tháng sau đoàn kiểm tra đối chiếu với sổ ga: vênh hai mươi phút.', severe=3),
    _odd('rw-bolt-fake', 'corner', 'crew', '🔩', '“Ghi là đã siết rồi”', 'Anh Toàn · tổ thợ cung',
         '“Mấy con bu lông lỏng ở Km 7 em ghi “đã siết” giùm anh, mai anh làm. Hôm nay tổ hết giờ rồi.”',
         ['“Bu lông thôi mà, một hôm có sao.”', '“Em ghi đúng thì anh bị kiểm điểm đấy.”'],
         persist=(1, 3), mood=(0, 2), weight=2,
         back='Anh Toàn lầm bầm rồi quay lại siết luôn trong mười phút. “Thôi, làm cho xong.”',
         give='Bạn ghi “đã siết”. Ba hôm sau mối nối đó rơ hẳn, tàu hàng qua kêu lốc cốc.', severe=2),
    _odd('rw-open-early', 'corner', 'crew', '⏩', '“Nâng luôn, hỏi ga làm gì”', 'Anh Lộc · gác chắn ca sau',
         '“Tàu qua rồi thì nâng luôn, hỏi ga làm gì cho mất công. Giờ này làm gì còn tàu.”',
         ['“Hỏi ga mất cả phút, xe dồn kìa.”', '“Anh gác hai chục năm có bao giờ hỏi đâu.”'],
         persist=(1, 3), mood=(0, 2), weight=2,
         back='Anh Lộc chép miệng, cầm bộ đàm hỏi ga. Ga báo: “Có tàu hàng H2 đang tới đường 2.” Anh Lộc tái mặt.',
         give='Bạn nâng chắn không hỏi. Ba phút sau tàu hàng rúc còi ở đầu kia, bạn hạ chắn khẩn cấp.', severe=3),
    _odd('rw-lend-cabin', 'corner', 'kin', '🏠', 'Em họ xin ngồi chòi chơi game', 'Thằng Bin · em họ bạn',
         '“Anh ơi cho em ngồi trong chòi chơi game, có điều hòa với wifi xí nghiệp, em không đụng gì đâu!”',
         ['“Em ngồi im mà, anh khó thế.”', '“Mẹ em bảo anh trông em mà.”'],
         persist=(1, 2), mood=(0, 1), weight=1,
         words={'speak': 'Chòi gác không phải chỗ chơi.', 'rule': 'Người ngoài không được vào chòi.', 'alt': 'Em ngồi quán bà Bông, hết ca anh chở về.'},
         back='Thằng Bin phụng phịu sang quán bà Bông, được bà cho cốc chè.',
         give='Bạn cho vào. Thằng Bin tò mò bấm thử nút chuông giữa lúc không có tàu, cả phố giật mình.', severe=2),
    # --- bargains with the depot
    _odd('rw-double', 'bargain', 'boss', '🌙', 'Gác thêm ca đêm', 'Anh Quý · cung trưởng',
         '“Tuần này thiếu người. Em gác thêm ba ca đêm liền nhé, cuối tháng có thêm tiền.”',
         ['“Cả cung đang khó, em chịu khó chút.”', '“Không nhận thì tháng này khó xét thưởng đó.”'],
         ask=3, limit=1, unit='ca đêm', pay=8, tire=2, cost=10, weight=3, npc=QUY,
         lawful='Anh Quý hậm hực nhưng đành xếp thêm người: luật giờ nghỉ đứng về phía bạn.'),
    _odd('rw-cover', 'bargain', 'crew', '🔁', 'Đổi ca cho anh Lộc', 'Anh Lộc · gác chắn ca sau',
         '“Em gác thay anh hai ca cuối tuần nhé, anh có đám giỗ. Tuần sau anh trả.”',
         ['“Có hai ca thôi mà em.”', '“Anh nhờ mỗi em thôi đó.”'],
         ask=2, limit=1, unit='ca', pay=6, tire=2, cost=0, weight=2),
    _odd('rw-km', 'bargain', 'boss', '🚶', 'Tuần thêm cả đoạn Km 9', 'Anh Quý · cung trưởng',
         '“Tổ tuần đường thiếu người. Tuần này em đi thêm bốn ca tuần đoạn Km 9 nữa nhé, đi bộ khỏe người.”',
         ['“Đi bộ thôi mà, có gì đâu.”', '“Ai cũng phải gánh thêm.”'],
         ask=4, limit=2, unit='ca tuần', pay=5, tire=1, cost=10, weight=2, npc=QUY),
    _odd('rw-holiday', 'bargain', 'boss', '🎆', 'Trực xuyên lễ', 'Đội trưởng đội gác chắn',
         '“Dịp lễ này em trực liền bốn ngày nhé, người khác về quê hết rồi.”',
         ['“Lễ nào chả thế, ráng đi em.”', '“Có ai được nghỉ đâu.”'],
         ask=4, limit=2, unit='ngày trực', pay=7, tire=2, cost=12, weight=1),
]

DAY_LINES = dict(odd='🙄 Gặp {n} chuyện oái oăm, xử lý đẹp {ok}.', record='📁 Hồ sơ: {label}.',
                 tired='😮‍💨 Mệt rồi: thưởng ca chỉ còn một nửa. Xin nghỉ bù ở chòi gác.')
