/** Finished paintings are separate buildings, not variations of a shared house.
 * Gameplay footprints, door positions and career availability stay server-owned. */
export interface CareerArtSign {x:number;y:number;width:number;height:number;angle:number;panel?:boolean}
export interface CareerArtwork {
  career:string;
  key:string;
  src:string;
  tradeName:string;
  architecture:string;
  sign:CareerArtSign;
}

/** Fractions of the trimmed image, centred on its painted front-left name board.
 * Each entry is measured on the shipped careers-v1 painting. Width and height
 * describe the inner text area, leaving the painted frame visible. No new panel
 * is drawn over the complete painting. */
const frontSign:CareerArtSign={x:.38,y:.38,width:.34,height:.075,angle:.30};
const exterior=(career:string,tradeName:string,architecture:string,sign:Partial<CareerArtSign>={}):CareerArtwork=>({
  career,key:'career-'+career,src:'/icons/careers-v1/'+career+'.webp',tradeName,architecture,sign:{...frontSign,...sign},
});

export const CAREER_ART:Readonly<Record<string,CareerArtwork>>={
  grocery:exterior('grocery','Tiệm tạp hóa',"A ONE STORY broad open-front Vietnamese neighborhood grocery kiosk. Low moss-green hipped corrugated roof, timber open shutters, side pantry extension, dense colorful packets hanging from an exposed crossbeam, glass jars and rice sacks, woven vegetable baskets, stepped orange tile threshold. No upper floor. Large storefront entirely open, clear front door position.",{x:0.3533,y:0.3158,width:0.282,height:0.056,angle:0.27}),
  cafe_bakery:exterior('cafe_bakery','Lò bánh và cà phê',"An artisanal Vietnamese riverside BAKERY CAFE: low L-shaped building, large circular brick bread oven chimney at one end, weathered sage zinc shed roof over coffee veranda, warmly lit curved glass pastry case facing front, bread racks, two woven cafe chairs beneath curved terracotta awning. Long horizontal silhouette, no upper storey.",{x:0.2573,y:0.2711,width:0.212,height:0.0568,angle:0.329}),
  milk_tea:exterior('milk_tea','Quán trà sữa',"A playful Vietnamese BUBBLE TEA cafe in a compact two-volume kiosk: cylindrical pale apricot serving tower with scalloped flat canopy connected to low sage flat-roof lounge, generous glass takeaway hatch, rows of colorful cups and topping jars, curvy lime benches, sheltered pickup counter. No giant drink icon, actual architecture.",{x:0.325,y:0.4262,width:0.311,height:0.062,angle:0.1005}),
  florist:exterior('florist','Nhà hoa',"A florist garden conservatory: tall slender glasshouse with a steep green metal ridge roof and exposed slender frame, lower brick base, small timber side shed, very large open French doors, flower buckets and a visible bouquet work table; cascading flowers around structural trellis and porch. Most roof transparent glass, not red tile.",{x:0.3165,y:0.4648,width:0.247,height:0.0455,angle:0.2427}),
  mother_baby:exterior('mother_baby','Cửa hàng mẹ và bé',"A gentle Vietnamese maternity-and-baby boutique shaped as a compact CORNER bungalow with two overlapping peach-tile hip roofs, bowed nursery display window, pale pink and cream plaster, sheltered semicircular porch, two small strollers parked by entrance, tiny baby clothing neatly displayed behind glass, flowering bougainvillea. Wide single level, no tower.",{x:0.2962,y:0.4006,width:0.237,height:0.0564,angle:0.1981}),
  restaurant:exterior('restaurant','Nhà hàng',"A traditional Vietnamese courtyard family RESTAURANT with a U-shaped single storey layout, layered dark terracotta roof wings framing open dining courtyard, lantern-hung timber front gateway, several round dining tables inside visible open side, a substantial chimney and brick cooking annex to right. Large white sign integrated frontgateway at38percentheight.",{x:0.2673,y:0.5928,width:0.198,height:0.0476,angle:0.3834}),
  pho:exterior('pho','Quán phở',"An authentic PHO noodle kitchen: weathered mustard one-storey corner eatery with steep orange double roof and large old chimney, front entire wall folded open, gigantic visible stainless stockpot under tiled vent hood and steam represented static wisps, noodle baskets on preparation bench, two red stools; compact streetkitchen recognizably pho.",{x:0.3339,y:0.397,width:0.353,height:0.062,angle:0.2669}),
  com:exterior('com','Tiệm cơm',"A Vietnamese COM TAM grilled rice diner: long low pale ochre open-front eatery under green corrugated mono-pitch roof, brick charcoal grill with angular extraction hood at left, glass hot-food display at front, metal rice cooking pots, small lunch tables right, striped canvas sideline. Grill shape distinguishesfromstockpotpho.",{x:0.3993,y:0.354,width:0.357,height:0.062,angle:0.2271}),
  clothing:exterior('clothing','Cửa hàng thời trang',"A Vietnamese clothing boutique and tailor showroom: deep narrow two-storey pale lavender facade with steep rose roof and central glazed gable, enormous tall display bay showing two dress mannequins, curtained fitting-room window on side, fabric rolls and clothing rail under projecting striped fabric shade, timber double entry.",{x:0.27,y:0.5807,width:0.263,height:0.0456,angle:0.36}),
  zpop:exterior('zpop','Tiệm album',"An independent pop music RECORD shop: cool compact split-volume building with sloped butterfly copper roof, tall circular architectural window showing vinylrecords, open listening-booth side wing, broad glazed display of album sleeves (no faces/text), record racks and one retro speaker by entrance; warm cream +burgundy.",{x:0.3233,y:0.4673,width:0.396,height:0.054,angle:0.2517}),
  fruit:exterior('fruit','Vựa trái cây',"A Vietnamese FRUIT SELLER market stand: open timber stall under an asymmetric yellow-and-white canvas sail supported by bamboo poles, tiered wooden bins with watermelon/pineapple/mango/bananas, a hanging mechanical scale, handcart on side, little rear storage hut with half-height tiled roof. Low and horizontal, no two-storey shop.",{x:0.2989,y:0.4266,width:0.24,height:0.0585,angle:0.352}),
  farm:exterior('farm','Nông trại',"A compact WORKING VEGETABLE FARM building: rustic open-sided bamboo potting barn with tall asymmetrical thatched roof, small attached translucent glass greenhouse, seedling trays, watering cans and baskets of fresh greens, raised planter beds hugging the foundation. A real farm workyard on a tiny irregular earth footprint, not a retail shop.",{x:0.3278,y:0.3983,width:0.229,height:0.0528,angle:0.3007}),
  homestay:exterior('homestay','Nhà nghỉ homestay',"A cozy HOMESTAY with raised timber stilt cabin upper floor, broad palm-thatch A-frame roof, exterior stair climbing right side, deep veranda with hammock, one reception desk in open ground-level alcove, luggage bench and ferns, bamboo handrails. Asymmetric holiday cabin silhouette, not urban townhouse.",{x:0.3575,y:0.5709,width:0.243,height:0.042,angle:0.0571}),
  pagoda:exterior('pagoda','Chùa',"A beautiful compact Vietnamese Buddhist pagoda: multi-tiered sweeping dark red clay roofs with gently upturned corners, ornate timber carved pillars, open central worship hall, small lateral bell pavilion and incense urn on stone steps, lotus pots and old bonsai; rich traditional sacred architecture, no shop window.",{x:0.3703,y:0.46,width:0.209,height:0.041,angle:0.3375}),
  teacher:exterior('teacher','Lớp học',"A small cheerful Vietnamese schoolhouse with asymmetric red tiled double gables, a tall central clock turret with simple clock face no numerals, pale yellow plaster, wide multi-pane classroom windows, covered timber veranda, outdoor blackboard blank, tiny fenced reading corner with books and a sapling; a real school with wide entrance and stone steps, not a shop.",{x:0.2696,y:0.5085,width:0.195,height:0.044,angle:0.1628}),
  homemaker:exterior('homemaker','Ngôi nhà gia đình',"A charming FAMILY HOME: compact Vietnamese split-level house with broad yellow tiled hip roof, lower side kitchen wing with stove chimney, sheltered front porch with rocking chair, open wood lattice window showing family dining table, vegetable pots and laundry rail at side. Friendly personal house, no storefront displays.",{x:0.2917,y:0.4983,width:0.274,height:0.0463,angle:0.3676}),
  giupviec:exterior('giupviec','Dịch vụ giúp việc',"A household CLEANING service workshop: low blue tiled-roof washhouse with central open service corridor, whitewashed walls, several visible washing machines in side bay, covered outdoor clothesline, yellow janitor cart with folded towels/bucket/mop, separate little supply shed. Functional elongated courtyard composition.",{x:0.2094,y:0.5538,width:0.171,height:0.0512,angle:0.3616}),
  naucom:exterior('naucom','Bếp nấu cơm',"A HOME COOK catering kitchen: small Vietnamese brick courtyard cooking house with two low terracotta shed roofs separated by open air gap, large tiled chimney and three cooking pots, window counter for food containers, outside preparation table with vegetables and a covered clay oven. Kitchen architecture, no dining restaurant.",{x:0.2623,y:0.3657,width:0.254,height:0.0605,angle:0.4416}),
  babysitter:exterior('babysitter','Nhà giữ trẻ',"A neighborhood CHILDCARE cottage: low cream building with three small pastel gabled bays of different widths, scalloped nursery veranda, large round windows, child-height timber gate, covered little sandbox and toy storage by entrance, baby cot visible through open doorway. No children/people, no genericshop.",{x:0.3349,y:0.4179,width:0.307,height:0.064,angle:0.204}),
  salon:exterior('salon','Tiệm tóc',"A stylish Vietnamese HAIR SALON occupying an elegant low Art Nouveau curved-front pavilion. One rounded high copper-green dome over glazed bay, short rectangular flat-roof back wing, tall arched mirrors and two salon chairs visible through enormous front window, maroon barber pole attached facade, little stone entry steps and carefully trimmed pots.",{x:0.4357,y:0.41,width:0.385,height:0.0459,angle:0.061}),
  nail:exterior('nail','Tiệm làm móng',"A small boutique MANICURE studio: low blush-pink rectilinear building with stepped rose terrazzo flat roof terrace and slim brass railing, deeply recessed full-height display window revealing two manicure tables with lamps and nail polish shelves, side curved privacy screen with palms. Narrow one-storeyplusroofterrace, not barberdome.",{x:0.3556,y:0.3556,width:0.428,height:0.0649,angle:0.3142}),
  photobooth:exterior('photobooth','Tiệm chụp ảnh',"A charming photo studio: compact black-and-white cinema-like stepped Art Deco facade, tall semicircular cream entrance arch with maroon curtain, side glass display of blank photo frames, oversized real tripod camera inside the open booth, small print kiosk extension and amber marquee light bulbs (unlit/static). No text.",{x:0.3231,y:0.3674,width:0.393,height:0.064,angle:0.1976}),
  pet_care:exterior('pet_care','Trạm chăm sóc thú cưng',"A cute veterinary pet GROOMING pavilion: low cream stucco building with soft curved coral barrel roof, open washing bay with elevated tub and hose, side fenced covered kennel run, big circular paw-shaped window (architecture not floating icon), towel cabinet and pet carrier by wide entrance. Deliberately different shape from a pet retail shop.",{x:0.2293,y:0.455,width:0.226,height:0.061,angle:0.2956}),
  repair:exterior('repair','Xưởng sửa chữa',"A wide low Vietnamese electronics repair workshop, industrial blue-grey corrugated sawtooth roof, one tall OPEN roller-shutter work bay, raised metal workbench with disassembled fan and radio, pegboard with tools, coils of wire and labeled-free spare parts drawers, small red tool cabinet, side lean-to with a repaired TV. No upper floor, not a retail grocery.",{x:0.3339,y:0.3672,width:0.367,height:0.0601,angle:0.318}),
  pharmacy:exterior('pharmacy','Nhà thuốc',"An Art Deco white and jade pharmacy, asymmetrical stepped flat roof parapet, rounded projecting glazed medicine bay, distinct tall narrow green glass cabinet facade, one small recessed front entrance, antiseptic mint glazed wall tiles, glass medicine shelving visible inside, green medical cross built into side wall architecture (no text). Compact one-floor medical pavilion, no red tiled shop roof.",{x:0.2873,y:0.3906,width:0.32,height:0.062,angle:0.2786}),
  nurse:exterior('nurse','Phòng chăm sóc sức khỏe',"A neighborhood NURSING clinic: low asymmetric white pavilion, curved mint barrel-roof patient ward to left and square consultation entrance to right, wheelchair access ramp, broad frosted medical windows with beds visible inside, shaded ambulance-free dropoff porch and built-in simple green cross. Differentfrompharmacyfrontshop.",{x:0.5685,y:0.3816,width:0.226,height:0.073,angle:0.3812}),
  police:exterior('police','Trạm cảnh sát',"A neighborhood POLICE civic station: sturdy pale yellow single-story courtyard building with central high square gatehouse, blue hip roof, wide welcoming timber door and two side administrative bays, flagpole withoutflag, simple shield relief carved into lintel, benches in frontcourtyard. Real station no genericoffice.",{x:0.432,y:0.451,width:0.203,height:0.0385,angle:0.1789}),
  rescue:exterior('rescue','Trạm cứu hộ',"A maritime rescue coordination station: angular cream and orange observation cabin raised on sturdy stilts above open equipment bay, flat winged roof with radio aerials, broad lookout glazing, exterior stair, red rescue board and life rings fixed under side canopy. Clear emergency sea-rescue architecture, no water.",{x:0.315,y:0.4839,width:0.263,height:0.0532,angle:0.2535}),
  pet_shop:exterior('pet_shop','Cửa hàng thú cưng',"A pet supply shop resembling a low warm timber pet-lodge: double overlapping green shingle gables, broad aquarium display window blue glass along right side, open shelves of pet food tins left, small bird aviary annex and pet bed by front door; playful zigzag roof but believable shop. Distinct from curved pet grooming bath pavilion.",{x:0.3088,y:0.4443,width:0.301,height:0.0626,angle:0.2055}),
  accounting:exterior('accounting','Văn phòng kế toán',"An intimate independent bookkeeping office in a narrow ONE-and-a-half-storey French-Vietnamese timber townhouse: steep charcoal slate mansard roof with one wide dormer, cream lower level with recessed arch entrance, shuttered wood study window with papers and a small abacus visible, little side archive annex and clay pots. Residential scale, no corporate glass box.",{x:0.3637,y:0.4291,width:0.367,height:0.065,angle:0.2}),
  customer_care:exterior('customer_care','Trung tâm chăm sóc khách hàng',"A friendly contemporary customer support CALL CENTER pavilion: rounded horseshoe low roof, teal blue horizontal louver band, bright continuous wraparound windows showing rows of headset operator cubicles, curved reception entrance under a projecting pale yellow cantilever canopy, one communications antenna integrated at rear, round planters. One broad storey, no tiled townhouse.",{x:0.3181,y:0.5007,width:0.263,height:0.057,angle:0.2783}),
  corp_accounting:exterior('corp_accounting','Kế toán doanh nghiệp',"A modern corporate accounting office: asymmetrical THREE-STOREY terraced cream business building with flat green-roof stepbacks, tall central vertical glass atrium, horizontal brass sunshade fins, small public reception porch, rows of work desks visible through ground glazing. Compact corporate HQ, no red tiled roof.",{x:0.2298,y:0.5375,width:0.255,height:0.047,angle:0.2644}),
  tax_payroll:exterior('tax_payroll','Văn phòng thuế và lương',"A civic payroll-and-tax service office: single broad neoclassical cream building with low stone pediment over TWO separate arched service windows, central recessed blue door, short flight of stone steps, archive tower at back with green shutters, shallow grey metal hip roof. Organized civic counters with document trays visible; no generic townhouse.",{x:0.3977,y:0.4716,width:0.329,height:0.058,angle:0.193}),
  group_accounting:exterior('group_accounting','Kế toán tập đoàn',"A financial group consolidation HQ: two slender unequal-height cream office wings bridged by an enclosed glass skybridge above an open ground reception court; dark copper flat roof frames and vertical teal glass strips; abstract three-part structural arrangement, one clear front entry beneath bridge. No logos/numbers.",{x:0.1879,y:0.5449,width:0.171,height:0.0386,angle:0.31}),
  hr_admin:exterior('hr_admin','Văn phòng nhân sự',"A human resources training center: low L-shaped contemporary cream building enclosing a small interview courtyard, sawtooth skylight roof over long training wing, round meeting-room bay at end, wooden benches and file cabinets visible through entrance, green perforated sunshade panels. No generic corporate tower.",{x:0.2012,y:0.4289,width:0.163,height:0.0434,angle:0.4263}),
  secretary:exterior('secretary','Văn phòng thư ký',"An executive reception SECRETARIAT: formal asymmetric two-storey cream villa-office with a tall square corner stair tower, dark red hipped roof, generous columned porte-cochere with reception desk glimpsed through open glass entry, small side mail-sorting annex and a curved stone bench. Differentshape fromlibraryorretail.",{x:0.2904,y:0.5485,width:0.217,height:0.0395,angle:0.2822}),
  it_helpdesk:exterior('it_helpdesk','Trạm hỗ trợ công nghệ',"An IT repair and support lab: compact cube-and-cylinder modern tech workshop, flat charcoal rooftop with ventilation units, projecting teal glass server tower at back right, open front repair bay full of computers and monitor benches, cable conduit and a side rack of network equipment. Cool blue glass with warm cream plaster.",{x:0.3135,y:0.4183,width:0.347,height:0.063,angle:0.288}),
  library:exterior('library','Thư viện',"A public LIBRARY: taller central stone reading hall with arched rooflight and two low gabled book-stack wings, large wood double doors, giant arched windows revealing high bookcases, side reading porch and brass lamps, ivy growing sparingly. Warm cream sandstone and deep teal slate roof, distinct scholarly silhouette.",{x:0.3348,y:0.5745,width:0.18,height:0.0393,angle:0.4341}),
  delivery:exterior('delivery','Bưu trạm giao hàng',"A busy compact parcel-delivery POST DEPOT: wide industrial low roof with two offset red metal pitched sections, open loading bay right, conveyor belt and sorted cardboard parcels inside, small mustard office cube left, a parked compact red delivery scooter integrated under canopy, stack of parcel cages; recognizably logistics yard.",{x:0.2219,y:0.4458,width:0.208,height:0.057,angle:0.4186}),
  pilot:exterior('pilot','Nhà chứa máy bay',"A tiny island AVIATION operations airfield building: narrow round observation control tower attached to low curved corrugated aircraft hangar, wide half-open hangar door revealing nose and propeller of small plane, windsock at roof, small front briefing-room porch. Cream steel and terracotta accents, clearly aviation notstore.",{x:0.253,y:0.6197,width:0.212,height:0.0387,angle:0.2369}),
  flight_attendant:exterior('flight_attendant','Nhà đón tiếp hàng không',"An airport PASSENGER service terminal: low sweeping butterfly-shaped canopy roof on slender cream pillars, broad curved glazed lounge showing airplane cabin training seats, short enclosed jetbridge stub to side, stacked luggage carts outside glass entrance. No control tower/hangar, wide open elegant departure architecture.",{x:0.2286,y:0.4905,width:0.203,height:0.0493,angle:0.3022}),
  oil:exterior('oil','Trạm dầu khí',"An offshore OIL operation miniature platform building: steel ochre deck raised on visible short pylons, tall red-brown lattice derrick off-center, compact blue control cabin, grouped grey pipes and valves, orange safety rails and stairway, thick service tanks. Entire self-contained oil work platform with no ocean/background. No domestic roof.",{x:0.3021,y:0.5307,width:0.203,height:0.0366,angle:0.2685}),
  railway:exterior('railway','Ga đường sắt',"A Vietnamese RAILWAY crossing signal cabin: elevated narrow timber signal box on brick base with exterior staircase, huge wraparound operating windows, steep dark green roof, short rail track section and one raised red-white crossing barrier alongside, visible signal levers inside. Railway architecture, no plane/noairport.",{x:0.4258,y:0.4853,width:0.238,height:0.0362,angle:0.2809}),
  tour_guide:exterior('tour_guide','Nhà hướng dẫn du lịch',"An island tourist-information pavilion: octagonal cream kiosk with copper conical roof, wide open service hatch, attached timber pergola with large physical wall map (abstract unlabeled colored lines) and rack of folded paper maps, viewing telescope beside entrance, trail-direction wooden posts no text. Tourist center, no office tower.",{x:0.3964,y:0.4864,width:0.246,height:0.0492,angle:0.1282}),
  lighthouse:exterior('lighthouse','Hải đăng',"A coastal LIGHTHOUSE keeper complex: tall tapered white stone tower with red horizontal band and green-glass lantern room under copper cap, external spiral balcony, adjoining tiny one-storey keeper cottage with blue metal gable roof and stone garden wall. Tower clearly dominant and whole visible, nobackgroundisland.",{x:0.2628,y:0.6469,width:0.122,height:0.0295,angle:0.26}),
  lifeguard:exterior('lifeguard','Trạm cứu hộ bãi biển',"A pool LIFEGUARD facility: compact open-sided tall timber lifeguard observation chair tower attached to low blue-wave-roof changing cabin, roof-mounted observation binoculars, rack of rescue tubes and floats, little attached rectangle of turquoise swimming-pool edge with ladder. No full giantpool, compactfacility silhouette.",{x:0.2559,y:0.5416,width:0.247,height:0.0432,angle:0.3336}),
  garbage:exterior('garbage','Trạm tái chế',"A tidy neighborhood recycling collection station: three open staggered green-roof sorting bays with large different colored bins, a compact glass-front sorting office, green wheeled handcart, a baler and neatly bundled cardboard under side steel canopy. Clear industrial waste-service equipment, warm illustrated and clean, not gross.",{x:0.2829,y:0.3847,width:0.226,height:0.061,angle:0.3346}),
  drain:exterior('drain','Trạm thoát nước',"A drainage and plumbing repair depot: rugged one-floor cream brick workshop with offset lean-to corrugated roofs, large exposed copper and blue pipes bending around exterior walls, pipe-storage racks, coiled inspection hose and pump trolley by open arch-shaped service door, shallow grated inspection platform.",{x:0.288,y:0.3797,width:0.254,height:0.065,angle:0.1961}),
  tra_da:exterior('tra_da','Quán trà đá',"An open Vietnamese street TEA STALL: no enclosed shop building, large old tree trunk with leafy crown framing a low weathered bamboo lean-to and patched canvas canopy, thermos flasks, glass tea cups on long narrow timber bar, several tiny red plastic stools, stool stack, a chess table at side. Everything in compact sprite, broad airy silhouette.",{x:0.5332,y:0.547,width:0.254,height:0.0518,angle:0.3647}),
  ice_cream:exterior('ice_cream','Quầy kem',"An island ICE CREAM parlor: small cylindrical cream-and-mint pavilion with wide gently undulating pale blue canopy roof, triple glazed serving arches around front, low chilled display cases of pastel scoops, two terrazzo stools and a side freezer kiosk; rounded low shape rather than a townhouse. No floating icecream icon.",{x:0.4557,y:0.4511,width:0.357,height:0.0534,angle:0.038}),
};

export const CAREER_ASSETS:Readonly<Record<string,string>>=Object.fromEntries(Object.values(CAREER_ART).map(a=>[a.key,a.src]));
const careerArtKeys=new Set(Object.keys(CAREER_ASSETS));
export function isCareerArtKey(key:string):boolean{return careerArtKeys.has(key);}

/** A trimmed painting can be rectangular. Only its longest edge is capped.
 * 50 RGBA textures at the maximum dimensions cost 50 MiB; finished art is never
 * duplicated into the legacy career-facade canvas cache. */
export const CAREER_ART_BUDGET={maxEdge:512,maxAssetBytes:256*1024,maxTotalBytes:10*1024*1024,maxDecodedBytes:50*512*512*4} as const;
